### PR TITLE
`azurerm_windows_function_app` node version validation strings.

### LINKED ISSUE #15852: azurerm_windows_function_app sets incorrect WEBSITE_NODE_DEFAULT_VERSION app setting for node
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform v1.1.7 on linux_amd64
* provider registry.terraform.io/hashicorp/azurerm v2.99.0

### Terraform Configuration Files

```hcl
resource "azurerm_windows_function_app" "example" {
  name                = "example-windows-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name = azurerm_storage_account.example.name
  service_plan_id      = azurerm_service_plan.example.id

  site_config {
    application_stack {
      node_version = "14"
    }
  }
}
```

### Description / Feedback
While the function app deploys successfully, myFunc on said funcapp is unable to be invoked due no available language workers:
```
2022-03-16T10:37:59.026 [Information] Executing 'Functions.myFunc' (Reason='(null)', Id=8fb92df8-08f0-4312-b9a9-426b9f3c6a54)
2022-03-16T10:37:59.033 [Information] Trigger Details: PartionId: 0, Offset: 14656-15680, EnqueueTimeUtc: 2022-03-16T10:36:43.6170000+00:00-2022-03-16T10:37:28.8120000+00:00, SequenceNumber: 28-30, Count: 3
2022-03-16T10:38:50.052 [Error] Executed 'Functions.myFunc' (Failed, Id=8fb92df8-08f0-4312-b9a9-426b9f3c6a54, Duration=51141ms)Did not find any initialized language workers
```

Inspecting the app settings for the function app reveals that the provider has set `WEBSITE_NODE_DEFAULT_VERSION` to `14`.

Based on the [function stacks api](https://github.com/Azure/azure-functions-ux/blob/dev/server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts#L81), the correct app settings in this case (Node.js 14, windows runtime) are:
```
                FUNCTIONS_WORKER_RUNTIME: 'node',
                WEBSITE_NODE_DEFAULT_VERSION: '~14',
```

When I change WEBSITE_NODE_DEFAULT_VERSION from 14 to ~14 in the azure portal, the function invokes without error.
Therefore, the provider should set the `WEBSITE_NODE_DEFAULT_VERSION` app setting to `~14` when node_version is 14 (or accept node_version=~14).

Note specifying `site_config.application_stack.node_version = "~14"` leads to the error: `expected site_config.0.application_stack.0.node_version to be one of [12 14], got ~14`
Note WEBSITE_NODE_DEFAULT_VERSION is a setting [specific to windows function apps](https://github.com/Azure/azure-functions-dotnet-worker/issues/556#issuecomment-921180540).
### References

See also this issue: https://github.com/Azure/azure-functions-dotnet-worker/issues/556#issuecomment-920697240

### PR DESCRIPTION
**Pull request by jackofallops**
Also adds support for Node 16 preview.

closes #15852

### CODE REVIEW

**Comment by jackofallops** [comment]
Testing looks fine:

image

File: internal/services/appservice/helpers/function_app_schema.go [hunk 1]
```diff
@@ -1284,8 +1285,9 @@ func windowsFunctionAppStackSchema() *pluginsdk.Schema {
 					Type:     pluginsdk.TypeString,
 					Optional: true,
 					ValidateFunc: validation.StringInSlice([]string{
-						"12",
-						"14",
+						"~12",
+						"~14",
+						"~16",
```
Comment (tombuildsstuff) [inline internal/services/appservice/helpers/function_app_schema.go:1290]: do we need to update the docs too?

**Review by tombuildsstuff — APPROVED** [review]
One comment but this otherwise seems fine 👍
