### PR TITLE
[Bug Fix ] `azurerm_redis_cache` - Support for unsetting  `data_persistence_authentication_method`

### LINKED ISSUE #27878: azurerm_redis_cache: provider says that it will update data_persistence_authentication_method but does not
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.8.0

### Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### Terraform Configuration Files

```hcl
... a configuration not mentioning data_persistence_authentication_method
```

### Debug Output/Panic Output

```shell
# azurerm_redis_cache.treasure will be updated in-place
...
      ~ redis_configuration {
          - data_persistence_authentication_method  = "SAS" -> null
```

### Expected Behaviour

terraform should either make the promised change, or not say that it is going to change it

### Actual Behaviour

after applying and re-applying the state is not changed and terraform continues to say that it will make this update

### Steps to Reproduce

_No response_

### Important Factoids

fallout from #26948, I guess

my resource was created using an earlier version of the provider and this behaviour is new since upgrading

### References

_No response_

### PR DESCRIPTION
**Pull request by xuzhang3**
Support unset `data_persistence_authentication_method`

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27878 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by xuzhang3** [comment]
Failed tests is not relates with this PR.
image

File: internal/services/redis/redis_cache_resource.go [hunk 1]
```diff
@@ -935,29 +935,31 @@ func expandRedisConfiguration(d *pluginsdk.ResourceData) (*redis.RedisCommonProp
...
 	if v := raw["maxmemory_policy"].(string); v != "" {
-		output.MaxmemoryPolicy = utils.String(v)
+		output.MaxmemoryPolicy = pointer.To(v)
 	}
 
 	if v := raw["data_persistence_authentication_method"].(string); v != "" {
-		output.PreferredDataPersistenceAuthMethod = utils.String(v)
+		output.PreferredDataPersistenceAuthMethod = pointer.To(v)
+	} else {
+		output.PreferredDataPersistenceAuthMethod = pointer.To("")
```
Comment (catriona-m) [inline internal/services/redis/redis_cache_resource.go:962]: Would it make sense to replace this with the below since we are now setting it whether or not the string is empty?

`output.PreferredDataPersistenceAuthMethod = pointer.To(raw["data_persistence_authentication_method"].(string))`

**Review by catriona-m — CHANGES_REQUESTED** [review]
Hi @xuzhang3 - I left one minor comment on this but can take another look once it is addressed. Thanks!

File: internal/services/redis/redis_cache_resource.go (hunk 1 above)
Comment (xuzhang3) [reply internal/services/redis/redis_cache_resource.go:962]: @catriona Empty string will be ignore but `null` will be accepted by service

Comment (catriona-m) [reply internal/services/redis/redis_cache_resource.go:962]: I believe this should still be ok as it won't be sent in the payload if it is null

Comment (xuzhang3) [reply internal/services/redis/redis_cache_resource.go]: Updated

**Review by catriona-m — APPROVED** [review]
Thanks @xuzhang3 LGTM!
