### PR TITLE
`azurerm_synapse_workspace` - Fix nilpointer for `sql_aad_admin`

### LINKED ISSUE #14272: The terraform-provider-azurerm_v2.86.0_x5.exe plugin crashed!
While attempting to deploy azurerm_synapse_workspace using terraform version `1.0.11`, I get the error below:

```
module.synapse.azurerm_synapse_workspace.workspace: Still creating... [9m40s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with module.synapse.azurerm_synapse_workspace.workspace,
│   on ..\..\tf-mod-az-synapse-workspace\main.tf line 81, in resource "azurerm_synapse_workspace" "workspace":
│   81: resource "azurerm_synapse_workspace" "workspace" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.86.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x500505b]

goroutine 297 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/synapse.resourceSynapseWorkspaceCreate(0x0, {0x5470360, 0xc000835180})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/synapse/synapse_workspace_resource.go:433 +0x175b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc002a982a0, {0x6505128, 0xc002ac5ac0}, 0x2, {0x5470360, 0xc000835180})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000cb0e00, {0x6505128, 0xc002ac5ac0}, 0xc002af4750, 0xc0011ae700, {0x5470360, 0xc000835180})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000005c38, {0x6505128, 0xc002ac5ac0}, 0xc000c3f310)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000c2d6c0, {0x65051d0, 0xc002aea690}, 0x8)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5994480, 0xc000c2d6c0}, {0x65051d0, 0xc002aea690}, 0xc0020f9140, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000220700, {0x65546c0, 0xc001338000}, 0xc002aee7e0, 0xc00101c2d0, 0xaa45440, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000220700, {0x65546c0, 0xc001338000}, 0xc002aee7e0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.86.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Please assist.

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #14272

- [x] Acceptance Test for Synapse AAD Admin and Synapse SQL AAD Admin

### CODE REVIEW

File: internal/services/synapse/synapse_workspace_resource.go [hunk 1]
```diff
@@ -430,7 +430,7 @@ func resourceSynapseWorkspaceCreate(d *pluginsdk.ResourceData, meta interface{})
 
 	sqlAdmin := expandArmWorkspaceAadAdmin(d.Get("sql_aad_admin").([]interface{}))
```
Comment (aristosvo) [inline internal/services/synapse/synapse_workspace_resource.go:431]: It would probably need an `expandArmWorkspaceAadAdmin` function to expand here properly

**Review by aristosvo — COMMENTED** [review]
It's not enough to fix just that reference

**Comment by aristosvo** [comment]
```bash
 TF_ACC=1 go test -v ./internal/services/synapse -run=TestAccSynapseWorkspace_update -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccSynapseWorkspace_update
=== PAUSE TestAccSynapseWorkspace_update
=== CONT  TestAccSynapseWorkspace_update
--- PASS: TestAccSynapseWorkspace_update (962.88s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/synapse
```

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2021-11-22 at 11 25 53
