### PR TITLE
`azurerm_container_group` - Supports CMK with user assigned identity

### LINKED ISSUE #23305: Error when deploying azurerm_container_group with CMK using key_vault_key_id setting
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.0

### AzureRM Provider Version

3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_container_group

### Terraform Configuration Files

```hcl
resource "azurerm_container_group" "azure_ci" {
  name = lower("ci-${var.abv_location}-${var.env}-${var.current_index}-${var.service}")
 
  location            = var.location
  resource_group_name = var.resource_group_name
  ip_address_type     = "Private"
  os_type             = "Linux"
  tags                = var.tags
  key_vault_key_id    = var.key_vault_key_id
  zones               = var.zones
  subnet_ids          = [var.ci_subnet_id]
 
  dynamic "container" {
    for_each = var.container
 
    content {
      name   = lower("${var.abv_location}-${var.env}-${container.key}-${var.service}")
      image  = container.value.image
      cpu    = container.value.cpu
      memory = container.value.memory
 
      ports {
        port     = container.value.port
        protocol = container.value.protocol
      }
 
      dynamic "volume" {
        for_each = var.create_volume ? [1] : []
 
        content {
          name       = lower("${var.abv_location}-${var.env}-${container.key}-${var.service}-${container.value.vol_name}")
          mount_path = container.value.vol_path
          read_only  = container.value.vol_read_only
          share_name = container.value.vol_share
 
          storage_account_name = container.value.vol_stg_name
          storage_account_key  = container.value.vol_stg_primary_key
        }
      }
 
      environment_variables        = container.value.ci_env
      secure_environment_variables = container.value.ci_env_pvt
 
    }
  }
 
  dynamic "image_registry_credential" {
    for_each = var.image_registry_credential.server == "" ? [] : [1]
    content {
      username                  = var.image_registry_credential.username == null ? null : var.image_registry_credential.username
      password                  = var.image_registry_credential.password == null ? null : var.image_registry_credential.password
      user_assigned_identity_id = var.image_registry_credential.user_assigned_identity_id == null ? null : var.image_registry_credential.user_assigned_identity_id
      server                    = var.image_registry_credential.server
    }
  }
 
  identity {
    type         = var.identity.type
    identity_ids = var.identity.identity_ids
  }
 
  diagnostics {
    log_analytics {
      workspace_id  = var.log_analytics_workspace_workspace_id
      workspace_key = var.log_analytics_workspace_key
    }
  }
}
```

### Debug Output/Panic Output

```shell
{

    "status": "Failed",

    "error": {

        "code": "InternalServerError",

        "message": "Encountered an internal server error. The tracking activity id is 'cc386ab1-e5a8-4f34-b518-43d65d0c45c9', correlation id is 'ca2c32c5-ec39-471e-b94f-1f8f988fbe02'."

    }

}
```

### Expected Behaviour

Deploy the resource with CMK and linked to the specified KV.

### Actual Behaviour

A generic error is given:

```
{

    "status": "Failed",

    "error": {

        "code": "InternalServerError",

        "message": "Encountered an internal server error. The tracking activity id is 'cc386ab1-e5a8-4f34-b518-43d65d0c45c9', correlation id is 'ca2c32c5-ec39-471e-b94f-1f8f988fbe02'."

    }

}
```

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by magodo**
This PR adds a new property `key_vault_user_identity_id` to `azurerm_container_group` to support CMK with user assigned identity.

Fix #23305.

### CODE REVIEW

File: internal/services/containers/container_group_resource.go [hunk 1]
```diff
@@ -942,6 +952,12 @@ func resourceContainerGroupRead(d *pluginsdk.ResourceData, meta interface{}) err
 				return err
 			}
 			d.Set("key_vault_key_id", keyId.ID())
+
+			var uai string
+			if kvProps.Identity != nil {
+				uai = *kvProps.Identity
+			}
+			d.Set("key_vault_user_identity_id", uai)
```
Comment (stephybun) [inline internal/services/containers/container_group_resource.go:960]: This can become
```suggestion
			d.Set("key_vault_user_identity_id", pointer.From(kvProps.Identity))
```

File: website/docs/r/container_group.html.markdown [hunk 2]
```diff
@@ -99,6 +99,8 @@ The following arguments are supported:
 
 * `key_vault_key_id` - (Optional) The Key Vault key URI for CMK encryption. Changing this forces a new resource to be created.
 
+* `key_vault_user_identity_id` - (Optional) The user assigned identity that has access to the Key Vault Key. If not specified, the RP principal named "Azure Container Instance Service" will be used instead. Make sure the identity has the proper `key_permissions` set, at least with `Get`, `UnwrapKey`, `WrapKey` and `GetRotationPolicy`.
```
Comment (stephybun) [inline website/docs/r/container_group.html.markdown:102]: The ordering of the sentences here is a little confusing, are the `key_permissions` that are needed for the RP Principal or for `key_vault_user_identity_id`? Or both?

File: internal/services/containers/container_group_resource.go [hunk 3]
```diff
@@ -553,6 +553,12 @@ func resourceContainerGroup() *pluginsdk.Resource {
 				ForceNew:     true,
 				ValidateFunc: keyVaultValidate.NestedItemId,
 			},
+
+			"key_vault_user_identity_id": {
```
Comment (stephybun) [inline internal/services/containers/container_group_resource.go:557]: Currently the identity properties for CMK are inconsistent across the provider, some are called `identity_id`, `primary_user_assigned_identity_id`  or `user_assigned_identity_id`. We might want to consider standardising these for the next major release and having a `commonschema` for them like we do for identities.

All this to say, I think for the time being this might benefit from being called `key_vault_user_assigned_identity_id` since it's clear at first glance what type of ID it is and is also closer to what we currently have in the provider.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this @magodo. I left a few suggestions in-line. Could you please take a look at them? Thanks!

File: website/docs/r/container_group.html.markdown (hunk 2 above)
Comment (magodo) [reply website/docs/r/container_group.html.markdown:102]: It should be both identities.

File: internal/services/containers/container_group_resource.go (hunk 3 above)
Comment (magodo) [reply internal/services/containers/container_group_resource.go:557]: Renamed.

File: internal/services/containers/container_group_resource.go (hunk 1 above)
Comment (magodo) [reply internal/services/containers/container_group_resource.go]: Sure, I'll change it.

**Comment by magodo** [comment]
@stephybun Thank you for the review! I've changed the code per your comment, please take another look!

**Review by stephybun — APPROVED** [review]
Thanks for this @magodo LGTM 💯
