### PR TITLE
`azurerm_storage_account` - `infrastructure_encryption_enabled` supports premium `FileStorage`

### LINKED ISSUE #20013: Storage Account Infrastructure Encryption and Premium/FileStorage
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6-1.3.6

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "stg" {
  name = "storageaccountname"
  resource_group_name = "test-rg"
  location = "southcentralus"
  access_tier = “Hot”
  account_kind = “FileStorage”
  account_replication_type = “ZRS”
  account_tier = “Premium”
  infrastructure_encryption_enabled = true
}
```

### Debug Output/Panic Output

```shell
module.storage_account["st4"].azurerm_storage_account.stg: Creating...
Error: `infrastructure_encryption_enabled` can only be used with account kind `StorageV2`, or account tier `Premium` and account kind `BlockBlobStorage`
  with module.storage_account["st4"].azurerm_storage_account.stg,
  on .terraform/modules/storage_account/module.tf line 5, in resource "azurerm_storage_account" "stg":
   5: resource "azurerm_storage_account" "stg" {
ERROR: Job failed: command terminated with exit code 1
```

### Expected Behaviour

Storage Account should be deployed with Terraform with account_tier as Premium and account_kind as FileStorage when infrastructure_encryption_enabled is set to true.

### Actual Behaviour

Error: `infrastructure_encryption_enabled` can only be used with account kind `StorageV2`, or account tier `Premium` and account kind `BlockBlobStorage`

### Steps to Reproduce

Create Storage Account with account_kind FileStorage and account_tier Premium with infrastructure_encryption_enabled true.

`resource "azurerm_storage_account" "stg" {
  name = "storageaccountname"
  resource_group_name = "test-rg"
  location = "southcentralus"
  access_tier = “Hot”
  account_kind = “FileStorage”
  account_replication_type = “ZRS”
  account_tier = “Premium”
  infrastructure_encryption_enabled = true
}`

Then run
`terraform plan
terraform apply`

### Important Factoids

I am able to manually create the Storage Account with the same settings using Azure CLI and Azure Portal without any issues at all.

### References

Similar to https://github.com/hashicorp/terraform-provider-azurerm/issues/15512

### PR DESCRIPTION
**Pull request by magodo**
Fix #20013

I've also tried the premuim `BlobStorage`, the API returns an error in this case. Interestingly, the Portal allows you to use premium `BlobStorage` and enable the infra encrpytion in the UI, but the request will silently use `StorageV2` at the end.

## Test

```shell
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/storage -run=TestAccStorageAccount_infrastructureEncryption
=== RUN   TestAccStorageAccount_infrastructureEncryption
=== PAUSE TestAccStorageAccount_infrastructureEncryption
=== CONT  TestAccStorageAccount_infrastructureEncryption
--- PASS: TestAccStorageAccount_infrastructureEncryption (336.55s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       336.558s
```

### CODE REVIEW

File: internal/services/storage/storage_account_resource.go [hunk 1]
```diff
@@ -1282,9 +1282,9 @@ func resourceStorageAccountCreate(d *pluginsdk.ResourceData, meta interface{}) e
 	infrastructureEncryption := d.Get("infrastructure_encryption_enabled").(bool)
 
 	if infrastructureEncryption {
-		if !((accountTier == string(storage.SkuTierPremium) && accountKind == string(storage.KindBlockBlobStorage)) ||
+		if !((accountTier == string(storage.SkuTierPremium) && (accountKind == string(storage.KindBlockBlobStorage)) || accountKind == string(storage.KindFileStorage)) ||
 			(accountKind == string(storage.KindStorageV2))) {
-			return fmt.Errorf("`infrastructure_encryption_enabled` can only be used with account kind `StorageV2`, or account tier `Premium` and account kind `BlockBlobStorage`")
+			return fmt.Errorf("`infrastructure_encryption_enabled` can only be used with account kind `StorageV2`, or account tier `Premium` and account kind is one of `BlockBlobStorage` and `FileStorage`")
```
Comment (jackofallops) [inline internal/services/storage/storage_account_resource.go:1287]:
```suggestion
			return fmt.Errorf("`infrastructure_encryption_enabled` can only be used with account kind `StorageV2`, or account tier `Premium` and account kind is one of `BlockBlobStorage` or `FileStorage`")
```

File: website/docs/r/storage_account.html.markdown [hunk 2]
```diff
@@ -159,7 +159,7 @@ The following arguments are supported:
 
 * `infrastructure_encryption_enabled` - (Optional) Is infrastructure encryption enabled? Changing this forces a new resource to be created. Defaults to `false`.
 
--> **NOTE:** This can only be `true` when `account_kind` is `StorageV2` or when `account_tier` is `Premium` *and* `account_kind` is `BlockBlobStorage`.
+-> **NOTE:** This can only be `true` when `account_kind` is `StorageV2` or when `account_tier` is `Premium` *and* `account_kind` is one of `BlockBlobStorage` and `FileStorage`.
```
Comment (jackofallops) [inline website/docs/r/storage_account.html.markdown:162]:
```suggestion
-> **NOTE:** This can only be `true` when `account_kind` is `StorageV2` or when `account_tier` is `Premium` *and* `account_kind` is one of `BlockBlobStorage` or `FileStorage`.
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @magodo 
Thanks for this PR.  It looks mostly good, just a couple of minor amendments I'd like you to take a look at in-line below.

Thanks!

**Comment by magodo** [comment]
@jackofallops Thank you for the review! I've resolved the comments and passed the test:

```shell
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/storage -run=TestAccStorageAccount_infrastructureEncryption
=== RUN   TestAccStorageAccount_infrastructureEncryptionStorageV2
=== PAUSE TestAccStorageAccount_infrastructureEncryptionStorageV2
=== RUN   TestAccStorageAccount_infrastructureEncryptionFileStorage
=== PAUSE TestAccStorageAccount_infrastructureEncryptionFileStorage
=== RUN   TestAccStorageAccount_infrastructureEncryptionBlockBlobStorage
=== PAUSE TestAccStorageAccount_infrastructureEncryptionBlockBlobStorage
=== CONT  TestAccStorageAccount_infrastructureEncryptionStorageV2
=== CONT  TestAccStorageAccount_infrastructureEncryptionBlockBlobStorage
=== CONT  TestAccStorageAccount_infrastructureEncryptionFileStorage
--- PASS: TestAccStorageAccount_infrastructureEncryptionFileStorage (153.98s)
--- PASS: TestAccStorageAccount_infrastructureEncryptionBlockBlobStorage (154.02s)
--- PASS: TestAccStorageAccount_infrastructureEncryptionStorageV2 (293.23s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       293.245s
```

**Review by katbyte — APPROVED** [review]
LGTM 📂
