### PR TITLE
`azurerm_cdn_frontdoor_origin_group` - hack SDK to allow `health_probe` to be passed as `null`

### LINKED ISSUE #19585: `azurerm_cdn_frontdoor_origin_group`  - Health probe can't be removed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.34.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_origin_group

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_profile" "frontdoor_profile" {
  name                = "frontdoortest20221206"
  resource_group_name = data.azurerm_resource_group.existing_rsg.name
  sku_name            = "Standard_AzureFrontDoor"
}

resource "azurerm_cdn_frontdoor_origin_group" "frontdoor_origin_group" {
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.frontdoor_profile.id
  name                     = "frontdoororigingroup"

  health_probe { # Remove this section after creation to observe the issue
    interval_in_seconds = 240
    path                = "/healthProbe"
    protocol            = "Https"
    request_type        = "HEAD"
  }

  load_balancing {
    additional_latency_in_milliseconds = 0
    sample_size                        = 16
    successful_samples_required        = 3
  }
}
```

### Debug Output/Panic Output

```shell
  # azurerm_cdn_frontdoor_origin_group.frontdoor_origin_group will be updated in-place
  ~ resource "azurerm_cdn_frontdoor_origin_group" "frontdoor_origin_group" {
        id                                                        = "/subscriptions/4cedc5dd-e3ad-468d-bf66-32e31bdb9148/resourceGroups/1-ffc3bbe0-playground-sandbox/providers/Microsoft.Cdn/profiles/frontdoortest20221206/originGroups/frontdoororigingroup"
        name                                                      = "frontdoororigingroup"
        # (3 unchanged attributes hidden)

      - health_probe {
          - interval_in_seconds = 240 -> null
          - path                = "/healthProbe" -> null
          - protocol            = "Https" -> null
          - request_type        = "HEAD" -> null
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**For full debug output please see [https://gist.github.com/jamesryanuk/ccfe70a4d0e0fb6380845724e4a20fdd](https://gist.github.com/jamesryanuk/ccfe70a4d0e0fb6380845724e4a20fdd)**

### Expected Behaviour

The health probe should be disabled

### Actual Behaviour

1. The health probe is not disabled, despite the output saying "Apply complete! Resources: 0 added, 1 changed, 0 destroyed.". 
2. The next time `terraform apply` is run the output is the same

### Steps to Reproduce

1. Create both `azurerm_cdn_frontdoor_profile` and `azurerm_cdn_frontdoor_origin_group` using the code above
3. Remove the `health_probe` block
4. Run `terraform apply`

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by WodansSon**
(fixes #19585)

### CODE REVIEW

**Comment by WodansSon** [comment]
image

File: internal/services/cdn/azuresdkhacks/cdn_frontdoor_origin_group.go [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+	// SessionAffinityState - Whether to allow session affinity on this host. Valid options are 'Enabled' or 'Disabled'. Possible values include: 'EnabledStateEnabled', 'EnabledStateDisabled'
+	SessionAffinityState cdn.EnabledState `json:"sessionAffinityState,omitempty"`
+}
+
+// MarshalJSON is the custom marshaler for AFDOriginGroupUpdatePropertiesParameters.
+func (ogupp AFDOriginGroupUpdatePropertiesParameters) MarshalJSON() ([]byte, error) {
+	objectMap := make(map[string]interface{})
+	if ogupp.LoadBalancingSettings != nil {
+		objectMap["loadBalancingSettings"] = ogupp.LoadBalancingSettings
+	}
```
Comment (tombuildsstuff) [inline internal/services/cdn/azuresdkhacks/cdn_frontdoor_origin_group.go:121]: presumably this is also the case for loadBalancingSettings here too?

**Review by tombuildsstuff — APPROVED** [review]
One question but this otherwise LGTM 👍

File: internal/services/cdn/azuresdkhacks/cdn_frontdoor_origin_group.go (hunk 1 above)
Comment (WodansSon) [reply internal/services/cdn/azuresdkhacks/cdn_frontdoor_origin_group.go:121]: Good question, but I do not believe it will be needed for the loadBalancingSettings since it is a required field and has default values for the attributes within the code block. On a side note, it appears that the loadBalincingSettings are mostly used by the Health Probes to evaluate the quickest route to the nearest backend pool. So going out on a limb here, if you disable the health probes the loadBalincingSettings are ignored?
