### PR TITLE
azurerm_mssql_elasticpool - Fix for creating hyperscale elastic pool of type MOPRMS and PRMS

### LINKED ISSUE #27908: azurerm_mssql_elasticpool - Unable to create hyperscale epool
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.8.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_elasticpool

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_elasticpool" "mssql_epool" { 
  name                = var.epool_name
  resource_group_name = var.epool_rg_name
  location            = var.location
  server_name         = var.server_name
  license_type        = var.license_type 
  max_size_gb         = var.max_size_gb

  sku {
    name     = "HS_PRMS"
    tier     = "Hyperscale"
    family   = "PRMS"
    capacity = 4
  }

  per_database_settings {
    min_capacity = 0
    max_capacity = 4
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: 1 error occurred:
│       * service tier 'Hyperscale' PRMS must have a 'capacity'(4) of  vCores
│ 
│ 
│ 
│   with module.mssql-epool.azurerm_mssql_elasticpool.mssql_epool,
│   on ../modules/mssql_epool/module.tf line 1, in resource "azurerm_mssql_elasticpool" "mssql_epool":
│    1: resource "azurerm_mssql_elasticpool" "mssql_epool" { 
│ 
╵
```

### Expected Behaviour

Hyperscale PRMS elasticpool created with 4vCores

### Actual Behaviour

Terraform plan fails with 

╷
│ Error: 1 error occurred:
│       * service tier 'Hyperscale' PRMS must have a 'capacity'(4) of  vCores

### Steps to Reproduce

Run terraform plan with the following sku configuration

  sku {
    name     = "HS_PRMS"
    tier     = "Hyperscale"
    family   = "PRMS"
    capacity = 4
  }

### Important Factoids

N/A

### References

_No response_

### PR DESCRIPTION
**Pull request by mkohn**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
This PR adds the ability to leverage Memory Optimized Premium 

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

  # module.hyperscale1.azurerm_mssql_elasticpool.sql will be updated in-place
  ~ resource "azurerm_mssql_elasticpool" "sql" {
        id                             = "/subscriptions/xxxxxxxxx/resourceGroups/xxxxx-xxxx-xxxx/providers/Microsoft.Sql/servers/xxxxxxx/elasticPools/xxxx-xxx-xxxx-Prm1"
        name                           = "xxxxxx-xxxxx-xxxxx-Prm1"
        # (8 unchanged attributes hidden)

      ~ sku {
          ~ family   = "PRMS" -> "MOPRMS"
          ~ name     = "HS_PRMS" -> "HS_MOPRMS"
            # (2 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

For state migrations please test the changes locally and provide details here, such as the versions involved in testing the migration path. For further details on testing state migration changes please see our guide on [state migrations](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-state-migrations.md#testing) in the contributor documentation. -->

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_mssql_elasticpool` - adding support for the Sku MOPRMS and PRMS

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27908

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/mssql/helper/elasticpool.go [hunk 1]
```diff
@@ -201,34 +201,52 @@ var getvCoreMaxGB = map[string]map[string]map[int]float64{
...
+			16:  128000,
+			18:  128000,
+			20:  128000,
+			24:  128000,
+			32:  128000,
+			40:  128000,
+			64:  128000,
+			80:  128000,
+			128: 128000,
+		},
```
Comment (stephybun) [inline internal/services/mssql/helper/elasticpool.go:234]: I don't believe these should be changed to some arbitrary maximum value

File: internal/services/mssql/helper/elasticpool.go [hunk 2]
```diff
@@ -201,34 +201,52 @@ var getvCoreMaxGB = map[string]map[string]map[int]float64{
...
+			12: 128000,
+			14: 128000,
+			16: 128000,
+			18: 128000,
+			20: 128000,
+			24: 128000,
+			32: 128000,
+			40: 128000,
+			64: 128000,
+			80: 128000,
```
Comment (stephybun) [inline internal/services/mssql/helper/elasticpool.go:249]: Same here, we should be setting meaningful values here. The Azure documentation should probably have some information on what the values of these should be.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @mkohn. I'm not able to reproduce the problem described in the issue that these changes are supposed to fix. 

Looking through our PR history it appears #28178 should have closed #27908 and went out in v4.13.0 of the provider.

We're happy to add support for additional sku's though, would you mind resolving the comments I left in-line on that?

File: internal/services/mssql/helper/elasticpool.go (hunk 1 above)
Comment (mkohn) [reply internal/services/mssql/helper/elasticpool.go:234]: @stephybun They are not set to arbitrary maximum value. They are set to 128TB see https://learn.microsoft.com/en-us/azure/azure-sql/database/resource-limits-vcore-single-databases?view=azuresql#hyperscale---provisioned-compute---gen5 for more details.

File: internal/services/mssql/helper/elasticpool.go (hunk 2 above)
Comment (mkohn) [reply internal/services/mssql/helper/elasticpool.go:249]: @stephybun They are not set to arbitrary maximum value. They are set to 128TB see https://learn.microsoft.com/en-us/azure/azure-sql/database/resource-limits-vcore-single-databases?view=azuresql#hyperscale---provisioned-compute---gen5 for more details.

**Review by stephybun — APPROVED** [review]
Thanks for the supporting links @mkohn LGTM 👍
