### PR TITLE
`storage` - add support for `storage_account_id` to `azurerm_storage_container` and `azurerm_storage_share`

### LINKED ISSUE #2977: Cannot create azurerm_storage_container in azurerm_storage_account that uses network_rules
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11
+ provider.azurerm v1.21.0

### Affected Resource(s)

* `azurerm_storage_account`
* `azurerm_storage_container`

### Terraform Configuration Files

```
resource "azurerm_storage_account" "test-storage-acct" {
  name                     = "${var.prefix}storacct"
  resource_group_name      = "${var.resgroup}"
  location                 = "${var.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  network_rules {
    ip_rules                   = ["aaa.bbb.ccc.ddd/ee"]
    virtual_network_subnet_ids = ["${var.subnetid}"]
  }
}
resource "azurerm_storage_container" "provisioning" {
  name                  = "${var.prefix}-provisioning"
  resource_group_name   = "${var.resgroup}"
  storage_account_name  = "${azurerm_storage_account.test-storage-acct.name}"
  container_access_type = "private"
}
```

### Debug Output

* azurerm_storage_container.provisioning: Error creating container "philtesting1-provisioning" in storage account "philtesting1storacct": storage: service returned error: StatusCode=403, ErrorCode=AuthorizationFailure, ErrorMessage=This request is not authorized to perform this operation.
RequestId:a7f9d2e1-701e-00b3-4e74-cf3b34000000
Time:2019-02-28T14:45:53.7885750Z, RequestInitiated=Thu, 28 Feb 2019 14:45:53 GMT, RequestId=a7f9d2e1-701e-00b3-4e74-cf3b34000000, API Version=, QueryParameterName=, QueryParameterValue=

### Expected Behavior

Container can be created in a storage account that uses network rules

### Actual Behavior

After applying a network_rule to a storage account I cannot provision a container into it.  My public IP is included in the address range specified in the network rule.  I can successfully create the container via the Azure portal

### Steps to Reproduce

1. `terraform apply`

### LINKED ISSUE #27607: Failed to create containers when provisioned azure storage account has configured PE and network acl
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.7

### AzureRM Provider Version

4.0.1

### Affected Resource(s)/Data Source(s)

Containers of Azure Storage account

### Terraform Configuration Files

```hcl
required_providers{
 azurerm = {
  source = "hasicorp/azurerm"
  version = "4.0.1"

}

}
```

### Debug Output/Panic Output

```shell
024-10-10T06:40:54.883Z [ERROR] provider.terraform-provider-azurerm_v4.0.1_x5: Response contains error diagnostic: diagnostic_severity=ERROR
  diagnostic_summary=
  | retrieving static website properties for Storage Account (Subscription: "xxx"
  | Resource Group Name: "xx"
  | Storage Account Name: "xx"): executing request: Get "https://xx.blob.core.windows.net/?comp=properties&restype=service": context deadline exceeded
```

### Expected Behaviour

the containers should be created successfully after provisioning the storage account

### Actual Behaviour

storage account was provisioned successfully but containers were failed to be created with the error in the debug log above. It keeps retrieving static website properties which was not used at all in the client terraform.

We have also tested successfully with similar terraform whereby if the provisioned storage account has public access enabled without PE + network acl, both account and containers are successfully provisioned without issues.

### Steps to Reproduce

1. use azurerm version "4.0.1" in the provider file
2. have 2 modules - one to provisioning storage account with PE + network acl
3. the other module to provisioning containers after account was created successfully.

### Important Factoids

N.A.

### References

Found similar Github issue but failed to succeed it by using azapi:
https://github.com/hashicorp/terraform-provider-azurerm/issues/2977

### PR DESCRIPTION
**Pull request by jackofallops**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR introduces the `storage_account_id` to supersede the `storage_account_name` property into `azurerm_storage_container` and `azurerm_storage_share`. This allows the provider to create and manage these resources via the Resource Manager API rather than the Data Plane. 
Existing resources using the `storage_account_name` property cannot be migrated directly, but can be removed and re-imported using the Resource Manager ID type.

The `storage_account_name` property is now deprecated in both resources and will be removed in v5.0 of the provider.

The `resource_manager_id` property is now deprecated in both resources and will be removed in v5.0 of the provider, this value is available as `id` in resources using `storage_account_id`. 

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_storage_container` - support for the `storage_account_id` property
* `azurerm_storage_share` - support for the `storage_account_id` property

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Closes #2977 
_NOTE: please see #27818 and #27819 for other issues that ended up being tracked/associated with the original issue._ 
Closes #27607 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/storage/storage_container_resource.go [hunk 1]
```diff
@@ -185,145 +275,249 @@ func resourceStorageContainerCreate(d *pluginsdk.ResourceData, meta interface{})
...
+	id, err := commonids.ParseStorageContainerID(d.Id())
 	if err != nil {
-		return fmt.Errorf("building Containers Client: %v", err)
+		return err
 	}
 
-	if err = client.Delete(ctx, id.ContainerName); err != nil {
-		return fmt.Errorf("deleting %s: %v", id, err)
+	if _, err := containerClient.Delete(ctx, *id); err != nil {
+		return fmt.Errorf("deleting %q: %v", d.Id(), err)
```
Comment (stephybun) [inline internal/services/storage/storage_container_resource.go:520]:
```suggestion
		return fmt.Errorf("deleting %s: %v", id, err)
```

File: internal/services/storage/storage_container_resource_test.go [hunk 2]
```diff
@@ -35,7 +56,56 @@ func TestAccStorageContainer_basic(t *testing.T) {
 	})
 }
 
+func TestAccStorageContainer_complete(t *testing.T) {
```
Comment (stephybun) [inline internal/services/storage/storage_container_resource_test.go:59]: Should this also be renamed since it's being skipped?
```suggestion
func TestAccStorageContainer_completeDeprecated(t *testing.T) {
```

File: internal/services/storage/storage_container_resource_test.go [hunk 3]
```diff
@@ -35,7 +56,56 @@ func TestAccStorageContainer_basic(t *testing.T) {
...
+	if features.FivePointOhBeta() {
+		t.Skip("skipping as test is not valid in 5.0")
+	}
+
+	data := acceptance.BuildTestData(t, "azurerm_storage_container", "test")
+	r := StorageContainerResource{}
+
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.complete(data),
```
Comment (stephybun) [inline internal/services/storage/storage_container_resource_test.go:69]: Here too?
```suggestion
			Config: r.completeDeprecated(data),
```

File: internal/services/storage/storage_container_resource_test.go [hunk 4]
```diff
@@ -202,6 +433,19 @@ func TestAccStorageContainer_web(t *testing.T) {
...
+		if err != nil {
+			return nil, err
+		}
+		existing, err := client.Storage.ResourceManager.BlobContainers.Get(ctx, *id)
+		if err != nil {
+			return nil, fmt.Errorf("retrieving %s: %+v", id, err)
+		}
+
+		return pointer.To(existing.Model != nil), nil
+	}
```
Comment (stephybun) [inline internal/services/storage/storage_container_resource_test.go:447]: I think this also wants to have the behaviour split using `!features.FivePointOhBeta` so that it's clear post 5.0 what can and needs to be removed when we clean up 
```suggestion
	if !features.FivePointOhBeta() {
		// the old dance here
	}
	
	id, err := commonids.ParseStorageContainerID(state.ID)
	if err != nil {
		return nil, err
	}
	existing, err := client.Storage.ResourceManager.BlobContainers.Get(ctx, *id)
	if err != nil {
		return nil, fmt.Errorf("retrieving %s: %+v", id, err)
	}

	return pointer.To(existing.Model != nil), nil
```

File: internal/services/storage/storage_container_resource_test.go [hunk 5]
```diff
@@ -225,7 +469,7 @@ func (r StorageContainerResource) Exists(ctx context.Context, client *clients.Cl
 		return nil, fmt.Errorf("retrieving Container %q in %s: %+v", id.ContainerName, id.AccountId, err)
 	}
 
-	return utils.Bool(prop != nil), nil
+	return pointer.To(prop != nil), nil
 }
 
 func (r StorageContainerResource) Destroy(ctx context.Context, client *clients.Client, state *pluginsdk.InstanceState) (*bool, error) {
```
Comment (stephybun) [inline internal/services/storage/storage_container_resource_test.go:475]: Does this also need some special treatment?

File: internal/services/storage/storage_share_data_source.go [hunk 6]
```diff
@@ -74,74 +79,133 @@ func dataSourceStorageShare() *pluginsdk.Resource {
...
+				"storage_account_name",
+				"storage_account_id",
+			},
+			ValidateFunc: commonids.ValidateStorageAccountID,
+		}
+
+		r.Schema["resource_manager_id"] = &pluginsdk.Schema{
+			Type:       pluginsdk.TypeString,
+			Computed:   true,
+			Deprecated: "this property has been deprecated in favour of id and will be removed in version 5.0 of the Provider.",
```
Comment (stephybun) [inline internal/services/storage/storage_share_data_source.go:108]:
```suggestion
			Deprecated: "this property has been deprecated in favour of `id` and will be removed in version 5.0 of the Provider.",
```

File: internal/services/storage/storage_share_data_source.go [hunk 7]
```diff
@@ -74,74 +79,133 @@ func dataSourceStorageShare() *pluginsdk.Resource {
...
+		}
 	}
+
+	return r
 }
 
 func dataSourceStorageShareRead(d *pluginsdk.ResourceData, meta interface{}) error {
 	storageClient := meta.(*clients.Client).Storage
```
Comment (stephybun) [inline internal/services/storage/storage_share_data_source.go:116]: Declare this within the `!features.FivePointOhBeta` block?

File: internal/services/storage/storage_share_resource.go [hunk 8]
```diff
@@ -25,13 +32,17 @@ import (
...
 		Update: resourceStorageShareUpdate,
 		Delete: resourceStorageShareDelete,
 
 		Importer: helpers.ImporterValidatingStorageResourceId(func(id, storageDomainSuffix string) error {
+			if strings.HasPrefix(id, "/subscriptions") {
+				_, err := fileshares.ParseShareID(id)
+				return err
+			}
 			_, err := shares.ParseShareID(id, storageDomainSuffix)
 			return err
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:47]: I think we should use the `!features.FivePointOhBeta` flag here to steer the behaviour so it's clear what can be removed post 5.0

File: internal/services/storage/storage_share_resource.go [hunk 9]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
+	if !features.FivePointOhBeta() {
+		r.Schema["storage_account_name"] = &pluginsdk.Schema{
+			Type:     pluginsdk.TypeString,
+			Optional: true,
+			ForceNew: true,
+			ExactlyOneOf: []string{
+				"storage_account_name",
+				"storage_account_id",
+			},
+			Deprecated: "This property has been deprecated and will be replaced by 'storage_account_id' in version 5.0 of the provider.",
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:163]: I think all other deprecation messages begin with lower case, can we be consistent?

File: internal/services/storage/storage_share_resource.go [hunk 10]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
+			ExactlyOneOf: []string{
+				"storage_account_name",
+				"storage_account_id",
+			},
+		}
+
+		r.Schema["resource_manager_id"] = &pluginsdk.Schema{
+			Type:       pluginsdk.TypeString,
+			Computed:   true,
+			Deprecated: "this property is deprecated and will be removed 5.0 and replaced by the 'id' property.",
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:179]:
```suggestion
			Deprecated: "this property is deprecated and will be removed 5.0 and replaced by the `id` property.",
```

File: internal/services/storage/storage_share_resource.go [hunk 11]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
+
+		r.Schema["storage_account_id"] = &pluginsdk.Schema{
+			Type:     pluginsdk.TypeString,
+			Optional: true,
+			ForceNew: true,
+			ExactlyOneOf: []string{
+				"storage_account_name",
+				"storage_account_id",
+			},
+		}
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:174]: Should these also have `Computed` set on them?

File: internal/services/storage/storage_share_resource.go [hunk 12]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
+			Computed:   true,
+			Deprecated: "this property is deprecated and will be removed 5.0 and replaced by the 'id' property.",
+		}
+	}
+
+	return r
 }
 
 func resourceStorageShareCreate(d *pluginsdk.ResourceData, meta interface{}) error {
 	storageClient := meta.(*clients.Client).Storage
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:187]: Declare this in the `!features.FivePointOhBeta` block?

File: internal/services/storage/storage_share_resource.go [hunk 13]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
 
-	if err = client.Create(ctx, shareName, input); err != nil {
+	pollerType := custompollers.NewStorageShareCreatePoller(sharesClient, id, payload)
+	poller := pollers.NewPoller(pollerType, 5*time.Second, pollers.DefaultNumberOfDroppedConnectionsToAllow)
+
+	if err = poller.PollUntilDone(ctx); err != nil {
 		return fmt.Errorf("creating %s: %v", id, err)
 	}
 
 	d.SetId(id.ID())
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:311]: Not sure if I've overlooked it, but we're not setting the `acl` property in the new RM behaviour for storage shares and it hasn't been deprecated

File: internal/services/storage/storage_share_resource.go [hunk 14]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
 
-	if err = client.UpdateACLs(ctx, shareName, shares.SetAclInput{SignedIdentifiers: acls}); err != nil {
-		return fmt.Errorf("setting ACLs for %s: %v", id, err)
-	}
-
 	return resourceStorageShareRead(d, meta)
 }
 
 func resourceStorageShareRead(d *pluginsdk.ResourceData, meta interface{}) error {
 	storageClient := meta.(*clients.Client).Storage
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:316]: Declare this in the `!features.FivePointOhBeta` block below?

File: internal/services/storage/storage_share_resource.go [hunk 15]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
-	props, err := client.Get(ctx, id.ShareName)
+	existing, err := sharesClient.Get(ctx, *id, fileshares.DefaultGetOperationOptions())
 	if err != nil {
-		return err
+		if response.WasNotFound(existing.HttpResponse) {
+			log.Printf("[DEBUG] %q was not found, removing from state", *id)
+			d.SetId("")
+			return nil
+		}
+		return fmt.Errorf("retrieving %q: %v", *id, err)
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:392]:
```suggestion
		return fmt.Errorf("retrieving %s: %v", *id, err)
```

File: internal/services/storage/storage_share_resource.go [hunk 16]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
 	}
-	if props == nil {
-		log.Printf("[DEBUG] File Share %q was not found in %s - assuming removed & removing from state", id.ShareName, account.StorageAccountId)
-		d.SetId("")
-		return nil
+
+	d.Set("storage_account_id", commonids.NewStorageAccountID(id.SubscriptionId, id.ResourceGroupName, id.StorageAccountName).ID())
+
+	if model := existing.Model; model != nil {
+		d.Set("name", id.ShareName)
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:398]: Since we have this information in the `id` and it's not dependent on whether model is `nil` or not we should probably set this outside of this block

File: internal/services/storage/storage_share_resource.go [hunk 17]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
+			d.Set("metadata", FlattenMetaData(pointer.From(props.Metadata)))
+		}
 	}
 
-	d.Set("name", id.ShareName)
-	d.Set("storage_account_name", id.AccountId.AccountName)
-	d.Set("quota", props.QuotaGB)
-	d.Set("url", id.ID())
-	d.Set("enabled_protocol", string(props.EnabledProtocol))
+	d.Set("resource_manager_id", id.ID())
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:413]:
```suggestion
	if !features.FivePointOhBeta() {
		d.Set("resource_manager_id", id.ID())
	}
	
```

File: internal/services/storage/storage_share_resource.go [hunk 18]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
+		return fmt.Errorf("locating Storage Account %q", id.StorageAccountName)
 	}
-	d.Set("access_tier", accessTier)
 
-	if err := d.Set("acl", flattenStorageShareACLs(props.ACLs)); err != nil {
-		return fmt.Errorf("flattening `acl`: %+v", err)
+	// Determine the file endpoint, so we can build a data plane ID
+	endpoint, err := account.DataPlaneEndpoint(client.EndpointTypeFile)
+	if err != nil {
+		return fmt.Errorf("determining File endpoint: %v", err)
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:426]: Shouldn't we **not** be using any Data Plane functionality here?

File: internal/services/storage/storage_share_resource.go [hunk 19]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
-		return fmt.Errorf("flattening `metadata`: %+v", err)
+	// Parse the file endpoint as a data plane account ID
+	accountId, err := accounts.ParseAccountID(*endpoint, storageClient.StorageDomainSuffix)
+	if err != nil {
+		return fmt.Errorf("parsing Account ID: %v", err)
 	}
 
-	resourceManagerId := parse.NewStorageShareResourceManagerID(account.StorageAccountId.SubscriptionId, account.StorageAccountId.ResourceGroupName, account.StorageAccountId.StorageAccountName, "default", id.ShareName)
-	d.Set("resource_manager_id", resourceManagerId.ID())
+	// TODO Giovanni Deprecation - Port the storage data plane ID helper(s) from Giovanni to go-azure-sdk so we can remove this
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:435]: Which helpers specifically, the ones above? all of them?

File: internal/services/storage/storage_share_resource.go [hunk 20]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
+	id, err := fileshares.ParseShareID(d.Id())
 	if err != nil {
 		return err
 	}
 
-	account, err := storageClient.FindAccount(ctx, subscriptionId, id.AccountId.AccountName)
+	existing, err := sharesClient.Get(ctx, *id, fileshares.DefaultGetOperationOptions())
 	if err != nil {
-		return fmt.Errorf("retrieving Account %q for Share %q: %v", id.AccountId.AccountName, id.ShareName, err)
+		return fmt.Errorf("retrieving %q: %v", *id, err)
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:535]:
```suggestion
		return fmt.Errorf("retrieving %s: %v", *id, err)
```

File: internal/services/storage/storage_share_resource.go [hunk 21]
```diff
@@ -143,239 +150,424 @@ func resourceStorageShare() *pluginsdk.Resource {
...
 	}
 
-	// The files API does not support bearer tokens (@manicminer, 2024-02-15)
-	client, err := storageClient.FileSharesDataPlaneClient(ctx, *account, storageClient.DataPlaneOperationSupportingOnlySharedKeyAuth())
-	if err != nil {
-		return fmt.Errorf("building File Share Client for %s: %+v", account.StorageAccountId, err)
+	props := model.Properties
+	if props == nil {
+		return fmt.Errorf("retrieving %s: properties is nil", id)
 	}
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:546]: Same remark here regarding these checks which we typically only do if we need to patch an existing model to use for the `CreateOrUpdate` call

File: internal/services/storage/storage_share_resource.go [hunk 22]
```diff
@@ -384,39 +576,75 @@ func resourceStorageShareUpdate(d *pluginsdk.ResourceData, meta interface{}) err
...
+		return err
 	}
 
-	// The files API does not support bearer tokens (@manicminer, 2024-02-15)
-	client, err := storageClient.FileSharesDataPlaneClient(ctx, *account, storageClient.DataPlaneOperationSupportingOnlySharedKeyAuth())
-	if err != nil {
-		return fmt.Errorf("building File Share Client for %s: %+v", account.StorageAccountId, err)
+	if resp, err := fileSharesClient.Delete(ctx, *id, fileshares.DefaultDeleteOperationOptions()); err != nil {
+		if !response.WasNotFound(resp.HttpResponse) {
+			return fmt.Errorf("deleting %q: %v", id, err)
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:634]:
```suggestion
			return fmt.Errorf("deleting %s: %v", id, err)
```

File: internal/services/storage/storage_share_resource.go [hunk 23]
```diff
@@ -384,39 +576,75 @@ func resourceStorageShareUpdate(d *pluginsdk.ResourceData, meta interface{}) err
...
+		}
 	}
 
-	if err = client.Delete(ctx, id.ShareName); err != nil {
-		if strings.Contains(err.Error(), "The specified share does not exist") {
-			return nil
+	if resp, err := fileSharesClient.Get(ctx, *id, fileshares.DefaultGetOperationOptions()); err != nil {
+		if !response.WasNotFound(resp.HttpResponse) {
+			return fmt.Errorf("deleting %q: %v", id, err)
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:640]:
```suggestion
			return fmt.Errorf("deleting %s: %v", id, err)
```

File: internal/services/storage/storage_share_resource.go [hunk 24]
```diff
@@ -384,39 +576,75 @@ func resourceStorageShareUpdate(d *pluginsdk.ResourceData, meta interface{}) err
...
 	subscriptionId := meta.(*clients.Client).Account.SubscriptionId
+	fileSharesClient := meta.(*clients.Client).Storage.ResourceManager.FileShares
 	ctx, cancel := timeouts.ForDelete(meta.(*clients.Client).StopContext, d)
 	defer cancel()
 
-	id, err := shares.ParseShareID(d.Id(), storageClient.StorageDomainSuffix)
-	if err != nil {
-		return err
+	if !features.FivePointOhBeta() {
+		if strings.HasPrefix(d.Id(), "/subscriptions/") {
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:584]: Same comment here about squishing the conditions together like we do for the Create/Update/Read

File: internal/services/storage/storage_share_resource.go (hunk 23 above)
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:640]: Why do we need to perform a get after deleting it?

File: internal/services/storage/storage_share_resource_test.go [hunk 25]
```diff
@@ -264,6 +552,19 @@ func TestAccStorageShare_protocolUpdate(t *testing.T) {
 }
 
 func (r StorageShareResource) Exists(ctx context.Context, client *clients.Client, state *pluginsdk.InstanceState) (*bool, error) {
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource_test.go:554]: Can we use the `!features.FivePointOhBeta` flag here to control the correct behaviour

File: website/docs/r/storage_share.html.markdown [hunk 26]
```diff
@@ -89,9 +93,9 @@ A `access_policy` block supports the following:
 
 ~> **Note:** Permission order is strict at the service side, and permissions need to be listed in the order above.
 
-* `start` - (Optional) The time at which this Access Policy should be valid from, in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format.
+* `start` - (Optional) The time at which this Access Policy should be valid from. When using `storage_account_id` this should be in RFC3339 format. If using the deprecated `storage_account_name` property, this uses the [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format.
 
-* `expiry` - (Optional) The time at which this Access Policy should be valid until, in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format.
+* `expiry` - (Optional) The time at which this Access Policy should be valid untilWhen using `storage_account_id` this should be in RFC3339 format. If using the deprecated `storage_account_name` property, this uses the [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format.
```
Comment (stephybun) [inline website/docs/r/storage_share.html.markdown:98]: Will we have broken this behaviour since we added `RFC3339` validation onto those properties in the resource?

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @jackofallops.

Thinking ahead for when we make this breaking change in 5.0, would we be able to add a state migration for this so that users don't need to remove and re-import this into their state?

File: internal/services/storage/storage_share_resource.go (hunk 11 above)
Comment (jackofallops) [reply internal/services/storage/storage_share_resource.go:174]: In the case one is configured, the other will never have a value as they are mutually exclusive. the schema in `azurerm_storage_container` is incorrectly marked as `Computed`, I'll remove that.

File: internal/services/storage/storage_share_resource.go (hunk 18 above)
Comment (jackofallops) [reply internal/services/storage/storage_share_resource.go:426]: This is unfortunately still necessary due to a dependency on `giovanni` until that functionality is ported to `go-azure-sdk`. This doesn't actually make any external calls to the data plane, should be fine to be used here until for now.

File: internal/services/storage/storage_share_resource.go (hunk 19 above)
Comment (jackofallops) [reply internal/services/storage/storage_share_resource.go:435]: Ultimately yes, we need to deprecate the use of Giovanni completely, but that work is outside the scope of this PR.

File: website/docs/r/storage_share.html.markdown (hunk 26 above)
Comment (jackofallops) [reply website/docs/r/storage_share.html.markdown:98]: RFC3339 and ISO8601 are compatible in the Go `time` package and both pass the validation function. Tests are passing locally for both value formats.

File: internal/services/storage/storage_container_resource_test.go (hunk 2 above)
Comment (jackofallops) [reply internal/services/storage/storage_container_resource_test.go:59]: Copy-paste error, this is a new test and should not have been skipped.

File: internal/services/storage/storage_share_resource.go [hunk 27]
```diff
@@ -384,39 +572,55 @@ func resourceStorageShareUpdate(d *pluginsdk.ResourceData, meta interface{}) err
 func resourceStorageShareDelete(d *pluginsdk.ResourceData, meta interface{}) error {
 	storageClient := meta.(*clients.Client).Storage
```
Comment (stephybun) [inline internal/services/storage/storage_share_resource.go:573]: Declare this in the `!features.FivePointOhBeta` block below?

**Review by stephybun — COMMENTED** [review]
Thanks @jackofallops LGTM 🐈‍⬛

**Review by stephybun — APPROVED** [review]

**Comment by jackofallops** [comment]
Tests look good:
image
