### PR TITLE
`azurerm_machine_learning_compute_instance` - allow empty `subnet_resource_id` with managed networking

### LINKED ISSUE #27866: azurerm_machine_learning_compute_instance subnet_resource_id should be optional, even though node_public_ip_enabled is false
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

3.116.0

### Affected Resource(s)/Data Source(s)

azurerm_machine_learning_compute_instance

### Terraform Configuration Files

```hcl
resource "azurerm_machine_learning_compute_instance" "compute_instance" {
  name                          = var.default_compute_cluster_name
  machine_learning_workspace_id = azurerm_machine_learning_workspace.mlworkspace[0].id
  virtual_machine_size          = "STANDARD_D2S_V3"

  node_public_ip_enabled        = false
  local_auth_enabled            = false

  assign_to_user {
    object_id = data.azuread_users.mlworkspace_users.users[0].object_id
    tenant_id = data.azurerm_client_config.current.tenant_id
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
Error: `subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false`
```

### Expected Behaviour

Since we are in a private networking scenario with a Managed VNET I don't have to provide the subnetid in the Azure MLW UI.
I have created a compute instance manually in my scenario via Azure UI and it says subnetid NULL and "enableNodePublicIp": false

Very same issue resolved for compute cluster here: https://github.com/hashicorp/terraform-provider-azurerm/issues/25901

### Actual Behaviour

Error: `subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false`

### Steps to Reproduce

Setup AML in a manged network

resource "azurerm_machine_learning_workspace" "mlworkspace" {
  resource_group_name      = azurerm_resource_group.rg.name
  location                             = var.general_location
  name                                 = local.mlworkspace_name
  key_vault_id                       = azurerm_key_vault.keyvault.id
  storage_account_id           = azurerm_storage_account.storage_mlworkspace[0].id
  application_insights_id      = azurerm_application_insights.mlworkspace[0].id
  container_registry_id         = azurerm_container_registry.acr[0].id
  public_network_access_enabled = false

  managed_network {
    isolation_mode = "AllowInternetOutbound"
  }

  identity {
    type = "SystemAssigned"
  }
}

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by wyattfry**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR changes the validation of the `subnet_resource_id` property so it matches Azure's validation.

In Azure, associating compute workspaces with a vnet/subnet **is optional** in the following circumstance:
1. Has no public IP exposed (`node_public_ip_enabled` is set to `false`)
2. Is using a managed network (meaning in Terraform, its `isolation_mode` is **not** `Disabled`, or in Azure portal, its "outbound traffic" setting is "public")

However, the validation in the provider does respect condition number 2 and **incorrectly requires** a vnet/subnet when the workspace has no public IP but is using a managed network.

This PR changes the validation such that before requiring a vnet/subnet, it checks whether the associated workspace is using a managed network. Only if it is not using one will it then require a vnet/subnet.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_machine_learning_compute_instance` - allow empty `subnet_resource_id` with managed networking [GH-29811]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27866

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by Haricharan0310** [comment]
Hi @Username, I noticed you’ve been keeping docs up-to-date, always good to see.

I built a small LLM-based tool for maintaining high-level docs (SDK guides, API references, READMEs, tutorials). It auto-updates them on PRs to prevent drift.

No pressure at all, but thought it might be useful: https://github.com/marketplace/deepdocsai

**Comment by Haricharan0310** [comment]
Hi @Username, I noticed you’ve been keeping docs up-to-date, always good to see.

I built a small LLM-based tool for maintaining high-level docs (SDK guides, API references, READMEs, tutorials). It auto-updates them on PRs to prevent drift.

No pressure at all, but thought it might be useful: https://github.com/marketplace/deepdocsai

File: internal/services/machinelearning/machine_learning_compute_instance_resource_test.go [hunk 1]
```diff
@@ -375,3 +390,76 @@ resource "azurerm_machine_learning_workspace" "test" {
...
+  key_vault_id                  = azurerm_key_vault.test.id
+  storage_account_id            = azurerm_storage_account.test.id
+  public_network_access_enabled = true
+  identity {
+    type = "SystemAssigned"
+  }
+  managed_network {
+    # Ensure the compute instance can be created without public IP and without subnet
+    # as long as its parent workspace is using a managed network
+    isolation_mode = "AllowInternetOutbound"
```
Comment (wyattfry) [inline internal/services/machinelearning/machine_learning_compute_instance_resource_test.go:452]: Can't use `template` because `template` does not use a managed network.

File: internal/services/machinelearning/machine_learning_compute_instance_resource.go [hunk 2]
```diff
@@ -317,7 +322,26 @@ func resourceComputeInstanceRead(d *pluginsdk.ResourceData, meta interface{}) er
...
+			workspace, err := meta.(*clients.Client).MachineLearning.Workspaces.Get(ctx, workspaceId)
+			if err != nil {
+				return err
+			}
+			if workspace.Model == nil {
+				return fmt.Errorf("machine learning %s Workspace: model is nil", id)
+			}
+			if workspace.Model.Location == nil {
+				return fmt.Errorf("machine learning %s Workspace: model `Location` is nil", id)
+			}
```
Comment (sreallymatt) [inline internal/services/machinelearning/machine_learning_compute_instance_resource.go]: Since we're not accessing `workspace.Model.Location` in the read function, I think we can remove it

File: website/docs/r/machine_learning_compute_instance.html.markdown [hunk 3]
```diff
@@ -118,7 +118,9 @@ The following arguments are supported:
 
 * `subnet_resource_id` - (Optional) Virtual network subnet resource ID the compute nodes belong to. Changing this forces a new Machine Learning Compute Instance to be created.
 
-* `node_public_ip_enabled` - (Optional) Whether the compute instance will have a public ip. To set this to false a `subnet_resource_id` needs to be set. Defaults to `true`. Changing this forces a new Machine Learning Compute Cluster to be created.
+* `node_public_ip_enabled` - (Optional) Whether the compute instance will have a public ip. Defaults to `true`. Changing this forces a new Machine Learning Compute Cluster to be created.
+
+-> **Note:** if `node_public_ip_enabled` is set to `false`, and the instance's parent workspace is not using a managed network (i.e. the workspace's outbound isolation mode is `Disabled`), then `subnet_resource_id` must be set.
```
Comment (sreallymatt) [inline website/docs/r/machine_learning_compute_instance.html.markdown]: Nit: I think this should be a warning note (since if not followed this will lead to an error from Terraform)

```suggestion
~> **Note:** if `node_public_ip_enabled` is set to `false`, and the instance's parent workspace is not using a managed network (i.e. the workspace's outbound isolation mode is `Disabled`), then `subnet_resource_id` must be set.
```

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Thanks @wyattfry, I've left 2 comments inline, once those are reviewed I can take another look!

File: internal/services/machinelearning/machine_learning_compute_instance_resource.go (hunk 2 above)
Comment (sreallymatt) [reply internal/services/machinelearning/machine_learning_compute_instance_resource.go]: Actually, looking at this again, since we're in the read we would probably want to avoid returning errors where possible. Are these checks all required? It may be better to make subnet_resource_id a Computed property if Azure returns it when the workspace has isolation_mode set to Disabled

Comment (wyattfry) [reply internal/services/machinelearning/machine_learning_compute_instance_resource.go]: Great idea. I've updated it so that if anything errors, instead of returning the error, it defaults to persisting the subnet ID to state.

I'd like to avoid Optional Computed if possible; and I think it's ok to leave it Optional because in Azure Portal, instances made with managed networking do not expose their networking information (even though it is in the REST API). In fact, Azure creates the vnet/subnet in a hidden resource group that is not visible via Portal.

**Review by sreallymatt — APPROVED** [review]
Thanks @wyattfry LGTM ✅
