### PR TITLE
`azurerm_static_site_custom_domain` - make `validation_type` optional

### LINKED ISSUE #15837: Importing azurerm_static_site_custom_domain resource fails to set validation_type, leading to resource replacement
<!---
Please note the following potential times when an issue might be in Terraform core:

* [Configuration Language](https://www.terraform.io/docs/configuration/index.html) or resource ordering issues
* [State](https://www.terraform.io/docs/state/index.html) and [State Backend](https://www.terraform.io/docs/backends/index.html) issues
* [Provisioner](https://www.terraform.io/docs/provisioners/index.html) issues
* [Registry](https://registry.terraform.io/) issues
* Spans resources across multiple providers

If you are running into one of these scenarios, we recommend opening an issue in the [Terraform core repository](https://github.com/hashicorp/terraform/) instead.
--->

<!--- Please keep this note for the community --->

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

<!--- Thank you for keeping this note for the community --->

### Terraform (and AzureRM Provider) Version

<!--- Please run `terraform -v` to show the Terraform core version and provider version(s). If you are not running the latest version of Terraform or the provider, please upgrade because your issue may have already been fixed. [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions). --->
* Terraform v1.1.7 on linux_amd64
* provider registry.terraform.io/hashicorp/azurerm v2.95.0

### Affected Resource(s)

<!--- Please list the affected resources and data sources. --->

* `azurerm_static_site_custom_domain`

### Terraform Configuration Files

<!--- Information about code formatting: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code --->

```hcl
variable "resource_group_name" {}

data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

resource "azurerm_static_site" "spa" {
  name                = "mySpa"
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location
  sku_tier            = "Free"
}

resource "azurerm_static_site_custom_domain" "spa" {
  static_site_id  = azurerm_static_site.spa.id
  domain_name     = "example.com"
  validation_type = "cname-delegation"
}
```

### Debug Output
```bash
❯ terraform import 'azurerm_static_site_custom_domain.spa[0]' /subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/staticSites/mySpa/customDomains/example.com                                  
azurerm_static_site_custom_domain.spa[0]: Importing from ID "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/staticSites/mySpa/customDomains/example.com"...                                                        
azurerm_static_site_custom_domain.spa[0]: Import prepared!                                                                                        
  Prepared azurerm_static_site_custom_domain for import                                                                                                        
azurerm_static_site_custom_domain.spa[0]: Refreshing state... [id=/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/staticSites/mySpa/customDomains/example.com]                                                      
                                                                                                                                                               
Import successful!                                                                                                                                             
                                                                                                                                                               
The resources that were imported are shown above. These resources are now in                                                                                   
your Terraform state and will henceforth be managed by Terraform.                                                                                              
```

<!---
Please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
--->

### Panic Output

<!--- If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`. --->

### Expected Behaviour

<!--- What should have happened? --->
The resource is imported in a complete state.

### Actual Behaviour

<!--- What actually happened? --->
The resource is imported partially,  with `validation_type` not set. This the resource state after the import:
```json
    {
      "mode": "managed",
      "type": "azurerm_static_site_custom_domain",
      "name": "spa",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 0,
          "attributes": {
            "domain_name": "example.com",
            "id": "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/staticSites/mySpa/customDomains/example.com",
            "static_site_id": "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/staticSites/mySpa",
            "timeouts": {
              "create": null,
              "delete": null,
              "read": null,
              "update": null
            },
            "validation_token": "",
            "validation_type": null
          },
          "sensitive_attributes": [],
          "private": "REDACTED"
        }
      ]
    },
```
Note that `validation_type` is set to null.

Whenever terraform creates a new plan after the import, it proposes to replace the imported resource:
```
Terraform will perform the following actions:

  # azurerm_static_site_custom_domain.spa[0] must be replaced
-/+ resource "azurerm_static_site_custom_domain" "spa" {
      ~ id               = "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/staticSites/mySpa/customDomains/example.com" -> (known after apply)  
      + validation_token = (sensitive value)
      + validation_type  = "cname-delegation" # forces replacement
        # (2 unchanged attributes hidden)

      - timeouts {}                     
    }                                   

Plan: 1 to add, 0 to change, 1 to destroy.

```

### Steps to Reproduce

<!--- Please list the steps required to reproduce the issue. --->

1. Provision just the SWA from terraform
2. Provision custom domain from another tool (e.g. azure portal)
3. Import custom domain resource into terraform (see above)
4. Run `terraform plan`

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: Running in a Azure China/Germany/Government? --->

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
--->

* #0000

### PR DESCRIPTION
**Pull request by magodo**
This is to allow the imported `azurerm_static_site_custom_domain` not suffering force replacement issue.

Fixes #15837.

### CODE REVIEW

File: internal/services/web/static_site_custom_domain_resource.go [hunk 1]
```diff
@@ -55,7 +55,7 @@ func resourceStaticSiteCustomDomain() *pluginsdk.Resource {
 
 			"validation_type": {
 				Type:     pluginsdk.TypeString,
-				Required: true,
+				Optional: true,
```
Comment (tombuildsstuff) [inline internal/services/web/static_site_custom_domain_resource.go:58]: rather than doing this - we should instead update the Import function to set this field based on the value from the config

Comment (magodo) [reply internal/services/web/static_site_custom_domain_resource.go:58]: @tombuildsstuff During the import, you don't have access to the config (i.e. `d.GetRawConfig` returns a cty value whose internal value is `nil`). Also, this is the same case for `terraform-plugin-framework`, where the `tfsdk.ImportResourceStateRequest` only export the identifier which users have specified in the CLI. If we change the resource id into form like `<azure resource id>:<validation type>`, then it should work. However, this seems weired.

Comment (tombuildsstuff) [reply internal/services/web/static_site_custom_domain_resource.go:58]: @magodo we do this just fine in some other resources, it depends what's in the config at the time of import

Comment (magodo) [reply internal/services/web/static_site_custom_domain_resource.go:58]: I'm assuming you mean [this](https://github.com/hashicorp/terraform-provider-azurerm/blob/17f5ffefefccde9e163ef6315b923459d99a403a/internal/services/loganalytics/log_analytics_storage_insights_resource.go#L38-L47). But if I have following import code:

```go
Importer: pluginsdk.ImporterValidatingResourceIdThen(
	func(id string) error {
		_, err := parse.StaticSiteCustomDomainID(id)
		return err
	},
	func(ctx context.Context, d *pluginsdk.ResourceData, meta interface{}) ([]*pluginsdk.ResourceData, error) {
		v := d.Get("validation_type")
		_ = v
		cfg := d.GetRawConfig()
		_ = cfg
		return []*pluginsdk.ResourceData{d}, nil
	},
),
```

And have following config in the workspace:

```hcl
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-220316110941683707"
  location = "WestEurope"
}
resource "azurerm_static_site" "test" {
  name                = "acctestSS-220316110941683707"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}
resource "azurerm_static_site_custom_domain" "test" {
  static_site_id  = azurerm_static_site.test.id
  domain_name     = "ranran2.biz"
  validation_type = "dns-txt-token"
}
```

Then inspect at the last line of the `Importer`, I get:

image

Comment (magodo) [reply internal/services/web/static_site_custom_domain_resource.go:58]: @fvdnabee Yes, for the terraform framwork SDK, it is clearly documented: https://www.terraform.io/plugin/framework/resources#read

Comment (fvdnabee) [reply internal/services/web/static_site_custom_domain_resource.go:58]: Thank you for that link @magodo, reading the tf  config during import appears to be documented as unsupported indeed.

Considering `validation_type` is not part of the state of the SWA customDomain Azure resource state [1], should it be tracked as part of the terraform state? Couldn't it be removed from the TF state altogether? 

Once the domain is available, it seems irrelevant whether it was validated via a CNAME record or TXT record (and Azure  appears to not be tracking the validation_type; see [1]). If the domain validation fails, then the custom domain resource fails to be created; so on the next tf apply it would be recreated and the provider can just read the validation_type from the config again. validation_type also does not seem to impact resource destruction. Maybe the validation type can just be read from the config when creating/updating the resource and it could be removed from the tf state? I'm unsure if this is feasible in the provider however.

[1] this is what azurerm returns for an active custom domain; note the validation type is not tracked:
```json
❯ az rest -m get -u 'https://management.azure.com//subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/staticSites/stapp-d-10007318-0/customDomains/example.com?api-version=2021-02-01'
{
  "id": "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/staticSites/stapp-d-10007318-0/customDomains/example.com",
  "location": "West Europe",
  "name": "example.com",
  "properties": {
    "createdOn": "2022-03-14T15:49:02.5454741",
    "domainName": "example.com",
    "isDefault": false,
    "status": "Ready"
  },
  "type": "Microsoft.Web/staticSites/customDomains"
}
```

Comment (magodo) [reply internal/services/web/static_site_custom_domain_resource.go:58]: @fvdnabee Thanks for the clarification! Given the `validation_type` is not returned in GET, hence we didn't set it to state in read. In case the custom domain is created via Terraform, it is still set in the state during create as it is in the config. On the other hand, if it is imported, then the state will never have `validation_type`, which means you shouldn't specify it in the config as well, to avoid the diff.

That said, the `validation_type` is only useful during creation, and should be ignored in other cases. So one solution is to make the `validation_type` optional, but still mark it as required in the document to indicate that it is required during create, as this PR did. Another way to workaround this is to use the `ignore_chanages` to explicitly ignore it after you imported it.

Comment (fvdnabee) [reply internal/services/web/static_site_custom_domain_resource.go:58]: @magodo could you clarify the following:
> In case the custom domain is created via Terraform, it is still set in the state during create as it is in the config.

This is a necessary requirement for terraform providers? Including the validation type in the resource creation request forces us to track it as part of the TF state? I understand it is impossible (or bad practice?) to include parameters in the resource creation request that are sourced from the TF config without them being tracked in the TF state. 

I like the optional `validation_type` idea for importing (then it wouldn't be part of the TF state), but when creating a custom domain resourced it should indeed be clear that validation_type is a required argument. Is it possible to enforce this in the provider (i.e. `validation_type` is mandatory when creating the resource; if `validation_type` is absent during creation the provider throws an error)?

Comment (magodo) [reply internal/services/web/static_site_custom_domain_resource.go:58]: Yes, [provider will fail if `validation_type` is not set in creation](https://github.com/hashicorp/terraform-provider-azurerm/pull/15849/files/17f5ffefefccde9e163ef6315b923459d99a403a#diff-b88d11ab9071d8d0d231342a9df82a63f622ea3aed7344c17d87dd23ebc2b3cbR105-R107).

For the reason why it is set in the state during creation, it is how the plugin SDKv2 works. The values in the config will be in the state if don't explicitly change them.

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍
