### PR TITLE
`azurerm_recovery_services_vault` - support direct creation with immutability `locked`

### LINKED ISSUE #23792: Upstream Azure API error unable to create azurerm_recovery_services_vault with immutability locked
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.77

### Affected Resource(s)/Data Source(s)

azurerm_recovery_services_vault

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

locals {
  location  = "eastus"
  name      = "backup-test"
}

resource "azurerm_resource_group" "resource_group" {
  location = local.location
  name     = format("rg-%s", local.name)
}

resource "azurerm_recovery_services_vault" "recovery_vault" {
  name                = format("rsv-%s", local.name)
  location            = local.location
  resource_group_name = azurerm_resource_group.resource_group.name
  immutability        = "Locked"
  sku                 = "Standard"
}
```

### Debug Output/Panic Output

```shell
Vault Name: "rsv-backup-test"): performing CreateOrUpdate: unexpected status 400 with error: UserErrorUnsupportedVaultImmutabilityStateChange: The immutable vault property for this vault is locked, hence, this setting cannot be disabled. The vault has its immutable vault property enabled and locked, and it can no longer be reverted to a non-immutable vault. Refer to the documentation to learn more: https://aka.ms/AB-ImmutableVaults-States
```

### Expected Behaviour

Recovery Vault is created

### Actual Behaviour

No vault is created and error is thrown

### Steps to Reproduce

terraform init
terraform apply

It is not a terraform issue but one of the Azure CLI.  It can also be reproduced running the command: 
`az backup vault create --location eastus --name rsv-backup-test --resource-group rg-backup-test --immutability-state Locked`

The workaround is to create the vault first unlocked and then reapply the configuration with the vault locked.  Documenting here so it can be linked to a Microsoft API issue, thank

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ziyeqf**
fix #23792

test
---
```
❯ tftest recoveryservices TestAccRecoveryServicesVault   
=== RUN   TestAccRecoveryServicesVault_basic
=== PAUSE TestAccRecoveryServicesVault_basic
=== RUN   TestAccRecoveryServicesVault_ToggleCrossRegionRestore
=== PAUSE TestAccRecoveryServicesVault_ToggleCrossRegionRestore
=== RUN   TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType
=== PAUSE TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType
=== RUN   TestAccRecoveryServicesVault_zrs
=== PAUSE TestAccRecoveryServicesVault_zrs
=== RUN   TestAccRecoveryServicesVault_complete
=== PAUSE TestAccRecoveryServicesVault_complete
=== RUN   TestAccRecoveryServicesVault_update
=== PAUSE TestAccRecoveryServicesVault_update
=== RUN   TestAccRecoveryServicesVault_requiresImport
=== PAUSE TestAccRecoveryServicesVault_requiresImport
=== RUN   TestAccRecoveryServicesVault_SystemAssignedIdentity
=== PAUSE TestAccRecoveryServicesVault_SystemAssignedIdentity
=== RUN   TestAccRecoveryServicesVault_UserAssignedIdentity
=== PAUSE TestAccRecoveryServicesVault_UserAssignedIdentity
=== RUN   TestAccRecoveryServicesVault_immutabilityLocked
=== PAUSE TestAccRecoveryServicesVault_immutabilityLocked
=== RUN   TestAccRecoveryServicesVault_immutability
=== PAUSE TestAccRecoveryServicesVault_immutability
=== RUN   TestAccRecoveryServicesVault_softDelete
=== PAUSE TestAccRecoveryServicesVault_softDelete
=== RUN   TestAccRecoveryServicesVault_storageModeType
=== PAUSE TestAccRecoveryServicesVault_storageModeType
=== RUN   TestAccRecoveryServicesVault_crossRegionRestore
=== PAUSE TestAccRecoveryServicesVault_crossRegionRestore
=== RUN   TestAccRecoveryServicesVault_CrossRegionRestoreWithEncryption
=== PAUSE TestAccRecoveryServicesVault_CrossRegionRestoreWithEncryption
=== RUN   TestAccRecoveryServicesVault_sku
=== PAUSE TestAccRecoveryServicesVault_sku
=== RUN   TestAccRecoveryServicesVault_updateSkuWithExistingEncryption
=== PAUSE TestAccRecoveryServicesVault_updateSkuWithExistingEncryption
=== RUN   TestAccRecoveryServicesVault_encryptionWithKeyVaultKey
=== PAUSE TestAccRecoveryServicesVault_encryptionWithKeyVaultKey
=== RUN   TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey
=== PAUSE TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey
=== RUN   TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage
=== PAUSE TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage
=== RUN   TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage
=== PAUSE TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage
=== RUN   TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption
=== PAUSE TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption
=== RUN   TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey
=== PAUSE TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey
=== RUN   TestAccRecoveryServicesVault_encryptionWithUserAssignedIdentity
=== PAUSE TestAccRecoveryServicesVault_encryptionWithUserAssignedIdentity
=== RUN   TestAccRecoveryServicesVault_TogglePublicNetworkAccessEnabled
=== PAUSE TestAccRecoveryServicesVault_TogglePublicNetworkAccessEnabled
=== RUN   TestAccRecoveryServicesVault_basicWithClassicVmwareReplicateEnabled
=== PAUSE TestAccRecoveryServicesVault_basicWithClassicVmwareReplicateEnabled
=== RUN   TestAccRecoveryServicesVault_basicWithMonitorDisabled
=== PAUSE TestAccRecoveryServicesVault_basicWithMonitorDisabled
=== CONT  TestAccRecoveryServicesVault_basic
=== CONT  TestAccRecoveryServicesVault_CrossRegionRestoreWithEncryption
=== CONT  TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption
=== CONT  TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey
=== CONT  TestAccRecoveryServicesVault_SystemAssignedIdentity
=== CONT  TestAccRecoveryServicesVault_softDelete
=== CONT  TestAccRecoveryServicesVault_zrs
=== CONT  TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType
--- PASS: TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType (132.82s)
=== CONT  TestAccRecoveryServicesVault_ToggleCrossRegionRestore
--- PASS: TestAccRecoveryServicesVault_basic (255.30s)
=== CONT  TestAccRecoveryServicesVault_requiresImport
--- PASS: TestAccRecoveryServicesVault_zrs (280.71s)
=== CONT  TestAccRecoveryServicesVault_TogglePublicNetworkAccessEnabled
--- PASS: TestAccRecoveryServicesVault_SystemAssignedIdentity (286.99s)
=== CONT  TestAccRecoveryServicesVault_basicWithMonitorDisabled
--- PASS: TestAccRecoveryServicesVault_requiresImport (257.37s)
=== CONT  TestAccRecoveryServicesVault_basicWithClassicVmwareReplicateEnabled
--- PASS: TestAccRecoveryServicesVault_basicWithMonitorDisabled (255.03s)
=== CONT  TestAccRecoveryServicesVault_encryptionWithUserAssignedIdentity
--- PASS: TestAccRecoveryServicesVault_ToggleCrossRegionRestore (492.08s)
=== CONT  TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey
--- PASS: TestAccRecoveryServicesVault_CrossRegionRestoreWithEncryption (649.56s)
=== CONT  TestAccRecoveryServicesVault_crossRegionRestore
--- PASS: TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption (656.41s)
=== CONT  TestAccRecoveryServicesVault_storageModeType
--- PASS: TestAccRecoveryServicesVault_softDelete (688.61s)
=== CONT  TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage
--- PASS: TestAccRecoveryServicesVault_basicWithClassicVmwareReplicateEnabled (203.48s)
=== CONT  TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage
--- PASS: TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey (723.78s)
=== CONT  TestAccRecoveryServicesVault_immutabilityLocked
--- PASS: TestAccRecoveryServicesVault_TogglePublicNetworkAccessEnabled (551.85s)
=== CONT  TestAccRecoveryServicesVault_immutability
--- PASS: TestAccRecoveryServicesVault_crossRegionRestore (354.93s)
=== CONT  TestAccRecoveryServicesVault_UserAssignedIdentity
--- PASS: TestAccRecoveryServicesVault_storageModeType (350.29s)
=== CONT  TestAccRecoveryServicesVault_update
--- PASS: TestAccRecoveryServicesVault_immutabilityLocked (310.72s)
=== CONT  TestAccRecoveryServicesVault_updateSkuWithExistingEncryption
--- PASS: TestAccRecoveryServicesVault_encryptionWithUserAssignedIdentity (639.19s)
=== CONT  TestAccRecoveryServicesVault_encryptionWithKeyVaultKey
--- PASS: TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage (632.93s)
=== CONT  TestAccRecoveryServicesVault_sku
--- PASS: TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey (698.02s)
=== CONT  TestAccRecoveryServicesVault_complete
--- PASS: TestAccRecoveryServicesVault_UserAssignedIdentity (332.40s)
--- PASS: TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage (640.67s)
--- PASS: TestAccRecoveryServicesVault_update (468.28s)
--- PASS: TestAccRecoveryServicesVault_complete (249.32s)
--- PASS: TestAccRecoveryServicesVault_immutability (742.50s)
--- PASS: TestAccRecoveryServicesVault_updateSkuWithExistingEncryption (575.72s)
--- PASS: TestAccRecoveryServicesVault_encryptionWithKeyVaultKey (555.78s)
--- PASS: TestAccRecoveryServicesVault_sku (772.91s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices	2094.502s
```

### CODE REVIEW

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 1]
```diff
@@ -249,7 +249,17 @@ func resourceRecoveryServicesVaultCreate(d *pluginsdk.ResourceData, meta interfa
 		vault.Sku.Tier = utils.String("Standard")
 	}
 
+	requireAddtionalUpdate := false
+	updatePatch := vaults.PatchVault{
+		Properties: &vaults.VaultProperties{},
+	}
+	// The `immutability` could only be set to `Locked` from `Unlocked`
 	if immutability, ok := d.GetOk("immutability"); ok {
+		if immutability == string(vaults.ImmutabilityStateLocked) {
```
Comment (magodo) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:258]: Can we describe the intent a bit clearer, e.g.:
```suggestion
	if immutability, ok := d.GetOk("immutability"); ok {
	        // The API doesn't allow to set the immutability to "Locked" on ceartion.
	        // Here we firstly make it "Unlocked", and once created, we will update it to "Locked".
	        // Note: The `immutability` could be transitioned only from `Unlocked` to `Locked`.
		if immutability == string(vaults.ImmutabilityStateLocked) {
```

File: internal/services/recoveryservices/recovery_services_vault_resource_test.go [hunk 2]
```diff
@@ -188,13 +188,28 @@ func TestAccRecoveryServicesVault_UserAssignedIdentity(t *testing.T) {
 	})
 }
 
+func TestAccRecoveryServicesVault_immutabilityLocked(t *testing.T) {
+	data := acceptance.BuildTestData(t, "azurerm_recovery_services_vault", "test")
+	r := RecoveryServicesVaultResource{}
+
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			// To test creation with `Locked`, it is irreversible.
```
Comment (magodo) [inline internal/services/recoveryservices/recovery_services_vault_resource_test.go:197]: Since this is irreversible, shall we also test/implement that when this property get updated, the resource will be recreated?

**Review by magodo — CHANGES_REQUESTED** [review]
Thanks for this PR!
I've taken a look through and left some comments inline, but this is mostly looking good to me 👍

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 3]
```diff
@@ -179,6 +179,12 @@ func resourceRecoveryServicesVault() *pluginsdk.Resource {
 			pluginsdk.ForceNewIfChange("cross_region_restore_enabled", func(ctx context.Context, old, new, meta interface{}) bool {
 				return old.(bool) && !new.(bool)
 			}),
+			pluginsdk.ForceNewIfChange("immutability", func(ctx context.Context, old, new, meta interface{}) bool {
+				if old.(string) != new.(string) && old.(string) == string(vaults.ImmutabilityStateLocked) {
```
Comment (magodo) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:183]: Is there a case that `old != new`?, also this function can be simplified to a single `return` expression?

**Review by magodo — CHANGES_REQUESTED** [review]
Thanks for this PR!
I have left some additional mostly minor comments that once addressed this should be good to merge 👍

**Comment by ziyeqf** [comment]
new test result
```
 tftest recoveryservices TestAccRecoveryServicesVault       
=== RUN   TestAccRecoveryServicesVault_basic
=== PAUSE TestAccRecoveryServicesVault_basic
=== RUN   TestAccRecoveryServicesVault_ToggleCrossRegionRestore
=== PAUSE TestAccRecoveryServicesVault_ToggleCrossRegionRestore
=== RUN   TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType
=== PAUSE TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType
=== RUN   TestAccRecoveryServicesVault_zrs
=== PAUSE TestAccRecoveryServicesVault_zrs
=== RUN   TestAccRecoveryServicesVault_complete
=== PAUSE TestAccRecoveryServicesVault_complete
=== RUN   TestAccRecoveryServicesVault_update
=== PAUSE TestAccRecoveryServicesVault_update
=== RUN   TestAccRecoveryServicesVault_requiresImport
=== PAUSE TestAccRecoveryServicesVault_requiresImport
=== RUN   TestAccRecoveryServicesVault_SystemAssignedIdentity
=== PAUSE TestAccRecoveryServicesVault_SystemAssignedIdentity
=== RUN   TestAccRecoveryServicesVault_UserAssignedIdentity
=== PAUSE TestAccRecoveryServicesVault_UserAssignedIdentity
=== RUN   TestAccRecoveryServicesVault_immutabilityLocked
=== PAUSE TestAccRecoveryServicesVault_immutabilityLocked
=== RUN   TestAccRecoveryServicesVault_immutability
=== PAUSE TestAccRecoveryServicesVault_immutability
=== RUN   TestAccRecoveryServicesVault_softDelete
=== PAUSE TestAccRecoveryServicesVault_softDelete
=== RUN   TestAccRecoveryServicesVault_storageModeType
=== PAUSE TestAccRecoveryServicesVault_storageModeType
=== RUN   TestAccRecoveryServicesVault_crossRegionRestore
=== PAUSE TestAccRecoveryServicesVault_crossRegionRestore
=== RUN   TestAccRecoveryServicesVault_CrossRegionRestoreWithEncryption
=== PAUSE TestAccRecoveryServicesVault_CrossRegionRestoreWithEncryption
=== RUN   TestAccRecoveryServicesVault_sku
=== PAUSE TestAccRecoveryServicesVault_sku
=== RUN   TestAccRecoveryServicesVault_updateSkuWithExistingEncryption
=== PAUSE TestAccRecoveryServicesVault_updateSkuWithExistingEncryption
=== RUN   TestAccRecoveryServicesVault_encryptionWithKeyVaultKey
=== PAUSE TestAccRecoveryServicesVault_encryptionWithKeyVaultKey
=== RUN   TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey
=== PAUSE TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey
=== RUN   TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage
=== PAUSE TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage
=== RUN   TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage
=== PAUSE TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage
=== RUN   TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption
=== PAUSE TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption
=== RUN   TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey
=== PAUSE TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey
=== RUN   TestAccRecoveryServicesVault_encryptionWithUserAssignedIdentity
=== PAUSE TestAccRecoveryServicesVault_encryptionWithUserAssignedIdentity
=== RUN   TestAccRecoveryServicesVault_TogglePublicNetworkAccessEnabled
=== PAUSE TestAccRecoveryServicesVault_TogglePublicNetworkAccessEnabled
=== RUN   TestAccRecoveryServicesVault_basicWithClassicVmwareReplicateEnabled
=== PAUSE TestAccRecoveryServicesVault_basicWithClassicVmwareReplicateEnabled
=== RUN   TestAccRecoveryServicesVault_basicWithMonitorDisabled
=== PAUSE TestAccRecoveryServicesVault_basicWithMonitorDisabled
=== CONT  TestAccRecoveryServicesVault_basic
=== CONT  TestAccRecoveryServicesVault_CrossRegionRestoreWithEncryption
=== CONT  TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption
=== CONT  TestAccRecoveryServicesVault_requiresImport
=== CONT  TestAccRecoveryServicesVault_update
=== CONT  TestAccRecoveryServicesVault_SystemAssignedIdentity
=== CONT  TestAccRecoveryServicesVault_TogglePublicNetworkAccessEnabled
=== CONT  TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey
--- PASS: TestAccRecoveryServicesVault_requiresImport (275.31s)
=== CONT  TestAccRecoveryServicesVault_basicWithMonitorDisabled
--- PASS: TestAccRecoveryServicesVault_basic (283.66s)
=== CONT  TestAccRecoveryServicesVault_basicWithClassicVmwareReplicateEnabled
--- PASS: TestAccRecoveryServicesVault_SystemAssignedIdentity (284.83s)
=== CONT  TestAccRecoveryServicesVault_zrs
--- PASS: TestAccRecoveryServicesVault_update (513.20s)
=== CONT  TestAccRecoveryServicesVault_complete
--- PASS: TestAccRecoveryServicesVault_basicWithMonitorDisabled (263.55s)
=== CONT  TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey
--- PASS: TestAccRecoveryServicesVault_basicWithClassicVmwareReplicateEnabled (256.14s)
=== CONT  TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage
--- PASS: TestAccRecoveryServicesVault_zrs (262.74s)
=== CONT  TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage
--- PASS: TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption (570.94s)
=== CONT  TestAccRecoveryServicesVault_encryptionWithUserAssignedIdentity
--- PASS: TestAccRecoveryServicesVault_CrossRegionRestoreWithEncryption (579.59s)
=== CONT  TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType
--- PASS: TestAccRecoveryServicesVault_TogglePublicNetworkAccessEnabled (598.72s)
=== CONT  TestAccRecoveryServicesVault_ToggleCrossRegionRestore
--- PASS: TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType (103.55s)
=== CONT  TestAccRecoveryServicesVault_updateSkuWithExistingEncryption
--- PASS: TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey (748.91s)
=== CONT  TestAccRecoveryServicesVault_encryptionWithKeyVaultKey
--- PASS: TestAccRecoveryServicesVault_complete (267.37s)
=== CONT  TestAccRecoveryServicesVault_immutabilityLocked
--- PASS: TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage (596.40s)
=== CONT  TestAccRecoveryServicesVault_immutability
--- PASS: TestAccRecoveryServicesVault_ToggleCrossRegionRestore (550.25s)
=== CONT  TestAccRecoveryServicesVault_crossRegionRestore
--- PASS: TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage (609.39s)
=== CONT  TestAccRecoveryServicesVault_storageModeType
--- PASS: TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey (685.93s)
=== CONT  TestAccRecoveryServicesVault_UserAssignedIdentity
--- PASS: TestAccRecoveryServicesVault_encryptionWithUserAssignedIdentity (686.58s)
=== CONT  TestAccRecoveryServicesVault_sku
--- PASS: TestAccRecoveryServicesVault_updateSkuWithExistingEncryption (592.70s)
=== CONT  TestAccRecoveryServicesVault_softDelete
--- PASS: TestAccRecoveryServicesVault_encryptionWithKeyVaultKey (639.44s)
--- PASS: TestAccRecoveryServicesVault_storageModeType (361.65s)
--- PASS: TestAccRecoveryServicesVault_immutabilityLocked (789.49s)
--- PASS: TestAccRecoveryServicesVault_UserAssignedIdentity (347.53s)
--- PASS: TestAccRecoveryServicesVault_crossRegionRestore (448.78s)
--- PASS: TestAccRecoveryServicesVault_immutability (854.14s)
--- PASS: TestAccRecoveryServicesVault_softDelete (733.29s)
--- PASS: TestAccRecoveryServicesVault_sku (806.89s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices	2064.476s
```

File: internal/services/recoveryservices/recovery_services_vault_resource.go (hunk 3 above)
Comment (ziyeqf) [reply internal/services/recoveryservices/recovery_services_vault_resource.go:183]: I'm not sure when will this func be called, worried if it will be always called ( it will only be called when there is diff dectected? checked code but not 100% sure ).

**Comment by magodo** [comment]
LGTM!

**Review by katbyte — APPROVED** [review]
LGTM 🦑
