### PR TITLE
Add optional argument to oracle_autonomous_database, fix issue with backup_retention_period_in_days, and mark system_version as computed in VmClusterResource

### LINKED ISSUE #29232: Support for long_term_backup_schedule for Oracle autonomous database
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Added the long_term_backup_schedule capability in  Autonomous database. 

### New or Affected Resource(s)/Data Source(s)

internal/services/oracle/autonomous_database_regular_resource.go
internal/services/oracle/autonomous_database_regular_data_source.go
internal/services/oracle/autonomous_database_regular_resource_test.go
website/docs/d/oracle_autonomous_database.html.markdown
website/docs/r/oracle_autonomous_database.html.markdown

internal/services/oracle/cloud_vm_cluster_resource.go

### Potential Terraform Configuration

```hcl

```

### References

_No response_

### PR DESCRIPTION
**Pull request by mihretkidane-OCI**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

**New Optional Argument:**

long_term_backup_schedule: Allows users to configure automated long-term backup schedules for their Autonomous Database. Supported options include weekly, monthly, yearly, or a one-time backup.

**Updated Arguments:**

backup_retention_period_in_days: Removed the ForceNew property since this field is now updatable without requiring resource recreation.

system_version: Marked as Computed: true in the cloud_vm_cluster_resource, as the system automatically sets a default value when none is provided by the user during creation. We have the same behavior in cloud_vm_cluster_dataSource.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

Screenshot 2025-03-31 at 3 38 16 PM
Screenshot 2025-03-31 at 2 17 40 PM

Screenshot 2025-04-04 at 12 15 57 PM
Screenshot 2025-04-04 at 9 41 21 AM

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29232 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by mihretkidane-OCI** [comment]
@stephybun please help review this PR. Thank you!

**Comment by mihretkidane-OCI** [comment]
@katbyte PR is ready please help with review. Thank you.

**Review by chanstev — APPROVED** [review]

File: internal/services/oracle/autonomous_database_regular_data_source.go [hunk 1]
```diff
@@ -201,6 +209,31 @@ func (d AutonomousDatabaseRegularDataSource) Attributes() map[string]*pluginsdk.
 			Computed: true,
 		},
 
+		"long_term_backup_schedule": {
```
[the remark this answers is not in the document]
Comment (mihretkidane-OCI) [reply internal/services/oracle/autonomous_database_regular_data_source.go:212]: @chanstev yes,  long_term_backup_schedule we get a default value from backend ..and we can only change this with update call.

File: internal/services/oracle/autonomous_database_regular_data_source.go
[the remark this answers is not in the document]
Comment (mihretkidane-OCI) [reply internal/services/oracle/autonomous_database_regular_data_source.go:1]: let me try

**Comment by mihretkidane-OCI** [comment]
@stephybun could you please help review this PR

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @mihretkidane-OCI - i've given this a review and left some comments that need to be addressed.

File: internal/services/oracle/oracle_autonomous_database_resource.go [hunk 2]
```diff
@@ -156,6 +156,40 @@ func (AutonomousDatabaseRegularResource) Arguments() map[string]*pluginsdk.Schem
...
+					},
+					"time_of_backup": {
+						Type:         pluginsdk.TypeString,
+						Required:     true,
+						ValidateFunc: validation.StringIsNotEmpty,
+					},
+					"retention_period_in_days": {
+						Type:         pluginsdk.TypeInt,
+						Required:     true,
+						ValidateFunc: validation.IntBetween(90, 3650),
```
[the remark this answers is not in the document]
Comment (mihretkidane-OCI) [reply internal/services/oracle/oracle_autonomous_database_resource.go:183]: https://learn.microsoft.com/en-us/rest/api/oracle/autonomous-databases/create-or-update?view=rest-oracle-2025-03-01&tabs=HTTP#longtermbackupscheduledetails

its actually min 90 to 2558 days(7 years), I update it.

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 3]
```diff
@@ -88,6 +88,16 @@ The following arguments are supported:
 
 * `tags` - (Optional) A mapping of tags which should be assigned to the Autonomous Database.
 
+A `long_term_backup_schedule` - (optional) (Updatable) Block supports the following: for more information see [Create Long-Term Backups on Autonomous Database](https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/backup-long-term.html#GUID-BD76E02E-AEB0-4450-A6AB-5C9EB1F4EAD0) 
+
+* `repeat_cadence` - (required)  Specifies the schedule for automated long-term backups. Options include Weekly, Monthly, Yearly, or OneTime (does not repeat) . For example, if the Backup date and Time is Jan 24, 2025 00:09:00 UTC and this is a Tuesday, and Weekly is selected, the long-term backup will happen every Tuesday.
```
Comment (katbyte) [inline website/docs/r/oracle_autonomous_database.html.markdown]: again, please blockquote constants and values
```suggestion
* `repeat_cadence` - (required)  Specifies the schedule for automated long-term backups. Options include `Weekly`, `Monthly`, `Yearly`, or `OneTime` (does not repeat) . For example, if the Backup date and Time is `Jan 24, 2025 00:09:00 UTC` and this is a Tuesday, and Weekly is selected, the long-term backup will happen every Tuesday.
```

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 4]
```diff
@@ -88,6 +88,16 @@ The following arguments are supported:
...
+
+* `time_of_backup` - (required) The date and time in which the backup should be taken in ISO8601 Date Time format. For example if we want to set  the backup date and time for Jan 24, 2025 00:09:00 UTC the value passed  should be `2025-01-24T09:00:00Z`. 
+
+* `retention_period_in_days` - (required) The retention period in days for Autonomous database backup it can range from `90` to `2558` days (7 years).
```
Comment (katbyte) [inline website/docs/r/oracle_autonomous_database.html.markdown]:
```suggestion
* `retention_period_in_days` - (required) The retention period in days for Autonomous database backup it can range from `90` to `2558` days (`7` years).
```

File: internal/services/oracle/oracle_autonomous_database_resource_test.go [hunk 5]
```diff
@@ -191,6 +192,12 @@ resource "azurerm_oracle_autonomous_database" "test" {
   national_character_set           = "AL16UTF16"
   subnet_id                        = azurerm_subnet.test.id
   virtual_network_id               = azurerm_virtual_network.test.id
+  long_term_backup_schedule {
+    repeat_cadence           = "Monthly"
+    time_of_backup           = "2025-04-03T09:00:00Z"
+    retention_period_in_days = 323
+    is_disabled              = false
```
Comment (katbyte) [inline internal/services/oracle/oracle_autonomous_database_resource_test.go]: needs to be updated to match schema?

**Review by katbyte — DISMISSED** [review]

File: internal/services/oracle/oracle_autonomous_database_resource_test.go (hunk 5 above)
Comment (mihretkidane-OCI) [reply internal/services/oracle/oracle_autonomous_database_resource_test.go]: @katbyte thank you , I just updated it.

**Comment by mihretkidane-OCI** [comment]
@katbyte the PR shows conflict on website/docs/r/log_analytics_linked_service.html.markdown , However we can't resolve it as we don't own that document . Could you please help resolve those conflicts. Thank you.

File: internal/services/oracle/oracle_autonomous_database_data_source.go [hunk 6]
```diff
@@ -489,3 +523,16 @@ func (d AutonomousDatabaseRegularDataSource) Read() sdk.ResourceFunc {
...
+	if longTermBackUpScheduleDetails != nil {
+		return append(output, LongTermBackUpScheduleDetails{
+			RepeatCadence:         string(pointer.From(longTermBackUpScheduleDetails.RepeatCadence)),
+			TimeOfBackup:          pointer.From(longTermBackUpScheduleDetails.TimeOfBackup),
+			RetentionPeriodInDays: pointer.From(longTermBackUpScheduleDetails.RetentionPeriodInDays),
+			Enabled:               pointer.From(longTermBackUpScheduleDetails.IsDisabled),
+		})
+	}
+	return output
+}
```
Comment (sreallymatt) [inline internal/services/oracle/oracle_autonomous_database_data_source.go]: Since this is being used by both the resource and data source, could you move this to a separate helper file? (e.g. `oracle_autonomous_database.go`)

File: internal/services/oracle/oracle_autonomous_database_resource.go [hunk 7]
```diff
@@ -156,6 +156,40 @@ func (AutonomousDatabaseRegularResource) Arguments() map[string]*pluginsdk.Schem
 			}, false),
 		},
 
+		"long_term_backup_schedule": {
```
Comment (sreallymatt) [inline internal/services/oracle/oracle_autonomous_database_resource.go:159]: This is missing from the create function, it needs to be added there as well

File: internal/services/oracle/oracle_autonomous_database_resource.go [hunk 8]
```diff
@@ -76,7 +77,6 @@ func (AutonomousDatabaseRegularResource) Arguments() map[string]*pluginsdk.Schem
 		"backup_retention_period_in_days": {
```
Comment (sreallymatt) [inline internal/services/oracle/oracle_autonomous_database_resource.go:77]: If this is no longer ForceNew could you update the `update` test config with a value different than `basic` test config?

File: internal/services/oracle/oracle_autonomous_database_resource.go [hunk 9]
```diff
@@ -156,6 +156,40 @@ func (AutonomousDatabaseRegularResource) Arguments() map[string]*pluginsdk.Schem
...
+				Schema: map[string]*pluginsdk.Schema{
+					"repeat_cadence": {
+						Type:     pluginsdk.TypeString,
+						Required: true,
+						ValidateFunc: validation.StringInSlice([]string{
+							string(autonomousdatabases.RepeatCadenceTypeMonthly),
+							string(autonomousdatabases.RepeatCadenceTypeOneTime),
+							string(autonomousdatabases.RepeatCadenceTypeWeekly),
+							string(autonomousdatabases.RepeatCadenceTypeYearly),
+						}, false),
```
Comment (sreallymatt) [inline internal/services/oracle/oracle_autonomous_database_resource.go]: Instead of listing each constant we can use the `PossibleValues*` helper function

```suggestion
						ValidateFunc: validation.StringInSlice(autonomousdatabases.PossibleValuesForRepeatCadenceType(), false),
```

File: internal/services/oracle/oracle_autonomous_database_resource.go [hunk 10]
```diff
@@ -303,6 +337,14 @@ func (r AutonomousDatabaseRegularResource) Update() sdk.ResourceFunc {
 			if metadata.ResourceData.HasChange("auto_scaling_for_storage_enabled") {
 				update.Properties.IsAutoScalingForStorageEnabled = pointer.To(model.AutoScalingForStorageEnabled)
 			}
+			if metadata.ResourceData.HasChange("long_term_backup_schedule") {
+				update.Properties.LongTermBackupSchedule = &autonomousdatabases.LongTermBackUpScheduleDetails{
+					RepeatCadence:         pointer.To(autonomousdatabases.RepeatCadenceType(model.LongTermBackUpSchedule[0].RepeatCadence)),
+					TimeOfBackup:          pointer.To(model.LongTermBackUpSchedule[0].TimeOfBackup),
+					RetentionPeriodInDays: pointer.To(model.LongTermBackUpSchedule[0].RetentionPeriodInDays),
+					IsDisabled:            pointer.To(model.LongTermBackUpSchedule[0].Enabled),
+				}
```
Comment (sreallymatt) [inline internal/services/oracle/oracle_autonomous_database_resource.go]: Please add an expand function for this. We should also check the length of `LongTermBackupSchedule` before accessing index 0 to ensure we don't encounter any panics.

File: internal/services/oracle/oracle_autonomous_database_resource_test.go [hunk 11]
```diff
@@ -177,7 +178,7 @@ resource "azurerm_oracle_autonomous_database" "test" {
   resource_group_name              = azurerm_resource_group.test.name
   location                         = "%[3]s"
   compute_model                    = "ECPU"
-  compute_count                    = 3
+  compute_count                    = 2
```
Comment (sreallymatt) [inline internal/services/oracle/oracle_autonomous_database_resource_test.go:236]: Why was this changed? It seems unrelated to the changes being made in this PR so we'd prefer to leave existing tests as they were

File: internal/services/oracle/oracle_autonomous_database_resource_test.go [hunk 12]
```diff
@@ -191,6 +192,12 @@ resource "azurerm_oracle_autonomous_database" "test" {
   national_character_set           = "AL16UTF16"
   subnet_id                        = azurerm_subnet.test.id
   virtual_network_id               = azurerm_virtual_network.test.id
+  long_term_backup_schedule {
+    repeat_cadence           = "Monthly"
+    time_of_backup           = "2025-04-03T09:00:00Z"
+    retention_period_in_days = 323
+    enabled              = false
+  }
```
Comment (sreallymatt) [inline internal/services/oracle/oracle_autonomous_database_resource_test.go]: Could you add a separate test for long_term_backup_schedule where we add, remove, update values, enable, disable, etc. to ensure all of this functions as expected?

```suggestion
```

File: website/docs/d/oracle_autonomous_database.html.markdown [hunk 13]
```diff
@@ -145,6 +145,13 @@ In addition to the Arguments listed above - the following Attributes are exporte
 
 * `used_data_storage_size_in_tbs` - The amount of storage that has been used, in terabytes.
 
+* `long_term_backup_schedule` - Block exports the following:
```
Comment (sreallymatt) [inline website/docs/d/oracle_autonomous_database.html.markdown]: We separate block arguments and attributes. 

1. An entry for the block itself, with `as defined <below/above>`
2. An entry for the block + the block's sub properties, which should come after all the other top level properties in the docs. The website scaffold tool can be helpful to get the right structure (keep in mind that this tool will wipe the existing docs, so you'd have to copy-paste the existing property descriptions.)

e.g.

```suggestion
* `long_term_backup_schedule` - A `long_term_backup_schedule` block as defined below

---

A `long_term_backup_schedule` blocks exports the following:

<properties here>
```

Properties in the documentation should also be ordered following the same [guidelines as the schema](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-new-resource.md#step-3-scaffold-an-emptynew-resource):

- Any fields that make up the resource's ID, with the last user specified segment (usually the resource's name) first. (e.g. name then resource_group_name, or name then parent_resource_id)
- The location field.
- Required fields, sorted alphabetically.
- Optional fields, sorted alphabetically.
- Computed fields, sorted alphabetically. (Although in a typed resource these are always added within the Attributes method)

File: website/docs/d/oracle_autonomous_database.html.markdown [hunk 14]
```diff
@@ -145,6 +145,13 @@ In addition to the Arguments listed above - the following Attributes are exporte
...
+
+* `repeat_cadence` -  Specifies the frequency  for automated long-term backups. 
+* `time_of_backup` - The date and time in which the backup should be taken. 
+* `retention_period_in_days` - The retention period in days for Autonomous database backup.
+* `enabled` -  A boolean value that indicates if long term backup is enabled/disabled.
```
Comment (sreallymatt) [inline website/docs/d/oracle_autonomous_database.html.markdown]: Properties should have an empty line between them

```suggestion
* `repeat_cadence` - The frequency for automated long-term backups. 

* `time_of_backup` - The date and time in which the backup would be made. 

* `retention_period_in_days` - The retention period in days for Autonomous database backup.

* `enabled` -  A boolean value that indicates if long term backup is enabled/disabled.
```

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 15]
```diff
@@ -48,7 +48,7 @@ The following arguments are supported:
 
 * `admin_password` - (Required) The password must be between `12` and `30 `characters long, and must contain at least 1 uppercase, 1 lowercase, and 1 numeric character. It cannot contain the double quote symbol (") or the username "admin", regardless of casing. Changing this forces a new Autonomous Database to be created.
 
-* `backup_retention_period_in_days` - (Optional) (Updatable) Retention period, in days, for backups. Changing this forces a new Autonomous Database to be created.
+* `backup_retention_period_in_days` - (Optional) (Updatable) Retention period, in days, for backups.
```
Comment (sreallymatt) [inline website/docs/r/oracle_autonomous_database.html.markdown]: We don't add `(Updatable)` to properties, properties are updatable unless we add `Changing this forces a new resource to be created` at the end of the description

```suggestion
* `backup_retention_period_in_days` - (Optional) Retention period, in days, for backups. 
```

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 16]
```diff
@@ -88,6 +88,16 @@ The following arguments are supported:
 
 * `tags` - (Optional) A mapping of tags which should be assigned to the Autonomous Database.
 
+A `long_term_backup_schedule` - (optional) (Updatable) Block supports the following: for more information see [Create Long-Term Backups on Autonomous Database](https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/backup-long-term.html#GUID-BD76E02E-AEB0-4450-A6AB-5C9EB1F4EAD0)
```
Comment (sreallymatt) [inline website/docs/r/oracle_autonomous_database.html.markdown]: Optional should start with a capital, for additional information we use [notes](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-documentation-standards.md#notes)

This will also need to be structured as explained in the comment in the data source documentation

```suggestion
A `long_term_backup_schedule` - (Optional) Block supports the following:
```

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 17]
```diff
@@ -88,6 +88,16 @@ The following arguments are supported:
 
 * `tags` - (Optional) A mapping of tags which should be assigned to the Autonomous Database.
 
+A `long_term_backup_schedule` - (optional) (Updatable) Block supports the following: for more information see [Create Long-Term Backups on Autonomous Database](https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/backup-long-term.html#GUID-BD76E02E-AEB0-4450-A6AB-5C9EB1F4EAD0) 
+
+* `repeat_cadence` - (required)  Specifies the schedule for automated long-term backups. Options include `Weekly`, `Monthly`, `Yearly`, or `OneTime` (does not repeat) . For example, if the Backup date and Time is `Jan 24, 2025 00:09:00 UTC` and this is a Tuesday, and Weekly is selected, the long-term backup will happen every Tuesday.
```
Comment (sreallymatt) [inline website/docs/r/oracle_autonomous_database.html.markdown]: Required should start with a capital, for consistency with the rest of the provider docs, please replace `options include` with `Possible values are`.

Instead of adding the example and explanation here, we should update the example in the documentation to include the `long_term_backup_schedule` block, we should aim to keep the description of the property concise.

```suggestion
* `repeat_cadence` - (Required)  Specifies the schedule for automated long-term backups. Possible values are `Weekly`, `Monthly`, `Yearly`, or `OneTime`.
```

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 18]
```diff
@@ -88,6 +88,16 @@ The following arguments are supported:
...
+
+* `time_of_backup` - (required) The date and time in which the backup should be taken in ISO8601 Date Time format. For example if we want to set  the backup date and time for Jan 24, 2025 00:09:00 UTC the value passed  should be `2025-01-24T09:00:00Z`.
```
Comment (sreallymatt) [inline website/docs/r/oracle_autonomous_database.html.markdown]:
```suggestion
* `time_of_backup` - (Required) The date and time in which the backup should be taken in ISO8601 Date Time format. 
```

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 19]
```diff
@@ -88,6 +88,16 @@ The following arguments are supported:
 
 * `tags` - (Optional) A mapping of tags which should be assigned to the Autonomous Database.
 
+A `long_term_backup_schedule` - (optional) (Updatable) Block supports the following: for more information see [Create Long-Term Backups on Autonomous Database](https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/backup-long-term.html#GUID-BD76E02E-AEB0-4450-A6AB-5C9EB1F4EAD0) 
+
+* `repeat_cadence` - (required)  Specifies the schedule for automated long-term backups. Options include `Weekly`, `Monthly`, `Yearly`, or `OneTime` (does not repeat) . For example, if the Backup date and Time is `Jan 24, 2025 00:09:00 UTC` and this is a Tuesday, and Weekly is selected, the long-term backup will happen every Tuesday.
+
+* `time_of_backup` - (required) The date and time in which the backup should be taken in ISO8601 Date Time format. For example if we want to set  the backup date and time for Jan 24, 2025 00:09:00 UTC the value passed  should be `2025-01-24T09:00:00Z`. 
+
+* `retention_period_in_days` - (required) The retention period in days for Autonomous database backup it can range from `90` to `2558` days (`7` years).
```
Comment (sreallymatt) [inline website/docs/r/oracle_autonomous_database.html.markdown]:
```suggestion
* `retention_period_in_days` - (Required) The retention period in days for the Autonomous Database Backup. Possible values range from `90` to `2558` days (7 years).
```

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 20]
```diff
@@ -88,6 +88,16 @@ The following arguments are supported:
...
+
+* `enabled` - (required) A boolean value that indicates if long term backup is enabled.
```
Comment (sreallymatt) [inline website/docs/r/oracle_autonomous_database.html.markdown]:
```suggestion
* `enabled` - (Required) A boolean value that indicates whether the long term backup schedule is enabled. 
```

**Comment by sreallymatt** [comment]
Could you also run `make terrafmt`? That should fix the failure in the `Terraform Schema Linting` action

File: internal/services/oracle/oracle_autonomous_database_resource.go (hunk 7 above)
Comment (mihretkidane-OCI) [reply internal/services/oracle/oracle_autonomous_database_resource.go:159]: @sreallymatt , LongTermBackup has Read/Update visibility . Its not part of the create parameter.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/oracle/Oracle.Database.Management/models/autonomousdatabase/autonomousDatabase.tsp#L703

Comment (sreallymatt) [reply internal/services/oracle/oracle_autonomous_database_resource.go:159]: @mihretkidane-OCI It will still need to be added to the create function, if it can't be sent in the initial create request we'll need to add a separate call in the create function to update the resource with the backup schedule.

If we don't do this, on creation the `long_term_backup_schedule` would not be configured, and the next `terraform plan` would show a diff

File: internal/services/oracle/oracle_autonomous_database_data_source.go (hunk 6 above)
Comment (mihretkidane-OCI) [reply internal/services/oracle/oracle_autonomous_database_data_source.go]: Done

Comment (mihretkidane-OCI) [reply internal/services/oracle/oracle_autonomous_database_data_source.go]: done

File: internal/services/oracle/oracle_autonomous_database_resource.go (hunk 7 above)
Comment (mihretkidane-OCI) [reply internal/services/oracle/oracle_autonomous_database_resource.go:159]: 1. add a separate call in the create function to update long_term_backup_schedule
2. modified update function to handle both update calls (update to basic parameters and update longterm backup schedule)

**Comment by mihretkidane-OCI** [comment]
Screenshot 2025-06-17 at 12 24 21 PM

test result after applying latest changes.

**Comment by mihretkidane-OCI** [comment]
@sreallymatt resolved all comments please help review PR. Thank you!

File: internal/services/oracle/oracle_autonomous_database_resource.go [hunk 21]
```diff
@@ -285,28 +325,51 @@ func (r AutonomousDatabaseRegularResource) Update() sdk.ResourceFunc {
...
+				if err := client.UpdateThenPoll(ctx, *id, generalUpdate); err != nil {
+					return fmt.Errorf("updating general properties for %s: %+v", *id, err)
+				}
 			}
 
-			err = client.UpdateThenPoll(ctx, *id, *update)
-			if err != nil {
-				return fmt.Errorf("updating %s: %v", id, err)
+			// Step 2: Handle backup schedule update separately
+			if needsBackupScheduleUpdate {
```
Comment (sreallymatt) [inline internal/services/oracle/oracle_autonomous_database_resource.go:363]: Could you clarify why the backup schedule needs a separate update here? For the `Create` function I understand, it's using a PUT rather than PATCH, but here both requests are using `PATCH`.

File: internal/services/oracle/oracle_autonomous_database_resource_test.go [hunk 22]
```diff
@@ -158,13 +159,22 @@ resource "azurerm_oracle_autonomous_database" "test" {
...
 }
 `, a.template(data), data.RandomInteger, data.Locations.Primary)
 }
 
 func (a AdbsRegularResource) update(data acceptance.TestData) string {
 	return fmt.Sprintf(`
 
+
+
+
```
Comment (sreallymatt) [inline internal/services/oracle/oracle_autonomous_database_resource_test.go]: Nit: not sure why we're adding multiple empty lines?

File: internal/services/oracle/oracle_autonomous_database_resource_test.go (hunk 11 above)
Comment (sreallymatt) [reply internal/services/oracle/oracle_autonomous_database_resource_test.go:236]: This is still outstanding

File: website/docs/d/oracle_autonomous_database.html.markdown (hunk 13 above)
Comment (sreallymatt) [reply website/docs/d/oracle_autonomous_database.html.markdown]: Still outstanding

File: website/docs/d/oracle_autonomous_database.html.markdown (hunk 14 above)
Comment (sreallymatt) [reply website/docs/d/oracle_autonomous_database.html.markdown]: Still outstanding

File: website/docs/r/oracle_autonomous_database.html.markdown (hunk 15 above)
Comment (sreallymatt) [reply website/docs/r/oracle_autonomous_database.html.markdown]: Still outstanding

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 23]
```diff
@@ -88,6 +88,16 @@ The following arguments are supported:
...
 
+A `long_term_backup_schedule` - (Optional) (Updatable) Block supports the following: for more information see [Create Long-Term Backups on Autonomous Database](https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/backup-long-term.html#GUID-BD76E02E-AEB0-4450-A6AB-5C9EB1F4EAD0) 
+
+* `repeat_cadence` - (Required)  Specifies the schedule for automated long-term backups. Possible values are `Weekly`, `Monthly`, `Yearly`, or `OneTime`.
+
+* `time_of_backup` - (Required) The date and time in which the backup should be taken in ISO8601 Date Time format. 
+
+* `retention_period_in_days` - (Required) The retention period in days for the Autonomous Database Backup. Possible values range from `90` to `2558` days (7 years).
+
+* `enabled` - (Required) A boolean value that indicates whether the long term backup schedule is enabled.
```
Comment (sreallymatt) [inline website/docs/r/oracle_autonomous_database.html.markdown]: This is not quite how we document blocks, could you use the website-scaffold tool to generate the structure?

**Review by sreallymatt — CHANGES_REQUESTED** [review]

File: internal/services/oracle/oracle_autonomous_database_resource.go (hunk 21 above)
Comment (mihretkidane-OCI) [reply internal/services/oracle/oracle_autonomous_database_resource.go:363]: @sreallymatt I added this because of our update API behavior, when calling update with longterm backup schedule it ignores the other updated fields and create backup schedule or vice versa there fore I had to make two update calls to update all the changes fields.

File: internal/services/oracle/oracle_autonomous_database_resource_test.go (hunk 12 above)
Comment (mihretkidane-OCI) [reply internal/services/oracle/oracle_autonomous_database_resource_test.go]: done

File: website/docs/r/oracle_autonomous_database.html.markdown (hunk 15 above)
Comment (mihretkidane-OCI) [reply website/docs/r/oracle_autonomous_database.html.markdown]: done

File: website/docs/d/oracle_autonomous_database.html.markdown (hunk 14 above)
Comment (mihretkidane-OCI) [reply website/docs/d/oracle_autonomous_database.html.markdown]: done

File: internal/services/oracle/oracle_autonomous_database_resource_test.go (hunk 22 above)
Comment (mihretkidane-OCI) [reply internal/services/oracle/oracle_autonomous_database_resource_test.go]: done

**Comment by mihretkidane-OCI** [comment]
@sreallymatt please help review this PR

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 24]
```diff
@@ -88,6 +88,20 @@ The following arguments are supported:
 
 * `tags` - (Optional) A mapping of tags which should be assigned to the Autonomous Database.
 
+* `long_term_backup_schedule` - (Optional) Block supports the following: for more information see [Create Long-Term Backups on Autonomous Database](https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/backup-long-term.html#GUID-BD76E02E-AEB0-4450-A6AB-5C9EB1F4EAD0)
```
Comment (sreallymatt) [inline website/docs/r/oracle_autonomous_database.html.markdown]: For additional information, we generally try to use [notes](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-documentation-standards.md), and blocks include the text `` A `<block name>` block as defined below. ``

```suggestion
* `long_term_backup_schedule` - (Optional) A `long_term_backup_schedule` block as defined below.

-> **Note:** for more information see [Create Long-Term Backups on Autonomous Database](https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/backup-long-term.html#GUID-BD76E02E-AEB0-4450-A6AB-5C9EB1F4EAD0) 
```

File: website/docs/r/oracle_autonomous_database.html.markdown [hunk 25]
```diff
@@ -88,6 +88,20 @@ The following arguments are supported:
 
 * `tags` - (Optional) A mapping of tags which should be assigned to the Autonomous Database.
 
+* `long_term_backup_schedule` - (Optional) Block supports the following: for more information see [Create Long-Term Backups on Autonomous Database](https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/backup-long-term.html#GUID-BD76E02E-AEB0-4450-A6AB-5C9EB1F4EAD0) 
+
+---
+
+A `long_term_backup_schedule` blocks supports the following:
+
+* `repeat_cadence` - (Required)  Specifies the schedule for automated long-term backups. Options include `Weekly`, `Monthly`, `Yearly`, or `OneTime` (does not repeat) . For example, if the Backup date and Time is `Jan 24, 2025 00:09:00 UTC` and this is a Tuesday, and Weekly is selected, the long-term backup will happen every Tuesday.
```
Comment (sreallymatt) [inline website/docs/r/oracle_autonomous_database.html.markdown]:
```suggestion
* `repeat_cadence` - (Required)  Specifies the schedule for automated long-term backups. Possible values are `Weekly`, `Monthly`, `Yearly`, or `OneTime` (does not repeat) . For example, if the Backup date and Time is `Jan 24, 2025 00:09:00 UTC` and this is a Tuesday, and Weekly is selected, the long-term backup will happen every Tuesday.
```

File: website/docs/r/oracle_autonomous_database.html.markdown (hunk 19 above)
Comment (sreallymatt) [reply website/docs/r/oracle_autonomous_database.html.markdown]: It doesn't appear this line was updated?

**Review by sreallymatt — APPROVED** [review]
Thanks @mihretkidane-OCI LGTM ✅
