### PR TITLE
fix(ip_group_cidr): Fixed the position of the CIDR existence check

### LINKED ISSUE #26998: The resource `azurerm_ip_group_cidr` does not detect missing CIDRs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.3

### AzureRM Provider Version

3.114.0

### Affected Resource(s)/Data Source(s)

azurerm_ip_group_cidr

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "test-rg"
  location = "West Europe"
}

resource "azurerm_ip_group" "example" {
  name                = "test-ipgroup"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_ip_group_cidr" "example" {
  ip_group_id = azurerm_ip_group.example.id
  cidr        = "10.10.10.0/24"
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

If the CIDR definied in `azurerm_ip_group_cidr` is no longer preset, it should be recreated.
It seems the refresh is currently not checking for the existence of the CIDR.

### Actual Behaviour

Missing CIDR is not detected

### Steps to Reproduce

1. terraform apply
2. Remove CIDR vom IP Group (outside of Terraform)
3. terraform apply (no required change is detected)

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by tiwood**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Fixed the position of the CIDR existence check.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_ip_group_cidr` - fixed the IP group CIDR existence check [GH-27103]

This is a (please select all that apply):

- [X] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #26998 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/network/ip_group_cidr_resource.go [hunk 1]
```diff
@@ -136,10 +136,11 @@ func resourceIpGroupCidrRead(d *pluginsdk.ResourceData, meta interface{}) error
 		if resp.Model.Properties == nil {
 			return fmt.Errorf("retrieving %s: `properties` was nil", ipGroupId)
 		}
-		if !utils.SliceContainsValue(*resp.Model.Properties.IPAddresses, cidr) {
-			d.SetId("")
-			return nil
-		}
+	}
+
+	if !utils.SliceContainsValue(*resp.Model.Properties.IPAddresses, cidr) {
```
Comment (stephybun) [inline internal/services/network/ip_group_cidr_resource.go:141]: Since `IPAddresses` is a pointer this also wants to be nil checked before dereferencing, alternatively we can use `pointer.From` to do that for us 
```suggestion
	if !utils.SliceContainsValue(pointer.From(resp.Model.Properties.IPAddresses), cidr) {
```

**Review by stephybun — CHANGES_REQUESTED** [review]

File: internal/services/network/ip_group_cidr_resource.go (hunk 1 above)
Comment (tiwood) [reply internal/services/network/ip_group_cidr_resource.go]: thanks for the suggestion 👍

**Review by stephybun — APPROVED** [review]
Thanks @tiwood LGTM 🍿
