### PR TITLE
Fix `azurerm_application_insights_standard_web_test`

### LINKED ISSUE #20064: azurerm_application_insights_standard_web_test resource with validation_rules block fails with Error code: PropertyMissingForKind
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

azurerm_application_insights_standard_web_test

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.2.1"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.39.1"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = "change_this"
}

data "azurerm_application_insights" "this" {
  name                = "appinsight-app01"
  resource_group_name = "rg-appinsight"
}

# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_standard_web_test
resource "azurerm_application_insights_standard_web_test" "example" {
  name                    = "std-web-test"
  resource_group_name     = "rg-appinsight"
  location                = "UK South"
  application_insights_id = data.azurerm_application_insights.this.id
  geo_locations           = [ "emea-gb-db3-azr" ]
  
  request {
    url = "https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_standard_web_test"
  }

  validation_rules {
    ssl_check_enabled    = true
  }

}
```

### Debug Output/Panic Output

```shell
azurerm_application_insights_standard_web_test.example: Creating...
╷
│ Error: creating Web Test (Subscription: "change_this"
│ Resource Group Name: "rg-appinsight"
│ Web Test Name: "std-web-test"): webtestsapis.WebTestsAPIsClient#WebTestsCreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Specified argument was out of the range of valid values.\r\nParameter name: Error code: PropertyMissingForKind. Web test 'std-web-test' is invalid. 'ValidationRules.ContentValidation' property is provided, a required property 'ValidationRules.ContentValidation.ContentMatch' is missing or empty for 'standard' web test" InnerError={"trace":["System.ArgumentOutOfRangeException"]}
│ 
│   with azurerm_application_insights_standard_web_test.example,
│   on azurerm_application_insights_standard_web_test.tf line 24, in resource "azurerm_application_insights_standard_web_test" "example":
│   24: resource "azurerm_application_insights_standard_web_test" "example" {
```

### Expected Behaviour

Standard Web Test is created when `validation_rules` block in the resource definition is not present.

### Actual Behaviour

Adding a simple validation rule block into resource...

``` 
validation_rules {
    ssl_check_enabled    = true
  }
``` 
...results in error.

The error message implies that the property named `kind` or `web-test-kind` is missing and such property should carry a value `standard` 

Microsoft [documentation for Standard Web Test](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/2020-10-05-preview/webtests?pivots=deployment-language-bicep#webtestproperties) specifies Kind as a required property.

I've validated this by creating equivalent Standard Web Test using `az` command line tool. 
Creation only works when including a flag `--web-test-kind standard` in the command like `az monitor app-insights web-test create --web-test-kind standard  --location "UK South" ....`

Attempting to create a Standard Web Test without a flag `--web-test-kind standard` results in error similar to what Azurerm v.3.39.1 is reporting. 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #20064

## AccTests
```bash
❯ go install && make acctests SERVICE='applicationinsights' TESTARGS='-run=TestAccApplicationInsightsStandardWebTest_'

==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/applicationinsights -run=TestAccApplicationInsightsStandardWebTest_ -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccApplicationInsightsStandardWebTest_basic
=== PAUSE TestAccApplicationInsightsStandardWebTest_basic
=== RUN   TestAccApplicationInsightsStandardWebTest_requiresImport
=== PAUSE TestAccApplicationInsightsStandardWebTest_requiresImport
=== RUN   TestAccApplicationInsightsStandardWebTest_complete
=== PAUSE TestAccApplicationInsightsStandardWebTest_complete
=== CONT  TestAccApplicationInsightsStandardWebTest_basic
=== CONT  TestAccApplicationInsightsStandardWebTest_complete
=== CONT  TestAccApplicationInsightsStandardWebTest_requiresImport
--- PASS: TestAccApplicationInsightsStandardWebTest_basic (183.80s)
--- PASS: TestAccApplicationInsightsStandardWebTest_requiresImport (203.03s)
--- PASS: TestAccApplicationInsightsStandardWebTest_complete (443.03s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/applicationinsights   444.901s
```

### CODE REVIEW

File: internal/services/applicationinsights/application_insights_standard_webtests_resource_test.go [hunk 1]
```diff
@@ -59,6 +68,45 @@ func (ApplicationInsightsStandardWebTestResource) Exists(ctx context.Context, cl
...
+  name                    = "acctestappinsightswebtests-%d"
+  location                = azurerm_resource_group.test.location
+  resource_group_name     = azurerm_resource_group.test.name
+  application_insights_id = azurerm_application_insights.test.id
+  geo_locations           = ["us-tx-sn1-azr"]
+
+  request {
+    url = "https://microsoft.com"
+  }
+	validation_rules {
```
Comment (mbfrahry) [inline internal/services/applicationinsights/application_insights_standard_webtests_resource_test.go:99]: The formatting is off here.

File: internal/services/applicationinsights/application_insights_standard_webtests_resource.go [hunk 2]
```diff
@@ -151,8 +151,9 @@ func (ApplicationInsightsStandardWebTestResource) Arguments() map[string]*plugin
 					// },
 
 					"ssl_cert_remaining_lifetime": {
-						Type:     pluginsdk.TypeInt,
-						Optional: true,
+						Type:         pluginsdk.TypeInt,
+						Optional:     true,
+						ValidateFunc: validation.IntBetween(1, 365),
```
Comment (mbfrahry) [inline internal/services/applicationinsights/application_insights_standard_webtests_resource.go:156]: We should add this validation to the docs

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @aristosvo, this change looks good but there is a minor formatting issue and we should update the docs.

File: internal/services/applicationinsights/application_insights_standard_webtests_resource.go (hunk 2 above)
Comment (aristosvo) [reply internal/services/applicationinsights/application_insights_standard_webtests_resource.go:156]: Done 🎉

File: internal/services/applicationinsights/application_insights_standard_webtests_resource_test.go (hunk 1 above)
Comment (aristosvo) [reply internal/services/applicationinsights/application_insights_standard_webtests_resource_test.go]: Ouch, fixed it. Is there a reason formatting is not checked anymore by the GitHub Actions?

Comment (mbfrahry) [reply internal/services/applicationinsights/application_insights_standard_webtests_resource_test.go]: I believe we turned them off as there was a bug in that linter. We'll get it back on soon!

**Review by katbyte — APPROVED** [review]
LGTM 🏷️
