### PR TITLE
mssql - fix Long Term Retention not supported for SQL database with Free edition

### LINKED ISSUE #16231: Long Term Retention is not supported : Not supported for database with Free edition.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "mps_mssqldb" {
  name                 = "mps_db"
  server_id            = azurerm_mssql_server.mps_mssql.id
  collation            = "SQL_Latin1_General_CP1_CI_AS"
  sku_name             = var.sql_sku_name
  read_scale           = "false"
  zone_redundant       = "Local"
  storage_account_type = "Free"
}
```

### Debug Output/Panic Output

```shell
│ Error: retrieving Long Term Retention Policies for Database: (Name "mps_db" / Server Name "dev-mps-mssql" / Resource Group "dev-rg-mps-spa-studio-wallsmedia"): sql.LongTermRetentionPoliciesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LongTermRetentionPolicyNotSupported" Message="Long Term Retention is not supported : Not supported for database with Free edition."
│
│   with azurerm_mssql_database.mps_mssqldb,
│   on mssql.tf line 47, in resource "azurerm_mssql_database" "mps_mssqldb":
│   47: resource "azurerm_mssql_database" "mps_mssqldb" {
```

### Expected Behaviour

Pass

### Actual Behaviour

Error: retrieving Long Term Retention Policies for Database: 

### Steps to Reproduce

terraform apply or plan 

### Important Factoids

No

### References

None

### PR DESCRIPTION
**Pull request by cdituri**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Fixes the deployment of SQL Database Free tier by skipping Long-Term and Short-Term Retention Policies, which are not supported on the Free tier.

Fixes #16231
Fixes half of #13387

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

I added a minimal acceptance test for the unique case of deploying `mssql` resource on the Free tier. The new acceptance test passes and its log output can be found below.

Note: After passing the new test I attempted to run all the acceptance tests for service `mssql` but quickly hit my rate-limit and blew out my subscription's quota 🙃 Apologies there isn't more test output available. Hoping a github action will trigger and exhaustively test once this PR is opened...

```sh
PS C:\Go\src\github.com\hashicorp\terraform-provider-azurerm> make acctests SERVICE='mssql' TESTARGS='-run=TestAccMsSqlDatabase_free' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/mssql -run=TestAccMsSqlDatabase_free -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccMsSqlDatabase_free
=== PAUSE TestAccMsSqlDatabase_free
=== CONT  TestAccMsSqlDatabase_free
--- PASS: TestAccMsSqlDatabase_free (325.52s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql 325.707s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `mssql` - support deployment of SQL Database `Free` sku/tier resources [GH-26894]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #16231
Fixes half of #13387

### CODE REVIEW

File: internal/services/mssql/mssql_database_resource_test.go [hunk 1]
```diff
@@ -1020,6 +1037,22 @@ resource "azurerm_mssql_database" "test" {
 `, r.template(data), data.RandomInteger)
 }
 
+func (r MsSqlDatabaseResource) basicWithSku(t *testing.T, data acceptance.TestData, sku string) string {
+	if _, err := mssqlValidate.DatabaseSkuName()(sku, ""); err != nil {
+		t.Errorf("%s", errors.Join(err...).Error())
+	}
```
Comment (cdituri) [inline internal/services/mssql/mssql_database_resource_test.go:1043]: Made this `basicWithSku` method accept a `sku` string, to allow testing basic, default configurations with different skus easy in the future. This does however require passing a `*testing.T` through to the method. Happy to change if you'd rather see another approach used.

Comment (stephybun) [reply internal/services/mssql/mssql_database_resource_test.go:1043]: Appreciate the thought to make it easier and more robust to test the basic config for more skus!

My thoughts on this are that we don't typically test more than a few skus to ensure that they function so I don't see a _huge_ need for this. We do prefer using explicit configs where possible rather than parameterised and it is non-standard to validate testing configs in the provider. All up this would be introducing a new "inconsistency" into the provider, which given the size of the code base and the many contributors we have, we try not to do since it makes keeping standard practices and reviews more difficult.

Given the reasons above I would prefer to see this validation in the config removed, the test case is perfectly valid though.

Comment (cdituri) [reply internal/services/mssql/mssql_database_resource_test.go:1043]: Thank you for the feedback and makes sense @stephybun. I originally had the test configuration explicit. Had a gut feeling that would be preferred; a large part of the reason I called this bit out via comment. I should have listed to my instinct, keep it simple 🙃

An easy change, and I will fixup as you've instructed. Cheers.

**Comment by cdituri** [comment]
@stephybun I addressed your https://github.com/hashicorp/terraform-provider-azurerm/pull/26894#discussion_r1716476019 and made the test configuration explicit. If there's anything else you'd like changed just let me know. Cheers.

**Review by stephybun — APPROVED** [review]
Tests look good, thanks for this @cdituri. LGTM 💯
