### PR TITLE
r/private_endpoint: normalizing the private_connection_resource_id for a redis cache

### LINKED ISSUE #20413: 3.43.0 redis id changed in casing, causes recreation of private endpoint
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.8

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### Terraform Configuration Files

```hcl
resource "azurerm_redis_cache" "redis_cache" {
  name                          = "${var.environment}-redis-cache"
  location                      = azurerm_resource_group.esc.location
  resource_group_name           = azurerm_resource_group.esc.name
  capacity                      = var.redis_capacity
  family                        = "C"
  sku_name                      = "Standard"
  public_network_access_enabled = false
  redis_version                 = 6

  redis_configuration {
    notify_keyspace_events = "Egx"
  }

  patch_schedule {
    day_of_week    = "wednesday"
    start_hour_utc = 16
  }
  patch_schedule {
    day_of_week    = "thursday"
    start_hour_utc = 16
  }
  tags = {
    "managedBy" = "terraform"
  }
}

resource "azurerm_private_endpoint" "redis_private_endpoint" {
  name                = "${var.environment}-redis"
  location            = azurerm_resource_group.esc.location
  resource_group_name = azurerm_resource_group.esc.name
  subnet_id           = azurerm_subnet.esc.id

  private_service_connection {
    name                           = "redis"
    private_connection_resource_id = azurerm_redis_cache.redis_cache.id
    is_manual_connection           = false
    subresource_names              = ["RedisCache"]
  }
  private_dns_zone_group {
    name                 = "redis-${var.environment}"
    private_dns_zone_ids = [data.azurerm_private_dns_zone.redis_dns_zone.id]
  }
  tags = {
    "managedBy" = "terraform"
  }
}
```

### Debug Output/Panic Output

```shell
{"@level":"info","@message":"azurerm_private_endpoint.redis_private_endpoint: Plan to replace","@module":"terraform.ui","@timestamp":"2023-02-10T10:02:38.841369Z","change":{"resource":{"addr":"azurerm_private_endpoint.redis_private_endpoint","module":"","resource":"azurerm_private_endpoint.redis_private_endpoint","implied_provider":"azurerm","resource_type":"azurerm_private_endpoint","resource_name":"redis_private_endpoint","resource_key":null},"action":"replace","reason":"cannot_update"},"type":"planned_change"}
```

### Expected Behaviour

No recreation of the private endpoint

### Actual Behaviour

The change of the redis resource id (Redis => redis) is causing a recreation of the private endpoint.

grafik

My workaround:
```terraform
  lifecycle {
    ignore_changes = [
      private_service_connection["private_connection_resource_id"]
    ]
  }
```

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

#20313

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Fixes #20413

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🪴

File: internal/services/network/private_endpoint_resource.go [hunk 1]
```diff
@@ -873,6 +874,11 @@ func flattenPrivateLinkEndpointServiceConnection(serviceConnections *[]network.P
 						privateConnectionId = serverId.ID()
 					}
 				}
+				if strings.Contains(strings.ToLower(privateConnectionId), "microsoft.redis") {
```
Comment (wiebeck) [inline internal/services/network/private_endpoint_resource.go:877]: @tombuildsstuff Sorry about my dumb question, but we're facing the same issue this PR is supposed to fix but the `private_connection_resource_id` contains `Microsoft.Cache/Redis` / `Microsoft.Cache/redis` and not just `Microsoft.Redis` or `Microsoft.redis`. Is this a different id? Does this PR actually fix the issue then?
