### PR TITLE
`azurerm_public_ip` - fix ddos diff from old version

### LINKED ISSUE #19855: azurerm_public_ip inconsistent state of ddos_protection_mode argument after provider upgraded to version > 3.30
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.37.0

### Affected Resource(s)/Data Source(s)

azurerm_public_ip

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 3.30"
    }
  }
}

provider "azurerm" {
  features {
  }
  skip_provider_registration = true
}

resource "azurerm_public_ip" "test_ip" {
  name = "test-ip"
  resource_group_name = "Terraform"
  location = "westeurope"
  allocation_method = "Static"
  sku = "Standard"
  tags = {
    env = "Test"
  }
}
```

### Debug Output/Panic Output

```shell
>terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_public_ip.test_ip will be created
  + resource "azurerm_public_ip" "test_ip" {
      + allocation_method       = "Static"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + idle_timeout_in_minutes = 4
      + ip_address              = (known after apply)
      + ip_version              = "IPv4"
      + location                = "westeurope"
      + name                    = "test-ip"
      + resource_group_name     = "Terraform"
      + sku                     = "Standard"
      + sku_tier                = "Regional"
      + tags                    = {
          + "env" = "Test"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_public_ip.test_ip: Creating...
azurerm_public_ip.test_ip: Creation complete after 3s [id=/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/Terraform/providers/Microsoft.Network/publicIPAddresses/test-ip]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

>terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 3.30.0"...
- Installing hashicorp/azurerm v3.37.0...
- Installed hashicorp/azurerm v3.37.0 (signed by HashiCorp)

>terraform plan

azurerm_public_ip.test_ip: Refreshing state... [id=/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/Terraform/providers/Microsoft.Network/publicIPAddresses/test-ip]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_public_ip.test_ip will be updated in-place
  ~ resource "azurerm_public_ip" "test_ip" {
      + ddos_protection_mode    = "VirtualNetworkInherited"
        id                      = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/Terraform/providers/Microsoft.Network/publicIPAddresses/test-ip"
        name                    = "test-ip"
        tags                    = {
            "env" = "Test"
        }
        # (10 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

No changes. Your infrastructure matches the configuration.

### Actual Behaviour

  # azurerm_public_ip.test_ip will be updated in-place
  ~ resource "azurerm_public_ip" "test_ip" {
      + ddos_protection_mode    = "VirtualNetworkInherited"
        id                      = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/Terraform/providers/Microsoft.Network/publicIPAddresses/test-ip"
        name                    = "test-ip"
        tags                    = {
            "env" = "Test"
        }
        # (10 unchanged attributes hidden)
    }

### Steps to Reproduce

1. terraform apply
2. terraform init -upgrade
3. terraform plan

### Important Factoids

_No response_

### References

Problem is caused by #19206

### PR DESCRIPTION
**Pull request by teowa**
resolves #19855
`azurerm_public_ip` resource provisioned in 3.30 or older version of azurerm provider (network@2021-08-01) has no `ddos_protection_mode` property in (network@2022-05-01) API response, but newly provisioned resource will have `ddos_protection_mode = 'VirtualNetworkInherited'` as default value in API response. related to https://github.com/Azure/azure-rest-api-specs/issues/22068

### CODE REVIEW

File: internal/services/network/public_ip_resource.go [hunk 1]
```diff
@@ -73,6 +73,9 @@ func resourcePublicIp() *pluginsdk.Resource {
 					string(network.DdosSettingsProtectionModeVirtualNetworkInherited),
 				}, false),
 				Default: string(network.DdosSettingsProtectionModeVirtualNetworkInherited),
+				DiffSuppressFunc: func(_, old, new string, _ *pluginsdk.ResourceData) bool {
+					return old == "" && new == string(network.DdosSettingsProtectionModeVirtualNetworkInherited)
+				},
```
Comment (tombuildsstuff) [inline internal/services/network/public_ip_resource.go:78]: Rather than adding a workaround, we should instead look to set the appropriate default value in the Read function when this is not returned but implied - as such can we look to update this to default this value in the Read function if it's not returned from the API?

We should also raise an API bug over this, since the API should be returning the value here if it's implied from a previous version?

Comment (teowa) [reply internal/services/network/public_ip_resource.go]: This makes sense. I have changed code.

**Review by katbyte — APPROVED** [review]
LGTM 📟
