### PR TITLE
`azurerm_servicebus_namespace_disaster_recovery_config`: support alias_authorization_rule_id

### LINKED ISSUE #18743: ServiceBus Geo Replication Resource returning null value for alias attributes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.26.0

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace_disaster_recovery_config 

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "servicebus-replication"
  location = "West Europe"
}

resource "azurerm_servicebus_namespace" "primary" {
  name                = "servicebus-primary"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Premium"
  capacity            = "1"
}

resource "azurerm_servicebus_namespace" "secondary" {
  name                = "servicebus-secondary"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Premium"
  capacity            = "1"
}

resource "azurerm_servicebus_namespace_disaster_recovery_config" "example" {
  name                 = "servicebus-alias-name"
  primary_namespace_id = azurerm_servicebus_namespace.primary.id
  partner_namespace_id = azurerm_servicebus_namespace.secondary.id
}
```

### Debug Output/Panic Output
Error: Missing required argument
│
│   with module.servicebus_namespace_001scmshard.module.keyvaultsecretupdate.azurerm_key_vault_secret.secret_updation["default_primary_connection_string"],
│   on .terraform\modules\servicebus_namespace_001scmshard\KeyVaultSecretUpdate\main.tf line 14, in resource "azurerm_key_vault_secret" "secret_updation":
│   14:   value        = each.value.value
│
│ The argument "value" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   with module.servicebus_namespace_001scmshard.module.keyvaultsecretupdate.azurerm_key_vault_secret.secret_updation["default_secondary_connection_string"],
│   on .terraform\modules\servicebus_namespace_001scmshard\KeyVaultSecretUpdate\main.tf line 14, in resource "azurerm_key_vault_secret" "secret_updation":
│   14:   value        = each.value.value
│
│ The argument "value" is required, but no definition was found.
```shell
NA
```

### Expected Behaviour

Upon creation of the disaster recovery config, terraform should export the attribute value for aliases (primary and secondary) on to the state file. 

primary_connection_string_alias  &  secondary_connection_string_alias both the attribute values are being returned as NULL.

The value of the alias is correct in the portal when we browse to the service bus geo replication page and look at the shared access policy. But it is not returned properly in the attribute instead null is returned.

### Actual Behaviour

primary_connection_string_alias and secondary_connection_string_alias attribute IDs when referenced or retrieved are being returned as NULL values.

### Steps to Reproduce

create 2 service bus name spaces.
setup geo replication between both the service bus namespaces
retrieve the attribute value of primary_connection_string_alias and secondary_connection_string_alias in the output and it will throw an error.

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by xiaxyi**
The dr alias connection string should be accessed by specifying the shared access policy which is having a default value `RootManageSharedAccessKey`, instead of using the alias name directly. 

fix failed acc tests"
`testcase.go:110: Step 1/1 error: Check failed: Check 4/7 error: data.azurerm_servicebus_namespace_disaster_recovery_config.test: Attribute 'primary_connection_string_alias' expected to be set`

in this pr, also add importSteps in test cases for servicebus

fix #18743

### CODE REVIEW

File: internal/services/servicebus/servicebus_namespace_disaster_recovery_config_data_source.go [hunk 1]
```diff
@@ -50,6 +51,12 @@ func dataSourceServiceBusNamespaceDisasterRecoveryConfig() *pluginsdk.Resource {
 				AtLeastOneOf: []string{"namespace_id", "resource_group_name", "namespace_name"},
 			},
 
+			"auth_rule_id_of_the_alias": {
```
Comment (katbyte) [inline internal/services/servicebus/servicebus_namespace_disaster_recovery_config_data_source.go:54]: I think this would be better as
```suggestion
			"alias_authorization_rule_id": {
```

**Review by katbyte — CHANGES_REQUESTED** [review]

**Comment by xiaxyi** [comment]
Thanks @katbyte , updated the property name
