### PR TITLE
`azurerm_web_pubsub_hub` - remove uai validation to support token audience as a valid input

### LINKED ISSUE #28086: Support for audience in azurerm_web_pubsub_hub handlers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

When configuring an event handler for Azure Web PubSub using the portal I can specify the issued token audience using a value like `api://AzureADTokenExchange`. This is accepted and the pubsub service is able to generate Entra Id tokens with this audience.

image

It is also possible to accomplish the same results using the [az cli](https://learn.microsoft.com/en-us/cli/azure/webpubsub/hub?view=azure-cli-latest#az-webpubsub-hub-create-optional-parameters)

```
az webpubsub hub create \
 --hub-name TestHub \
 --name my-test-pubsub \
 --resource-group test-rg \
 --allow-anonymous false \
 --event-handler \
   url-template="https://example/v1/test/eventhandler/{event}" \
   system-event="connect" \
   auth-type="ManagedIdentity" \
   auth-resource="api://AzureADTokenExchange"

```

But when using terraform I only have the option `auth.managed_identity_id`. Trying to use this attribute returns an error:

```
resource "azurerm_web_pubsub_hub" "my_hub" {
  ...  
  event_handler {
   ....
    auth {
      managed_identity_id = "api://AzureADTokenExchange"
    }
  }
} 
```
The error:
```
Error: expected "event_handler.0.auth.0.managed_identity_id" to be a valid UUID, got api://AzureADTokenExchange
Error: parsing "api://AzureADTokenExchange": parsing the UserAssignedIdentity ID: the number of segments didn't match
```

### New or Affected Resource(s)/Data Source(s)

azurerm_web_pubsub_hub

### Potential Terraform Configuration

```hcl
resource "azurerm_web_pubsub_hub" "example" {
  ...

  event_handler {
    ...
    auth {
      auth_resource = "uri://myUri"
    }
  }
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_pubsub_hub
https://learn.microsoft.com/en-us/cli/azure/webpubsub/hub?view=azure-cli-latest#az-webpubsub-hub-create-optional-parameters

### PR DESCRIPTION
**Pull request by xiaxyi**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

--- PASS: TestAccWebPubsubHub_usingAuthTokenAudience (235.14s)
--- PASS: TestAccWebPubsubHub_usingAuthGuid (251.78s)
--- PASS: TestAccWebPubsubHub_usingAuthUpdate (416.97s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/signalr       441.325s

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #28086 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/signalr/web_pubsub_hub_resource.go [hunk 1]
```diff
@@ -95,12 +94,9 @@ func resourceWebPubSubHub() *pluginsdk.Resource {
...
 									"managed_identity_id": {
-										Type:     pluginsdk.TypeString,
-										Required: true,
-										ValidateFunc: validation.Any(
-											validation.IsUUID,
-											commonids.ValidateUserAssignedIdentityID,
-										),
+										Type:         pluginsdk.TypeString,
+										Required:     true,
+										ValidateFunc: validation.StringIsNotEmpty,
```
Comment (catriona-m) [inline internal/services/signalr/web_pubsub_hub_resource.go:99]: rather than removing the existing validation, would it be possible to include additional validation for the token audience instead?

**Review by catriona-m — CHANGES_REQUESTED** [review]
Hi @xiaxyi thanks for submitting this. I left one suggestion inline for you to consider, but once that is addressed I can take another look. Thanks!

File: internal/services/signalr/web_pubsub_hub_resource.go (hunk 1 above)
Comment (xiaxyi) [reply internal/services/signalr/web_pubsub_hub_resource.go:99]: @catriona-m Thanks for the review! I checked the api definition and also confirmed with the service team. There isn't any validation to the user's input of the string, any string set to this `managed_identity_id` will be accepted by the api, however, there will be error when the token is actually used. So I don't think we need to add any validation to it neither, WDYT?

**Comment by xiaxyi** [comment]
@catriona-m Please see my response inline. let me know if you have any questions. Thanks!

File: internal/services/signalr/web_pubsub_hub_resource.go (hunk 1 above)
Comment (catriona-m) [reply internal/services/signalr/web_pubsub_hub_resource.go:99]: thanks @xiaxyi - if this can be any string then I think we can leave this as it is

**Comment by xiaxyi** [comment]
@catriona-m Good day! Do you have any other comments regarding this PR? Let me know if there is any! Thanks!

**Review by catriona-m — APPROVED** [review]
Thanks @xiaxyi LGTM!
