### PR TITLE
bug: removing checking of futures during deletion

### LINKED ISSUE #12852: Provider crash on frontdoor destruction
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
 terraform -v
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0
```

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

```
azurerm_frontdoor.this: Destroying... [id=/subscriptions/4e094144-afbc-420a-8d74-a4a0da618a3b/resourceGroups/fxs-ops-frontdoor-poc/providers/Microsoft.Network/frontDoors/fxs-ops-poc]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.70.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x58ba3c7]

goroutine 31 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor.resourceFrontDoorDelete(0xc001820a80, 0x6376e00, 0xc0002ea700, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor/frontdoor_resource.go:810 +0x247
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc000c02d20, 0x73098c8, 0xc0012d6240, 0xc001820a80, 0x6376e00, 0xc0002ea700, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:369 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000c02d20, 0x73098c8, 0xc0012d6240, 0xc0018302a0, 0xc0011ddf80, 0x6376e00, 0xc0002ea700, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:428 +0x8f7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002855d8, 0x73098c8, 0xc0012d6240, 0xc00138e3c0, 0xc0012d6240, 0x6857f00, 0xc001b44400)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000743c20, 0x7309970, 0xc0012d6240, 0xc001830000, 0xc000743c20, 0xc001b444e0, 0xc0002c4ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x6857f00, 0xc000743c20, 0x7309970, 0xc001b444e0, 0xc0010841e0, 0x0, 0x7309970, 0xc001b444e0, 0xc000847800, 0x176b)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00049c700, 0x7355a18, 0xc000299c80, 0xc0017ac5a0, 0xc0010664e0, 0xa8d0140, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00049c700, 0x7355a18, 0xc000299c80, 0xc0017ac5a0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000ac2e30, 0xc00049c700, 0x7355a18, 0xc000299c80, 0xc0017ac5a0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.70.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### PR DESCRIPTION
**Pull request by tombuildsstuff**
These exist for users who are running `terraform destroy` without a refresh, but that behaviour isn't intentionally supported (we explicitly recommend users run a refresh/plan before any change); as such removing these isn't considered a breaking change and works around an issue in the Azure SDK

Fixes #12852

### CODE REVIEW

File: internal/services/containers/container_registry_resource.go [hunk 1]
```diff
@@ -837,17 +836,11 @@ func resourceContainerRegistryDelete(d *pluginsdk.ResourceData, meta interface{}
 
 	future, err := client.Delete(ctx, resourceGroup, name)
 	if err != nil {
-		if response.WasNotFound(future.Response()) {
-			return nil
-		}
-		return fmt.Errorf("issuing Azure ARM delete request of Container Registry '%s': %+v", name, err)
+		return fmt.Errorf("deleting Container Registry %q (Resource Group %q) to be deleted: %+v", name, resourceGroup, err)
```
Comment (jackofallops) [inline internal/services/containers/container_registry_resource.go:839]:
```suggestion
		return fmt.Errorf("deleting Container Registry %q (Resource Group %q): %+v", name, resourceGroup, err)
```

File: internal/services/eventgrid/eventgrid_domain_topic_resource.go [hunk 2]
```diff
@@ -150,17 +149,11 @@ func resourceEventGridDomainTopicDelete(d *pluginsdk.ResourceData, meta interfac
 
 	future, err := client.Delete(ctx, id.ResourceGroup, id.DomainName, id.TopicName)
 	if err != nil {
-		if response.WasNotFound(future.Response()) {
-			return nil
-		}
-		return fmt.Errorf("deleting EventGrid Domain Topic %q: %+v", id.TopicName, err)
+		return fmt.Errorf("deleting of %s: %+v", *id, err)
```
Comment (jackofallops) [inline internal/services/eventgrid/eventgrid_domain_topic_resource.go:152]:
```suggestion
		return fmt.Errorf("deleting %s: %+v", *id, err)
```

File: internal/services/frontdoor/frontdoor_resource.go [hunk 3]
```diff
@@ -807,18 +807,11 @@ func resourceFrontDoorDelete(d *pluginsdk.ResourceData, meta interface{}) error
...
-		}
 		return fmt.Errorf("deleting Front Door %q (Resource Group %q): %+v", id.Name, id.ResourceGroup, err)
 	}
 	if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
-		if future.Response() != nil {
-			if !response.WasNotFound(future.Response()) {
-				return fmt.Errorf("waiting for deleting Front Door %q (Resource Group %q): %+v", id.Name, id.ResourceGroup, err)
-			}
+		if !response.WasNotFound(future.Response()) {
+			return fmt.Errorf("waiting for deleting Front Door %q (Resource Group %q): %+v", id.Name, id.ResourceGroup, err)
```
Comment (jackofallops) [inline internal/services/frontdoor/frontdoor_resource.go:814]:
```suggestion
			return fmt.Errorf("waiting for deletion of Front Door %q (Resource Group %q): %+v", id.Name, id.ResourceGroup, err)
```

**Review by jackofallops — APPROVED** [review]
Thanks @tombuildsstuff - just a few minor observations, but otherwise LGTM 👍
