### PR TITLE
`azurerm_subnet` - add delegation `Microsoft.BareMetal/AzureHostedService`

### LINKED ISSUE #21862: azurerm_subnet - missing delgation service
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

azurerm_subnet is missing:

service_delegation {
     # name    = "Microsoft.BareMetal/AzureHostedService"

It was added in October 2022.

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.4.6

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

azurerm v3.55.0

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network" "main" {
  name = "TME-terra-metal"
  location                    = azurerm_resource_group.main.location
  resource_group_name         = azurerm_resource_group.main.name
  address_space               = ["10.0.0.0/26"]
  dns_servers                 = ["8.8.8.8", "1.1.1.1"]
}

resource "azurerm_subnet" "main" {
  name         = "Terra-AHV"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes   = ["10.0.0.0/27"]
  delegation {
    name = "delegation"

    service_delegation {
      name    = "Microsoft.BareMetal/AzureHostedService"
      
    }
  }

}

resource "azurerm_virtual_network" "mainpc" {
  name                        = "TME-terra-PC"
  location                    = azurerm_resource_group.main.location
  resource_group_name         = azurerm_resource_group.main.name
  address_space               = ["10.0.10.0/24"]
  dns_servers                 = ["8.8.8.8", "1.1.1.1"]

  subnet {
    name           = "Terra-FlowInteral"
    address_prefix = "10.0.10.32/27"
  }
}

resource "azurerm_subnet" "mainpc" {
  name         = "Terra-PC"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.mainpc.name
  address_prefixes   = ["10.0.10.0/27"]
  #delegation {
    #name = "delegation"

    #service_delegation {
     # name    = "Microsoft.BareMetal/AzureHostedService"
      
    #}
  #}

}
resource "azurerm_subnet" "mainpcEXT" {
  name         = "Terra-FlowExternal"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.mainpc.name
  address_prefixes   = ["10.0.10.128/26"]
  #delegation {
    #name = "delegation"

    #service_delegation {
     # name    = "Microsoft.BareMetal/AzureHostedService"
      
    #}
  #}

}
resource "azurerm_public_ip_prefix" "tme_gw_ahv" {
  name                = "TME-AHV-nat-pre"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  ip_version          = "IPv4"
  prefix_length       = 29
  sku                 = "Standard"
  zones               = ["1"]
}
resource "azurerm_nat_gateway" "tme_gw_ahv" {
  name                    = "natgw-ahv"
  resource_group_name     = azurerm_resource_group.main.name
  location                = azurerm_resource_group.main.location
  sku_name                = "Standard"
  idle_timeout_in_minutes = 10
  zones                   = ["1"]
  tags                    = {"fastpathenabled" = "true"}
}

resource "azurerm_public_ip" "tme_gw_ahv" {
  name                = "tme_gw_ahv-PIP"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"
  zones               = ["1"]
}

resource "azurerm_nat_gateway_public_ip_association" "tme_gw_ahv" {
  nat_gateway_id       = azurerm_nat_gateway.tme_gw_ahv.id
  public_ip_address_id = azurerm_public_ip.tme_gw_ahv.id
}

resource "azurerm_nat_gateway_public_ip_prefix_association" "tme_gw_ahv" {
  nat_gateway_id      = azurerm_nat_gateway.tme_gw_ahv.id
  public_ip_prefix_id = azurerm_public_ip_prefix.tme_gw_ahv.id

}

resource "azurerm_subnet_nat_gateway_association" "tme_gw_ahv" {
  subnet_id      = azurerm_subnet.main.id
  nat_gateway_id = azurerm_nat_gateway.tme_gw_ahv.id
}

output "gateway_ips" {
  value = azurerm_public_ip_prefix.tme_gw_ahv.ip_prefix
}

######################## - Azure PC 
resource "azurerm_public_ip_prefix" "tme_gw_PC" {
  name                = "TME-PX-nat-pre"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  ip_version          = "IPv4"
  prefix_length       = 29
  sku                 = "Standard"
  zones               = ["1"]
}

resource "azurerm_nat_gateway" "tme_gw_PC" {
  name                    = "natgw-PC"
  resource_group_name     = azurerm_resource_group.main.name
  location                = azurerm_resource_group.main.location
  sku_name                = "Standard"
  idle_timeout_in_minutes = 10
  zones                   = ["1"]
  tags                    = {"fastpathenabled" = "true"}
}

resource "azurerm_public_ip" "tme_gw_PC" {
  name                = "tme_gw_PC-PIP"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"
  zones               = ["1"]                
}

resource "azurerm_nat_gateway_public_ip_association" "tme_gw_PC" {
  nat_gateway_id       = azurerm_nat_gateway.tme_gw_PC.id
  public_ip_address_id = azurerm_public_ip.tme_gw_PC.id
}

resource "azurerm_nat_gateway_public_ip_prefix_association" "tme_gw_PC" {
  nat_gateway_id      = azurerm_nat_gateway.tme_gw_PC.id
  public_ip_prefix_id = azurerm_public_ip_prefix.tme_gw_PC.id

}

resource "azurerm_subnet_nat_gateway_association" "tme_gw_PC" {
  subnet_id      = azurerm_subnet.mainpc.id
  nat_gateway_id = azurerm_nat_gateway.tme_gw_PC.id
}

resource "azurerm_subnet_nat_gateway_association" "tme_gw_PC2" {
  subnet_id      = azurerm_subnet.mainpcEXT.id
  nat_gateway_id = azurerm_nat_gateway.tme_gw_PC.id
}

output "gateway_PC_ips" {
  value = azurerm_public_ip_prefix.tme_gw_PC.ip_prefix
}

resource "azurerm_virtual_network_peering" "main" {
  name                      = "peer1to2"
  resource_group_name       = azurerm_resource_group.main.name
  virtual_network_name      = azurerm_virtual_network.main.name
  remote_virtual_network_id = azurerm_virtual_network.mainpc.id
}

resource "azurerm_virtual_network_peering" "mainpc" {
  name                      = "peer2to1"
  resource_group_name       = azurerm_resource_group.main.name
  virtual_network_name      = azurerm_virtual_network.mainpc.name
  remote_virtual_network_id = azurerm_virtual_network.main.id
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected delegation.0.service_delegation.0.name to be one of [Microsoft.ApiManagement/service Microsoft.AzureCosmosDB/clusters Microsoft.BareMetal/AzureVMware Microsoft.BareMetal/CrayServers Microsoft.Batch/batchAccounts Microsoft.ContainerInstance/containerGroups Microsoft.ContainerService/managedClusters Microsoft.Databricks/workspaces Microsoft.DBforMySQL/flexibleServers Microsoft.DBforMySQL/serversv2 Microsoft.DBforPostgreSQL/flexibleServers Microsoft.DBforPostgreSQL/serversv2 Microsoft.DBforPostgreSQL/singleServers Microsoft.HardwareSecurityModules/dedicatedHSMs Microsoft.Kusto/clusters Microsoft.Logic/integrationServiceEnvironments Microsoft.LabServices/labplans Microsoft.MachineLearningServices/workspaces Microsoft.Netapp/volumes Microsoft.Network/dnsResolvers Microsoft.Network/managedResolvers Microsoft.PowerPlatform/vnetaccesslinks Microsoft.ServiceFabricMesh/networks Microsoft.Sql/managedInstances Microsoft.Sql/servers Microsoft.StoragePool/diskPools Microsoft.StreamAnalytics/streamingJobs Microsoft.Synapse/workspaces Microsoft.Web/hostingEnvironments Microsoft.Web/serverFarms Microsoft.Orbital/orbitalGateways NGINX.NGINXPLUS/nginxDeployments PaloAltoNetworks.Cloudngfw/firewalls Qumulo.Storage/fileSystems], got Microsoft.BareMetal/AzureHostedService
│
│   with azurerm_subnet.main,
│   on network.tf line 18, in resource "azurerm_subnet" "main":
│   18:       name    = "Microsoft.BareMetal/AzureHostedService"
```

### Expected Behaviour

Should proceed assuming the customer has the service registered

### Actual Behaviour

Microsoft.BareMetal/AzureHostedService is not listed

### Steps to Reproduce

terraform apply the code attached

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by myc2h6o**
Close #21862

### CODE REVIEW

File: internal/services/network/subnet_resource.go [hunk 1]
```diff
@@ -27,6 +27,7 @@ var SubnetResourceName = "azurerm_subnet"
 var subnetDelegationServiceNames = []string{
 	"Microsoft.ApiManagement/service",
 	"Microsoft.AzureCosmosDB/clusters",
+	"Microsoft.BareMetal/AzureHostedService",
```
Comment (catriona-m) [inline internal/services/network/subnet_resource.go:30]: could we also add this to the list of possible values in the docs?

Comment (myc2h6o) [reply internal/services/network/subnet_resource.go:30]: sure, I've updated the document  as well

**Review by catriona-m — APPROVED** [review]
Thanks @myc2h6o LGTM!
