### PR TITLE
azurerm_virtual_network , azurerm_subnet: Add 'Informatica.DataManagement/organizations' service name to service endpoint allowed values.

### LINKED ISSUE #27946: Delegation service Informatica.DataManagement/organizations not available when deploying an Informatica azurerm_subnet
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.9.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "this" {
  #checkov:skip=CKV2_AZURE_31:already implemented via another template
  for_each = var.subnets

  name                                          = "${each.value.global_parameters.prefix}-${upper(each.value.global_parameters.region)}-${upper(each.value.global_parameters.environment_short)}-${each.value.suffix}-${each.value.description}"
  resource_group_name                           = each.value.resource_group_name
  virtual_network_name                          = each.value.virtual_network_name
  address_prefixes                              = each.value.address_prefixes
  private_endpoint_network_policies             = each.value.private_endpoint_network_policies
  private_link_service_network_policies_enabled = each.value.private_link_service_network_policies_enabled
  service_endpoints                             = each.value.service_endpoints

  dynamic "delegation" {
    for_each = each.value.delegation
    iterator = item

    content {
      name = item.value.name

      service_delegation {
        name    = item.value.service
        actions = var.subnet_delegations_actions[item.value.service]
      }
    }
  }
}


variables.tf

# Required input variables
variable "subnets" {
  description = "Subnets settings"
  type = map(object({
    suffix                                        = string
    description                                   = string
    resource_group_name                           = string
    virtual_network_name                          = string
    address_prefixes                              = list(string)
    private_endpoint_network_policies             = string
    private_link_service_network_policies_enabled = bool
    service_endpoints                             = list(string)
    global_parameters                             = map(string)
    delegation = list(object({
      name    = string
      service = string
    }))
  }))
}

variable "subnet_delegations_actions" {
  type        = map(list(string))
  description = "List of subnet delegation actions"
  default = {
    "Microsoft.App/environments"                      = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Web/serverFarms"                       = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.ContainerInstance/containerGroups"     = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.Netapp/volumes"                        = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.HardwareSecurityModules/dedicatedHSMs" = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.ServiceFabricMesh/networks"            = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.Logic/integrationServiceEnvironments"  = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.Batch/batchAccounts"                   = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.Sql/managedInstances"                  = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action", "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"]
    "Microsoft.Web/hostingEnvironments"               = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.BareMetal/CrayServers"                 = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Databricks/workspaces"                 = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action", "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"]
    "Microsoft.BareMetal/AzureVMware"                 = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.StreamAnalytics/streamingJobs"         = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforPostgreSQL/serversv2"             = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.AzureCosmosDB/clusters"                = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.MachineLearningServices/workspaces"    = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforPostgreSQL/singleServers"         = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforPostgreSQL/flexibleServers"       = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforMySQL/serversv2"                  = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforMySQL/flexibleServers"            = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.ApiManagement/service"                 = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"]
    "Microsoft.Synapse/workspaces"                    = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.PowerPlatform/vnetaccesslinks"         = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Network/dnsResolvers"                  = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Kusto/clusters"                        = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action", "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"]
    "Microsoft.DelegatedNetwork/controller"           = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.ContainerService/managedClusters"      = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.PowerPlatform/enterprisePolicies"      = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.StoragePool/diskPools"                 = ["Microsoft.Network/virtualNetworks/read"]
    "Microsoft.DocumentDB/cassandraClusters"          = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Apollo/npu"                            = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.AVS/PrivateClouds"                     = ["Microsoft.Network/networkinterfaces/*"]
    "Informatica.DataManagement/organizations"        = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
  }
}

tfvars file entry:
subnets = {
  "informatica_subnet" = {
    suffix                                        = "XXX110"
    description                                   = "informatica"
    resource_group_name                           = "network_rg"
    virtual_network_name                          = "vnet"
    address_prefixes                              = ["xx.xx.xx.xx/26"]
    service_endpoints                             = []
    private_endpoint_network_policies             = "Disabled"
    private_link_service_network_policies_enabled = false
    delegation                                    = [
      {
        name    = "informatica"
        service = "Informatica.DataManagement/organizations"
      }
    ]
  }
}
```

### Debug Output/Panic Output

```shell
I get error when doing terraform plan:

╵
│ Error: expected delegation.0.service_delegation.0.name to be one of ["GitHub.Network/networkSettings" "Microsoft.ApiManagement/service" "Microsoft.Apollo/npu" "Microsoft.App/environments" "Microsoft.App/testClients" "Microsoft.AVS/PrivateClouds" "Microsoft.AzureCosmosDB/clusters" "Microsoft.BareMetal/AzureHostedService" "Microsoft.BareMetal/AzureHPC" "Microsoft.BareMetal/AzurePaymentHSM" "Microsoft.BareMetal/AzureVMware" "Microsoft.BareMetal/CrayServers" "Microsoft.BareMetal/MonitoringServers" "Microsoft.Batch/batchAccounts" "Microsoft.CloudTest/hostedpools" "Microsoft.CloudTest/images" "Microsoft.CloudTest/pools" "Microsoft.Codespaces/plans" "Microsoft.ContainerInstance/containerGroups" "Microsoft.ContainerService/managedClusters" "Microsoft.ContainerService/TestClients" "Microsoft.Databricks/workspaces" "Microsoft.DBforMySQL/flexibleServers" "Microsoft.DBforMySQL/servers" "Microsoft.DBforMySQL/serversv2" "Microsoft.DBforPostgreSQL/flexibleServers" "Microsoft.DBforPostgreSQL/serversv2" "Microsoft.DBforPostgreSQL/singleServers" "Microsoft.DelegatedNetwork/controller" "Microsoft.DevCenter/networkConnection" "Microsoft.DevOpsInfrastructure/pools" "Microsoft.DocumentDB/cassandraClusters" "Microsoft.Fidalgo/networkSettings" "Microsoft.HardwareSecurityModules/dedicatedHSMs" "Microsoft.Kusto/clusters" "Microsoft.LabServices/labplans" "Microsoft.Logic/integrationServiceEnvironments" "Microsoft.MachineLearningServices/workspaces" "Microsoft.Netapp/volumes" "Microsoft.Network/dnsResolvers" "Microsoft.Network/managedResolvers" "Microsoft.Network/fpgaNetworkInterfaces" "Microsoft.Network/networkWatchers." "Microsoft.Network/virtualNetworkGateways" "Microsoft.Orbital/orbitalGateways" "Microsoft.PowerPlatform/enterprisePolicies" "Microsoft.PowerPlatform/vnetaccesslinks" "Microsoft.ServiceFabricMesh/networks" "Microsoft.ServiceNetworking/trafficControllers" "Microsoft.Singularity/accounts/networks" "Microsoft.Singularity/accounts/npu" "Microsoft.Sql/managedInstances" "Microsoft.Sql/managedInstancesOnebox" "Microsoft.Sql/managedInstancesStage" "Microsoft.Sql/managedInstancesTest" "Microsoft.Sql/servers" "Microsoft.StoragePool/diskPools" "Microsoft.StreamAnalytics/streamingJobs" "Microsoft.Synapse/workspaces" "Microsoft.Web/hostingEnvironments" "Microsoft.Web/serverFarms" "NGINX.NGINXPLUS/nginxDeployments" "PaloAltoNetworks.Cloudngfw/firewalls" "Qumulo.Storage/fileSystems" "Oracle.Database/networkAttachments"], got Informatica.DataManagement/organizations
│ 
│   with module.az_subnets.azurerm_subnet.this["informatica_subnet"],
│   on ../../templates/az-subnets/main.tf line 5, in resource "azurerm_subnet" "this":
│    5:   name                                          = EDITED
```

### Expected Behaviour

I expect to be able to add the delegated service `Informatica.DataManagement/organizations` into the subnet

### Actual Behaviour

I get an output where it lists me all the services that can be delegated to the subnet, but Informatica is not present amogst them.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by CorrenSoft**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

- Added 'Informatica.DataManagement/organizations' to the allowed service names in subnet delegations.
- Updated docs, including some missing values in this property.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

`TestAccVirtualNetwork_edgeZone` fails because I was unable to register the `Microsoft.EdgeZones` in my subscription.
``` 
TF_ACC=1 go test -v ./internal/services/network -run=TestAccSubnet_ -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccSubnet_basic
=== PAUSE TestAccSubnet_basic
=== RUN   TestAccSubnet_basic_addressPrefixes
=== PAUSE TestAccSubnet_basic_addressPrefixes
=== RUN   TestAccSubnet_complete_addressPrefixes
=== PAUSE TestAccSubnet_complete_addressPrefixes
=== RUN   TestAccSubnet_update_addressPrefixes
=== PAUSE TestAccSubnet_update_addressPrefixes
=== RUN   TestAccSubnet_requiresImport
=== PAUSE TestAccSubnet_requiresImport
=== RUN   TestAccSubnet_disappears
=== PAUSE TestAccSubnet_disappears
=== RUN   TestAccSubnet_defaultOutbound
=== PAUSE TestAccSubnet_defaultOutbound
=== RUN   TestAccSubnet_delegation
=== PAUSE TestAccSubnet_delegation
=== RUN   TestAccSubnet_privateEndpointNetworkPolicies
=== PAUSE TestAccSubnet_privateEndpointNetworkPolicies
=== RUN   TestAccSubnet_enablePrivateLinkServiceNetworkPolicies
=== PAUSE TestAccSubnet_enablePrivateLinkServiceNetworkPolicies
=== RUN   TestAccSubnet_serviceEndpoints
=== PAUSE TestAccSubnet_serviceEndpoints
=== RUN   TestAccSubnet_serviceEndpointPolicy
=== PAUSE TestAccSubnet_serviceEndpointPolicy
=== RUN   TestAccSubnet_updateAddressPrefix
=== PAUSE TestAccSubnet_updateAddressPrefix
=== RUN   TestAccSubnet_privateLinkEndpointNetworkPoliciesValidateDefaultValues
=== PAUSE TestAccSubnet_privateLinkEndpointNetworkPoliciesValidateDefaultValues
=== RUN   TestAccSubnet_updateServiceDelegation
=== PAUSE TestAccSubnet_updateServiceDelegation
=== CONT  TestAccSubnet_basic
=== CONT  TestAccSubnet_enablePrivateLinkServiceNetworkPolicies
=== CONT  TestAccSubnet_privateEndpointNetworkPolicies
=== CONT  TestAccSubnet_updateServiceDelegation
=== CONT  TestAccSubnet_privateLinkEndpointNetworkPoliciesValidateDefaultValues
=== CONT  TestAccSubnet_updateAddressPrefix
=== CONT  TestAccSubnet_serviceEndpointPolicy
=== CONT  TestAccSubnet_serviceEndpoints
=== CONT  TestAccSubnet_requiresImport
--- PASS: TestAccSubnet_basic (663.11s)
--- PASS: TestAccSubnet_privateLinkEndpointNetworkPoliciesValidateDefaultValues (673.08s)
=== CONT  TestAccSubnet_delegation
--- PASS: TestAccSubnet_updateAddressPrefix (947.25s)
=== CONT  TestAccSubnet_defaultOutbound
--- PASS: TestAccSubnet_serviceEndpointPolicy (997.21s)
=== CONT  TestAccSubnet_disappears
--- PASS: TestAccSubnet_requiresImport (400.46s)
=== CONT  TestAccSubnet_complete_addressPrefixes
--- PASS: TestAccSubnet_enablePrivateLinkServiceNetworkPolicies (1141.77s)
=== CONT  TestAccSubnet_update_addressPrefixes
--- PASS: TestAccSubnet_updateServiceDelegation (1362.52s)
=== CONT  TestAccSubnet_basic_addressPrefixes
--- PASS: TestAccSubnet_disappears (397.12s)
--- PASS: TestAccSubnet_complete_addressPrefixes (534.19s)
--- PASS: TestAccSubnet_privateEndpointNetworkPolicies (1601.25s)
--- PASS: TestAccSubnet_serviceEndpoints (1626.95s)
--- PASS: TestAccSubnet_defaultOutbound (756.88s)
--- PASS: TestAccSubnet_basic_addressPrefixes (496.75s)
--- PASS: TestAccSubnet_update_addressPrefixes (931.00s)
--- PASS: TestAccSubnet_delegation (1399.83s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       2073.527s
```

```
make acctests SERVICE='network' TESTARGS='-run=TestAccVirtualNetwork_'

=== RUN   TestAccVirtualNetwork_basic
=== PAUSE TestAccVirtualNetwork_basic
=== RUN   TestAccVirtualNetwork_complete
=== PAUSE TestAccVirtualNetwork_complete
=== RUN   TestAccVirtualNetwork_updateFlowTimeoutInMinutes
=== PAUSE TestAccVirtualNetwork_updateFlowTimeoutInMinutes
=== RUN   TestAccVirtualNetwork_basicUpdated
=== PAUSE TestAccVirtualNetwork_basicUpdated
=== RUN   TestAccVirtualNetwork_requiresImport
=== PAUSE TestAccVirtualNetwork_requiresImport
=== RUN   TestAccVirtualNetwork_ddosProtectionPlan
=== PAUSE TestAccVirtualNetwork_ddosProtectionPlan
=== RUN   TestAccVirtualNetwork_disappears
=== PAUSE TestAccVirtualNetwork_disappears
=== RUN   TestAccVirtualNetwork_withTags
=== PAUSE TestAccVirtualNetwork_withTags
=== RUN   TestAccVirtualNetwork_deleteSubnet
=== PAUSE TestAccVirtualNetwork_deleteSubnet
=== RUN   TestAccVirtualNetwork_bgpCommunity
=== PAUSE TestAccVirtualNetwork_bgpCommunity
=== RUN   TestAccVirtualNetwork_edgeZone
=== PAUSE TestAccVirtualNetwork_edgeZone
=== RUN   TestAccVirtualNetwork_subnet
=== PAUSE TestAccVirtualNetwork_subnet
=== RUN   TestAccVirtualNetwork_subnetRouteTable
=== PAUSE TestAccVirtualNetwork_subnetRouteTable
=== CONT  TestAccVirtualNetwork_basic
=== CONT  TestAccVirtualNetwork_withTags
=== CONT  TestAccVirtualNetwork_requiresImport
=== CONT  TestAccVirtualNetwork_updateFlowTimeoutInMinutes
=== CONT  TestAccVirtualNetwork_complete
=== CONT  TestAccVirtualNetwork_disappears
=== CONT  TestAccVirtualNetwork_ddosProtectionPlan
=== CONT  TestAccVirtualNetwork_basicUpdated
--- PASS: TestAccVirtualNetwork_disappears (303.25s)
=== CONT  TestAccVirtualNetwork_subnetRouteTable
--- PASS: TestAccVirtualNetwork_requiresImport (309.25s)
=== CONT  TestAccVirtualNetwork_bgpCommunity
--- PASS: TestAccVirtualNetwork_withTags (335.75s)
=== CONT  TestAccVirtualNetwork_edgeZone
--- PASS: TestAccVirtualNetwork_complete (444.32s)
=== CONT  TestAccVirtualNetwork_deleteSubnet
--- PASS: TestAccVirtualNetwork_basic (467.37s)
=== CONT  TestAccVirtualNetwork_subnet
=== NAME  TestAccVirtualNetwork_edgeZone
    testcase.go:173: Step 1/3 error: Error running apply: exit status 1

        Error: no extended locations were found for the location "westus"

          with data.azurerm_extended_locations.test,
          on terraform_plugin_test.tf line 33, in data "azurerm_extended_locations" "test":
          33: data "azurerm_extended_locations" "test" {

--- FAIL: TestAccVirtualNetwork_edgeZone (172.68s)
--- PASS: TestAccVirtualNetwork_ddosProtectionPlan (520.09s)
--- PASS: TestAccVirtualNetwork_basicUpdated (712.80s)
--- PASS: TestAccVirtualNetwork_subnetRouteTable (490.02s)
--- PASS: TestAccVirtualNetwork_deleteSubnet (384.88s)
--- PASS: TestAccVirtualNetwork_updateFlowTimeoutInMinutes (901.06s)
--- PASS: TestAccVirtualNetwork_bgpCommunity (596.69s)
--- PASS: TestAccVirtualNetwork_subnet (468.62s)
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_virtual_network ` - support for  'Informatica.DataManagement/organizations' value on `delegation.service_delegation.name` property [GH-27946]
* `azurerm_subnet` - support for  'Informatica.DataManagement/organizations' value on `delegation.service_delegation.name` property [GH-27946]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27946

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/network/subnet_resource.go [hunk 1]
```diff
@@ -91,9 +92,9 @@ var subnetDelegationServiceNames = []string{
 	"Microsoft.Web/hostingEnvironments",
 	"Microsoft.Web/serverFarms",
 	"NGINX.NGINXPLUS/nginxDeployments",
+	"Oracle.Database/networkAttachments",
```
Comment (stephybun) [inline internal/services/network/subnet_resource.go:95]: Thank you so much for fixing the ordering here ❤️

**Review by stephybun — APPROVED** [review]
Thanks @CorrenSoft LGTM 🍯

File: internal/services/network/subnet_resource.go (hunk 1 above)
Comment (alexivanov-danone) [reply internal/services/network/subnet_resource.go:95]: I cannot believe that you guys actually merged my request for Informatica. Amazing. Thanks a lot!!!
