### PR TITLE
`azurerm_ai_foundry_project`: add support for `primary_user_assigned_identity`

### LINKED ISSUE #29074: azurerm_ai_foundry_project 400 internal error when using 'UserAssigned' identity type
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.11.2

### AzureRM Provider Version

v4.22.0 and v4.23.0

### Affected Resource(s)/Data Source(s)

azurerm_ai_foundry_project

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "rg" {
  name     = "testrg"
}

resource "azurerm_user_assigned_identity" "project1_identity" {
  name                = "p1_ai_project_identity_${random_string.this.result}"
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location
  tags = {
    Owner = "PD"
  }
}

resource "azurerm_ai_foundry_project" "projects" {
  name               = "project1_test_${random_string.this.result}"
  location           = data.azurerm_resource_group.rg.location
  ai_services_hub_id = var.ai_foundry_hub_id
  description        = "Test project"
  friendly_name      = "Project 1"
  tags               = {
    "Env" = "Test"
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.project1_identity.id]
    }
}
```

### Debug Output/Panic Output

```shell
│   with azurerm_ai_foundry_project.projects,
│   on main.tf line XXX, in resource "azurerm_ai_foundry_project" "projects":
│  XXX: resource "azurerm_ai_foundry_project" "projects" {
│ 
│ creating Workspace (Subscription: "<subId>"
│ Resource Group Name: "<rgName>"
│ Workspace Name: "project1_test_5j8erjwz"): polling after CreateOrUpdate:
│ polling failed: the Azure API returned the following error:
│ 
│ Status: "InternalServerError"
│ Code: ""
│ Message: "Received 400 from a service request"
│ Activity Id: ""
│ 
│ ---
│ 
│ API Response:
│ 
│ ----[start]----
│ {
│   "status": "Failed",
│   "error": {
│     "code": "InternalServerError",
│     "message": "Received 400 from a service request"
│   }
│ }
│ -----[end]-----
│ 
╵
```

### Expected Behaviour

Deploy AI foundry project in an existing AI foundry hub with User Assigned Identity.

### Actual Behaviour

It fails with a 400 internal server error.

In the Azure portal Activity Log, I see error when:
- Creating the ML workspace: "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"InternalServerError\",\"message\":\"Received 400 from a service request\"}]}}"
    This operation is initiiated by the deployment sp
- Assigning permissions on the hub associated storage account, Key Vault, ACR fail with the following message: statusMessage": "{\"error\":{\"code\":\"InvalidRequestContent\",\"message\":\"The content of your request was not valid, and the original object could not be deserialized. Exception message: 'Required property 'principalId' expects a value but got null. Path 'Properties', line 1, position 327.'\"}}",
    This operation is initiated by Azure Machine Learning enterprise app.

I have already assigned a number of roles to the project user assigned identity ("Storage Blob Data Contributor", "Storage Blob Data Owner",  "Storage File Data Privileged Contributor", "Azure AI Inference Deployment Operator", "Key Vault Administrator", "Cognitive Services Contributor", "Azure AI Administrator", "Search Index Data Reader", "Search Index Data Contributor", "Search Service Contributor", so that I ensure here are no permission issues.
The deployment SP have 'Contributor' over the deployment RG. The AI foundry hub is created with User Assigned Identity and CMK.

### Steps to Reproduce

1. Deploy AI Foudry Hub with ACR, KV, SA, CMK and User assigned identity
2. Create the user assigned identity and grant it permissions over the RG/resources;
3. Apply the azurerm_ai_foundry_project resource with user assigned identity

### Important Factoids

_No response_

### References

https://registry.terraform.io/providers/hashicorp/azurerm/4.22.0/docs/resources/ai_foundry_project

### PR DESCRIPTION
**Pull request by wuxu92**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

The user identity should specifid by separate field as `PrimaryUserAssignedIdentity`. API Spec reference: https://github.com/Azure/azure-rest-api-specs/blob/c488b4a741cb78f93514d7a9d3332d08ea7b32e1/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2024-04-01/workspaceRP.json#L1812

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_ai_foundry_project`: add support for `primary_user_assigned_identity` property [GH-29074]

This is a (please select all that apply):

- [x] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29074

### CODE REVIEW

File: internal/services/machinelearning/ai_foundry_project_resource.go [hunk 1]
```diff
@@ -105,6 +107,12 @@ func (r AIFoundryProject) Arguments() map[string]*pluginsdk.Schema {
 			ForceNew: true,
 		},
 
+		"primary_user_assigned_identity": {
+			Type:         pluginsdk.TypeString,
+			Optional:     true,
+			ValidateFunc: commonids.ValidateUserAssignedIdentityID,
```
Comment (catriona-m) [inline internal/services/machinelearning/ai_foundry_project_resource.go:113]: should we add that this is RequiredWith identity here?

File: internal/services/machinelearning/ai_foundry_project_resource_test.go [hunk 2]
```diff
@@ -115,6 +137,98 @@ resource "azurerm_ai_foundry_project" "test" {
 `, AIFoundry{}.basic(data), data.RandomInteger)
 }
 
+func (r AIFoundryProject) userIdentityTempalte(data acceptance.TestData) string {
```
Comment (catriona-m) [inline internal/services/machinelearning/ai_foundry_project_resource_test.go:140]:
```suggestion
func (r AIFoundryProject) userIdentityTemplate(data acceptance.TestData) string {
```

File: website/docs/r/ai_foundry_project.html.markdown [hunk 3]
```diff
@@ -71,10 +71,40 @@ resource "azurerm_ai_foundry" "example" {
...
+  tenant_id    = azurerm_user_assigned_identity.example.tenant_id
+  object_id    = azurerm_user_assigned_identity.example.client_id
+
+  key_permissions = [
+    "Create",
+    "Get",
+  ]
+}
+
+
```
Comment (catriona-m) [inline website/docs/r/ai_foundry_project.html.markdown:97]: since `identity` and `primary_user_assigned_identity` are optional properties, we don't need to include config for them in the example
```suggestion
```

File: website/docs/r/ai_foundry_project.html.markdown [hunk 4]
```diff
@@ -71,10 +71,40 @@ resource "azurerm_ai_foundry" "example" {
...
-  ai_services_hub_id = azurerm_ai_foundry.example.id
+  name                           = "example"
+  location                       = azurerm_ai_foundry.example.location
+  ai_services_hub_id             = azurerm_ai_foundry.example.id
+  primary_user_assigned_identity = azurerm_user_assigned_identity.example.id
+
+  identity {
+    type         = "UserAssigned"
+    identity_ids = [azurerm_user_assigned_identity.example.id]
+  }
```
Comment (catriona-m) [inline website/docs/r/ai_foundry_project.html.markdown:107]:
```suggestion
```

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks @wuxu92 - I left a couple of comments inline but once those are addressed we can take another look at this. Thanks!

**Comment by katiepatterson0** [comment]
Hi @wuxu92 ! We have reviewed this on the HashiCorp side and provided some comments to be addressed. Please review and then merge once you are finished if you're able. Thanks in advance!
