### PR TITLE
`azurerm_private_endpoint` Try to add retry on creation

### LINKED ISSUE #16182: `azurerm_private_endpoint` fails intermittently with retriable error
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

3.0.2

### Affected Resource(s)

* `azurerm_private_endpoint`

### Terraform Configuration Files

```hcl

resource "azurerm_private_endpoint" "acr" {
  name                = "${local.prefix}-${local.location_short}-acr-pe"
  location            = azurerm_resource_group.stamp.location
  resource_group_name = azurerm_resource_group.stamp.name
  subnet_id           = azurerm_subnet.private_endpoints.id

  private_dns_zone_group {
    name                 = "privatednsacr"
    private_dns_zone_ids = [azurerm_private_dns_zone.acr.id]
  }

  private_service_connection {
    name                           = "acr-privateserviceconnection"
    private_connection_resource_id = data.azurerm_container_registry.global.id
    is_manual_connection           = false
    subresource_names              = ["registry"]
  }

  tags = var.default_tags
}
```

### Expected Behaviour

Terraform should automatically retry retryable errors and not fail.

### Actual Behaviour

Sometimes during provisioning of a private endpoint, we have seen the following error. Looking into the Azure portal, the Private Endpoint indeed exists and is working. However, we cannot just run `terraform apply` again, since it does not exist in state. We need to manually delete the PE first (or could manually import it).

```
│ Error: waiting for creation of Private Endpoint "acintbf3e-westeurop-acr-pe" (Resource Group "acintbf3e-stamp-westeurope-rg"): Code="RetryableError" Message="A retryable error occurred." Details=[{"code":"ReferencedResourceNotProvisioned","message":"Cannot proceed with operation because resource /subscriptions/***/resourceGroups/ao-network/providers/Microsoft.Network/virtualNetworks/vnet-we/subnets/private-endpoints-snet used by resource /subscriptions/***/resourceGroups/acintbf3e-stamp-westeurope-rg/providers/Microsoft.Network/networkInterfaces/acintbf3e-westeurop-acr-pe.nic.8b3a01bb-91bd-4a50-b197-04119f1cb398 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation."}]
```

### Steps to Reproduce

Not sure, it happens intermittently.

### Important Factoids

We are provisioning multiple private endpoints in parallel into the same subnet, not sure if that is causing the issue.

### PR DESCRIPTION
**Pull request by lonegunmanb**
Add retry on creation to fix #16182 .

### CODE REVIEW

**Comment by lonegunmanb** [comment]
Acc tests:

=== RUN   TestAccPrivateEndpoint_basic
=== PAUSE TestAccPrivateEndpoint_basic
=== CONT  TestAccPrivateEndpoint_basic
--- PASS: TestAccPrivateEndpoint_basic (462.73s)
=== RUN   TestAccPrivateEndpoint_updateTag

=== PAUSE TestAccPrivateEndpoint_updateTag

=== CONT  TestAccPrivateEndpoint_updateTag
--- PASS: TestAccPrivateEndpoint_updateTag (634.01s)
=== RUN   TestAccPrivateEndpoint_requestMessage
=== PAUSE TestAccPrivateEndpoint_requestMessage
=== CONT  TestAccPrivateEndpoint_requestMessage
--- PASS: TestAccPrivateEndpoint_requestMessage (534.62s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneGroup
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneGroup
=== CONT  TestAccPrivateEndpoint_privateDnsZoneGroup
--- PASS: TestAccPrivateEndpoint_privateDnsZoneGroup (519.38s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRename
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRename
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRename
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRename (656.88s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneUpdate
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneUpdate
=== CONT  TestAccPrivateEndpoint_privateDnsZoneUpdate
--- PASS: TestAccPrivateEndpoint_privateDnsZoneUpdate (790.60s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRemove
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRemove
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRemove
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRemove (731.34s)
=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias
=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
--- PASS: TestAccPrivateEndpoint_privateConnectionAlias (465.02s)

File: internal/services/network/private_endpoint_resource.go [hunk 1]
```diff
@@ -299,8 +300,17 @@ func resourcePrivateEndpointCreate(d *pluginsdk.ResourceData, meta interface{})
...
+		if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
+			return &resource.RetryError{
+				Err:       fmt.Errorf("waiting for creation of Private Endpoint %q (Resource Group %q): %+v", id.Name, id.ResourceGroup, err),
+				Retryable: strings.Contains(strings.ToLower(err.Error()), "retryable"),
+			}
+		}
+		return nil
+	})
+	if err != nil {
+		return err
```
Comment (tombuildsstuff) [inline internal/services/network/private_endpoint_resource.go:313]: unfortunately this won't do anything since it's only retrying on the poller/future.. since this is an API error this'd need to be fixed here - is there a Swagger issue tracking this upstream issue?

**Comment by lonegunmanb** [comment]
Hi @tombuildsstuff , since the error message is:

>Message="A retryable error occurred." Details=[{"code":"ReferencedResourceNotProvisioned","message":"Cannot proceed with operation because resource /subscriptions/***/resourceGroups/ao-network/providers/Microsoft.Network/virtualNetworks/vnet-we/subnets/private-endpoints-snet used by resource /subscriptions/***/resourceGroups/acintbf3e-stamp-westeurope-rg/providers/Microsoft.Network/networkInterfaces/acintbf3e-westeurop-acr-pe.nic.8b3a01bb-91bd-4a50-b197-04119f1cb398 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation."}]

After searching for `Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation.` I found this [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/2605), and a pr with retry on the poller fix the issue with the very similar error message. Do I need open an issue on the Swagger project? Thanks!

**Comment by lonegunmanb** [comment]
Hello @tombuildsstuff , is there any chance to merge is pr since pr #3392 fixed very similar issue #2605 by retry, or should I open an issue on Azure service team? Thanks.

**Comment by lonegunmanb** [comment]
Hello @tombuildsstuff , a kindly ping for this pr, is there anything I can do to get this pr been merged? Any advice will be appreciated.

**Comment by tombuildsstuff** [comment]
@lonegunmanb this PR still polls the Read request - so this isn't going to change anything?

**Comment by lonegunmanb** [comment]
@tombuildsstuff thanks for the guidance. Now I use retry on CreateOrUpate and polling, would you please give another review? Thanks!

Acc tests:

=== RUN   TestAccPrivateEndpoint_basic
=== PAUSE TestAccPrivateEndpoint_basic
=== CONT  TestAccPrivateEndpoint_basic
--- PASS: TestAccPrivateEndpoint_basic (549.82s)
=== RUN   TestAccPrivateEndpoint_updateTag
=== PAUSE TestAccPrivateEndpoint_updateTag
=== CONT  TestAccPrivateEndpoint_updateTag
--- PASS: TestAccPrivateEndpoint_updateTag (610.13s)
=== RUN   TestAccPrivateEndpoint_requestMessage
=== PAUSE TestAccPrivateEndpoint_requestMessage
=== CONT  TestAccPrivateEndpoint_requestMessage
--- PASS: TestAccPrivateEndpoint_requestMessage (520.74s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneGroup
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneGroup
=== CONT  TestAccPrivateEndpoint_privateDnsZoneGroup
--- PASS: TestAccPrivateEndpoint_privateDnsZoneGroup (711.88s)

=== RUN   TestAccPrivateEndpoint_privateDnsZoneRename
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRename
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRename
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRename (718.42s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneUpdate
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneUpdate
=== CONT  TestAccPrivateEndpoint_privateDnsZoneUpdate
--- PASS: TestAccPrivateEndpoint_privateDnsZoneUpdate (840.11s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRemove
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRemove
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRemove
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRemove (855.77s)

=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias

=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
--- PASS: TestAccPrivateEndpoint_privateConnectionAlias (465.13s)

**Comment by lonegunmanb** [comment]
Rebased with latest main branch, acc tests:

=== RUN   TestAccPrivateEndpoint_basic
=== PAUSE TestAccPrivateEndpoint_basic
=== CONT  TestAccPrivateEndpoint_basic
--- PASS: TestAccPrivateEndpoint_basic (378.15s)
=== RUN   TestAccPrivateEndpoint_updateTag

=== PAUSE TestAccPrivateEndpoint_updateTag

=== CONT  TestAccPrivateEndpoint_updateTag
--- PASS: TestAccPrivateEndpoint_updateTag (627.65s)
=== RUN   TestAccPrivateEndpoint_requestMessage
=== PAUSE TestAccPrivateEndpoint_requestMessage
=== CONT  TestAccPrivateEndpoint_requestMessage
--- PASS: TestAccPrivateEndpoint_requestMessage (478.36s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneGroup
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneGroup
=== CONT  TestAccPrivateEndpoint_privateDnsZoneGroup
--- PASS: TestAccPrivateEndpoint_privateDnsZoneGroup (524.03s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRename
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRename
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRename
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRename (677.02s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneUpdate
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneUpdate
=== CONT  TestAccPrivateEndpoint_privateDnsZoneUpdate
--- PASS: TestAccPrivateEndpoint_privateDnsZoneUpdate (773.47s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRemove
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRemove
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRemove
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRemove (787.14s)
=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias

=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
--- PASS: TestAccPrivateEndpoint_privateConnectionAlias (388.26s)
PASS

**Review by katbyte — CHANGES_REQUESTED** [review]
Looking at the issue it seems like this is just a bandaid over the existing problem: provisioning multiple private endpoints causes them all to update the same dependant resource because terraform doesn't know about this dependancy? instead should we not be locking on the subnet id to prevent multiple changes from happening at the same time?

also could we add a test that provisions 5 or 6 to cover the use cases described in the issue?

File: internal/services/network/private_endpoint_resource.go [hunk 2]
```diff
@@ -289,17 +290,32 @@ func resourcePrivateEndpointCreate(d *pluginsdk.ResourceData, meta interface{})
...
 	}
+	err = pluginsdk.Retry(d.Timeout(pluginsdk.TimeoutCreate), func() *resource.RetryError {
+		future, err := client.CreateOrUpdate(ctx, id.ResourceGroup, id.Name, parameters)
+		if err != nil {
+			if strings.EqualFold(err.Error(), "is missing required parameter 'group Id'") {
+				return &resource.RetryError{
+					Err:       fmt.Errorf("creating Private Endpoint %q (Resource Group %q) due to missing 'group Id', ensure that the 'subresource_names' type is populated: %+v", id.Name, id.ResourceGroup, err),
+					Retryable: false,
+				}
+			} else {
```
[the remark this answers is not in the document]
Comment (katbyte) [reply internal/services/network/private_endpoint_resource.go:301]: test /wr

**Comment by lonegunmanb** [comment]
Hello @katbyte , thanks for your advice, I've added lock on subnet id, and add new test to create multiple private endpoint instances, all the tests passed:

=== RUN   TestAccPrivateEndpoint_basic
=== PAUSE TestAccPrivateEndpoint_basic
=== CONT  TestAccPrivateEndpoint_basic
--- PASS: TestAccPrivateEndpoint_basic (366.77s)
=== RUN   TestAccPrivateEndpoint_updateTag

=== PAUSE TestAccPrivateEndpoint_updateTag

=== CONT  TestAccPrivateEndpoint_updateTag
--- PASS: TestAccPrivateEndpoint_updateTag (647.21s)
=== RUN   TestAccPrivateEndpoint_requestMessage
=== PAUSE TestAccPrivateEndpoint_requestMessage
=== CONT  TestAccPrivateEndpoint_requestMessage
--- PASS: TestAccPrivateEndpoint_requestMessage (410.05s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneGroup
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneGroup
=== CONT  TestAccPrivateEndpoint_privateDnsZoneGroup
--- PASS: TestAccPrivateEndpoint_privateDnsZoneGroup (504.90s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRename
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRename
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRename
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRename (597.69s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneUpdate
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneUpdate
=== CONT  TestAccPrivateEndpoint_privateDnsZoneUpdate
--- PASS: TestAccPrivateEndpoint_privateDnsZoneUpdate (761.94s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRemove
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRemove
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRemove
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRemove (765.35s)
=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias
=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
--- PASS: TestAccPrivateEndpoint_privateConnectionAlias (412.78s)
=== RUN   TestAccPrivateEndpoint_multipleInstances
=== PAUSE TestAccPrivateEndpoint_multipleInstances
=== CONT  TestAccPrivateEndpoint_multipleInstances
--- PASS: TestAccPrivateEndpoint_multipleInstances (601.73s)
PASS

Would you please give this pr another review? Thanks!

File: internal/services/network/private_endpoint_resource.go [hunk 3]
```diff
@@ -289,17 +290,35 @@ func resourcePrivateEndpointCreate(d *pluginsdk.ResourceData, meta interface{})
...
+	locks.ByName(subnetId, "azurerm_private_endpoint")
+	defer locks.UnlockByName(subnetId, "azurerm_private_endpoint")
 
-	future, err := client.CreateOrUpdate(ctx, id.ResourceGroup, id.Name, parameters)
-	if err != nil {
-		if strings.EqualFold(err.Error(), "is missing required parameter 'group Id'") {
-			return fmt.Errorf("creating Private Endpoint %q (Resource Group %q) due to missing 'group Id', ensure that the 'subresource_names' type is populated: %+v", id.Name, id.ResourceGroup, err)
-		} else {
-			return fmt.Errorf("creating Private Endpoint %q (Resource Group %q): %+v", id.Name, id.ResourceGroup, err)
+	err = pluginsdk.Retry(d.Timeout(pluginsdk.TimeoutCreate), func() *resource.RetryError {
```
Comment (katbyte) [inline internal/services/network/private_endpoint_resource.go:296]: now that we are locking can we revert this and remove the retry? as it shouldn't be required

**Review by katbyte — CHANGES_REQUESTED** [review]
we also have a  test failure:
```
------- Stdout: -------
=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias
=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Private Endpoint "acctest-privatelink-220809073512394901" (Resource Group "acctestRG-privatelink-220809073512394901"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidPrivateLinkServiceId" Message="PrivateLinkServiceId Invalid private link service id: {0} passed in private link service connection: {1} passed in input is invalid" Details=[]
        
          with azurerm_private_endpoint.test,
          on terraform_plugin_test.tf line 80, in resource "azurerm_private_endpoint" "test":
          80: resource "azurerm_private_endpoint" "test" {
        
--- FAIL: TestAccPrivateEndpoint_privateConnectionAlias (213.61s)
FAIL
```

**Comment by lonegunmanb** [comment]
Hi @katbyte , I believe it's a concurrent related issue, if we run this test alone then it will pass. I'll try to fix it.

File: internal/services/network/private_endpoint_resource.go (hunk 3 above)
Comment (lonegunmanb) [reply internal/services/network/private_endpoint_resource.go:296]: Copy that.

**Comment by lonegunmanb** [comment]
Hi @katbyte , thanks for reviewing this pr. I've tried to remove the retry, but to fix the failed test I found I have to add this retry back.

My theory is, the test failure is due to some performance and cache issue on the service side. When we execute this test alone it'll pass, but if we execute all private endpoint tests together, the service side will complain that the private link service we've passed is invalid.

In this test we used private link service's alias instead of id, so I guess when a private link service has been created, if we query its id immediately it will return an empty result occasionally, depends on how busy the service side were. I think it's a retriable error. I added a retry on this error message then the tests passed.

Since I've modified the update function, I also add an update in the test.

=== RUN   TestAccPrivateEndpoint_basic
=== PAUSE TestAccPrivateEndpoint_basic
=== CONT  TestAccPrivateEndpoint_basic
--- PASS: TestAccPrivateEndpoint_basic (378.77s)
=== RUN   TestAccPrivateEndpoint_updateTag
=== PAUSE TestAccPrivateEndpoint_updateTag
=== CONT  TestAccPrivateEndpoint_updateTag
--- PASS: TestAccPrivateEndpoint_updateTag (667.90s)
=== RUN   TestAccPrivateEndpoint_requestMessage
=== PAUSE TestAccPrivateEndpoint_requestMessage
=== CONT  TestAccPrivateEndpoint_requestMessage
--- PASS: TestAccPrivateEndpoint_requestMessage (507.50s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneGroup
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneGroup
=== CONT  TestAccPrivateEndpoint_privateDnsZoneGroup
--- PASS: TestAccPrivateEndpoint_privateDnsZoneGroup (456.53s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRename
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRename
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRename
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRename (677.53s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneUpdate
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneUpdate
=== CONT  TestAccPrivateEndpoint_privateDnsZoneUpdate

--- PASS: TestAccPrivateEndpoint_privateDnsZoneUpdate (780.76s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRemove
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRemove
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRemove
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRemove (805.95s)
=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias
=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
--- PASS: TestAccPrivateEndpoint_privateConnectionAlias (399.50s)
=== RUN   TestAccPrivateEndpoint_updateToPrivateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_updateToPrivateConnectionAlias
=== CONT  TestAccPrivateEndpoint_updateToPrivateConnectionAlias
--- PASS: TestAccPrivateEndpoint_updateToPrivateConnectionAlias (562.12s)
=== RUN   TestAccPrivateEndpoint_multipleInstances
=== PAUSE TestAccPrivateEndpoint_multipleInstances
=== CONT  TestAccPrivateEndpoint_multipleInstances
--- PASS: TestAccPrivateEndpoint_multipleInstances (638.91s)
PASS

**Review by katbyte — CHANGES_REQUESTED** [review]
that sounds like a bug on the API side? could we open an issue on the rest specs and link to it where we are doing the retry?

**Comment by lonegunmanb** [comment]
> that sounds like a bug on the API side? could we open an issue on the rest specs and link to it where we are doing the retry?

Sure thing @katbyte , I'll open a ticket on this issue to the service team, meanwhile as this issue occurred on concurrent scenario, and it's not quite relevant to the issue we're trying to fix by this pr, could we accept this pr for now to solve user's issue, and when the service team fix this bug I'll open a new pr to remove this retry? Anyway, I'll open a ticket now. Thanks for your review.

File: internal/services/network/private_endpoint_resource.go [hunk 4]
```diff
@@ -282,24 +283,61 @@ func resourcePrivateEndpointCreate(d *pluginsdk.ResourceData, meta interface{})
...
```
Comment (katbyte) [inline internal/services/network/private_endpoint_resource.go:305]:
```suggestion
	err = pluginsdk.Retry(d.Timeout(pluginsdk.TimeoutCreate), func() *resource.RetryError { // this is required due to a bug in the API https://github.com/Azure/azure-rest-api-specs/issues/20289
```

**Review by katbyte — APPROVED** [review]
Nope this is fine as long as there is an open issue describing what the issue is on the rest specs and its linked to in the code where the workaround exists. adding that now and it'll LGTM 🌩️
