### PR TITLE
Making the `azurerm_client_config` data source work with AzureCLI auth

### LINKED ISSUE #392: azurerm_client_config error listing Service Principals
Error on getting data from azurerm_client_config
```* data.azurerm_client_config.current: data.azurerm_client_config.current: Error listing Service Principals: autorest.DetailedError{Original:(*azure.RequestError)(0xc420619ef0), PackageType:"graphrbac.ServicePrincipalsClient", Method:"List", StatusCode:401, Message:"Failure responding to request", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc420619e60)}```

### Terraform Version
```
Terraform v0.10.7
.
└── provider.azurerm 0.2.2
```
### Affected Resource(s)
- data.azurerm_client_config

### Terraform Configuration Files
```hcl
provider "azurerm" {}

data "azurerm_client_config" "current" {}

output "account_id" {
  value = "${data.azurerm_client_config.current.account_id}"
}
```

### Debug Output
[REMOVED]

### Actual Behavior
failed to get any data 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Tried both with az cli auth and service principal
i'm not an admin of whole account but have subscription owner role
list service principals from az cli successful with same credentials
`az ad sp list`

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Fixes #392

Unfortunately testing this is tricky, since we rely on a Service Principal to run the acceptance tests (and not AzureCLI auth) - however I've verified this works as expected in both cases

Tests pass:

```
$ acctests azurerm TestAccDataSourceAzureRMClientConfig_basic
=== RUN   TestAccDataSourceAzureRMClientConfig_basic
--- PASS: TestAccDataSourceAzureRMClientConfig_basic (12.65s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	12.673s
```

### CODE REVIEW

File: azurerm/data_source_arm_client_config.go [hunk 1]
```diff
@@ -38,28 +39,35 @@ func dataSourceArmClientConfig() *schema.Resource {
...
+		if listErr != nil {
+			return fmt.Errorf("Error listing Service Principals: %#v", listErr)
+		}
+
+		if listResult.Value == nil || len(*listResult.Value) != 1 {
+			return fmt.Errorf("Unexpected Service Principal query result: %#v", listResult.Value)
+		}
 
-	servicePrincipal := (*listResult.Value)[0]
+		servicePrincipal = &(*listResult.Value)[0]
```
Comment (radeksimko) [inline azurerm/data_source_arm_client_config.go]: 🙀

File: azurerm/config.go [hunk 2]
```diff
@@ -46,10 +46,11 @@ import (
...
 // resource classes' respective clients.
 type ArmClient struct {
-	clientId       string
-	tenantId       string
-	subscriptionId string
-	environment    azure.Environment
+	clientId              string
+	tenantId              string
+	subscriptionId        string
+	usingServicePrincipal bool
```
Comment (radeksimko) [inline azurerm/config.go]: Nitpick, but `using*` to me sounds like a state that may be managed from somewhere outside, how do you feel about calling it `useServicePrinciple` instead?

**Review by radeksimko — APPROVED** [review]
LGTM, although I don't know much about service principles nor Azure, so take that with a pinch of salt.

File: azurerm/config.go (hunk 2 above)
Comment (tombuildsstuff) [reply azurerm/config.go]: it will be managed from somewhere outside (it's determined in the Config class, and then cast to an `ArmConfig` once the authentication tokens have been obtained) - as such I think `using` makes more sense in this context than `use`? That said, I'm happy to change this - but I'm a little stumped for a better name ¯\_(ツ)_/¯

Comment (tombuildsstuff) [reply azurerm/config.go]: (merging this for the moment - we can rename this later if needed)
