### PR TITLE
`azurerm_function_app` and `azurerm_function_app_slot` - fix `app_settings` for `WEBSITE_CONTENTSHARE`

### LINKED ISSUE #10499: Function app unexpected changes in WEBSITE_CONTENTSHARE after apply
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform version:  v0.13.3
* Azurerm provider: 2.46.1

### Affected Resource(s)

* `azurerm_function_app`
* `azurerm_function_app_slot`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "2.46.1"
  features {}
}

variable "resource_group" {
  default = "dev-walter"
}

variable "location" {
  default = "West Europe"
}

resource "azurerm_storage_account"  "fn4_test_storage" {
 name = "fn4teststorage"
 resource_group_name = var.resource_group
 location = var.location
 account_tier = "Standard"
 account_replication_type = "LRS"
}

resource "azurerm_app_service_plan"  "fn4_test_plan" {
  name = "fn4-test-plan"
  location = var.location
  resource_group_name = var.resource_group
  kind = "elastic"

  sku {
    capacity = 1
    tier = "ElasticPremium"
    size = "EP1"
  }
}

resource "azurerm_function_app"  "fn4_test" {
  name = "fn4-test"
  location = var.location
  resource_group_name = var.resource_group
  app_service_plan_id = azurerm_app_service_plan.fn4_test_plan.id
  storage_account_name = azurerm_storage_account.fn4_test_storage.name
  storage_account_access_key = azurerm_storage_account.fn4_test_storage.primary_access_key
  version = "~3"
  enable_builtin_logging = false
  
  app_settings = {
    ENABLE_ORYX_BUILD = "false"
    FUNCTIONS_WORKER_RUNTIME = "node"
    SCM_DO_BUILD_DURING_DEPLOYMENT = "false"
    WEBSITE_NODE_DEFAULT_VERSION = "~14"
    DUMMY = 1
    WEBSITE_CONTENTSHARE = "fn4-test-content"
  }
}

resource "azurerm_function_app_slot"  "fn4_test_slot" {
    name = "staging"
    location = var.location
    resource_group_name = var.resource_group
    app_service_plan_id = azurerm_app_service_plan.fn4_test_plan.id
    function_app_name = azurerm_function_app.fn4_test.name
    storage_account_name = azurerm_storage_account.fn4_test_storage.name
    storage_account_access_key = azurerm_storage_account.fn4_test_storage.primary_access_key
    version = "~3"
    enable_builtin_logging = false

    app_settings = {
        FUNCTIONS_WORKER_RUNTIME = "node"
        WEBSITE_NODE_DEFAULT_VERSION = "~14"
        ENABLE_ORYX_BUILD = "false"
        SCM_DO_BUILD_DURING_DEPLOYMENT = "false"
        WEBSITE_CONTENTSHARE = "staging-content"
    }
}
```

### Debug Output

I changed the value of the DUMMY app settings from 1 to 2 and this is the only change I see running the **plan** command:

```
  ....
  ~ app_settings                   = {
         
          ~ "DUMMY"                                 = "1" -> "2"
            "ENABLE_ORYX_BUILD"                     = "false"
            "FUNCTIONS_WORKER_RUNTIME"              = "node"
            "SCM_DO_BUILD_DURING_DEPLOYMENT"        = "false"
            "WEBSITE_CONTENTSHARE"                  = "staging-content"
            "WEBSITE_NODE_DEFAULT_VERSION"          = "~14"
        }
        client_affinity_enabled        = false
....        
```

### Expected Behaviour

I am expecting to go in azure portal Home → dev-walter → fn4-test → Configuration and see only one change: the value of the app setting DUMMY 

### Actual Behaviour

The app settings DUMMY is correctly set to 2 while the **WEBSITE_CONTENTSHARE** changed from staging-content to fn4-test-content even if within the plan there is no evidence that setting is going to change.
This is very **dangerous** because it can cause an "hidden swap" of the running software from a stable version to an unstable one. 

### Steps to Reproduce

1. `terraform apply`
2. Deploy on the "production" slot version 1.0 of your function
3. Deploy on "staging" slot version 2.0 of your function
4. Go to the portal and swap staging and production slots. When your run the swap azure behind the hood also swap the values inside the settings WEBSITE_CONTENTSHARE.
        - before the swap: **production**  is equal to fn4-test-content    **staging**    is equal to  staging-content
        - after the swap:   **production**  is equal to staging-content    **production** is equal to fn4-test-content
       (as far as I know this is how azure works) 
       **Now version 2.0 runs in production while version 1.0 is in stating** 
5. Edit your terraform configuration file: for instance change the value of the app settings DUMMY
6. `terraform apply`
7. Check the plan on the standard output: the only change highlighted is the value of the DUMMY app settings like in the example above
8. As soon as the apply is completed you will find out **version 1.0 runs in production while version 2.0 is in stating** unexpectedly.

### References

Since I am stucking   with this issue blocking me to any further changes in my function apps running in production I've tried to fix the provider.
Here my PR

* [Fix functions app website_contenteshare unwanted changes](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10494)

Basically I don't see the reason to set inside the provider the value for WEBSITE_CONTENTSHARE.
I prefer to set it within my terraform configuration file: 

**production**
```hcl
app_settings = {

  WEBSITE_CONTENTSHARE = "fn4-test-content"
}
```
**staging**
```hcl
app_settings = {

  WEBSITE_CONTENTSHARE = "staging-content"
}
```
Then I don't want to change them with following apply. Provided that I am also putting the **lifecycle** block in the definition of the function 

```hcl
resource "azurerm_function_app"  "fn4_test" {
    name = "fn4-test"
    ....
    ....
    lifecycle {
        ignore_changes = [
          app_settings["WEBSITE_CONTENTSHARE"],
        ]
    }
}
....
resource "azurerm_function_app_slot"  "fn4_test_slot" {
name = "staging"
...
  lifecycle {
    ignore_changes = [
      app_settings["WEBSITE_CONTENTSHARE"],
    ]
  }
}
```

Also refer to these issues:
* #9766
* #7888
* #8130
* #9536

### LINKED ISSUE #12914: Linux ElasticPremium didn't add WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE automatically
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

``` 
resource "random_string" "random" {
  length           = 4
  special          = false
  lower            = true
  upper            = false
}

resource "azurerm_resource_group" "resource_group" {
  name = "${var.project}-${var.environment}-resource-group${random_string.random.result}"
  location = var.location
}

resource "azurerm_storage_account" "storage_account" {
  name = "storage${random_string.random.result}"
  resource_group_name = azurerm_resource_group.resource_group.name
  location = var.location
  account_tier = "Standard"
  account_replication_type = "LRS"
}
resource "azurerm_application_insights" "application_insights" {
  name                = "${var.project}-${var.environment}-application-insights"
  location            = var.location
  resource_group_name = azurerm_resource_group.resource_group.name
  application_type    = "Node.JS"
}
resource "azurerm_app_service_plan" "app_service_plan" {
  name                = "${var.project}-${var.environment}-app-service-plan"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = var.location
  kind                = "elastic"
  reserved = true # this has to be set to true for Linux. Not related to the Premium Plan
  sku {
    tier = "elasticpremium"
    size = "EP1"
    capacity = 1
  }
}

resource "azurerm_function_app" "function_app" {
  name                       = "${var.project}-${var.environment}-function-app${random_string.random.result}"
  resource_group_name        = azurerm_resource_group.resource_group.name
  location                   = var.location
  app_service_plan_id        = azurerm_app_service_plan.app_service_plan.id
  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE" = "",
    "FUNCTIONS_WORKER_RUNTIME" = "node",
    "APPINSIGHTS_INSTRUMENTATIONKEY" = azurerm_application_insights.application_insights.instrumentation_key,
  }
  os_type = "linux"
  site_config {
    linux_fx_version          = "node|14"
    use_32_bit_worker_process = false
  }
  storage_account_name       = azurerm_storage_account.storage_account.name
  storage_account_access_key = azurerm_storage_account.storage_account.primary_access_key
  version                    = "~3"

  lifecycle {
    ignore_changes = [
      app_settings["WEBSITE_RUN_FROM_PACKAGE"],
    ]
  }
}
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE will added to App settings automatically for Linux ElasticPremium

### Actual Behaviour

WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE are not added automatically

### Steps to Reproduce

When it's Windows ElasticPremium, those 2 settings will be created, but not for Linux ElasticPremium

1. `terraform apply`

### References

* #0000
review the code https://github.com/terraform-providers/terraform-provider-azurerm/blob/a3d535171b1919ad0e05cbde688c9bb055b09618/internal/services/web/function_app.go#L316, 
it seems elasticpremium has been checked, but it didn't take effect.

### PR DESCRIPTION
**Pull request by jackofallops**
fixes #10499
fixes #12914
supersedes #10494

### CODE REVIEW

File: internal/services/web/function_app.go [hunk 1]
```diff
@@ -331,8 +344,8 @@ func getBasicFunctionAppAppSettings(d *pluginsdk.ResourceData, appServiceTier, e
 
 	// On consumption and premium plans include WEBSITE_CONTENT components, unless it's a Linux consumption plan
 	// (see https://github.com/Azure/azure-functions-python-worker/issues/598)
-	if (strings.EqualFold(appServiceTier, "dynamic") || strings.EqualFold(appServiceTier, "elasticpremium") || strings.HasPrefix(strings.ToLower(appServiceTier), "premium")) &&
-		!strings.EqualFold(d.Get("os_type").(string), "linux") {
+	if !(strings.EqualFold(appServiceTier, "dynamic") && strings.EqualFold(d.Get("os_type").(string), "linux")) &&
+		(strings.EqualFold(appServiceTier, "dynamic") || strings.HasPrefix(appServiceTier, "elastic") || strings.HasPrefix(appServiceTier, "Elastic")) {
```
Comment (manicminer) [inline internal/services/web/function_app.go:348]: Minor but a bit shorter?

```suggestion
		(strings.EqualFold(appServiceTier, "dynamic") || strings.HasPrefix(strings.ToLower(appServiceTier), "elastic")) {
```

File: internal/services/web/function_app_resource.go [hunk 2]
```diff
@@ -680,10 +696,10 @@ func resourceFunctionAppRead(d *pluginsdk.ResourceData, meta interface{}) error
...
 	}
 
-	// Let the user have a final say whether they want to keep these 2 or not on
-	// Linux consumption plans. They shouldn't be there according to a bug
-	// report (see // https://github.com/Azure/azure-functions-python-worker/issues/598)
-	if !strings.EqualFold(d.Get("os_type").(string), "linux") {
+	// From the docs:
+	// Only used when deploying to a Premium plan or to a Consumption plan running on Windows. Not supported for Consumptions plans running Linux.
+	if (strings.EqualFold(appServiceTier, "dynamic") && strings.EqualFold(d.Get("os_type").(string), "linux")) ||
+		(strings.EqualFold(appServiceTier, "dynamic") || strings.HasPrefix(appServiceTier, "elastic") || strings.HasPrefix(appServiceTier, "Elastic")) {
```
Comment (manicminer) [inline internal/services/web/function_app_resource.go:702]:
```suggestion
		(strings.EqualFold(appServiceTier, "dynamic") || strings.HasPrefix(strings.ToLower(appServiceTier), "elastic")) {
```

**Review by manicminer — APPROVED** [review]
Very minor suggestion but otherwise LGTM 🍎

**Review by katbyte — APPROVED** [review]
