### PR TITLE
`azurerm_container_app_custom_domain` - support the ability to use Azure Managed Certificates

### LINKED ISSUE #24110: On azurerm_container_app adding custom domain, the field certificate_id is required and should not be
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.2

### AzureRM Provider Version

3.76.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl

```

### Debug Output/Panic Output

```shell
│ Error: Missing required argument
│
│   with module.container_apps.azurerm_container_app.container_app["capp-web"],
│   on modules\container_apps\main.tf line 15, in resource "azurerm_container_app" "container_app":
│   15: resource "azurerm_container_app" "container_app" {
│
│ The argument "ingress.0.custom_domain.0.certificate_id" is required, but no definition was found.
```

### Expected Behaviour

Adding "custom domain" with Terraform dot not raise an error that "certificate_id" is required (exporting on JSON VIEW on the Azure Portal is not required).

### Actual Behaviour

In Azure, with container app add two custom domains, go to "overview", click on JSON view and you can see the SCHEMA exported for the custom domains have 2 properties "name" and "bindingType".

Although, if you add these "custom domain" with Terraform it will raise and error that "certificate_id" is required but doing it on the Azure platform it is not required.

### Steps to Reproduce

In Azure, with container app add two custom domains, go to "overview", click on JSON view and you can see the SCHEMA exported for the custom domains have 2 properties "name" and "bindingType".

Although, if you add these "custom domain" with Terraform it will raise and error that "certificate_id" is required but doing it on the Azure platform it is not required.

```
(...)
                "customDomains": [
                    {
                        "name": "test.ambitiousbay-xxxxxxx.westeurope.azurecontainerapps.io",
                        "bindingType": "Disabled"
                    },
                    {
                        "name": "mysubdomain.example.com",
                        "bindingType": "Disabled"
                    }
                ],
(...)
```

Error on terraform adding a custom domain without certificate (only name="subdomain.example.com" and certificate_binding_type="Disabled" filled):
```
│ Error: Missing required argument
│
│   with module.container_apps.azurerm_container_app.container_app["capp-web"],
│   on modules\container_apps\main.tf line 15, in resource "azurerm_container_app" "container_app":
│   15: resource "azurerm_container_app" "container_app" {
│
│ The argument "ingress.0.custom_domain.0.certificate_id" is required, but no definition was found.
```

Source on terraform -> terraform-provider-azurerm\internal\services\containerapps\helpers\container_apps.go:
```

type CustomDomain struct {
	CertBinding   string `tfschema:"certificate_binding_type"`
	CertificateId string `tfschema:"certificate_id"`
	Name          string `tfschema:"name"`
}

func ContainerAppIngressCustomDomainSchema() *pluginsdk.Schema {
	return &pluginsdk.Schema{
		Type:     pluginsdk.TypeList,
		Optional: true,
		MaxItems: 1,
		Elem: &pluginsdk.Resource{
			Schema: map[string]*pluginsdk.Schema{
				"certificate_binding_type": {
					Type:         pluginsdk.TypeString,
					Optional:     true,
					Default:      containerapps.BindingTypeDisabled,
					ValidateFunc: validation.StringInSlice(containerapps.PossibleValuesForBindingType(), false),
					Description:  "The Binding type. Possible values include `Disabled` and `SniEnabled`. Defaults to `Disabled`",
				},

				"certificate_id": {
					Type:         pluginsdk.TypeString,
					Required:     true,
					ValidateFunc: managedenvironments.ValidateCertificateID,
				},

				"name": {
					Type:         pluginsdk.TypeString,
					Required:     true,
					ValidateFunc: validation.StringIsNotEmpty,
					Description:  "The hostname of the Certificate. Must be the CN or a named SAN in the certificate.",
				},
			},
		},
	}
}
```

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jackofallops**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

This changes `container_app_environment_certificate_id` and `certificate_binding_type` to become `Optional` properties. This is required to support the automatic creation of Azure Managed Certificates. This PR is in Draft as we are considering design options and may significantly change how this is implemented before inclusion in the provider.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_container_app_custom_domain` - enables support for Azure Managed Certificates 

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
closes #24110 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by stephybun — APPROVED** [review]
Thanks @jackofallops. LGTM provided tests pass 🦢

File: internal/services/containerapps/container_app_resource.go [hunk 1]
```diff
@@ -296,7 +296,7 @@ func (r ContainerAppResource) Read() sdk.ResourceFunc {
 
 func (r ContainerAppResource) Delete() sdk.ResourceFunc {
 	return sdk.ResourceFunc{
-		Timeout: 30 * time.Minute,
+		Timeout: 60 * time.Minute,
```
Comment (cgraf-spiria) [inline internal/services/containerapps/container_app_resource.go:299]: Why change the timeout? If needed, you would also need to update the documentation:
> `delete` - (Defaults to 30 minutes) Used when deleting the Container App.

Comment (jackofallops) [reply internal/services/containerapps/container_app_resource.go]: This was a change made to facilitate debugging during testing and mistakenly included.
