### PR TITLE
Mark ip_configuration as Required

### LINKED ISSUE #22152: Attribute "ip_configuration" should not be marked as (Optional)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_bastion_host

### Terraform Configuration Files

```hcl
provider "azurerm" {
    features {}   
}

resource "azurerm_resource_group" "bastion" {
  location = "westeurope"
  name     = "bastion-rg"

}
resource "azurerm_bastion_host" "main" {
  name                   = "my-bastion-host"
  location               = azurerm_resource_group.bastion.location
  resource_group_name    = azurerm_resource_group.bastion.name
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: creating/updating Bastion Host: (Name "my-bastion-host" / Resource Group "bastion-rg"): network.BastionHostsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BastionHostMustHaveAtleastOneHostIpConfiguration" Message="BastionHost /subscriptions/<subscription_id>/resourceGroups/bastion-rg/providers/Microsoft.Network/bastionHosts/my-bastion-host must contain at least 1 IP Configuration." Details=[]
│ 
│   with azurerm_bastion_host.main,
│   on main.tf line 38, in resource "azurerm_bastion_host" "main":
│   38: resource "azurerm_bastion_host" "main" {
│
```

### Expected Behaviour

Creating a bastion host without `ip_configuration` block will succeed as implied by the docs saying `ip_configuration` block is `Optional`. 

(this is what current docs suggest)

### Actual Behaviour

According to [docs here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bastion_host#ip_configuration) the `ip_configuration` block is `Optional` this falsely implies that you can create a bastion host without that variable which is definitely not true as you can see the attempt above which fails.

Therefore, I suggest we update the docs to make `ip_configuration` block `(Required)`

### Steps to Reproduce

```
terraform apply -auto-approve
```

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by CiucurDaniel**
This PR fixes the issue: [Attribute "ip_configuration" should not be marked as (Optional) #22152](https://github.com/hashicorp/terraform-provider-azurerm/issues/22152)

Fixes #22152

### CODE REVIEW

**Review by catriona-m — CHANGES_REQUESTED** [review]
Hi @CiucurDaniel thanks for spotting this. It looks like this also needs updated in the schema here too: https://github.com/hashicorp/terraform-provider-azurerm/blob/64a9d39b460c419e396c3473b1f210180a1c7f58/internal/services/network/bastion_host_resource.go#L69 . Would it be possible to do this as part of this fix too? Thanks!

**Comment by CiucurDaniel** [comment]
Sure, doing it now.

File: internal/services/network/bastion_host_resource.go [hunk 1]
```diff
@@ -66,7 +66,7 @@ func resourceBastionHost() *pluginsdk.Resource {
 			"ip_configuration": {
 				Type:     pluginsdk.TypeList,
 				ForceNew: true,
-				Optional: true,
+				Optional: false,
```
Comment (katbyte) [inline internal/services/network/bastion_host_resource.go:69]: instead of changing optional to false we should use `Required:     true`
```suggestion
				Required: true,
```

**Review by catriona-m — APPROVED** [review]
Thanks @CiucurDaniel LGTM!

**Comment by CiucurDaniel** [comment]
Thank you as well! @catriona-m 😄
