### PR TITLE
`azurerm_backup_policy_vm`: support `instant_restore_resource_group`

### LINKED ISSUE #20559: azurerm_backup_policy_vm has no "Azure Backup Resource Group (Optional)" parameter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_backup_policy_vm

### Terraform Configuration Files

```hcl
resource "azurerm_backup_policy_vm" "daily_backup" {
  name                = "Daily_VM_Backup_Policy"
  recovery_vault_name = azurerm_recovery_services_vault.rsv.name
  resource_group_name = var.resource_group.name
  timezone = "W. Europe Standard Time"
  backup {
    frequency = "Daily"
    time      = "05:00"
  }
  retention_daily {
    count = 7
  }
  retention_monthly {
    count    = 3
    weekdays = ["Sunday"]
    weeks    = ["Last"]
  }
}
```

### Debug Output/Panic Output

```shell
There is no parameter that allows you to set "Azure Backup Resource Group (Optional)" as you can do via the Azure portal.
```

### Expected Behaviour

The expected behavior is to have the parameter.

image

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ziyeqf**
close #20559 

test
---
```
terraform-provider-azurerm ❯ TF_ACC=1 go test -v ./internal/services/recoveryservices -run=TestAccBackupProtectionPolicyVM -timeout=600m                            [ tengzh/issue/policy_vm_enhance][$!][🐹 v1.19.5][⏱ 19s][13:53:25]
=== RUN   TestAccBackupProtectionPolicyVM_policyTypeDefault
=== PAUSE TestAccBackupProtectionPolicyVM_policyTypeDefault
=== RUN   TestAccBackupProtectionPolicyVM_basicDaily
=== PAUSE TestAccBackupProtectionPolicyVM_basicDaily
=== RUN   TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdate
=== PAUSE TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdate
=== RUN   TestAccBackupProtectionPolicyVM_requiresImport
=== PAUSE TestAccBackupProtectionPolicyVM_requiresImport
=== RUN   TestAccBackupProtectionPolicyVM_basicWeekly
=== PAUSE TestAccBackupProtectionPolicyVM_basicWeekly
=== RUN   TestAccBackupProtectionPolicyVM_completeDaily
=== PAUSE TestAccBackupProtectionPolicyVM_completeDaily
=== RUN   TestAccBackupProtectionPolicyVM_completeWeekly
=== PAUSE TestAccBackupProtectionPolicyVM_completeWeekly
=== RUN   TestAccBackupProtectionPolicyVM_updateDaily
=== PAUSE TestAccBackupProtectionPolicyVM_updateDaily
=== RUN   TestAccBackupProtectionPolicyVM_updateWeekly
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeekly
=== RUN   TestAccBackupProtectionPolicyVM_updateDailyToWeekly
=== PAUSE TestAccBackupProtectionPolicyVM_updateDailyToWeekly
=== RUN   TestAccBackupProtectionPolicyVM_updateWeeklyToDaily
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeeklyToDaily
=== RUN   TestAccBackupProtectionPolicyVM_updateWeeklyToPartial
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeeklyToPartial
=== RUN   TestAccBackupProtectionPolicyVM_basicHourlyV2
=== PAUSE TestAccBackupProtectionPolicyVM_basicHourlyV2
=== RUN   TestAccBackupProtectionPolicyVM_basicDailyV2
=== PAUSE TestAccBackupProtectionPolicyVM_basicDailyV2
=== RUN   TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdateV2
=== PAUSE TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdateV2
=== RUN   TestAccBackupProtectionPolicyVM_basicWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_basicWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_completeHourlyV2
=== PAUSE TestAccBackupProtectionPolicyVM_completeHourlyV2
=== RUN   TestAccBackupProtectionPolicyVM_completeDailyV2
=== PAUSE TestAccBackupProtectionPolicyVM_completeDailyV2
=== RUN   TestAccBackupProtectionPolicyVM_completeWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_completeWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateHourlyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateHourlyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateDailyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateDailyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateHourlyAndWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateHourlyAndWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateDailyAndWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateDailyAndWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateWeeklyToPartialV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeeklyToPartialV2
=== RUN   TestAccBackupProtectionPolicyVM_withCustomRGName
=== PAUSE TestAccBackupProtectionPolicyVM_withCustomRGName
=== RUN   TestAccBackupProtectionPolicyVMWorkload_basic
=== PAUSE TestAccBackupProtectionPolicyVMWorkload_basic
=== RUN   TestAccBackupProtectionPolicyVMWorkload_update
=== PAUSE TestAccBackupProtectionPolicyVMWorkload_update
=== CONT  TestAccBackupProtectionPolicyVM_policyTypeDefault
=== CONT  TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdateV2
=== CONT  TestAccBackupProtectionPolicyVM_completeWeekly
=== CONT  TestAccBackupProtectionPolicyVM_updateDaily
=== CONT  TestAccBackupProtectionPolicyVM_requiresImport
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyToPartial
=== CONT  TestAccBackupProtectionPolicyVM_basicWeekly
=== CONT  TestAccBackupProtectionPolicyVM_completeDaily
--- PASS: TestAccBackupProtectionPolicyVM_completeWeekly (389.29s)
=== CONT  TestAccBackupProtectionPolicyVM_updateDailyToWeekly
--- PASS: TestAccBackupProtectionPolicyVM_completeDaily (389.93s)
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyToDaily
--- PASS: TestAccBackupProtectionPolicyVM_policyTypeDefault (392.23s)
=== CONT  TestAccBackupProtectionPolicyVM_updateWeekly
--- PASS: TestAccBackupProtectionPolicyVM_basicWeekly (395.25s)
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyV2
--- PASS: TestAccBackupProtectionPolicyVM_requiresImport (413.19s)
=== CONT  TestAccBackupProtectionPolicyVMWorkload_update
--- PASS: TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdateV2 (503.87s)
=== CONT  TestAccBackupProtectionPolicyVMWorkload_basic
--- PASS: TestAccBackupProtectionPolicyVM_updateDaily (556.66s)
=== CONT  TestAccBackupProtectionPolicyVM_withCustomRGName
--- PASS: TestAccBackupProtectionPolicyVM_updateWeeklyToPartial (672.30s)
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyToPartialV2
--- PASS: TestAccBackupProtectionPolicyVMWorkload_basic (283.75s)
=== CONT  TestAccBackupProtectionPolicyVM_updateDailyAndWeeklyV2
--- PASS: TestAccBackupProtectionPolicyVM_updateWeekly (461.52s)
=== CONT  TestAccBackupProtectionPolicyVM_updateHourlyAndWeeklyV2
--- PASS: TestAccBackupProtectionPolicyVM_updateWeeklyV2 (467.50s)
=== CONT  TestAccBackupProtectionPolicyVM_completeWeeklyV2
--- PASS: TestAccBackupProtectionPolicyVMWorkload_update (454.79s)
=== CONT  TestAccBackupProtectionPolicyVM_updateDailyV2
--- PASS: TestAccBackupProtectionPolicyVM_updateWeeklyToDaily (488.90s)
=== CONT  TestAccBackupProtectionPolicyVM_updateHourlyV2
--- PASS: TestAccBackupProtectionPolicyVM_withCustomRGName (362.91s)
=== CONT  TestAccBackupProtectionPolicyVM_basicDailyV2
=== CONT  TestAccBackupProtectionPolicyVM_basicHourlyV2
--- PASS: TestAccBackupProtectionPolicyVM_updateDailyToWeekly (572.92s)
--- PASS: TestAccBackupProtectionPolicyVM_updateWeeklyToPartialV2 (472.53s)
=== CONT  TestAccBackupProtectionPolicyVM_completeHourlyV2
--- PASS: TestAccBackupProtectionPolicyVM_completeWeeklyV2 (368.81s)
=== CONT  TestAccBackupProtectionPolicyVM_completeDailyV2
--- PASS: TestAccBackupProtectionPolicyVM_updateHourlyV2 (405.45s)
=== CONT  TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdate
--- PASS: TestAccBackupProtectionPolicyVM_basicDailyV2 (366.61s)
=== CONT  TestAccBackupProtectionPolicyVM_basicDaily
--- PASS: TestAccBackupProtectionPolicyVM_basicHourlyV2 (370.11s)
=== CONT  TestAccBackupProtectionPolicyVM_basicWeeklyV2
--- PASS: TestAccBackupProtectionPolicyVM_updateDailyV2 (475.67s)
--- PASS: TestAccBackupProtectionPolicyVM_updateDailyAndWeeklyV2 (589.16s)
--- PASS: TestAccBackupProtectionPolicyVM_updateHourlyAndWeeklyV2 (599.52s)
--- PASS: TestAccBackupProtectionPolicyVM_completeHourlyV2 (359.04s)
--- PASS: TestAccBackupProtectionPolicyVM_completeDailyV2 (369.96s)
--- PASS: TestAccBackupProtectionPolicyVM_basicWeeklyV2 (371.90s)
--- PASS: TestAccBackupProtectionPolicyVM_basicDaily (465.14s)
--- PASS: TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdate (491.47s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      1777.029s

```

### CODE REVIEW

File: internal/services/recoveryservices/backup_policy_vm_resource.go [hunk 1]
```diff
@@ -517,6 +538,24 @@ func expandBackupProtectionPolicyVMRetentionWeeklyFormat(block map[string]interf
 	return &weekly
 }
 
+func flattenBackupProtectionPolicyVMResourceGroup(rpDetail *backup.InstantRPAdditionalDetails) []interface{} {
+	if rpDetail == nil || rpDetail.AzureBackupRGNamePrefix == nil {
+		return nil
+	}
```
Comment (stephybun) [inline internal/services/recoveryservices/backup_policy_vm_resource.go:544]: Do we need to nil check here since we're already nil checking the input on https://github.com/hashicorp/terraform-provider-azurerm/blob/2186bdcdbdbc3ff18fd75698628dc9bcc11d7c3c/internal/services/recoveryservices/backup_policy_vm_resource.go#L275

File: internal/services/recoveryservices/backup_policy_vm_resource.go [hunk 2]
```diff
@@ -517,6 +538,24 @@ func expandBackupProtectionPolicyVMRetentionWeeklyFormat(block map[string]interf
...
+
+	block := map[string]interface{}{}
+
+	if rpDetail.AzureBackupRGNamePrefix != nil {
+		block["prefix"] = *rpDetail.AzureBackupRGNamePrefix
+	}
+
+	if rpDetail.AzureBackupRGNameSuffix != nil {
+		block["suffix"] = *rpDetail.AzureBackupRGNameSuffix
+	}
```
Comment (stephybun) [inline internal/services/recoveryservices/backup_policy_vm_resource.go:554]: These need to have a value set into state
```suggestion
	prefix := ""
	if rpDetail.AzureBackupRGNamePrefix != nil {
		prefix = *rpDetail.AzureBackupRGNamePrefix
	}
	block["prefix"] = prefix

        suffix := ""
	if rpDetail.AzureBackupRGNameSuffix != nil {
		suffix = *rpDetail.AzureBackupRGNameSuffix
	}
	block["suffix"] = suffix
```

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this @ziyeqf, left a few comments in-line but once those are fixed up we can take another look at this!

**Comment by ziyeqf** [comment]
test
---
```
terraform-provider-azurerm ❯ TF_ACC=1 go test -v ./internal/services/recoveryservices -run=TestAccBackupProtectionPolicyVM -timeout=600m                          [ tengzh/issue/policy_vm_enhance][$!][🐹 v1.19.6][⏱ 3m55s][10:24:48]
=== RUN   TestAccBackupProtectionPolicyVM_policyTypeDefault
=== PAUSE TestAccBackupProtectionPolicyVM_policyTypeDefault
=== RUN   TestAccBackupProtectionPolicyVM_basicDaily
=== PAUSE TestAccBackupProtectionPolicyVM_basicDaily
=== RUN   TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdate
=== PAUSE TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdate
=== RUN   TestAccBackupProtectionPolicyVM_requiresImport
=== PAUSE TestAccBackupProtectionPolicyVM_requiresImport
=== RUN   TestAccBackupProtectionPolicyVM_basicWeekly
=== PAUSE TestAccBackupProtectionPolicyVM_basicWeekly
=== RUN   TestAccBackupProtectionPolicyVM_completeDaily
=== PAUSE TestAccBackupProtectionPolicyVM_completeDaily
=== RUN   TestAccBackupProtectionPolicyVM_completeWeekly
=== PAUSE TestAccBackupProtectionPolicyVM_completeWeekly
=== RUN   TestAccBackupProtectionPolicyVM_updateDaily
=== PAUSE TestAccBackupProtectionPolicyVM_updateDaily
=== RUN   TestAccBackupProtectionPolicyVM_updateWeekly
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeekly
=== RUN   TestAccBackupProtectionPolicyVM_updateDailyToWeekly
=== PAUSE TestAccBackupProtectionPolicyVM_updateDailyToWeekly
=== RUN   TestAccBackupProtectionPolicyVM_updateWeeklyToDaily
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeeklyToDaily
=== RUN   TestAccBackupProtectionPolicyVM_updateWeeklyToPartial
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeeklyToPartial
=== RUN   TestAccBackupProtectionPolicyVM_basicHourlyV2
=== PAUSE TestAccBackupProtectionPolicyVM_basicHourlyV2
=== RUN   TestAccBackupProtectionPolicyVM_basicDailyV2
=== PAUSE TestAccBackupProtectionPolicyVM_basicDailyV2
=== RUN   TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdateV2
=== PAUSE TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdateV2
=== RUN   TestAccBackupProtectionPolicyVM_basicWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_basicWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_completeHourlyV2
=== PAUSE TestAccBackupProtectionPolicyVM_completeHourlyV2
=== RUN   TestAccBackupProtectionPolicyVM_completeDailyV2
=== PAUSE TestAccBackupProtectionPolicyVM_completeDailyV2
=== RUN   TestAccBackupProtectionPolicyVM_completeWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_completeWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateHourlyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateHourlyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateDailyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateDailyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateHourlyAndWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateHourlyAndWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateDailyAndWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateDailyAndWeeklyV2
=== RUN   TestAccBackupProtectionPolicyVM_updateWeeklyToPartialV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeeklyToPartialV2
=== RUN   TestAccBackupProtectionPolicyVM_withCustomRGName
=== PAUSE TestAccBackupProtectionPolicyVM_withCustomRGName
=== RUN   TestAccBackupProtectionPolicyVMWorkload_basic
=== PAUSE TestAccBackupProtectionPolicyVMWorkload_basic
=== RUN   TestAccBackupProtectionPolicyVMWorkload_update
=== PAUSE TestAccBackupProtectionPolicyVMWorkload_update
=== CONT  TestAccBackupProtectionPolicyVM_policyTypeDefault
=== CONT  TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdateV2
=== CONT  TestAccBackupProtectionPolicyVM_basicDailyV2
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyV2
=== CONT  TestAccBackupProtectionPolicyVM_withCustomRGName
=== CONT  TestAccBackupProtectionPolicyVMWorkload_update
=== CONT  TestAccBackupProtectionPolicyVM_completeWeeklyV2
=== CONT  TestAccBackupProtectionPolicyVM_updateDailyV2
--- PASS: TestAccBackupProtectionPolicyVM_policyTypeDefault (366.60s)
=== CONT  TestAccBackupProtectionPolicyVM_completeHourlyV2
--- PASS: TestAccBackupProtectionPolicyVM_basicDailyV2 (372.47s)
=== CONT  TestAccBackupProtectionPolicyVM_completeDailyV2
--- PASS: TestAccBackupProtectionPolicyVM_completeWeeklyV2 (382.11s)
=== CONT  TestAccBackupProtectionPolicyVM_updateHourlyV2
--- PASS: TestAccBackupProtectionPolicyVM_withCustomRGName (383.61s)
=== CONT  TestAccBackupProtectionPolicyVM_basicWeeklyV2
--- PASS: TestAccBackupProtectionPolicyVMWorkload_update (457.07s)
=== CONT  TestAccBackupProtectionPolicyVMWorkload_basic
--- PASS: TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdateV2 (485.38s)
=== CONT  TestAccBackupProtectionPolicyVM_updateDailyAndWeeklyV2
--- PASS: TestAccBackupProtectionPolicyVM_updateDailyV2 (538.14s)
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyToPartialV2
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyV2
    testing_new.go:86: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Resource Group: (Resource Group "acctestRG-backup-230221102458923558"): resources.GroupsClient#Delete: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'acctestRG-backup-230221102458923558' could not be found."
        
--- FAIL: TestAccBackupProtectionPolicyVM_updateWeeklyV2 (552.81s)
=== CONT  TestAccBackupProtectionPolicyVM_updateHourlyAndWeeklyV2
--- PASS: TestAccBackupProtectionPolicyVM_completeHourlyV2 (378.56s)
=== CONT  TestAccBackupProtectionPolicyVM_updateDaily
--- PASS: TestAccBackupProtectionPolicyVM_completeDailyV2 (373.01s)
=== CONT  TestAccBackupProtectionPolicyVM_basicHourlyV2
--- PASS: TestAccBackupProtectionPolicyVM_basicWeeklyV2 (372.31s)
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyToPartial
--- PASS: TestAccBackupProtectionPolicyVMWorkload_basic (355.19s)
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyToDaily
--- PASS: TestAccBackupProtectionPolicyVM_updateHourlyV2 (469.86s)
=== CONT  TestAccBackupProtectionPolicyVM_updateDailyToWeekly
--- PASS: TestAccBackupProtectionPolicyVM_updateWeeklyToPartialV2 (482.49s)
=== CONT  TestAccBackupProtectionPolicyVM_updateWeekly
--- PASS: TestAccBackupProtectionPolicyVM_updateDailyAndWeeklyV2 (598.51s)
=== CONT  TestAccBackupProtectionPolicyVM_basicWeekly
--- PASS: TestAccBackupProtectionPolicyVM_basicHourlyV2 (371.17s)
=== CONT  TestAccBackupProtectionPolicyVM_completeWeekly
--- PASS: TestAccBackupProtectionPolicyVM_updateHourlyAndWeeklyV2 (597.10s)
=== CONT  TestAccBackupProtectionPolicyVM_completeDaily
--- PASS: TestAccBackupProtectionPolicyVM_updateDaily (464.03s)
=== CONT  TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdate
--- PASS: TestAccBackupProtectionPolicyVM_updateWeeklyToPartial (469.64s)
=== CONT  TestAccBackupProtectionPolicyVM_requiresImport
--- PASS: TestAccBackupProtectionPolicyVM_updateWeeklyToDaily (466.14s)
=== CONT  TestAccBackupProtectionPolicyVM_basicDaily
--- PASS: TestAccBackupProtectionPolicyVM_updateDailyToWeekly (471.08s)
--- PASS: TestAccBackupProtectionPolicyVM_basicWeekly (373.94s)
--- PASS: TestAccBackupProtectionPolicyVM_updateWeekly (460.97s)
--- PASS: TestAccBackupProtectionPolicyVM_completeWeekly (378.89s)
--- PASS: TestAccBackupProtectionPolicyVM_completeDaily (367.10s)
--- PASS: TestAccBackupProtectionPolicyVM_requiresImport (395.18s)
--- PASS: TestAccBackupProtectionPolicyVM_basicDaily (370.13s)
--- PASS: TestAccBackupProtectionPolicyVM_withInstantRestoreRetentionRangeUpdate (478.92s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      1689.355s
FAIL
```

failed one
---
```
terraform-provider-azurerm ❯ TF_ACC=1 go test -v ./internal/services/recoveryservices -run=TestAccBackupProtectionPolicyVM_updateWeeklyV2 -timeout=600m             [ tengzh/issue/policy_vm_enhance][$][🐹 v1.19.6][⏱ 24ms][10:50:39]
=== RUN   TestAccBackupProtectionPolicyVM_updateWeeklyV2
=== PAUSE TestAccBackupProtectionPolicyVM_updateWeeklyV2
=== CONT  TestAccBackupProtectionPolicyVM_updateWeeklyV2
--- PASS: TestAccBackupProtectionPolicyVM_updateWeeklyV2 (497.98s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      499.228s

```

**Review by stephybun — APPROVED** [review]
Thanks @ziyeqf LGTM 🌶️
