### PR TITLE
[Enhancement:] `azurerm_databricks_workspace`/`azurerm_databricks_workspace_root_dbfs_customer_managed_key` - expose `managed_services_cmk_key_vault_id`, `managed_disk_cmk_key_vault_id` and `key_vault_id` to support cross subscription CMK's

### LINKED ISSUE #24883: [ISSUE] Issue with azurerm_databricks_workspace resource and CMK for encryption cross subscriptions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.91.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  skip_provider_registration = true
  subscription_id            = ""
}

provider "azurerm" {
  features {}
  alias           = "management"
  subscription_id = ""
}

data "azurerm_key_vault" "existing" {
  provider            = azurerm.management
  name                = "mngt-kvault1"
  resource_group_name = "mngt"
}

data "azurerm_key_vault_key" "example" {
  provider            = azurerm.management
  name         = "databricks-cmk"
  key_vault_id = data.azurerm_key_vault.existing.id
}

resource "azurerm_databricks_workspace" "this" {
  name                                                = var.databricks_workspace_name
  resource_group_name                                 = var.spoke_resource_group_name
  managed_resource_group_name                         = local.managed_resource_group_name
  location                                            = var.location
  customer_managed_key_enabled                        = "true"
  managed_services_cmk_key_vault_key_id               = data.azurerm_key_vault_key.example.id
  managed_disk_cmk_key_vault_key_id                   = data.azurerm_key_vault_key.example.id
  managed_disk_cmk_rotation_to_latest_version_enabled = "true"
  sku                                                 = "premium"

  custom_parameters {
    no_public_ip                                         = true
    virtual_network_id                                   = azurerm_virtual_network.this.id
    private_subnet_name                                  = azurerm_subnet.private.name
    public_subnet_name                                   = azurerm_subnet.public.name
    private_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.private.id
    public_subnet_network_security_group_association_id  = azurerm_subnet_network_security_group_association.public.id
  }
}
```

### Debug Output/Panic Output

```shell
2024-02-14T17:13:13.062+0800 [ERROR] vertex "module.adb-lakehouse.azurerm_databricks_workspace.this" error: retrieving the Resource ID for the customer-managed keys for managed services Key Vault at URL "https://mngt-kvault1.vault.azure.net/": <nil>
╷
│ Error: retrieving the Resource ID for the customer-managed keys for managed services Key Vault at URL "https://mngt-kvault1.vault.azure.net/": <nil>
│ 
│   with module.adb-lakehouse.azurerm_databricks_workspace.this,
│   on ../../modules/adb-lakehouse/vnet_injected_databricks_workspace.tf line 67, in resource "azurerm_databricks_workspace" "this":
│   67: resource "azurerm_databricks_workspace" "this" {
│
```

### Expected Behaviour

When deploying a new Azure Databricks workspace and using encryption with a Customer Managed Key (CMK) sourced from a Key Vault in a distinct Azure subscription, the workspace must be instantiated utilizing said key for encryption. Same behaviour should apply when configuring CMK to an existing Azure Databricks workspace. 

### Actual Behaviour

During the execution of "terraform apply," the AzureRM provider fails in accessing the key from the other subscription. We experimented with both passing the key ID as a variable and utilising a Terraform Data Source, but neither method proved successful.
Similar [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/20199) 

### Steps to Reproduce

Using the adb-lakehouse Terraform [example](https://github.com/databricks/terraform-databricks-examples/tree/main/examples/adb-lakehouse) and adding the CMK arguments to azurerm_databricks_workspace resource. 

### Important Factoids

_No response_

### References

Similar [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/20199)

### PR DESCRIPTION
**Pull request by WodansSon**
(fixes #24883)

### CODE REVIEW

**Comment by WodansSon** [comment]
Validating that current changes to the resource does not break current behavior... still testing cross subscription key vault scenario...

image

**Comment by MaguellSandifort** [comment]
I gave this a go with a cross subscription key vault configuration. The workspace is deployed to subscription 1, while the keyvault with the key is stored in subscription 2.

The databricks workspace is deployed with
```
managed_disk_cmk_key_vault_key_id = data.azurerm_key_vault_key.cmk
managed_services_cmk_key_vault_key_id = data.azurerm_key_vault_key.cmk
```

The `key_vault_key` data sources are run with a second provider set to subscription 2

During the deployment of the workspace, terraform runs into this:
afbeelding

**Comment by WodansSon** [comment]
> I gave this a go with a cross subscription key vault configuration. The workspace is deployed to subscription 1, while the keyvault with the key is stored in subscription 2.
> 
> The databricks workspace is deployed with
> 
> ```
> managed_disk_cmk_key_vault_key_id = data.azurerm_key_vault_key.cmk
> managed_services_cmk_key_vault_key_id = data.azurerm_key_vault_key.cmk
> ```
> 
> The `key_vault_key` data sources are run with a second provider set to subscription 2
> 
> During the deployment of the workspace, terraform runs into this: afbeelding

@MaguellSandifort, can you add this to the issue rather than the PR? That said did you define the newly exposed `managed_cmk_key_vault_id` in your databricks resource config? I have done just finished testing this new functionality and it works as expected for me.

**Comment by WodansSon** [comment]
No regressions due to code changes in this PR...
image

**Review by MaguellSandifort — COMMENTED** [review]
Works like a charm! 

I did run into an issue with our configuration: We deployed with 2 service principals, one for each provider. Each SP only had permissions on its own subscription. That resulted in the error:

``` 
Error: retrieving the Resource ID for the customer-managed keys for managed services Key Vault in subscription "Subscription (Subscription: <key vault subscription>)" at URL "<key vault url>: listing the Key Vaults within Subscription (Subscription: "<key vault subscription>"): loading the initial page: vaults.VaultsClient#ListBySubscription: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<SP of the first provider>' with object id '<SP of the first provider>' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '<key vault subscription>' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

So when deploying, the SP linked to the provider that deploys the workspace needs at least read permissions on the keyvault in the second subscription. 

Unsure if that can be easily fixed; might be good to add it as a caveat to the docs?

**Comment by WodansSon** [comment]
> Works like a charm!
> 
> I did run into an issue with our configuration: We deployed with 2 service principals, one for each provider. Each SP only had permissions on its own subscription. That resulted in the error:
> 
> ```
> Error: retrieving the Resource ID for the customer-managed keys for managed services Key Vault in subscription "Subscription (Subscription: <key vault subscription>)" at URL "<key vault url>: listing the Key Vaults within Subscription (Subscription: "<key vault subscription>"): loading the initial page: vaults.VaultsClient#ListBySubscription: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<SP of the first provider>' with object id '<SP of the first provider>' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '<key vault subscription>' or the scope is invalid. If access was recently granted, please refresh your credentials."
> ```
> 
> So when deploying, the SP linked to the provider that deploys the workspace needs at least read permissions on the keyvault in the second subscription.
> 
> Unsure if that can be easily fixed; might be good to add it as a caveat to the docs?

Good to know, thank you for testing this new code in the real world. It is often hard to try to repro the exact scenario our customers are hitting in our dev environments for various reasons. TBH, I didn't even think about the providers being executed under different SPN's. You are 100% right, since Terraform runs under the SPN that ran the `apply` command that the SPN should prolly be given `Read` and `List` perms to that subscription, which should be easily done via the `azurerm_key_vault_access_policy` resource. I will add this as a note in the documentation for this PR.

**Comment by WodansSon** [comment]
Need to get the documentation right to note multiple SPN scenario...

**Comment by WodansSon** [comment]
image

File: internal/services/databricks/databricks_root_dbfs_customer_managed_key_resource.go [hunk 1]
```diff
@@ -67,6 +67,13 @@ func resourceDatabricksWorkspaceRootDbfsCustomerManagedKey() *pluginsdk.Resource
 				Required:     true,
 				ValidateFunc: keyVaultValidate.KeyVaultChildID,
 			},
+
+			// added to support cross subscription cmk's
+			"key_vault_id": {
```
Comment (katbyte) [inline internal/services/databricks/databricks_root_dbfs_customer_managed_key_resource.go:72]: So i am wondering if there is a way to solve this with out adding a new property?

key_vault_key.id is the data plane id which is a uri, however we have key_vault_key.resource[_versionless]_id which is the resource manager ID which should contain the subscription.

key_vault_key_id should likely already expect the RM ID (vs key_vault_key_uri which is the data plane URI)

i imagine we might be able to support both for the property, however it would break import as we wouldn't be able to know which format to write on an import - would it make sense to just do a breaking change here?

**Review by katbyte — CHANGES_REQUESTED** [review]

File: internal/services/databricks/databricks_root_dbfs_customer_managed_key_resource.go (hunk 1 above)
Comment (WodansSon) [reply internal/services/databricks/databricks_root_dbfs_customer_managed_key_resource.go:70]: Using a RM ID isn't possible here since you can't get the subscription from the URL and the API only contains the key vault key URL...

**Comment by WodansSon** [comment]
image

**Review by katbyte — APPROVED** [review]
LGTM 🎢 :

**Comment by WodansSon** [comment]
image
