### PR TITLE
`azurerm_palo_alto_next_generation_firewall_virtual_network_local_rulestack`: add lock of `ruleStackID` in creating

### LINKED ISSUE #23472: Firewall creation failure during initial attempt
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.3.7

### AzureRM Provider Version

3.69.0

### Affected Resource(s)/Data Source(s)

azurerm_palo_alto_next_generation_firewall_virtual_network_local_rulestack

### Terraform Configuration Files

```hcl
# create resource group
resource azurerm_resource_group "rg" {
    name = "rg-${var.resource_suffix}"
    location = var.location
    tags = var.tags
} 

# create vnet/subnets

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet-fw-${var.resource_suffix}"
  address_space       = [var.vnet_cidr]
  location            = var.location

  resource_group_name = azurerm_resource_group.rg.name

  tags = {
    Purpose = "terraform testing"
  }
}

# create localrulestack
resource azurerm_palo_alto_local_rulestack "lrs1" {
    name = "lrs-${var.resource_suffix}-1"
    resource_group_name = azurerm_resource_group.rg.name
    location = var.location
    description = "rulestack1"
}

resource azurerm_palo_alto_local_rulestack "lrs2" {
    name = "lrs-${var.resource_suffix}-2"
    resource_group_name = azurerm_resource_group.rg.name
    location = var.location
    description = "rulestack2"
}

# create prefix list
resource "azurerm_palo_alto_local_rulestack_prefix_list" "prefix" {
  name         = "prefix-${var.resource_suffix}"
  prefix_list  = [ "10.0.2.0/26" ]
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  description = "prefixlist1"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
}

# create fqdn list
resource azurerm_palo_alto_local_rulestack_fqdn_list "fqdn" {
  name = "fqdn-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  fully_qualified_domain_names = ["www.defnews.com"]
  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
}

# create certificate (self signed)
resource "azurerm_palo_alto_local_rulestack_certificate" "cert" {
  name         = "cert-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  self_signed = true
  # key_vault_certificate_id  = "https://kvtesting456.vault.azure.net/certificates/kvtesting"
  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
}

# creare local rulestack rule
resource "azurerm_palo_alto_local_rulestack_rule" "localrule" {
  name          = "rule-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1000
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/24"]
  }
  destination {
    cidrs = ["192.168.16.0/24"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

# create localrulestack rule2
resource "azurerm_palo_alto_local_rulestack_rule" "localrule2" {
  name          = "rule2-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1001
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

resource "azurerm_palo_alto_local_rulestack_rule" "localrule3" {
  name          = "rule3-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1002
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

resource "azurerm_palo_alto_local_rulestack_rule" "localrule5" {
  name          = "rule5-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1003
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

resource "azurerm_palo_alto_local_rulestack_rule" "localrule4" {
  name          = "rule4-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1004
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

data "azurerm_virtual_network" "vnet" {
  name = "vnet-fw-${var.resource_suffix}"
  resource_group_name = var.rgname
}

data "azurerm_palo_alto_local_rulestack" "lrs-out" {
  resource_group_name = var.rgname
  name = var.lrsname
}

resource "azurerm_subnet" "trust" {
  name                 = "subnet-trust-vnetfw-${var.resource_suffix}"
  resource_group_name  = var.rgname
  virtual_network_name = var.vnet_name
  address_prefixes     = [var.trust_subnet_cidr]

  delegation {
    name = "trusted"

    service_delegation {
      name = "PaloAltoNetworks.Cloudngfw/firewalls"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_subnet" "untrust" {
  name                 = "subnet-untrust-vnetfw-${var.resource_suffix}"
  resource_group_name  = var.rgname
  virtual_network_name = var.vnet_name
  address_prefixes     = [var.untrust_subnet_cidr]

  delegation {
    name = "untrusted"

    service_delegation {
      name = "PaloAltoNetworks.Cloudngfw/firewalls"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

# create outbound certificate association
resource "azurerm_palo_alto_local_rulestack_outbound_trust_certificate_association" "certassoc" {
  certificate_id = var.cert_id
}

# create public ip
resource "azurerm_public_ip" "vnetfw-pubip" {
  name                ="pip-vnetfw-${var.resource_suffix}"
  location            = var.location
  resource_group_name = var.rgname
  allocation_method   = "Static"
  sku                 = "Standard"
}

# create vnet firewall
resource "azurerm_palo_alto_next_generation_firewall_virtual_network_local_rulestack" "firewall1" {
  name                = "vnetfw-${var.resource_suffix}"
  resource_group_name = var.rgname
  rulestack_id        = data.azurerm_palo_alto_local_rulestack.lrs-out.id

  network_profile {
    public_ip_address_ids = [azurerm_public_ip.vnetfw-pubip.id]

    vnet_configuration {
      virtual_network_id  = data.azurerm_virtual_network.vnet.id
      trusted_subnet_id   = azurerm_subnet.trust.id
      untrusted_subnet_id = azurerm_subnet.untrust.id
    }
  }

  dns_settings {
    dns_servers = [azurerm_public_ip.vnetfw-pubip.ip_address]
  }

  # destination_nat {
  #   backend_config {
  #     port = 80
  #     public_ip_address = "10.3.1.12"
  #   }
  #   frontend_config {
  #     port = 80
  #     public_ip_address_id = azurerm_public_ip.fw-vnet-pubip.id
  #   }
  #   protocol = "TCP"
  #   name = "${var.resource_prefix}-fw-${local.timestring}-dnat1"
  # }
  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
“tenantId”: “e6579873-b3c7-4248-b0b5-700db290acec”,
    “properties”: {
        “statusCode”: “BadRequest”,
        “serviceRequestId”: null,
        “statusMessage”: “{\“error\“:{\“code\“:\“PANError\“,\“message\“:\“Commit process unfinished.\“}}“,
        “eventCategory”: “Administrative”,
```

### Expected Behaviour

Able to create firewall along with rulestack. Firewall creation should proceed after successfull commit operation performed on rulestack,.

### Actual Behaviour

Create all the resources (rulestack, rules. fqdn, prefix , firewall) from a single tf file -> this gives the above error.

Instead if we create rulestack related resources first and then firewall creation -> this works.

Upon investigation, we noticed that firewall creation is initiated when rulestack commit was still not complete triggerring race conditions.

### Steps to Reproduce

1. Create firewall and all other resources (rulestack,rules etc..) from a single tf file.

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by wuxu92**
fixes #23472.

Firewall Creating should be sequentialized with other rule create operation, so we should add a lock for it (also extend timeout value).

image

### CODE REVIEW

File: internal/services/paloalto/next_generation_firewall_vhub_local_rulestack_resource.go [hunk 1]
```diff
@@ -276,6 +280,12 @@ func (r NextGenerationFirewallVHubLocalRuleStackResource) Update() sdk.ResourceF
 				firewall.Tags = tags.Expand(model.Tags)
 			}
 
+			if metadata.ResourceData.HasChange("rulestack_id") {
+				ruleStackID, _ := localrulestacks.ParseLocalRulestackID(model.RuleStackId)
```
[the remark this answers is not in the document]
Comment (wuxu92) [reply internal/services/paloalto/next_generation_firewall_vhub_local_rulestack_resource.go:284]: The Line 252 above has checked this error already.

[the remark this answers is not in the document]
Comment (catriona-m) [reply internal/services/paloalto/next_generation_firewall_vhub_local_rulestack_resource.go:284]: it will only get checked there if there is the rulestack_id has been updated. I think we should check it here and in next_generation_firewall_vnet_local_rulestack_resource.go line 280 as well just to be on the safe side.

[the remark this answers is not in the document]
Comment (wuxu92) [reply internal/services/paloalto/next_generation_firewall_vhub_local_rulestack_resource.go]: error check added.

File: internal/services/paloalto/next_generation_firewall_vhub_local_rulestack_resource.go [hunk 2]
```diff
@@ -276,6 +280,15 @@ func (r NextGenerationFirewallVHubLocalRuleStackResource) Update() sdk.ResourceF
 				firewall.Tags = tags.Expand(model.Tags)
 			}
 
+			if metadata.ResourceData.HasChange("rulestack_id") {
```
Comment (catriona-m) [inline internal/services/paloalto/next_generation_firewall_vhub_local_rulestack_resource.go:283]: should we be locking when `rulestack_id` has not changed too?

Comment (wuxu92) [reply internal/services/paloalto/next_generation_firewall_vhub_local_rulestack_resource.go:283]: TBH I'm not sure about this because it seems to be related to the API implementation. But intuitively, we only need lock when `rulestack_id` changes as it's only a reference to the rulestack resource.

Comment (catriona-m) [reply internal/services/paloalto/next_generation_firewall_vhub_local_rulestack_resource.go:283]: we could add the locks after line 251 then to avoid checking if it's changed and parsing it twice

Comment (wuxu92) [reply internal/services/paloalto/next_generation_firewall_vhub_local_rulestack_resource.go]: I have ever thought about it before, but now moved the locks after L251.

**Review by catriona-m — APPROVED** [review]
Thanks @wuxu92 LGTM!
