### PR TITLE
`azurerm_web_application_firewall_policy` - fix the value of `rule_group_name` does not exist for Application Gateway Firewall

### LINKED ISSUE #24160: RuleGroup 'APPLICATION-ATTACK-SQLI' cannot be configured for rule set `Microsoft_DefaultRuleSet` version `2.1`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.84.0

### Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy

### Terraform Configuration Files

```hcl
resource "azurerm_web_application_firewall_policy" "application_gateway" {
  name                = "my-waf-policy"
  location            = azurerm_resource_group.application_gateway.location
  resource_group_name = azurerm_resource_group.application_gateway.name

  managed_rules {
    managed_rule_set {
      type    = "Microsoft_DefaultRuleSet"
      version = "2.1"

      rule_group_override {
        rule_group_name = "APPLICATION-ATTACK-SQLI"

        rule {
          action  = "AnomalyScoring"
          id      = "942110"
          enabled = false
        }
        rule {
          action  = "AnomalyScoring"
          enabled = false
          id      = "942150"
        }
        rule {
          action  = "AnomalyScoring"
          enabled = false
          id      = "942230"
        }
        rule {
          action  = "AnomalyScoring"
          enabled = false
          id      = "942260"
        }
        rule {
          action  = "AnomalyScoring"
          enabled = false
          id      = "942430"
        }
        rule {
          action  = "AnomalyScoring"
          enabled = false
          id      = "942440"
        }
      }
    }
    managed_rule_set {
      type    = "Microsoft_BotManagerRuleSet"
      version = "1.0"
    }
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: creating Application Gateway Web Application Firewall Policy (Subscription: "xxx"
│ Resource Group Name: "application-gateway-test"
│ Application Gateway Web Application Firewall Policy Name: "test"): unexpected status 400 with error: ApplicationGatewayFirewallUnknownRuleGroup: RuleGroup 'APPLICATION-ATTACK-SQLI' cannot be configured since it does not exist for Application Gateway Firewall in context ''.
│ 
│   with azurerm_web_application_firewall_policy.application_gateway,
│   on ../../application-gateway-waf.tf line 1, in resource "azurerm_web_application_firewall_policy" "application_gateway":
│    1: resource "azurerm_web_application_firewall_policy" "application_gateway" {
│ 
╵
##[error]Bash exited with code '1'.
```

### Expected Behaviour

Rule group `Microsoft_DefaultRuleSet` gets configured

### Actual Behaviour

Error during terraform apply

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by sinbai**
After testing, the following values of `rule_group_name` of DRS do not exist for  Application Gateway Firewall.
  "APPLICATION-ATTACK-LFI",
	"APPLICATION-ATTACK-RFI",
	"APPLICATION-ATTACK-RCE",
	"APPLICATION-ATTACK-PHP",
	"APPLICATION-ATTACK-NodeJS",
	"APPLICATION-ATTACK-XSS",
	"APPLICATION-ATTACK-SQLI",
	"APPLICATION-ATTACK-SESSION-FIXATION",
	"APPLICATION-ATTACK-SESSION-JAVA"

The facts should look like this:
        "LFI",
	"RFI",
	"RCE",
	"PHP",
	"NODEJS",
	"XSS",
	"SQLI",
	"FIX",
	"JAVA"

Submit this PR to update `rule_group_name` in order to fix #24160.

Test result:
PASS: TestAccWebApplicationFirewallPolicy_ManagedRuleSetDRS (312.58s)

### CODE REVIEW

File: internal/services/network/web_application_firewall_policy_resource.go [hunk 1]
```diff
@@ -1296,3 +1296,57 @@ func flattenWebApplicationFirewallPoliciesSubResourcesToIDs(input *[]webapplicat
...
+		ruleGroupName = "SQLI"
+	case "APPLICATION-ATTACK-SESSION-FIXATION":
+		ruleGroupName = "FIX"
+	case "APPLICATION-ATTACK-SESSION-JAVA":
+		ruleGroupName = "JAVA"
+	default:
+		ruleGroupName = name
+	}
+	return ruleGroupName
+}
```
Comment (stephybun) [inline internal/services/network/web_application_firewall_policy_resource.go:1325]: If the API doesn't accept any of these values then we can probably just remove these from the validation function instead of adding a conversion function here?

File: internal/services/network/web_application_firewall_policy_resource.go [hunk 2]
```diff
@@ -1296,3 +1296,57 @@ func flattenWebApplicationFirewallPoliciesSubResourcesToIDs(input *[]webapplicat
...
+		ruleGroupName = "APPLICATION-ATTACK-SQLI"
+	case "FIX":
+		ruleGroupName = "APPLICATION-ATTACK-SESSION-FIXATION"
+	case "JAVA":
+		ruleGroupName = "APPLICATION-ATTACK-SESSION-JAVA"
+	default:
+		ruleGroupName = name
+	}
+	return ruleGroupName
+}
```
Comment (stephybun) [inline internal/services/network/web_application_firewall_policy_resource.go:1352]: Then we can also remove this unnecessary conversion.

**Review by stephybun — CHANGES_REQUESTED** [review]
@sinbai - I think this can be fixed in a more straight forward way depending on what the API accepts. Please take a look at the comments left in-line.

**Review by alexdokka — COMMENTED** [review]
maybe it’s better to just add new values (needed for Microsoft_DefaultRuleSet 2.1 ) and leave the old ones (needed for OWASP 3.2) ?

**Comment by stephybun** [comment]
@alexdokka if the old ones are still valid for a different configuration then I agree, we should just add the new ones.

**Comment by sinbai** [comment]
> maybe it’s better to just add new values (needed for Microsoft_DefaultRuleSet 2.1 ) and don't touch the old ones (needed for OWASP 3.2) ?

In fact, the old ones are not supported by the other versions either.

File: internal/services/network/web_application_firewall_policy_resource.go (hunk 1 above)
Comment (sinbai) [reply internal/services/network/web_application_firewall_policy_resource.go]: fixed.

File: internal/services/network/web_application_firewall_policy_resource.go (hunk 2 above)
Comment (sinbai) [reply internal/services/network/web_application_firewall_policy_resource.go]: fixed.

**Comment by sinbai** [comment]
> @sinbai - I think this can be fixed in a more straight forward way depending on what the API accepts. Please take a look at the comments left in-line.


Hi @stephybun thanks for your feedback. The code has been updated. Could you please take another look?

File: internal/services/network/validate/web_application_firewall_policy.go [hunk 3]
```diff
@@ -38,15 +38,15 @@ var ValidateWebApplicationFirewallPolicyRuleGroupName = validation.StringInSlice
...
-	"APPLICATION-ATTACK-LFI",
-	"APPLICATION-ATTACK-RFI",
-	"APPLICATION-ATTACK-RCE",
-	"APPLICATION-ATTACK-PHP",
-	"APPLICATION-ATTACK-NodeJS",
-	"APPLICATION-ATTACK-XSS",
-	"APPLICATION-ATTACK-SQLI",
-	"APPLICATION-ATTACK-SESSION-FIXATION",
-	"APPLICATION-ATTACK-SESSION-JAVA",
+	"LFI",
```
Comment (stephybun) [inline internal/services/network/validate/web_application_firewall_policy.go:41]: Looking into this further there is a command which returns a list of supported rule set names and there are two that are still missing. Can you please add `crs_49_inbound_blocking` and `KnownBadBots` to the validation.

Can you also please add the following comment in this validation function - It will be helpful to ensure this list remains up to date:
```
// The following command will return a list of available Rule Group Names with information on whether the rules are GA, Deprecated, etc.:
// az rest --method get --url “https://management.azure.com/subscriptions/{subscription_id_here}/providers/Microsoft.Network/locations/{location}/applicationGatewayWafDynamicManifests/default?api-version=2023-05-01” --query “properties.availableRuleSets[].ruleGroups[].ruleGroupName” | sort | uniq
```

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for updating the validation values and for checking the behaviour of the API @sinbai 

There are actually two values that are missing from the validation and I think it'd be helpful to add a comment that will enable us to keep these values up to date.

Once those two additions are in this is good to go!

File: internal/services/network/validate/web_application_firewall_policy.go (hunk 3 above)
Comment (sinbai) [reply internal/services/network/validate/web_application_firewall_policy.go:45]: Great suggestion about adding above comment, the code has been updated. Could you please take a look at it again?

**Review by katbyte — APPROVED** [review]
LGTM 🧯
