### PR TITLE
[BUG:] `azurerm_cdn_frontdoor_route` - fix read function to parse `cdn_frontdoor_origin_group_id` insensitively

### LINKED ISSUE #19103: Terraform keeps trying to change casing after importing azurerm_cdn_front_door_route
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_route

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_profile" "afd" {
  name                = "afd-example-dev"
  resource_group_name = azurerm_resource_group.afd.name
  sku_name            = "Premium_AzureFrontDoor"

}

resource "azurerm_cdn_frontdoor_endpoint" "afd" {
  name                     = "default-endpoint"
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.afd.id
}

resource "azurerm_cdn_frontdoor_origin_group" "origin_group" {
  name                     = "origin1"
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.afd.id

  load_balancing {
    additional_latency_in_milliseconds = 0
    sample_size                        = 16
    successful_samples_required        = 3
  }
}

resource "azurerm_cdn_frontdoor_origin" "origin" {
  name                          = "origin1"
  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.origin_groups.id

  enabled                        = true
  certificate_name_check_enabled = true

  host_name          = "example.com"
  origin_host_header = "example.com"
}


#### resources below are created through the azure portal and imported afterwards

resource "azurerm_cdn_frontdoor_custom_domain" "domains" {
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.afd.id
  host_name                = "example.com"
  tls {
    certificate_type    = "ManagedCertificate"
    minimum_tls_version = "TLS12"
  }
}

resource "azurerm_cdn_frontdoor_route" "route" {
  name                          = "route1"
  cdn_frontdoor_endpoint_id     = azurerm_cdn_frontdoor_endpoint.afd.id
  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.origin_groups.id
  cdn_frontdoor_origin_ids      = [azurerm_cdn_frontdoor_origin.origin.id]
  enabled                       = true

  forwarding_protocol    = "HttpsOnly"
  https_redirect_enabled = true
  patterns_to_match      = ["/*"]
  supported_protocols    = ["Http", "Https"]

  cdn_frontdoor_custom_domain_ids = [azurerm_cdn_frontdoor_custom_domain.domain.id]
  link_to_default_domain          = false

}

resource "azurerm_cdn_frontdoor_custom_domain_association" "domain_associations" {
  cdn_frontdoor_route_ids        = [azurerm_cdn_frontdoor_route.route.id]
  cdn_frontdoor_custom_domain_id = azurerm_cdn_frontdoor_custom_domain.domain.id
}
```

### Debug Output/Panic Output

```shell
# azurerm_cdn_frontdoor_route.route["example"] will be updated in-place
  ~ resource "azurerm_cdn_frontdoor_route" "routes" {
      ~ cdn_frontdoor_origin_group_id   = "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/rg-example/providers/Microsoft.Cdn/profiles/afd-example-dev/origingroups/example-com" -> "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-example/providers/Microsoft.Cdn/profiles/afd-example-dev/originGroups/example-com"
        id                              = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-example/providers/Microsoft.Cdn/profiles/afd-example-dev/afdEndpoints/default-endpoint/routes/example-com"
        name                            = "example-com"
        # (10 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
```

### Expected Behaviour

I would expect terraform to find no changes, as the ID is already correct, it is just changing origingroups -> originGroups

### Actual Behaviour

On each terraform plan and apply, the change keeps recurring in the terraform plan. If I apply the plan the change goes through succesfully, but just comes back the next run.

### Steps to Reproduce

1. create the azurerm_cdn_frontdoor_profile, azurerm_cdn_frontdoor_endpoint, azurerm_cdn_frontdoor_origin_group, azurerm_cdn_frontdoor_origin through terraform
2.  create the azurerm_cdn_frontdoor_custom_domain, azurerm_cdn_frontdoor_route and azurerm_cdn_frontdoor_custom_domain_association in the portal **first** and then import them into the state. 

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by WodansSon**
(fixes #19103)

### CODE REVIEW

**Comment by WodansSon** [comment]
image

File: internal/services/cdn/cdn_frontdoor_route_resource.go [hunk 1]
```diff
@@ -326,7 +326,7 @@ func resourceCdnFrontDoorRouteRead(d *pluginsdk.ResourceData, meta interface{})
 	ctx, cancel := timeouts.ForRead(meta.(*clients.Client).StopContext, d)
 	defer cancel()
 
-	id, err := parse.FrontDoorRouteID(d.Id())
+	id, err := parse.FrontDoorRouteIDInsensitively(d.Id())
```
Comment (tombuildsstuff) [inline internal/services/cdn/cdn_frontdoor_route_resource.go:329]: this would signify the resource has been imported incorrectly, which there's validation to check this is valid, so this doesn't need to be set:

```suggestion
	id, err := parse.FrontDoorRouteID(d.Id())
```

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
Left a comment inline to fix up regarding the `d.Id()`

**Review by katbyte — APPROVED** [review]
LGTM 🌩️

**Comment by WodansSon** [comment]
image
