### PR TITLE
`azurerm_network_manager_deployment` - add parallel locks 

### LINKED ISSUE #25334: azurerm_network_manager_deployment only appears to deploy one thing despite TF saying it's done 'n'
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_network_manager_deployment

### Terraform Configuration Files

```hcl
data "azurerm_subscription" "current" {

}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "uk south"
}



resource "azurerm_network_manager" "example" {
  name                = "example-network-manager"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  scope {
    subscription_ids = [data.azurerm_subscription.current.id]
  }
  scope_accesses = ["Connectivity"]
  description    = "example network manager"
}

resource "azurerm_network_manager_network_group" "example" {
  name               = "example-group"
  network_manager_id = azurerm_network_manager.example.id
}

resource "azurerm_virtual_network" "example" {
  name                    = "example-net"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  address_space           = ["10.0.0.0/16"]
  flow_timeout_in_minutes = 10
}

resource "azurerm_network_manager_connectivity_configuration" "example" {
  count                 = 3
  name                  = "example-connectivity-conf-${count.index}"
  network_manager_id    = azurerm_network_manager.example.id
  connectivity_topology = "HubAndSpoke"
  applies_to_group {
    group_connectivity = "None"
    network_group_id   = azurerm_network_manager_network_group.example.id
  }
  hub {
    resource_id   = azurerm_virtual_network.example.id
    resource_type = "Microsoft.Network/virtualNetworks"
  }
}

resource "azurerm_network_manager_deployment" "example" {
  count = 3

  network_manager_id = azurerm_network_manager.example.id
  location           = "uksouth"
  scope_access       = "Connectivity"
  configuration_ids  = [azurerm_network_manager_connectivity_configuration.example[count.index].id]
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/stusklinar/bbbcaaae0da2b979e55eb99e46c0fa90

--

Running it again after a manual run, detects the deployments in Azure and removes the extra deployments.

Terraform says that its created 3 deployments - only 1 shows in portal.
You can deploy them all, and you get 1 `update`, 2 `adds` , and it runs as expected.
then if you rerun terraform, it detects they exist, and tries to remove them, as if they're not in state.


# azurerm_network_manager_deployment.example[1] will be updated in-place
  ~ resource "azurerm_network_manager_deployment" "example" {
      ~ configuration_ids  = [
            "/subscriptions/000000-0000-0000-0000-0000000/resourceGroups/example-resources/providers/Microsoft.Network/networkManagers/example-network-manager/connectivityConfigurations/example-connectivity-conf-1",
          - "/subscriptions/000000-0000-0000-0000-0000000/resourceGroups/example-resources/providers/Microsoft.Network/networkManagers/example-network-manager/connectivityConfigurations/example-connectivity-conf-0",
          - "/subscriptions/000000-0000-0000-0000-0000000/resourceGroups/example-resources/providers/Microsoft.Network/networkManagers/example-network-manager/connectivityConfigurations/example-connectivity-conf-2",
        ]
        id                 = "/subscriptions/000000-0000-0000-0000-0000000/resourceGroups/example-resources/providers/Microsoft.Network/networkManagers/example-network-manager/commit|uksouth|Connectivity"
        # (3 unchanged attributes hidden)
    }
```

### Expected Behaviour

Expected 3 deployments to have run, as the output says 3 have run/been deployed

### Actual Behaviour

Only one single deployment run
Screenshot 2024-03-20 at 15 10 09

Go into deployments and manually run - it runs the other 2 that never ran.
Screenshot 2024-03-20 at 15 10 30

Screenshot 2024-03-20 at 15 11 06

### Steps to Reproduce

terraform apply

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by teowa**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Add locks to limit provisioning multiple network manger deployment with same ID at the same time.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_network_manager_deployment` - error out if provisioning deployment with same ID concurrently [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Resolves #25334

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/network/network_manager_deployment_resource.go [hunk 1]
```diff
@@ -108,6 +109,9 @@ func (r ManagerDeploymentResource) Create() sdk.ResourceFunc {
 			normalizedLocation := azure.NormalizeLocation(state.Location)
 			id := parse.NewNetworkManagerDeploymentID(networkManagerId.SubscriptionId, networkManagerId.ResourceGroupName, networkManagerId.NetworkManagerName, normalizedLocation, state.ScopeAccess)
 
+			locks.ByID(id.ID())
+			defer locks.UnlockByID(id.ID())
```
Comment (tombuildsstuff) [inline internal/services/network/network_manager_deployment_resource.go:113]: we'll need these during Update and Delete too?

**Review by katbyte — APPROVED** [review]
LGTM 🏖️
