### PR TITLE
`azurerm_security_center_setting` - Allow `Sentinel` to be the valid `setting_name`

### LINKED ISSUE #24203: Recreation of imported azurerm_security_center_setting for Serntinel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.5.7

### AzureRM Provider Version

3.84

### Affected Resource(s)/Data Source(s)

azurerm_security_center_setting

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_setting" "self" {
  setting_name = "SENTINEL"
  enabled      = true
}
```

### Debug Output/Panic Output

```shell
# module.security-center.module.sentinel.azurerm_security_center_setting.self must be replaced
-/+ resource "azurerm_security_center_setting" "self" {
      ~ id           = "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Security/settings/Sentinel" -> (known after apply)
      ~ setting_name = "Sentinel" -> "SENTINEL" # forces replacement
        # (1 unchanged attribute hidden)
    }
```

### Expected Behaviour

setting_name argument  for azurerm_security_center_setting  have to be  "Sentinel" instead of "SENTINEL"

### Actual Behaviour

setting_name accepts only "SENTINEL" as a result existing (imported) azurerm_security_center_setting will be recreated. 
According to the[ azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/security/resource-manager/Microsoft.Security/stable/2021-06-01/settings.json#L285) SettingName for  Sentinel have to be "Sentinel"
I checked the [initial version](https://github.com/hashicorp/terraform-provider-azurerm/pull/16882/files#diff-8b9a9e5339c573abe9be55a4d83f9a24c0b85c686df5ea39465ccdf7b1f378c8R47) of azurerm_security_center_setting and it had correct setting_name value "Sentinel"

### Steps to Reproduce

1. az security setting update -n "Sentinel" --enabled true
2. Import existing Sentinel azurerm_security_center_setting 
3. Run terraform plan

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by magodo**
This PR adds a new valid `setting_name` as `Sentinel`, as is defined by the swagger: https://github.com/Azure/azure-rest-api-specs/blob/4e11f9198d3500bb47fffe805ffa7c25a1a4bc46/specification/security/resource-manager/Microsoft.Security/stable/2021-06-01/settings.json#L285, which was overlooked in the prior PR (#19126) when this was introduced. Though both `Sentinel` and `SENTINEL` can work, it would be better to align with the API spec. The `SENTINEL` is still kept until v4.0.

Fix #24203

### CODE REVIEW

File: internal/services/securitycenter/security_center_setting_resource.go [hunk 1]
```diff
@@ -46,6 +46,10 @@ func resourceSecurityCenterSetting() *pluginsdk.Resource {
 				ValidateFunc: validation.StringInSlice([]string{
 					"MCAS",
 					"WDATP",
+					"Sentinel",
+
+					// TODO 4.0: Remove this per the swagger definition:
+					//           https://github.com/Azure/azure-rest-api-specs/blob/b52464f520b77222ac8b0bdeb80a030c0fdf5b1b/specification/security/resource-manager/Microsoft.Security/stable/2021-06-01/settings.json#L285
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_setting_resource.go:52]: Can we please put this behind the `features.FourPointOhBeta()` flag instead of a comment

**Review by stephybun — CHANGES_REQUESTED** [review]

File: internal/services/securitycenter/security_center_setting_resource.go (hunk 1 above)
Comment (magodo) [reply internal/services/securitycenter/security_center_setting_resource.go]: Sure, updated!

**Review by stephybun — APPROVED** [review]
Thanks @magodo! LGTM 🥟
