### PR TITLE
`azurerm_role_assignment`: check role assignment exits for 409 error

### LINKED ISSUE #28557: `azurerm_role_assignment` already exists error does not output the id of the resource in the error
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.1

### AzureRM Provider Version

4.16.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
╷
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."
│ 
│   with module.common.module.resource_group.azurerm_role_assignment.log_analytics_readers["516411a8-5d8c-4a3d-989e-3e1f1fc54966"],
│   on .terraform/modules/common/common/resource_group/main.tf line 7, in resource "azurerm_role_assignment" "log_analytics_readers":
│    7: resource "azurerm_role_assignment" "log_analytics_readers" ***
│ 
╵
```

### Expected Behaviour

```
╷
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists." for resource /subscriptions/subscriptionid/resource_group/rgid/role_assignment/roleAssignmentId
│ 
│   with module.common.module.resource_group.azurerm_role_assignment.log_analytics_readers["516411a8-5d8c-4a3d-989e-3e1f1fc54966"],
│   on .terraform/modules/common/common/resource_group/main.tf line 7, in resource "azurerm_role_assignment" "log_analytics_readers":
│    7: resource "azurerm_role_assignment" "log_analytics_readers" ***
│ 
╵
```

I actualy don't care what the format is or where the ID is logged but right now it can't easily just be imported into the state or deleted because there is no easy way to know which role assignment is conflicting. Pretty much everything else in this provider always produces a resource id when it already exists but this one doesn't.

I'm assuming its because it gets a 409 error instead of a 400 level error like other resources because its a Role Assignment but I'm not really sure.

### Actual Behaviour

The error is emitted sans resource id so there is no easy way to resolve the issue manually.

### Steps to Reproduce

1. Create a deployment with a Role Assignment.
2. Delete it from your state file manually.
3. Deploy again.

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by wuxu92**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Scope, role_name, and principal_id define the role assignment while `name` is actually optional. So API responds a `409` conflict error when create a new role assignment with the same trio but different `name`. This PR is to update this logic when Create API responds 409:

1. List the existing role assignments to find the conflict resource.
2. if `name` was not given in configuration, return an import error to suggest use to import the existing role assignment id.
3. if `name` was specified in the configuration, then return an error to the user that another role assignment with id xxx already exists.

result example for scenario name not given:

```
azurerm_role_assignment.test2: Creating...
╷
│ Error: A resource with the ID "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleAssignments/626d93de-afd8-41bd-af46-2c195e7b320c" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_role_assignment" for more information.
│
│   with azurerm_role_assignment.test2,
│   on main.tf line 18, in resource "azurerm_role_assignment" "test2":
│   18: resource "azurerm_role_assignment" "test2" {

```
and while name `626d93de-afd8-41bd-af46-2c195e7b320c` if given:

```
azurerm_role_assignment.test2: Creating...
╷
│ Error: role Assignment with name: 626d93de-afd8-41bd-af46-2c195e7b320c already exists: /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleAssignments/626d93de-afd8-41bd-af46-2c195e7b320c
│
│   with azurerm_role_assignment.test2,
│   on main.tf line 18, in resource "azurerm_role_assignment" "test2":
│   18: resource "azurerm_role_assignment" "test2" {

```

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_role_assignment` - update logic for checking exists role assignment [GH-28557]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #28557

### CODE REVIEW

**Review by justinmchase — APPROVED** [review]
Thank you so much this will make a big difference for us!

**Review by justinmchase — APPROVED** [review]

**Comment by justinmchase** [comment]
Any chance we could get this reviewed and merged? This is a very coveted fix for us.

**Comment by cracautanu** [comment]
Any chance to get this merged soon? We need this fix, thank you!

**Comment by justinmchase** [comment]
Just keeping this fresh and checking in again.

**Comment by magodo** [comment]
@wuxu92 Please resolve the conflict and I'll take a look at this PR. Thanks!

**Comment by wuxu92** [comment]
rebased main branch and added a new acceptance test for it:

image

File: internal/services/authorization/role_assignment_resource.go [hunk 1]
```diff
@@ -381,6 +382,17 @@ func retryRoleAssignmentsClient(d *pluginsdk.ResourceData, id parse.ScopedRoleAs
 				return pluginsdk.RetryableError(err)
 			case retryLinkedAuthorizationFailedError && response.WasForbidden(resp.HttpResponse) && strings.Contains(err.Error(), "LinkedAuthorizationFailed"):
 				return pluginsdk.RetryableError(err)
+			case response.WasStatusCode(resp.HttpResponse, http.StatusConflict) && strings.Contains(err.Error(), "RoleAssignmentExists"):
```
Comment (magodo) [inline internal/services/authorization/role_assignment_resource.go:385]: Instead of checking here, shall we move it to L228 to do the existance check?

**Review by magodo — CHANGES_REQUESTED** [review]

File: internal/services/authorization/role_assignment_resource.go (hunk 1 above)
Comment (wuxu92) [reply internal/services/authorization/role_assignment_resource.go:385]: Considering that this is a low-probability corner case, I prefer placing it here rather than listing role assignments for every creation in L228.

Comment (magodo) [reply internal/services/authorization/role_assignment_resource.go:385]: After a reconsidering, if we are building two conflict role assignments, keeping the error handling here seems more reasonable, as otherwise there is a race condition and the latter assignment will still hit this conflict error, if we move the check to L228.

File: internal/services/authorization/role_assignment_resource.go [hunk 2]
```diff
@@ -381,6 +382,17 @@ func retryRoleAssignmentsClient(d *pluginsdk.ResourceData, id parse.ScopedRoleAs
...
+				// find the existing role assignment and output it in error message
+				// we omit the err in lookupRoleAssignment and return the origin Create error
+				if existing := lookupRoleAssignment(ctx, roleAssignmentsClient, id, param.Properties); existing != nil && existing.Properties != nil {
+					existsID := roleassignments.NewScopedRoleAssignmentID(pointer.From(existing.Properties.Scope), pointer.From(existing.Name))
+					if configName := d.Get("name").(string); configName != "" && configName != pointer.From(existing.Name) {
+						return pluginsdk.NonRetryableError(fmt.Errorf("role assignment `%s` already exists with a different name: %s", id.ID(), pointer.From(existing.Name)))
```
Comment (magodo) [inline internal/services/authorization/role_assignment_resource.go]: Shall we always return the `existsID.ID()` so that user can simply grab the id and import it if they wish?

Comment (wuxu92) [reply internal/services/authorization/role_assignment_resource.go]: That's my first version design to always return the ImportAsExistsError, but considering user may specify the role assignment name in config, tf will produce a force new plan after importing, then I changed it to a normal error. maybe I should change the error message to contain the existing id as well.

**Review by magodo — APPROVED** [review]
Thanks for the changes! It LGTM now 👍
