### PR TITLE
`azurerm_proximity_placement_group` - fix update when vm is attached

### LINKED ISSUE #20056: azurerm_proximity_placement_group resource cannot be modified due allowed_vm_sizes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

azurerm_proximity_placement_group

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

terraform {
  required_version = "~> 1.3.6"

  required_providers {
    azurerm = {
      # Azure Resource Manager
      source  = "hashicorp/azurerm"
      version = "~> 3.38"
    }
  }
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_proximity_placement_group" "example" {
  name                = "exampleProximityPlacementGroup"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  tags = {
    environment = "Production"
    #
    # Uncomment the following tag to produce the issue:
    # newtag = "value"
  }
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  proximity_placement_group_id = azurerm_proximity_placement_group.example.id

  admin_ssh_key {
    username   = "adminuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # azurerm_proximity_placement_group.example will be updated in-place
  ~ resource "azurerm_proximity_placement_group" "example" {
        id                  = "/subscriptions/.../resourceGroups/example-resources/providers/Microsoft.Compute/proximityPlacementGroups/exampleProximityPlacementGroup"
        name                = "exampleProximityPlacementGroup"
      ~ tags                = {
          + "newtag"      = "value"
            # (1 unchanged element hidden)
        }
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_proximity_placement_group.example: Modifying... [id=/subscriptions/.../resourceGroups/example-resources/providers/Microsoft.Compute/proximityPlacementGroups/exampleProximityPlacementGroup]
╷
│ Error: creating/updating Proximity Placement Group (Subscription: "..."
│ Resource Group Name: "example-resources"
│ Proximity Placement Group Name: "exampleProximityPlacementGroup"): proximityplacementgroups.ProximityPlacementGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Updating 'proximityPlacementGroup.properties.intent.vmSizes' property of proximity placement group is not allowed. Please deallocate all VMs and Virtual Machine Scale Set VMs that has reference of the proximity placement group and retry the request."
│
│   with azurerm_proximity_placement_group.example,
│   on main.tf line 22, in resource "azurerm_proximity_placement_group" "example":
│   22: resource "azurerm_proximity_placement_group" "example" {
│
╵
```

### Expected Behaviour

A new tag should be added to the placement proximity group resource without errors and `allowed_vm_sizes` should stay optional.

### Actual Behaviour

azurerm_proximity_placement_group resource cannot be changed (e.g. tags updated) after a VM has been attached to it.

Before the PPG has any VMs changing e.g. the tags works just fine.

Also defining `allowed_vm_sizes` based on the VMs in the PPG does not work, from actual deployment with existing PPG and multiple VMs failed with 
```
│ Error: expected allowed_vm_sizes.0 to be one of [Basic_A4 Basic_A1 Basic_A3 Basic_A2 Basic_A0 Standard_A8 Standard_A8_v2 Standard_A8m_v2 Standard_A5 Standard_A4 Standard_A4_v2 Standard_A4m_v2 Standard_A9 Standard_A1 Standard_A11 Standard_A1_v2 Standard_A10 Standard_A7 Standard_A6 Standard_A3 Standard_A2 Standard_A2_v2 Standard_A2m_v2 Standard_A0 Standard_B8ms Standard_B4ms Standard_B1ms Standard_B1s Standard_B2ms Standard_B2s Standard_D8_v3 Standard_D8s_v3 Standard_D5_v2 Standard_D4 Standard_D4_v3 Standard_D4_v2 Standard_D4s_v3 Standard_D1 Standard_D15_v2 Standard_D14 Standard_D14_v2 Standard_D11 Standard_D11_v2 Standard_D16_v3 Standard_D16s_v3 Standard_D13 Standard_D13_v2 Standard_D12 Standard_D12_v2 Standard_D1_v2 Standard_DS5_v2 Standard_DS4 Standard_DS4_v2 Standard_DS1 Standard_DS15_v2 Standard_DS14 Standard_DS14-8_v2 Standard_DS14-4_v2 Standard_DS14_v2 Standard_DS11 Standard_DS11_v2 Standard_DS13 Standard_DS13-4_v2 Standard_DS13-2_v2 Standard_DS13_v2 Standard_DS12 Standard_DS12_v2 Standard_DS1_v2 Standard_DS3 Standard_DS3_v2 Standard_DS2 Standard_DS2_v2 Standard_D64_v3 Standard_D64s_v3 Standard_D3 Standard_D32_v3 Standard_D32s_v3 Standard_D3_v2 Standard_D2 Standard_D2_v3 Standard_D2_v2 Standard_D2s_v3 Standard_E8_v3 Standard_E8s_v3 Standard_E4_v3 Standard_E4s_v3 Standard_E16_v3 Standard_E16s_v3 Standard_E64-16s_v3 Standard_E64-32s_v3 Standard_E64_v3 Standard_E64s_v3 Standard_E32-8s_v3 Standard_E32-16_v3 Standard_E32_v3 Standard_E32s_v3 Standard_E2_v3 Standard_E2s_v3 Standard_F8 Standard_F8s Standard_F8s_v2 Standard_F4 Standard_F4s Standard_F4s_v2 Standard_F1 Standard_F16 Standard_F16s Standard_F16s_v2 Standard_F1s Standard_F72s_v2 Standard_F64s_v2 Standard_F32s_v2 Standard_F2 Standard_F2s Standard_F2s_v2 Standard_G5 Standard_G4 Standard_G1 Standard_GS5 Standard_GS5-8 Standard_GS5-16 Standard_GS4 Standard_GS4-8 Standard_GS4-4 Standard_GS1 Standard_GS3 Standard_GS2 Standard_G3 Standard_G2 Standard_H8 Standard_H8m Standard_H16 Standard_H16m Standard_H16mr Standard_H16r Standard_L8s Standard_L4s Standard_L16s Standard_L32s Standard_M128-64ms Standard_M128-32ms Standard_M128ms Standard_M128s Standard_M64-16ms Standard_M64-32ms Standard_M64ms Standard_M64s Standard_NC12 Standard_NC12s_v3 Standard_NC12s_v2 Standard_NC6 Standard_NC6s_v3 Standard_NC6s_v2 Standard_NC24 Standard_NC24r Standard_NC24rs_v3 Standard_NC24rs_v2 Standard_NC24s_v3 Standard_NC24s_v2 Standard_ND12s Standard_ND6s Standard_ND24rs Standard_ND24s Standard_NV12 Standard_NV6 Standard_NV24], got Standard_E48ds_v5
```

Standard_E48ds_v5 is the machine type already in the PPG and the list doesn't contain all the available VM types (e.g. no _v5 types).

### Steps to Reproduce

1. terraform apply

The initial resources will be built (VM in PPG, VNet, etc).

2. Modify `main.tf` to include the a `newtag` tag for the Proximity Placement Group resource.

3. terraform apply

Will now fail with the above error.

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by myc2h6o**
Fix #20056
- Loosen the validation of `allowed_vm_sizes`, as VM sizes could be added ahead of Spec update, and it is validated at service side
- In update scenario, when updating `allowed_vm_sizes` to empty, only explicitly set it to empty when existing property value is not empty. When existing property value is empty, explicitly setting it to empty will cause failure when there is a VM attached to it.

### CODE REVIEW

**Comment by myc2h6o** [comment]
Test result
image

File: internal/services/compute/proximity_placement_group_resource.go [hunk 1]
```diff
@@ -57,7 +56,7 @@ func resourceProximityPlacementGroup() *pluginsdk.Resource {
 				MinItems: 1,
 				Elem: &pluginsdk.Schema{
 					Type:         pluginsdk.TypeString,
-					ValidateFunc: validation.StringInSlice(virtualmachines.PossibleValuesForVirtualMachineSizeTypes(), false),
+					ValidateFunc: validation.StringIsNotEmpty,
```
Comment (jackofallops) [inline internal/services/compute/proximity_placement_group_resource.go:59]: We can't really do this here, whilst it may be lagging behind the swagger updates, not validating the values invites a lot of other problems.  Is there a reason there's a lag between the swagger updates and the service updates?

Comment (myc2h6o) [reply internal/services/compute/proximity_placement_group_resource.go:59]: This string slice only populates value for [HardwareProfile.vmSize](https://github.com/Azure/azure-rest-api-specs/blob/d66735f5dc80731ee5c7a31399c2a46f8743153a/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-03-01/computeRPCommon.json#L437-L439) but not the full list of VM Sizes, thus some of the possible values are not contained there.

Comment (katbyte) [reply internal/services/compute/proximity_placement_group_resource.go:59]: does that not indicate that the swagger is incomplete and needs these missing values added?

Comment (myc2h6o) [reply internal/services/compute/proximity_placement_group_resource.go:59]: It seems like the service is [moving away from the static enum list](https://github.com/Azure/azure-rest-api-specs/blob/d66735f5dc80731ee5c7a31399c2a46f8743153a/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-03-01/computeRPCommon.json#L441), so the list is incomplete any more. It is said in the swagger that "*The enum data type is currently deprecated and will be removed by December 23rd 2023.*".

Comment (katbyte) [reply internal/services/compute/proximity_placement_group_resource.go:59]: ahh then that would explain why it is not maintained. there isn't much we can do about it then. thanks @myc2h6o

**Review by katbyte — APPROVED** [review]
Thanks @myc2h6o - LGTM once you fix conflicts 🦀

**Comment by myc2h6o** [comment]
Hi @katbyte thanks for reviewing! I've resolved the conflicts

**Comment by katbyte** [comment]
still have conflicts @myc2h6o

**Comment by myc2h6o** [comment]
@katbyte have resolved the second conflicts
