### PR TITLE
`azurerm_key_vault_certificate_contacts` - in v4.0 make the `contact` field optional to allow for deletion of contacts from the key vault. / `azurerm_key_vault` - deprecate the `contact` field from v3.x provider and update properties to `Computed` `Optional`.

### LINKED ISSUE #22301: azurerm_key_vault manages certificate contacts even if null specified; conflicts with azurerm_key_vault_certificate_contacts
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.62.1

### Affected Resource(s)/Data Source(s)

- `azurerm_key_vault`
- `azurerm_key_vault_certificate_contacts`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.62.1"
    }
  }
}
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy    = true
      recover_soft_deleted_key_vaults = true
    }
  }
}
data "azurerm_client_config" "current" {}
resource "azurerm_resource_group" "a" {
  location = "eastus"
  name     = "tf-azurerm-issue-22301"
}
resource "azurerm_key_vault" "a" {
  name                       = azurerm_resource_group.a.name
  location                   = azurerm_resource_group.a.location
  resource_group_name        = azurerm_resource_group.a.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days = 7
  purge_protection_enabled   = false
  sku_name                   = "standard"
  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id
    certificate_permissions = [
      "Backup",
      "Create",
      "Delete",
      "DeleteIssuers",
      "Get",
      "GetIssuers",
      "Import",
      "List",
      "ListIssuers",
      "ManageContacts",
      "ManageIssuers",
      "Purge",
      "Recover",
      "Restore",
      "SetIssuers",
      "Update"
    ]
  }
}
resource "azurerm_key_vault_certificate_contacts" "a" {
  key_vault_id = azurerm_key_vault.a.id
  contact {
    email = "user@domain.com"
  }
}
```

### Expected Behaviour

on first run

- key vault is created
- certificate contact is create

on every subsequent run

- terraform has nothing to do

### Actual Behaviour

on first run

- resources are created

alternating subsequent runs:

- `azurerm_key_vault.a` deletes the certificate contact even though it's not being managed here
- `azurerm_key_vault_certificate_contacts.a` sees that the contact is missing. adds it back

### Steps to Reproduce

1. `terraform apply -auto-approve`
2. run `#1` again

### PR DESCRIPTION
**Pull request by WodansSon**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

* `azurerm_key_vault` - deprecate the `contact` field from v3.x provider and update properties to `Computed` `Optional`.
* `azurerm_key_vault_certificate_contacts` - in v4.0 make the `contact` field optional to allow for deletion of contacts from the key vault.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_key_vault` - deprecate the `contact` field from v3.x provider and update properties to `Computed` `Optional`.
* `azurerm_key_vault_certificate_contacts` - in v4.0 make the `contact` field optional to allow for deletion of contacts from the key vault.

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #22301

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/keyvault/key_vault_resource.go [hunk 1]
```diff
@@ -232,12 +212,39 @@ func resourceKeyVault() *pluginsdk.Resource {
 			},
 		},
 	}
+
+	if !features.FourPointOhBeta() {
+		resource.Schema["contact"] = &pluginsdk.Schema{
+			Type:       pluginsdk.TypeSet,
+			Optional:   true,
+			Computed:   true,
+			Deprecated: "As the `contact` property requires reaching out to the dataplane to better support private endpoints and keyvaults with public network access disabled, `contact` will be removed in favour of the `azurerm_key_vault_certificate_contacts` resource in version 4.0 of the AzureRM Provider.",
```
Comment (katbyte) [inline internal/services/keyvault/key_vault_resource.go:221]:
```suggestion
			Deprecated: "As the `contact` property requires reaching out to the dataplane, to better support private endpoints and keyvaults with public network access disabled, `contact` will be removed in favour of the `azurerm_key_vault_certificate_contacts` resource in version 4.0 of the AzureRM Provider.",
```

**Review by katbyte — APPROVED** [review]
aside from one minor comment LGTM 🌋
