### PR TITLE
`azurerm_recovery_services_vault`: upgrade sdk version to `2024-01-01`

### LINKED ISSUE #25228: Need azurerm_recovery_services_vault api version updated to 2023-08-01 to use property standardTierStorageRedundancy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

N/A

### AzureRM Provider Version

2.99

### Affected Resource(s)/Data Source(s)

recovery service vault 

### Terraform Configuration Files

```hcl
azure-rest-api-specs/specification/recoveryservices/resource-manager/Microsoft.RecoveryServices/stable/2023-08-01 at main · Azure/azure-rest-api-specs (github.com)
```

### Debug Output/Panic Output

```shell
Policy not working as expected.
```

### Expected Behaviour

Recovery service vault soft delete enabled property should work with policy.

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ziyeqf**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

1. `azurerm_recovery_services_vault` - upgrade SDK version (API version) from `2022-10-01` to `2024-0101`
2. `cross_region_restore_enabled` and `storage_mode_type` requires a seprated client to set/update, but now it could be updated with the same client.
3. `encryption` used to requiring an additional update and cannot be set/update during creationg, but now it could.
## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)
image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_recovery_services_vault ` - upgrade sdk version to `2024-01-01` [GH-25325]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25228

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 1]
```diff
@@ -189,18 +188,12 @@ func resourceRecoveryServicesVault() *pluginsdk.Resource {
...
 	ctx, cancel := timeouts.ForCreate(meta.(*clients.Client).StopContext, d)
 	defer cancel()
 
 	id := vaults.NewVaultID(subscriptionId, d.Get("resource_group_name").(string), d.Get("name").(string))
-	storageId := backupresourcestorageconfigsnoncrr.VaultId{
-		SubscriptionId:    id.SubscriptionId,
-		ResourceGroupName: id.ResourceGroupName,
-		VaultName:         id.VaultName,
-	}
 	cfgId := backupresourcevaultconfigs.VaultId{
```
Comment (tombuildsstuff) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:197]: I realise this code was already present in the Provider, but can we fix this to use the `New` method?

```suggestion
	cfgId := backupresourcevaultconfigs.NewVaultID(
```

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 2]
```diff
@@ -245,13 +238,30 @@ func resourceRecoveryServicesVaultCreate(d *pluginsdk.ResourceData, meta interfa
 		Properties: &vaults.VaultProperties{
 			PublicNetworkAccess: expandRecoveryServicesVaultPublicNetworkAccess(d.Get("public_network_access_enabled").(bool)),
 			MonitoringSettings:  expandRecoveryServicesVaultMonitorSettings(d.Get("monitoring").([]interface{})),
+			RedundancySettings: &vaults.VaultPropertiesRedundancySettings{
+				CrossRegionRestore: pointer.To(func() vaults.CrossRegionRestore {
+					if d.Get("cross_region_restore_enabled").(bool) {
+						return vaults.CrossRegionRestoreEnabled
+					}
+					return vaults.CrossRegionRestoreDisabled
+				}()),
```
Comment (tombuildsstuff) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:247]: can we make this a variable above rather than a function

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 3]
```diff
@@ -286,72 +296,13 @@ func resourceRecoveryServicesVaultCreate(d *pluginsdk.ResourceData, meta interfa
 		return fmt.Errorf("creating %s: %+v", id.String(), err)
 	}
 
-	// `encryption` needs to be set before `cross_region_restore_enabled` is set. Or the service will return an error. "If CRR is enabled for the Vault, the storage state will be locked and it will interfere with further operations"
-	// recovery vault's encryption config cannot be set while creation, so a standalone update is required.
```
Comment (tombuildsstuff) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:290]: this seems like a pretty important behavioural change - has this codepath been tested?

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 4]
```diff
@@ -286,72 +296,13 @@ func resourceRecoveryServicesVaultCreate(d *pluginsdk.ResourceData, meta interfa
...
-			return pluginsdk.NonRetryableError(err)
-		}
-		return nil
-	})
-	if err != nil {
-		return fmt.Errorf("creating %s: %+v", id, err)
-	}
-
-	// storage type is not updated instantaneously, so we wait until storage type is correct
-	err = pluginsdk.Retry(d.Timeout(pluginsdk.TimeoutCreate), func() *pluginsdk.RetryError {
```
Comment (tombuildsstuff) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:331]: same here, this seems like a lot of retry related logic that's being removed, what's the logic here?

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 5]
```diff
@@ -484,58 +429,6 @@ func resourceRecoveryServicesVaultUpdate(d *pluginsdk.ResourceData, meta interfa
 		},
 	}
 
-	if d.HasChanges("storage_mode_type", "cross_region_restore_enabled") {
```
Comment (tombuildsstuff) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:487]: (same here)

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 6]
```diff
@@ -609,6 +502,18 @@ func resourceRecoveryServicesVaultUpdate(d *pluginsdk.ResourceData, meta interfa
...
 	}
 
+	if d.HasChanges("storage_mode_type", "cross_region_restore_enabled") {
+		vault.Properties.RedundancySettings = &vaults.VaultPropertiesRedundancySettings{
+			CrossRegionRestore: pointer.To(func() vaults.CrossRegionRestore {
+				if crossRegionRestore {
+					return vaults.CrossRegionRestoreEnabled
+				}
+				return vaults.CrossRegionRestoreDisabled
+			}()),
```
Comment (tombuildsstuff) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:512]: (same here) can we use variables for this

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 7]
```diff
@@ -673,11 +577,6 @@ func resourceRecoveryServicesVaultRead(d *pluginsdk.ResourceData, meta interface
 	if err != nil {
 		return err
 	}
-	storageId := backupresourcestorageconfigsnoncrr.VaultId{
-		SubscriptionId:    id.SubscriptionId,
-		ResourceGroupName: id.ResourceGroupName,
-		VaultName:         id.VaultName,
-	}
 	cfgId := backupresourcevaultconfigs.VaultId{
```
Comment (tombuildsstuff) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:580]: (as above)

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 8]
```diff
@@ -709,16 +608,27 @@ func resourceRecoveryServicesVaultRead(d *pluginsdk.ResourceData, meta interface
...
+		if prop.SecuritySettings != nil && prop.SecuritySettings.ImmutabilitySettings != nil {
+			d.Set("immutability", string(pointer.From(prop.SecuritySettings.ImmutabilitySettings.State)))
+		}
 
-	if model.Properties != nil && model.Properties.PublicNetworkAccess != nil {
-		d.Set("public_network_access_enabled", flattenRecoveryServicesVaultPublicNetworkAccess(model.Properties.PublicNetworkAccess))
-	}
+		if prop.PublicNetworkAccess != nil {
+			d.Set("public_network_access_enabled", flattenRecoveryServicesVaultPublicNetworkAccess(model.Properties.PublicNetworkAccess))
+		}
```
Comment (tombuildsstuff) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:618]: The Flatten function should handle this value being nil and set an appropriate default value (e.g. false) else this is going to be `null` meaning users won't be able to interpolate the value

File: internal/services/recoveryservices/recovery_services_vault_resource.go [hunk 9]
```diff
@@ -709,16 +608,27 @@ func resourceRecoveryServicesVaultRead(d *pluginsdk.ResourceData, meta interface
...
+
+		if prop.MonitoringSettings != nil {
+			d.Set("monitoring", flattenRecoveryServicesVaultMonitorSettings(*model.Properties.MonitoringSettings))
+		}
```
Comment (tombuildsstuff) [inline internal/services/recoveryservices/recovery_services_vault_resource.go:622]: The Flatten function should handle this value being nil and set an appropriate default value (e.g. false) else this is going to be `null` meaning users won't be able to interpolate the value

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
@ziyeqf looks like we've removed a _lot_ of retry related logic here but I can't see any explanation of why - what testing's been done to validate this polling logic is safe to remove?

File: internal/services/recoveryservices/recovery_services_vault_resource.go (hunk 3 above)
Comment (ziyeqf) [reply internal/services/recoveryservices/recovery_services_vault_resource.go:290]: In the past version, these settings should be set by a different API, it can not be set by the "Vaults" API itself. So it requires an additional update for it. But for this new API version it could be done by 1 API. And it has been tested with `TestAccRecoveryServicesVault_CrossRegionRestoreWithEncryption` test case

File: internal/services/recoveryservices/recovery_services_vault_resource.go (hunk 4 above)
Comment (ziyeqf) [reply internal/services/recoveryservices/recovery_services_vault_resource.go:331]: samilar to the `encryption`, the storage settings required a seprate client to set, but it can and must be set via the Vault API for now. It's tested by `TestAccRecoveryServicesVault_ToggleCrossRegionRestore` test case

File: internal/services/recoveryservices/recovery_services_vault_resource.go (hunk 5 above)
Comment (ziyeqf) [reply internal/services/recoveryservices/recovery_services_vault_resource.go:487]: the storage update is done by the `updateAndPoll()`, it does not need a seperate client.

**Comment by ziyeqf** [comment]
Have triggered a new test for the new commit. will append the test result here later

**Comment by rcskosir** [comment]
@ziyeqf :wave: Thank you for using our new PR template! Can you please include a brief description of what this PR does under the Description heading? This will help future users understand what changed in the code from this PR, thanks!

**Review by katbyte — APPROVED** [review]
LGTM 🚜
