### PR TITLE
`azurerm_[linux|windows]_function_app` and `azurerm_[linux|windows]_function_app_slot` - support Key Vault Secret for storage connection string

### LINKED ISSUE #15775: Overwriting app_settings in azurerm_windows_function_app leads to incorrect TF state
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: v1.1.6
* AzureRM Provider version: v2.98.0 with PR #15740 applied (dev overwrite)

### Terraform Configuration Files

As the configuration is rather lengthy, I've included it in a [github repo](https://github.com/fvdnabee/terraform-provider-azurerm-beta-funcapp-appsettings). The `azurerm_windows_function_app` resource is [here](https://github.com/fvdnabee/terraform-provider-azurerm-beta-funcapp-appsettings/blob/570fad98f4fe818941e539e2238ae567772c45d1/funcapp.tf). The configuration overwrites `azurerm_windows_function_app.app_settings` in order to use key vault references instead of the plain-text secrets (set by the azurerm provider) for the storage account connection strings, where necessary. The TF configuration should be easily reproducible, given that you apply PR #15470; otherwise the deduplication of the merged app settings does not work. 

### Description / Feedback

When you apply this configuration multiple times, the terraform state for the `azurerm_windows_function_app.funcapp` resource is never in sync with the resource on azure. Specifically, TF always tries to update the function app for `storage_account_access_key`,  `storage_account_name` and the overwritten app settings `AzureWebJobsDashboard` and `AzureWebJobsStorage` (see the TF plan output below). 

One issue is that the provider [expects `storage_account_access_key` to be provided in the form of a connection string](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/windows_function_app_resource.go#L367-L369), which clearly isn't the case for key vault references. For these specific lines of code, the app_settings overwrite is used succesfully. However, [`helpers.ParseWebJobsStorageString(v)`](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/windows_function_app_resource.go#L903-L904) suffers from the same assumption.

Another issue lies with `builtin_logging_enabled`. If set to true, the created resource always contains the connection string in plain-text regardless of the value for `app_settings.AzureWebJobsDashboard`. It must be set to false with the key vault reference supplied directly via `app_settings.AzureWebJobsDashboard`. However, when the provider gets the state from AzureRM, it decides that builtin_logging is in fact enabled (which it is) and that this does not match the terraform config and hence it always tries to update the resource.

<details>
  <summary>terraform plan -var 'resource_group_name=myRGP'</summary>
  
```
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/azurerm in /home/fvdnabee/go/bin
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
random_string.suffix: Refreshing state... [id=34rcu2ghf0b4]
azurerm_service_plan.funcapp: Refreshing state... [id=/subscriptions/xxx-yyy-zzz/resourceGroups/myRGP/providers/Microsoft.Web/serverfarms/plan-34rcu2ghf0b4]
azurerm_key_vault.funcapp: Refreshing state... [id=/subscriptions/xxx-yyy-zzz/resourceGroups/myRGP/providers/Microsoft.KeyVault/vaults/kv-34rcu2ghf0b4]
azurerm_user_assigned_identity.kv: Refreshing state... [id=/subscriptions/xxx-yyy-zzz/resourceGroups/myRGP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-34rcu2ghf0b4]
azurerm_storage_account.funcapp: Refreshing state... [id=/subscriptions/xxx-yyy-zzz/resourceGroups/myRGP/providers/Microsoft.Storage/storageAccounts/stfx34rcu2ghf0b4]
azurerm_key_vault_access_policy.owner: Refreshing state... [id=/subscriptions/xxx-yyy-zzz/resourceGroups/myRGP/providers/Microsoft.KeyVault/vaults/kv-34rcu2ghf0b4/objectId/9929ceb6-50fe-4667-8ffc-03f1b38e67a1]
azurerm_key_vault_access_policy.funcapp: Refreshing state... [id=/subscriptions/xxx-yyy-zzz/resourceGroups/myRGP/providers/Microsoft.KeyVault/vaults/kv-34rcu2ghf0b4/objectId/c96a8067-1dc2-4d3c-9840-cdc90c772fd4]
azurerm_key_vault_secret.azure_files_connection_string: Refreshing state... [id=https://kv-34rcu2ghf0b4.vault.azure.net/secrets/azure-files-connection-string/89c61374a916462580a7cb03dada37bb]
azurerm_windows_function_app.funcapp: Refreshing state... [id=/subscriptions/xxx-yyy-zzz/resourceGroups/myRGP/providers/Microsoft.Web/sites/func-34rcu2ghf0b4]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_windows_function_app.funcapp will be updated in-place
  ~ resource "azurerm_windows_function_app" "funcapp" {
      ~ app_settings                      = {
          + "AzureWebJobsDashboard"                    = "@Microsoft.KeyVault(SecretUri=https://kv-34rcu2ghf0b4.vault.azure.net/secrets/azure-files-connection-string/89c61374a916462580a7cb03dada37bb)"
          + "AzureWebJobsStorage"                      = "@Microsoft.KeyVault(SecretUri=https://kv-34rcu2ghf0b4.vault.azure.net/secrets/azure-files-connection-string/89c61374a916462580a7cb03dada37bb)"
            # (1 unchanged element hidden)
        }
      ~ builtin_logging_enabled           = true -> false
        id                                = "/subscriptions/xxx-yyy-zzz/resourceGroups/myRGP/providers/Microsoft.Web/sites/func-34rcu2ghf0b4"
        name                              = "func-34rcu2ghf0b4"
      ~ storage_account_access_key        = (sensitive value)
      ~ storage_account_name              = "" -> "stfx34rcu2ghf0b4"
        tags                              = {
            "terraform_test" = "true"
        }
        # (20 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```
</details>

I'm unsure whether the `azurerm_windows_function_app` resource overwriting its arguments (storage_account_access_key, builtin_logging_enabled) with the overwrites from its app_settings is a viable fix. It reeks of bad design to me.

A better approach could be to support KeyVault references directly in the `storage_account_access_key` argument and use the reference when setting all of the storage account app settings (AzureWebJobsStorage, AzureWebJobsDashboard, WEBSITE_CONTENTAZUREFILECONNECTIONSTRING + any others). This is clearly not intended with the current implementation of  `azurerm_windows_function_app`, which assumes it can retrieve the storage account name from the `AzureWebJobsStorage` app setting (or `AzureWebJobsStorage__accountName` in case of MSI). When using KeyVault references, I believe it's not possible to determine the storage account name without resolving the key vault reference.

### References
Issue relating to dedup of merged app settings is here #15733

### PR DESCRIPTION
**Pull request by jackofallops**
* `azurerm_linux_function_app` - add support for `storage_key_vault_secret_id`
* `azurerm_windows_function_app` - add support for `storage_key_vault_secret_id`
* `azurerm_linux_function_app_slot` - add support for `storage_key_vault_secret_id`
* `azurerm_windows_function_app_slot` - add support for `storage_key_vault_secret_id`

* Data Source: `azurerm_linux_function_app` - add support for `storage_key_vault_secret_id`
* Data Source: `azurerm_windows_function_app` - add support for `storage_key_vault_secret_id`

closes #15775

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🏗️

File: internal/services/appservice/linux_function_app_data_source.go [hunk 1]
```diff
@@ -28,8 +28,9 @@ type LinuxFunctionAppDataSourceModel struct {
 	ServicePlanId      string `tfschema:"service_plan_id"`
 	StorageAccountName string `tfschema:"storage_account_name"`
 
-	StorageAccountKey string `tfschema:"storage_account_access_key"`
-	StorageUsesMSI    bool   `tfschema:"storage_uses_managed_identity"` // Storage uses MSI not account key
+	StorageAccountKey       string `tfschema:"storage_account_access_key"`
+	StorageUsesMSI          bool   `tfschema:"storage_uses_managed_identity"` // Storage uses MSI not account key
+	StorageKeyVaultSecretID string `tfschema:"storage_key_vault_secret_id"`
```
Comment (fvdnabee) [inline internal/services/appservice/linux_function_app_data_source.go:33]: I would propose to rename this argument to `storage_key_vault_reference_string` in order to align with the MS docs on [Key Vault references](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#reference-syntax). Note users might want to use the alternative syntax which doesn't use the secret uri. Either way, the argument should be renamed (in all resources) to reflect that more than just the secret id is required.

File: internal/services/appservice/linux_function_app_resource.go [hunk 2]
```diff
@@ -126,11 +132,22 @@ func (r LinuxFunctionAppResource) Arguments() map[string]*pluginsdk.Schema {
...
+
+		"storage_key_vault_secret_id": {
+			Type:         pluginsdk.TypeString,
+			Optional:     true,
+			ValidateFunc: kvValidate.NestedItemId,
+			ExactlyOneOf: []string{
+				"storage_account_name",
+				"storage_key_vault_secret_id",
+			},
+			Description: "The Key Vault Secret ID, including version, that contains the Connection String to connect to the storage account for this Function App.",
```
Comment (fvdnabee) [inline internal/services/appservice/linux_function_app_resource.go:150]: If you decide to rename the argument, I'd propose to update the description along the lines of: `A Key Vault reference string pointing to a secret that contains the Connection String to connect to the storage account for this Function App.` If possible maybe link directly to the MS docs on the reference string.

File: website/docs/r/windows_function_app_slot.html.markdown [hunk 3]
```diff
@@ -103,9 +101,15 @@ The following arguments are supported:
...
 * `storage_account_access_key` - (Optional) The access key which will be used to access the storage account for the Function App Slot.
 
+* `storage_account_name` - (Optional) The backend storage account name which will be used by this Function App Slot.
+
 * `storage_uses_managed_identity` - (Optional) Should the Function App Slot use its Managed Identity to access storage.
 
-~> **NOTE:** One of `storage_account_access_key` or `storage_uses_managed_identity` must be specified.
+~> **NOTE:** One of `storage_account_access_key` or `storage_uses_managed_identity` must be specified when using `storage_account_name`.
+
+* `storage_key_vault_secret_id` - (Optional) The Key Vault Secret ID, including version, that contains the Connection String to connect to the storage account for this Function App Slot.
```
Comment (fvdnabee) [inline website/docs/r/windows_function_app_slot.html.markdown:110]: Same comment here about reference string:
`If you decide to rename the argument, I'd propose to update the description along the lines of: `A Key Vault reference string pointing to a secret that contains the Connection String to connect to the storage account for this Function App.` If possible maybe link directly to the MS docs on the reference string.`

**Review by fvdnabee — CHANGES_REQUESTED** [review]
Thank you very much @jackofallops. 

I would only propose to rename the `storage_key_vault_secret_id` and include a link to the MS docs on Key vault references.

File: internal/services/appservice/linux_function_app_data_source.go (hunk 1 above)
Comment (jackofallops) [reply internal/services/appservice/linux_function_app_data_source.go:33]: Hi @fvdnabee - Thanks for the suggestion. Since we refer to this in the provider as the [Secret ID](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret#id) on the resource we're referencing, within the context of Terraform and the provider the name here is appropriate and consistent.

Comment (fvdnabee) [reply internal/services/appservice/linux_function_app_data_source.go:33]: Even MS names it (i.e. the secretURI) the `secret id`, cfr. https://docs.microsoft.com/en-us/rest/api/keyvault/secrets/get-secret/get-secret#secretbundle. So yeah disregard my comment.

**Review by fvdnabee — APPROVED** [review]
