### PR TITLE
provider: log instead of error when RPs are unavailable when validating RP registrations

### LINKED ISSUE #21785: Terraform plan/apply fail for Azure China Cloud with: "Error ensuring Resource Providers are registered"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.56.0

### Affected Resource(s)/Data Source(s)

any

### Terraform Configuration Files

```hcl
resource "azurerm_storage_container" "services_container" {
  name                  = "services"
  storage_account_name  = "storage_account_name"
  container_access_type = "blob"

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/abreunig359/5cca0e749d0b60d9d55c80bdd4e62285
```

### Expected Behaviour

Both `terraform plan` and `terraform apply` should finish successfully for Azure China Cloud.

### Actual Behaviour

The output of `the required Resource Provider ... wasn't returned from the Azure API` varies, but it always fails with the same overall error:

```
╷
│ Error: Error ensuring Resource Providers are registered.
│
│ Terraform automatically attempts to register the Resource Providers it supports to
│ ensure it's able to provision resources.
│
│ If you don't have permission to register Resource Providers you may wish to use the
│ "skip_provider_registration" flag in the Provider block to disable this functionality.
│
│ Please note that if you opt out of Resource Provider Registration and Terraform tries
│ to provision a resource from a Resource Provider which is unregistered, then the errors
│ may appear misleading - for example:
│
│ > API version 2019-XX-XX was not found for Microsoft.Foo
│
│ Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
│ but this could also indicate that this Azure Region doesn't support this API version.
│
│ More information on the "skip_provider_registration" flag can be found here:
│ https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration
│
│ Original Error: determining which Required Resource Providers require registration: the required Resource Provider "Microsoft.AVS" wasn't returned from the Azure API
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 24, in provider "azurerm":
│   24: provider "azurerm" {
│
```

### Steps to Reproduce

1. terraform init -upgrade
2. terraform plan

### Important Factoids

_No response_

### References

There was a PR related to provider registration that has been released with azurerm 3.56.0
https://github.com/hashicorp/terraform-provider-azurerm/pull/21695

### PR DESCRIPTION
**Pull request by manicminer**
Resolves: #21785

### CODE REVIEW

File: internal/resourceproviders/requiring_registration.go [hunk 1]
```diff
@@ -20,8 +23,13 @@ func DetermineWhichRequiredResourceProvidersRequireRegistration(requiredResource
 		}
 
 		if _, isUnregistered := (*unregisteredResourceProviders)[providerName]; !isUnregistered {
-			// this is likely a typo in the Required Resource Providers list, so we should surface this
-			return nil, fmt.Errorf("the required Resource Provider %q wasn't returned from the Azure API", providerName)
+			if environment.Name == environments.AzurePublicCloud {
+				// this is likely a typo in the Required Resource Providers list, so we should surface this
+				return nil, fmt.Errorf("the required Resource Provider %q wasn't returned from the Azure API", providerName)
+			}
```
Comment (tombuildsstuff) [inline internal/resourceproviders/requiring_registration.go:29]: thinking about this we should probably remove this error here, and just log all the time - the unit test should fail but if an RP gets removed we shouldn't flag an error here?

**Comment by TZdybel** [comment]
Is there any way to push this PR further? We are currently blocked by the issue that this PR should solve.

**Review by mbfrahry — APPROVED** [review]
LGTM after addressing the review
