### PR TITLE
azurerm_cdn_frontdoor_origin.private_link: add web_secondary and Gateway to target_type accepted values

### LINKED ISSUE #23113: cdn_frontdoor_origin.private_link.target_type doesn't accept value web_secondary
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Resource azurerm_cdn_frontdoor_origin.private_link.target_type doesn't support web_secondary value as param for Storage Account Static Website secondary endpoint - for replication type RA_GRS or RA_GZRS in AccountKind: StorageV2.

Same configuration is possible via Azure Portal. Bellow is part of ARM template export from mentioned configuration.

azurerm provider: 3.71.0

terraform: 1.5.3

Error from terraform plan phase:

```
│ Error: expected private_link.0.target_type to be one of [blob blob_secondary sites web], got web_secondary
│
│   with azurerm_cdn_frontdoor_origin.storage_account_example_secondary,
│   on afd-storage-account-example.tf line 71, in resource "azurerm_cdn_frontdoor_origin" "storage_account_example_secondary":
│   71:     target_type = "web_secondary"
│
```

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_origin

### Potential Terraform Configuration

```hcl
resource "azurerm_cdn_frontdoor_origin" "storage_account_example_secondary" {
  name = "storage-account-example-secondary"

  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.example.id

  enabled = true

  host_name = var.storage_account_example.primary_web_host
  origin_host_header = var.storage_account_example.primary_web_host
  certificate_name_check_enabled = true

  http_port = 80
  https_port = 443
  priority = 2
  weight = 500

  private_link {
    request_message = "Request access for Private Link Origin CDN Frontdoor"
    target_type = "web_secondary"
    location = var.location
    private_link_target_id = var.storage_account_example.id
  }

}
```

### References

Copy from ARM template export:

```
{
            "type": "Microsoft.Cdn/profiles/origingroups/origins",
            "apiVersion": "2022-11-01-preview",
            "name": "storage-account-example-secondary')]",
            "properties": {
                "hostName": "example-secondary.z6.web.core.windows.net",
                "httpPort": 80,
                "httpsPort": 443,
                "originHostHeader": "example-secondary.z6.web.core.windows.net",
                "priority": 4,
                "weight": 500,
                "enabledState": "Enabled",
                "sharedPrivateLinkResource": {
                    "privateLink": {
                        "id": "resourceId_to_storage_account_example"
                    },
                    "groupId": "web_secondary",
                    "privateLinkLocation": "westeurope",
                    "requestMessage": "Request access for Private Link Origin CDN Frontdoor"
                },
                "enforceCertificateNameCheck": true
            }
},
```

### LINKED ISSUE #28115: Support for the Azure Frontdoor Premium azurerm_cdn_frontdoor_origin.private_link.target_type="managedEnvironments"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I request to support for the Azure Frontdoor Premium azurerm_cdn_frontdoor_origin.private_link.target_type="managedEnvironments". It is used to connect an Azure Container Apps environment.

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_origin

### Potential Terraform Configuration

_No response_

### References

https://learn.microsoft.com/en-us/azure/container-apps/how-to-integrate-with-azure-front-door#create-an-azure-front-door-origin

### PR DESCRIPTION
**Pull request by ycamargo**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
Support `web_secondary` and `Gateway` as a private link target types. These are used for connecting to Azure Storage Static Web Sites and Azure API Management, respectively.
Also, fixed the documentation to add the supported backend services related to the supported target types. Some of them were already supported on the target type list, but they were not listed as supported services, like Azure Storage (Static Web Sites) and Azure Container Apps (preview), for instance.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

Just a validation change, test not required

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_cdn_frontdoor_origin.private_link` - support for `web_secondary` and `Gateway` as values for the `target_type` property [#23113]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #23113 
Similar solution used to close #28115 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🐈

File: internal/services/cdn/cdn_frontdoor_origin_resource.go [hunk 1]
```diff
@@ -133,9 +133,11 @@ func resourceCdnFrontDoorOrigin() *pluginsdk.Resource {
 							ValidateFunc: validation.StringInSlice([]string{
 								"blob",
 								"blob_secondary",
+								"Gateway",
```
Comment (WodansSon) [inline internal/services/cdn/cdn_frontdoor_origin_resource.go:136]: I have one question, is this supposed to be `Gateway` or `gateway`?

**Review by WodansSon — CHANGES_REQUESTED** [review]
@ycamargo, thanks for opening this PR, it mostly LGTM, but I did have one question. If you can answer that and the tests pass we should be able to get this one in shortly. 🚀

File: internal/services/cdn/cdn_frontdoor_origin_resource.go (hunk 1 above)
Comment (WodansSon) [reply internal/services/cdn/cdn_frontdoor_origin_resource.go:136]: I have answered my own question, it's `Gateway` per the [documentation](https://learn.microsoft.com/azure/private-link/private-endpoint-dns). 🙂
