### PR TITLE
dependencies: update go-azure-sdk to v0.20250131.1134653

### LINKED ISSUE #17143: azurerm_api_connection import - Error unmarshalling json: cannot unmarshal bool into Go struct field ApiConnectionDefinitionProperties.properties.nonSecretParameterValues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_api_connection

### Terraform Configuration Files

```hcl
resource "azurerm_api_connection" "dsbismtpconnection" {
  name                = "smtp"
  resource_group_name = "example"
  display_name = "smtp"
}

terraform import azurerm_api_connection.dsbismtpconnection /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example/providers/Microsoft.Web/connections/smtp
```

### Debug Output/Panic Output

```shell
Error: retrieving Connection (Subscription: "00000000-0000-0000-0000-000000000000"
│ Resource Group Name: "example"
│ Connection Name: "smtp"): connections.ConnectionsClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal bool into Go struct field ApiConnectionDefinitionProperties.properties.nonSecretParameterValues of type string' JSON = '{"kind":"V1","properties":{"displayName":"smtp","authenticatedUser":{},"overallStatus":"Connected","statuses":[{"status":"Connected"}],"customParameterValues":{},"nonSecretParameterValues":{"enableSSL":true,"port":587,"serverAddress":"sampleaddress","userName":"sampleuser"},"createdTime":"2022-06-06T18:25:10.8848256Z","changedTime":"2022-06-07T12:58:42.4774783Z","api":{"name":"smtp","displayName":"SMTP","description":"SMTP (Simple Mail Transfer Protocol) is an internet standard for email supported by most email processing servers. Connect to SMTP to send email.","iconUri":"https://connectoricons-prod.azureedge.net/non_zr_connectors/1.0.1575.2789/smtp/icon.png","brandColor":"#e75300","category":"Standard","id":"/subscriptions/c00000000-0000-0000-0000-000000000000/providers/Microsoft.Web/locations/westus/managedApis/smtp","type":"Microsoft.Web/locations/managedApis"},"testLinks":[{"requestUri":"https://management.azure.com:443/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example/providers/Microsoft.Web/connections/smtp/extensions/proxy/TestConnection?api-version=2016-06-01","method":"get"}],"testRequests":[{"body":{"request":{"method":"get","path":"TestConnection"}},"requestUri":"https://management.azure.com:443/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example/providers/Microsoft.Web/connections/smtp/dynamicInvoke?api-version=2016-06-01","method":"POST"}]},"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example/providers/Microsoft.Web/connections/smtp","name":"smtp","type":"Microsoft.Web/connections","location":"westus"}'
```

### Expected Behaviour

It should be imported successfully without any error

### Actual Behaviour

Import failed with error
`Error: occurred unmarshalling JSON - Error = 'json: cannot unmarshal bool into Go struct field` 

### Steps to Reproduce

Create a logic app with smtp connector or simply api connections directly. 
then try to import it

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by magodo**
<!--  All Submissions -->


## Community Note
<!-- Please leave the community note as is. -->
* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review


## Description

<!-- Please include a description below with the reason for the PR, what it is doing, what it is trying to accomplish, and anything relevant for a reviewer to know. 

If this is a breaking change for users please detail how it cannot be avoided and why it should be made in a minor version of the provider -->

Update the go-azure-sdk to v0.20250131.1134653, with a couple of fixes below:

- Provider config: The `GtihubOIDCRequest(URL|Token)` fields in the sdk has been renamed to removing the `Github` prefix. Tested below.
- The API connection resource model has a type change on its `ParameterValues` field, causing a compile error. Tested below.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”


<!-- You can erase any parts of this template below this point that are not applicable to your Pull Request. -->


## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.


## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

<!-- Please include testing logs or evidence here or an explanation on why no testing evidence can be provided. 

For state migrations please test the changes locally and provide details here, such as the versions involved in testing the migration path. For further details on testing state migration changes please see our guide on [state migrations](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-state-migrations.md#testing) in the contributor documentation. -->

### Provider Github OIDC Test

```yml
name: terraform-azurerm-provider OIDC test
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout terraform-provider-azurerm repo'
        uses: actions/checkout@v4
        with:
          repository: 'magodo/terraform-provider-azurerm'
          ref: 'sdk_v0.20250131.1134653'
      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: 'Go Test'
        run: |
          export TF_ACC=1
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          go test -v -run="TestAccProvider_githubOidcAuth" ./internal/provider
```

![{4087E7DA-A98F-42DE-8F48-238000A39F8D}](https://github.com/user-attachments/assets/3796e070-e411-432a-9cb5-6ba5ef99fa9d)


### API Connection

```shell
terraform-provider-azurerm on  main via 🐹 v1.23.3
💤  TF_ACC=1 go test -v -timeout=20h -parallel=20 -run=TestAccApiConnection_complete ./internal/services/connections
=== RUN   TestAccApiConnection_complete
=== PAUSE TestAccApiConnection_complete
=== CONT  TestAccApiConnection_complete                                                                                                                                                                           --- PASS: TestAccApiConnection_complete (250.39s)                                                                                                                                                                 PASS                                                                                                                                                                                                              ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/connections   250.418s      
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

<!-- Replace the changelog example below with your entry. One resource per line. -->

* dependencies: update go-azure-sdk to v0.20250131.1134653 [GH-00000]


<!-- What type of PR is this? -->
This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change


## Related Issue(s)
Fixes #17143 


> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by jackofallops — APPROVED** [review]
Thanks @magodo - As discussed offline, I've pushed some changes to expose the new property for users. Can you check it's working as expected with your ADO setup and post any results you are able to before we merge?

Thanks

File: internal/provider/framework/config.go [hunk 1]
```diff
@@ -78,10 +78,13 @@ func (p *ProviderConfig) Load(ctx context.Context, data *ProviderModel, tfVersio
 	enableOIDC := getEnvBoolIfValueAbsent(data.UseOIDC, "ARM_USE_OIDC") || getEnvBoolIfValueAbsent(data.UseAKSWorkloadIdentity, "ARM_USE_AKS_WORKLOAD_IDENTITY")
 	auxTenants := getEnvListOfStringsIfAbsent(data.AuxiliaryTenantIds, "ARM_AUXILIARY_TENANT_IDS", ";")
 
+	adoPipelineServiceConnectionID := getEnvStringOrDefault(data.ADOPipelineServiceConnectionID, "ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID", "")
```
[the remark this answers is not in the document]
Comment (magodo) [reply internal/provider/framework/config.go]: I've made the change now.

File: internal/provider/framework/config.go [hunk 2]
```diff
@@ -78,10 +78,13 @@ func (p *ProviderConfig) Load(ctx context.Context, data *ProviderModel, tfVersio
...
+
 	oidcReqURL := getEnvStringOrDefault(data.OIDCRequestURL, "ARM_OIDC_REQUEST_URL", "")
```
[the remark this answers is not in the document]
Comment (magodo) [reply internal/provider/framework/config.go]: I've made the change now.

**Comment by magodo** [comment]
Hi @jackofallops, I've made some more commits to fix a couple of missing parts. Now it behaves correctly, see the tests below.

Note that all the tests below uses the tool [`terraform-client-import`](https://github.com/magodo/terraform-client-go/tree/main/cmd/terraform-client-import), which configures the provider, imports and reads a RG. The env vars are all passed through to the provider. This is easier to test the provider behavior than constructing a .tf file and run `terraform` (with setting up to use a local provider).

## Github Action

```yml
name: terraform-azurerm-provider OIDC test
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout terraform-provider-azurerm repo'
        uses: actions/checkout@v4
        with:
          repository: 'magodo/terraform-provider-azurerm'
          ref: 'sdk_v0.20250131.1134653'
      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: 'Unit Test'
        run: |
          export TF_ACC=1
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          go test -v -run="TestAccProvider_githubOidcAuth" ./internal/provider

      - name: 'E2E Test'
        run: |
          # Install provider
          go install 
          # Install terraform-client-import
          go install github.com/magodo/terraform-client-go/cmd/terraform-client-import@main

          # Import a RG
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          export ARM_PROVIDER_ENHANCED_VALIDATION=1
          export ARM_RESOURCE_PROVIDER_REGISTRATIONS=none
          export ARM_USE_OIDC=true
          ~/go/bin/terraform-client-import -type azurerm_resource_group -id /subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/zhwen-domain -path ~/go/bin/terraform-provider-azurerm
```

{32CD06CE-536F-436D-86EF-A8935EBDC88A}



## Azure Pipeline

```yml
trigger: 
 - none

pool:
   vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform-provider-azurerm
      type: github
      endpoint: magodo-pat-read-public-repo
      name: magodo/terraform-provider-azurerm
      ref: sdk_v0.20250131.1134653

steps: 
- task: GoTool@0
  inputs:
    version: '1.23.3'

- checkout: terraform-provider-azurerm

- task: AzureCLI@2
  inputs:
    azureSubscription: $(CONNECTION_ID)
    scriptType: bash
    scriptLocation: "inlineScript"
    inlineScript: |
      set -e

      # Unit Test
      go test -v -run="TestAccProvider_adoOidcAuth" ./internal/provider

      # E2E Test
      go install 
      go install github.com/magodo/terraform-client-go/cmd/terraform-client-import@main
      ~/go/bin/terraform-client-import -type azurerm_resource_group -id /subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/zhwen-domain -path ~/go/bin/terraform-provider-azurerm

  env:
    TF_ACC: 1
    ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(AZURE_TENANT_ID)
    ARM_CLIENT_ID: $(AZURE_CLIENT_ID) 
    ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID: $(CONNECTION_ID)
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    SYSTEM_OIDCREQUESTURI: $(System.OidcRequestUri)
    ARM_PROVIDER_ENHANCED_VALIDATION: 1
    ARM_RESOURCE_PROVIDER_REGISTRATIONS: none
    ARM_USE_OIDC: true
```

image



---

The remaining question is that are we fine with the current solution, especially for the auth method selection, based on whether the ADO service connection is specified or not, to choose between Github auth and ADO auth. This won't work if we need to support a 3rd platform with OIDC.

One possible solution is to convert the toggles of `use_oidc` and `use_aks_workload_identity` to be a single toggle `use_oidc`, plus an enum like property `oidc_method`, with enum values: `OIDCAssertionToken`, `GithubAction`, `ADOPipeline`, etc.

The root issue here is that the interface of `sdk/auth` is defined as an array of toggles, whilst in the implementation, only one will be picked up, which relies on the order and the existance of other config values. Do you think we shall consider changing the interface to be an enum in the sdk, then the provider do the evaluation about which enum value to use based on the user's config, which can hopefully keep the current behavior/schema unchanged.

Anyway, we can plan to do any of the above in another PR if needed. Whilst, I think we still need to update the provider document in this PR?

**Comment by jackofallops** [comment]
Thanks for the change @magodo - As discussed offline, I agree this PR should also update the `service_principal_oidc.html.markdown` documentation to cover the ADO properties, ideally with an example config. Once that's in, I'm happy to approve and merge this.

Thanks again!

**Comment by sreallymatt** [comment]
Fixes #17143

**Comment by magodo** [comment]
@jackofallops Thanks! I've updated both the *service_principal_oidc.html.markdown* and the *index.html.markdown*. Please take another look!

File: website/docs/guides/service_principal_oidc.html.markdown [hunk 3]
```diff
@@ -144,58 +144,47 @@ For more information about OIDC in GitHub Actions, see [official documentation](
...
+
+~> **Note:** `SYSTEM_ACCESSTOKEN` is not automatically defined by the Azure DevOps Pipelines, you'll need to source it from the pre-defined variable `System.AccessToken`.
+
+Besides, the provider will detect the ADO service connection ID via environment variable `ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID`. You can also specify the `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID`, which is compatible with the `terraform-provider-azapi`.
+
+~> **Note:** Whether the `ado_pipeline_service_connection_id` is specified or not, impacts the provider to build the authorizer as a Github OIDC authorizer (unspecified) or ADO Pipelines authorizer (specified).
+
+For Azure DevOps Pipelines, you'll need to ensure there is at least one task in the pipeline has the Service Connection support and has your service connection specified. Otherwise, the agent won't load your Service Connection and ends up with an error: `No service connection found with identifier "..."`.
+
+Recommend to use the `AzureCLI@2` task as below (note the `azureSubscription` input parameter):
```
Comment (jackofallops) [inline website/docs/guides/service_principal_oidc.html.markdown:157]: The AzureRM provider standardised on `ARM_` prefixed env vars, can we ensure that we're leading with those, and indicating we will also try to fall back on the `SYSTEM_`?

```suggestion
When running Terraform in Azure DevOps Pipelines, the provider use `ARM_OIDC_REQUEST_TOKEN` and `ARM_OIDC_REQUEST_URL` environment variables, if these are absent, it will attempt to fall back on `SYSTEM_ACCESSTOKEN` and `SYSTEM_OIDCREQUESTURI` environment variables respectively.

The ADO service connection ID is required in combination with these and can be specified via environment variable `ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID`, or in the provider configuration directly via `ado_pipeline_service_connection_id`. For users of the AzAPI provider AzureRM will also fall back on `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID` for compatibility.

~> **Note:** If the `ado_pipeline_service_connection_id` value is not set, either directly via config or by environment variable, the presence of the remaining OIDC configuration will result in the provider falling back on the GitHub OIDC authoriser instead.

For Azure DevOps Pipelines, at least one task in the pipeline has Service Connection support and has your service connection specified. Without this, the agent will fail to load the Service Connection and results in a `No service connection found with identifier "..."`  error.

It is recommend to use the `AzureCLI@2` task as below (note the `azureSubscription` input parameter):
```

File: website/docs/index.html.markdown [hunk 4]
```diff
@@ -143,9 +143,11 @@ More information on [how to configure a Service Principal using a Client Secret
 
 When authenticating as a Service Principal using Open ID Connect, the following fields can be set:
 
-* `oidc_request_token` - (Optional) The bearer token for the request to the OIDC provider. This can also be sourced from the `ARM_OIDC_REQUEST_TOKEN` or `ACTIONS_ID_TOKEN_REQUEST_TOKEN` Environment Variables.
+* `oidc_request_token` - (Optional) The bearer token for the request to the OIDC provider. This can also be sourced from the `ARM_OIDC_REQUEST_TOKEN`, `ACTIONS_ID_TOKEN_REQUEST_TOKEN` or `SYSTEM_ACCESSTOKEN` Environment Variables.
```
Comment (jackofallops) [inline website/docs/index.html.markdown:146]: Is it worth noting here that these are in priority order?
```suggestion
* `oidc_request_token` - (Optional) The bearer token for the request to the OIDC provider. This can also be sourced from the `ARM_OIDC_REQUEST_TOKEN`, `ACTIONS_ID_TOKEN_REQUEST_TOKEN` or `SYSTEM_ACCESSTOKEN` Environment Variables. The provider will look for values in this order and use the first it finds configured.
```

File: website/docs/index.html.markdown [hunk 5]
```diff
@@ -143,9 +143,11 @@ More information on [how to configure a Service Principal using a Client Secret
...
 
-* `oidc_request_url` - (Optional) The URL for the OIDC provider from which to request an ID token. This can also be sourced from the `ARM_OIDC_REQUEST_URL` or `ACTIONS_ID_TOKEN_REQUEST_URL` Environment Variables.
+* `oidc_request_url` - (Optional) The URL for the OIDC provider from which to request an ID token. This can also be sourced from the `ARM_OIDC_REQUEST_URL`, `ACTIONS_ID_TOKEN_REQUEST_URL` or `SYSTEM_OIDCREQUESTURI` Environment Variables.
```
Comment (jackofallops) [inline website/docs/index.html.markdown:148]: same here?
```suggestion
* `oidc_request_url` - (Optional) The URL for the OIDC provider from which to request an ID token. This can also be sourced from the `ARM_OIDC_REQUEST_URL`, `ACTIONS_ID_TOKEN_REQUEST_URL` or `SYSTEM_OIDCREQUESTURI` Environment Variables. The provider will look for values in this order and use the first it finds configured.
```

File: website/docs/index.html.markdown [hunk 6]
```diff
@@ -143,9 +143,11 @@ More information on [how to configure a Service Principal using a Client Secret
...
+
+* `ado_pipeline_service_connection_id` - (Optional) The Azure DevOps Pipeline Service Connection ID. This can also be sourced from the `ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID` or `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID` Environment Variables.
```
Comment (jackofallops) [inline website/docs/index.html.markdown:150]: and here
```suggestion
* `ado_pipeline_service_connection_id` - (Optional) The Azure DevOps Pipeline Service Connection ID. This can also be sourced from the `ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID` or `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID` Environment Variables. The provider will look for values in this order and use the first it finds configured.
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Thanks @magodo - I've made some wording change suggestions below if you can take a look? As soon as they're addressed I'll get this approved and merged.

Thanks!

**Review by jackofallops — APPROVED** [review]
Thanks @magodo - this LGTM now 👍
