### PR TITLE
`r\site_recovery_replicated_vm`: Add support for `target_disk_encryption`

### LINKED ISSUE #7239: Support for encrypted disks with azurerm_site_recovery_replicated_vm
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently I am able to use azurerm_site_recovery_replicated_vm as long as I do not have the VM Disk Encryption extension enabled (AzureDiskEncryption).

```hcl
resource "azurerm_key_vault" "shared" {
  name                = "${var.prefix}-kv-pri-shared"
  resource_group_name = azurerm_resource_group.kv.name
  location            = azurerm_resource_group.kv.location

  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name                    = var.key_vault_sku

  network_acls {
    default_action = "Deny"
    ip_rules       = var.key_vault_ip_cidr
    bypass         = "AzureServices"
  }
}

resource "azurerm_virtual_machine_extension" "mgmt-encrypt" {
  name  = "AzureDiskEncryption"

  virtual_machine_id         = azurerm_windows_virtual_machine.mgmt.id
  publisher                  = "Microsoft.Azure.Security"
  type                       = "AzureDiskEncryption"
  type_handler_version       = "2.2"
  auto_upgrade_minor_version = true

  settings = <<SETTINGS
{
    "EncryptionOperation": "EnableEncryption",
    "KeyVaultURL": "${azurerm_key_vault.shared.vault_uri}",
    "KeyVaultResourceId": "${azurerm_key_vault.shared.id}",
    "VolumeType": "OS"
}
             SETTINGS
}
```

If I enable disk encryption, the the terraform apply fails:

```
Error: Error creating replicated vm mgmt-vm-replication (vault nardl-recovery-vault-shared): Code="150175" Message="Virtual machine's OS disk is encrypted and there is no disk information found."
2020-06-06T03:39:17.2678042Z 
2020-06-06T03:39:17.2678389Z   on 06-recoveryvault.tf line 105, in resource "azurerm_site_recovery_replicated_vm" "mgmt-vm-replication":
2020-06-06T03:39:17.2678899Z  105: resource "azurerm_site_recovery_replicated_vm" "mgmt-vm-replication" {
2020-06-06T03:39:17.2679119Z 
```

If I apply the replication for the VM from the Azure Portal, it asks for the Disk encryption key vault source and target, which doesn't appear to be an option on the current azurerm_site_recovery_replicated_vm resource interraform.

Digging in further, if I export an ARM template before enabling the site replication, I see the following in the replicationProtectedItems section.

```json
"type": "microsoft.recoveryservices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectedItems",
            "apiVersion": "2018-07-10",
            "name": "",
            "properties": {
                "policyId": "",
                "protectableItemId": "",
                "providerSpecificDetails": {
                    "instanceType": "A2A",
                    "fabricObjectId": "",
                    "recoveryResourceGroupId": "",
                    "recoveryContainerId": "",
                    "vmDisks": [],
                    "vmManagedDisks": [
                        {
                            "diskId": "",
                            "primaryStagingAzureStorageAccountId": "",
                            "recoveryResourceGroupId": "",
                            "recoveryReplicaDiskAccountType": "",
                            "recoveryTargetDiskAccountType": "",
                            "diskEncryptionInfo": {
                                "diskEncryptionKeyInfo": {
                                    "secretIdentifier": "",
                                    "keyVaultResourceArmId": ""
                                },
                                "keyEncryptionKeyInfo": {
                                    "keyIdentifier": "",
                                    "keyVaultResourceArmId": ""
                                }
                            }
                        }
                    ],
                    "multiVmGroupName": "",
                    "recoveryAzureNetworkId": ""
                }
            }
```

Namely the section for diskEncryptionInfo under vmManagedDisks. It takes the target key vault and target encryption secret as arguments (I believe in a previous step it copies the secret from the source key vault to the target).

### New or Affected Resource(s)

* azurerm_site_recovery_replicated_vm

### Potential Terraform Configuration

Suggest adding a target_key_vault_id to the managed_disk block:

```hcl
resource "azurerm_site_recovery_replicated_vm" "vm-replication" {
  name                = "mgmt-vm-replication"
  resource_group_name = azurerm_resource_group.shared.name

  recovery_vault_name                       = azurerm_recovery_services_vault.vault.name
  source_recovery_fabric_name               = azurerm_site_recovery_fabric.primary.name
  source_vm_id                              = azurerm_windows_virtual_machine.mgmt.id
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.policy.id
  source_recovery_protection_container_name = azurerm_site_recovery_protection_container.primary.name

  target_resource_group_id                = azurerm_resource_group.shared.id
  target_recovery_fabric_id               = azurerm_site_recovery_fabric.secondary.id
  target_recovery_protection_container_id = azurerm_site_recovery_protection_container.secondary.id

  managed_disk {
    disk_id                    = "/subscriptions/${var.subscription_id}/resourcegroups/${azurerm_resource_group.shared.name}/providers/microsoft.compute/disks/${azurerm_windows_virtual_machine.mgmt.os_disk.0.name}"
    staging_storage_account_id = azurerm_storage_account.recoverycache-pri.id
    target_resource_group_id   = azurerm_resource_group.shared.id
    target_disk_type           = "Premium_LRS"
    target_replica_disk_type   = "Premium_LRS"
    target_key_vault_id       = azurerm_key_vault.shared.id
  }
}
```

On a side note, there doesn't seem to be a way to access the managed_disk on the azurerm_windows_virtual_machine like we could previously on azurerm_virtual_machine. On azurerm_virtual_machine the following worked:

azurerm_virtual_machine.mgmt.storage_os_disk.0.managed_disk_id

However, on the new azurerm_windows_virtual_machine I don't see a way to get the disk ID, only the name. That is why in the configuration snippet above, I have a long ID parsed together from pieces.

### PR DESCRIPTION
**Pull request by myc2h6o**
Fix #7239
- Doc link: https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-how-to-enable-replication-ade-vms
- acc test uses `target_zone` field to ease the key vault secret migration (without it, test needs to decrypt and create an encrypted secret in a new region), need to wait for #15617

### CODE REVIEW

File: internal/services/recoveryservices/site_recovery_replicated_vm_resource.go [hunk 1]
```diff
@@ -175,6 +176,60 @@ func resourceSiteRecoveryReplicatedVM() *pluginsdk.Resource {
 							ValidateFunc:     azure.ValidateResourceID,
 							DiffSuppressFunc: suppress.CaseDifference,
 						},
+
+						"target_disk_encryption_info": {
```
Comment (katbyte) [inline internal/services/recoveryservices/site_recovery_replicated_vm_resource.go:180]: info is redundant and doesn't add anything to ux here, so we should remove it
```suggestion
						"target_disk_encryption": {
```

Comment (myc2h6o) [reply internal/services/recoveryservices/site_recovery_replicated_vm_resource.go]: _info removed

**Comment by myc2h6o** [comment]
Hi @katbyte thanks for reviewing the change. I've removed the "_info" as suggested, please take a look.

**Comment by devsheoran** [comment]
@katbyte @myc2h6o - Thanks to you both for your contribution on this functionality. Could you please expedite PR review and complete it? We are waiting for this functionality to be available.

File: internal/services/recoveryservices/site_recovery_replicated_vm_resource_test.go [hunk 2]
```diff
@@ -45,6 +45,21 @@ func TestAccSiteRecoveryReplicatedVm_des(t *testing.T) {
...
+
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.targetDiskEncryption(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+			),
+		},
+		data.ImportStep(),
+	})
```
Comment (stephybun) [inline internal/services/recoveryservices/site_recovery_replicated_vm_resource_test.go:60]: Since it looks like it's possible to update the `disk_encryption_key` and `key_encryption_key` it would make sense to add an update step to this test as well?

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @myc2h6o, unfortunately the test is failing
```
------- Stdout: -------
=== RUN   TestAccSiteRecoveryReplicatedVm_targetDiskEncryption
=== PAUSE TestAccSiteRecoveryReplicatedVm_targetDiskEncryption
=== CONT  TestAccSiteRecoveryReplicatedVm_targetDiskEncryption
testcase.go:110: Step 1/2 error: Error running pre-apply refresh: exit status 1
Error: expected key_permissions.0 to be one of [Backup Create Decrypt Delete Encrypt Get Import List Purge Recover Restore Sign UnwrapKey Update Verify WrapKey], got create
with azurerm_key_vault_access_policy.service-principal,
on terraform_plugin_test.tf line 37, in resource "azurerm_key_vault_access_policy" "service-principal":
37:     "create",
Error: expected key_permissions.1 to be one of [Backup Create Decrypt Delete Encrypt Get Import List Purge Recover Restore Sign UnwrapKey Update Verify WrapKey], got delete
with azurerm_key_vault_access_policy.service-principal,
on terraform_plugin_test.tf line 38, in resource "azurerm_key_vault_access_policy" "service-principal":
38:     "delete",
Error: expected key_permissions.2 to be one of [Backup Create Decrypt Delete Encrypt Get Import List Purge Recover Restore Sign UnwrapKey Update Verify WrapKey], got get
with azurerm_key_vault_access_policy.service-principal,
on terraform_plugin_test.tf line 39, in resource "azurerm_key_vault_access_policy" "service-principal":
39:     "get",
Error: expected key_permissions.3 to be one of [Backup Create Decrypt Delete Encrypt Get Import List Purge Recover Restore Sign UnwrapKey Update Verify WrapKey], got update
with azurerm_key_vault_access_policy.service-principal,
on terraform_plugin_test.tf line 40, in resource "azurerm_key_vault_access_policy" "service-principal":
40:     "update",
Error: expected secret_permissions.0 to be one of [Backup Delete Get List Purge Recover Restore Set], got get
with azurerm_key_vault_access_policy.service-principal,
on terraform_plugin_test.tf line 44, in resource "azurerm_key_vault_access_policy" "service-principal":
44:     "get",
Error: expected secret_permissions.1 to be one of [Backup Delete Get List Purge Recover Restore Set], got delete
with azurerm_key_vault_access_policy.service-principal,
on terraform_plugin_test.tf line 45, in resource "azurerm_key_vault_access_policy" "service-principal":
45:     "delete",
Error: expected secret_permissions.2 to be one of [Backup Delete Get List Purge Recover Restore Set], got set
with azurerm_key_vault_access_policy.service-principal,
on terraform_plugin_test.tf line 46, in resource "azurerm_key_vault_access_policy" "service-principal":
46:     "set",
--- FAIL: TestAccSiteRecoveryReplicatedVm_targetDiskEncryption (3.53s)
FAIL
```

File: internal/services/recoveryservices/site_recovery_replicated_vm_resource_test.go (hunk 2 above)
Comment (myc2h6o) [reply internal/services/recoveryservices/site_recovery_replicated_vm_resource_test.go:60]: Hi @stephybun thanks for pointing out the issue, I've fixed the case issue related to the key vault permission, and actually this new test is waiting for `target_zone` property to be added by #15617 first.

For the update step, these properties are nested in `managed_disk` which is ForceNew, so it will not trigger the update

**Comment by stephybun** [comment]
The test is still failing
```
------- Stdout: -------
=== RUN   TestAccSiteRecoveryReplicatedVm_targetDiskEncryption
=== PAUSE TestAccSiteRecoveryReplicatedVm_targetDiskEncryption
=== CONT  TestAccSiteRecoveryReplicatedVm_targetDiskEncryption
testcase.go:110: Step 1/2 error: Error running pre-apply refresh: exit status 1
Error: Unsupported argument
on terraform_plugin_test.tf line 224, in resource "azurerm_site_recovery_replicated_vm" "test":
224:   target_zone                               = "2"
An argument named "target_zone" is not expected here.
--- FAIL: TestAccSiteRecoveryReplicatedVm_targetDiskEncryption (3.22s)
FAIL
```

**Comment by myc2h6o** [comment]
`target_zone` has been added by #15617 which unblocks the test case in this change. There is one more issue in the test case of dangling temp disk which is taken care of by #16596, after it's merged the test should be good to go

**Comment by myc2h6o** [comment]
@katbyte @stephybun the acc test of this `site_recovery_replicated_vm` are all failing due to the dangling temp disk issue, which could be fixed by #16596. could you take a look at these two?

**Review by katbyte — APPROVED** [review]
LGTM 🦕 \
