### PR TITLE
Bug Fix of azurerm_virtual_machine.storage_os_disk.image_uri

### LINKED ISSUE #838: Terraform is not keeping azurerm_virtual_machine.storage_os_disk.image_uri properly
### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.1.1

### Affected Resource(s)
- azurerm_virtual_machine

### Terraform Configuration Files
```hcl
provider "azurerm" {
  version = ">= 1.1.1"
  subscription_id = "x"
  client_id       = "x"
  client_secret   = "x"
  tenant_id       = "x"
}

resource "azurerm_resource_group" "test_rg" {
  name     = "test-rg"
  location = "Brazil South"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet-test"
  location            = "Brazil South"
  address_space       = ["10.1.0.0/16"]
  resource_group_name = "${azurerm_resource_group.test_rg.name}"
}

resource "azurerm_subnet" "subnet" {
  name                 = "subnet-test"
  resource_group_name  = "test-rg"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  address_prefix       = "10.1.1.0/24"
}

resource "azurerm_network_interface" "test_ni" {
  name                      = "test-ni"
  location                  = "Brazil South"
  resource_group_name       = "${azurerm_resource_group.test_rg.name}"
  ip_configuration {
    name                          = "test-config"
    private_ip_address_allocation = "dynamic"
    subnet_id                     = "${azurerm_subnet.subnet.id}"    
  }
}

resource "azurerm_virtual_machine" "teste_instance" {
  name                             = "test-virtual-machine"
  location                         = "Brazil South"
  resource_group_name              = "${azurerm_resource_group.test_rg.name}"
  network_interface_ids            = ["${azurerm_network_interface.test_ni.id}"]
  vm_size                          = "Standard_DS2_V2"
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = false

  os_profile {
    computer_name  = "teste-computer"
    admin_username = "testUser"
    admin_password = "Test1234@Abcd"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }

  storage_os_disk {
    name          = "test-local-disk"
    image_uri     = "https://xxxxxxxx.blob.core.windows.net/system/Microsoft.Compute/Images/images/test.vhd"
    vhd_uri       = "https://xxxxxxxx.blob.core.windows.net/vhds/test.vhd"
    create_option = "FromImage"
    os_type       = "Linux"
  }
}
```
### Expected Behavior
When you execute ```terraform apply``` terraform previews correctly the storage_os_disk.0.image_uri state: 
```
storage_os_disk.0.image_uri:  "https://xxxx.blob.core.windows.net/system/Microsoft.Compute/Images/images/xxxx.vhd"
```
Then you confirm with ```yes``` and all the resources are properly created.
When you execute ```terraform show``` storage_os_disk.0.image_uri should be listed with the desired state. 

### Actual Behavior
When you execute ```terraform show``` storage_os_disk.0.image_uri is empty:
```
storage_os_disk.0.image_uri =
```
This implies that future executions of ```terraform apply``` will try to update the state, even we don't have anything to update.

### Steps to Reproduce
Create a terraform file as the example above
1. `terraform apply`
2. `terraform show`

### PR DESCRIPTION
**Pull request by JunyiYi**
This PR fixes #838 . Without the fix, the test case will complain that `plan is not empty after apply`.

### CODE REVIEW

File: azurerm/resource_arm_virtual_machine_unmanaged_disks_test.go [hunk 1]
```diff
@@ -102,6 +102,28 @@ func TestAccAzureRMVirtualMachine_basicLinuxMachine_disappears(t *testing.T) {
...
+		Providers:    testAccProviders,
+		CheckDestroy: testCheckAzureRMVirtualMachineDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: config,
+				Check: resource.ComposeTestCheckFunc(
+					testCheckAzureRMVirtualMachineExists("azurerm_virtual_machine.test", &vm),
+					testCheckAzureRMVirtualMachineExists("azurerm_virtual_machine.mirror", &mirrorVm),
+					testCheckAzureRMVirtualMachineVHDExistence("myosdisk1.vhd", true),
+					testCheckAzureRMVirtualMachineVHDExistence("mirrorosdisk.vhd", true),
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_virtual_machine_unmanaged_disks_test.go]: we can also check the `image_uri` field is set correctly in the state here by using:

```
resource.TestCheckResourceAttrSet("azurerm_virtual_machine.mirror", "storage_os_disk.0.image_uri")
```

**Review by tombuildsstuff — APPROVED** [review]
One thing to fix but this otherwise LGTM 👍

**Comment by jeffreyCline** [comment]
image

**Review by WodansSon — APPROVED** [review]
Hi @JunyiYi I have finished looking over the code and ran the test case. This LGTM!

File: azurerm/resource_arm_virtual_machine_unmanaged_disks_test.go (hunk 1 above)
Comment (jeffreyCline) [reply azurerm/resource_arm_virtual_machine_unmanaged_disks_test.go]: I mentioned this same thing to him last night and I believe he has a commit with the `image_uri` check in it ready to push.

**Comment by jeffreyCline** [comment]
Re-ran the one test that fail:
image
