### PR TITLE
Remove incorrect validation of app service sticky setting names

### LINKED ISSUE #16612: azurerm_windows_web_app sticky_settings app_setting_names doesnt allow valid characters
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.4.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app and possibly everything with sticky_settings property mentioned here: https://github.com/hashicorp/terraform-provider-azurerm/pull/16546

### Terraform Configuration Files

```hcl
resource "azurerm_windows_web_app" "app_service" {
  name                = var.service_name
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name
  service_plan_id     = var.app_service_plan_id

  site_config {
    always_on         = local.site_config.always_on
    ...
  }

  app_settings = {
    "ConfigManager:Location" = var.config_manager.location
    ...
  }

  sticky_settings {
    app_setting_names = ["ConfigManager:Location"] //the colon is not allowed by the azurerm provider even though we have had this setting in Azure for years
    ...
  }
}
```

### Debug Output/Panic Output

```shell
Error: "sticky_settings.0.app_setting_names.0" may only contain alphanumeric characters, periods and underscores
```

### Expected Behaviour

The azurerm provider allows all characters allowed in the Azure App Settings. I.e. it allows to implement the suggested hierarchical namespaces via colons, or slashes as well as use other common practices described here: https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value

### Actual Behaviour

The azurerm provider does not allow us to use the common key naming practices, which prevents us from upgrading from azurerm_app_service resource to the azurerm_windows_web_app

### Steps to Reproduce

Try to add any setting that is allowed in the Azure App Service -> Configuration -> Application Settings that contains characters other than the characters allowed by the current provider. Other than my example with colon, you can try adding a Key Vault Reference, which has a syntax: `@Microsoft.KeyVault({referenceString})`. More on that: https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jennings**
This validation is too strict. The Azure Portal allows the following name for both app settings and connection strings:

    A test: !@#$%^&*()_+-=' ";/?

I can't find a reference for what the valid character set would be, and the names in the app_settings attribute aren't validated at all, so we may as well remove this validation.

Fixes #16612

image

### CODE REVIEW

**Comment by jennings** [comment]
@jackofallops I would love to get this into an upcoming release because it's blocking my use of `sticky_settings` entirely. Is there any research I can to do make this easier to review? Or, let me know if I should change something and I can work on it.

File: internal/services/appservice/helpers/shared_schema.go [hunk 1]
```diff
@@ -1554,7 +1553,6 @@ func StickySettingsSchema() *pluginsdk.Schema {
 					Optional: true,
 					Elem: &pluginsdk.Schema{
 						Type:         pluginsdk.TypeString,
-						ValidateFunc: appserviceValidate.AppSettingName,
```
Comment (jackofallops) [inline internal/services/appservice/helpers/shared_schema.go:1557]: Unfortunately, we can't remove validation entirely, since an empty name is invalid, so we'd need to at least use:
```
							ValidateFunc: validation.StringIsNotEmpty,
```

File: internal/services/appservice/helpers/shared_schema.go [hunk 2]
```diff
@@ -1568,7 +1566,6 @@ func StickySettingsSchema() *pluginsdk.Schema {
...
```
Comment (jackofallops) [inline internal/services/appservice/helpers/shared_schema.go:1571]: as above.

**Review by jackofallops — CHANGES_REQUESTED** [review]
HI @jennings - Apologies for the delay in review, I've been away for a few days. 

Thanks for the catch here, the information I developed this against suggested this was the correct validation, but I should have remembered your point about setting hierarchy, my bad!

Just two minor changes needed, since we can't remove validation entirely here.

Can you add test(s) for these names that cover special characters?  Since this is something that can potentially change over time, we'd need to ensure that's covered.  Once those changes and tests are in I'll run them on our acceptance suite and we'll get this merged.

Thanks again!

**Comment by jennings** [comment]
@jackofallops I added `validation.StringIsNotEmpty` and added my pathological setting name to the four acceptance tests I found that are testing `sticky_settings` on `azurerm_windows_web_app` and `azurerm_windows_function_app`. I hope this is what you intended, if not I can try again. Thanks for your help!

**Comment by jackofallops** [comment]
Tests looking fine:
image

Failure here was a transient issue:
image
