### PR TITLE
`storage` - allow `azurerm_storage_account` to be used in Data Plane restrictive environments

### LINKED ISSUE #10765: r/storage_account: support for provisioning items when private link required
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is a meta issue tracking support for conditionally using the Resource Manager API's rather than the Data Plane API's for the nested storage resources - which enables provisioning Containers, File Shares, Queues etc within Storage Accounts with Private Link enabled.

Unfortunately at this time there's compatibility issues between the Data Plane and Resource Manager API's, where the two aren't 1 for 1 compatible (e.g. missing functionality) and there's a permissions issue within the Resource Manager API's for older Role Assignments vs newer Role Assignments.

### New or Affected Resource(s)

* `azurerm_storage_*`

### References

* #0000

### LINKED ISSUE #27310: Error: reading static website for AzureRM Storage Account
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.2

### AzureRM Provider Version

3.116.0 / 4.0.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "friday" {
  name                            = "friday25a"
  resource_group_name             = "friday"
  location                        = "westeurope"
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
}
```

### Debug Output/Panic Output

```shell
Error: retrieving static website properties for Storage Account (Subscription: "sss" Resource Group Name: "friday" Storage Account Name: "friday25a"): executing request: Get "https://friday25a.blob.core.windows.net/?comp=properties&restype=service": context deadline exceeded
```

### Expected Behaviour

I understand the challenge - I have seen the other closed issues.
What would help is a `bool` flag that will instruct the provider to **not** refresh the Static Website properties because I don't want it to. I can remove this flag after I deploy the PE, but I cannot deploy the PE if the prerequisite - SA creation - blocks its creation.

### Actual Behaviour

Terraform is properly trying to honor DSC in this case, but causes an impossible scenario in regulated environment. A deadlock.

### Steps to Reproduce

_No response_

### Important Factoids

The Storage Account doesn't have Private Endpoint yet.
It will work just fine after it has a Private Endpoint...
... but I cannot create the Private Endpoint, because the Storage Account itself will not finish creating.
image
My TFE doesn't and will not have connectivity to internet.

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/24982
https://github.com/hashicorp/terraform-provider-azurerm/issues/20257

### LINKED ISSUE #27750: `azurerm_storage_account` cannot be created without internet access due to `static_website` field
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

4.3.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "configs" {
  name                     = var.config_storage_name
  resource_group_name      = azurerm_resource_group.stage.name
  location                 = azurerm_resource_group.stage.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  allow_nested_items_to_be_public = false
  public_network_access_enabled = false

  lifecycle {
    ignore_changes = [static_website]
  }
}
```

### Debug Output/Panic Output

```shell
Error: retrieving static website properties for Storage Account (Subscription: "[MASKED]"
│ Resource Group Name: "[MASKED]"
│ Storage Account Name: "configapp52xxxxx"): executing request: Get "https://configapp52xxxxx.blob.core.windows.net/?comp=properties&restype=service": context deadline exceeded
```

### Expected Behaviour

_No response_

### Actual Behaviour

The domain `*.core.windows.net` is blocked by our company firewall, so the request to that URL is supposed to fail. As I understand it, the root cause is that azure itself does not provide the current state of `static_website` via the API. [Azure/azure-rest-api-specs/issues/22984]

That said, it should be possible to explicitly ignore changes and thus not trigger the refresh if disabled in `lifecycle`. That would allow us to create the storage and PEP as planned.

### Steps to Reproduce

terraform plan

### Important Factoids

_No response_

### References

https://github.com/Azure/azure-rest-api-specs/issues/22984 <- the root cause of this and the other issues
https://github.com/hashicorp/terraform-provider-azurerm/issues/27750
https://github.com/hashicorp/terraform-provider-azurerm/issues/20257 
https://github.com/hashicorp/terraform-provider-azurerm/issues/2977

### PR DESCRIPTION
**Pull request by jackofallops**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritise for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR introduces functionality to allow the `azurerm_storage_account` resource to be deployed in situations that prohibit data plane access, such as Terraform agents that are behind restrictive Enterprise Firewalls. 

To preserve the ability to configure Data Plane only sections of the configuration, 2 new resources are introduced, these are `azurerm_storage_account_queue_properties` and `azurerm_storage_account_static_website`. These are intended to supersede the (now deprecated) `queue_properties` and `static_website` blocks on the `azurerm_storage_account` resource, these deprecated blocks are planned to be removed in `v5.0` of the provider. 

Also introduced is the `data_plane_available` Provider Feature flag. This allows the provider to be globally configured to not use the data plane APIs at all for `azurerm_storage_account`. The caveats are that the availability guarantees for the Data endpoints being ready are not available, and the `queue_properties` and `static_website` blocks become incompatible configuration, and will error on `plan` and `apply`. To allow these blocks to still be configured, The 2 new sub-resources mentioned above can allow users to  configure these items post-creation of the account, and if necessary, after the creation of Private Endpoints. See below for example usage of the flag in conjunction with PE's:

```terraform
provider "azurerm" {
  features {
    storage {
        data_plane_available = false 
    }
  }
}

resource "azurerm_storage_account" "nodataplane" {
  provider                 = azurerm.no_data_plane
  name                     = "account1"
  resource_group_name      = azurerm_resource_group.example
  location                 = "westeurope"
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
}

resource "azurerm_private_endpoint" "static_website" {
#  network specific config...
}

resource "azurerm_storage_account_static_website" "test" {
  storage_account_id = azurerm_storage_account.test.id
  error_404_document = "sadpanda_2.html"
  index_document     = "index_2.html"
  depends_on = [ azurerm_private_endpoint.static_website ]
}
```

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_storage_account` - can now be created and managed if Data Plane endpoints are blocked by a firewall
* **New Resource:** `azurerm_storage_account_queue_properties`
* **New Resource:** `azurerm_storage_account_static_website`
* New Provider Feature - storage `data_plane_available` feature flag

This is a (please select all that apply):

- [x] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

Depends on #27733 
Closes #27750 
Closes #27310 
Closes #10765

### CODE REVIEW

File: internal/services/storage/custompollers/data_plane_queues_availability_poller.go [hunk 1]
```diff
@@ -35,6 +36,10 @@ func NewDataPlaneQueuesAvailabilityPoller(ctx context.Context, client *storageCl
 
 func (d *DataPlaneQueuesAvailabilityPoller) Poll(ctx context.Context) (*pollers.PollResult, error) {
 	resp, err := d.client.GetServiceProperties(ctx)
+	var e pollers.PollingDroppedConnectionError
+	if errors.As(err, &e) {
+		return nil, err
+	}
```
Comment (stephybun) [inline internal/services/storage/custompollers/data_plane_queues_availability_poller.go:42]: The other two availability pollers return the `PollingDroppedConnectionError` based on whether `resp.HttpResponse == nil`. Can we not use the same pattern for checking here?

File: internal/services/storage/storage_account_data_plane_helpers.go [hunk 2]
```diff
@@ -64,8 +66,10 @@ func waitForDataPlaneToBecomeAvailableForAccount(ctx context.Context, client *cl
 			return fmt.Errorf("building Blob Service Poller: %+v", err)
 		}
 		poller := pollers.NewPoller(pollerType, initialDelayDuration, pollers.DefaultNumberOfDroppedConnectionsToAllow)
-		if err := poller.PollUntilDone(ctx); err != nil {
-			return fmt.Errorf("waiting for the Blob Service to become available: %+v", err)
+		if err = poller.PollUntilDone(ctx); err != nil {
+			if !connectionError(err) {
+				return fmt.Errorf("waiting for the Blob Service to become available: %+v", err)
+			}
```
Comment (stephybun) [inline internal/services/storage/storage_account_data_plane_helpers.go:72]: Clarifying my understanding here, if we get a connection error while polling we silently ignore it?

File: internal/services/storage/storage_account_queue_properties_resource.go
Comment (stephybun) [inline internal/services/storage/storage_account_queue_properties_resource.go:1]: We briefly discussed naming convention for data plane only resources, should this be renamed to `storage_account_queue_properties_data_plane_resource.go`?

File: internal/services/storage/storage_account_queue_properties_resource.go [hunk 3]
```diff
@@ -0,0 +1,666 @@
...
+}
+
+func (s AccountQueuePropertiesResource) Create() sdk.ResourceFunc {
+	return sdk.ResourceFunc{
+		Timeout: 30 * time.Minute,
+		Func: func(ctx context.Context, metadata sdk.ResourceMetaData) error {
+			storageClient := metadata.Client.Storage
+			var model AccountQueuePropertiesModel
+			if err := metadata.Decode(&model); err != nil {
+				return err
```
Comment (stephybun) [inline internal/services/storage/storage_account_queue_properties_resource.go:269]:
```suggestion
				return fmt.Errorf("decoding: %+v", err)
```

File: internal/services/storage/storage_account_queue_properties_resource.go [hunk 4]
```diff
@@ -0,0 +1,666 @@
...
+			}
+
+			// Get the target account to ensure it supports queues
+			account, err := storageClient.ResourceManager.StorageAccounts.GetProperties(ctx, *accountID, storageaccounts.DefaultGetPropertiesOperationOptions())
+			if err != nil {
+				return fmt.Errorf("retrieving %s: %+v", *accountID, err)
+			}
+			if account.Model == nil {
+				return fmt.Errorf("account %s has no model", *accountID)
+			}
```
Comment (stephybun) [inline internal/services/storage/storage_account_queue_properties_resource.go:284]: We've been returning these as 
```suggestion
			if account.Model == nil {
				return fmt.Errorf("retrieving %s: `model` was nil", *accountID)
			}
```

File: internal/services/storage/storage_account_queue_properties_resource.go [hunk 5]
```diff
@@ -0,0 +1,666 @@
...
+			if err != nil {
+				return err
+			}
+
+			state.StorageAccountId = id.ID()
+
+			account, err := storageClient.FindAccount(ctx, id.SubscriptionId, id.StorageAccountName)
+			if err != nil {
+				return metadata.MarkAsGone(id)
+			}
```
Comment (stephybun) [inline internal/services/storage/storage_account_queue_properties_resource.go:401]: Should we only be marking this as gone if it's a 404?

File: internal/services/storage/storage_account_queue_properties_resource.go [hunk 6]
```diff
@@ -0,0 +1,666 @@
...
+
+			client, err := storageClient.QueuesDataPlaneClient(ctx, *account, storageClient.DataPlaneOperationSupportingAnyAuthMethod())
+			if err != nil {
+				return fmt.Errorf("building Queues Client for %s: %v", *id, err)
+			}
+
+			props, err := client.GetServiceProperties(ctx)
+			if err != nil {
+				return fmt.Errorf("retrieving %s for update: %+v", *id, err)
```
Comment (stephybun) [inline internal/services/storage/storage_account_queue_properties_resource.go:530]:
```suggestion
				return fmt.Errorf("retrieving %s: %+v", *id, err)
```

File: internal/services/storage/storage_account_queue_properties_resource.go [hunk 7]
```diff
@@ -0,0 +1,666 @@
...
+			}
+
+			var model AccountQueuePropertiesModel
+
+			if err = metadata.Decode(&model); err != nil {
+				return err
```
Comment (stephybun) [inline internal/services/storage/storage_account_queue_properties_resource.go:536]:
```suggestion
				return fmt.Errorf("decoding: %+v", err)
```

File: internal/services/storage/storage_account_queue_properties_resource_test.go [hunk 8]
```diff
@@ -0,0 +1,322 @@
...
+	})
+}
+
+func TestAccStorageAccountQueueProperties_loggingOnly(t *testing.T) {
+	data := acceptance.BuildTestData(t, "azurerm_storage_account_queue_properties", "test")
+	r := AccountQueuePropertiesResource{}
+
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.complete(data),
```
Comment (stephybun) [inline internal/services/storage/storage_account_queue_properties_resource_test.go:41]:
```suggestion
			Config: r.loggingOnly(data),
```

File: internal/services/storage/storage_account_queue_properties_resource_test.go [hunk 9]
```diff
@@ -0,0 +1,322 @@
...
+	})
+}
+
+func TestAccStorageAccountQueueProperties_hourMetricsOnly(t *testing.T) {
+	data := acceptance.BuildTestData(t, "azurerm_storage_account_queue_properties", "test")
+	r := AccountQueuePropertiesResource{}
+
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.complete(data),
```
Comment (stephybun) [inline internal/services/storage/storage_account_queue_properties_resource_test.go:56]:
```suggestion
			Config: r.hourMetricsOnly(data),
```

File: internal/services/storage/storage_account_queue_properties_resource_test.go [hunk 10]
```diff
@@ -0,0 +1,322 @@
...
+	})
+}
+
+func TestAccStorageAccountQueueProperties_minuteMetricsOnly(t *testing.T) {
+	data := acceptance.BuildTestData(t, "azurerm_storage_account_queue_properties", "test")
+	r := AccountQueuePropertiesResource{}
+
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.complete(data),
```
Comment (stephybun) [inline internal/services/storage/storage_account_queue_properties_resource_test.go:71]:
```suggestion
			Config: r.minuteMetricsOnly(data),
```

File: internal/services/storage/storage_account_resource.go [hunk 11]
```diff
@@ -1266,28 +1145,144 @@ func resourceStorageAccount() *pluginsdk.Resource {
...
+						ValidateFunc: validation.StringIsNotEmpty,
+					},
+					"index_document": {
+						Type:         pluginsdk.TypeString,
+						Optional:     true,
+						ValidateFunc: validation.StringIsNotEmpty,
+					},
+				},
+			},
+			Deprecated: "this block has been deprecated and superseded by the `azurerm_storage_account_static_website` resource and will be removed in `v5.0` of the provider",
```
Comment (stephybun) [inline internal/services/storage/storage_account_resource.go:1169]: Minor but I've never seen us put the provider version in backticks in the deprecation message 
```suggestion
			Deprecated: "this block has been deprecated and superseded by the `azurerm_storage_account_static_website` resource and will be removed in v5.0 of the AzureRM provider",
```

File: internal/services/storage/storage_account_resource.go [hunk 12]
```diff
@@ -1266,28 +1145,144 @@ func resourceStorageAccount() *pluginsdk.Resource {
...
+								Type:         pluginsdk.TypeInt,
+								Optional:     true,
+								ValidateFunc: validation.IntBetween(1, 365),
+							},
+						},
+					},
+				},
+			},
+		},
+		Deprecated: "this block has been deprecated and superseded by the `azurerm_storage_account_queue_properties` resource and will be removed in `v5.0` of the provider",
```
Comment (stephybun) [inline internal/services/storage/storage_account_resource.go:1272]:
```suggestion
		Deprecated: "this block has been deprecated and superseded by the `azurerm_storage_account_queue_properties` resource and will be removed in v5.0 of the AzureRM provider",
```

File: internal/services/storage/storage_account_resource.go [hunk 13]
```diff
@@ -1482,21 +1472,70 @@ func resourceStorageAccountCreate(d *pluginsdk.ResourceData, meta interface{}) e
...
-		return fmt.Errorf("retrieving %s: %+v", id, err)
-	}
-	if dataPlaneAccount == nil {
-		return fmt.Errorf("unable to locate %q", id)
-	}
-
 	supportLevel := availableFunctionalityForAccount(accountKind, accountTier, replicationType)
-	if err := waitForDataPlaneToBecomeAvailableForAccount(ctx, storageClient, dataPlaneAccount, supportLevel); err != nil {
-		return fmt.Errorf("waiting for the Data Plane for %s to become available: %+v", id, err)
+	// Start of Data Plane access - this entire block can be removed for 5.0, as the data_plane_available flag becomes redundant at that time.
```
Comment (stephybun) [inline internal/services/storage/storage_account_resource.go:1480]: Just to clarify, will we be removing the `data_plane_available` feature flag in 5.0?

File: internal/services/storage/storage_account_resource.go [hunk 14]
```diff
@@ -1592,35 +1611,57 @@ func resourceStorageAccountCreate(d *pluginsdk.ResourceData, meta interface{}) e
...
-		}
-
-		accountsClient, err := storageClient.AccountsDataPlaneClient(ctx, *dataPlaneAccount, storageClient.DataPlaneOperationSupportingAnyAuthMethod())
-		if err != nil {
-			return fmt.Errorf("building Accounts Data Plane Client: %s", err)
-		}
-
-		staticWebsiteProps := expandAccountStaticWebsiteProperties(val.([]interface{}))
+	// Replacing the `return resourceStorageAccountRead(d, meta)` here with setting the configuration values directly to
+	// state allow us to skip a one read operation since this pattern is a code convenience/deduplication choice, and
```
Comment (stephybun) [inline internal/services/storage/storage_account_resource.go:1620]:
```suggestion
	// state allows us to skip one read operation since this pattern is a code convenience/deduplication choice, and
```

File: internal/services/storage/storage_account_resource.go [hunk 15]
```diff
@@ -2256,30 +2275,58 @@ func resourceStorageAccountRead(d *pluginsdk.ResourceData, meta interface{}) err
...
+		queueProperties := make([]interface{}, 0)
+		if supportLevel.supportQueue {
+			queueClient, err := dataPlaneClient.QueuesDataPlaneClient(ctx, *account, dataPlaneClient.DataPlaneOperationSupportingAnyAuthMethod())
+			if err != nil {
+				return fmt.Errorf("building Queues Client: %s", err)
+			}
+
+			queueProps, err := queueClient.GetServiceProperties(ctx)
+			if err != nil {
+				// Queue properties is a data plan only service, so we tolerate connection errors here in case of firewalls
```
Comment (stephybun) [inline internal/services/storage/storage_account_resource.go:2289]:
```suggestion
				// Queue properties is a data plane only service, so we tolerate connection errors here in case of firewalls
```

File: internal/services/storage/storage_account_static_website_resource.go
Comment (stephybun) [inline internal/services/storage/storage_account_static_website_resource.go:1]: Should this be renamed to `storage_account_static_website_data_plane_resource.go`

File: internal/services/storage/storage_account_static_website_resource.go [hunk 16]
```diff
@@ -0,0 +1,268 @@
...
+}
+
+func (a AccountStaticWebsiteResource) Create() sdk.ResourceFunc {
+	return sdk.ResourceFunc{
+		Timeout: 30 * time.Minute,
+		Func: func(ctx context.Context, metadata sdk.ResourceMetaData) error {
+			storageClient := metadata.Client.Storage
+			var model AccountStaticWebsiteResourceModel
+			if err := metadata.Decode(&model); err != nil {
+				return err
```
Comment (stephybun) [inline internal/services/storage/storage_account_static_website_resource.go:75]:
```suggestion
				return fmt.Errorf("decoding: %+v", err)
```

File: internal/services/storage/storage_account_static_website_resource.go [hunk 17]
```diff
@@ -0,0 +1,268 @@
...
+			}
+
+			// Get the target account to ensure it supports queues
+			account, err := storageClient.ResourceManager.StorageAccounts.GetProperties(ctx, *accountID, storageaccounts.DefaultGetPropertiesOperationOptions())
+			if err != nil {
+				return fmt.Errorf("retrieving %s: %+v", *accountID, err)
+			}
+			if account.Model == nil {
+				return fmt.Errorf("account %s has no model", *accountID)
```
Comment (stephybun) [inline internal/services/storage/storage_account_static_website_resource.go:89]:
```suggestion
				return fmt.Errorf("retrieving %s: `model` was nil", *accountID)
```

**Review by stephybun — CHANGES_REQUESTED** [review]

File: internal/services/storage/custompollers/data_plane_queues_availability_poller.go (hunk 1 above)
Comment (jackofallops) [reply internal/services/storage/custompollers/data_plane_queues_availability_poller.go:42]: Unfortunately the API call `GetServiceProperties` does not return the same struct, and does not contain `HttpResponse`, it instead returns the details and an error type. We check that error type here via `errors.As()` to take the appropriate action.

File: internal/services/storage/storage_account_data_plane_helpers.go (hunk 2 above)
Comment (jackofallops) [reply internal/services/storage/storage_account_data_plane_helpers.go:72]: Correct, whilst this is counter to typical behaviour in the provider it is necessary in this unique case until 5.0 and we complete the separation of Data Plane APIs from all Resource Manager resources.

File: internal/services/storage/storage_account_resource.go (hunk 13 above)
Comment (jackofallops) [reply internal/services/storage/storage_account_resource.go:1480]: Correct. There's no mechanism for deprecating Provider features at the moment, and such functionality is beyond the scope of this PR. 5.0 will have no overlap of Resource Manager and Data Plane API usage in resources so this flag will be redundant at that time.

File: internal/services/storage/storage_account_static_website_resource.go [hunk 18]
```diff
@@ -0,0 +1,268 @@
...
+			if err != nil {
+				return err
+			}
+
+			state.StorageAccountId = id.ID()
+
+			accountDetails, err := storageClient.FindAccount(ctx, id.SubscriptionId, id.StorageAccountName)
+			if err != nil {
+				return metadata.MarkAsGone(id)
+			}
```
[the remark this answers is not in the document]
Comment (jackofallops) [reply internal/services/storage/storage_account_static_website_resource.go:160]: As noted above, this function doesn't surface the HTTP code and if the err is not `nil` the account this resource belongs to cannot have been found, so should be marked as gone.

File: internal/services/storage/storage_account_static_website_resource.go [hunk 19]
```diff
@@ -0,0 +1,268 @@
...
+			storageClient := metadata.Client.Storage
+
+			id, err := commonids.ParseStorageAccountID(metadata.ResourceData.Id())
+			if err != nil {
+				return err
+			}
+
+			accountDetails, err := storageClient.FindAccount(ctx, id.SubscriptionId, id.StorageAccountName)
+			if err != nil {
+				// If we don't find the account we can safely assume we don't need to remove the website since it must already be deleted
```
[the remark this answers is not in the document]
Comment (jackofallops) [reply internal/services/storage/storage_account_static_website_resource.go:195]: as above.

**Review by stephybun — APPROVED** [review]
Thanks @jackofallops, provided the tests in both 4.0 and 5.0 mode pass this looks good to me 🫎

**Comment by jackofallops** [comment]
Test results
v4 mode:
image

v5 mode:
image

**Comment by bethforsyth** [comment]
(I'd left a comment on https://github.com/hashicorp/terraform-provider-azurerm/issues/27750, but commenting here too) - needing to re-import existing storage accounts is extremely non ideal for managing long lived resources - the more manual fiddling with terraform state you do, the easier it is to break something, and we use terraform to manage some fairly critical infratructure. If it is possible to make this upgradable with no manual inputs (maybe warnings about any queue_properties or static_website  blocks that would be lost if not migrated to the new types) that would be vastly preferable.  😄

**Comment by jackofallops** [comment]
Hi @joakimlemb 

You are correct, this was intended to be for newly created accounts, however, it is not necessary to set for existing accounts as the API calls to the Data Plane endpoints failing for reasons relating to network connection availability will now not fail the Terraform operation (create/read/update). This tolerance does come at the expense of deployment time, in that we have to perform retries to help protect against temporary failures, but ultimately fire-walled deployments unable to reach Data Plane URLs will still succeed.  The `data_plane_available` feature flag is intended for use where the `queue_properties` and `static_website` blocks are never going to be used on the resource (even post creation after any Private Endpoints are available) to bypass these availability checks altogether and provide a similar experience to that which will be in place after 5.0 ships and these properties/blocks are removed altogether in favour of their new replacement resources. There should be no need to remove/re-import to make use of this functionality.

I can see that the storage feature block is missing from the features documentation, so we'll get that added with an explanation as above. I'll take a look at making the feature flag compatible with existing storage accounts too, but I suspect that may potentially end up with a Diff that would need to be added to `ignore_changes` since there may already be values present in the state.

Hope this helps!

**Comment by bethforsyth** [comment]
@jackofallops Thanks for the clarification on in intended behaviour! To make sure I understand - you're saying that taking 4.9.0 should allow deployment of storage accounts with no change to definitions other than the provider version? Should that also apply to terraform plan? I've just attempted to test this out, and I'm still seeing errors on terraform plan operations unfortunately. 

```Error: retrieving static website properties for Storage Account (Subscription: "<subscription>"
Resource Group Name: "<rg name>"
Storage Account Name: "<storage account name>"): executing request: Get "https://<storage account name>.blob.core.windows.net/?comp=properties&restype=service": dial tcp: lookup <storage account name>.blob.core.windows.net on 127.0.0.53:53: no such host```

**Comment by jackofallops** [comment]
> @jackofallops Thanks for the clarification on in intended behaviour! To make sure I understand - you're saying that taking 4.9.0 should allow deployment of storage accounts with no change to definitions other than the provider version? Should that also apply to terraform plan? I've just attempted to test this out, and I'm still seeing errors on terraform plan operations unfortunately.
> 
> ```
> Resource Group Name: "<rg name>"
> Storage Account Name: "<storage account name>"): executing request: Get "https://<storage account name>.blob.core.windows.net/?comp=properties&restype=service": dial tcp: lookup <storage account name>.blob.core.windows.net on 127.0.0.53:53: no such host```
> ```

Hi @bethforsyth - Apologies for the delay in response, I didn't get a notification for some reason!

Correct, in every scenario (customer and theoretical) this was tested, this was the case. I see from the error you provided that you're using a link-local address for DNS resolution? Do you have a local `Hosts` file configured (or local DNS resolver) on your Terraform agent that has some bespoke configuration for responding to the Data Plane endpoint domains? (e.g. *.blob.core.windows.net) If so, can you test without this in place?

(in the meantime, I'll check why I didn't get notified of your mention, and I'll keep popping back to this issue to check for replies. Sorry again about that!)

**Comment by gesnaud** [comment]
Hello @jackofallops !

I tried to use the `data_plane_available` feature without success

- I created a storage account with   `data_plane_available = false` and with `public_network_access_enabled = false`
-  Then I change the code to add a container to the created storage account
- It failed with a 403
- I destroyed everything
- I created a storage account with   `data_plane_available = true` and with `public_network_access_enabled = false`
-  Then I change the code to add a container to the created storage account
- It failed agauin with a 403.

Shoud I have misunderstood the purpose? OR normally with `data_plane_available = true` I should have been able to create a container?

Thanks for your reply!

**Comment by gesnaud** [comment]
Hi @joakimlemb !

Thanks for the tips... But, how to know which management features is concerned?

@jackofallops , I tried another time by 
1. Create storage account with:
  - `data_plane_available = false` 
  - A network rule allowing one of the both public ip I have access to.
  - The host from where I execute the code *does not* use the public IP authorized on the storage account.
  - I expect, thanks to the feature, that my code will be able to update the storage account even if it is not in the white list.
 2. I update the code by adding the creation of a container.
   - I have a 403....

please @jackofallops , teach me how to use your feature!
