### PR TITLE
`azurerm_virtual_machine_scale_set`: adding a `plan` block for Marketplace images

### LINKED ISSUE #95: Missing required plan information support for Azure Marketplace images in azurerm_virtual_machine_scale_set
_This issue was originally opened by @atld as hashicorp/terraform#14926. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
* azurerm_virtual_machine_scale_set

### Terraform Configuration Files
```hcl
...
resource "azurerm_virtual_machine_scale_set" "worker-vmss" {
  name                = "worker-vmss"
  location            = "West Europe"
  resource_group_name = "${azurerm_resource_group.psqldemo-rg.name}"
  upgrade_policy_mode = "Manual"

  plan {
    name = "docker-ce"
    product = "docker-ce"
    publisher = "docker"
  }
...
```
### Expected Behavior
According to[ virtualMachineScaleSets template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachinescalesets), for Azure marketplace images, [Plan](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#plan) section should be supported in azurerm_virtual_machine_scale_set resource, similarly like for azurerm_virtual_machine resource type. 

### Actual Behavior
During VMSS creation, in case there is no plan section, Terraform drops the following error:
```hcl
* azurerm_virtual_machine_scale_set.worker-vmss: 1 error(s) occurred:

* azurerm_virtual_machine_scale_set.worker-vmss: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="VMMarketplaceInvalidInput" Message="Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is worker-vmss_worker-vmss_0_OsDisk_1_97a2010334f9449baad0f65c9a6351e9."
```

If I define plan section, I got following error:
```hcl
1 error(s) occurred:

* azurerm_virtual_machine_scale_set.worker-vmss: : invalid or unknown key: plan
```

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Adding a `plan` block to VMSS to match the VM resource so that we support deploying Marketplace images

Tests pass:

screen shot 2017-07-08 at 08 38 23

Fixes #95

### CODE REVIEW

File: azurerm/resource_arm_virtual_machine_scale_set.go [hunk 1]
```diff
@@ -653,6 +688,10 @@ func resourceArmVirtualMachineScaleSetRead(d *schema.ResourceData, meta interfac
 		d.Set("extension", extension)
 	}
 
+	if resp.Plan != nil {
+		d.Set("plan", flattenAzureRmVirtualMachineScaleSetPlan(resp.Plan))
```
Comment (stack72) [inline azurerm/resource_arm_virtual_machine_scale_set.go]: for complex Set operations like this, it would be good to throw an error if the set fails

File: azurerm/resource_arm_virtual_machine_scale_set.go [hunk 2]
```diff
@@ -417,6 +417,31 @@ func resourceArmVirtualMachineScaleSet() *schema.Resource {
...
+							Required: true,
+						},
+
+						"product": {
+							Type:     schema.TypeString,
+							Required: true,
+						},
+					},
+				},
+				Set: resourceArmVirtualMachineScaleSetPlanHash,
```
Comment (stack72) [inline azurerm/resource_arm_virtual_machine_scale_set.go]: I think we can just use the Default Set Hash - it does exactly the same thing you have done but without a custom func for it

File: azurerm/resource_arm_virtual_machine_scale_set.go [hunk 3]
```diff
@@ -1475,3 +1514,40 @@ func expandAzureRMVirtualMachineScaleSetExtensions(d *schema.ResourceData) (*com
...
+	buf.WriteString(fmt.Sprintf("%s-", m["publisher"].(string)))
+	buf.WriteString(fmt.Sprintf("%s-", m["product"].(string)))
+
+	return hashcode.String(buf.String())
+}
+
+func flattenAzureRmVirtualMachineScaleSetPlan(plan *compute.Plan) []interface{} {
+	result := make(map[string]interface{})
+
+	result["name"] = *plan.Name
```
Comment (stack72) [inline azurerm/resource_arm_virtual_machine_scale_set.go]: No chance these can be missing right? If they can, then panic city...

**Review by stack72 — COMMENTED** [review]
Hi @tombuildsstuff 

LGTM - few minor points inline

P.

File: azurerm/resource_arm_virtual_machine_scale_set.go (hunk 3 above)
Comment (tombuildsstuff) [inline azurerm/resource_arm_virtual_machine_scale_set.go]: According to the docs, no - as all 3 fields are required

File: azurerm/resource_arm_virtual_machine_scale_set.go (hunk 1 above)
Comment (tombuildsstuff) [inline azurerm/resource_arm_virtual_machine_scale_set.go]: Updated.

File: azurerm/resource_arm_virtual_machine_scale_set.go (hunk 2 above)
Comment (tombuildsstuff) [inline azurerm/resource_arm_virtual_machine_scale_set.go]: Updated.

**Comment by tombuildsstuff** [comment]
Updated and tests still pass: 
screen shot 2017-07-17 at 06 42 12

**Review by mbfrahry — APPROVED** [review]
LGTM!
