### PR TITLE
`azurerm_managed_disk` `azurerm_snapshot`: Deprecate `enabled` in `encryption_settings`

### LINKED ISSUE #14574: r/managed_disk: support for platform encryption
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would want to enable encryption for azurerm_managed_disk resources on Azure which uses Default Encryption using platform managed keys. However, terraform resource doesn't provide the feature, with just enabling encryption_settings, it throws below error:
`Error: creating/updating Managed Disk "acctestmd2" (Resource Group "TerraformTesting"): compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="DiskEncryptionKey is required for  if encryption is enabled."`

### New or Affected Resource(s)

* azurerm_managed_disk

### Potential Terraform Configuration

Disk-encryption-Azure

```
resource "azurerm_managed_disk" "copy" {
  name                 = "acctestmd2"
  location             = "West US 2"
  resource_group_name  = azurerm_resource_group.rg.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  # source_resource_id   = azurerm_managed_disk.source.id
  disk_size_gb         = "1"
  encryption_settings {
    enabled = true
  }
}
```

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_disk#encryption_settings

* #0000

### PR DESCRIPTION
**Pull request by myc2h6o**
- Fix #14574 `enabled` can be determined according to `disk_encryption_key`, deprecating it to avoid additional settings and confusion.
- Removed `enabled` in doc.
- Added missing `encryption_settings` in `r\snapshot.html.markdown`
- `encryption_settings` now supports updating the keys, did some change in expand function signature so that it suits the Update call

### CODE REVIEW

File: internal/services/compute/encryption_settings.go [hunk 1]
```diff
@@ -13,15 +13,15 @@ func encryptionSettingsSchema() *pluginsdk.Schema {
...
 				"enabled": {
-					Type:     pluginsdk.TypeBool,
-					Required: true,
-
-					// Azure can change enabled from false to true, but not the other way around, so
-					//   to keep idempotency, we'll conservatively set this to ForceNew=true
-					ForceNew: true,
+					Type:       pluginsdk.TypeBool,
+					Optional:   true,
+					Default:    true,
```
Comment (myc2h6o) [inline internal/services/compute/encryption_settings.go:20]: Set the default value to `true`, so that it fits the logic when only `disk_encryption_key` is specified and `enabled` is not specified

File: internal/services/compute/encryption_settings.go [hunk 2]
```diff
@@ -63,10 +63,15 @@ func encryptionSettingsSchema() *pluginsdk.Schema {
 	}
 }
 
-func expandManagedDiskEncryptionSettings(settings map[string]interface{}) *compute.EncryptionSettingsCollection {
-	enabled := settings["enabled"].(bool)
+func expandManagedDiskEncryptionSettings(settingsList []interface{}) *compute.EncryptionSettingsCollection {
+	if len(settingsList) == 0 {
+		return &compute.EncryptionSettingsCollection{}
```
Comment (myc2h6o) [inline internal/services/compute/encryption_settings.go:68]: This is for update call, when removing the `encryption_settings` block. This will set the enabled to false and remove encryption keys

**Comment by myc2h6o** [comment]
Example for Disk ADE is moved to #15356 so that example linting can pass.
Because `enabled` is changed from `Required` to `Optional`, need to wait for new release to allow the example linting to pass

File: internal/services/compute/managed_disk_resource.go [hunk 3]
```diff
@@ -257,6 +258,16 @@ func resourceManagedDisk() *pluginsdk.Resource {
 
 			return s
 		}(),
+
+		// Encryption Settings cannot be disabled once enabled
+		CustomizeDiff: pluginsdk.CustomDiffWithAll(
+			pluginsdk.ForceNewIfChange("encryption_settings", func(ctx context.Context, old, new, meta interface{}) bool {
+				if !features.ThreePointOhBeta() {
+					return false
```
Comment (myc2h6o) [inline internal/services/compute/managed_disk_resource.go:266]: For 2.x `enabled` is `ForceNew`, so return `false`

**Comment by myc2h6o** [comment]
Hi @katbyte @tombuildsstuff I've added `CustomizeDiff` and `ForceNewIfChange` to `encryption_settings` in disk and snapshot resource and move 3.0 related changes behind the 3.0 beta flag. Please take a look.

**Comment by myc2h6o** [comment]
Test result with `TestAccManagedDisk_|TestAccSnapshot_ `
`TestAccManagedDisk_import` fails on main as well for missing blob `https://accsa220323034733968725.blob.core.windows.net/vhds/myosdisk1.vhd`, maybe it was deleted in the subscription or blob permission changed?
image

**Review by katbyte — CHANGES_REQUESTED** [review]
build failures:
image

File: internal/services/compute/encryption_settings.go [hunk 4]
```diff
@@ -2,29 +2,79 @@ package compute
...
+				Schema: map[string]*pluginsdk.Schema{
+					"enabled": {
+						Type:     pluginsdk.TypeBool,
+						Optional: true,
+						Default:  true,
+
+						// Azure can change enabled from false to true, but not the other way around, so
+						//   to keep idempotency, we'll conservatively set this to ForceNew=true
+						ForceNew:   true,
+						Deprecated: "Deprecated, Azure Disk Encryption is now configured directly by `disk_encryption_key` and `key_encryption_key`. To disable Azure Disk Encryption, please remove `encryption_settings` block",
```
[the remark this answers is not in the document]
Comment (myc2h6o) [reply internal/services/compute/encryption_settings.go]: Updated

**Comment by myc2h6o** [comment]
@katbyte thanks for reviewing! I've updated the deprecation message, as well as resolved the build issue after merging latest main. Please take a look

**Comment by myc2h6o** [comment]
Updated test result: (`TestAccManagedDisk_import` is being fixed in #18303)
image

**Review by katbyte — APPROVED** [review]
Thanks @myc2h6o - LGTM 👾

**Comment by katbyte** [comment]
@myc2h6o - good to go once merge conflicts are fixed

**Comment by myc2h6o** [comment]
Hi @katbyte I've resolved the merge conflicts.

**Comment by myc2h6o** [comment]
Test result after the update
image
