### PR TITLE
`azurerm_web_app_hybrid_connection` `azurerm_app_hybrid_connection` - update auth rule id subscription

### LINKED ISSUE #20756: Parse for hybridConnections is case sensitive, does not match reply from Az
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_web_app_hybrid_connection

### Terraform Configuration Files

```hcl
resource "azurerm_web_app_hybrid_connection" "web_app_hybrid_connection" {
  for_each = var.HYBRID_CONNECTION_TARGET.hybridconnections
  web_app_id = azurerm_windows_web_app.app_service.id
  relay_id   = azurerm_relay_hybrid_connection.shipmanager-api-proxy-hybrid-connection[each.key].id
  hostname   = each.value.hybrid_connection_target_server
  port       = each.value.hybrid_connection_target_server_port
  send_key_name = "defaultSender"
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/****/resourceGroups/shipmanager-prod/providers/Microsoft.Relay/namespaces/xxxx-api-proxy-relay-prod/hybridconnections/xxxx-dev": parsing segment "staticHybridConnections": expected the segment "hybridconnections" to be "hybridConnections"
│
│   with module.app-service-with-hybrid-connection.azurerm_web_app_hybrid_connection.web_app_hybrid_connection["xxxx-dev"],
│   on ..\..\stacks\app-service-with-hybrid-connection\hybrid-connection.tf line 53, in resource "azurerm_web_app_hybrid_connection" "web_app_hybrid_connection":
│   53: resource "azurerm_web_app_hybrid_connection" "web_app_hybrid_connection" {
│
│ parsing "/subscriptions/****/resourceGroups/shipmanager-prod/providers/Microsoft.Relay/namespaces/xxxx-api--proxy-relay-prod/hybridconnections/xxxx-dev": parsing
│ segment "staticHybridConnections": expected the segment "hybridconnections" to be "hybridConnections"
```

### Expected Behaviour

The terraform plan execution executes successfully and azurerm_web_app_hybrid_connection is able to validate the current config against latest state.

### Actual Behaviour

The parsing error occurs as it seems the provider is expecting hybrid**C**onnections in the resource string return by azure but instead azure is returning hybrid**c**onnections with lowercase c

### Steps to Reproduce

No pre-existing resource
-terraform apply 
  - creating web app with configured relay and hybrid connection is created without issues
-terraform plan
  - the error occurs

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by myc2h6o**
Using ID from relayId to compose authorization rule, instead of the ID from the resource itself.

### CODE REVIEW

File: internal/services/appservice/web_app_hybrid_connection_resource.go [hunk 1]
```diff
@@ -231,12 +231,7 @@ func (r WebAppHybridConnectionResource) Read() sdk.ResourceFunc {
 				}
 
 				hybridConnectionsClient := metadata.Client.Relay.HybridConnectionsClient
-				hybridConnectionID, err := hybridconnections.ParseHybridConnectionID(appHybridConn.RelayId)
-				if err != nil {
-					return err
-				}
-
-				ruleID := hybridconnections.NewHybridConnectionAuthorizationRuleID(id.SubscriptionId, hybridConnectionID.ResourceGroupName, appHybridConn.ServiceBusNamespace, *existing.Name, appHybridConn.SendKeyName)
+				ruleID := hybridconnections.NewHybridConnectionAuthorizationRuleID(id.SubscriptionId, relayId.ResourceGroupName, appHybridConn.ServiceBusNamespace, *existing.Name, appHybridConn.SendKeyName)
```
Comment (tombuildsstuff) [inline internal/services/appservice/web_app_hybrid_connection_resource.go:234]: this is using a different resource group, which is going to be a breaking change - what's the reasoning for this?

Comment (myc2h6o) [reply internal/services/appservice/web_app_hybrid_connection_resource.go:234]: `hybridConnectionID` and `relayId` are both parsed from `appHybridConn.RelayId`, which we parsed twice duplicated from above, thus removing one of them. This is similar to https://github.com/hashicorp/terraform-provider-azurerm/pull/20237#discussion_r1093117062

Comment (tombuildsstuff) [reply internal/services/appservice/web_app_hybrid_connection_resource.go:234]: since we're querying the Hybrid Connection Rule, doesn't this want to be this?

```suggestion
				ruleID := hybridconnections.NewHybridConnectionAuthorizationRuleID(appHybridConn.SubscriptionId, appHybridConn.ResourceGroupName, appHybridConn.ServiceBusNamespace, *existing.Name, appHybridConn.SendKeyName)
```

Comment (myc2h6o) [reply internal/services/appservice/web_app_hybrid_connection_resource.go]: Right. I've updated subscriptionID for composing the Authorization Rule ID to be the one from appHybridConn, which is `relayId`

**Review by jackofallops — APPROVED** [review]
Thanks @myc2h6o - this LGTM now 👍

**Comment by jackofallops** [comment]
Tests passing: 

image
