### PR TITLE
`azurerm_managed_disk` additions

### LINKED ISSUE #327: azurerm_managed_disk does not support FromImage
The Azure REST API supports creating a separate managed disk instance from a standard offering image, as opposed to within a VM OS disk definition block.

https://docs.microsoft.com/en-us/rest/api/compute/manageddisks/disks/disks-create-or-update

There are a number of terraform use-cases where separating the disk definition from the VM definition is extremely useful. 
Particularly: Certain changes to a VM require a destroy/rebuild and terraform can't reattach an existing OS disk without code changes (FromImage -> Attach).

This means that all your VM redeploys that don't set `delete os disk on termination` will fail.

This means otherwise generic and maintainable IaaS code is now operation specific to that one change.

### Terraform Version
0.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_managed_disk

### Expected Behavior
Terraform creates the managed disk and then attaches it to the VM.

### Actual Behavior
Terraform throws the following error:
`module.dcos.azurerm_managed_disk.dcosBootstrapOSDisk: expected create_option to be one of [Import Empty Copy], got FromImage`

### PR DESCRIPTION
**Pull request by tombuildsstuff**
- Enables creating Managed Disks from Platform Images by supporting "FromImage"
- Enables creating Encrypted Managed Disks as started in #157 

Fixes #327

### CODE REVIEW

File: azurerm/resource_arm_managed_disk.go [hunk 1]
```diff
@@ -77,10 +84,12 @@ func resourceArmManagedDisk() *schema.Resource {
 
 			"disk_size_gb": {
```
Comment (mbfrahry) [inline azurerm/resource_arm_managed_disk.go]: Should we change how we get `disk_size_gb` now that it's not required? Swap to `GetOk`?

**Review by mbfrahry — APPROVED** [review]
LGTM with a minor comment

File: azurerm/resource_arm_managed_disk.go (hunk 1 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_managed_disk.go]: we could - however given this is an Integer it wouldn't help (as the default value is still `0`) - as such I think the current `Get` with a check > 0 should work (from below):

```
if v := d.Get("disk_size_gb"); v != 0 {
```
