### PR TITLE
`azurerm_storage_account` - `azure_file_authentication.0.active_directory` supports setting `domain_name` and `domain_guid` when `directory_type` is `AADKERB`

### LINKED ISSUE #22784: azurerm_storage_account with azure files authentication AADKERB & active directory settings
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.65.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "this" {
  name                = "storageacc"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location

  account_tier              = "Premium"
  account_kind              = "FileStorage"
  account_replication_type  = "ZRS"
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"

  azure_files_authentication {
    directory_type = "AADKERB"
    active_directory {
      domain_name = "xxxxxxx"
      domain_guid = "xxxxxxx"
    }
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

the following properties should not be required when `azure_files_authentication.directory_type` is set to `AADKERB`:
- domain_sid
- forest_name
- netbios_domain_name
- storage_sid

only `domain_name` and `domain_guid` should be required, see ARM spec: https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-bicep#activedirectoryproperties

Relevant part of the code: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/storage/storage_account_resource.go#L191

### Actual Behaviour

```
╷
│ Error: Missing required argument
│ 
│   on storage.tf line 27, in resource "azurerm_storage_account" "this":
│   27:     active_directory {
│ 
│ The argument "domain_sid" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on storage.tf line 27, in resource "azurerm_storage_account" "this":
│   27:     active_directory {
│ 
│ The argument "forest_name" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on storage.tf line 27, in resource "azurerm_storage_account" "this":
│   27:     active_directory {
│ 
│ The argument "netbios_domain_name" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on storage.tf line 27, in resource "azurerm_storage_account" "this":
│   27:     active_directory {
│ 
│ The argument "storage_sid" is required, but no definition was found.
╵
```

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by magodo**
This PR changes downgrades the following properties in `azure_file_authentication.0.active_directory` block from `Required` to `Optional` + (the unfortunate) `Computed`:

- domain_sid
- storage_sid
- forest_name
- netbios_domain_name

These 4 properties are not needed to be set in the `active_directory` when the `directory_type` is set to `AADKERB` 

The reason to add the `Computed` for them is to align with the current user experience of the whole `active_directory` block (which was set to be `O+C` for now). Since when setting to `AADKERB` with omitting the `domain_name` and `domain_guid`, the whole block is returned back. Otherwise, users might be confused to be asked to explicitly ignore changes for those four properties once they set the `domain_name` and `domain_guid`.

Fix #22784

## Test

image

### CODE REVIEW

File: internal/services/storage/storage_account_resource.go [hunk 1]
```diff
@@ -208,21 +202,31 @@ func resourceStorageAccount() *pluginsdk.Resource {
...
+										Optional:     true,
+										Computed:     true,
 										ValidateFunc: validation.StringIsNotEmpty,
 									},
 
 									"netbios_domain_name": {
 										Type:         pluginsdk.TypeString,
-										Required:     true,
+										Optional:     true,
+										Computed:     true,
```
Comment (stephybun) [inline internal/services/storage/storage_account_resource.go:229]: Since these fields were previously set to `Required` they will have been set anyway if the block was supplied, so I don't see any benefit in having them set to Computed. The users should be adding these to `ignore_changes`.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this @magodo. I don't believe that asking users to add these fields to `ignore_changes` is a confusing requirement or a strong enough reason to be setting these to Computed as well.

It's an expectation in Terraform that users should explicitly ignore fields that they do not wish to configure. Given that at some point in the future we will have to go through and re-evaluate which fields can remain O+C I think it's better to introduce and enforce this behaviour now, than further down the track and all in one go.

**Comment by magodo** [comment]
@stephybun Thank you for the review! I've now removed the `Computed` and update the test to put them into the `ignore_changes`, the test is passing: 
image

Please take another look!

File: internal/services/storage/storage_account_resource.go [hunk 2]
```diff
@@ -2462,29 +2462,60 @@ func expandArmStorageAccountAzureFilesAuthentication(input []interface{}) (*stor
...
+			return nil, fmt.Errorf("`active_directory.0.forest_name` is required when `directory_type` is `AD`")
+		}
+		if ad.NetBiosDomainName == nil {
+			return nil, fmt.Errorf("`active_directory.0.netbios_domain_name` is required when `directory_type` is `AD`")
+		}
+	case string(storageaccounts.DirectoryServiceOptionsAADKERB):
+		if _, ok := v["active_directory"]; ok {
+			ad = expandArmStorageAccountActiveDirectoryProperties(v["active_directory"].([]interface{}))
+		}
+	}
```
Comment (stephybun) [inline internal/services/storage/storage_account_resource.go:2489]: Minor but we need to call the expand function for the AD properties in all cases so I think we can simplify this to
```suggestion
	ad := expandArmStorageAccountActiveDirectoryProperties(v["active_directory"].([]interface{}))
	if directoryOption == storage.DirectoryServiceOptionsAD {
		if ad == nil {
			return nil, fmt.Errorf("`active_directory` is required when `directory_type` is `AD`")
		}
		if ad.AzureStorageSid == nil {
			return nil, fmt.Errorf("`active_directory.0.storage_sid` is required when `directory_type` is `AD`")
		}
		if ad.DomainSid == nil {
			return nil, fmt.Errorf("`active_directory.0.domain_sid` is required when `directory_type` is `AD`")
		}
		if ad.ForestName == nil {
			return nil, fmt.Errorf("`active_directory.0.forest_name` is required when `directory_type` is `AD`")
		}
		if ad.NetBiosDomainName == nil {
			return nil, fmt.Errorf("`active_directory.0.netbios_domain_name` is required when `directory_type` is `AD`")
		}
	}
```

File: website/docs/r/storage_account.html.markdown [hunk 3]
```diff
@@ -344,23 +344,21 @@ A `azure_files_authentication` block supports the following:
 
 * `active_directory` - (Optional) A `active_directory` block as defined below. Required when `directory_type` is `AD`.
```
Comment (stephybun) [inline website/docs/r/storage_account.html.markdown:345]: Can we add a note above for `directory_type` clarifying that `domain_sid`, `storage_sid`, `forest_name`, `netbios_domain_name` are required when `directory_type` is set to `AD`?

**Review by stephybun — COMMENTED** [review]
Thanks for removing `Computed` from those fields @magodo! I think this is almost good to go - an additional note on the docs would be good to clarify that all the fields are needed when the `directory_type` is `AD` and there is also potential for some simplification. This should be good to go once that's done 👍

File: website/docs/r/storage_account.html.markdown (hunk 3 above)
Comment (magodo) [reply website/docs/r/storage_account.html.markdown:345]: They are mentioned for each of the property themselves, do you mean we need to add an additional note something like:

```
~> **NOTE:** `domain_sid`, `storage_sid`, `forest_name`, `netbios_domain_name` are required when `directory_type` is set to `AD`.

A `active_directory` block supports the following:

* `domain_name` - (Required) Specifies the primary domain that the AD DNS server is authoritative for.

* `domain_guid` - (Required) Specifies the domain GUID.

...

```

File: internal/services/storage/storage_account_resource.go (hunk 2 above)
Comment (stephybun) [reply internal/services/storage/storage_account_resource.go:2489]: I'm not sure I follow? I pulled your branch and ran the test with those changes and it appears to be fine?

File: website/docs/r/storage_account.html.markdown (hunk 3 above)
Comment (stephybun) [reply website/docs/r/storage_account.html.markdown:345]: Ah apologies, I overlooked that sentence in the property description. In which case that's fine, nothing to do here.

File: internal/services/storage/storage_account_resource.go (hunk 2 above)
Comment (stephybun) [reply internal/services/storage/storage_account_resource.go:2489]: @magodo do you have an update?

**Comment by magodo** [comment]
@stephybun Thank you for the review! I've updated the code per your comment, please take another look!

```test
terraform-provider-azurerm on  storage_account_azf_auth_aadkerb via 🐹 v1.21.1 took 5m40s
💤  TF_ACC=1 go test -v -timeout=20h -run='TestAccAzureRMStorageAccount_azureFilesAuthentication' ./internal/services/storage
=== RUN   TestAccAzureRMStorageAccount_azureFilesAuthentication
=== PAUSE TestAccAzureRMStorageAccount_azureFilesAuthentication
=== CONT  TestAccAzureRMStorageAccount_azureFilesAuthentication
--- PASS: TestAccAzureRMStorageAccount_azureFilesAuthentication (348.23s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       348.242s
```

**Review by stephybun — APPROVED** [review]
Thanks @magodo LGTM 🦕
