### PR TITLE
Fix vm not turning back on after update

### LINKED ISSUE #16656: After DH migration to other Host VMs are in deallocated state
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
No errors
```

### Expected Behaviour

VM after changing dedicated_host_id should be in started state

### Actual Behaviour

VM after changing dedicated_host_id are in deallocated state and need manual start action via Portal

### Steps to Reproduce

1. Have VM running on DH, say Type2
2. Update terraform dedicated_host_id to other DH, say Type4
3. terraform apply
4. VM is migrated fine with all the resources but it is in stopped state (dealloc), required manual start

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by myc2h6o**
- Fix #16656
- Update vm deallocating/shutting down in `r/managed_disk` as well to keep them consistent

### CODE REVIEW

File: internal/services/compute/managed_disk_resource.go [hunk 1]
```diff
@@ -715,14 +715,16 @@ func resourceManagedDiskUpdate(d *pluginsdk.ResourceData, meta interface{}) erro
 				state = strings.TrimPrefix(state, "powerstate/")
 				switch strings.ToLower(state) {
 				case "deallocated":
-				case "deallocating":
-					shouldTurnBackOn = false
+					// VM already deallocated, no shutdown and deallocation needed anymore
 					shouldShutDown = false
 					shouldDeallocate = false
-				case "stopping":
```
Comment (myc2h6o) [inline internal/services/compute/managed_disk_resource.go:722]: setting `shouldTurnBackOn` to `false` is not needed in case of `stopping` as `virtualMachineShouldBeStarted` already returns false when state is not `running`

**Comment by kolargol** [comment]
when this will be implemented in the release ?

**Comment by myc2h6o** [comment]
@tombuildsstuff to possibly review on this.

**Review by katbyte — APPROVED** [review]
Thanks @myc2h6o - LGTM 🥫
