### PR TITLE
[Bug:] `azurerm_cdn_frontdoor_firewall_policy` - expose `AnomalyScoring` in `override` `rule` `action` for DRS 2.0

### LINKED ISSUE #18480: Can't override anomaly based rules for azurerm_cdn_frontdoor_firewall_policy due to incorrect validator
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.23.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_firewall_policy

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_firewall_policy" "foobar" {
  name                = "foobar"
  resource_group_name = "foo"
  sku_name            = "Premium_AzureFrontDoor"
  enabled             = true
  mode                = "Prevention"

  managed_rule {
    type    = "Microsoft_DefaultRuleSet"
    version = "2.0"
    action  = "Block"

    override {
      rule_group_name = "PROTOCOL-ENFORCEMENT"
      rule {
        rule_id = "920320"
        enabled = false
        action = "AnomalyScoring" # This action is what the Azure portal sets but it doesn't pass Terraform validation
      }
      rule {
        rule_id = "920330"
        enabled = false
        action = "Block" # This action passes terraform validation but isn't accepted by Azure for Microsoft DefaultRuleSet
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected managed_rule.0.override.0.rule.0.action to be one of [Allow Log Block Redirect], got AnomalyScoring
│
│   with azurerm_cdn_frontdoor_firewall_policy.foobar,
│   on frontdoor-waf.tf line 84, in resource "azurerm_cdn_frontdoor_firewall_policy" "foobar":
│   84:         action = "AnomalyScoring"
│
```

### Expected Behaviour

We should be able to disable rules from managed rule set `Microsoft_DefaultRuleSet_2.0`

### Actual Behaviour

Terraform validation blocks us from disabling rules.

### Steps to Reproduce

We want to disable certain managed rules using `azurerm_cdn_frontdoor_firewall_policy`, but the validation for anomaly based rule sets is incorrect (e.g. Microsoft_DefaultRuleSet_2.0). Terraform should accept `AnomalyScoring` as a valid action, but it only allows `Allow Log Block Redirect`.

I think the fix is as easy as updating the validator here: https://github.com/hashicorp/terraform-provider-azurerm/blob/de964e86cb80ca3a31246297eaa9a7b51219c587/internal/services/cdn/cdn_frontdoor_firewall_policy_resource.go#L412-L417

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #19088: Override in azurerm_cdn_frontdoor_firewall_policy managed rules when using Microsoft_DefaultRuleSet 2.0 fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.3.3

### AzureRM Provider Version

v3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_firewall_policy

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_firewall_policy" "foobar" {
  name                = "foobar"
  resource_group_name = "foo"
  sku_name            = "Premium_AzureFrontDoor"
  enabled             = true
  mode                = "Detection"

  managed_rule {
    type    = "Microsoft_DefaultRuleSet"
    version = "2.0"
    action  = "Log"
    override {     
      rule_group_name = "PHP"       
      rule {
        rule_id = "933100"
        enabled = false
        action  = "Block"
      }
    }    
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: updating Front Door Firewall Policy: (Front Door Web Application Firewall Policy Name "foobar" / Resource Group "foo"): frontdoor.PoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="WebApplicationFirewallPolicy validation failed. More information \"The configured rule level action is not supported for this managed rule set.\"."
│
│   with azurerm_cdn_frontdoor_firewall_policy.foobar,
│   on fd_cdn.tf line 22, in resource "azurerm_cdn_frontdoor_firewall_policy" "foobar":
│   22: resource "azurerm_cdn_frontdoor_firewall_policy" "foobar" {
│
```

### Expected Behaviour

Deploys and sets the override as expected.  I pulled this code directly from the registry https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_firewall_policy

### Actual Behaviour

Deployment fails when using override. I have tried few different valid overrides and they all fail with the same error.

### Steps to Reproduce

Run the code above, assuming you have a resource group
See the error

### Important Factoids

_No response_

### References

This issue seems to be similar:
https://github.com/hashicorp/terraform-provider-azurerm/issues/18480

### PR DESCRIPTION
**Pull request by WodansSon**
This issue is due to the fact that the API defers the valid `version`/`action` of the `override` by the `type` value (e.g. `DefaultRuleSet` or `Microsoft_DefaultRuleSet`). In version `1.0` and `preview-0.1` (type `DefaultRuleSet`) the accepted actions are [Allow, Block, Log, and Redirect](https://learn.microsoft.com/azure/web-application-firewall/afds/afds-overview#waf-actions), however in `2.0` (type `Microsoft_DefaultRuleSet`) the only valid action is `AnomalyScoring` due to the DRS 2.0 implementing the `OWASP` anomaly score model.

## Example of a DRS 1.X Override:

```hcl
resource "azurerm_cdn_frontdoor_firewall_policy" "example" {
  name                              = "exampleWAF"
  resource_group_name               = azurerm_resource_group.example.name
  sku_name                          = azurerm_cdn_frontdoor_profile.example.sku_name
  enabled                           = true
  mode                              = "Prevention"
  redirect_url                      = "https://www.contoso.com"
  custom_block_response_status_code = 403
  custom_block_response_body        = "PGh0bWw+CjxoZWFkZXI+PHRpdGxlPkhlbGxvPC90aXRsZT48L2hlYWRlcj4KPGJvZHk+CkhlbGxvIHdvcmxkCjwvYm9keT4KPC9odG1sPg=="

  managed_rule {
    type    = "DefaultRuleSet"
    version = "1.0"
    action  = "Log"

    override {     
      rule_group_name = "PHP"

      rule {
        rule_id = "933100"
        enabled = false
        action  = "Block"
      }
    }    
  }
}
```

## Example of a DRS 2.0 Override:

```hcl
resource "azurerm_cdn_frontdoor_firewall_policy" "example" {
  name                              = "exampleWAF"
  resource_group_name               = azurerm_resource_group.example.name
  sku_name                          = azurerm_cdn_frontdoor_profile.example.sku_name
  enabled                           = true
  mode                              = "Prevention"
  redirect_url                      = "https://www.contoso.com"
  custom_block_response_status_code = 403
  custom_block_response_body        = "PGh0bWw+CjxoZWFkZXI+PHRpdGxlPkhlbGxvPC90aXRsZT48L2hlYWRlcj4KPGJvZHk+CkhlbGxvIHdvcmxkCjwvYm9keT4KPC9odG1sPg=="

  managed_rule {
    type    = "Microsoft_DefaultRuleSet"
    version = "2.0"
    action  = "Log"

    override {     
      rule_group_name = "PHP"

      rule {
        rule_id = "933100"
        enabled = false
        action  = "AnomalyScoring"
      }
    }    
  }
}
```

(fixes #18480)
(fixes #19088)

### CODE REVIEW

**Comment by WodansSon** [comment]
image

File: internal/services/cdn/cdn_frontdoor_firewall_policy_resource.go [hunk 1]
```diff
@@ -417,6 +418,7 @@ func resourceCdnFrontDoorFirewallPolicy() *pluginsdk.Resource {
 														string(frontdoor.ActionTypeLog),
 														string(frontdoor.ActionTypeBlock),
 														string(frontdoor.ActionTypeRedirect),
+														"AnomalyScoring", // Only valid with 2.0 and above
```
Comment (katbyte) [inline internal/services/cdn/cdn_frontdoor_firewall_policy_resource.go:421]: We should make sure this exists in swagger & if not open an issue to ensure it is added in future SDKs

**Review by katbyte — APPROVED** [review]
LGTM with 1 comment 🚪

File: internal/services/cdn/cdn_frontdoor_firewall_policy_resource.go (hunk 1 above)
Comment (WodansSon) [reply internal/services/cdn/cdn_frontdoor_firewall_policy_resource.go:421]: Opened [issue](https://github.com/Azure/azure-rest-api-specs/issues/21435)
