### PR TITLE
`azurerm_data_fatory_trigger_schedule` - Fix `schedule` for `frequency = "Month/Week"`

### LINKED ISSUE #14384: Terraform Azure Data Factory Trigger Schedule - Error When Using Activated With Schedule Block
I've created a new datafactory pipeline trigger meant to invoke every 5th of the month at 13:00 UTC using Terraform. This was achieved using **_azurerm_data_factory_trigger_schedule_** resource key.

However, as the trigger Status doesn't automatically get set to Started on deploy, I used the **_activated_** property in an attempt to set it. This is following the updates made on this PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/13390

However, adding _activated_ causes an error on deployment.

The Terraform script I'm using is as follows:

```
resource "azurerm_data_factory_trigger_schedule" "pipeline_trigger" {
  name                = "Pipeline_MonthlyTrigger"
  data_factory_name   = "dataFactoryName"
  resource_group_name = "resourceGroupName"
  pipeline_name       = "pipelineName"

  frequency           = "Month"
  interval            = 1

  activated           = true

  schedule  {
    days_of_month     = [4]
    hours             = [13]
    minutes           = [0]
  }
}
```

The error that comes up on deployment:

> The recurrence schedule of trigger could not have 'WeekDays' for recurrence frequency 'Month'." Target="Pipeline_MonthlyTrigger"

I raised [a similar question on Stackoverflow](https://stackoverflow.com/questions/70148972/terraform-azure-data-factory-trigger-schedule-error-when-using-activated-with) and was told that this is most likely a bug on the newly added support for _activated_ clashing with _schedule_ block.

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #14384

## Acceptance tests
- [x] Passing
Screenshot 2021-11-30 at 11 39 08

## Extra
- [x] Fix for `start_time`, the fallback when `start_time` was empty produced an invalid time value

### CODE REVIEW

File: internal/services/datafactory/data_factory_trigger_schedule_resource.go [hunk 1]
```diff
@@ -138,8 +138,6 @@ func resourceDataFactoryTriggerSchedule() *pluginsdk.Resource {
 			},
 
 			// This time can only be  represented in UTC.
-			// An issue has been filed in the SDK for the timezone attribute that doesn't seem to work
-			// https://github.com/Azure/azure-sdk-for-go/issues/6244
```
Comment (katbyte) [inline internal/services/datafactory/data_factory_trigger_schedule_resource.go:142]: could we leave this in for future context?

File: internal/services/datafactory/data_factory_trigger_schedule_resource.go [hunk 2]
```diff
@@ -149,8 +147,6 @@ func resourceDataFactoryTriggerSchedule() *pluginsdk.Resource {
...
```
Comment (katbyte) [inline internal/services/datafactory/data_factory_trigger_schedule_resource.go:153]: could we leave this in for future context?

**Review by katbyte — CHANGES_REQUESTED** [review]
Aside from 1 comment LGTM @aristosvo

**Review by katbyte — APPROVED** [review]
Thanks @aristosvo - LGTM 🌿
