### PR TITLE
`azurerm_private_endpoint` - add `member_name` property of `ip_configuration` block, support multiple `ip_configuration` blocks.

### LINKED ISSUE #18443: Azure Private Endpoint with ip_configuration for a Key Vault fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_private_endpoint" "this" {
  name                = "pe-private-endpoint-test"
  location            = "northeurope"
  resource_group_name = "rg-test"
  subnet_id           = "<subnet-ID>"

  private_service_connection {
    name                           = "pe-private-endpoint-test-privateserviceconnection"
    private_connection_resource_id = "<key-vault-resource-id>"
    is_manual_connection           = false
    subresource_names              = ["vault"]
  }

  ip_configuration {
    name                = "pe-private-endpoint-test-ip-configuration"
    private_ip_address  = "xxx.xxx.xxx.xxx"
    subresource_name    = "vault"
  }
}
```

### Debug Output/Panic Output

```shell
Private Endpoint /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/<resource-group-name>/providers/Microsoft.Network/privateEndpoints/<key-vault-name> contains static ipconfigurations: [PrivateIPAddress: xxx.xxx.xxx.xxx, GroupId: vault, MemberName: vault] and its missing these membernames/groupids requested by Private Link service [GroupId: vault, MemberName: default]. Private Endpoint needs to be reconfigured with missing memberNames.
```

### Expected Behaviour

One should be able to define the member name of the IP configuration (which has to be `vault` for key vaults, I guess).

### Actual Behaviour

`subresource_name` is used for `group_id` AND `member_name` (I suppose this is the problem).

By the way: The problem does not apply for private endpoints connected to e.g. Storage Accounts, App Configurations and Azure Data Factories, with ip_configuration. There it works just fine.

### Steps to Reproduce

terraform init
terraform plan # will work
terraform apply # ARM returns error

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #19293: Cant assign multiple static ip addresses for Recovery Vault Services Private Endpoint
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
variable "test_ip_addresses" {
    type = map
    description = "IP Addresses"
    default = {
        "test1PrivateEndpointNIC"     = "192.168.1.20"
        "test2PrivateEndpointNIC"     = "192.168.1.21"
        "test3PrivateEndpointNIC"     = "192.168.1.22"
        "test4PrivateEndpointNIC"     = "192.168.1.23"
        "test5PrivateEndpointNIC"     = "192.168.1.24"
        "test6PrivateEndpointNIC"     = "192.168.1.25"
        "test7PrivateEndpointNIC"     = "192.168.1.26"
        "test8PrivateEndpointNIC"     = "192.168.1.27"
        "test9PrivateEndpointNIC"     = "192.168.1.28"
        "test10PrivateEndpointNIC"    = "192.168.1.29"
}

resource "azurerm_private_endpoint" "test_private_endpoint1" {
    name                                = "private-endpoint-backups-mytestsubscription"
    location                            = azurerm_resource_group.test_network_resource_group1.location
    resource_group_name                 = azurerm_resource_group.test_network_resource_group1.name
    subnet_id                           = azurerm_subnet.test_private_endpoint_subnet1.id
    custom_network_interface_name       = "nic-private-endpoint-backups-mytestsubscription"

    ip_configuration {
        name                            = "backup-ecs1"
        private_ip_address              = var.test_ip_addresses["test1PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"
    
        name                            = "backup-rec2"
        private_ip_address              = var.test_ip_addresses["test2PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"

        name                            = "backup-prot1b"
        private_ip_address              = var.test_ip_addresses["test3PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"

        name                            = "backup-id1"
        private_ip_address              = var.test_ip_addresses["test4PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"
  
        name                            = "backup-prot1c"
        private_ip_address              = var.test_ip_addresses["test5PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"
 
        name                            = "backup-wbcm1"
        private_ip_address              = var.test_ip_addresses["test6PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"

        name                            = "backup-fab1"
        private_ip_address              = var.test_ip_addresses["test7PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"
 
        name                            = "backup-fc1"
        private_ip_address              = var.test_ip_addresses["test8PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"

        name                            = "backup-prot1"
        private_ip_address              = var.test_ip_addresses["test9PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"

        name                            = "backup-tel1"
        private_ip_address              = var.test_ip_addresses["test10PrivateEndpointNIC"]
        subresource_name                = "AzureBackup"
    }

    private_service_connection {
        name                            = "private-connection-backups-mytestsubscription"
        private_connection_resource_id  = data.azurerm_recovery_services_vault.backup_vault1.id 
        subresource_names               = ["AzureBackup"]  
        is_manual_connection            = true
        request_message                 = "Private link request created by Terraform" 
    }


}
```

### Debug Output/Panic Output

```shell
The argument "name" was already set. Each argument may be set only once.
╷
│ Error: Attribute redefined


│ The argument "private_ip_address" was already set. Each argument may be set only once.
╵
╷
│ Error: Attribute redefined
│

│ The argument "subresource_name" was already set. Each argument may be set only once.
```

### Expected Behaviour

_No response_

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

Create a new Azure Recovery Vault Service in Azure Portal
Set the network access to private only
Create a new private link in the Recovery vault networking section produces the following template which I cant reproduce in Terraform:

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "location": {
            "type": "string"
        },
        "privateEndpointName": {
            "type": "string"
        },
        "privateLinkResource": {
            "type": "string"
        },
        "targetSubResource": {
            "type": "array"
        },
        "requestMessage": {
            "type": "string"
        },
        "subnet": {
            "type": "string"
        },
        "virtualNetworkId": {
            "type": "string"
        },
        "virtualNetworkResourceGroup": {
            "type": "string"
        },
        "subnetDeploymentName": {
            "type": "string"
        }
    },
    "resources": [
        {
            "location": "[parameters('location')]",
            "name": "[parameters('privateEndpointName')]",
            "type": "Microsoft.Network/privateEndpoints",
            "apiVersion": "2021-05-01",
            "properties": {
                "subnet": {
                    "id": "[parameters('subnet')]"
                },
                "ipConfigurations": [
                    {
                        "name": "backup-ecs1",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-ecs1",
                            "privateIPAddress": "192.168.1.20"
                        }
                    },
                    {
                        "name": "backup-rec2",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-rec2",
                            "privateIPAddress": "192.168.1.21"
                        }
                    },
                    {
                        "name": "backup-prot1b",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-prot1b",
                            "privateIPAddress": "192.168.1.22"
                        }
                    },
                    {
                        "name": "backup-id1",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-id1",
                            "privateIPAddress": "192.168.1.23"
                        }
                    },
                    {
                        "name": "backup-prot1c",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-prot1c",
                            "privateIPAddress": "192.168.1.24"
                        }
                    },
                    {
                        "name": "backup-wbcm1",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-wbcm1",
                            "privateIPAddress": "192.168.1.25"
                        }
                    },
                    {
                        "name": "backup-fab1",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-fab1",
                            "privateIPAddress": "192.168.1.26"
                        }
                    },
                    {
                        "name": "backup-fc1",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-fc1",
                            "privateIPAddress": "192.168.1.27"
                        }
                    },
                    {
                        "name": "backup-prot1",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-prot1",
                            "privateIPAddress": "192.168.1.28"
                        }
                    },
                    {
                        "name": "backup-tel1",
                        "properties": {
                            "groupId": "AzureBackup",
                            "memberName": "backup-tel1",
                            "privateIPAddress": "192.168.1.29"
                        }
                    }
                ],
                "customNetworkInterfaceName": "test-nic",
                "privateLinkServiceConnections": [
                    {
                        "name": "[parameters('privateEndpointName')]",
                        "properties": {
                            "privateLinkServiceId": "[parameters('privateLinkResource')]",
                            "groupIds": "[parameters('targetSubResource')]"
                        }
                    }
                ]
            },
            "tags": {},
            "dependsOn": []
        }
    ]
}

### PR DESCRIPTION
**Pull request by ziyeqf**
fix #19293
fix #18443

CI failed due to a lock on subnet used on delete function added #16315, and it cannot be resolved for now.

Screenshot 2022-11-22 at 16 12 04

### CODE REVIEW

File: internal/services/network/private_endpoint_resource.go [hunk 1]
```diff
@@ -196,6 +195,13 @@ func resourcePrivateEndpoint() *pluginsdk.Resource {
 							ForceNew:     true,
 							ValidateFunc: validation.StringIsNotEmpty,
 						},
+						"member_name": { // TODO: set to Required, remove Computed in v4.0
```
Comment (katbyte) [inline internal/services/network/private_endpoint_resource.go:198]: could we make this change now and put it behind the 4.0 flag instead of a todo please? thanks

**Review by katbyte — CHANGES_REQUESTED** [review]

**Review by katbyte — APPROVED** [review]
thanks @ziyeqf - LGTM 🦘
