### PR TITLE
`azurerm_security_center_setting` - fix a bug when name `SENTINEL`

### LINKED ISSUE #24438: `azurerm_security_center_setting` - SENTINEL is not valid anymore for `setting_name`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_security_center_setting

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_setting" "main" {
  setting_name = "SENTINEL"
  enabled      = true
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/XXXXXX-XXXX-XXXX/providers/Microsoft.Security/settings/SENTINEL": parsing segment "settingName": expected the segment "settingName" to match one of the values "MCAS, Sentinel, WDATP, WDATP_EXCLUDE_LINUX_PUBLIC_PREVIEW, WDATP_UNIFIED_SOLUTION" but got "SENTINEL"
Operation failed: failed running terraform plan (exit 1)
```

### Expected Behaviour

Terraform plans should run without errors and update the value of `name_setting` to the new case.

### Actual Behaviour

We upgraded from provider version 3.83.0 to 3.86.0 and all Terraform plans fail. The casing of the option `setting_name` was changed in provider version 3.85.0 and does not accept the old value anymore. Therefore all Terraform runs fail during the plan stage making all changes to update to the new value `Sentinel` impossible.

### Steps to Reproduce

1. `terraform apply` using provider version 3.83.0
2. upgrade provider to 3.86.0
3. Optional: Change `setting_name` to new value `Sentinel`
4. `terraform apply` using new provider version

### Important Factoids

_No response_

### References

- https://github.com/hashicorp/terraform-provider-azurerm/pull/24210

### PR DESCRIPTION
**Pull request by ziyeqf**
fix #24438

Test
---
image

### CODE REVIEW

File: internal/services/securitycenter/migration/security_center_settings_v0_to_v1.go [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+	return func(ctx context.Context, rawState map[string]interface{}, meta interface{}) (map[string]interface{}, error) {
+		log.Println("[DEBUG] Migrating Security Center Settings from v0 to v1 format")
+		oldId := rawState["id"].(string)
+		// only find the last one
+		idx := strings.LastIndex(oldId, "/SENTINEL")
+		newId := oldId[:idx] + "/Sentinel"
+
+		log.Printf("[DEBUG] Updating ID from %q to %q", oldId, newId)
+
+		rawState["id"] = newId
```
Comment (stephybun) [inline internal/services/securitycenter/migration/security_center_settings_v0_to_v1.go:41]: This will crash on security settings with other setting names since `strings.LastIndex` will return `-1` if it isn't `SENTINEL`. I think a safer way to do this would be like below 
```suggestion
		oldId := strings.Split(rawState["id"].(string), "/")
		// recase the last index if it's `SENTINEL`
		if oldId[len(oldId)-1] == "SENTINEL" {
			oldId[len(oldId)-1] = "Sentinel"
		}
		newId := strings.Join(oldId, "/")

		log.Printf("[DEBUG] Updating ID from %q to %q", oldId, newId)

		rawState["id"] = newId
```

File: internal/services/securitycenter/security_center_setting_resource_test.go [hunk 2]
```diff
@@ -33,7 +34,7 @@ func testAccSecurityCenterSetting_update(t *testing.T) {
 	r := SecurityCenterSettingResource{}
 
 	// lintignore:AT001
-	data.ResourceSequentialTest(t, r, []acceptance.TestStep{
+	testcases := []acceptance.TestStep{
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_setting_resource_test.go:37]: Which means we can undo all of these changes as well

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @ziyeqf. I left some comments in-line, could you please look over them?

**Comment by jackofallops** [comment]
Hi @ziyeqf - Looks like we now have a failure in the tests:
```
=== RUN   TestAccSecurityCenterSetting/setting/update
    testcase.go:120: Step 9/14 error: Error running apply: exit status 1
        Error: A resource with the ID "/subscriptions/*******/providers/Microsoft.Security/settings/Sentinel" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_security_center_setting" for more information.
          with azurerm_security_center_setting.test,
          on terraform_plugin_test.tf line 21, in resource "azurerm_security_center_setting" "test":
          21: resource "azurerm_security_center_setting" "test" {
=== RUN   TestAccSecurityCenterSetting/setting/requiresImport
--- FAIL: TestAccSecurityCenterSetting (121.48s)
```

Could you take a look? 

Thanks!

**Comment by ziyeqf** [comment]
Sorry for my carelessness, it passes now.
```
❯❯ tftest securitycenter TestAccSecurityCenterSetting
=== RUN   TestAccSecurityCenterSetting
=== RUN   TestAccSecurityCenterSetting/setting
=== RUN   TestAccSecurityCenterSetting/setting/update
=== RUN   TestAccSecurityCenterSetting/setting/requiresImport
--- PASS: TestAccSecurityCenterSetting (166.13s)
    --- PASS: TestAccSecurityCenterSetting/setting (166.13s)
        --- PASS: TestAccSecurityCenterSetting/setting/update (134.38s)
        --- PASS: TestAccSecurityCenterSetting/setting/requiresImport (31.75s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/securitycenter	166.192s
```

**Review by katbyte — APPROVED** [review]
LGTM 🚜
