### PR TITLE
`azurerm_linux_web_app_slot` `azurerm_linux_web_app` -  Add length check to avoid potential index out of range panic

### LINKED ISSUE #21324: auto heal setting of liunx web app error out with provider crash while creating through terraform
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "linux_web_app" {
  name                = "unitappservice"
  location            = "canadacentral"
  resource_group_name = "unittestrg"
  identity = {
    type = "SystemAssigned"
  }
   site_config = {
    minimum_tls_version = "1.2"
    auto_heal_enabled = true
    auto_heal_setting = {
      action = {
        action_type = "Recycle"
      }
      trigger = {
        slow_request = [{
          count    = 7
          interval = "12:25:10"
        }]
      }
    }
```

### Debug Output/Panic Output
https://gist.github.com/amaniommi39/3b44c7e960777a912f4617e91e64ec37
```shell
Error: The terraform-provider-azurerm_v3.48.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

auto heal setting should be applied on linux web app being created

### Actual Behaviour

Error: Request cancelled
│ 
│   with module.linux_web_app.azurerm_linux_web_app.linux_web_app,
│   on ../../../../web/linux_web_app/v1/linux_web_app_main.tf line 44, in resource "azurerm_linux_web_app" "linux_web_app":
│   44: resource "azurerm_linux_web_app" "linux_web_app" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-azurerm_v3.48.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

### Steps to Reproduce

run terraform init && terraform plan
run terraform apply

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by lonegunmanb**
This patch added slice length for optional list field to avoid potential index out range panic. It should fix #21324.

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🔱

File: internal/services/appservice/helpers/linux_web_app_schema.go [hunk 1]
```diff
@@ -968,6 +968,16 @@ func expandAutoHealSettingsLinux(autoHealSettings []AutoHealSettingLinux) *web.A
...
+		result.Actions.ActionType = web.AutoHealActionType(action.ActionType)
+		result.Actions.MinProcessExecutionTime = pointer.To(action.MinimumProcessTime)
+	}
+
+	if len(autoHeal.Triggers) == 0 {
+		return result
+	}
+
 	triggers := autoHeal.Triggers[0]
 	if len(triggers.Requests) == 1 {
```
Comment (katbyte) [inline internal/services/appservice/helpers/linux_web_app_schema.go:982]: actually instead of returning early here can we wrap the code instead?
```suggestion
	if len(autoHeal.Triggers) == 0 {

		triggers := autoHeal.Triggers[0]
		if len(triggers.Requests) == 1 {
```

**Review by katbyte — CHANGES_REQUESTED** [review]

File: internal/services/appservice/helpers/linux_web_app_schema.go (hunk 1 above)
Comment (lonegunmanb) [reply internal/services/appservice/helpers/linux_web_app_schema.go:982]: Hi @katbyte, I'm not sure that I got your point, since line 977 `len(autoHeal.Triggers) == 0`, line 979 `autoHeal.Triggers[0]` would trigger an index out of range panic right? Do you mean `if len(autoHeal.Triggers) == 1 {` for line 977?

I personal prefer return early style to reduce nested blocks' depth and avoid [arrow code](https://blog.codinghorror.com/flattening-arrow-code/), but this is HashiCorp's project so I would be happy to follow your guidance.

**Review by jackofallops — COMMENTED** [review]
Hi @lonegunmanb - both of these are `Required` properties, so are not the cause of the panic in the reported issue.  The crash is actually pointing here: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/helpers/linux_web_app_schema.go#L990
suggesting that `len()` isn't handling the nil for us, so should be nil checked before checking length.

Can you take a look and update as necessary? 

Thanks!

**Comment by lonegunmanb** [comment]
> Hi @lonegunmanb - both of these are `Required` properties, so are not the cause of the panic in the reported issue. The crash is actually pointing here: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/helpers/linux_web_app_schema.go#L990 suggesting that `len()` isn't handling the nil for us, so should be nil checked before checking length.
> 
> Can you take a look and update as necessary?
> 
> Thanks!

Hi @jackofallops thanks for the catch, before I work for the patch as you suggested I have a question. As #21324 [described](https://gist.github.com/amaniommi39/3b44c7e960777a912f4617e91e64ec37#file-gistfile1-txt-L4):

>Error: The terraform-provider-azurerm_v3.48.0_x5 plugin crashed!

So I just checked [`linux_web_app_schema.go:990`](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.48.0/internal/services/appservice/helpers/linux_web_app_schema.go#L990) in v3.48.0:

```go
triggers := autoHeal.Triggers[0]
```

Are you sure that we should make the patch base on the current codebase? Thanks.

**Comment by jackofallops** [comment]
> > Hi @lonegunmanb - both of these are `Required` properties, so are not the cause of the panic in the reported issue. The crash is actually pointing here: [`main`/internal/services/appservice/helpers/linux_web_app_schema.go#L990](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/helpers/linux_web_app_schema.go?rgh-link-date=2023-04-19T14%3A56%3A48Z#L990) suggesting that `len()` isn't handling the nil for us, so should be nil checked before checking length.
> > Can you take a look and update as necessary?
> > Thanks!
> 
> Hi @jackofallops thanks for the catch, before I work for the patch as you suggested I have a question. As #21324 [described](https://gist.github.com/amaniommi39/3b44c7e960777a912f4617e91e64ec37#file-gistfile1-txt-L4):
> 
> > Error: The terraform-provider-azurerm_v3.48.0_x5 plugin crashed!
> 
> So I just checked [`linux_web_app_schema.go:990`](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.48.0/internal/services/appservice/helpers/linux_web_app_schema.go?rgh-link-date=2023-04-19T14%3A56%3A48Z#L990) in v3.48.0:
> 
> ```go
> triggers := autoHeal.Triggers[0]
> ```
> 
> Are you sure that we should make the patch base on the current codebase? Thanks.

@lonegunmanb - Sorry. My mistake, I think I must have conflated the `windows` schema here. Having checked out the 3.48 tag I can see you changes do appear to be correct.  I'll re-review shortly and get the tests run.

**Review by jackofallops — APPROVED** [review]
LGTM 👍
