### PR TITLE
`azurerm_app_service_certificate` - add `key_vault_id` property to support referring to Key Vault in different Subscription

### LINKED ISSUE #14611: azurerm_app_service_certificate - Unable to determine the Resource ID for the Key Vault at URL
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: v1.1.0
Azurerm: v2.89.0

### Affected Resource(s)
* azurerm_app_service_certificate

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

provider "azurerm" {
  alias           = "subscription1"
  subscription_id = var.subscription_id_1
  features {}
}

# Resource Group (Subscription 1)
data "azurerm_resource_group" "subscription1" {
  name     = "rg-subscription1"
  provider = azurerm.subscription1
}

# Resource Group (Subscription 2)
data "azurerm_resource_group" "subscription2" {
  name     = "rg-subscription2"
}

# Key Vault (Subscription 1)
data "azurerm_key_vault" "subscription1" {
  name                = "kv_subscription1"
  resource_group_name = data.azurerm_resource_group.subscription1.name
  provider            = azurerm.subscription1
}

# SSL Certificate (Subscription 1)
data "azurerm_key_vault_certificate" "subscription1" {
  name         = "cert"
  key_vault_id = data.azurerm_key_vault.subscription1.id
  provider     = azurerm.subscription1
}

# Access Policy to App Service in subscription 2 on Key Vault in subscription 1
resource "azurerm_key_vault_access_policy" "app_service_in_subscription_2" {
  key_vault_id = data.azurerm_key_vault.subscription1.id
  tenant_id    = data.azurerm_client_config.this.tenant_id
  object_id    = azurerm_app_service.subscription2.identity[0].principal_id

  key_permissions         = []
  certificate_permissions = ["Get"]
  secret_permissions      = ["Get"]
  storage_permissions     = []

  provider = azurerm.subscription1
}

# SSL Certificate for App Service (Subscription 2)
resource "azurerm_app_service_certificate" "subscription2" {
  name                = "cert"
  resource_group_name = data.azurerm_resource_group.subscription2.name
  location            = data.azurerm_resource_group.subscription2.location

  key_vault_secret_id = data.azurerm_key_vault_certificate.subscription1.secret_id

  depends_on = [azurerm_key_vault_access_policy.app_service_in_subscription_2]

  # provider = azurerm.subscription1 -> Tested both commented and uncommented
}

# SSL Certificate Binding to Custom Domain (Subscription 2)
resource "azurerm_app_service_certificate_binding" "subscription2" {
  hostname_binding_id = azurerm_app_service_custom_hostname_binding.subscription2.id
  certificate_id      = azurerm_app_service_certificate.subscription2.id
  ssl_state           = "SniEnabled"
}
```

### Debug Output

The issue is due to `azurerm_app_service_certificate`. Since the corresponding key vault and the certificate in that key vault are in "Subscription 1" and the app service is in the "Subscription 2", two providers are required to detect the resources.

When the provider for the "Subscription 2" is used (which for me seems to be right one), the Terraform cannot find the key vault "Subscription 1" and the following error is prompted:
-> Unable to determine the Resource ID for the Key Vault at URL <url_of_the_key_vault>

When the provider for the "Subscription 1" is used, the Terraform cannot find the resource group in the "Subscription 2" and the following error is prompted:
-> StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'rg-subscription2' could not be found."

### Expected Behaviour

The secret ID of the certificate in the "Subscription 1" should have been retrieved and assigned to the app service certificate in the "Subscription 2" successfully.

When I have tried to create the `azurerm_app_service_certificate` with a certificate in a key vault which is in the same subscription, everything worked perfectly.

### Actual Behaviour

Terraform can access the certificate in a key vault in "Subscription 1" and can grab its secret ID. However it cannot assign it to the app service in "Subscription 2".

### PR DESCRIPTION
**Pull request by teowa**
resolves #14611 
to support refer to Key Vault Certificate in different Subscription

```
TF_ACC=1 go test -v ./internal/services/web -parallel 20 -run TestAccAppServiceCertificate_KeyVaultId -timeout 2h -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAppServiceCertificate_KeyVaultIdUpdate
=== PAUSE TestAccAppServiceCertificate_KeyVaultIdUpdate
=== RUN   TestAccAppServiceCertificate_KeyVaultId
=== PAUSE TestAccAppServiceCertificate_KeyVaultId
=== CONT  TestAccAppServiceCertificate_KeyVaultIdUpdate
=== CONT  TestAccAppServiceCertificate_KeyVaultId
--- PASS: TestAccAppServiceCertificate_KeyVaultId (319.97s)
--- PASS: TestAccAppServiceCertificate_KeyVaultIdUpdate (341.09s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/web   341.114s
```
<details>

<summary>tf config to test `azurerm_app_service_certificate` refer to kv in different sub</summary>

```hcl
provider "azurerm" {
  alias           = "sub2"
  subscription_id = "00000000-0000-0000-0000-000000000000"
  features {}
}
provider "azurerm" {
  features {}
}

provider "azuread" {}

data "azurerm_client_config" "test" {}

data "azuread_service_principal" "test" {
  display_name = "Microsoft Azure App Service"
}

resource "azurerm_resource_group" "test" {
  name     = "acctestwebcert"
  location = "westus"
}

resource "azurerm_key_vault" "test" {
  name                = "wtaaghavhsdw"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  tenant_id = data.azurerm_client_config.test.tenant_id

  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.test.tenant_id
    object_id = data.azurerm_client_config.test.object_id

    secret_permissions = [
      "Delete",
      "Get",
      "Purge",
      "Set",
    ]

    certificate_permissions = [
      "Create",
      "Delete",
      "Get",
      "Purge",
      "Import",
    ]
  }

  access_policy {
    tenant_id = data.azurerm_client_config.test.tenant_id
    object_id = data.azuread_service_principal.test.object_id

    secret_permissions = [
      "Get",
    ]

    certificate_permissions = [
      "Get",
    ]
  }
}

resource "azurerm_key_vault_certificate" "test" {
  name         = "acctes840293t"
  key_vault_id = azurerm_key_vault.test.id

  certificate {
    contents = filebase64("testdata/app_service_certificate.pfx")
    password = "terraform"
  }

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }
}

resource "azurerm_resource_group" "test2" {
  provider = azurerm.sub2
  name     = "acctestwebcert2"
  location = "westus"
}

resource "azurerm_app_service_certificate" "test" {
  provider              = azurerm.sub2
  name                  = "acctestn12391264"
  resource_group_name   = azurerm_resource_group.test2.name
  location              = azurerm_resource_group.test2.location
  key_vault_id          = azurerm_key_vault.test.id
  key_vault_secret_name = azurerm_key_vault_certificate.test.name
}
```

</details>

### CODE REVIEW

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @teowa - Thanks for this PR. 

I think we need a slightly different approach here for Terraform to function correctly and not change the behaviour.  I think we need to keep `key_vault_secret_id ` and introduce an `Optional` and `ForceNew` property of `key_vault_id` to allow users to be explicit about the KV to be used. When present, we can skip the call to `keyVaultsClient.KeyVaultIDFromBaseUrl` as we'll have the ID already, and we can extract the secret name from the secret ID as usual.  This will mean that changes to the secret in use will be detectable by Terraform and allow us to make changes appropriately. WDYT?

File: internal/services/web/app_service_certificate_resource.go [hunk 1]
```diff
@@ -298,4 +295,56 @@ func resourceAppServiceCertificateSchema() map[string]*pluginsdk.Schema {
...
+			ConflictsWith: []string{"password"},
+			RequiredWith:  []string{"key_vault_secret_name"},
+		}
+
+		schema["key_vault_secret_name"] = &pluginsdk.Schema{
+			Type:         pluginsdk.TypeString,
+			Optional:     true,
+			ValidateFunc: keyVaultValidate.NestedItemName,
+			RequiredWith: []string{"key_vault_id"},
+		}
```
[the remark this answers is not in the document]
Comment (jackofallops) [reply internal/services/web/app_service_certificate_resource.go:324]: Ignore this, forgot to remove it from the review before posting the alternative approach.

File: internal/services/web/app_service_certificate_resource.go [hunk 2]
```diff
@@ -238,13 +240,22 @@ func resourceAppServiceCertificateSchema() map[string]*pluginsdk.Schema {
 			ValidateFunc: validation.NoZeroValues,
 		},
 
+		"key_vault_id": {
+			Type:         pluginsdk.TypeString,
+			Optional:     true,
+			ForceNew:     true,
+			ValidateFunc: commonids.ValidateKeyVaultID,
+			RequiredWith: []string{"key_vault_secret_id"},
```
Comment (stephybun) [inline internal/services/web/app_service_certificate_resource.go:248]: If we set this then `key_vault_id` will always need to be set even if users are using a secret from a key vault in the same subscription, this could also constitute a breaking change so this should probably be removed.
```suggestion
```

File: website/docs/r/app_service_certificate.html.markdown [hunk 3]
```diff
@@ -60,6 +62,10 @@ data "azuread_service_principal" "MicrosoftWebApp" {
 }
 ```
 
+* `key_vault_id` - (Optional) The ID of the Key Vault. Must be specified if Key Vault of `key_vault_secret_id` is in different subscription from the App Service Certificate. Changing this forces a new resource to be created.
```
Comment (stephybun) [inline website/docs/r/app_service_certificate.html.markdown:65]:
```suggestion
* `key_vault_id` - (Optional) The ID of the Key Vault. Must be specified if the Key Vault of `key_vault_secret_id` is in a different subscription from the App Service Certificate. Changing this forces a new resource to be created.
```

File: website/docs/r/app_service_certificate.html.markdown [hunk 4]
```diff
@@ -60,6 +62,10 @@ data "azuread_service_principal" "MicrosoftWebApp" {
...
+
+-> **NOTE:** `key_vault_id` must be specified with `key_vault_secret_id`.
```
Comment (stephybun) [inline website/docs/r/app_service_certificate.html.markdown:67]: This shouldn't be, and doesn't need to be a requirement
```suggestion
```

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for making those changes @teowa. I think there is still bit of tweaking that needs to happen here to fulfill the suggestion that @jackofallops made in his initial review. Could you please take a look at the comments I left in-line?

File: internal/services/web/app_service_certificate_resource.go (hunk 2 above)
Comment (teowa) [reply internal/services/web/app_service_certificate_resource.go:248]: The `RequiredWith: []string{"key_vault_secret_id"},` is to limit the `key_vault_id` can only be set if `key_vault_secret_id` has been set. Otherwise it has no meaning if only `key_vault_id` is set. 

By test `TestAccAppServiceCertificate_KeyVault`, if `key_vault_id` is not specified, there won't be validation error.

File: website/docs/r/app_service_certificate.html.markdown (hunk 4 above)
Comment (teowa) [reply website/docs/r/app_service_certificate.html.markdown]: changed to 
```
-> **NOTE:** `key_vault_id` can only be specified if `key_vault_secret_id` has been set.
```

**Review by stephybun — APPROVED** [review]
Thanks @teowa LGTM 👍
