### PR TITLE
`vmss` - support specifying `ultra_ssd_disk_iops_read_write` and `ultra_ssd_disk_mbps_read_write` for `PremiumV2_LRS`

### LINKED ISSUE #21108: `PremiumV2_LRS` data disks attached to linux scale set VMs don't allow configuration of IOPs and MBps
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.48.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "gitlab_runners_linux" {
    name = "${local.name_prefix}-scaleset"
    resource_group_name = azurerm_resource_group.gitlab_runners_linux.name
    location = azurerm_resource_group.gitlab_runners_linux.location
    sku = var.linux_vm_type
    instances = var.initial_linux_instances
    admin_username = "admin"
    zones = ["1"]

    source_image_id = var.linux_image_id

    os_disk {
        storage_account_type = "Premium_LRS"
        caching = "ReadWrite"
        disk_size_gb = "${var.os_disk_size_gb}"
    }

    additional_capabilities {
        ultra_ssd_enabled = false
    }

    data_disk {
        caching = "None"
        disk_size_gb = 128
        storage_account_type = "PremiumV2_LRS"
        lun = 1

        disk_iops_read_write = 7500
        disk_mbps_read_write = 500
    }
    

    admin_ssh_key {
        username = "admin"
        public_key = tls_private_key.gitlab_runners_linux_key.public_key_openssh
    }

    network_interface {
        name = "${local.name_prefix}-scaleset-nic"
        primary = true

        ip_configuration {
            name = "${local.name_prefix}-scaleset-ipconfig-internal"
            primary = true
            subnet_id = azurerm_subnet.gitlab_runners_linux_internal.id
        }
    }

    custom_data = data.cloudinit_config.gitlab_runners_linux_config.rendered

    lifecycle {
        ignore_changes = [instances]
        replace_triggered_by = [null_resource.linux_image_id, null_resource.gitlab_runners_linux_config]
    }
}
```

### Debug Output/Panic Output

```shell
Error: Unsupported argument
│ 
│   on modules/azure-gitlab-runners-linux/main.tf line 136, in resource "azurerm_linux_virtual_machine_scale_set" "gitlab_runners_linux":
│  136:         disk_iops_read_write = 7500
│ 
│ An argument named "disk_iops_read_write" is not expected here.
╵
╷
 Error: Unsupported argument
│ 
│   on modules/azure-gitlab-runners-linux/main.tf line 137, in resource "azurerm_linux_virtual_machine_scale_set" "gitlab_runners_linux":
│  137:         disk_mbps_read_write = 500
│ 
│ An argument named "disk_mbps_read_write" is not expected here.
╵
```

### Expected Behaviour

According to #18991 , this behavior was developed and merged in when creating a managed disk of type `PremiumV2_LRS`. `disk_iops_read_write` and `disk_mbps_read_write` are configurable. It is expected that when creating this same disk type attached to a VM in a linux scale set, these same configuration options would be present.

### Actual Behaviour

`disk_iops_read_write` and `disk_mbps_read_write` are not valid options for a `data_disk` block with type `PremiumV2_LRS` on to a VM that is part of a linux scale set.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

_No response_

### References

Issue regarding same problem with managed disks that has been fixed: #18977
Relevant pull request: #18991

Thanks!

### PR DESCRIPTION
**Pull request by myc2h6o**
Close #21108
- Add comments for renaming `ultra_ssd_disk_[io|mb]ps_read_write` to `disk_[io|mb]ps_read_write` in 4.0 since these are now supported for not only ultra ssd but also `PremiumV2_LRS`
- Added validation for these properties to allow a minimum value of `1`, which is taken from https://learn.microsoft.com/azure/virtual-machines/disks-types#ultra-disk-throughput and [`managed_disk`](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/managed_disk_resource.go#L174)

### CODE REVIEW

File: internal/services/compute/orchestrated_virtual_machine_scale_set.go [hunk 1]
```diff
@@ -549,20 +550,40 @@ func OrchestratedVirtualMachineScaleSetDataDiskSchema() *pluginsdk.Schema {
...
+					Optional:     true,
+					ValidateFunc: validation.IntAtLeast(1),
+					Computed:     true,
 				},
 			},
 		},
 	}
+
+	if !features.FourPointOhBeta() {
+		schema.Elem.(*pluginsdk.Resource).Schema["ultra_ssd_disk_iops_read_write"] = &pluginsdk.Schema{
```
Comment (catriona-m) [inline internal/services/compute/orchestrated_virtual_machine_scale_set.go:571]: When we switch to plugin framework this may not work as expected anymore - could we add a TODO to make the rename in 4.0 instead of doing the deprecation? Whilst we would normally recommend doing a deprecation here, this could cause confusion because all four fields are computed.

**Review by catriona-m — CHANGES_REQUESTED** [review]
Hi @myc2h6o thanks for this! I left one comment inline about the deprecation portion of this change - it would be good if we did this in 4.0 rather as a deprecation here. As such, could we rework this to include only the validation change? Thanks!

**Review by catriona-m — APPROVED** [review]
Thanks for updating with these changes @myc2h6o - LGTM!
