### PR TITLE
`azurerm_api_management_api`: add costom poller for `import` openapi

### LINKED ISSUE #22042: Provider ignores APIM error when importing an invalid swagger for the second time
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.59

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Terraform Configuration Files

`swagger1.json` file:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Demo",
    "version": "1.0.0"
  },
  "paths": {
    "/path1": {
      "get": {
        "description": "Description 1",
        "operationId": "operationId1",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/path2": {
      "get": {
        "description": "Description 2",
        "operationId": "operationId2",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```

`swagger2` file:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Demo",
    "version": "1.0.0"
  },
  "paths": {
    "/path1": {
      "get": {
        "description": "Description 1",
        "operationId": "operationId2",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/path2": {
      "get": {
        "description": "Description 2",
        "operationId": "operationId3",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```

Manifests:

```hcl
variable "swagger_file" {
  type        = string
  description = "The swagger file to use to deploy the API."
}

resource "azurerm_api_management_api" "api" {
  name                = "test-apim"
  resource_group_name = "rg"
  api_management_name = "apim-test"
  revision            = "1"
  display_name        = "test"
  path                = "test/test"
  protocols           = ["https"]

  subscription_required = false

  import {
    content_format = "openapi+json"
    content_value  = file(var.swagger_file)
  }
}
```

### Debug Output/Panic Output

Deploy the API with `swagger1.json` for the first time: OK

Deploy the API with `swagger2.json` for the first time:

```console
azurerm_api_management_api.api: Modifying... [id=/subscriptions/XXX/resourceGroups/rg/providers/Microsoft.ApiManagement/service/apim-test/apis/test-apim]
azurerm_api_management_api.api: Still modifying... [id=/subscriptions/XXX-...test/apis/test-apim, 10s elapsed]
...
azurerm_api_management_api.api: Still modifying... [id=/subscriptions/XXX-...test/apis/test-apim, 4m0s elapsed]
╷
│ Error: waiting on creating/updating Api: (Name "test-apim" / Service Name "apim-test" / Resource Group "rg"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=400 -- Original Error: Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"Operation with the same method and URL template already exists: GET, /path1","target":"urlTemplate"},{"code":"ValidationError","message":"Operation with the same method and URL template already exists: GET, /path1","target":"method"}]
│
│   with azurerm_api_management_api.api,
│   on api.tf line 1, in resource "azurerm_api_management_api" "api":
│    1: resource "azurerm_api_management_api" "api" {
│
╵
```

Deploy the API with `swagger2.json` for the second time: OK

### Expected Behaviour

When applying the manifests with `swagger2.json` for the second time, I expect to have the same error as when applying for the first time.

### Actual Behaviour

Actually, when applying the manifests with `swagger2.json` for the second time, there is no error.

However, the error is present when using `az` to deploy the `swagger2.json` for the second time (as expected):

```sh
az apim api import -g "rg" --service-name "apim-test" --path "test/test" --specification-format "OpenApiJson" --api-id "test-api" --specification-path "swagger2.json"
```

Result:

```console
(ValidationError) One or more fields contain incorrect values:
Code: ValidationError
Message: One or more fields contain incorrect values:
Exception Details:	(ValidationError) Operation with the same method and URL template already exists: GET, /path1
	Code: ValidationError
	Message: Operation with the same method and URL template already exists: GET, /path1
	Target: urlTemplate	(ValidationError) Operation with the same method and URL template already exists: GET, /path1
	Code: ValidationError
	Message: Operation with the same method and URL template already exists: GET, /path1
	Target: method
```

### Steps to Reproduce

1. `terraform apply -var swagger_file=swagger1.json` # OK
2. `terraform apply -var swagger_file=swagger2.json` # Get an error (because we are modifying an existing operationId)
3. `terraform apply -var swagger_file=swagger2.json` # OK

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #23322: Unable to create azurerm_api_management_api with imported content file with azurerm > 3.69.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

>3.69.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Terraform Configuration Files

```hcl
data "azurerm_api_management" "apim" {
  name                = var.apim_name
  resource_group_name = var.resource_group_name
}

resource "azurerm_api_management_api" "api" {
  for_each = var.managed_apis

  name                  = var.instance_id != null ? "${each.key}-${var.instance_id}" : each.key
  display_name          = "${each.value.display_name} [${upper(var.env)}]"
  resource_group_name   = data.azurerm_api_management.apim.resource_group_name
  api_management_name   = data.azurerm_api_management.apim.name
  revision              = "current"
  soap_pass_through     = each.value.import_type == "wsdl" ? true : false
  path                  = local.is_shared_service ? "${local.app_context}/${each.value.service_path}" : each.value.service_path
  protocols             = ["https"]
  subscription_required = each.value.subscription_required
  version               = each.value.version != null ? each.value.version : null
  version_set_id        = each.value.version_set != null ? azurerm_api_management_api_version_set.version_set[each.value.version_set].id : null

  dynamic "import" {
    for_each = each.value.api_file == null ? [] : [1]
    content {
      content_format = each.value.import_type
      content_value  = file("${var.paths.apis}/${each.value.api_file}")

      dynamic "wsdl_selector" {
        for_each = each.value.wsdl_selector

        content {
          service_name  = wsdl_selector.value.service_name
          endpoint_name = wsdl_selector.value.endpoint_name
        }
      }
    }
  }
  depends_on = [azurerm_api_management_api_version_set.version_set]
}
```
#### EXAMPLE managed_apis var:
```
managed_apis = {
  "testapi" = {
    display_name = "test"
    service_path = "test"
    import_type  = "openapi"
    // This product id will have to match one of the the product id's in the 
    // Azure Portal in the APIs -> Products section of the APIM.  If you don't
    // see one that matches the project your API is for then reach out your
    // team lead (if not using a shared services apim) or the Cloud Services
    // team in MS Teams (if using share services apim)
    product_id            = "test"
    api_file              = "test.openapi.yaml"
    subscription_required = false
    wsdl_selector         = []
  },
}
```
#### EXAMPLE test.openapi.yaml
```
openapi: 3.0.0
info:
  title: title
  description: endpoint
  version: 1.0.0
servers:
  - url: "https://redacted.com/test/v1/test/test"
    description: environment
paths:
  /default:
    post:
      operationId: default
      summary: Default
      description: Default operation
      responses:
        "200":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
components:
  schemas:
    response:
      type: object
      properties:
        status:
          type: string
          example: success
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
```

### Debug Output/Panic Output

```shell
terraform [init -upgrade=false]
  Running command terraform with args [init -upgrade=false]
  
  Initializing the backend...
  
  Initializing provider plugins...
  - Finding hashicorp/azurerm versions matching "< 4.0.0"...
  - Installing hashicorp/azurerm v3.73.0...
  - Installed hashicorp/azurerm v3.73.0 (signed by HashiCorp)
  
  Terraform has created a lock file .terraform.lock.hcl to record the provider
  selections it made above. Include this file in your version control repository
  so that Terraform can guarantee to make the same selections by default when
  you run "terraform init" in the future.
  
  Terraform has been successfully initialized!
  
  You may now begin working with Terraform. Try running "terraform plan" to see
  any changes that are required for your infrastructure. All Terraform commands
  should now work.
  
  If you ever set or change modules or backend configuration for Terraform,
  rerun this command to reinitialize your working directory. If you forget, other
  commands will detect it and remind you to do so if necessary.
  terraform [apply -input=false -auto-approve -var managed_apis={"test-api-v1" = {"display_name" = "Test API", "service_path" = "test/test", "subscription_required" = false, "wsdl_selector" = [], "product_id" = "test", "api_file" = "test.openapi.yaml", "import_type" = "openapi", "version" = null, "version_set" = null}} -var project_context=testing -var version_sets=[] -var instance_id=256 -var env=dev -var api_operations=[] -var apim_product={} -var api_policies=[] -var operation_policies=[] -var named_values={} -var resource_group_name=rg-redacted-01 -var apim_name=apim-redacted-01 -var paths={"apis" = "/home/runner/work/terraform-azure-managed-api-module/terraform-azure-managed-api-module/test/apis", "policies" = null} -no-color -lock=false]
  Running command terraform with args [apply -input=false -auto-approve -var managed_apis={"test-api-v1" = {"display_name" = "Test API", "service_path" = "test/test", "subscription_required" = false, "wsdl_selector" = [], "product_id" = "test", "api_file" = "test.openapi.yaml", "import_type" = "openapi", "version" = null, "version_set" = null}} -var project_context=testing -var version_sets=[] -var instance_id=256 -var env=dev -var api_operations=[] -var apim_product={} -var api_policies=[] -var operation_policies=[] -var named_values={} -var resource_group_name=rg-redacted-01 -var apim_name=apim-redacted-01 -var paths={"apis" = "/home/runner/work/terraform-azure-managed-api-module/terraform-azure-managed-api-module/test/apis", "policies" = null} -no-color -lock=false]
  data.azurerm_api_management.apim: Reading...
  data.azurerm_api_management.apim: Read complete after 1s [id=/subscriptions/***/resourceGroups/rg-redacted-01/providers/Microsoft.ApiManagement/service/apim-redacted-01]
  
  Terraform used the selected providers to generate the following execution
  plan. Resource actions are indicated with the following symbols:
    + create
  
  Terraform will perform the following actions:
  
    # azurerm_api_management_api.api["test-api-v1"] will be created
    + resource "azurerm_api_management_api" "api" {
        + api_management_name   = "apim-redacted-01"
        + api_type              = (known after apply)
        + display_name          = "Test API [DEV]"
        + id                    = (known after apply)
        + is_current            = (known after apply)
        + is_online             = (known after apply)
        + name                  = "test-api"
        + path                  = "test/test"
        + protocols             = [
            + "https",
          ]
        + resource_group_name   = "rg-redacted-01"
        + revision              = "current"
        + service_url           = (known after apply)
        + soap_pass_through     = false
        + subscription_required = false
        + version               = (known after apply)
        + version_set_id        = (known after apply)
  
        + import {
            + content_format = "openapi"
            + content_value  = <<-EOT
                  openapi: 3.0.0
                  info:
                    title: title
                    description: endpoint
                    version: 1.0.0
                  servers:
                    - url: "https://redacted.com/test/v1/test/test"
                      description: sandbox environment
                  paths:
                    /default:
                      post:
                        operationId: default
                        summary: Default
                        description: Default operation
                        responses:
                          "200":
                            description: Accepted
                            content:
                              application/json:
                                schema:
                                  $ref: "#/components/schemas/response"
                  components:
                    schemas:
                      response:
                        type: object
                        properties:
                          status:
                            type: string
                            example: success
                    securitySchemes:
                      basicAuth:
                        type: http
                        scheme: basic
              EOT
          }
      }
  
    # azurerm_api_management_product_api.product_api["test-api-v1"] will be created
    + resource "azurerm_api_management_product_api" "product_api" {
        + api_management_name = "apim-redacted-01"
        + api_name            = "test-api"
        + id                  = (known after apply)
        + product_id          = "test"
        + resource_group_name = "rg-redacted-01"
      }
  
  Plan: 2 to add, 0 to change, 0 to destroy.
  azurerm_api_management_api.api["test-api-v1"]: Creating...
  azurerm_api_management_api.api["test-api-v1"]: Still creating... [10s elapsed]
  
  Warning: Argument is deprecated
  
    with azurerm_api_management_api.api["test-api-v1"],
    on main.tf line 14, in resource "azurerm_api_management_api" "api":
    14:   soap_pass_through     = each.value.import_type == "wsdl" ? true : false
  
  `soap_pass_through` will be removed in favour of the property `api_type` in
  version 4.0 of the AzureRM Provider
  
  (and one more similar warning elsewhere)
  
  Error: creating/updating Api (Subscription: "***"
  Resource Group Name: "rg-redacted-01"
  Service Name: "apim-redacted-01"
  Api: "test-api"): polling after CreateOrUpdate: executing request: unexpected status 404 with error: ResourceNotFound: Api not found.
  
    with azurerm_api_management_api.api["test-api-v1"],
    on main.tf line 6, in resource "azurerm_api_management_api" "api":
```

### Expected Behaviour

The `azurerm_api_management_api` should be created successfully.

I'm trying to create an `azurerm_api_management_api` using an openapi type imported file. 

### Actual Behaviour

With any version `> 3.69.0`, The `azurerm_api_management_api` creation fails with the following error:

``` 
  Error: creating/updating Api (Subscription: "***"
  Resource Group Name: "rg-redacted-01"
  Service Name: "apim-dedacted-01"
  Api: "test-api"): polling after CreateOrUpdate: executing request: unexpected status 404 with error: ResourceNotFound: Api not found.
```

If you used `<= 3.69.0` the creation is successful.

### Steps to Reproduce

`terraform apply`

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #28201: azurerm_api_management_api triggers unexpected status 404 with error: "ResourceNotFound: Api not found."
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

I tried with the following versions:

- 4.7
- 4.8
- 4.13.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api" "app" {
  name                  = var.api_name
  resource_group_name   = var.apim_resource_group_name
  api_management_name   = var.apim_name
  revision              = "1"
  api_type              = "http"
  display_name          = var.api_display_name
  path                  = var.api_path
  protocols             = ["https"]
  service_url           = var.service_url
  subscription_required = false

  import {
    content_format = "openapi"
    content_value  = file("${path.module}/${var.api_filename}")
  }

  license {
    name = "<my-company>"
    url  = "<my-license-url>"
  }
}
```

### Debug Output/Panic Output

```shell
13:18:29   ╷
13:18:29   │ Error: creating/updating Api (Subscription: "<subscription-id>"
13:18:29   │ Resource Group Name: "<resource-group-name>"
13:18:29   │ Service Name: "<apim-service-name>"
13:18:29   │ Api: "<api-name>;rev=1"): polling after CreateOrUpdate: executing request: unexpected status 404 (404 Not Found) with error: ResourceNotFound: Api not found.
13:18:29   │ 
13:18:29   │   with module.apis["<api-name>"].azurerm_api_management_api.app,
13:18:29   │   on ../../modules/apis/main.tf line 1, in resource "azurerm_api_management_api" "app":
13:18:29   │    1: resource "azurerm_api_management_api" "app" {
13:18:29   │ 
13:18:29   ╵
```

**Please note that it used to work perfectly fine. The problem has been occurring in the past two weeks or so.**
Running the terraform build multiple times finally results in success, but we sometimes had the case that the API was not updated correctly.

### Expected Behaviour

Whether or not an API is already there on the APIM, the behavior should always be a successful deployment. It's a CreateOrUpdate, as mentioned in the error.

### Actual Behaviour

I get the error above.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by wuxu92**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

As the LRO of importing an OpenAPI file, the polling URL requires the `asyncId` query string to retrieve the actual failure message. This PR adds a custom poller to override the default provisioningState poller.

Also setting the `Partial` to true is required to fix the issue https://github.com/hashicorp/terraform-provider-azurerm/issues/24379#issuecomment-1899251199.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
--- PASS: TestAccApiManagementApi_importOpenapiInvalide (180.43s)
PASS
```

image

The failing cases are not related to this PR. Some of them are fixed in #28194.

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_api_management_api` - fix poller of importing OpenAPI content [GH-23322]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #23322, fixes #22042, fixes #28201 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/apimanagement/api_management_api_resource.go [hunk 1]
```diff
@@ -393,6 +393,9 @@ func resourceApiManagementApiCreateUpdate(d *pluginsdk.ResourceData, meta interf
 	// If import is used, we need to send properties to Azure API in two operations.
 	// First we execute import and then updated the other props.
 	if vs, hasImport := d.GetOk("import"); hasImport {
+		// as `import` field won't return by API, we need to use `Partial` to avoid set to it state
+		// or the sequential apply will report no changes: https://github.com/hashicorp/terraform-provider-azurerm/issues/24379#issuecomment-1899251199
+		d.Partial(true)
```
Comment (jackofallops) [inline internal/services/apimanagement/api_management_api_resource.go:398]: I feel this is symptomatic of the combined `CreateUpdate`, can we split this before continuing with this custom poller to make this less difficult to maintain?

**Review by jackofallops — CHANGES_REQUESTED** [review]
Thanks @wuxu92 - The changes here I think are made more complicated due to the combined create+update, could you take a look at splitting that before applying the custom poller? (I think a separate PR to do this, then rebase your work here on that when merged will be the fastest way to get this in, due to the complexity of review and safety of testing)

Thanks

**Comment by byronbayer** [comment]
is there any chance this can get merged in and approved.

File: internal/services/apimanagement/testdata/api_management_api_openapi_invalide.yaml [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+      operationId: default
+      summary: Default
+      description: Default operation
+      parameters:
+        - description: status
+          in: query
+          name: status
+          schema:
+            type: string
+            default: PRODUCTIVEInvalide
```
Comment (jackofallops) [inline internal/services/apimanagement/testdata/api_management_api_openapi_invalide.yaml:24]: This looks like a typo? Should it be?
```suggestion
            default: PRODUCTIVEInvalid
```

File: internal/services/apimanagement/custompollers/api_management_api_poller.go [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+	pollingSuccess = pollers.PollResult{
+		Status:       pollers.PollingStatusSucceeded,
+		PollInterval: 10 * time.Second,
+	}
+	pollingInProgress = pollers.PollResult{
+		Status:       pollers.PollingStatusInProgress,
+		PollInterval: 10 * time.Second,
+	}
+)
+
```
Comment (jackofallops) [inline internal/services/apimanagement/custompollers/api_management_api_poller.go:37]: Can we add godoc here to explain the purpose of this custom polller? something like:
```suggestion
// NewAPIManagementAPIPoller - creates a new custom poller for API Management API to handle the case where... [details here]
```

File: internal/services/apimanagement/api_management_api_resource.go [hunk 4]
```diff
@@ -442,6 +451,11 @@ func resourceApiManagementApiCreate(d *pluginsdk.ResourceData, meta interface{})
 	if sourceApiId != "" {
 		params.Properties.SourceApiId = pointer.To(sourceApiId)
 	}
+
+	if description != "" {
```
[the remark this answers is not in the document]
Comment (jackofallops) [reply internal/services/apimanagement/api_management_api_resource.go:455]: agreed, can we pull the `description :=` line down to here for better visibility, and use `d.GetOk()` here to ensure the value is populated and not the zero response?

File: internal/services/apimanagement/testdata/api_management_api_openapi_invalide.yaml [hunk 5]
```diff
@@ -0,0 +1,46 @@
+# Copyright (c) HashiCorp, Inc.
```
Comment (jackofallops) [inline internal/services/apimanagement/testdata/api_management_api_openapi_invalide.yaml:1]: Similar typo in the file name? Should this be:
`internal/services/apimanagement/testdata/api_management_api_openapi_invalid.yaml` ?

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @wuxu92 - Thanks for this. Just a few items to take a quick look at, but looking mostly good.

**Comment by Pedroms1** [comment]
@jackofallops were you able to review these changes? The issue is creating some impact

**Comment by J0F3** [comment]
@katbyte @mbfrahry @jackofallops

Could someone please review this PR? This is a very serious bug in the `azurerm_api_management_api` resource which makes the resource almost useless in many cases. The initial issue https://github.com/hashicorp/terraform-provider-azurerm/issues/23322 is now open since September 2023! Unfortunately, there seems almost now reaction to it form Hashicorp / Maintainer of the provider itself to it. 
So, I am really apricate when someone would look into it so that this issue can finally be fixed. 

Thank you!
