### PR TITLE
`azurerm_log_analytics_cluster_customer_managed_key` - fix a bug in resource operation

### LINKED ISSUE #13166: Log Analytics Cluster Customer Managed Key failing to apply with Failure responding to request: `StatusCode=202`
### Issue

When attempting to deploy a log Analytics cluster resource then applying a CMK with `azurerm_log_analytics_cluster_customer_managed_key` will initally fail with Status=202 Code="Unknown" Message="Unknown service error" and Http Response Body is null. 

Then on the next try the `azurerm_log_analytics_cluster_customer_managed_key` resource will fail with `Error: removing Log Analytics Cluster Customer Managed Key from cluster "example-cluster" (resource group "example-resources")`, as the KeyName and KeyVersions have been successfully applied to the Log Analytics Cluster when checking the cluster manually.

Looking briefly and I feel this my be an issue with the [asynchronous operations and status checks](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-dedicated-clusters#asynchronous-operations-and-status-check) for the Updating the Log Cluster operation which is an async response.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.74.0
```

### Affected Resource(s)

* `azurerm_log_analytics_cluster_customer_managed_key`

### Terraform Configuration Files

 This is the example code from the [registry docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_cluster_customer_managed_key) which I was able to reproduce this error with.
```hcl
data "azurerm_client_config" "current" {}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_log_analytics_cluster" "example" {
  name                = "example-cluster"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_key_vault" "example" {
  name                = "keyvaultkeyexample"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "premium"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "create",
      "get",
    ]

    secret_permissions = [
      "set",
    ]
  }

  tags = {
    environment = "Production"
  }

  access_policy {
    tenant_id = azurerm_log_analytics_cluster.example.identity.0.tenant_id
    object_id = azurerm_log_analytics_cluster.example.identity.0.principal_id

    key_permissions = [
      "get",
      "unwrapkey",
      "wrapkey",
    ]
  }

}

resource "azurerm_key_vault_key" "example" {
  name         = "generated-certificate"
  key_vault_id = azurerm_key_vault.example.id
  key_type     = "RSA"
  key_size     = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

resource "azurerm_log_analytics_cluster_customer_managed_key" "example" {
  log_analytics_cluster_id = azurerm_log_analytics_cluster.example.id
  key_vault_key_id         = azurerm_key_vault_key.example.id
}
```

### Expected Behaviour

```
azurerm_log_analytics_cluster_customer_managed_key.example: Creating...
azurerm_log_analytics_cluster_customer_managed_key.example: Creation complete after 5s [id=***]
```

### Actual Behaviour

```
azurerm_key_vault.example: Still creating... [2m0s elapsed]
azurerm_key_vault.example: Creation complete after 2m9s [id=/subscriptions/***/resourceGroups/example-resources/providers/Microsoft.KeyVault/vaults/keyvaultkeyexample]
azurerm_key_vault_key.example: Creating...
azurerm_key_vault_key.example: Creation complete after 5s [id=https://keyvaultkeyexample.vault.azure.net/keys/generated-certificate/***]
azurerm_log_analytics_cluster_customer_managed_key.example: Creating...
╷
│ Error: updating Log Analytics Cluster "example-cluster" (Resource Group "example-resources"): operationalinsights.ClustersClient#Update: Failure responding to request: StatusCode=202 -- Original Error: autorest/azure: Service returned an error. Status=202 Code="Unknown" Message="Unknown service error" Details=[{"HttpResponse.Body":"null"}]
│ 
│   with azurerm_log_analytics_cluster_customer_managed_key.example,
│   on main.tf line 73, in resource "azurerm_log_analytics_cluster_customer_managed_key" "example":
│   73: resource "azurerm_log_analytics_cluster_customer_managed_key" "example" {
│ 
╵
terraform apply  14.30s user 4.34s system 10% cpu 2:51.93 total
```

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by ziyeqf**
fix #13166

cause: https://github.com/Azure/azure-rest-api-specs/issues/21799

Test
---
```
TF_ACC=1 go test -v ./internal/services/loganalytics -run=TestAccLogAnalyticsClusterCustomerManagedKey -timeout=600m
=== RUN   TestAccLogAnalyticsClusterCustomerManagedKey_basic
=== PAUSE TestAccLogAnalyticsClusterCustomerManagedKey_basic
=== RUN   TestAccLogAnalyticsClusterCustomerManagedKey_update
=== PAUSE TestAccLogAnalyticsClusterCustomerManagedKey_update
=== CONT  TestAccLogAnalyticsClusterCustomerManagedKey_basic
=== CONT  TestAccLogAnalyticsClusterCustomerManagedKey_update
--- PASS: TestAccLogAnalyticsClusterCustomerManagedKey_basic (2197.21s)
--- PASS: TestAccLogAnalyticsClusterCustomerManagedKey_update (2854.47s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/loganalytics  2855.629s
```

### CODE REVIEW

File: internal/services/loganalytics/log_analytics_cluster_customer_managed_key_resource.go [hunk 1]
```diff
@@ -19,9 +19,9 @@ import (
 
 func resourceLogAnalyticsClusterCustomerManagedKey() *pluginsdk.Resource {
 	return &pluginsdk.Resource{
-		Create: resourceLogAnalyticsClusterCustomerManagedKeyCreate,
+		Create: resourceLogAnalyticsClusterCustomerManagedKeyCreateOrUpdate,
 		Read:   resourceLogAnalyticsClusterCustomerManagedKeyRead,
-		Update: resourceLogAnalyticsClusterCustomerManagedKeyUpdate,
+		Update: resourceLogAnalyticsClusterCustomerManagedKeyCreateOrUpdate,
```
Comment (katbyte) [inline internal/services/loganalytics/log_analytics_cluster_customer_managed_key_resource.go:24]: we should not be combining creating and update functions as it breaks lifecycle - please keep this seperate

**Review by katbyte — CHANGES_REQUESTED** [review]

**Comment by ziyeqf** [comment]
test after refactor
---
```
TF_ACC=1 go test -v ./internal/services/loganalytics -run=TestAccLogAnalyticsClusterCustomerManagedKey -timeout=600m
=== RUN   TestAccLogAnalyticsClusterCustomerManagedKey_basic
=== PAUSE TestAccLogAnalyticsClusterCustomerManagedKey_basic
=== RUN   TestAccLogAnalyticsClusterCustomerManagedKey_update
=== PAUSE TestAccLogAnalyticsClusterCustomerManagedKey_update
=== CONT  TestAccLogAnalyticsClusterCustomerManagedKey_basic
=== CONT  TestAccLogAnalyticsClusterCustomerManagedKey_update
--- PASS: TestAccLogAnalyticsClusterCustomerManagedKey_basic (2163.43s)
--- PASS: TestAccLogAnalyticsClusterCustomerManagedKey_update (2901.14s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/loganalytics  2902.305s
```

**Review by katbyte — APPROVED** [review]
LGTM 🦺
