### PR TITLE
`azurerm_site_recovery_protection_container_mapping`: Support new property `automatic_update.authentication_type`

### LINKED ISSUE #20304: azurerm_site_recovery_protection_container_mapping automatic_update Auto update settings is un-healthy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.42.0

### Affected Resource(s)/Data Source(s)

azurerm_site_recovery_protection_container_mapping

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_protection_container_mapping" "container-mapping" {
  name                                      = "container-mapping"
  resource_group_name                       = azurerm_recovery_services_vault.recovery.resource_group_name
  recovery_vault_name                       = azurerm_recovery_services_vault.recovery.name
  recovery_fabric_name                      = azurerm_site_recovery_fabric.primary.name
  recovery_source_protection_container_name = azurerm_site_recovery_protection_container.primary.name
  recovery_target_protection_container_id   = azurerm_site_recovery_protection_container.secondary.id
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.policy.id
  automatic_update {
    enabled               = true
    automation_account_id = azurerm_automation_account.support.id
  }
}
```

### Debug Output/Panic Output

```shell
No terraform error
```

### Expected Behaviour

ASR should configure auto update

### Actual Behaviour

Auto update settings is un-healthy

### Steps to Reproduce

terraform apply
Check Site Recovery infrastructure | Extension update settings

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ziyeqf**
fix #20304

test case `TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension` skipped as creation of [new Run As Account is not allowed](https://learn.microsoft.com/en-us/azure/automation/migrate-run-as-accounts-managed-identity?tabs=run-as-account#:~:text=Azure%20Automation%20Run,not%20be%20possible.). 

test
---
```
❯ tftest recoveryservices TestAccSiteRecoveryProtectionContainerMapping                        
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_basic
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_basic
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_withSystemAssignedAutoUpdate
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_withSystemAssignedAutoUpdate
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
    site_recovery_protection_container_mapping_resource_test.go:62: skipped as RunAsAccount is deprecated and it's not allowed to create new ones
--- SKIP: TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension (0.00s)
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_basic
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_withSystemAssignedAutoUpdate
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_basic (971.37s)
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_withSystemAssignedAutoUpdate (1341.36s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      1341.402s

```

### CODE REVIEW

File: internal/services/recoveryservices/site_recovery_protection_container_mapping_resource.go [hunk 1]
```diff
@@ -92,11 +93,20 @@ func resourceSiteRecoveryProtectionContainerMapping() *pluginsdk.Resource {
...
 							Type:         pluginsdk.TypeString,
 							Optional:     true,
 							ValidateFunc: azure.ValidateResourceID,
-							RequiredWith: []string{"automatic_update.0.enabled"},
+						},
+
+						"authentication_type": {
+							Type:     pluginsdk.TypeString,
+							Optional: true,
+							Default:  string(replicationprotectioncontainermappings.AutomationAccountAuthenticationTypeSystemAssignedIdentity),
```
Comment (katbyte) [inline internal/services/recoveryservices/site_recovery_protection_container_mapping_resource.go:106]: what does that mean for existing resources? will this not change them as the default for them was different?

**Review by katbyte — CHANGES_REQUESTED** [review]

File: internal/services/recoveryservices/site_recovery_protection_container_mapping_resource.go (hunk 1 above)
Comment (ziyeqf) [reply internal/services/recoveryservices/site_recovery_protection_container_mapping_resource.go]: Have updated code to make the default value effective in 4.0...
