### PR TITLE
`azurerm_container_app` - add support for scale rules

### LINKED ISSUE #20629: Setting scale rules
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is support for scale rules in Azure Container Apps planed?

It would also be beneficial if I could use AzApi to fill this gap. But using AzApi in conjunction with AzureRm for this seems broken. The scale rules defined in AzApi never seem to get set. It's happened that they do get set, but then disappear after a following deployment, or just after some time (?). I assume this is a bug. And, according to this comment (https://github.com/hashicorp/terraform-provider-azurerm/issues/20535#issuecomment-1441608202), weird stuff is happening with scale rules, even when not using AzApi. So I assume the bug is on AzureRm's side.

Created a bug report for this problem: https://github.com/hashicorp/terraform-provider-azurerm/issues/20631

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

### Potential Terraform Configuration

_No response_

### References

_No response_

### LINKED ISSUE #21207: Support for custom scaling rules in container apps
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AZ API allows you to set custom scaling rules in the container template. Current AZ API implementation looks something like:
```hcl
body = {
  template = {
    scale = {
      rules = [
        {
          name = "name"
          custom = {
            type = "http"
            metadata : {
              concurrentRequests: "100"
            }
          }
        }
      ]
    }
  }
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

### Potential Terraform Configuration

```hcl
resource azurerm_container_app example {
  template {
    rules {
      "name" = {
        type = "http"
        concurrentRequests = 100
      },
      "name2" = {
        type = "queue"
        queueLength = 10
        queueName = "queuename"
      }
    }
  }
}
```

### References

_No response_

### PR DESCRIPTION
**Pull request by jackofallops**
Closes #20629 
Closes #21207 

Supersedes #21274

### CODE REVIEW

File: internal/services/containerapps/helpers/container_apps.go [hunk 1]
```diff
@@ -2347,3 +2400,617 @@ func ContainerAppProbesRemoved(metadata sdk.ResourceMetaData) bool {
...
+				"name": {
+					Type:         pluginsdk.TypeString,
+					Required:     true,
+					ValidateFunc: validation.StringIsNotEmpty,
+				},
+
+				"concurrent_requests": {
+					Type:         pluginsdk.TypeString,
+					Required:     true,
+					ValidateFunc: nil, // TODO - str value for int
```
Comment (stephybun) [inline internal/services/containerapps/helpers/container_apps.go:2640]: This still need doing?

File: internal/services/containerapps/helpers/container_apps.go [hunk 2]
```diff
@@ -2347,3 +2400,617 @@ func ContainerAppProbesRemoved(metadata sdk.ResourceMetaData) bool {
...
+				"name": {
+					Type:         pluginsdk.TypeString,
+					Required:     true,
+					ValidateFunc: validation.StringIsNotEmpty,
+				},
+
+				"concurrent_requests": {
+					Type:         pluginsdk.TypeString,
+					Required:     true,
+					ValidateFunc: nil, // TODO Validation for int as str
```
Comment (stephybun) [inline internal/services/containerapps/helpers/container_apps.go:2727]: Same with this?

**Review by stephybun — COMMENTED** [review]
Thanks @jackofallops. I have two minor comments regarding TODO's in the PR.
