### PR TITLE
[BUG:] `azurerm_linux_virtual_machine`/`azurerm_windows_virtual_machine` - deprecate the `graceful_shutdown` feature flag due to API breaking change

### LINKED ISSUE #26705: terraform destroy does not work for virtual machines if extensions are enabled and the vm is turned off
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.2

### AzureRM Provider Version

3.112.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension, azurerm_linux_virtual_machine

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  location = "northeurope"
  name     = "my_resource_group"
}


# Create virtual network
resource "azurerm_virtual_network" "my_terraform_network" {
  name                = "myVnet"
  address_space       = ["10.0.0.0/16"]
  location            = "northeurope"
  resource_group_name = azurerm_resource_group.rg.name
}

# Create subnet
resource "azurerm_subnet" "my_terraform_subnet" {
  name                 = "mySubnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.my_terraform_network.name
  address_prefixes     = ["10.0.1.0/24"]

}

# Create public IPs
resource "azurerm_public_ip" "my_terraform_public_ip" {
  name                = "myPublicIP"
  location            = "northeurope"
  resource_group_name = azurerm_resource_group.rg.name
  allocation_method   = "Static"
  sku                 = "Standard"

}
resource "azurerm_network_interface" "my_terraform_nic" {
  name                = "myNIC"
  location            = "northeurope"
  resource_group_name = azurerm_resource_group.rg.name

  ip_configuration {
    name                          = "my_nic_configuration"
    subnet_id                     = azurerm_subnet.my_terraform_subnet.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.my_terraform_public_ip.id
  }
}

resource "azurerm_linux_virtual_machine" "my_terraform_vm" {
  name                  = "my_vm"
  location              = "northeurope"
  resource_group_name   = azurerm_resource_group.rg.name
  network_interface_ids = [azurerm_network_interface.my_terraform_nic.id]
  size                  = "Standard_DS1_v2"
  zone                  = "1"

  os_disk {
    name                 = "myOsDisk"
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = "100"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }

  computer_name  = "hostname"
  admin_username = "azureadmin"

}

resource "azurerm_virtual_machine_extension" "health_extension" {
  name               = "HealthExtension2"
  virtual_machine_id = azurerm_linux_virtual_machine.my_terraform_vm.id # Replace with your VM's ID
  publisher            = "Microsoft.ManagedServices"
  type                 = "ApplicationHealthLinux"
  type_handler_version = "2.0"

  settings = <<EOF
  {
    "protocol": "http",
    "port": 80,
    "requestPath": "/",
    "intervalInSeconds": 5,
    "numberOfProbes": 5,
    "gracePeriod": 10
  }
  EOF

}
```

### Debug Output/Panic Output

```shell
Error: deleting Extension (Subscription: "72e2103d-fa69-4102-8a60-fa0fb803d4f3"
│ Resource Group Name: "my_resource_group"
│ Virtual Machine Name: "my_vm"
│ Extension Name: "HealthExtension2"): performing Delete: unexpected status 409 (409 Conflict) with error: OperationNotAllowed: Cannot modify extensions in the VM when the VM is not running.
```

### Expected Behaviour

- I create the VM and the extension through terraform
- I do my thing
- at some point I stop the VM to save resources
- I want to destroy everything so run a terraform destroy
- all resources are destroyed

### Actual Behaviour

The extension resource cannot be removed because the VM is not running.
This would be reasonable behaviour if I was trying to delete only the extension. But because I'm also deleting the vm it doesn't really matter that the extension cannot be removed.

### Steps to Reproduce

1. terraform apply
2. stop the vm through portal, auto shutdown or cli
3. terraform destroy

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #28218: Operation ‘powerOff’ is not allowed (409 Conflict)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.117.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_virtual_machine.windows_vm

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
╷
│ Error: powering off Windows Virtual Machine (Subscription: "xxx"
│ Resource Group Name: "yyy"
│ Virtual Machine Name: "zzz"): performing PowerOff: unexpected status 409 (409 Conflict) with error: OperationNotAllowed: Operation 'powerOff' is not allowed on VM 'zzz' since the VM is either deallocated or marked to be deallocated. Please refer to https://aka.ms/vmpowerstates  to learn about different VM power states.
│ 
│ 
╵
```

### Expected Behaviour

After VM generalization, destroy command should destroy the VM.

### Actual Behaviour

I started to get the error above since 6 December 24. Before that it was working just as expected.

### Steps to Reproduce

- Create a VM,
- Generalize that VM (either via a script or Azure UI)
- Run destroy command (terraform plan -destroy xxx)

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by WodansSon**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
* In October 2024 the PowerOff API made a breaking change to all versions of their API's which was pushed into production at the end of November 2024. This resulted in a large influx of errors being logged (e.g. 584,138 per month from Terraform alone) as a result of the `graceful_shutdown` feature flag being/not being used in the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources.

As a result of this change in the API, I am **deprecating** the `graceful_shutdown` feature flag from the AzureRM Provider and ignoring the value (if `set` in the configuration file), during the `delete` operation.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_linux_virtual_machine` - deprecate the `graceful_shutdown` feature flag due to API breaking change [GH-00000]
* `azurerm_windows_virtual_machine` - deprecate the `graceful_shutdown` feature flag due to API breaking change [GH-00000]

This is a (please select all that apply):

- [X] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related PR(s)
Supersedes PR [#28412](https://github.com/hashicorp/terraform-provider-azurerm/pull/28412)

## Related Issue(s)
Fixes #28218 
Fixes #26705 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/provider/features_test.go [hunk 1]
```diff
@@ -183,7 +183,7 @@ func TestExpandFeatures(t *testing.T) {
 						map[string]interface{}{
 							"detach_implicit_data_disk_on_deletion": true,
 							"delete_os_disk_on_deletion":            true,
-							"graceful_shutdown":                     true,
+							"graceful_shutdown":                     true, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:186]: There's no point testing this any more since it doesn't do anything?
```suggestion
```

File: internal/provider/features_test.go [hunk 2]
```diff
@@ -378,7 +378,7 @@ func TestExpandFeatures(t *testing.T) {
 						map[string]interface{}{
 							"detach_implicit_data_disk_on_deletion": false,
 							"delete_os_disk_on_deletion":            false,
-							"graceful_shutdown":                     false,
+							"graceful_shutdown":                     false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:381]:
```suggestion
```

File: internal/provider/features_test.go [hunk 3]
```diff
@@ -967,7 +967,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 				VirtualMachine: features.VirtualMachineFeatures{
 					DetachImplicitDataDiskOnDeletion: false,
 					DeleteOSDiskOnDeletion:           true,
-					GracefulShutdown:                 false,
+					GracefulShutdown:                 false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:970]:
```suggestion
```

File: internal/provider/features_test.go [hunk 4]
```diff
@@ -980,7 +980,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 						map[string]interface{}{
 							"detach_implicit_data_disk_on_deletion": true,
 							"delete_os_disk_on_deletion":            false,
-							"graceful_shutdown":                     false,
+							"graceful_shutdown":                     false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:983]:
```suggestion
```

File: internal/provider/features_test.go [hunk 5]
```diff
@@ -991,7 +991,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 				VirtualMachine: features.VirtualMachineFeatures{
 					DetachImplicitDataDiskOnDeletion: true,
 					DeleteOSDiskOnDeletion:           false,
-					GracefulShutdown:                 false,
+					GracefulShutdown:                 false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:994]:
```suggestion
```

File: internal/provider/features_test.go [hunk 6]
```diff
@@ -1004,7 +1004,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 						map[string]interface{}{
 							"detach_implicit_data_disk_on_deletion": false,
 							"delete_os_disk_on_deletion":            true,
-							"graceful_shutdown":                     false,
+							"graceful_shutdown":                     false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:1007]:
```suggestion
```

File: internal/provider/features_test.go [hunk 7]
```diff
@@ -1015,7 +1015,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 				VirtualMachine: features.VirtualMachineFeatures{
 					DetachImplicitDataDiskOnDeletion: false,
 					DeleteOSDiskOnDeletion:           true,
-					GracefulShutdown:                 false,
+					GracefulShutdown:                 false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:1018]:
```suggestion
```

File: internal/provider/features_test.go [hunk 8]
```diff
@@ -1028,7 +1028,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 						map[string]interface{}{
 							"detach_implicit_data_disk_on_deletion": false,
 							"delete_os_disk_on_deletion":            false,
-							"graceful_shutdown":                     true,
+							"graceful_shutdown":                     true, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:1031]:
```suggestion
```

File: internal/provider/features_test.go [hunk 9]
```diff
@@ -1038,7 +1038,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 				VirtualMachine: features.VirtualMachineFeatures{
 					DetachImplicitDataDiskOnDeletion: false,
 					DeleteOSDiskOnDeletion:           false,
-					GracefulShutdown:                 true,
+					GracefulShutdown:                 true, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:1041]:
```suggestion
```

File: internal/provider/features_test.go [hunk 10]
```diff
@@ -1051,7 +1051,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 						map[string]interface{}{
 							"detach_implicit_data_disk_on_deletion": false,
 							"delete_os_disk_on_deletion":            false,
-							"graceful_shutdown":                     false,
+							"graceful_shutdown":                     false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:1054]:
```suggestion
```

File: internal/provider/features_test.go [hunk 11]
```diff
@@ -1061,7 +1061,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 				VirtualMachine: features.VirtualMachineFeatures{
 					DetachImplicitDataDiskOnDeletion: false,
 					DeleteOSDiskOnDeletion:           false,
-					GracefulShutdown:                 false,
+					GracefulShutdown:                 false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:1064]:
```suggestion
```

File: internal/provider/features_test.go [hunk 12]
```diff
@@ -1074,7 +1074,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 						map[string]interface{}{
 							"detach_implicit_data_disk_on_deletion": false,
 							"delete_os_disk_on_deletion":            false,
-							"graceful_shutdown":                     false,
+							"graceful_shutdown":                     false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:1077]:
```suggestion
```

File: internal/provider/features_test.go [hunk 13]
```diff
@@ -1084,7 +1084,7 @@ func TestExpandFeaturesVirtualMachine(t *testing.T) {
 				VirtualMachine: features.VirtualMachineFeatures{
 					DetachImplicitDataDiskOnDeletion: false,
 					DeleteOSDiskOnDeletion:           false,
-					GracefulShutdown:                 false,
+					GracefulShutdown:                 false, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/features_test.go:1087]:
```suggestion
```

File: internal/provider/framework/config.go [hunk 14]
```diff
@@ -334,6 +334,7 @@ func (p *ProviderConfig) Load(ctx context.Context, data *ProviderModel, tfVersio
 				f.VirtualMachine.DeleteOSDiskOnDeletion = feature[0].DeleteOsDiskOnDeletion.ValueBool()
 			}
 
+			// TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/framework/config.go:337]: This does nothing now and defaults to `false` anyway, so I think we can just remove it?

File: internal/features/user_flags.go [hunk 15]
```diff
@@ -31,7 +31,7 @@ type CognitiveAccountFeatures struct {
 type VirtualMachineFeatures struct {
 	DetachImplicitDataDiskOnDeletion bool
 	DeleteOSDiskOnDeletion           bool
-	GracefulShutdown                 bool
+	GracefulShutdown                 bool // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/features/user_flags.go:34]: We don't normally allow Major version TODOs in the code, but since this is unavoidable right now, I think a longer explanation should be present for whomever has to deal with this for 5.0?
```suggestion
	GracefulShutdown                 bool // TODO: Remove in 5.0 - Currently not possible to deprecate feature block struct items via feature flagging. Feature made redundant/ineffective by a breaking API change.
```

File: internal/provider/framework/config.go [hunk 16]
```diff
@@ -345,7 +346,7 @@ func (p *ProviderConfig) Load(ctx context.Context, data *ProviderModel, tfVersio
 			}
 		} else {
 			f.VirtualMachine.DeleteOSDiskOnDeletion = false
-			f.VirtualMachine.GracefulShutdown = false
+			f.VirtualMachine.GracefulShutdown = false // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/framework/config.go:349]:
```suggestion
```

File: internal/provider/framework/config_test.go [hunk 17]
```diff
@@ -151,6 +151,7 @@ func TestProviderConfig_LoadDefault(t *testing.T) {
 		t.Errorf("expected virtual_machine.detach_implicit_data_disk_on_deletion to be false")
 	}
 
+	// TODO: Remove in 5.0
 	if features.VirtualMachine.GracefulShutdown {
 		t.Errorf("expected virtual_machine.graceful_shutdown to be false")
 	}
```
Comment (jackofallops) [inline internal/provider/framework/config_test.go:157]:
```suggestion
```

File: internal/provider/framework/model.go [hunk 18]
```diff
@@ -167,15 +167,15 @@ var TemplateDeploymentAttributes = map[string]attr.Type{
 
 type VirtualMachine struct {
 	DeleteOsDiskOnDeletion           types.Bool `tfsdk:"delete_os_disk_on_deletion"`
-	GracefulShutdown                 types.Bool `tfsdk:"graceful_shutdown"`
+	GracefulShutdown                 types.Bool `tfsdk:"graceful_shutdown"` // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/framework/model.go:170]: As above...
```suggestion
	GracefulShutdown                 types.Bool `tfsdk:"graceful_shutdown"` // TODO: Remove in 5.0 - Currently not possible to deprecate feature block struct items via feature flagging. Feature made redundant/ineffective by a breaking API change.
```

File: internal/provider/framework/model.go [hunk 19]
```diff
@@ -167,15 +167,15 @@ var TemplateDeploymentAttributes = map[string]attr.Type{
...
 	SkipShutdownAndForceDelete       types.Bool `tfsdk:"skip_shutdown_and_force_delete"`
 	DetachImplicitDataDiskOnDeletion types.Bool `tfsdk:"detach_implicit_data_disk_on_deletion"`
 }
 
 var VirtualMachineAttributes = map[string]attr.Type{
 	"delete_os_disk_on_deletion":            types.BoolType,
 	"detach_implicit_data_disk_on_deletion": types.BoolType,
-	"graceful_shutdown":                     types.BoolType,
+	"graceful_shutdown":                     types.BoolType, // TODO: Remove in 5.0
```
Comment (jackofallops) [inline internal/provider/framework/model.go:178]:
```suggestion
	"graceful_shutdown":                     types.BoolType, // TODO: Remove in 5.0 - Currently not possible to deprecate feature block struct items via feature flagging. Feature made redundant/ineffective by a breaking API change.
```

File: internal/provider/framework/provider.go [hunk 20]
```diff
@@ -369,9 +369,13 @@ func (p *azureRmFrameworkProvider) Schema(_ context.Context, _ provider.SchemaRe
...
 										Optional: true,
 									},
+
+									// TODO: Remove in 5.0
 									"graceful_shutdown": schema.BoolAttribute{
-										Optional: true,
+										Optional:           true,
+										DeprecationMessage: "'graceful_shutdown' has been deprecated and will be removed from v5.0 of the AzureRM provider.",
 									},
+
```
Comment (jackofallops) [inline internal/provider/framework/provider.go:378]: This can be removed here and conditionally added based on the `FivePointOh()` flag at the bottom of this function:
```
	if !features.FivePointOh() {
		response.Schema.Blocks["features"].(schema.ListNestedBlock).NestedObject.Blocks["virtual_machine"].(schema.ListNestedBlock).NestedObject.Attributes["graceful_shutdown"] = schema.BoolAttribute{
			Optional:           true,
			DeprecationMessage: "'graceful_shutdown' has been deprecated and will be removed from v5.0 of the AzureRM provider.",
		}
	}

```
Sorry, can't add as a suggestion to use, due to deleted lines and requiring adding the `import` for the `features` package.

File: internal/services/compute/linux_virtual_machine_resource.go [hunk 21]
```diff
@@ -1674,28 +1674,7 @@ func resourceLinuxVirtualMachineDelete(d *pluginsdk.ResourceData, meta interface
...
-					SkipShutdown: pointer.To(skipShutdown),
-				}
-				if err := client.PowerOffThenPoll(ctx, *id, options); err != nil {
-					return fmt.Errorf("powering off Linux %s: %+v", id, err)
-				}
-				log.Printf("[DEBUG] Powered Off Linux %s", id)
-			}
-		}
-	}
+	// Due to a breaking change in the API the power down (e.g., 'graceful_shutdown') feature flag is no longer supported...
```
Comment (jackofallops) [inline internal/services/compute/linux_virtual_machine_resource.go:1677]: Can remove this comment, it will have no meaning post merge.
```suggestion
```

File: internal/services/compute/windows_virtual_machine_resource.go [hunk 22]
```diff
@@ -1728,26 +1728,7 @@ func resourceWindowsVirtualMachineDelete(d *pluginsdk.ResourceData, meta interfa
...
-			options := virtualmachines.PowerOffOperationOptions{
-				SkipShutdown: pointer.To(skipShutdown),
-			}
-			if err := client.PowerOffThenPoll(ctx, *id, options); err != nil {
-				return fmt.Errorf("powering off Windows %s: %+v", id, err)
-			}
-			log.Printf("[DEBUG] Powered Off Windows %s", id)
-		}
-	}
+	// Due to a breaking change in the API the power down (e.g., 'graceful_shutdown') feature flag is no longer supported...
```
Comment (jackofallops) [inline internal/services/compute/windows_virtual_machine_resource.go:1731]: Same here
```suggestion
```

File: website/docs/guides/features-block.html.markdown [hunk 23]
```diff
@@ -280,12 +280,10 @@ The `virtual_machine` block supports the following:
 
 * `graceful_shutdown` - (Optional) Should the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` request a graceful shutdown when the Virtual Machine is destroyed? Defaults to `false`.
 
-~> **Note:** When using a graceful shutdown, Azure gives the Virtual Machine a 5 minutes window in which to complete the shutdown process, at which point the machine will be force powered off - [more information can be found in this blog post](https://azure.microsoft.com/en-us/blog/linux-and-graceful-shutdowns-2/).
+!> **Note:** `graceful_shutdown` has been deprecated and will be removed from v5.0 of the AzureRM provider.
```
Comment (jackofallops) [inline website/docs/guides/features-block.html.markdown:283]:
```suggestion
!> **Note:** Due to a breaking API change `graceful_shutdown` is no longer effective and has been deprecated. This feature will be removed from v5.0 of the AzureRM provider.
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Thanks @WodansSon - I know we've not done a deprecation on the features block before, but we should follow the same approach as for resource schema changes or we'll bump into problems when we start testing for 5.0.

I've left suggestions and code snippets I believe should work fine if you can take a look?

File: helpers/azure/quoted_string_output_test.go [hunk 24]
```diff
@@ -33,11 +33,16 @@ func TestQuotedStringSlice(t *testing.T) {
 	}
```
[the remark this answers is not in the document]
Comment (WodansSon) [reply helpers/azure/quoted_string_output_test.go:33]: Fixed.

File: internal/provider/features.go [hunk 25]
```diff
@@ -220,11 +220,15 @@ func schemaFeatures(supportLegacyTestSuite bool) *pluginsdk.Schema {
 						Optional: true,
 						Default:  false,
 					},
+
+					// TODO: Remove in 5.0
```
[the remark this answers is not in the document]
Comment (WodansSon) [reply internal/provider/features.go:224]: Fixed.

File: internal/provider/features.go [hunk 26]
```diff
@@ -569,9 +573,12 @@ func expandFeatures(input []interface{}) features.UserFeatures {
 			if v, ok := virtualMachinesRaw["delete_os_disk_on_deletion"]; ok {
 				featuresMap.VirtualMachine.DeleteOSDiskOnDeletion = v.(bool)
 			}
+
+			// TODO: Remove in 5.0
 			if v, ok := virtualMachinesRaw["graceful_shutdown"]; ok {
 				featuresMap.VirtualMachine.GracefulShutdown = v.(bool)
 			}
```
[the remark this answers is not in the document]
Comment (WodansSon) [reply internal/provider/features.go:580]: Fixed.

File: internal/provider/features_test.go (hunk 1 above)
Comment (WodansSon) [reply internal/provider/features_test.go:186]: Fixed.

File: internal/provider/features_test.go (hunk 2 above)
Comment (WodansSon) [reply internal/provider/features_test.go:381]: Fixed.

File: internal/provider/features_test.go (hunk 3 above)
Comment (WodansSon) [reply internal/provider/features_test.go:970]: Fixed.

File: internal/provider/features_test.go (hunk 4 above)
Comment (WodansSon) [reply internal/provider/features_test.go:983]: Fixed.

File: internal/provider/features_test.go (hunk 5 above)
Comment (WodansSon) [reply internal/provider/features_test.go:994]: Fixed.

File: internal/provider/features_test.go (hunk 6 above)
Comment (WodansSon) [reply internal/provider/features_test.go:1007]: Fixed.

File: internal/provider/features_test.go (hunk 7 above)
Comment (WodansSon) [reply internal/provider/features_test.go:1018]: Fixed.

File: internal/provider/features_test.go (hunk 8 above)
Comment (WodansSon) [reply internal/provider/features_test.go:1031]: Fixed.

File: internal/provider/features_test.go (hunk 9 above)
Comment (WodansSon) [reply internal/provider/features_test.go:1041]: Fixed.

File: internal/provider/features_test.go (hunk 10 above)
Comment (WodansSon) [reply internal/provider/features_test.go:1054]: Fixed.

File: internal/provider/features_test.go (hunk 11 above)
Comment (WodansSon) [reply internal/provider/features_test.go:1064]: Fixed.

File: internal/provider/features_test.go (hunk 12 above)
Comment (WodansSon) [reply internal/provider/features_test.go:1077]: Fixed.

File: internal/provider/features_test.go (hunk 13 above)
Comment (WodansSon) [reply internal/provider/features_test.go:1087]: Fixed.

File: internal/provider/framework/config.go (hunk 14 above)
Comment (WodansSon) [reply internal/provider/framework/config.go:337]: Fixed.

File: internal/features/user_flags.go (hunk 15 above)
Comment (WodansSon) [reply internal/features/user_flags.go:34]: Fixed.

File: internal/provider/framework/config.go (hunk 16 above)
Comment (WodansSon) [reply internal/provider/framework/config.go:349]: Fixed.

File: internal/provider/framework/model.go (hunk 18 above)
Comment (WodansSon) [reply internal/provider/framework/model.go:170]: Fixed.

File: internal/provider/framework/model.go (hunk 19 above)
Comment (WodansSon) [reply internal/provider/framework/model.go:178]: Fixed.

File: internal/provider/framework/provider.go (hunk 20 above)
Comment (WodansSon) [reply internal/provider/framework/provider.go:378]: Fixed.

File: internal/services/compute/linux_virtual_machine_resource.go (hunk 21 above)
Comment (WodansSon) [reply internal/services/compute/linux_virtual_machine_resource.go:1677]: Fixed.

File: internal/services/compute/windows_virtual_machine_resource.go (hunk 22 above)
Comment (WodansSon) [reply internal/services/compute/windows_virtual_machine_resource.go:1731]: Fixed.

File: website/docs/guides/features-block.html.markdown (hunk 23 above)
Comment (WodansSon) [reply website/docs/guides/features-block.html.markdown:283]: Fixed.
