### PR TITLE
`azurerm_cognitive_deployment` - Upgrade cognitive api version, update resource schema to fix deprecated argument's issue

### LINKED ISSUE #22198: Warnings for azurerm_cognitive_deployment documentation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was having issues with `azurerm_cognitive_deployment` which was giving me this error. 
```
CreateOrUpdate: unexpected status 400 with error: InvalidResourceProperties: The specified scale type 'Standard' of account deployment is not supported by the model 'text-davinci-003'.
```
This was causing me confusion as "scale type" can only be set to `Standard` in Terraform so I wasn't sure what to do.

What this actually turned out to be was I was trying to deploy `text-davinci-003` to `uksouth` which isn't supported (as per https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/models#gpt-3-models)

Is there anything that could be added to the documentation here to warn users that not all models can be deployed to all regions?

### New or Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Potential Terraform Configuration

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by lonegunmanb**
This pr contains a breaking change to `azurerm_cognitive_deployment` and it should fix #22198.

In cognitive API version `2022-10-01` there's `scale` object in the resource's domain object, but it's no longer supported. If we create the cognitive deployment on the portal you would find that the portal use `2023-05-01` API and it won't send `scale` property to the service side. Actually, both of `scale` and new added `sku` object is optional, but when I tried adding an optional `sku` block and provision an `azurerm_cognitive_deployment` resource without `sku`, the service side would set default values to `sku` block and caused a drift (set `name = Standard` and `capacity = 1`).

So I set `sku` a required block since the service side would set default values if it's absent. To avoid a drift the easiest way is passing a `sku` block like we set `scale` block before:

```hcl
sku {
    name = "Standard"
}
```

The reason I removed `scale` block which caused a breaking change is, if we preserve this block, the new API would complain like the following error message:

```text
Error: creating Deployment (Subscription: "xxxxxxxx"
        Resource Group Name: "acctest-rg-230620144039447170"
        Account Name: "acctest-ca-230620144039447170"
        Deployment Name: "acctest-cd-230620144039447170"): performing CreateOrUpdate: unexpected status 400 with error: InvalidResourceProperties: The scale settings of account deployment is deprecated since API version '2023-05-01', please use 'sku' instead.
        
          with azurerm_cognitive_deployment.test,
          on terraform_plugin_test.tf line 32, in resource "azurerm_cognitive_deployment" "test":
          32: resource "azurerm_cognitive_deployment" "test" {
        
        creating Deployment (Subscription: "xxxxxxxx"
        Resource Group Name: "acctest-rg-230620144039447170"
        Account Name: "acctest-ca-230620144039447170"
        Deployment Name: "acctest-cd-230620144039447170"): performing CreateOrUpdate:
        unexpected status 400 with error: InvalidResourceProperties: The scale
        settings of account deployment is deprecated since API version '2023-05-01',
        please use 'sku' instead.
        --- FAIL: TestAccCognitiveDeploymentSequential/deployment/basic (205.40s)
```

Since we cannot set this block anymore, to avoid such errors in the future I removed this block from the resource.

### CODE REVIEW

File: internal/services/cognitive/cognitive_deployment_resource.go [hunk 1]
```diff
@@ -94,21 +99,46 @@ func (r CognitiveDeploymentResource) Arguments() map[string]*pluginsdk.Schema {
 			},
 		},
 
-		"scale": {
+		"sku": {
```
Comment (stephybun) [inline internal/services/cognitive/cognitive_deployment_resource.go:102]: Completely removing/renaming will break existing users since this is ForceNew - since these look to be doing/controlling the same thing I think we should keep the existing names but map it to the new names e.g. scale -> sku and type -> name within the provider, this means users configs will remain the same. We can do a hard rename of this in the next major release. 

Does that makes sense?

**Review by stephybun — CHANGES_REQUESTED** [review]

File: internal/services/cognitive/cognitive_deployment_resource.go (hunk 1 above)
Comment (kirk-marple) [reply internal/services/cognitive/cognitive_deployment_resource.go:102]: It appears we're also blocked by this and can't deploy changes to our OpenAI deployments via Terraform.

Is there a short-term workaround to make 'scale' not required, potentially?

Comment (lonegunmanb) [reply internal/services/cognitive/cognitive_deployment_resource.go:102]: @stephybun I've tried the solution you suggested but we have a problem now.  There's an argument named `capacity` in the new `sku` block:

```hcl
"capacity": {
				Type:     pluginsdk.TypeInt,
				Optional: true,
				ForceNew: true,
				Default:  1,
			},
```

The `capacity`'s default value is `1`, and you cannot pass `nil` to API otherwise an error would be raised. That means the whole new `sku` block is required, otherwise when we try to import the resource and got `1` for `capacity` from the service side, the absent of `sku` block would cause a drift. Since all properties for this resource are ForceNew that would cause a re-creation.

But if users added a `sku` block to the existing code, that would cause a re-creation too. It seems like we cannot avoid a re-creation.

The good news is this deployment resource seems to be a stateless one, so a re-creation won't cause any data loss or long-term service downtime.

Another possible approach is just to hide all `sku`'s properties, and just hard code the `capacity` to `1` in the provider's code, that looks better than the status quo to me.

I'll try this approach and you can decide whether you like this design or not.

**Comment by lonegunmanb** [comment]
@stephybun Would you please give this pr another review? Thanks!

**Comment by lonegunmanb** [comment]
@stephybun Would you please give this pr another review? Thanks!

**Comment by MarvelOrange** [comment]
Bump on this one, I am unable to deploy a model now and its impacting delivery :(

**Comment by unique-dominik** [comment]
Same from our side, our delivery is blocked due to this ❤️ Hoping for a review.

File: internal/services/cognitive/cognitive_deployment_resource.go (hunk 1 above)
Comment (katbyte) [reply internal/services/cognitive/cognitive_deployment_resource.go]: That sounds like a reasonable plan to me

**Review by katbyte — APPROVED** [review]
Thanks @lonegunmanb - LGTM 💾

File: internal/services/cognitive/cognitive_deployment_resource.go (hunk 1 above)
Comment (jayendranarumugam) [reply internal/services/cognitive/cognitive_deployment_resource.go]: @katbyte , Is there any process to track these kinds of improvements/breaking change to 4.0 ?
