### PR TITLE
`azurerm_sentinel_alert_rule_scheduled` - remove `forcenew` for `alert_rule_template_version`

### LINKED ISSUE #25564: Error "409 Conflict" when updating a Sentinel analytics rule
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.9

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_alert_rule_scheduled

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
}

resource "azurerm_sentinel_log_analytics_workspace_onboarding" "example" {
  workspace_id = azurerm_log_analytics_workspace.example.id
}

resource "azurerm_sentinel_alert_rule_scheduled" "example" {
  name                       = "example"
  log_analytics_workspace_id = azurerm_sentinel_log_analytics_workspace_onboarding.example.workspace_id
  alert_rule_template_guid = "173f8699-6af5-484a-8b06-8c47ba89b380"
  alert_rule_template_version = "1.0.4"
  display_name               = "example"
  severity                   = "Medium"
  query                      = <<QUERY
AzureActivity |
  where OperationName == "Create or Update Virtual Machine" or OperationName =="Create Deployment" |
  where ActivityStatus == "Succeeded" |
  make-series dcount(ResourceId) default=0 on EventSubmissionTimestamp in range(ago(7d), now(), 1d) by Caller
QUERY
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: creating Sentinel Alert Rule Scheduled "Alert Rule (Subscription: \"25d04c6b-xxxxxx\"\nResource Group Name: \"example\"\nWorkspace Name: \"example\"\nRule: \"example\")": unexpected status 409 (409 Conflict) with error: Conflict: The rule with id 'example' was recently deleted. You need to allow some time before re-using the same id. Please try again later.
│
│   with azurerm_sentinel_alert_rule_scheduled.example,
│   on main.tf line 21, in resource "azurerm_sentinel_alert_rule_scheduled" "example":
│   21: resource "azurerm_sentinel_alert_rule_scheduled" "example" {
│
╵
```

### Expected Behaviour

The `alert_rule_template_version` is updated, e.g., from "1.0.4" to "1.0.5", and the deployment is successful in one attempt.

### Actual Behaviour

The deployment failed with error code 409, output with a message saying it needs some time before re-using the same id. 

Essentially, according to the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sentinel_alert_rule_scheduled#alert_rule_template_version), changing the version of the alert rule will force a new Sentinel Scheduled Alert Rule to be created. Previously, creating a newly updated rule will be done immediately after destroying the resources.

 Still, now it seems that the time of this process is dramatically extended and will require another apply attempt after almost one hour, which in the meantime introduces the risk of missing the rule that was going to be updated.

### Steps to Reproduce

1. deploy the resource with `alert_rule_template_version` being "1.0.4"
2. update `alert_rule_template_version` being` to "1.0.5" and deploy it again

### Important Factoids

none

### References

_No response_

### PR DESCRIPTION
**Pull request by ziyeqf**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

remove the `forcenew` property for `alert_rule_template_version`. As per testing it's not required now.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
❯❯ tftest sentinel TestAccSentinelAlertRuleScheduled        
=== RUN   TestAccSentinelAlertRuleScheduled_basic
=== PAUSE TestAccSentinelAlertRuleScheduled_basic
=== RUN   TestAccSentinelAlertRuleScheduled_upgrade
=== PAUSE TestAccSentinelAlertRuleScheduled_upgrade
=== RUN   TestAccSentinelAlertRuleScheduled_complete
=== PAUSE TestAccSentinelAlertRuleScheduled_complete
=== RUN   TestAccSentinelAlertRuleScheduled_update
=== PAUSE TestAccSentinelAlertRuleScheduled_update
=== RUN   TestAccSentinelAlertRuleScheduled_requiresImport
=== PAUSE TestAccSentinelAlertRuleScheduled_requiresImport
=== RUN   TestAccSentinelAlertRuleScheduled_withAlertRuleTemplateGuid
=== PAUSE TestAccSentinelAlertRuleScheduled_withAlertRuleTemplateGuid
=== RUN   TestAccSentinelAlertRuleScheduled_updateEventGroupingSetting
=== PAUSE TestAccSentinelAlertRuleScheduled_updateEventGroupingSetting
=== CONT  TestAccSentinelAlertRuleScheduled_basic
=== CONT  TestAccSentinelAlertRuleScheduled_requiresImport
=== CONT  TestAccSentinelAlertRuleScheduled_updateEventGroupingSetting
=== CONT  TestAccSentinelAlertRuleScheduled_complete
=== CONT  TestAccSentinelAlertRuleScheduled_upgrade
=== CONT  TestAccSentinelAlertRuleScheduled_withAlertRuleTemplateGuid
=== CONT  TestAccSentinelAlertRuleScheduled_update
=== NAME  TestAccSentinelAlertRuleScheduled_requiresImport
    testing_new.go:90: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Solution (Subscription: "*****"
        Resource Group Name: "acctestRG-sentinel-240422142804380013"
        Solution Name: "SecurityInsights(acctestLAW-240422142804380013)"): performing Delete: unexpected status 204 (204 No Content) received with no body
        
        deleting Solution (Subscription: "*****"
        Resource Group Name: "acctestRG-sentinel-240422142804380013"
        Solution Name: "SecurityInsights(acctestLAW-240422142804380013)"): performing
        Delete: unexpected status 204 (204 No Content) received with no body
--- FAIL: TestAccSentinelAlertRuleScheduled_requiresImport (143.33s)
--- PASS: TestAccSentinelAlertRuleScheduled_complete (287.05s)
--- PASS: TestAccSentinelAlertRuleScheduled_basic (289.01s)
--- PASS: TestAccSentinelAlertRuleScheduled_withAlertRuleTemplateGuid (289.63s)
--- PASS: TestAccSentinelAlertRuleScheduled_updateEventGroupingSetting (362.60s)
--- PASS: TestAccSentinelAlertRuleScheduled_upgrade (370.77s)
--- PASS: TestAccSentinelAlertRuleScheduled_update (429.31s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-azurerm/internal/services/sentinel	429.385s
FAIL
```
rerun the failed one
```
❯❯ tftest sentinel TestAccSentinelAlertRuleScheduled_requiresImport
=== RUN   TestAccSentinelAlertRuleScheduled_requiresImport
=== PAUSE TestAccSentinelAlertRuleScheduled_requiresImport
=== CONT  TestAccSentinelAlertRuleScheduled_requiresImport
--- PASS: TestAccSentinelAlertRuleScheduled_requiresImport (206.98s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/sentinel	207.060s
```
## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

`azurerm_sentinel_alert_rule_scheduled` - remove `forcenew` for `alert_rule_template_version` [GH-25688]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25564

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/sentinel/sentinel_alert_rule_scheduled_resource_test.go [hunk 1]
```diff
@@ -339,6 +361,32 @@ QUERY
 `, r.template(data), data.RandomInteger)
 }
 
+func (r SentinelAlertRuleScheduledResource) upgradeVersion(data acceptance.TestData, update bool) string {
+	version := "1.0.4"
+	if update {
+		version = "1.0.5"
+	}
+	return fmt.Sprintf(`
```
Comment (jackofallops) [inline internal/services/sentinel/sentinel_alert_rule_scheduled_resource_test.go:369]: Is there a reason not to just use a string here and avoid complication of the bool to string evaluation, and be able to provide values in the calling test? e.g.
```suggestion
func (r SentinelAlertRuleScheduledResource) upgradeVersion(data acceptance.TestData, version string) string {
	return fmt.Sprintf(`
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @ziyeqf - Thanks for this PR. It looks mostly fine, but one comment below to take a look at if you could? 

Thanks

**Review by stephybun — APPROVED** [review]
Thanks @ziyeqf LGTM 👍
