### PR TITLE
``azurerm_windows_web_app`` - FIX node version reset to "0.12.1" during update

### LINKED ISSUE #25452: Update of Azure Web App using runtime NodeJS can unset the NodeJS version leading to crash
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.86.0 (verified on 3.87.1)

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3"
    }
  }
}

provider "azurerm" {
  features {}
}

provider "random" {}

resource "random_string" "unique" {
  length  = 4
  lower   = true
  number  = true
  upper   = false
  special = false
}

resource "azurerm_resource_group" "windows" {
  name     = "rg-windows-${random_string.unique.result}"
  location = "centralus"
}

resource "azurerm_app_service_plan" "windows" {
  name                = "plan-windows-${random_string.unique.result}"
  location            = azurerm_resource_group.windows.location
  resource_group_name = azurerm_resource_group.windows.name
  kind                = "Windows"
  reserved            = false # Must be false (the default value) for Windows plans

  sku {
    tier     = "Free"
    size     = "F1"
    capacity = 0
  }
}

resource "azurerm_app_service" "windows" {
  name                = "app-windows-${random_string.unique.result}"
  location            = azurerm_resource_group.windows.location
  resource_group_name = azurerm_resource_group.windows.name
  app_service_plan_id = azurerm_app_service_plan.windows.id

  site_config {
    use_32_bit_worker = true

    application_stack {
      current_stack = "node"
      node_version  = "~18"
    }
  }

  app_settings = {
    "RANDOM_KEY": "random-value"
  }
}
```

### Debug Output/Panic Output

```shell
N/A
(I'm not the manager of the terraform file and can't get these informations)
```

### Expected Behaviour

When we need to update the IP restriction, only the IP restriction should be updated and not the App Settings. At the same time, if we need to update the App Settings the node version should not be lost in the process

### Actual Behaviour

If the environment variable for NodeJS version is set and we start to update our ip restriction of the windows web app, it's lost in the update without notification leading to Azure using the NodeJS version 0.16.1 (all of our applications instantly crash).
However, if the environment variable for NodeJS version isn't set, Terraform correctly add it

--> Right now, we need to make 2 deployment if we have to change something in App Settings or Site Configuration leading to unacceptable downtime

### Steps to Reproduce

1. terraform plan
2. terraform apply

(I'm not the manager of the terraform file and can't get all the commands in details, so you have only the idea indicated)

### Important Factoids

N/A

### References

Seems related/similar to #16681

### PR DESCRIPTION
**Pull request by Apokalypt**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Right now, the NodeJS environment variable can be unset during an update. This PR ensure that the version is correctly set if we need to update AppSettings for any reason
I also remove the duplicate code to avoid patching/updating app settings two times

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

> Sorry but I could only run locally the tests... I've made some tests in our professional environment and it's correctly working but I will appreciate if someone can run them properly

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_windows_web_app` -  avoid "WEBSITE_NODE_DEFAULT_VERSION" to be lost during update

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25452

### CODE REVIEW

**Comment by Apokalypt** [comment]
@tombuildsstuff Could you review this PR fixing a bug that could be problematic if customers use Web Apps with a NodeJS runtime please?

(I don't know if I'm allowed to mention you, but if I'm not, I apologize)

File: internal/services/appservice/helpers/windows_web_app_schema.go [hunk 1]
```diff
@@ -644,14 +644,25 @@ func (s *SiteConfigWindows) ExpandForUpdate(metadata sdk.ResourceMetaData, exist
...
+		appSettings["WEBSITE_HEALTHCHECK_MAXPINGFAILURES"] = strconv.Itoa(int(s.HealthCheckEvictionTime))
+	}
+
 	if len(s.ApplicationStack) == 1 {
 		winAppStack := s.ApplicationStack[0]
-		if metadata.ResourceData.HasChange("site_config.0.application_stack.0.node_version") {
+
+		// (@apokalypt) If we are using node we need to always set the version since we remove it when we are parsing the web app
+		// https://github.com/hashicorp/terraform-provider-azurerm/issues/25452
+		if winAppStack.NodeVersion != "" {
```
Comment (stephybun) [inline internal/services/appservice/helpers/windows_web_app_schema.go:659]: We should still be using `d.HasChanges` here to support the use of `ignore_changes`. Can we please amend this to.
```suggestion

		if metadata.ResourceData.HasChange("site_config.0.application_stack.0.node_version") || winAppStack.NodeVersion != "" {
```

Could we also remove the comment, since that information should be traceable in the git history, PR description and issue links. To ensure that this peculiarity is maintained we should add a test for this.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @Apokalypt. I left some comments in-line which need to be addressed before we can proceed with this. It should also be feasible to add a test to ensure that this fix works and doesn't end up regressing, e.g. through extending one of the node acceptance tests with an additional update step.

Would you mind applying these changes to #25489 as well? Then we can get both fixes in. In future you're also welcome to lump small changes like these that span multiple app service resources in the same PR.

**Comment by Apokalypt** [comment]
> Thanks @Apokalypt. I left some comments in-line which need to be addressed before we can proceed with this. It should also be feasible to add a test to ensure that this fix works and doesn't end up regressing, e.g. through extending one of the node acceptance tests with an additional update step.
> 
> Would you mind applying these changes to #25489 as well? Then we can get both fixes in. In future you're also welcome to lump small changes like these that span multiple app service resources in the same PR.

Changes made as requested 👍 Sorry for making a double PR, I wanted to strictly follow contribution guidelines
As for the tests, I hope I've done them correctly. I still can't run the acceptance tests, as I don't have the necessary access. Could you please run them?

File: internal/services/appservice/windows_web_app_resource.go [hunk 2]
```diff
@@ -911,7 +911,9 @@ func (r WindowsWebAppResource) Update() sdk.ResourceFunc {
 			if metadata.ResourceData.HasChanges("app_settings", "site_config") || metadata.ResourceData.HasChange("site_config.0.health_check_eviction_time_in_min") {
 				appSettingsUpdate := helpers.ExpandAppSettingsForUpdate(model.Properties.SiteConfig.AppSettings)
 				appSettingsProps := *appSettingsUpdate.Properties
-				appSettingsProps["WEBSITE_HEALTHCHECK_MAXPINGFAILURES"] = strconv.Itoa(int(state.SiteConfig[0].HealthCheckEvictionTime))
+				if metadata.ResourceData.HasChange("site_config.0.health_check_eviction_time_in_min") {
+					appSettingsProps["WEBSITE_HEALTHCHECK_MAXPINGFAILURES"] = strconv.Itoa(int(state.SiteConfig[0].HealthCheckEvictionTime))
+				}
```
Comment (stephybun) [inline internal/services/appservice/windows_web_app_resource.go:916]: This still needs to be reverted to how it was previously in the code

File: internal/services/appservice/windows_web_app_resource_test.go [hunk 3]
```diff
@@ -1087,6 +1087,15 @@ func TestAccWindowsWebApp_withNode14(t *testing.T) {
 			),
 		},
 		data.ImportStep("site_credential.0.password"),
+		{
+			Config: r.nodeWithAppSettings(data, "~14"),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("site_config.0.application_stack.0.node_version").HasValue("~14"),
+			),
+			ExpectNonEmptyPlan: true, // should only indicate that the app settings have changed
```
Comment (stephybun) [inline internal/services/appservice/windows_web_app_resource_test.go:1096]: This means that we're expecting a diff to happen which is what these changes are trying to fix/avoid so this needs to be removed
```suggestion
```

File: internal/services/appservice/windows_web_app_resource_test.go [hunk 4]
```diff
@@ -1102,6 +1111,15 @@ func TestAccWindowsWebApp_withNode18(t *testing.T) {
 			),
 		},
 		data.ImportStep("site_credential.0.password"),
+		{
+			Config: r.nodeWithAppSettings(data, "~18"),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("site_config.0.application_stack.0.node_version").HasValue("~18"),
+			),
+			ExpectNonEmptyPlan: true, // should only indicate that the app settings have changed
```
Comment (stephybun) [inline internal/services/appservice/windows_web_app_resource_test.go:1120]:
```suggestion
```

File: internal/services/appservice/windows_web_app_resource_test.go [hunk 5]
```diff
@@ -1117,6 +1135,15 @@ func TestAccWindowsWebApp_withNode20(t *testing.T) {
 			),
 		},
 		data.ImportStep("site_credential.0.password"),
+		{
+			Config: r.nodeWithAppSettings(data, "~20"),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("site_config.0.application_stack.0.node_version").HasValue("~20"),
+			),
+			ExpectNonEmptyPlan: true, // should only indicate that the app settings have changed
```
Comment (stephybun) [inline internal/services/appservice/windows_web_app_resource_test.go:1144]:
```suggestion
```

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @Apokalypt, yeah I'll kick off the acceptance tests once the PR is ready to be merged as a final check. There's still some minor changes that need to happen, could you please take a look?

File: internal/services/appservice/windows_web_app_resource.go (hunk 2 above)
Comment (Apokalypt) [reply internal/services/appservice/windows_web_app_resource.go:916]: The "problem" is that without the if block, the app setting will be set to 0 when the health check property isn't configured in the terraform configuration.
Should I still remove the if block and create a different issue for that ?

Comment (stephybun) [reply internal/services/appservice/windows_web_app_resource.go:916]: Given the complex and temperamental nature of App Service my preference would be to fix this in a separate PR with a dedicated test. You don't need to open a separate issue for it, just the PR is fine.

File: internal/services/appservice/windows_web_app_resource_test.go (hunk 3 above)
Comment (stephybun) [reply internal/services/appservice/windows_web_app_resource_test.go:1096]: Unless a `ForceNew` property of the resource in the test config was changed then adding an additional test step like you have done here will call the update method of the resource. With the changes made in this PR,  after calling the update we would be expecting no diff to exist i.e. an empty plan.

Comment (Apokalypt) [reply internal/services/appservice/windows_web_app_resource_test.go]: Thanks, with your explanation and what I read in the code (terraform-plugin-testing) to run the tests, I understand better how the tests are run. So I made the requested change 👍

**Review by stephybun — COMMENTED** [review]
I've kicked off the tests, will come back later to check on them and then this should hopefully be good to go!

**Review by stephybun — APPROVED** [review]
Tests look good. Thanks @Apokalypt LGTM 🦖
