### PR TITLE
`azurerm_private_endpoint` Try add internal lock when private connection resource id is cosmosdb account id to fix #14364

### LINKED ISSUE #14364: Create multiple `azurerm_private_endpoint` linked to the same cosmos db concurrently would cause "InternalServerError"
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_private_endpoint` && `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.85.0"  # 2.77.0 added 'EnableServerless' cosmosdb capability, which we use
    }
  }
}

# Using the Azure plugin
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "zjhe-privateendpoint-cosmosdb"
  location = "West Europe"
}

resource "azurerm_virtual_network" "vnet" {
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.rg.location
  name                = "zjhe-privateendpoint-cosmosdb"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "sbunet" {
  name                 = "zjhe-privateendpoint-cosmosdb"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.0.0/24"]
  enforce_private_link_endpoint_network_policies = true
}

resource "azurerm_cosmosdb_account" "db" {
  name                          = "zjhe-privateendpoint-cosmosdb"
  location                      = azurerm_resource_group.rg.location
  resource_group_name           = azurerm_resource_group.rg.name
  offer_type                    = "Standard"
  kind                          = "MongoDB"
  public_network_access_enabled = false

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 5
    max_staleness_prefix    = 100
  }

  capabilities {
    name = "DisableRateLimitingResponses"
  }

  capabilities {
    name = "EnableMongo"
  }

  capabilities {
    name = "EnableServerless"
  }

  geo_location {
    location          = azurerm_resource_group.rg.location
    failover_priority = 0
  }

  backup {
    type                = "Periodic"
    interval_in_minutes = 240
    retention_in_hours  = 8
  }
}

resource "azurerm_cosmosdb_mongo_database" "mongo_db" {
  name                = "my_mongo_db"
  resource_group_name = azurerm_resource_group.rg.name
  account_name        = azurerm_cosmosdb_account.db.name
}

resource "azurerm_cosmosdb_mongo_collection" "mongo_collection" {
  name                = "my_collection"
  resource_group_name = azurerm_resource_group.rg.name
  account_name        = azurerm_cosmosdb_account.db.name
  database_name       = azurerm_cosmosdb_mongo_database.mongo_db.name

  default_ttl_seconds = 0

  index {
    keys   = [
      "$**",
    ]
    unique = false
  }

  index {
    keys   = [
      "_id",
    ]
    unique = true
  }
}

resource "azurerm_private_endpoint" "cosmos_endpoint" {
  count = 11
  name                = "zjhe-privateendpoint-cosmosdb-${count.index}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  subnet_id           = azurerm_subnet.sbunet.id

  private_service_connection {
    is_manual_connection           = false
    name                           = "${azurerm_cosmosdb_account.db.name}-connection-${count.index}"
    private_connection_resource_id = azurerm_cosmosdb_account.db.id
    subresource_names              = [azurerm_cosmosdb_account.db.kind]
  }
}
```

### Expected Behaviour

Multiple private endpoints been provisioned.

### Actual Behaviour

azurerm_private_endpoint.cosmos_endpoint[7]: Still creating... [31m21s elapsed]
╷
│ Error: waiting for creation of Private Endpoint "zjhe-privateendpoint-cosmosdb-1" (Resource Group "zjhe-privateendpoint-cosmosdb"): Code="InternalServerError" Message="An error occurred." Details=[]
│
│   with azurerm_private_endpoint.cosmos_endpoint[1],
│   on main.tf line 102, in resource "azurerm_private_endpoint" "cosmos_endpoint":
│  102: resource "azurerm_private_endpoint" "cosmos_endpoint" {
│
╵

### Steps to Reproduce

1. `terraform apply -auto-approve`

### Important Factoids

For now only create multiple private endpoints linked to the same cosmos db would complain this error.

According to the service team: "Due to a technical limitation, if multiple of these PrivateEndpoint resources are created in parallel that are associated with the same Cosmos DB account, the operations need to be serialized."

### References

* #0000

### PR DESCRIPTION
**Pull request by lonegunmanb**

### CODE REVIEW

**Comment by lonegunmanb** [comment]
Try add internal lock when private connection resource id is cosmosdb account id to fix #14364

File: internal/services/network/private_endpoint_resource.go [hunk 1]
```diff
@@ -281,6 +283,17 @@ func resourcePrivateEndpointCreate(d *pluginsdk.ResourceData, meta interface{})
 		Tags: tags.Expand(d.Get("tags").(map[string]interface{})),
 	}
 
+	cosmosDbResIds := getCosmosDbResIdInPrivateServiceConnections(parameters.PrivateEndpointProperties)
+	for _, cosmosDbResId := range cosmosDbResIds {
+		log.Printf("[DEBUG] Add Lock For Private Endpoint %q, lock name: %q", id.Name, cosmosDbResId)
+		locks.ByName(cosmosDbResId, "azurerm_private_endpoint")
+	}
```
Comment (katbyte) [inline internal/services/network/private_endpoint_resource.go:290]: could this not be
```suggestion
	for _, cosmosDbResId := range cosmosDbResIds {
		log.Printf("[DEBUG] Add Lock For Private Endpoint %q, lock name: %q", id.Name, cosmosDbResId)
		locks.ByName(cosmosDbResId, "azurerm_private_endpoint")
		defer locks.UnlockByName(cosmosDbResId, "azurerm_private_endpoint")
	}
```

Comment (lonegunmanb) [reply internal/services/network/private_endpoint_resource.go:290]: Hi @katbyte , I've tried defer in for loop and it would cause an IDE warning. Though we know that a for loop in defer is equal to defer in for, but I think the warning is annoying and want to avoid that. I'm ok with both implementations, which one do you prefer?
By the way, during my test there was a random error from time to time, i doubt there is some async logic on service side that could cause an error randomly and I'm querying the service team, and got no response yet. Once I've solved it I'll submit this pr formally.

Comment (katbyte) [reply internal/services/network/private_endpoint_resource.go:290]: what IDE warning do you get?

and sounds good

Comment (lonegunmanb) [reply internal/services/network/private_endpoint_resource.go:290]: JetBrains Goland would warn "Possible resource leak, 'defer' is called in the 'for' loop 
 Inspection info: Reports defer statements inside loops.
Using defer in loops can lead to resource leaks or unpredictable execution order of the statements."

I think it just want to avoid defer in a possibly infinity loop that caused resource leak or even worse a stackoverflow.

Comment (lonegunmanb) [reply internal/services/network/private_endpoint_resource.go:290]: And here's JetBrains's [link](https://www.jetbrains.com/help/go/code-inspections-in-go.html#Control_flow_issues).

Comment (katbyte) [reply internal/services/network/private_endpoint_resource.go:290]: its a valid warning however i don't think it applies in this case as we don't care about the order of the defer statements as long as they are called? - also as long as golang-ci doesn't flag it it should be ok?

Comment (lonegunmanb) [reply internal/services/network/private_endpoint_resource.go:290]: Roger that.

**Comment by lonegunmanb** [comment]
Hi @katbyte , I've move defer back into for loop as your suggestion. I'll check if multiple private endpoints linked to the same cosmosdb can be created successfully, but still no response from service team.

**Comment by katbyte** [comment]
Thanks @lonegunmanb - this looks good to me now so let me know when its no longer WIP and good to be merged

**Comment by lonegunmanb** [comment]
Hello @katbyte ,

Finally, we have solved the issue on our side. We've encountered an issue that would cause the second private endpoint's creation to fail randomly. After a long time's digging, we confirm that the issue was caused by some security policies set by our security team. The policy will modify the subnet temporarily, and that caused the failure.

After running the tests with my personal account (to get rid of these policies) for 24 hours I've seen no more random failures. 

Since this pr's codebase is old, I've rebased the branch to the latest main branch. I've re-run the acc tests, would you please give it another review? Thanks!

=== RUN   TestAccPrivateEndpoint_basic
=== PAUSE TestAccPrivateEndpoint_basic
=== CONT  TestAccPrivateEndpoint_basic
--- PASS: TestAccPrivateEndpoint_basic (357.11s)
=== RUN   TestAccPrivateEndpoint_updateTag
=== PAUSE TestAccPrivateEndpoint_updateTag
=== CONT  TestAccPrivateEndpoint_updateTag
--- PASS: TestAccPrivateEndpoint_updateTag (662.08s)
=== RUN   TestAccPrivateEndpoint_requestMessage
=== PAUSE TestAccPrivateEndpoint_requestMessage
=== CONT  TestAccPrivateEndpoint_requestMessage
--- PASS: TestAccPrivateEndpoint_requestMessage (400.68s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneGroup
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneGroup
=== CONT  TestAccPrivateEndpoint_privateDnsZoneGroup
--- PASS: TestAccPrivateEndpoint_privateDnsZoneGroup (459.28s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRename
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRename
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRename
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRename (598.36s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneUpdate
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneUpdate
=== CONT  TestAccPrivateEndpoint_privateDnsZoneUpdate
--- PASS: TestAccPrivateEndpoint_privateDnsZoneUpdate (710.57s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRemove
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRemove
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRemove
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRemove (636.85s)
=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias
=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
--- PASS: TestAccPrivateEndpoint_privateConnectionAlias (349.38s)
PASS

Process finished with the exit code 0

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @lonegunmanb - just have 1 failing test to address:
```
------- Stdout: -------
=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias
=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Private Endpoint "acctest-privatelink-220128031804283259" (Resource Group "acctestRG-privatelink-220128031804283259"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidPrivateLinkServiceId" Message="PrivateLinkServiceId Invalid private link service id: {0} passed in private link service connection: {1} passed in input is invalid" Details=[]
        
          with azurerm_private_endpoint.test,
          on terraform_plugin_test.tf line 80, in resource "azurerm_private_endpoint" "test":
          80: resource "azurerm_private_endpoint" "test" {
        
--- FAIL: TestAccPrivateEndpoint_privateConnectionAlias (204.76s)
FAIL
```

**Comment by lonegunmanb** [comment]
> TestAccPrivateEndpoint
Hi @katbyte , the tests passed on my machine:

=== RUN   TestAccPrivateEndpoint_basic
=== PAUSE TestAccPrivateEndpoint_basic
=== CONT  TestAccPrivateEndpoint_basic
--- PASS: TestAccPrivateEndpoint_basic (395.14s)
=== RUN   TestAccPrivateEndpoint_updateTag

=== PAUSE TestAccPrivateEndpoint_updateTag
=== CONT  TestAccPrivateEndpoint_updateTag
--- PASS: TestAccPrivateEndpoint_updateTag (618.40s)
=== RUN   TestAccPrivateEndpoint_requestMessage
=== PAUSE TestAccPrivateEndpoint_requestMessage
=== CONT  TestAccPrivateEndpoint_requestMessage
--- PASS: TestAccPrivateEndpoint_requestMessage (472.69s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneGroup
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneGroup
=== CONT  TestAccPrivateEndpoint_privateDnsZoneGroup
--- PASS: TestAccPrivateEndpoint_privateDnsZoneGroup (528.72s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRename
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRename
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRename
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRename (607.75s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneUpdate
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneUpdate
=== CONT  TestAccPrivateEndpoint_privateDnsZoneUpdate
--- PASS: TestAccPrivateEndpoint_privateDnsZoneUpdate (704.54s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRemove
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRemove
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRemove
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRemove (708.50s)
=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias

=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
--- PASS: TestAccPrivateEndpoint_privateConnectionAlias (372.75s)
PASS


Process finished with the exit code 0

I've triggered a re-run on TC, hope it's only a service side's glitch.

**Comment by lonegunmanb** [comment]
> Thanks @lonegunmanb - just have 1 failing test to address:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccPrivateEndpoint_privateConnectionAlias
> === PAUSE TestAccPrivateEndpoint_privateConnectionAlias
> === CONT  TestAccPrivateEndpoint_privateConnectionAlias
>     testcase.go:110: Step 1/2 error: Error running apply: exit status 1
>         
>         Error: creating Private Endpoint "acctest-privatelink-220128031804283259" (Resource Group "acctestRG-privatelink-220128031804283259"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidPrivateLinkServiceId" Message="PrivateLinkServiceId Invalid private link service id: {0} passed in private link service connection: {1} passed in input is invalid" Details=[]
>         
>           with azurerm_private_endpoint.test,
>           on terraform_plugin_test.tf line 80, in resource "azurerm_private_endpoint" "test":
>           80: resource "azurerm_private_endpoint" "test" {
>         
> --- FAIL: TestAccPrivateEndpoint_privateConnectionAlias (204.76s)
> FAIL
> ```

The tests worked fine in East US region, but failed in West Europe region. I've fired a support ticket to the support team.

**Comment by lonegunmanb** [comment]
Hello @katbyte , the branch `refs/pull/14398/merge` has passed all 8 tests on TC, I think the service team has fixed the issue, would you please give it another review? Thanks!

**Review by katbyte — APPROVED** [review]
@lonegunmanb - its still failing so i'm going to assume its flaky, probably should raise that with the service team but i'll merge this for now.
