### PR TITLE
`azurerm_cosmos_db_account` - `ip_range_filter` moved from string to List

### LINKED ISSUE #6439: IP filter for Azure Cosmos DB doesn't follow standards
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

12.x + 2.0.0/1.4

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
  ip_range_filter     = "1.1.1.1,2.2.2.2,3.3.3.3"
```

### Expected Behavior

The rules should either be formatted as a list

```hcl
  ip_range_filter     = ['1.1.1.1','2.2.2.2','3.3.3.3']
```

or as separate blocks or a mix of both (see MySQL, PostgreSQL, Network Security Groups)

### Actual Behavior

Terraform asked me to make a weird string with commas.

### Steps to Reproduce

Try to write a proper IP whitelist using list or blocks.

### PR DESCRIPTION
**Pull request by mbfrahry**
Fixes #6439

### CODE REVIEW

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
Left a couple of comments inline - but I think this is going to want to wait for 4.0 / be done gradually in a 3.x release

**Review by katbyte — APPROVED** [review]
LGTM 🧄

File: internal/services/cosmos/cosmosdb_account_resource_test.go [hunk 1]
```diff
@@ -738,6 +738,30 @@ func TestAccCosmosDBAccount_updateCapacity(t *testing.T) {
...
+			),
+		},
+		data.ImportStep(),
+	})
+}
+
+// todo remove for 4.0
+func TestAccCosmosDBAccount_vNetFiltersThreePointOh(t *testing.T) {
+	if features.FourPointOhBeta() {
+		t.Skip("this test requires 3.0 mode")
```
Comment (tombuildsstuff) [inline internal/services/cosmos/cosmosdb_account_resource_test.go:763]: 4.0 mode
