### PR TITLE
Fix regression in v2.91 `azurerm_virtual_desktop_host_pool` registration_info

### LINKED ISSUE #13793: Inconsistent final plan when a resource depends on `azurerm_virtual_desktop_host_pool`s `registration_info`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.81.0

### Affected Resource(s)

* `azurerm_virtual_desktop_host_pool`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "UK South"
}

resource "azurerm_virtual_desktop_host_pool" "example" {
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  name                     = "Example"
  friendly_name            = "Example"
  type                     = "Pooled"
  maximum_sessions_allowed = 10
  load_balancer_type       = "BreadthFirst"

  registration_info {
    expiration_date = timeadd(timestamp(), "1.1h")
  }
}

# This resource group just represents any resource that takes in the registration token from the hostpool
resource "azurerm_resource_group" "dependent" {
  name     = "dependent"
  location = "UK South"

  tags = {
    example = md5(azurerm_virtual_desktop_host_pool.example.registration_info[0].token)
  }
}
```

### Expected Behaviour
The Terraform should be able to run as many times as desired and update any fields that reference the token

### Actual Behaviour
The first apply will run fine but all subsequent apply's will produce an inconsistent plan

```
azurerm_resource_group.example: Refreshing state... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example]
azurerm_virtual_desktop_host_pool.example: Refreshing state... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example/providers/Microsoft.DesktopVirtualization/hostPools/Example]
azurerm_resource_group.dependent: Refreshing state... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/dependent]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_resource_group.dependent will be updated in-place
  ~ resource "azurerm_resource_group" "dependent" {
        id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/dependent"
        name     = "dependent"
      ~ tags     = {
          ~ "example" = (sensitive)
        }
        # (1 unchanged attribute hidden)
    }

  # azurerm_virtual_desktop_host_pool.example will be updated in-place
  ~ resource "azurerm_virtual_desktop_host_pool" "example" {
        id                       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example/providers/Microsoft.DesktopVirtualization/hostPools/Example"
        name                     = "Example"
        tags                     = {}
        # (9 unchanged attributes hidden)

      ~ registration_info {
          ~ expiration_date = "2021-10-19T15:10:58Z" -> (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_virtual_desktop_host_pool.example: Modifying... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example/providers/Microsoft.DesktopVirtualization/hostPools/Example]
azurerm_virtual_desktop_host_pool.example: Modifications complete after 0s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example/providers/Microsoft.DesktopVirtualization/hostPools/Example]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for azurerm_resource_group.dependent to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for .tags: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply` 

### Important Factoids

A work around I have used is to set the timestamp to midnight X number of days in the future but this isn't elegant as this results in at least one inconsistent plan a day

### References

Resolved by https://github.com/hashicorp/terraform-provider-azurerm/pull/14134

### LINKED ISSUE #14972: Behaviour of azurerm_virtual_desktop_host_pool has changed, token no longer available
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Issue first occurred in Provider 2.91.0

### Affected Resource(s)

* azurerm_virtual_desktop_host_pool

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "avd-test"
  location = "West Europe"
}

resource "time_offset" "time" {
    offset_days = 7
}

resource "azurerm_virtual_desktop_host_pool" "example" {
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  name                     = "pooleddepthfirst"
  friendly_name            = "pooleddepthfirst"
  validate_environment     = true
  start_vm_on_connect      = true
  custom_rdp_properties    = "audiocapturemode:i:1;audiomode:i:0;"
  description              = "Acceptance Test: A pooled host pool - pooleddepthfirst"
  type                     = "Pooled"
  maximum_sessions_allowed = 50
  load_balancer_type       = "DepthFirst"

  registration_info {
      expiration_date = resource.time_offset.time.rfc3339
  }
}

provider azurerm {
    features {}
}

#The use of the below resource is to expose the value of the token (which is not correct)
resource "azurerm_virtual_desktop_workspace" "workspace" {
  name                = "workspace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  friendly_name = azurerm_virtual_desktop_host_pool.example.registration_info[0].token
  description   = "A description of my workspace"
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.91.0"
    }
  }
}
# Changing this to 2.90.0 shows the expected behaviour
```

### Expected Behaviour

The value of azurerm_virtual_desktop_host_pool.example.registration_info[0].token should be a valid registration token. 

### Actual Behaviour

│   on main.tf line 38, in resource "azurerm_virtual_desktop_workspace" "workspace":
│   38:   friendly_name = azurerm_virtual_desktop_host_pool.example.registration_info[0].token
│     ├────────────────
│     │ azurerm_virtual_desktop_host_pool.example.registration_info is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.

### Steps to Reproduce

1. `terraform apply` - the token is no longer accessible

Without the token, we can't add hosts to the hostpool.
### References

* I suspect this is the source of the issue - https://github.com/hashicorp/terraform-provider-azurerm/issues/14188

### PR DESCRIPTION
**Pull request by amccullough84**
There is a regression in the 2.91 release which causes the registration_info block to not be read correctly from Hostpool Properties when using the new API version.

This PR updates the resource to use the new RetrieveRegistrationToken function which is introduced in the new API.

Fixes https://github.com/hashicorp/terraform/issues/30322

Acc Tests:

make acctests SERVICE='desktopvirtualization' TESTARGS='-run=TestAccVirtualDesktopHostPool' TESTTIMEOUT='30m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/desktopvirtualization -run=TestAccVirtualDesktopHostPool -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccVirtualDesktopHostPool_basic
=== PAUSE TestAccVirtualDesktopHostPool_basic
=== RUN   TestAccVirtualDesktopHostPool_complete
=== PAUSE TestAccVirtualDesktopHostPool_complete
=== RUN   TestAccVirtualDesktopHostPool_update
=== PAUSE TestAccVirtualDesktopHostPool_update
=== RUN   TestAccVirtualDesktopHostPool_requiresImport
=== PAUSE TestAccVirtualDesktopHostPool_requiresImport
=== CONT  TestAccVirtualDesktopHostPool_basic
=== CONT  TestAccVirtualDesktopHostPool_update
=== CONT  TestAccVirtualDesktopHostPool_requiresImport
=== CONT  TestAccVirtualDesktopHostPool_complete
--- PASS: TestAccVirtualDesktopHostPool_complete (117.76s)
--- PASS: TestAccVirtualDesktopHostPool_basic (177.84s)
--- PASS: TestAccVirtualDesktopHostPool_requiresImport (206.41s)
--- PASS: TestAccVirtualDesktopHostPool_update (223.91s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/desktopvirtualization 224.116s

Fixes #14972
Fixes #13793

### CODE REVIEW

File: internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go [hunk 1]
```diff
@@ -160,7 +160,7 @@ resource "azurerm_virtual_desktop_host_pool" "test" {
   }
   lifecycle {
     ignore_changes = [
-      registration_info,
+      registration_info[0].expiration_date,
```
Comment (katbyte) [inline internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go:163]: we probably shouldn't have this here - i assume this is the case because the value is not returned from the API? instead of doing an ignore changes can we instead pull the value across from config by doing a d.Get() and using that value?

Comment (katbyte) [reply internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go:163]: how come there should be a perpetual diff for that property? it looks like a required property on the resource so shouldn't change unless the user changes it?

Comment (amccullough84) [reply internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go:163]: The expiration_date attribute needs a future date/time to be valid and can't be set more than 30/31 days in the future.

The acceptance test resource provides this as:

`registration_info {
    expiration_date = timeadd(timestamp(), "48h")
  }`

As a result will always create a non-empty plan if we don't ignore changes in the test resource.

In practice this attribute will almost always be set to a dynamic future date as changing the expiration_date is required to generate a new valid token attribute (although this doesn't work as-is, but is fixed in https://github.com/hashicorp/terraform-provider-azurerm/pull/14134) so the test case is representative of real-world usage.

We could ignore non-empty plans, but that could mask other issues.

Comment (katbyte) [reply internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go:163]: ahh that makes sense, instead of generating the date in tf could we instead do it in go and then pass it into the test so we can remove the lifecycle ignore changes please?

**Comment by amccullough84** [comment]
Acceptance Tests:

**Comment by amccullough84** [comment]
make acctests SERVICE='desktopvirtualization' TESTARGS='-run=TestAccVirtualDesktopHostPool' TESTTIMEOUT='30m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/desktopvirtualization -run=TestAccVirtualDesktopHostPool -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccVirtualDesktopHostPool_basic
=== PAUSE TestAccVirtualDesktopHostPool_basic
=== RUN   TestAccVirtualDesktopHostPool_complete
=== PAUSE TestAccVirtualDesktopHostPool_complete
=== RUN   TestAccVirtualDesktopHostPool_update
=== PAUSE TestAccVirtualDesktopHostPool_update
=== RUN   TestAccVirtualDesktopHostPool_requiresImport
=== PAUSE TestAccVirtualDesktopHostPool_requiresImport
=== CONT  TestAccVirtualDesktopHostPool_basic
=== CONT  TestAccVirtualDesktopHostPool_update
=== CONT  TestAccVirtualDesktopHostPool_requiresImport
=== CONT  TestAccVirtualDesktopHostPool_complete
--- PASS: TestAccVirtualDesktopHostPool_complete (121.05s)
--- PASS: TestAccVirtualDesktopHostPool_basic (121.10s)
--- PASS: TestAccVirtualDesktopHostPool_requiresImport (151.07s)
--- PASS: TestAccVirtualDesktopHostPool_update (237.73s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/desktopvirtualization 238.087s

File: internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go (hunk 1 above)
Comment (amccullough84) [reply internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go]: Done!

File: internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go [hunk 2]
```diff
@@ -4,13 +4,15 @@ import (
...
 	"testing"
+	"time"
 
 	"github.com/hashicorp/terraform-provider-azurerm/internal/acceptance"
 	"github.com/hashicorp/terraform-provider-azurerm/internal/acceptance/check"
 	"github.com/hashicorp/terraform-provider-azurerm/internal/clients"
 	"github.com/hashicorp/terraform-provider-azurerm/internal/services/desktopvirtualization/parse"
 	"github.com/hashicorp/terraform-provider-azurerm/internal/tf/pluginsdk"
 	"github.com/hashicorp/terraform-provider-azurerm/utils"
+	// "github.com/Azure/go-autorest/autorest/date"
```
Comment (tombuildsstuff) [inline internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go:15]: we can remove this since it's not being used:

```suggestion
```

File: internal/services/desktopvirtualization/virtual_desktop_host_pool_resource.go [hunk 3]
```diff
@@ -265,7 +265,12 @@ func resourceVirtualDesktopHostPoolRead(d *pluginsdk.ResourceData, meta interfac
 		d.Set("start_vm_on_connect", props.StartVMOnConnect)
 		d.Set("custom_rdp_properties", props.CustomRdpProperty)
 
-		if err := d.Set("registration_info", flattenVirtualDesktopHostPoolRegistrationInfo(props.RegistrationInfo)); err != nil {
+		reginfo, err := client.RetrieveRegistrationToken(ctx, id.ResourceGroup, id.Name)
+		if err != nil {
+			return fmt.Errorf("Making Read request for registration token on Virtual Desktop Host Pool %q (Resource Group %q): %+v", id.Name, id.ResourceGroup, err)
```
Comment (tombuildsstuff) [inline internal/services/desktopvirtualization/virtual_desktop_host_pool_resource.go:270]: we can make this:

```suggestion
			return fmt.Errorf("retrieving Registration Token for %s: %+v", *id, err)
```

File: internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go [hunk 4]
```diff
@@ -59,7 +68,7 @@ func TestAccVirtualDesktopHostPool_update(t *testing.T) {
 			),
 		},
 		{
-			Config: r.complete(data),
+			Config: r.complete(data, expirationTime),
 			Check: acceptance.ComposeTestCheckFunc(
 				check.That(data.ResourceName).ExistsInAzure(r),
 				check.That(data.ResourceName).Key("tags.%").HasValue("1"),
```
Comment (tombuildsstuff) [inline internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go:74]: since we're validating that this has a value we should probably double-check that here?

```suggestion
				check.That(data.ResourceName).Key("tags.%").HasValue("1"),
				check.That(data.ResourceName).Key("registration_info.0.token").Exists(),
```

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hey @amccullough84 

Thanks for this PR - taking a look through on the whole this looks pretty good to me, but there's a few minor comments to fix up (including adding a check to ensure that the `token` field is explicitly set) but once those are fixed (and the tests pass) this should otherwise be good to merge 👍 

Thanks!

File: internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go (hunk 4 above)
Comment (amccullough84) [reply internal/services/desktopvirtualization/virtual_desktop_host_pool_resource_test.go:73]: Added to PR

**Comment by amccullough84** [comment]
Thanks for the review @tombuildsstuff - changes made and acceptance tests passing:

make acctests SERVICE='desktopvirtualization' TESTARGS='-run=TestAccVirtualDesktopHostPool' TESTTIMEOUT='30m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/desktopvirtualization -run=TestAccVirtualDesktopHostPool -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccVirtualDesktopHostPool_basic
=== PAUSE TestAccVirtualDesktopHostPool_basic
=== RUN   TestAccVirtualDesktopHostPool_complete
=== PAUSE TestAccVirtualDesktopHostPool_complete
=== RUN   TestAccVirtualDesktopHostPool_update
=== PAUSE TestAccVirtualDesktopHostPool_update
=== RUN   TestAccVirtualDesktopHostPool_requiresImport
=== PAUSE TestAccVirtualDesktopHostPool_requiresImport
=== CONT  TestAccVirtualDesktopHostPool_basic
=== CONT  TestAccVirtualDesktopHostPool_update
=== CONT  TestAccVirtualDesktopHostPool_requiresImport
=== CONT  TestAccVirtualDesktopHostPool_complete
--- PASS: TestAccVirtualDesktopHostPool_basic (92.81s)
--- PASS: TestAccVirtualDesktopHostPool_complete (95.06s)
--- PASS: TestAccVirtualDesktopHostPool_requiresImport (117.37s)
--- PASS: TestAccVirtualDesktopHostPool_update (188.59s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/desktopvirtualization 188.721s

**Comment by amccullough84** [comment]
Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/14972

**Comment by johnvanhienen** [comment]
What's the status of this PR? This issue prevents our environment from being able to run and the fix seems ready @tombuildsstuff ?

**Review by katbyte — CHANGES_REQUESTED** [review]
We have a test failure atm:
```
------- Stdout: -------
=== RUN   TestAccVirtualDesktopHostPoolRegInfo_update
=== PAUSE TestAccVirtualDesktopHostPoolRegInfo_update
=== CONT  TestAccVirtualDesktopHostPoolRegInfo_update
    testcase.go:110: Step 1/3 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_virtual_desktop_host_pool.test will be updated in-place
          ~ resource "azurerm_virtual_desktop_host_pool" "test" {
                id                       = "/subscriptions/*******/resourceGroups/acctestRG-vdesktop-220128031304514365/providers/Microsoft.DesktopVirtualization/hostPools/acctestHPdgnse"
                name                     = "acctestHPdgnse"
                tags                     = {}
                # (8 unchanged attributes hidden)
        
              - registration_info {
                  - expiration_date = "2022-01-29T03:13:04Z" -> null
                  - reset_token     = false -> null
                  - token           = (sensitive value)
                }
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccVirtualDesktopHostPoolRegInfo_update (102.55s)
FAIL
```

**Comment by amccullough84** [comment]
@katbyte Can't reproduce the test failure on my side, can we re-test please? Looks like something odd's happened there as for that step its a new resource which should does not have a registration_info block at all, so it's not clear how it's gotten a value back from the API for expiration_date as it should be null at that point.

TF_ACC=1 go test -v ./internal/services/desktopvirtualization -run=TestAccVirtualDesktopHostPool_update -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccVirtualDesktopHostPool_update
=== PAUSE TestAccVirtualDesktopHostPool_update
=== CONT  TestAccVirtualDesktopHostPool_update
--- PASS: TestAccVirtualDesktopHostPool_update (247.74s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/desktopvirtualization 247.906s

**Comment by stephybun** [comment]
Hi @amccullough84, I re-ran the tests but two are still failing with the same error message posted above.

image

**Comment by amccullough84** [comment]
OK, I can repro now against main but I'm now hitting an issue I think @tombuildsstuff foresaw...

The `registration_info` block implementation in this module is flawed as when used the token value will be out-of-sync after a second apply when using a time-span based expiry date as the value is computed so doesn't update when the expiry date changes. This is fixed by using the new `virtual_desktop_host_pool_registration_info` resource which does handle changes correctly. 

That tests fine against the current main as the API is returning null for the registration_info block, but when we fix the call we get a diff as the registration_info block has been changed by a separate resource.

The correct answer seems - people should use the new resource. So as a broader question - do we fix this?

Tom suggested changing registration_info to computed, but testing this we still get a diff as it's being modified by another resource:

` TestAccVirtualDesktopHostPoolRegInfo_basic
    testcase.go:110: Step 1/1 error: After applying this test step and performing a terraform refresh, the plan was not empty.
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # azurerm_virtual_desktop_host_pool.test will be updated in-place
          ~ resource "azurerm_virtual_desktop_host_pool" "test" {
                id                       = "/subscriptions/70e666b2-af2f-xxxx-xxxx-xxxxxxxxxx/resourceGroups/acctestRG-vdesktop-220202173438288595/providers/Microsoft.DesktopVirtualization/hostPools/acctestHP4myqi"
                name                     = "acctestHP4myqi"
                tags                     = {}
                # (8 unchanged attributes hidden)

              - registration_info {
                  - expiration_date = "2022-02-03T17:34:38Z" -> null
                  - reset_token     = false -> null
                  - token           = (sensitive value)
                }
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
`

I think there are three options here:

1 - Leave it broken as-is, mark as deprecated and steer towards the new resource
2 - Remove the registration_info block from the `virtual_desktop_host_pool` resource entirely skipping deprecation (this would be the nuclear option)
3 - Workaround the conflict to allow the use of the registration_info block to be deprecated while restoring previous functionality.

Playing with option 3 - we can co-exist by checking whether a registration_info block has been specified in the virtual_desktop_host_pool resource before we create/update/read the data from the API - we already have a warning in the docs that both should not be used at the same time, so that seems as though it would meet expectations - for example

Create/Update:

`
if _, ok := d.GetOk("registration_info"); ok {
	context.HostPoolProperties.RegistrationInfo = expandVirtualDesktopHostPoolRegistrationInfo(d)
}
`

Read:

`
if _, ok := d.GetOk("registration_info"); ok {

	reginfo, err := client.RetrieveRegistrationToken(ctx, id.ResourceGroup, id.Name)

	if err != nil {

		return fmt.Errorf("retrieving Registration Token for %s: %+v", *id, err)

	}

	if err := d.Set("registration_info", flattenVirtualDesktopHostPoolRegistrationInfo(&reginfo)); err != nil {

		return fmt.Errorf("setting registration_info: %+v", err)

	}

}
`

This approach tests OK, and allows us to mark it as deprecated, but wanted to check if this was a good approach or if there's something else I should be considering?

**Comment by tombuildsstuff** [comment]
hey @amccullough84 

Sorry for the delay re-review this one - digging into this there's a number of subtle bugs with these resources which I think are affecting the tests here. It turns out that the tests for the Registration Info depend on which timezone you're running them in - which I think is causing extra confusion here (since our CI server runs on UTC time).

Whilst we could look to try and fix this functionality within the `azurerm_virtual_desktop_host_pool` resource, since the API is no longer returning this information via this endpoint (so this change has already gone out) and since this field isn't directly usable in all cases - I think it's probably better to continue with this forced-deprecation in favour of the separate resource, rather than trying to fix this for a short time.

As such I hope you don't mind but I've pulled this down locally to work through this and so I've also made those changes - conditionally removing the `registration_info` field in 3.0 and explicitly setting it to an empty list in 2.x mode - with a deprecation message to push users across to the separate resource.

Whilst that's not ideal, unfortunately I think that's the "least bad thing" to do at this point - as reintroducing this broken field would leave users with the error seen in #13793 which they'd need to workaround by migrating to the separate resource anyway.

Thanks!

**Review by katbyte — APPROVED** [review]
LGTM 🧊

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2022-02-16 at 11 14 45
