### PR TITLE
`azurerm_eventhub` - seperate update and create and add check for sku

### LINKED ISSUE #13557: Resizing the partitions of eventhubs in Premium and Dedicated SKU eventhub_namespaces causes destroy & recreate
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.13.4
azurerm 2.77.0

### Affected Resource(s)

* `azurerm_eventhub`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "example" {
  name                = "acceptanceTestEventHubNamespace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Premium"
  capacity            = 1

  tags = {
    environment = "Production"
  }
}

resource "azurerm_eventhub" "example" {
  name                = "acceptanceTestEventHub"
  namespace_name      = azurerm_eventhub_namespace.example.name
  resource_group_name = azurerm_resource_group.example.name
  partition_count     = 2
  message_retention   = 1
}
```

### Expected Behaviour

As per [this Azure documentation on dynamically adding partitions](https://docs.microsoft.com/en-us/azure/event-hubs/dynamically-add-partitions), for **Premium** and **Dedicated** SKUs of eventhub namespaces, the number of partitions for an eventhub can be changed dynamically, i.e. without the need to delete and recreate the eventhub.

### Actual Behaviour

The plan showed that the eventhub would need to be destroyed and recreated.

It's clear to see from the code [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/eventhub/eventhub_resource.go#L63) why this behaviour exists. This is also HEAD of master and so I am assuming it persists. This line here should be conditional, I would guess.

### Steps to Reproduce

1. Create an eventhub_namespace with a "Premium" SKU
2. Create an eventhub in that namespace with X partitions
3. plan and apply
4. Change the number of partitions to Y (where X != Y)
5. Run `terraform plan`; you don't have to apply to see that it's going to destroy and recreate.

### References

* #0000

### PR DESCRIPTION
**Pull request by catriona-m**
fixes #13557

### CODE REVIEW

File: internal/services/eventhub/eventhub_resource.go [hunk 1]
```diff
@@ -173,16 +172,52 @@ func resourceEventHubCreateUpdate(d *pluginsdk.ResourceData, meta interface{}) e
...
+	messageRetention := int64(d.Get("message_retention").(int))
+	eventhubStatus := eventhubs.EntityStatus(d.Get("status").(string))
+
+	parameters := eventhubs.Eventhub{
+		Properties: &eventhubs.EventhubProperties{
+			PartitionCount:         &partitionCount,
+			MessageRetentionInDays: &messageRetention,
+			Status:                 &eventhubStatus,
+		},
+	}
```
Comment (katbyte) [inline internal/services/eventhub/eventhub_resource.go:185]: we can combine this?
```suggestion
	parameters := eventhubs.Eventhub{
		Properties: &eventhubs.EventhubProperties{
			PartitionCount:         int64(d.Get("partition_count").(int)),
			MessageRetentionInDays: int64(d.Get("message_retention").(int)),
			Status:                 eventhubs.EntityStatus(d.Get("status").(string)),
		},
	}
```

File: internal/services/eventhub/eventhub_resource.go [hunk 2]
```diff
@@ -192,13 +227,13 @@ func resourceEventHubCreateUpdate(d *pluginsdk.ResourceData, meta interface{}) e
 
 	parameters := eventhubs.Eventhub{
 		Properties: &eventhubs.EventhubProperties{
-			PartitionCount:         &partitionCount,
 			MessageRetentionInDays: &messageRetention,
+			PartitionCount:         &partitionCount,
```
Comment (katbyte) [inline internal/services/eventhub/eventhub_resource.go:231]: same here

**Review by katbyte — APPROVED** [review]
Aside from 1 comment this LGTM 🏗️
