### PR TITLE
`azurerm_role_management_policy` New resource & data source

### LINKED ISSUE #19912: Support for role PIM Role Assignments
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Through the Terraform AzureRM provider it isn't currently possible to assign PIM roles to Azure resources. Using AzAPI you can use the `Microsoft.Authorization/roleEligibilityScheduleRequests` resource type, but that then means all deployments required the AzAPI provider configuration.

It would be really helpful to have this natively in AzureRM to easily allow the zero trust/secure by design environments to easily be deployed.

Having separate resource type for the assignment would be beneficial, as the same API/resource type can be used to both assign a PIM role and also activate it.

### New or Affected Resource(s)/Data Source(s)

azurerm_role_eligibility_assignment

### Potential Terraform Configuration

```hcl
resource "azurerm_role_eligibility_assignment" "demo" {
  name = "string"
  scope = "string"
  principalId = "string"
  requestType = "string"
  roleDefinitionId = "string"
}
```

### References

https://learn.microsoft.com/en-us/azure/templates/microsoft.authorization/roleeligibilityschedulerequests?tabs=bicep&pivots=deployment-language-terraform

### LINKED ISSUE #22766: azurerm_pim_eligible_role_assignment 400 error when using null or empty schedule block
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_pim_eligible_role_assignment

### Terraform Configuration Files

```hcl
variable "teams" {
  type = map(object({
    team_name            = string
    location             = string
    Owner                = string
    TechnicalContact     = string
    SecurityGroup        = string
    DepartmentName       = string
    City                 = string
    ApplicationGroupType = string
    ApplicationType      = string
    LoadBalancerType     = string
    VDIType = string
    MaximumSessions      = number
  }))
}

resource "azurerm_resource_group" "vdi-rg" {
  for_each = var.teams
  name     = "${each.value.team_name}-VDI"
  location = coalesce(each.value.location, each.key)
  tags = {
    Owner            = coalesce(each.value.Owner, each.key)
    TechnicalContact = coalesce(each.value.TechnicalContact, each.key)
    Location         = coalesce(each.value.City, each.key)
    DepartmentName   = coalesce(each.value.DepartmentName, each.key)
    TeamName         = coalesce(each.value.team_name, each.key)
  }
}

resource "azurerm_pim_eligible_role_assignment" "role-vdi-vmadminpim" {
    for_each             = var.teams
  scope                = "/subscriptions/3f51eae4-8db3-468d-a09d-cb67d67630b4/resourceGroups/${azurerm_resource_group.vdi-rg[each.key].name}"
  role_definition_id = "/subscriptions/3f51eae4-8db3-468d-a09d-cb67d67630b4/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4"
  principal_id       = coalesce(each.value.SecurityGroup, each.key)

  timeouts {
    create = "10m"
    delete = "10m"
  }
     lifecycle {
    ignore_changes = [
      # Ignore changes to the Schedule block.  It won't take nulls as inputs and we assume that these PIM assignments are meant to live as long as the VDI environment.
      schedule
    ]
  }
}
```

### Debug Output/Panic Output

```shell
{"error":{"code":"RoleAssignmentRequestPolicyValidationFailed","message":"The following policy rules failed: [\"ExpirationRule\"]"}}: timestamp=2023-08-01T14:39:22.604-0400
2023-08-01T14:39:22.604-0400 [ERROR] provider.terraform-provider-azurerm_v3.67.0_x5.exe: Response contains error diagnostic: tf_req_id=15f63ca5-4bae-bb46-8ed2-2225d57fce01 diagnostic_detail="waiting for Role Management Policy: (Principal Id "01b95094-3727-42de-9bfe-f1bd55734554" / Scope "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName" / Role Definition Id "/subscriptions/ourSubscriptionGUID/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4") to be created: creating Scoped Role Eligibility Schedule Request (Scope: "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName"
Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed: ["ExpirationRule"]" diagnostic_severity=ERROR tf_proto_version=5.3 tf_provider_addr=provider tf_resource_type=azurerm_pim_eligible_role_assignment tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto diagnostic_summary="waiting for Role Management Policy: (Principal Id "01b95094-3727-42de-9bfe-f1bd55734554" / Scope "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName" / Role Definition Id "/subscriptions/ourSubscriptionGUID/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4") to be created: creating Scoped Role Eligibility Schedule Request (Scope: "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName"
Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed: ["ExpirationRule"]" timestamp=2023-08-01T14:39:22.604-0400
2023-08-01T14:39:22.606-0400 [DEBUG] State storage *remote.State declined to persist a state snapshot
2023-08-01T14:39:22.606-0400 [ERROR] vertex "azurerm_pim_eligible_role_assignment.role-vdi-vmadminpim[\"Team12\"]" error: waiting for Role Management Policy: (Principal Id "01b95094-3727-42de-9bfe-f1bd55734554" / Scope "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName" / Role Definition Id "/subscriptions/ourSubscriptionGUID/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4") to be created: creating Scoped Role Eligibility Schedule Request (Scope: "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName"
Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed: ["ExpirationRule"]
2023-08-01T14:39:22.609-0400 [DEBUG] provider.terraform-provider-azurerm_v3.67.0_x5.exe: AzureRM Response for https://management.azure.com/subscriptions/ourSubscriptionGUID/resourceGroups/rgName/providers/Microsoft.DesktopVirtualization/workspaces/MTDJumpbox-workspace?api-version=2022-02-10-preview: 
HTTP/2.0 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Tue, 01 Aug 2023 18:39:22 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/10.0
Set-Cookie: ARRAffinity=70e38c1ed72db5f7ffb204484a71ad78c423ea1a8a3bd749fefcc9c77560a9e4;Path=/;HttpOnly;Secure;Domain=rdarmprovider-g-us-r0.wvd.microsoft.com
Set-Cookie: ARRAffinitySameSite=70e38c1ed72db5f7ffb204484a71ad78c423ea1a8a3bd749fefcc9c77560a9e4;Path=/;HttpOnly;SameSite=None;Secure;Domain=rdarmprovider-g-us-r0.wvd.microsoft.com
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding,Accept-Encoding
X-Content-Type-Options: nosniff
X-Ms-Correlation-Id: 1d896bed-0d5a-45f7-ae79-c4d750973911
X-Ms-Correlation-Request-Id: 659d0fb3-bdf6-95a8-8b49-f1a84a113662
X-Ms-Lamport-Ts: 4474978300
X-Ms-Opsarmpath64: L3N1YnNjcmlwdGlvbnMvM2Y1MWVhZTQtOGRiMy00NjhkLWEwOWQtY2I2N2Q2NzYzMGI0L3Jlc291cmNlR3JvdXBzL01UREp1bXBib3gtVkRJL3Byb3ZpZGVycy9NaWNyb3NvZnQuRGVza3RvcFZpcnR1YWxpemF0aW9uL3dvcmtzcGFjZXMvTVRESnVtcGJveC13b3Jrc3BhY2U=
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11999
X-Ms-Request-Id: 15593fae-ccf4-4bc6-9040-2e4a9c4f28f8
X-Ms-Routing-Request-Id: EASTUS:20230801T183922Z:ec7d62d7-3fa1-45ab-bb1b-2d2983b2620c
X-Powered-By: ASP.NET
X-Rate-Limit-Limit: 0
X-Rate-Limit-Remaining: 9223372036854775807
X-Rate-Limit-Reset: 0
```

### Expected Behaviour

Terraform should create an Azure AD PIM eligible role with no expiration date/time.

### Actual Behaviour

Terraform throws an error: 
│ Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed: ["ExpirationRule"]
│
│   with azurerm_pim_eligible_role_assignment.role-vdi-vmadminpim["Team12"],
│   on AzureVDI.tf line 56, in resource "azurerm_pim_eligible_role_assignment" "role-vdi-vmadminpim":
│   56: resource "azurerm_pim_eligible_role_assignment" "role-vdi-vmadminpim" {
│
│ waiting for Role Management Policy: (Principal Id "01b95094-3727-42de-9bfe-f1bd55734554" / Scope "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName" / Role Definition Id     
│ "/subscriptions/ourSubscriptionGUID/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4") to be created: creating Scoped Role Eligibility Schedule        
│ Request (Scope: "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName"
│ Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed:
│ ["ExpirationRule"]

### Steps to Reproduce

1. Run terraform apply
2. Error occurs

### Important Factoids

_No response_

### References

Possibly related to #22608 - that threw a 400 error but with different error text.

### LINKED ISSUE #23458: Support for Azure resource role settings (related to/complementary to azurerm_pim_eligible_role_assignment)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Privileged Identity Management has a [series of settings for each role assignment](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-resource-roles-configure-role-settings) at each scope: management group, subscription, resource group, or resource.  These PIM settings govern details such as how long PIM eligibility lasts, approvals required, etc.  

Terraform recently released the ability to assign Azure resource roles to PIM via azurerm_pim_eligible_role_assignment, but there's no way to set resource role settings from Terraform.  Some use cases involve PIM eligible assignments that are permanent or longer than the 1 year default, and we have to create the resource group then manually change it in order to get PIM to work.  The same goes for PIM assignments where different approval or notification workflows are required.  

We should be able to set these role settings via Terraform.  The settings should all be optional, with separate blocks for approvals or other future workflows that have more than just bool/int/string values.  

### New or Affected Resource(s)/Data Source(s)

azurerm_pim_eligible_role_assignment

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "test-rg" {
name = "foobar"
location = "test"
}

resource "azurerm_pim_eligible_role_assignment" "test-assignment" { 
scope = azurerm_resource_group.test-rg.name
role_definition_id = "/subscriptions/ourSubscriptionGUID/providers/Microsoft.Authorization/roleDefinitions/roleDefinitionGUID"
principal_id = "guidOfSecurityGroup"
  schedule {
    start_date_time = "2023-10-02T17:00:00Z"
    expiration {
      end_date_time = "2099-10-02T17:22:00Z"
    }
}

resource "azurerm_pim_eligible_role_settings" "test-settings" { 
activation_maximum_duration = "integerValueOfHours"
allow_permanent_eligible_assignment = "true"
require_mfa_on_activation = "true"
require_justification_on_activation = "true"
require_approval_for_activation = "true"
approval {
list_of_approvers = ["emailA","emailB"]
}
```

### References

Identified via/related to #22766 
#23432 is tangentially related

### PR DESCRIPTION
**Pull request by oWretch**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Add support for managing the policies for PIM assignments to Azure resources. Based on the work in hashicorp/terraform-provider-azuread#1327.

Closes #23295 as this has not been updated for 7 months and has merge conflicts with main. I also thought code consistency would be nice between providers. Also closes #20496.

Fixes #19912, fixes #22766, fixes #23458, fixes hashicorp/terraform-provider-azuread#1186

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```shell
terraform-provider-azurerm % make acctests SERVICE='authorization' TESTARGS='-run="TestRoleManagementPolicy(DataSource)?_"' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/authorization -run="TestRoleManagementPolicy(DataSource)?_" -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestRoleManagementPolicyDataSource_resourceGroup
=== PAUSE TestRoleManagementPolicyDataSource_resourceGroup
=== RUN   TestRoleManagementPolicyDataSource_managementGroup
=== PAUSE TestRoleManagementPolicyDataSource_managementGroup
=== RUN   TestRoleManagementPolicy_resourceGroup
=== PAUSE TestRoleManagementPolicy_resourceGroup
=== RUN   TestRoleManagementPolicy_managementGroup
=== PAUSE TestRoleManagementPolicy_managementGroup
=== CONT  TestRoleManagementPolicyDataSource_resourceGroup
=== CONT  TestRoleManagementPolicy_resourceGroup
=== CONT  TestRoleManagementPolicy_managementGroup
=== CONT  TestRoleManagementPolicyDataSource_managementGroup
--- PASS: TestRoleManagementPolicyDataSource_managementGroup (87.60s)
--- PASS: TestRoleManagementPolicy_managementGroup (126.46s)
--- PASS: TestRoleManagementPolicyDataSource_resourceGroup (134.63s)
--- PASS: TestRoleManagementPolicy_resourceGroup (241.30s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/authorization 244.468s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_role_management_policy ` - new resource [GH-25900]
* `azurerm_role_management_policy ` - new data source [GH-25900]

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

### CODE REVIEW

File: internal/services/authorization/role_management_policy_resource.go [hunk 1]
```diff
@@ -0,0 +1,1097 @@
...
+				return fmt.Errorf("decoding %+v", err)
+			}
+
+			id := parse.NewRoleManagementPolicyID(config.Scope, "")
+			roleDefinitionId := config.RoleDefinitionId
+
+			scopedId, err := getScopedPolicyId(ctx, metadata, id, roleDefinitionId)
+			if err != nil {
+				return err
+			}
```
Comment (manicminer) [inline internal/services/authorization/role_management_policy_resource.go:383]: I'm not sure I follow why two parsers are being used here when `parse.RoleManagementPolicyId{}` and `rolemanagementpolicies.RoleManagementPolicyId{}` appear to have the same structure?

Can we not use `rolemanagementpolicies.RoleManagementPolicyId{}` (i.e. `scopedId`) as the resource ID rather than the `Id` field in the response, which seems to change on every update to the policy?

File: internal/services/authorization/role_management_policy_resource.go [hunk 2]
```diff
@@ -0,0 +1,1097 @@
...
+	// If it wasn't found (or no resource ID was provided), we need to search for the policy ID
+	resp, err := metadata.Client.Authorization.RoleManagementPolicyAssignmentsClient.ListForScope(ctx, commonids.NewScopeID(id.Scope))
+	if err != nil {
+		return nil, fmt.Errorf("failed to list Role Management Policy Assignments for scope %s. %+v", id.Scope, err)
+	}
+
+	for _, assignment := range *resp.Model {
+		if *assignment.Properties.RoleDefinitionId == roleDefinitionId {
+			parts := strings.Split(*assignment.Properties.PolicyId, "/providers/Microsoft.Authorization/roleManagementPolicies/")
+			scopedId := pointer.To(rolemanagementpolicies.NewScopedRoleManagementPolicyID(parts[0], parts[1]))
```
Comment (manicminer) [inline internal/services/authorization/role_management_policy_resource.go:1031]: Can we use a parser here rather than manually splitting the string? If we have do this, we'll also need to length check `parts` to avoid a potential crash.

File: internal/services/authorization/role_management_policy_resource.go [hunk 3]
```diff
@@ -0,0 +1,1097 @@
...
+		"assignee_notifications": {
+			Description: "Assignee notification settings",
+			Type:        pluginsdk.TypeList,
+			Optional:    true,
+			Computed:    true,
+			MaxItems:    1,
+			Elem: &pluginsdk.Resource{
+				Schema: notificationSettingsSchema(),
+			},
+		},
```
Comment (manicminer) [inline internal/services/authorization/role_management_policy_resource.go:1070]: Can we space these out per the schema above for readability? :)

```suggestion
		"admin_notifications": {
			Description: "Admin notification settings",
			Type:        pluginsdk.TypeList,
			Optional:    true,
			Computed:    true,
			MaxItems:    1,
			Elem: &pluginsdk.Resource{
				Schema: notificationSettingsSchema(),
			},
		},

		"approver_notifications": {
			Description: "Approver notification settings",
			Type:        pluginsdk.TypeList,
			Optional:    true,
			Computed:    true,
			MaxItems:    1,
			Elem: &pluginsdk.Resource{
				Schema: notificationSettingsSchema(),
			},
		},

		"assignee_notifications": {
			Description: "Assignee notification settings",
			Type:        pluginsdk.TypeList,
			Optional:    true,
			Computed:    true,
			MaxItems:    1,
			Elem: &pluginsdk.Resource{
				Schema: notificationSettingsSchema(),
			},
		},
```

File: internal/services/authorization/role_management_policy_resource.go [hunk 4]
```diff
@@ -0,0 +1,1097 @@
...
+			Required:     true,
+			ValidateFunc: validation.StringInSlice([]string{"All", "Critical"}, false),
+		},
+		"default_recipients": {
+			Description: "Whether the default recipients are notified",
+			Type:        pluginsdk.TypeBool,
+			Required:    true,
+		},
+		"additional_recipients": {
+			Description: "The additional recipients to notify",
```
Comment (manicminer) [inline internal/services/authorization/role_management_policy_resource.go:1088]: (as above)

File: internal/services/authorization/role_management_policy_data_source.go [hunk 5]
```diff
@@ -0,0 +1,595 @@
...
+	return &RoleManagementPolicyDataSourceModel{}
+}
+
+func (r RoleManagementPolicyDataSource) Arguments() map[string]*pluginsdk.Schema {
+	return map[string]*pluginsdk.Schema{
+		"scope": {
+			Description:  "The scope of the role to which this policy will apply",
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ForceNew:     true,
```
Comment (manicminer) [inline internal/services/authorization/role_management_policy_data_source.go:118]: ForceNew is not needed for a data source

File: internal/services/authorization/role_management_policy_data_source.go [hunk 6]
```diff
@@ -0,0 +1,595 @@
...
+			ValidateFunc: validation.StringStartsWithOneOf("/subscriptions/", "/providers/Microsoft.Management/managementGroups/"),
+		},
+
+		"role_definition_id": {
+			Description:  "ID of the Azure Role to which this policy is assigned",
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ForceNew:     true,
```
Comment (manicminer) [inline internal/services/authorization/role_management_policy_data_source.go:126]: (as above)

File: website/docs/r/role_management_policy.html.markdown [hunk 7]
```diff
@@ -0,0 +1,221 @@
...
+```
+
+## Argument Reference
+
+* `activation_rules` - (Optional) An `activation_rules` block as defined below.
+* `active_assignment_rules` - (Optional) An `active_assignment_rules` block as defined below.
+* `eligible_assignment_rules` - (Optional) An `eligible_assignment_rules` block as defined below.
+* `notification_rules` - (Optional) A `notification_rules` block as defined below.
+* `role_definition_id` - (Required) The scoped Role Definition ID of the role for which this policy will apply
+* `scope` - (Required) The scope to which this Role Management Policy will apply. Can be any scope where a role assignment can be made.
```
Comment (manicminer) [inline website/docs/r/role_management_policy.html.markdown:122]: A note about the ForceNew should be added for these.

```suggestion
* `role_definition_id` - (Required) The scoped Role Definition ID of the role for which this policy will apply. Changing this forces a new resource to be created.
* `scope` - (Required) The scope to which this Role Management Policy will apply. Can be any scope where a role assignment can be made. Changing this forces a new resource to be created.
```

File: internal/services/authorization/role_management_policy_resource.go [hunk 8]
```diff
@@ -0,0 +1,1097 @@
...
+			}
+
+			return metadata.Encode(&state)
+		},
+	}
+}
+
+func (r RoleManagementPolicyResource) Update() sdk.ResourceFunc {
+	return sdk.ResourceFunc{
+		Timeout: 5 * time.Minute,
```
Comment (manicminer) [inline internal/services/authorization/role_management_policy_resource.go:616]: Should this timeout be longer, perhaps the same as the Create timeout?

```suggestion
		Timeout: 30 * time.Minute,
```

File: website/docs/r/role_management_policy.html.markdown [hunk 9]
```diff
@@ -0,0 +1,221 @@
...
+```
+
+## Timeouts
+
+The `timeouts` block allows you to specify [timeouts](https://www.terraform.io/language/resources/syntax#operation-timeouts) for certain actions:
+
+* `create` - (Defaults to 30 minutes) Used when creating the Role Definition.
+* `update` - (Defaults to 60 minutes) Used when updating the Role Definition.
+* `read` - (Defaults to 5 minutes) Used when retrieving the Role Definition.
+* `delete` - (Defaults to 30 minutes) Used when deleting the Role Definition.
```
Comment (manicminer) [inline website/docs/r/role_management_policy.html.markdown:221]: These timeouts don't match those in the resource :)

File: internal/services/authorization/parse/role_management_policy.go [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+		return nil, fmt.Errorf("invalid role management policy ID: %s", id)
+	}
+
+	return NewRoleManagementPolicyID(parts[0], parts[1]), nil
+}
+
+func (id RoleManagementPolicyId) ID() string {
+	fmtString := "%s/providers/Microsoft.Authorization/roleManagementPolicies/%s"
+	return fmt.Sprintf(fmtString, id.Scope, id.Name)
+}
```
[the remark this answers is not in the document]
Comment (oWretch) [reply internal/services/authorization/parse/role_management_policy.go:36]: Yeah that makes sense 🤦

File: internal/services/authorization/role_management_policy_resource.go [hunk 11]
```diff
@@ -0,0 +1,1097 @@
...
+}
+
+func (r RoleManagementPolicyResource) Arguments() map[string]*pluginsdk.Schema {
+	return map[string]*pluginsdk.Schema{
+		"scope": {
+			Description:  "The scope of the role to which this policy will apply",
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ForceNew:     true,
+			ValidateFunc: validation.StringStartsWithOneOf("/subscriptions/", "/providers/Microsoft.Management/managementGroups/"),
```
[the remark this answers is not in the document]
Comment (oWretch) [reply internal/services/authorization/role_management_policy_resource.go:119]: Ahh yes - I like finding these nuggets of prebuilt goodness 🙂

**Comment by oWretch** [comment]
@manicminer I realised today I hadn't answered all your feedback. I think I have it all updated now.

**Review by manicminer — APPROVED** [review]
Hi @oWretch, thanks for circling back and making those changes. The updated `buildRoleManagementPolicyForUpdate()` function looks great 👍 

I've spent some time reviewing and testing, and whilst I originally had some more changes to request, once I starting digging a bit more into the APIs I realised that it would be dificult to communicate - so I've gone ahead and made some updates to get this ready, which I've summarized here:

- I noticed that the response payloads to the List operations to retrieve the policy assignments were coming in at 4-8MB each (!!). It also seems that the SDK doesn't support filtering on the `roleManagementPolicyAssignments` endpoint (presumably the API specs don't advertise it), so I reworked the resource to use only the `roleManagementPolicies` endpoint (incidentally, the List response payloads here are also in the multi-MB range, though a bit less than `roleManagementPolicyAssignments`), where we can use a `$filter` query parameter to filter on the role definition ID.
- Doing this means that responses are down to a few KB, drastically improving performance of the resource, but that we also need to save the role definition ID to state as part of the resource ID. I've added a custom ID type `RoleManagementPolicyId` which captures the `scope` and the `role_definition_id`, this enables us to perform a quick search with the new `FindRoleManagementPolicyId()` function whenever we need to get the latest policy. Given that the policy ID changes every time it is modified, this also provides us with a stable resource ID.
- The data source however, can continue to use the `rolemanagementpolicies.ScopedRoleManagementPolicyId` type since it does not matter if this changes at refresh time.
- Validating `role_definition_id` is tricky since it seems certain role definitions (looking at management groups in particular) are not scoped at all, so the ID types validation in the SDK fails to parse these, as does `parse.RoleDefinitionId` which is used in the `azurerm_role_definition` resource. Some definite inconsistency from the APIs here. I've opted to forego validation here (save for ensuring it's not empty), and I will follow up with another PR to consolidate the scattered logic around role definition IDs in the `authorization` package - else we will end up with _yet another_ ID type to add to the confusion.
- I've updated the validation for `scope` to only support management groups, subscriptions and resource groups at this time. If it becomes clear that other resource types expost role management policies, we can add support for those individually (ensuring we have test coverage as we go).
- I removed the `display_name` attribute from the resource and the data source, since in my testing this doesn't actually exist and seems to be a ghost field from the API specs.
- I've added test cases for subscription policies since it's important to ensure coverage for these too.

With all that said, since I've made considerable changes, and as I have been staring at this for awhile, I'm going to request a secondary review from another contributor. Pending their review, I'm happy to merge this. Thanks again for your work on this!

File: internal/services/authorization/role_management_policy.go [hunk 12]
```diff
@@ -0,0 +1,634 @@
...
+			}
+
+			var isEnabled bool
+			if _, set := metadata.ResourceData.GetOk("activation_rules.0.required_conditional_access_authentication_context"); set {
+				isEnabled = true
+				if len(model.ActivationRules) == 1 {
+					claimValue = model.ActivationRules[0].RequireConditionalAccessContext
+				}
+			} else {
+				isEnabled = false
```
Comment (mbfrahry) [inline internal/services/authorization/role_management_policy.go:313]: We could simplify this by starting with isEnabled is false

File: internal/services/authorization/role_management_policy.go [hunk 13]
```diff
@@ -0,0 +1,634 @@
...
+	}
+
+	if level != data.NotificationLevel {
+		level = data.NotificationLevel
+	}
+	if defaultRecipients != data.DefaultRecipients {
+		defaultRecipients = data.DefaultRecipients
+	}
+	if recipientChange {
+		additionalRecipients = data.AdditionalRecipients
```
Comment (mbfrahry) [inline internal/services/authorization/role_management_policy.go:575]: Are we losing recipient information with this? We're doing quite a bit of work [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/25900/commits/908d91cd2048dc267c138d06a4a829dcff37cb5a#diff-9996d5f0c36b15af9ef029fd994ed24509a0b1ad5e66f1b4f40beaa0c0189d5dR560) and then overwriting it if `recipientChange` is true. Did we want to append instead of overwrite or is this correct?

**Review by mbfrahry — APPROVED** [review]
Hey @manicminer, gave it a review and it looks good! Just had a couple comments to confirm but other than that, I think we're good!

File: internal/services/authorization/role_management_policy.go (hunk 13 above)
Comment (manicminer) [reply internal/services/authorization/role_management_policy.go:575]: I think this is OK, on lines 560-566 we're populating with any existing additional recipients as retrieved from the policy prior to updating, and here we're selectively replacing them if the property changed in the config (it seems they'll be removed if you just don't specify them in the Update request).

File: internal/services/authorization/role_management_policy.go (hunk 12 above)
Comment (manicminer) [reply internal/services/authorization/role_management_policy.go:313]: Good shout, will tidy this up 👍

**Comment by manicminer** [comment]
Test results

Screenshot 2024-06-13 at 22 09 54

**Comment by oWretch** [comment]
Thanks for that thorough review @manicminer. And I agree with your sentiments - the Azure API for role management could be far better than it is. One might think three versions would be enough to sort some of that out 🙂

**Comment by celsocoutinho-tangany** [comment]
This is awesome! But is it fair to assume that it is currently not possible to provision `azurerm_role_management_policy` on a resource-level, rather than on a RG, subscription or MG level?

**Comment by manicminer** [comment]
@celsocoutinho-tangany Currently yes, the resource only supports management group, subscription or resource group level. We had some challenging API interactions when trying to scope more specifically than that. I'll try to get those resolved in time, once the current implementation of this resource has had a break-in period to weed out any bugs.
