### PR TITLE
`azurerm_sentinel_data_connector_threat_intelligence_taxii`: fix parsing error

### LINKED ISSUE #26272: azurerm_sentinel_data_connector_threat_intelligence_taxii input parsing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.107.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_data_connector_threat_intelligence_taxii

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resource-group"
  location = "East US"
  
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "example-workspace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_solution" "example" {
  solution_name         = "SecurityInsights"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  workspace_resource_id = azurerm_log_analytics_workspace.example.id
  workspace_name        = azurerm_log_analytics_workspace.example.name

  plan {
  publisher = "Microsoft"
  product   = "OMSGallery/SecurityInsights"
  }
}

resource "azurerm_sentinel_data_connector_threat_intelligence_taxii" "example" {
  name                       = "ti-taxii-data-connector-example"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
  display_name               = "Mitre ATT&CK - Enterprise Attack Collection"
  api_root_url               = "https://cti-taxii.mitre.org/stix/"
  collection_id              = "95ecc380-afe9-11e4-9b6c-751b66dd541e"
  polling_frequency          = "OnceADay"
}
```

### Debug Output/Panic Output

```shell
Error: creating Data Connector: (Name "ti-taxii-data-connector-example" / Workspace Name "example-workspace" / Resource Group "example-resource-group"): securityinsight.DataConnectorsClient#CreateOrUpdate: Failure responding to request: StatusCode=201 -- Original Error: Error occurred unmarshalling JSON - Error = 'unknown enum for pollingFrequency "OnceADay"' JSON = '{"id":"/subscriptions/REDACTED/resourceGroups/example-resource-group/providers/Microsoft.OperationalInsights/workspaces/example-workspace/providers/Microsoft.SecurityInsights/dataConnectors/ti-taxii-data-connector-example","name":"ti-taxii-data-connector-example","etag":"REDACTED","type":"Microsoft.SecurityInsights/dataConnectors","kind":"ThreatIntelligenceTaxii","properties":{"taxiiServer":"https://cti-taxii.mitre.org/stix/","collectionId":"95ecc380-afe9-11e4-9b6c-751b66dd541e","workspaceId":"REDACTED","friendlyName":"Mitre ATT&CK - Enterprise Attack Collection","userName":null,"password":null,"taxiiLookbackPeriod":"1970-01-01T00:00:00Z","pollingFrequency":"OnceADay","dataTypes":{"taxiiClient":{"state":"enabled"}},"tenantId":"REDACTED"}}'
```

### Expected Behaviour

Resource should have deployed with the inputs provided

### Actual Behaviour

Terraform plan succeeds, but apply fails.
Error = 'unknown enum for pollingFrequency "OnceADay"' was observed

### Steps to Reproduce

terraform apply

### Important Factoids

_No response_

### References

issue #25409, resolved by merge request #25343 - similar unmarshalling JSON parsing occurrence with another input in this module

### PR DESCRIPTION
**Pull request by ziyeqf**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
❯❯ tftest sentinel TestAccDataConnectorThreatIntelligenceTAXII
=== RUN   TestAccDataConnectorThreatIntelligenceTAXII_basic
=== PAUSE TestAccDataConnectorThreatIntelligenceTAXII_basic
=== RUN   TestAccDataConnectorThreatIntelligenceTAXII_complete
=== PAUSE TestAccDataConnectorThreatIntelligenceTAXII_complete
=== RUN   TestAccDataConnectorThreatIntelligenceTAXII_update
=== PAUSE TestAccDataConnectorThreatIntelligenceTAXII_update
=== RUN   TestAccDataConnectorThreatIntelligenceTAXII_requiresImport
=== PAUSE TestAccDataConnectorThreatIntelligenceTAXII_requiresImport
=== CONT  TestAccDataConnectorThreatIntelligenceTAXII_basic
=== CONT  TestAccDataConnectorThreatIntelligenceTAXII_update
=== CONT  TestAccDataConnectorThreatIntelligenceTAXII_requiresImport
=== CONT  TestAccDataConnectorThreatIntelligenceTAXII_complete
--- PASS: TestAccDataConnectorThreatIntelligenceTAXII_requiresImport (303.67s)
--- PASS: TestAccDataConnectorThreatIntelligenceTAXII_complete (356.22s)
--- PASS: TestAccDataConnectorThreatIntelligenceTAXII_basic (385.99s)
--- PASS: TestAccDataConnectorThreatIntelligenceTAXII_update (580.03s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/sentinel      582.068s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_sentinel_data_connector_threat_intelligence_taxii`: fix parsing error [GH-26316]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #26272

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/sentinel/sentinel_data_connector.go [hunk 1]
```diff
@@ -88,12 +87,8 @@ func assertDataConnectorKind(dc securityinsight.BasicDataConnector, expectKind s
 		kind = securityinsight.DataConnectorKindAmazonWebServicesS3
 	case securityinsight.TiTaxiiDataConnector:
 		kind = securityinsight.DataConnectorKindThreatIntelligenceTaxii
-	case azuresdkhacks.TiTaxiiDataConnector:
-		kind = securityinsight.DataConnectorKindThreatIntelligenceTaxii
 	case securityinsight.TIDataConnector:
 		kind = securityinsight.DataConnectorKindThreatIntelligence
-	case azuresdkhacks.TIDataConnector:
-		kind = securityinsight.DataConnectorKindThreatIntelligence
```
Comment (katbyte) [inline internal/services/sentinel/sentinel_data_connector.go:96]: how come we are removing these and what effect will it have for the end users?

**Review by katbyte — CHANGES_REQUESTED** [review]

File: internal/services/sentinel/sentinel_data_connector.go (hunk 1 above)
Comment (ziyeqf) [reply internal/services/sentinel/sentinel_data_connector.go:96]: This func `assertDataConnectorKind` is only called by `importSentinelDataConnector` on above lines. 
The `importSentinelDataConnector` func used to use a patched client from `azuresdkhacks`, which will return these two removed models. 
Since the service is consistent with Swagger now, we don't need to use `azuresdkhacks` client now, so we don't need these two models either.

**Review by katbyte — APPROVED** [review]
LGTM 🍕
