### PR TITLE
`azurerm_machine_learning_compute_cluster` - `subnet_resource_id` does not have to be specified when `node_public_ip_enabled` is `false`

### LINKED ISSUE #27506: Can't create a Compute Instance without a Public IP on a Machine Learning Workspace with Managed Virtual Network enabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.1

### AzureRM Provider Version

3.116

### Affected Resource(s)/Data Source(s)

azurerm_machine_learning_compute_instance

### Terraform Configuration Files

```hcl
We have created a Machine Learning Workspace with Managed Virtual Network enabled.
Our goal is to create a machine learning compute instance with No Public IP.

As referring to the official Documentation:
https://registry.terraform.io/providers/hashicorp/azurerm/3.116.0/docs/resources/machine_learning_compute_instance
this can be done by setting the below parameter to false:
node_public_ip_enabled  = false

Though setting this to false indicates that it is a must for us to have subnet_resource_id set.

"node_public_ip_enabled - (Optional) Whether the compute instance will have a public ip. To set this to false a subnet_resource_id needs to be set. Defaults to true. Changing this forces a new Machine Learning Compute Cluster to be created."

But setting the subnet_resource_id conflicts with the fact that the workspace has a Managed Virtual Network / can not provide a subnet resource id if we have Managed Virtual Network enabled.

Option nr1:
resource "azurerm_machine_learning_compute_instance" "ml-ci" {
  for_each                      = local.compute_instances
  name                          = each.value["name"]
  location                      = var.azureml_resource_group_location
  machine_learning_workspace_id = var.azureml_workspace_id
  virtual_machine_size          = each.value["vm_size"]
  subnet_resource_id            = null
  tags                          = each.value["tags"]
  identity {
    type = "SystemAssigned"
  }
  assign_to_user {
    object_id = each.value["user_object_id"]
    tenant_id = var.tenant_id
  }
  node_public_ip_enabled = var.node_public_ip_enabled
}

Option nr2:
resource "azurerm_machine_learning_compute_instance" "ml-ci" {
  for_each                      = local.compute_instances
  name                          = each.value["name"]
  location                      = var.azureml_resource_group_location
  machine_learning_workspace_id = var.azureml_workspace_id
  virtual_machine_size          = each.value["vm_size"]
  subnet_resource_id            = "/subscriptions/xxx/resourceGroups/xx/providers/Microsoft.Network/virtualNetworks/xx/subnets/xx"
  tags                          = each.value["tags"]
  identity {
    type = "SystemAssigned"
  }
  assign_to_user {
    object_id = each.value["user_object_id"]
    tenant_id = var.tenant_id
  }
  node_public_ip_enabled = var.node_public_ip_enabled
}
```

### Debug Output/Panic Output

```shell
Error on option nr1:
This is the error we get if we do not provide a subnet_resource_id:
Error: `subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false`

Error on option nr2:
│ Error: waiting for creation of Machine Learning Compute (Subscription: "xxx"
│ Resource Group Name: "xxx"
│ Workspace Name: "xxx"
│ Compute Name: "xxx"): polling failed: the Azure API returned the following error:
│
│ Status: "BadRequest"
│ Code: ""
│ Message: "Unsupported operation: Attempting to create ComputeInstance compute in custom vnet (/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx) when the workspace is configured with a Managed 
Virtual Network. Please ensure the subnet is set to null or the workspace is not configured with a Managed Virtual Network."
│ Activity Id: ""
│
│ ---
│
│ API Response:
│
│ ----[start]----
│ {
│   "status": "Failed",
│   "error": {
│     "code": "BadRequest",
│     "message": "Unsupported operation: Attempting to create ComputeInstance compute in custom vnet (/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx) when the workspace is configured with a Managed Virtual Network. Please ensure the subnet is set to null or the workspace is not configured with a Managed Virtual Network."
│   }
│ }
│ -----[end]-----
│
│
│   with module.compute_instance_dp["xxx"].azurerm_machine_learning_compute_instance.ml-ci["xxx"],
│   on ..\modules\compute-instance\main.tf line 15, in resource "azurerm_machine_learning_compute_instance" "ml-ci":
│   15: resource "azurerm_machine_learning_compute_instance" "ml-ci" {
│
```

### Expected Behaviour

It is expected that the Compute Instance gets create on the workspace without Public IP and just a Private one which will be managed by Azure itself since Managed Virtual Network is enabled in the workspace.

The Instance is able to get created manually without Public IP from the Machine Learning Workspace.

We expect same to be created via terraform.

### Actual Behaviour

Currently this is not possible.

### Steps to Reproduce

_No response_

### Important Factoids

The region is West Europe

### References

https://registry.terraform.io/providers/hashicorp/azurerm/3.116.0/docs/resources/machine_learning_compute_instance

### PR DESCRIPTION
**Pull request by mbfrahry**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR makes it possible so that  `subnet_resource_id` does not have to be specified when `node_public_ip_enabled` is `false`.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_machine_learning_compute_cluster` - `subnet_resource_id` does not have to be specified when `node_public_ip_enabled` is `false` [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27506

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/machinelearning/machine_learning_compute_cluster_resource.go [hunk 1]
```diff
@@ -155,8 +155,10 @@ func resourceComputeCluster() *pluginsdk.Resource {
 			},
 
 			"subnet_resource_id": {
-				Type:     pluginsdk.TypeString,
+				Type: pluginsdk.TypeString,
+				// O + C as you don't have to specify it for Azure to assign one to the cluster
```
Comment (stephybun) [inline internal/services/machinelearning/machine_learning_compute_cluster_resource.go:159]:
```suggestion
				// NOTE: O+C as you don't have to specify it for Azure to assign one to the cluster
```

File: internal/services/machinelearning/machine_learning_compute_cluster_resource.go [hunk 2]
```diff
@@ -211,28 +213,6 @@ func resourceComputeClusterCreate(d *pluginsdk.ResourceData, meta interface{}) e
...
-	}
-
-	workspaceInManagedVnet := false
-
-	if workspaceModel.Properties != nil &&
-		workspaceModel.Properties.ManagedNetwork != nil &&
-		workspaceModel.Properties.ManagedNetwork.Status != nil &&
-		workspaceModel.Properties.ManagedNetwork.Status.Status != nil {
-		workspaceInManagedVnet = *workspaceModel.Properties.ManagedNetwork.Status.Status == workspaces.ManagedNetworkStatusActive
-	}
```
Comment (stephybun) [inline internal/services/machinelearning/machine_learning_compute_cluster_resource.go:231]: Are you able to confirm that this check isn't still required? Do we have an acceptance test for this?

Comment (mbfrahry) [reply internal/services/machinelearning/machine_learning_compute_cluster_resource.go:231]: I believe my acceptance test covered this check not being needed because nodePublicIPEnabled was false, the subnetResourceID was not specified and the workspace was not in a managed vnet and that test passes 

```
--- PASS: TestAccComputeCluster_subnetResourceId (670.21s)
```

File: internal/services/machinelearning/machine_learning_compute_cluster_resource.go [hunk 3]
```diff
@@ -211,28 +213,6 @@ func resourceComputeClusterCreate(d *pluginsdk.ResourceData, meta interface{}) e
...
-
-	if !nodePublicIPEnabled && subnetResourceID == "" && !workspaceInManagedVnet {
-		return fmt.Errorf("`subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false` or the workspace is not in a managed network")
```
Comment (stephybun) [inline internal/services/machinelearning/machine_learning_compute_cluster_resource.go:234]: Last comment, the docs mention this validation for the `node_public_ip_enabled` property, we should remove it.

**Review by stephybun — COMMENTED** [review]
Thanks @mbfrahry! One last comment regarding the docs, but once that's been updated this will be good to go!

**Review by stephybun — APPROVED** [review]
Thanks @mbfrahry LGTM 🦄
