### PR TITLE
`azurerm_api_management_diagnostic` - the `operation_name_format` property is only available for `applicationinsights` diagnostic

### LINKED ISSUE #19970: For azurerm_api_management_diagnostic, Event Hub Configuration not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

3.38.0

### AzureRM Provider Version

3.38.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_diagnostic

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_logger" "apim" {
  name                = "logger-apim-001"
  api_management_name = azurerm_api_management.apim.name
  resource_group_name = azurerm_resource_group.apim.name

  eventhub {
    name              = "evh-apim-001"
    connection_string = "primary_connection_string"
  }
}

resource "azurerm_api_management_diagnostic" "apim" {
  identifier               = "azuremonitor"
  resource_group_name      = azurerm_resource_group.apimfrc.name
  api_management_name      = azurerm_api_management.apim.name
  api_management_logger_id = azurerm_api_management_logger.apim.id
  always_log_errors        = true
  log_client_ip            = true
  verbosity                = "verbose"
  sampling_percentage      = 100

  frontend_request {
    headers_to_log = [
      "x-appgw-trace-id",
    ]
  }
  frontend_response {
    headers_to_log = [
      "x-appgw-trace-id",
    ]
  }
  backend_request {
    headers_to_log = [
      "x-appgw-trace-id",
    ]
  }
  backend_response {
    headers_to_log = [
      "x-appgw-trace-id",
    ]
  }
}
```

### Debug Output/Panic Output

```shell
We are trying to set up an azure monitor for the event hub and the error is on operationNameFormat which is only used in the case of application insight.
Error:
Apimanagement.DiagnosticClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"Property 'OperationNameFormat' is only supported for Application Insights diagnostics.","target":"operationNameFormat"}]
```

### Expected Behaviour

Azure event hub monitoring could be configured correctly

### Actual Behaviour

Error:
Apimanagement.DiagnosticClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"Property 'OperationNameFormat' is only supported for Application Insights diagnostics.","target":"operationNameFormat"}]

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by sinbai**
Although PR #22545 was submitted to fix #19970, no response was received from the submitter for a long time. Since we received  request from users to fix this issue, submitting this PR to fix it.

### CODE REVIEW

File: internal/services/apimanagement/api_management_diagnostic_resource.go [hunk 1]
```diff
@@ -147,11 +153,18 @@ func resourceApiManagementDiagnosticCreateUpdate(d *pluginsdk.ResourceData, meta
...
 		},
 	}
 
+	if d.Get("identifier") == "applicationinsights" {
+		if operationNameFormat, ok := d.GetOk("operation_name_format"); ok {
+			parameters.Properties.OperationNameFormat = pointer.To(diagnostic.OperationNameFormat(operationNameFormat.(string)))
+		} else {
+			parameters.Properties.OperationNameFormat = pointer.To(diagnostic.OperationNameFormatName)
+		}
+	}
```
Comment (stephybun) [inline internal/services/apimanagement/api_management_diagnostic_resource.go:166]: This should also be wrapped in the 4.0 flag since after 4.0 we don't want to be sending `diagnostic.OperationNameFormatName` is `operation_name_format` is omitted?

File: internal/services/apimanagement/api_management_diagnostic_resource.go [hunk 2]
```diff
@@ -259,7 +272,7 @@ func resourceApiManagementDiagnosticRead(d *pluginsdk.ResourceData, meta interfa
 				d.Set("backend_request", nil)
 				d.Set("backend_response", nil)
 			}
-			format := string(diagnostic.OperationNameFormatName)
+			format := ""
```
Comment (stephybun) [inline internal/services/apimanagement/api_management_diagnostic_resource.go:275]: Same here, pre 4.0 we should still be defaulting this in the read.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @sinbai. Some of the changes still need to be wrapped in the 4.0 flag. Once that's done I can take another look over.

File: internal/services/apimanagement/api_management_diagnostic_resource.go (hunk 1 above)
Comment (sinbai) [reply internal/services/apimanagement/api_management_diagnostic_resource.go]: Fixed.

File: internal/services/apimanagement/api_management_diagnostic_resource.go (hunk 2 above)
Comment (sinbai) [reply internal/services/apimanagement/api_management_diagnostic_resource.go:284]: Fixed.

**Comment by sinbai** [comment]
> Thanks for this PR @sinbai. Some of the changes still need to be wrapped in the 4.0 flag. Once that's done I can take another look over.

Hi @stephybun thanks for your time. The code has been updated. Could you please take another look?

**Review by stephybun — APPROVED** [review]
Thanks @sinbai. There was some misunderstanding around my comment about the wrapping so I pushed a simplification. I'll be more specific with my suggestions next time. LGTM 🥟
