### PR TITLE
[Enhancement:] `azurerm_cdn_frontdoor_profile` - add support for the `identity` property

### LINKED ISSUE #20289: `azurerm_cdn_frontdoor_profile` - missing identity settings
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_profile

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_profile" "shared" {
  name = "fd-${local.app_name}"
  sku_name = "Premium_AzureFrontDoor"
  response_timeout_seconds = 30

  resource_group_name = azurerm_resource_group.shared.name

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
$ terraform apply
╷
│ Error: Unsupported block type
│
│   on shared_frontdoor.tf line 11, in resource "azurerm_cdn_frontdoor_profile" "shared":
│   11:   identity {
│
│ Blocks of type "identity" are not expected here.
╵
```

### Expected Behaviour

I should be allowed to set the identity on a azurerm_cdn_frontdoor_profile resource

### Actual Behaviour

I get an error and this seems to not be supported yet

### Steps to Reproduce

1. terraform apply
2. Error

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by WodansSon**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

The purpose for this PR are as follows:

* add support for the `identity` field in the the AFD Profile resource

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_cdn_frontdoor_profile` - add support for the `identity` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #20289

## Related PR(s)
Supersedes #28068

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/cdn/cdn_frontdoor_profile_resource_test.go [hunk 1]
```diff
@@ -85,6 +127,97 @@ func TestAccCdnFrontDoorProfile_update(t *testing.T) {
...
+		},
+		data.ImportStep(),
+		{
+			Config: r.complete(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("response_timeout_seconds").HasValue("240"),
+			),
+		},
+	})
```
Comment (jackofallops) [inline internal/services/cdn/cdn_frontdoor_profile_resource_test.go:157]: Missed import step here?
```suggestion
		data.ImportStep(),
		{
			Config: r.complete(data),
			Check: acceptance.ComposeTestCheckFunc(
				check.That(data.ResourceName).ExistsInAzure(r),
				check.That(data.ResourceName).Key("response_timeout_seconds").HasValue("240"),
			),
		},
		data.ImportStep(),
	})
```

File: internal/services/cdn/cdn_frontdoor_profile_resource_test.go [hunk 2]
```diff
@@ -85,6 +127,97 @@ func TestAccCdnFrontDoorProfile_update(t *testing.T) {
...
```
Comment (jackofallops) [inline internal/services/cdn/cdn_frontdoor_profile_resource_test.go:187]:
```suggestion
		data.ImportStep(),
		{
			Config: r.complete(data),
			Check: acceptance.ComposeTestCheckFunc(
				check.That(data.ResourceName).ExistsInAzure(r),
				check.That(data.ResourceName).Key("response_timeout_seconds").HasValue("240"),
			),
		},
		data.ImportStep(),
	})
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Thanks @WodansSon - just a couple minor comments on the tests, but otherwise LGTM. I'll get the tests run as soon as the changes below are in and then we should be good to go.

**Comment by pie-r** [comment]
@WodansSon looking forward to seeing this merged ;)

File: internal/services/cdn/cdn_frontdoor_profile_resource_test.go (hunk 1 above)
Comment (WodansSon) [reply internal/services/cdn/cdn_frontdoor_profile_resource_test.go:157]: Fixed.

File: internal/services/cdn/cdn_frontdoor_profile_resource_test.go (hunk 2 above)
Comment (WodansSon) [reply internal/services/cdn/cdn_frontdoor_profile_resource_test.go:187]: Fixed.

**Comment by jackofallops** [comment]
Tests all look good 👍 

image

**Review by jackofallops — APPROVED** [review]
Thanks @WodansSon - LGTM now 👍
