### PR TITLE
`azurerm_security_center_pricing` - force new resource to be created when `subplan` changes

### LINKED ISSUE #27338: azurerm_security_center_subscription_pricing auto-enables OnUploadMalwareScanning extension with DefenderForStorageV2 subplan
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.114.0

### Affected Resource(s)/Data Source(s)

azurerm_security_center_subscription_pricing

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_subscription_pricing" "ms_defender" {
  tier          = "Standard"
  resource_type = "StorageAccounts"
  subplan       = "DefenderForStorageV2"

  extension {
    name = "SensitiveDataDiscovery"
  }
}
```

### Debug Output/Panic Output

```shell
n/a, they apply succeeds
```

### Expected Behaviour

I would expect my subscription to be set to the new Defender for Storage plan, with SensitiveDataDiscovery enabled

### Actual Behaviour

My subscription gets set to the new Defender for Storage plan, with SensitiveDataDiscovery **and OnUploadMalwareScanning** enabled. I don't want to use this feature, but I don't really have a way to disable it, because I can't explicitly disable it in Terraform, if I add it as an extension block it will also get enabled, at that point I can only tweak CapGBPerMonthPerStorageAccount.

### Steps to Reproduce

Nothing to add to above information.

### Important Factoids

_No response_

### References

https://registry.terraform.io/providers/hashicorp/azurerm/3.114.0/docs/resources/security_center_subscription_pricing

### PR DESCRIPTION
**Pull request by ziyeqf**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

When `subplan` changes, there might be extensions enabled by default, force a new resource to be created to keep the resource consistent with configuration.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_security_center_pricing` - force new resource to be created when subplan changes [GH-27805]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27338

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by yoavfr** [comment]
Hi @ziyeqf - what's happening with this? We have a customer waiting on it.

**Comment by ziyeqf** [comment]
kindly bubble this up

**Comment by ziyeqf** [comment]
convert to draft to update

**Comment by ziyeqf** [comment]
image

**Comment by yoavfr** [comment]
@ziyeqf - looks like this is stuck? Who needs to approve?

**Comment by yoavfr** [comment]
@ziyeqf ping. There is a customer waiting for this since October. Microsoft is not looking very good here.

File: internal/services/securitycenter/security_center_subscription_pricing_resource.go [hunk 1]
```diff
@@ -105,48 +108,46 @@ func resourceSecurityCenterSubscriptionPricing() *pluginsdk.Resource {
...
 		},
 	}
+
+	return res
 }
 
-func resourceSecurityCenterSubscriptionPricingUpdate(d *pluginsdk.ResourceData, meta interface{}) error {
+func resourceSecurityCenterSubscriptionPricingCreate(d *pluginsdk.ResourceData, meta interface{}) error {
 	client := meta.(*clients.Client).SecurityCenter.PricingClient
+
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_subscription_pricing_resource.go:117]:
```suggestion
```

File: internal/services/securitycenter/security_center_subscription_pricing_resource.go [hunk 2]
```diff
@@ -105,48 +108,46 @@ func resourceSecurityCenterSubscriptionPricing() *pluginsdk.Resource {
...
 	subscriptionId := meta.(*clients.Client).Account.SubscriptionId
-	ctx, cancel := timeouts.ForCreateUpdate(meta.(*clients.Client).StopContext, d)
+
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_subscription_pricing_resource.go:119]:
```suggestion
```

File: internal/services/securitycenter/security_center_subscription_pricing_resource.go [hunk 3]
```diff
@@ -177,21 +176,97 @@ func resourceSecurityCenterSubscriptionPricingUpdate(d *pluginsdk.ResourceData,
...
+		return fmt.Errorf("updating %s: %+v", id, updateErr)
+	}
+
+	d.SetId(id.ID())
+	return resourceSecurityCenterSubscriptionPricingRead(d, meta)
+}
+
+func resourceSecurityCenterSubscriptionPricingUpdate(d *pluginsdk.ResourceData, meta interface{}) error {
+	client := meta.(*clients.Client).SecurityCenter.PricingClient
+
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_subscription_pricing_resource.go:198]:
```suggestion
```

File: internal/services/securitycenter/security_center_subscription_pricing_resource.go [hunk 4]
```diff
@@ -177,21 +176,97 @@ func resourceSecurityCenterSubscriptionPricingUpdate(d *pluginsdk.ResourceData,
...
+	requiredAdditionalUpdate := false
+	if d.HasChange("extension") && update.Properties.PricingTier == pricings_v2023_01_01.PricingTierStandard {
+		extensions := expandSecurityCenterSubscriptionPricingExtensions(realCfgExtensions, &extensionsStatusFromBackend)
+		update.Properties.Extensions = extensions
+		requiredAdditionalUpdate = currentlyFreeTier
+	}
+
+	updateResponse, updateErr := client.Update(ctx, *id, update)
+	if updateErr != nil {
+		return fmt.Errorf("setting %s: %+v", id, updateErr)
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_subscription_pricing_resource.go:254]:
```suggestion
		return fmt.Errorf("updating %s: %+v", id, updateErr)
```

File: internal/services/securitycenter/security_center_subscription_pricing_resource.go [hunk 5]
```diff
@@ -177,21 +176,97 @@ func resourceSecurityCenterSubscriptionPricingUpdate(d *pluginsdk.ResourceData,
...
+	}
+
+	// The extensions list from backend might vary after `tier` changed, thus we need to retire it again.
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_subscription_pricing_resource.go:257]: should this be?
```suggestion
	// The extensions list from backend might vary after `tier` changed, thus we need to retrieve it again.
```

File: internal/services/securitycenter/security_center_subscription_pricing_resource.go [hunk 6]
```diff
@@ -177,21 +176,97 @@ func resourceSecurityCenterSubscriptionPricingUpdate(d *pluginsdk.ResourceData,
...
-		pricing.Properties.Extensions = extensions
-		_, updateErr := client.Update(ctx, id, pricing)
-		if err != nil {
-			if updateErr != nil {
-				return fmt.Errorf("setting %s: %+v", id, updateErr)
-			}
+		update.Properties.Extensions = extensions
+		_, updateErr := client.Update(ctx, *id, update)
+		if updateErr != nil {
+			return fmt.Errorf("setting %s: %+v", id, updateErr)
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_subscription_pricing_resource.go:269]:
```suggestion
			return fmt.Errorf("updating %s: %+v", id, updateErr)
```

File: internal/services/securitycenter/security_center_subscription_pricing_resource.go [hunk 7]
```diff
@@ -177,21 +176,97 @@ func resourceSecurityCenterSubscriptionPricingUpdate(d *pluginsdk.ResourceData,
...
+	// Update from `free` tier to `Standard`, we need to update it to `standard` tier first without extensions
+	// Then do an additional update for the `extensions`
+	requiredAdditionalUpdate := false
+	if d.HasChange("extension") && update.Properties.PricingTier == pricings_v2023_01_01.PricingTierStandard {
+		extensions := expandSecurityCenterSubscriptionPricingExtensions(realCfgExtensions, &extensionsStatusFromBackend)
+		update.Properties.Extensions = extensions
+		requiredAdditionalUpdate = currentlyFreeTier
+	}
+
+	updateResponse, updateErr := client.Update(ctx, *id, update)
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_subscription_pricing_resource.go:252]: we should be able to reuse `err` here
```suggestion
	updateResponse, err := client.Update(ctx, *id, update)
```

File: internal/services/securitycenter/security_center_subscription_pricing_resource.go [hunk 8]
```diff
@@ -177,21 +176,97 @@ func resourceSecurityCenterSubscriptionPricingUpdate(d *pluginsdk.ResourceData,
...
+	if requiredAdditionalUpdate {
 		extensions := expandSecurityCenterSubscriptionPricingExtensions(realCfgExtensions, &extensionsStatusFromBackend)
-		pricing.Properties.Extensions = extensions
-		_, updateErr := client.Update(ctx, id, pricing)
-		if err != nil {
-			if updateErr != nil {
-				return fmt.Errorf("setting %s: %+v", id, updateErr)
-			}
+		update.Properties.Extensions = extensions
+		_, updateErr := client.Update(ctx, *id, update)
```
Comment (stephybun) [inline internal/services/securitycenter/security_center_subscription_pricing_resource.go:267]:
```suggestion
		_, err = client.Update(ctx, *id, update)
```

File: website/docs/5.0-upgrade-guide.html.markdown [hunk 9]
```diff
@@ -167,6 +167,10 @@ Please follow the format in the example below for listing breaking changes in re
 
 * The property `minimum_tls_version` property no longer accepts `1.0` or `1.1` as a value.
 
+### `azurerm_security_center_princing_tier`
+
+* Changing the property `subplan` now forces a new resource to be created.
+
```
Comment (stephybun) [inline website/docs/5.0-upgrade-guide.html.markdown:173]: This isn't a 5.0 change anymore so this should be removed

**Review by stephybun — CHANGES_REQUESTED** [review]

**Comment by ziyeqf** [comment]
kindly bubble this up

**Comment by ziyeqf** [comment]
kindly ping @stephybun
