### PR TITLE
`azurerm_static_site` - fix Free tier creation error

### LINKED ISSUE #15125: azurerm_static_site error with message: "SkuCode 'SKU' is invalid" for Free option. For Standard works OK.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.4 on windows_amd64

### Affected Resource(s)

* `azurerm_static_site`

### Terraform Configuration Files

resource "azurerm_resource_group" "main_rg" {
  name     = "RES_DEV_FOR_TEST"
  location = "westeurope"

  lifecycle {
    prevent_destroy = true
  }
}

resource "azurerm_static_site" "common-static-web" {
  name                = "SWA-FOR-TEST"
  resource_group_name = azurerm_resource_group.main_rg.name
  location            = azurerm_resource_group.main_rg.location
}

### Debug Output

https://gist.github.com/azieh/19b3124a632cdc7aa7b140a687e5fdfe

### Expected Behaviour

Resource should be created

### Actual Behaviour

Above error do not allow deploy service

### Steps to Reproduce

Just try to create simple resource. Nothing more.

### Important Factoids

When SKU is set to "Standard", Azure resource is create without any error. After that in Azure Portal is possible to change SKU to Free.

### References

* #0000

### PR DESCRIPTION
**Pull request by magodo**
The free tier seems not support identity anymore, so ensure there is no
`identity` block specified in the request payload in this case.

Besides, even for `Standard` sku, the user assigned identity won't
return an overall principalId. Instead, it returns the principalId for
each user assigned identity. This causes the test case
TestAccAzureStaticSite_withUserAssignedIdentity continue failing.

Fixes #15125

### CODE REVIEW

File: internal/services/web/static_site_resource.go [hunk 1]
```diff
@@ -115,14 +115,21 @@ func resourceStaticSiteCreateOrUpdate(d *pluginsdk.ResourceData, meta interface{
...
+	skuName := d.Get("sku_size").(string)
+
 	identity, err := expandStaticSiteIdentity(d.Get("identity").([]interface{}))
 	if err != nil {
 		return fmt.Errorf("expanding `identity`: %+v", err)
 	}
 
+	// See: https://github.com/Azure/azure-rest-api-specs/issues/17525
+	if skuName == string(web.SkuNameFree) && identity != nil {
+		return fmt.Errorf("Free tier Static Site doens't support specifying `identity`")
```
Comment (tombuildsstuff) [inline internal/services/web/static_site_resource.go:127]: this is probably more descriptive as?

```suggestion
		return fmt.Errorf("a Managed Identity cannot be used when tier is set to `Free`")`
```

**Review by tombuildsstuff — APPROVED** [review]
One minor comment about the error message but this otherwise LGTM 👍

**Comment by tombuildsstuff** [comment]
Tests look good 👍
