### PR TITLE
azurerm_container_app - support:  allows IP restrictions without requiring CIDR

### LINKED ISSUE #25608: Unnecessary CIDR /32 Notation for Specifying Single IP Addresses in Container Apps IP Restrictions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

# Description

When setting IP restrictions for Azure Container Apps using the Azure Portal or CLI, it appears that the CIDR notation is not always necessary for a single host (no errors are reported).
[IP restrictions for Container Apps](https://learn.microsoft.com/en-us/azure/container-apps/ip-restrictions?pivots=azure-cli#create-or-update-rules).

```bash
az containerapp ingress access-restriction set --name example-app --resource-group example-app-rg --rule-name "my allow rule" --description "example of rule allowing access" --ip-address 192.168.0.1 --action Allow
```

However, when implementing the same settings via Terraform, the following error occurs:

```tf
resource "azurerm_container_app" "ai_worker_ca" {
# ...
    ip_security_restriction {
      name             = "AllowAll"
      description      = "Allow all IP addresses"
      action           = "Allow"
      ip_address_range = "192.168.0.1/32"
    }
}
```
```bash
terraform plan
```

```
Error: expected "ingress.0.ip_security_restriction.0.ip_address_range" to be a valid CIDR Value, got 192.168.0.1: invalid CIDR address: 192.168.0.1
```

Given that the native Azure behavior allows IP restrictions without requiring CIDR notation, should we not update the Terraform provider to align with this functionality? This would simplify configuration processes and reduce potential discrepancies between direct Azure usage and Terraform configurations.

### Terraform Version

1.8.0

### AzureRM Provider Version

3.89.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_app_environment" "example" {
  name                       = "Example-Environment"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
}
resource "azurerm_container_app" "example" {
  name                         = "example-app"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"

    ip_security_restriction {
      name             = "AllowAll"
      description      = "Allow all IP addresses"
      action           = "Allow"
      ip_address_range = "192.168.0.1"
    }

  template {
    container {
      name   = "examplecontainerapp"
      image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected "ingress.0.ip_security_restriction.0.ip_address_range" to be a valid CIDR Value, got 192.168.0.1: invalid CIDR address: 192.168.0.1
```

### Expected Behaviour

_No response_

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by sugar-cat7**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description
When setting IP restrictions for Azure Container Apps using the Azure Portal or CLI, it appears that the CIDR notation is not always necessary for a single host (no errors are reported).
[IP restrictions for Container Apps](https://learn.microsoft.com/en-us/azure/container-apps/ip-restrictions?pivots=azure-cli#create-or-update-rules).

```bash
az containerapp ingress access-restriction set --name example-app --resource-group example-app-rg --rule-name "my allow rule" --description "example of rule allowing access" --ip-address 192.168.0.1 --action Allow
```
Given that the native Azure behavior allows IP restrictions without requiring CIDR notation, should we not update the Terraform provider to align with this functionality? This would simplify configuration processes and reduce potential discrepancies between direct Azure usage and Terraform configurations.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

CleanShot 2024-04-14 at 01 40 03@2x

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25608 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/containerapps/helpers/container_apps.go [hunk 1]
```diff
@@ -484,7 +484,7 @@ func ContainerAppIngressIpSecurityRestriction() *pluginsdk.Schema {
 				"ip_address_range": {
 					Type:         pluginsdk.TypeString,
 					Required:     true,
-					ValidateFunc: validation.IsCIDR,
+					ValidateFunc: validation.IsIPAddressOrCIDR,
```
Comment (stephybun) [inline internal/services/containerapps/helpers/container_apps.go:487]: This can be achieved by specifying multiple validation functions 
```suggestion
					ValidateFunc: validation.Any(validation.IsCIDR, validation.IsIPAddress),
```

File: internal/tf/validation/pluginsdk.go [hunk 2]
```diff
@@ -143,6 +143,21 @@ func IsIPv6Address(i interface{}, k string) ([]string, []error) {
...
+	}
+
+	warningsCIDR, errorsCIDR := IsCIDR(i, k)
+	if len(errorsCIDR) == 0 {
+		return warningsCIDR, nil
+	}
+
+	return append(warningsIP, warningsCIDR...), append(errorsIP, errorsCIDR...)
+}
+
```
Comment (stephybun) [inline internal/tf/validation/pluginsdk.go:160]: Then this can be removed 
```suggestion
```

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @sugar-cat7. Could you take a look at the suggestions left in-line as well as update the docs for this property? Once that's done and provided the tests pass this should be good to go.

**Review by stephybun — APPROVED** [review]
Thanks @sugar-cat7 LGTM 🐯
