### PR TITLE
`azurerm_video_indexer_account` - support for the `public_network_access` property

### LINKED ISSUE #29618: azurerm_video_indexer_account - public_network_access attribute is not available
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.11.4

### AzureRM Provider Version

4.28.0

### Affected Resource(s)/Data Source(s)

azurerm_video_indexer_account

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "example"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_video_indexer_account" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = "West Europe"

  storage {
    storage_account_id = azurerm_storage_account.example.id
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

I should be able to set the `public_network_access` attribute to `Disabled` to disable public network access to the resource when using private link. The setting is available in Azure Portal when managing the resource via the UI.

### Actual Behaviour

The `public_network_access` attribute is not available in Terraform so the new resource always has public access enabled.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

https://registry.terraform.io/providers/hashicorp/azurerm/4.28.0/docs/resources/video_indexer_account

### PR DESCRIPTION
**Pull request by sinbai**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Support for the `public_network_access_enabled` property.

Swagger:https://github.com/Azure/azure-rest-api-specs/blob/c9c3e8b9ec547d82c487f36f1126228f9eef0e79/specification/vi/resource-manager/Microsoft.VideoIndexer/stable/2025-04-01/vi.json#L1049C10-L1049C29

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-29618]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29618

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/videoindexer/video_indexer_account_resource.go [hunk 1]
```diff
@@ -76,6 +77,12 @@ func (r AccountResource) Arguments() map[string]*pluginsdk.Schema {
 
 		"identity": commonschema.SystemAssignedUserAssignedIdentityRequired(),
 
+		"public_network_access_enabled": {
```
Comment (sreallymatt) [inline internal/services/videoindexer/video_indexer_account_resource.go]: While we've previously exposed the public network access enum as `public_network_access_enabled` (boolean), we're seeing more of these in the SDK with states other than `Enabled` and `Disabled`. Because of this, we'd prefer to standardize and expose these as `public_network_access` (string) moving forward to avoid potentially having to introduce a breaking change in the future.

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Hi @sinbai, could you rename `public_network_access_enabled` to `public_network_access` and make it of type String? I've left some more context inline, once that's done I'll give this a more thorough review, thanks!

File: internal/services/videoindexer/video_indexer_account_resource.go (hunk 1 above)
Comment (sinbai) [reply internal/services/videoindexer/video_indexer_account_resource.go]: Hi @sreallymatt thanks for your time. I have fixed the comment, would you mind take another look?

File: internal/services/videoindexer/video_indexer_account_resource.go [hunk 2]
```diff
@@ -76,6 +78,13 @@ func (r AccountResource) Arguments() map[string]*pluginsdk.Schema {
 
 		"identity": commonschema.SystemAssignedUserAssignedIdentityRequired(),
 
+		"public_network_access": {
+			Type:         pluginsdk.TypeString,
+			Optional:     true,
+			Default:      string(accounts.PublicNetworkAccessEnabled),
+			ValidateFunc: validation.StringInSlice(accounts.PossibleValuesForPublicNetworkAccess(), true),
```
Comment (sreallymatt) [inline internal/services/videoindexer/video_indexer_account_resource.go]: Was there a specific reason for validating this insensitively? We'd prefer to use case-sensitive forms where possible

```suggestion
			ValidateFunc: validation.StringInSlice(accounts.PossibleValuesForPublicNetworkAccess(), false),
```

**Review by sreallymatt — COMMENTED** [review]
Thanks for making those changes @sinbai, this looks good, I've just left one question inline.

File: internal/services/videoindexer/video_indexer_account_resource.go (hunk 2 above)
Comment (sinbai) [reply internal/services/videoindexer/video_indexer_account_resource.go]: Fixed.

**Comment by sinbai** [comment]
> Thanks for making those changes @sinbai, this looks good, I've just left one question inline.

Hi @sreallymatt thanks for pointing that out - It's been fixed. Would you mind take another look?
