### PR TITLE
`d/azurerm_key_vault_access_policy` - Fix Permission

### LINKED ISSUE #21360: data output "azurerm_key_vault_access_policy" isn't capitalised correctly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.51.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_access_policy

### Terraform Configuration Files

```hcl
# Create a Keyvault
resource "azurerm_key_vault" "my-kv" {
  name                        = "my-kv"
  resource_group_name = data.azurerm_resource_group.rg-c.name
  location            = data.azurerm_resource_group.rg-c.location
  soft_delete_retention_days  = 7
  purge_protection_enabled    = true
  sku_name = "standard"
  tags     = local.resource_tags

}

# Get a list of all Key Management permissions
data "azurerm_key_vault_access_policy" "key_policies" {
  name = "Key Management"
}

# Grant some client all the Key Management policies offered
resource "azurerm_key_vault_access_policy" "kvap" {
  key_vault_id       = azurerm_key_vault.kv-c.id
  object_id          = var.some_service_principal_objectid
  key_permissions    = data.azurerm_key_vault_access_policy.key_policies.key_permissions
}
```

### Debug Output/Panic Output

```shell
│ Error: expected key_permissions.2 to be one of [Backup Create Decrypt Delete Encrypt Get Import List Purge Recover Restore Sign UnwrapKey Update Verify WrapKey Release Rotate GetRotationPolicy SetRotationPolicy], got update
│ 
│   with module.wqinv.module.keyvault-fs.azurerm_key_vault_access_policy.kv-devops-fs,
│   on patterns/components/keyvault/permissions.tf line 54, in resource "azurerm_key_vault_access_policy" "kvap":
│   54:   key_permissions    = data.azurerm_key_vault_access_policy.key_policies.key_permissions
│
```

### Expected Behaviour

The block `data "azurerm_key_vault_access_policy"` should have returned 'Update' instead of 'update', so that the permissions could have been applied.

### Actual Behaviour

As the capitalisation is wrong, we are unable to apply the permissions.

### Steps to Reproduce

`terraform apply`

### Important Factoids

_No response_

### References

Looks like a remaining unfixed aspect of the transition to RM version 3 - see https://github.com/hashicorp/terraform-provider-azurerm/issues/16354#issuecomment-1097531707

### PR DESCRIPTION
**Pull request by myc2h6o**
Fix #21360

### CODE REVIEW

File: internal/services/keyvault/key_vault_access_policy_data_source.go [hunk 1]
```diff
@@ -62,89 +60,53 @@ func dataSourceKeyVaultAccessPolicy() *pluginsdk.Resource {
...
+		keyvault.CertificatePermissionsCreate,
+		keyvault.CertificatePermissionsImport,
+		keyvault.CertificatePermissionsDelete,
+		keyvault.CertificatePermissionsManagecontacts,
+		keyvault.CertificatePermissionsManageissuers,
+		keyvault.CertificatePermissionsGetissuers,
+		keyvault.CertificatePermissionsListissuers,
+		keyvault.CertificatePermissionsSetissuers,
+		keyvault.CertificatePermissionsDeleteissuers,
+	})
```
Comment (tombuildsstuff) [inline internal/services/keyvault/key_vault_access_policy_data_source.go:98]: we can use `certificatePermissions()` for this?

File: internal/services/keyvault/key_vault_access_policy_data_source.go [hunk 2]
```diff
@@ -62,89 +60,53 @@ func dataSourceKeyVaultAccessPolicy() *pluginsdk.Resource {
...
+		keyvault.KeyPermissionsGet,
+		keyvault.KeyPermissionsList,
+		keyvault.KeyPermissionsUpdate,
+		keyvault.KeyPermissionsCreate,
+		keyvault.KeyPermissionsImport,
+		keyvault.KeyPermissionsDelete,
+		keyvault.KeyPermissionsRecover,
+		keyvault.KeyPermissionsBackup,
+		keyvault.KeyPermissionsRestore,
+	})
```
Comment (tombuildsstuff) [inline internal/services/keyvault/key_vault_access_policy_data_source.go:73]: we can use `keyPermissions()` for this?

File: internal/services/keyvault/key_vault_access_policy_data_source.go [hunk 3]
```diff
@@ -62,89 +60,53 @@ func dataSourceKeyVaultAccessPolicy() *pluginsdk.Resource {
...
+		d.Set("key_permissions", keyPermissions)
 	}
 	if strings.Contains(name, "Secret") {
-		d.Set("secret_permissions", templateManagementPermissions["secret"])
+		d.Set("secret_permissions", secretPermissions)
 	}
 	if strings.Contains(name, "Certificate") {
-		d.Set("certificate_permissions", templateManagementPermissions["certificate"])
+		d.Set("certificate_permissions", certificatePermissions)
 	}
```
Comment (tombuildsstuff) [inline internal/services/keyvault/key_vault_access_policy_data_source.go:110]: we'll need to ensure that a value is always set into the state for these fields, else the list will be `null` rather than an empty slice

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hi @myc2h6o 

Thanks for this PR - taking a look at the resource here it appears that there's already a function which we can use for this information which comes from the Resource, as such it should be possible to use that instead of duplicating this?

Thanks!

**Comment by myc2h6o** [comment]
Hi @tombuildsstuff thanks for reviewing the change! I've looked at the templates from Portal and figured out the values from template are different from the functions `keyPermission(), ...`. I've tuned some values according to the latest templates and used the functions we have in the central location.
Below is the screenshot I captured from Portal:

image

**Comment by tombuildsstuff** [comment]
The PR https://github.com/hashicorp/pandora/pull/2456 should supersede this fwiw, since we'll be dynamically recasing this in both the Data Source and the Resource via the SDK

**Comment by myc2h6o** [comment]
@tombuildsstuff there are permissions change in `key_permissions` according to the latest template on Azure Portal, and is updated to always set the values even if not returned from API, so it's still needed?

**Review by stephybun — APPROVED** [review]
Thanks @myc2h6o LGTM. As an FYI these will need to be lower cased again once we switch keyvault over to the new base-layer, but since the behaviour is currently broken anyway this is fine for now.
