### PR TITLE
`azurerm_postgresql_flexible_server`: fix to set `administrator_login` with  `administrator_password_wo` when also enable password auth from false

### LINKED ISSUE #29447: azurerm_postgresql_flexible_server fails to enable authentication.password_auth_enabled on existing cluster
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.11.3

### AzureRM Provider Version

4.27.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "example" {
  administrator_login              = "pgadmin"
  administrator_password_wo        = module.ephemeral_resource.password
  administrator_password_wo_version = 1

  authentication {
    active_directory_auth_enabled = true
    password_auth_enabled         = true
    tenant_id                     = "...."
  }

  create_mode = "Default"
  version     = "16"

  # ... other configurations ...
}
```

### Debug Output/Panic Output

```shell
│ Status: "EngineCredentialsNotProvided"
│ Code: ""
│ Message: "The admin credentials are required for creating admin role while enabling Password Authentication and must be provided."
│ Activity Id: ""
```

### Expected Behaviour

Azure Postgres Flexible server that was created with `password_auth_enabled: false` will be updated to have password authentication enabled.

### Actual Behaviour

There is one scenario when it doesn't work as expected.
If postgres flexible server instance was created without password authentication enabled, then later trying to enable password authentication with terraform ends up in this error:

```
Status: "EngineCredentialsNotProvided"
Code: ""
Message: "The admin credentials are required for creating admin role while enabling Password Authentication and must be provided."
Activity Id: ""
```

However. 
If I deploy a NEW postgres flexible sever instance with `password_auth_enabled: true`. Deployment succeeds and all further deployments with same terraform code succeed as well. No errors like "EngineCredentialsNotProvided".

Also after I deployed it with `password_auth_enabled: true`, I can then change it to `password_auth_enabled: false`, deploy (it will remove password authentication). 
Then I change it back to `true` and try again - deployment works fine as expected.
So it looks the same terraform code that doesn't work when I try to run it on existing pg flexible server instance where password_auth_enabled was never activated.
But it works just fine if it has been ever activated in the past.

I've tried to do the same with Azure CLI and via Azure Portal.
Basically flipping the password_auth_enabled ON/OFF is fixing the problem. And terraform code starts to work as expected and I can then use it to enable/disable password authentication without issues.

### Steps to Reproduce

Deploy azurerm_postgresql_flexible_server resource in azure including following parameters:

```
password_auth_enabled: false
```

After deployment change the code to

```
password_auth_enabled: true

administrator_login: "pgadmin"

/// some ephemeral variable here, I used ephemeral "random_password"
administrator_password_wo: module.ephemeral_resource.password
administrator_password_wo_version: 1
```

Try to deploy again.
This should be enough to reproduce.

### Important Factoids

_No response_

### References

It looks similar to this bug in Azure CLI 
https://github.com/Azure/azure-cli/pull/30200

### PR DESCRIPTION
**Pull request by wuxu92**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

The admin password can be retrieve from `administrator_password` or `administrator_password_wo`, but in the `requireUpdateOnLogin` branch it directly get password from `administrator_password` only. In the scenario described in #29447, the `administratorLoginPassword` will be empty and cause the API returns the error.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
  # azurerm_postgresql_flexible_server.test will be updated in-place
  ~ resource "azurerm_postgresql_flexible_server" "test" {
      + administrator_login               = "adminTerraform"
        id                                = "/subscriptions/xxx/resourceGroups/rg-xuwu1-postgresql/providers/Microsoft.DBforPostgreSQL/flexibleServers/acctest-fs-xuwu1"
        name                              = "acctest-fs-xuwu1"
        tags                              = {}
        # (17 unchanged attributes hidden)

      ~ authentication {
          ~ password_auth_enabled         = false -> true
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

azurerm_postgresql_flexible_server.test: Modifications complete after 2m8s [id=/subscriptions/xxx/resourceGroups/rg-xuwu1-postgresql/providers/Microsoft.DBforPostgreSQL/flexibleServers/acctest-fs-xuwu1]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_postgresql_flexible_server` - fix set `administrator_password_wo` and enable password auth from false [GH-29447]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29447

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 1]
```diff
@@ -935,13 +935,19 @@ func resourcePostgresqlFlexibleServerUpdate(d *pluginsdk.ResourceData, meta inte
 
 	if requireUpdateOnLogin {
 		updateMode := servers.CreateModeUpdate
+		// login pasword can from adminitrator_password or administrator_password_wo
```
Comment (sreallymatt) [inline internal/services/postgres/postgresql_flexible_server_resource.go]:
```suggestion
		// Login password can be set using `administrator_password` or `administrator_password_wo`
```

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Thanks @wuxu92, just a minor comment regarding some typos in the comment. Once that's updated this should be good to go

**Comment by wuxu92** [comment]
> Thanks @wuxu92, just a minor comment regarding some typos in the comment. Once that's updated this should be good to go

@sreallymatt sorry for the late update, I committed the suggestion changes. thanks for reviewing.

**Review by sreallymatt — APPROVED** [review]
Thanks @wuxu92 LGTM ✅
