### PR TITLE
`azurerm_storage_account` - Add sanity check for `dns_endpoint_type` and `blob_properties.restore_policy`

### LINKED ISSUE #25410: storage.BlobServicesClient#SetServiceProperties: "Required feature Global Dns is disabled."
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "spoke_std_storage_account" {
  provider = azurerm.cluster_subscription

  name                            = local.std_storage_account_name
  resource_group_name             = "rg"
  location                        = "North Europe"
  account_tier                    = "Standard"
  account_replication_type        = "ZRS"
  public_network_access_enabled   = false
  nfsv3_enabled                   = false
  account_kind                    = "StorageV2"
  is_hns_enabled                  = false
  allow_nested_items_to_be_public = false
  dns_endpoint_type               = "AzureDnsZone"
  shared_access_key_enabled       = false

  network_rules {
    default_action = "Deny"
    bypass         = ["AzureServices"]
  }

  blob_properties {
    versioning_enabled      = true
    change_feed_enabled     = true

    delete_retention_policy {
      days = 10
    }

    restore_policy {
      days = 9
    }
  }

  routing {
    publish_microsoft_endpoints = true
    publish_internet_endpoints  = false
    choice                      = "MicrosoftRouting"
  }

  lifecycle {
    ignore_changes  = [tags]
    prevent_destroy = false
  }
}
```

### Debug Output/Panic Output

```shell
Error: updating `blob_properties`: storage.BlobServicesClient#SetServiceProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="RequiredFeatureDisabled" Message="Required feature Global Dns is disabled."

  with azurerm_storage_account.spoke_std_storage_account,
  on storage_account.tf line 1, in resource "azurerm_storage_account" "spoke_std_storage_account":
   1: resource "azurerm_storage_account" "spoke_std_storage_account" {
```

### Expected Behaviour

That the storage account is created with current settings. 

### Actual Behaviour

This is tricky one because I don't know if:

1 - The request made by the provider is wrong
2 - The combination of parameter I am using is not supported (and the provider lacks the specific validation)
3 - Something on my setup needs to change. I am creating a storage account within the context of hub & spoke architecture
4 - Is a problem with Azure API
5 - The error message is misleading and is throwing me off the real problem. I couldn't find any meaningful information about this error anywhere. There is no such feature, to enable in Azure registration procedure.

What I do know is that:

dns_endpoint_type               = "AzureDnsZone"

causes the error. The required feature Distributed Dns is already enabled for the subscription. Without this flag, the storage account becomes unreachable to the deployment agent. For some reason, the provider tries to access it via the domain name instead of resource id. I can access from the same machine via the portal, but the provider times out  when dns_endpoint_type parameter is not set, due to the fact that the private endpoint has not been created yet, so it fails to validate the resource creation.

Whic creates this kind of chicken and egg problem for storage accounts without public network access being deployed by the provider that runs in a jumpbox, peered to the Hub. The same jumpbox can access the resource via the portal, but not the provider. I already changed the provider to use "storage_use_azuread = true", but that didn't change anything.

Now this error message leads me to nowhere and I can only think that this is a bug, although not entirely sure from where. I exhausted everything I could think of that could cause a side effect like this.

### Steps to Reproduce

You will need a hub and spoke architecture setup and try to create a storage account with this code. 
Hub and spoke are in separate regions and that may play a role.

### Important Factoids

There may be a relation with the fact that the spoke in question is located in North Europe and the Hub is West Europe.
Jumpbox where it is being deployed from is a third spoke which is the same region of the Hub (West Europ)
But the vnets in question have Microsoft.Storage.Global service_endpoint enabled, which would be required for the complete setup which has a private endpoint.

### References

_No response_

### PR DESCRIPTION
**Pull request by magodo**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

`azurerm_storage_account` - Add sanity check for `dns_endpoint_type` and `blob_properties.restore_policy`

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```shell
terraform-provider-azurerm on  storage_restore_policy_check_against_dns_partition via 🐹 v1.22.1
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/storage -run='TestAccStorageAccount_basic'
=== RUN   TestAccStorageAccount_basic
=== PAUSE TestAccStorageAccount_basic
=== CONT  TestAccStorageAccount_basic
--- PASS: TestAccStorageAccount_basic (198.34s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       198.377s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_storage_account` - Add sanity check for `dns_endpoint_type` and `blob_properties.restore_policy` [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25410

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/storage/storage_account_resource.go [hunk 1]
```diff
@@ -1589,6 +1589,15 @@ func resourceStorageAccountCreate(d *pluginsdk.ResourceData, meta interface{}) e
 			}
 		}
 
+		if dnsEndpointType == string(storage.DNSEndpointTypeAzureDNSZone) {
+			if blobProperties.RestorePolicy != nil && blobProperties.RestorePolicy.Enabled != nil && *blobProperties.RestorePolicy.Enabled {
+				// Otherwise, API returns: "Required feature Global Dns is disabled"
+				// This is confirmed with the SRP team, where they said:
+				// > restorePolicy feature is incompatible with partitioned DNS
```
Comment (tombuildsstuff) [inline internal/services/storage/storage_account_resource.go:1596]: did they mention if this is a temporary limitation, or something that's planned to be removed in the future?

**Review by tombuildsstuff — APPROVED** [review]
One question just to clarify the comments but otherwise 👍

File: internal/services/storage/storage_account_resource.go (hunk 1 above)
Comment (magodo) [reply internal/services/storage/storage_account_resource.go:1596]: @tombuildsstuff I'll check with them and update it here later..

Comment (katbyte) [reply internal/services/storage/storage_account_resource.go:1596]: @magodo any update on this?

Comment (magodo) [reply internal/services/storage/storage_account_resource.go:1596]: Sorry for the delay (as I was on vacation), I just got the reply from the service team that this is a temporary limitation, and they said they don't have an ETA when this will be supported.

Comment (tombuildsstuff) [reply internal/services/storage/storage_account_resource.go:1596]: No worries - hope you enjoyed the time off :)

Cool ok, in that case can we update this comment to clarify that this is a temporary limitation rather than long-term limitation and so we should re-check this in the future? Perhaps it'd also be worth linking to this thread too?

Comment (magodo) [reply internal/services/storage/storage_account_resource.go:1598]: @tombuildsstuff Sure, I've added the comment.
