### PR TITLE
`azurerm_postgresql_flexible_server` - Add support for `version` `15`

### LINKED ISSUE #21921: Support for PostgreSQL version 15
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

v15 is already in preview and will be GA pretty soon.

> with azurerm_postgresql_flexible_server.v15,
│   on postgres.tf line 91, in resource "azurerm_postgresql_flexible_server" "v15":
│   91:   version                = "15"
│ 
╵
##[error]Terraform command 'validate' failed with exit code '1'.
##[error]╷
│ Error: expected version to be one of [14 11 13 12], got 15

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Potential Terraform Configuration

_No response_

### References

https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/why-should-you-migrate-to-postgresql-15/ba-p/3810725

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #21921

The newest version is not yet available in the REST API.

Screenshot 2023-05-25 at 16 14 24

### CODE REVIEW

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 1]
```diff
@@ -128,7 +128,7 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
 				Type:         pluginsdk.TypeString,
 				Optional:     true,
 				Computed:     true,
-				ValidateFunc: validation.StringInSlice(servers.PossibleValuesForServerVersion(), false),
+				ValidateFunc: validation.StringInSlice(append(servers.PossibleValuesForServerVersion(), "15"), false),
```
Comment (mbfrahry) [inline internal/services/postgres/postgresql_flexible_server_resource.go:131]: Any chance you can open an issue on their [api-specs](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2022-12-01/FlexibleServers.json#L376) and link that as a todo to remove once that is merged here?

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @aristosvo, thanks for this PR. It's shame that their api doesn't support this value yet. Can you open an issue on their api-specs and link that here? We'll be good to merge after that!

File: internal/services/postgres/postgresql_flexible_server_resource.go (hunk 1 above)
Comment (aristosvo) [inline internal/services/postgres/postgresql_flexible_server_resource.go:131]:
```suggestion
				// TODO: Remove "15" after this issue has been resolved:
				// https://github.com/Azure/azure-rest-api-specs/issues/24186
				ValidateFunc: validation.StringInSlice(append(servers.PossibleValuesForServerVersion(), "15"), false),
```

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for getting that issue opened
