### PR TITLE
`azurerm_redis_cache` - Fix the issue about data persistence could not be switched

### LINKED ISSUE #20228: Can't switch data persistence in `azure_cache_redis`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_cache_redis

### Terraform Configuration Files

```hcl
resource "azurerm_redis_cache" "main" {
  name                          = var.name
  location                      = azurerm_resource_group.main.location
  resource_group_name           = azurerm_resource_group.main.name
  redis_version                 = var.redis.redis_version
  replicas_per_primary          = var.redis.replicas_per_primary
  family                        = "P"
  capacity                      = var.redis.capacity
  sku_name                      = "Premium"
  minimum_tls_version           = "1.2"
  subnet_id                     = var.default_subnet_id
  public_network_access_enabled = false
  shard_count                   = var.cluster.enable_cluster ? var.cluster.shard_count : 0
  tags                          = var.default_tags

  redis_configuration {
    rdb_backup_enabled              = false
    aof_backup_enabled              = true
    aof_storage_connection_string_0 = azurerm_storage_account.aof0.primary_connection_string
    aof_storage_connection_string_1 = azurerm_storage_account.aof1.primary_connection_string
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: updating Redis Cache "local-dev-redis-0003" (Resource Group "local-dev-redis-0003"): redis.Client#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="AOF and RDB cannot both be enabled\r\nRequestID=4430166a-1f01-#########4"
│
│   with azurerm_redis_cache.main,
│   on main.tf line 7, in resource "azurerm_redis_cache" "main":
│    7: resource "azurerm_redis_cache" "main" {
```

### Expected Behaviour

`azure_cache_redis` can freely switch between data persistence types without any issues, just like in the Azure portal

### Actual Behaviour

I can't switch from `RDB` to `AOF` persistence or switch back. Also, I tried completely disabling data persistence before enabling `AOF` persistence, and I get the same error. Looks like remnants of data persistence gets left in the statefile somehow. 

Only way I can switch persistence is to completely destroy the cache and recreate it using another type. This is **not** how this behaves in the Azure portal.

### Steps to Reproduce

`terraform apply`

### Important Factoids

_No response_

### References

https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-premium-persistence#can-i-enable-aof-and-rdb-persistence-at-the-same-time

### PR DESCRIPTION
**Pull request by sinbai**
The `rdb_backup_enabled` or `aof_backup_enabled` is set to false in config when updating resource `azurerm_redis_cache`, they should be explicitly set value in terraform code so that data persistence could be switched.

Fix #20228 .

Test Results:
PASS: TestAccRedisCache_BackupEnabledDisabled (2173.38s)
PASS: TestAccRedisCache_AOFBackupEnabledDisabled (2631.76s)

### CODE REVIEW

File: internal/services/redis/redis_cache_resource.go [hunk 1]
```diff
@@ -817,11 +817,17 @@ func expandRedisConfiguration(d *pluginsdk.ResourceData) (*redis.CommonPropertie
 	}
 
 	// RDB Backup
-	if v := raw["rdb_backup_enabled"].(bool); v {
-		if connStr := raw["rdb_storage_connection_string"].(string); connStr == "" {
-			return nil, fmt.Errorf("The rdb_storage_connection_string property must be set when rdb_backup_enabled is true")
+	// the "output.RdbBackupEnabled" should be set value when the rdb_backup_enabled is set to false in config since not setting false means it could not be disabled using patch to update the Redis Cache.
+	// d.GetOk cannot identify if user sets the property that is bool type and `rdb_backup_enabled` is set as `false`. So it has to identify it using `d.GetRawConfig()`
+	if v := d.GetRawConfig().AsValueMap()["redis_configuration"].AsValueSlice(); len(v) > 0 && !v[0].AsValueMap()["rdb_backup_enabled"].IsNull() {
```
Comment (tombuildsstuff) [inline internal/services/redis/redis_cache_resource.go:822]: rather than using `GetRawConfig` - we should update this to use `d.GetOkExists` - since this approach can be nil/crash at multiple points along this expression

File: internal/services/redis/redis_cache_resource.go [hunk 2]
```diff
@@ -841,8 +847,14 @@ func expandRedisConfiguration(d *pluginsdk.ResourceData) (*redis.CommonPropertie
 	}
 
 	// AOF Backup
-	if v := raw["aof_backup_enabled"].(bool); v {
-		output.AdditionalProperties["aof-backup-enabled"] = utils.String(strconv.FormatBool(v))
+	// the "output.AdditionalProperties["aof-backup-enabled"]" should be set value when the aof_backup_enabled is set to false in config since not setting false means it could not be disabled using patch to update the Redis Cache.
+	// d.GetOk cannot identify if user sets the property that is bool type and `aof_backup_enabled` is set as `false`. So it has to identify it using `d.GetRawConfig()`
+	if v := d.GetRawConfig().AsValueMap()["redis_configuration"].AsValueSlice(); len(v) > 0 && !v[0].AsValueMap()["aof_backup_enabled"].IsNull() {
```
Comment (tombuildsstuff) [inline internal/services/redis/redis_cache_resource.go:852]: (same here)

File: internal/services/redis/redis_cache_resource_test.go [hunk 3]
```diff
@@ -143,6 +143,7 @@ func TestAccRedisCache_BackupDisabled(t *testing.T) {
 			Check: acceptance.ComposeTestCheckFunc(
 				check.That(data.ResourceName).ExistsInAzure(r),
 			),
+			ExpectNonEmptyPlan: true,
```
Comment (tombuildsstuff) [inline internal/services/redis/redis_cache_resource_test.go:146]: doing this would signify there's a bug to fix?

File: internal/services/redis/redis_cache_resource_test.go [hunk 4]
```diff
@@ -720,10 +733,13 @@ resource "azurerm_redis_cache" "test" {
   enable_non_ssl_port = false
 
   redis_configuration {
-    rdb_backup_enabled = false
+    rdb_backup_enabled              = false
+    aof_backup_enabled              = true
+    aof_storage_connection_string_0 = "DefaultEndpointsProtocol=https;BlobEndpoint=${azurerm_storage_account.test.primary_blob_endpoint};AccountName=${azurerm_storage_account.test.name};AccountKey=${azurerm_storage_account.test.primary_access_key}"
+    aof_storage_connection_string_1 = "DefaultEndpointsProtocol=https;BlobEndpoint=${azurerm_storage_account.test.primary_blob_endpoint};AccountName=${azurerm_storage_account.test.name};AccountKey=${azurerm_storage_account.test.secondary_access_key}"
```
Comment (tombuildsstuff) [inline internal/services/redis/redis_cache_resource_test.go:739]: there's `primary_` and `secondary_` connection strings available on the storage account resource?

File: internal/services/redis/redis_cache_resource_test.go [hunk 5]
```diff
@@ -789,10 +817,14 @@ resource "azurerm_redis_cache" "test" {
   enable_non_ssl_port = false
 
   redis_configuration {
-    aof_backup_enabled = false
+    aof_backup_enabled            = false
+    rdb_backup_enabled            = true
+    rdb_backup_frequency          = 60
+    rdb_backup_max_snapshot_count = 1
+    rdb_storage_connection_string = "DefaultEndpointsProtocol=https;BlobEndpoint=${azurerm_storage_account.test.primary_blob_endpoint};AccountName=${azurerm_storage_account.test.name};AccountKey=${azurerm_storage_account.test.primary_access_key}"
```
Comment (tombuildsstuff) [inline internal/services/redis/redis_cache_resource_test.go:824]: (same here)

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hi @sinbai 

Thanks for this PR.

I've taken a look through and left some comments inline, unfortunately we need to take a different approach to what's used here, namely rather than leaning on `GetRawConfig` (which can return nil, so will crash in the current context), we can instead use `GetOkExists` to achieve the same thing in a safer manner.

Thanks!

File: internal/services/redis/redis_cache_resource_test.go (hunk 4 above)
Comment (mclacore) [reply internal/services/redis/redis_cache_resource_test.go:739]: This shouldn't be the `primary` and `secondary` connection strings for the same storage account. This should be 2 separate storage accounts. 

Ref: https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-premium-persistence#when-should-i-use-a-second-storage-account

File: internal/services/redis/redis_cache_resource_test.go (hunk 3 above)
Comment (sinbai) [reply internal/services/redis/redis_cache_resource_test.go:150]: Yes, there is a [bug](https://github.com/Azure/azure-rest-api-specs/issues/3037). I have added a comment to it.

File: internal/services/redis/redis_cache_resource_test.go (hunk 4 above)
Comment (sinbai) [reply internal/services/redis/redis_cache_resource_test.go]: @tombuildsstuff , @mclacore , thanks for your feedback. I have updated the test. Could you take another look?

File: internal/services/redis/redis_cache_resource_test.go (hunk 5 above)
Comment (sinbai) [reply internal/services/redis/redis_cache_resource_test.go]: Fixed.

File: internal/services/redis/redis_cache_resource.go (hunk 1 above)
Comment (sinbai) [reply internal/services/redis/redis_cache_resource.go:822]: @tombuildsstuff thanks for your time to review this PR. If we use `if v, ok := d.GetOkExists("redis_configuration.0.rdb_backup_enabled"); ok{`  instead of `GetRawConfig`, the vaule of ok is true when the `rdb_backup_enabled` is removed in tf config. But the `GetRawConfig` is null (meaning false) in this case. 

Using `GetOkExists` means that if user specifies `rdb_backup_enabled` as true in creating a resource, and then removes `rdb_backup_enabled` in tf config to update the resource, the  `rdb_backup_enabled`  would be set to false.  In fact, the behavior of API in this case, the  `rdb_backup_enabled`  should remain true. That's why I use   `GetRawConfig` ranther than `GetOkExists`.  BTW, if rdb_backup_enabled is not specified, API return nil. 

So I assume that the `GetRawConfig` could not be replaced by `GetOkExists`. Please feel free let me know your feedback on this case.

File: internal/services/redis/redis_cache_resource.go (hunk 2 above)
Comment (sinbai) [reply internal/services/redis/redis_cache_resource.go:852]: Same answer as above.

File: internal/services/redis/redis_cache_resource_test.go (hunk 4 above)
Comment (mclacore) [reply internal/services/redis/redis_cache_resource_test.go]: LGTM 👍

File: internal/services/redis/redis_cache_resource.go (hunk 1 above)
Comment (katbyte) [reply internal/services/redis/redis_cache_resource.go:822]: @sinbai if you are going to do this you must be checking each conversion for a nil/crash. right now if anything changes/something unexpected happens this code will panic

**Review by katbyte — CHANGES_REQUESTED** [review]

**Comment by sinbai** [comment]
@katbyte thanks for your feedback. Code has been updated. Could you please take another look?

**Comment by katbyte** [comment]
@sinbai - could we fix the merge conflicts?

**Comment by sinbai** [comment]
> @sinbai - could we fix the merge conflicts?

Sure, fixed.

**Comment by katbyte** [comment]
@sinbai - after discussing internally i was informed that GetRawConfig will not be directly available when we switch to framework. We think  GetOkExists should be fine as there is a default, so we can just use the default?

**Comment by sinbai** [comment]
> @sinbai - after discussing internally i was informed that GetRawConfig will not be directly available when we switch to framework. We think GetOkExists should be fine as there is a default, so we can just use the default?

As I replied above , `using GetOkExists means that if user specifies rdb_backup_enabled as true in creating a resource, and then removes rdb_backup_enabled in tf config to update the resource, the rdb_backup_enabled would be set to false. In fact, the behavior of API in this case, the rdb_backup_enabled should remain true. That's why I use GetRawConfig ranther than GetOkExists. `

**Comment by katbyte** [comment]
@sinbai - the problem with us using get raw is that in the future when we move to framework, as i understand it, it won't be supported. so you will be introducing a future breaking change/behaviour we will not be able to mimic. 

I'm not sure why you cannot just use GetOkExist? it sounds like the property should be defaulting to true to match the API behaviour? and that would be a breaking change that we can ship for 4.0?

**Comment by sinbai** [comment]
> @sinbai - the problem with us using get raw is that in the future when we move to framework, as i understand it, it won't be supported. so you will be introducing a future breaking change/behaviour we will not be able to mimic.
> 
> I'm not sure why you cannot just use GetOkExist? it sounds like the property should be defaulting to true to match the API behaviour? and that would be a breaking change that we can ship for 4.0?



> @sinbai - the problem with us using get raw is that in the future when we move to framework, as i understand it, it won't be supported. so you will be introducing a future breaking change/behaviour we will not be able to mimic.
> 
> I'm not sure why you cannot just use GetOkExist? it sounds like the property should be defaulting to true to match the API behaviour? and that would be a breaking change that we can ship for 4.0?

Hi @katbyte

The reason I previously thought that using `GetOkExist` would not work was because updating behavior of TF was inconsistent with the update behavior of the API. See below for details:

Using `GetOkExist`, if user specifies `rdb_backup_enabled` as true in creating a resource, and then removes `rdb_backup_enabled` in tf config to update the resource by TF, TF would set `rdb_backup_enabled` to false. In this case, the update API would not update the value of `rdb_backup_enabled`, keep it true.

But for now, I think that `GetOkExist` can fix issue #20228 as long as we state in TF doc that the default value of `rdb_backup_enabled` is false. With it, it is by design that TF updates `rdb_backup_enabled` to false in the above situation. So, I update the code by using `GetOkExist` , and all the tests passed in Teamcity, could you please take another look?

**Review by katbyte — APPROVED** [review]
Thanks @sinbai - i think that is fine as the default should already have been false.

LGTM 🌵
