### PR TITLE
[Bug:] `azurerm_cdn_frontdoor_rule` - allow the `cdn_frontdoor_origin_group_id` field to be optional in the `route_configuration_override_action`, expose `Disabled` as a possible value of `cache_behavior`

### LINKED ISSUE #18889: azurerm_cdn_frontdoor_rule route_configuration_override_action cdn_frontdoor_origin_group_id parameter should not be required
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The parameter `cdn_frontdoor_origin_group_id` is required when specifying a `route_configuration_override_action` within an `azurerm_cdn_frontdoor_rule` resource. 
(see https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_rule#cdn_frontdoor_origin_group_id)

In Azure Portal, it is possible to set "Override origin group" to "No", leaving the original routing untouched while other changes are still possible. This cannot be configured using terraform as long as `cdn_frontdoor_origin_group_id` is a required parameter.

Actual use case:
The same rule set should be used for several routes with different origin groups. Caching behavior should be changed based on url_path_condition, but routing itself should not be changed.

Please allow the parameter `cdn_frontdoor_origin_group_id` to be optional to cover this use case.

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Potential Terraform Configuration

```hcl
resource "azurerm_cdn_frontdoor_rule" "MakeSureApisHaveShortCacheTime" {
  depends_on = [azurerm_cdn_frontdoor_origin_group.web, azurerm_cdn_frontdoor_origin.web]

  name                      = "MakeSureApisHaveShortCacheTime"
  cdn_frontdoor_rule_set_id = azurerm_cdn_frontdoor_rule_set.web.id
  order                     = 1
  behavior_on_match         = "Continue"

  conditions {
    url_path_condition {
      operator         = "RegEx"
      negate_condition = false
      match_values     = ["/api/?(.*)"]
      transforms       = ["Lowercase", "Trim"]
    }
  }

  actions {
    route_configuration_override_action {
      cdn_frontdoor_origin_group_id = null
      forwarding_protocol           = "HttpsOnly"
      query_string_caching_behavior = "UseQueryString"
      compression_enabled           = true
      cache_behavior                = "OverrideAlways"
      cache_duration                = "0:0:10"
    }
  }
}
```

### References

_No response_

### LINKED ISSUE #19008: `azurerm_cdn_frontdoor_rule` does not expose a way to disable the cache which is allowed in the portal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

**I have opened this issue for the community member, @sudeep1607, who originally reported this issue for tracking purposes**

>How to disable cache through terraform when configuring `route_configuration_override_action` in `azurerm_cdn_frontdoor_rule` resource. I don't see any parameter for that and `cache_duration` argument is being shown as Required. When caching is disabled for the action we don't have to specify duration right?
>
>image

### Terraform Version

12.31.0

### AzureRM Provider Version

3.27.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Expected Behaviour

You should be able to disable the cache via the Front Door (standard/premium) Rules resource just like you can in portal

### Actual Behaviour

There is no way currently exposed in the Terraform Front Door (standard/premium) Rules resource to allow this.

### Steps to Reproduce

You cannot as this is not currently supported

### Important Factoids

N/A

### References

#18889

### PR DESCRIPTION
**Pull request by WodansSon**
## Optional `cdn_frontdoor_origin_group_id`:

```hcl
actions {
  route_configuration_override_action {
    query_string_caching_behavior = "IncludeSpecifiedQueryStrings"
    query_string_parameters       = ["foo", "clientIp={client_ip}"]
    compression_enabled           = true
    cache_behavior                = "OverrideIfOriginMissing"
    cache_duration                = "365.23:59:59"
  }
}
```
|<b>NOTE:</b>|If you do not define the `cdn_frontdoor_origin_group_id` you cannot define `forwarding_protocol` as this would result in an error from the API.|
|-|:-|

(fixes #18889)

---

## Disable Cache Without the Origin Group ID:

```hcl
  actions {
    route_configuration_override_action {
      cache_behavior = "Disabled"
    }
  }
```

## Disable Cache With the Origin Group ID:

```hcl
  actions {
    route_configuration_override_action {
      cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.example.id
      forwarding_protocol           = "HttpsOnly"
      cache_behavior                = "Disabled"
    }
  }
```

(fixes #19008)

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @WodansSon, unfortunately there's a test failure
```
------- Stdout: -------
=== RUN   TestAccCdnFrontDoorRule_basicRegression18889
=== PAUSE TestAccCdnFrontDoorRule_basicRegression18889
=== CONT  TestAccCdnFrontDoorRule_basicRegression18889
testcase.go:110: Step 1/2 error: Error running apply: exit status 1
Error: expanding 'actions': the 'route_configuration_override_action' block is not valid, 'forwarding_protocol' can not be defined if the 'cdn_frontdoor_origin_group_id' is not set, got "HttpsOnly"
with azurerm_cdn_frontdoor_rule.test,
on terraform_plugin_test.tf line 49, in resource "azurerm_cdn_frontdoor_rule" "test":
49: resource "azurerm_cdn_frontdoor_rule" "test" {
--- FAIL: TestAccCdnFrontDoorRule_basicRegression18889 (168.80s)
FAIL
```

**Comment by WodansSon** [comment]
@stephybun, sorry about that I thought I marked this as `in progress`, but thank you for the quick review! 🚀 I think this PR is actually ready for a review now. 🙂

**Comment by WodansSon** [comment]
My test finally ran after over 5 hours of waiting, it appears I need to add some extra validation around the input values during create... 😭

**Comment by WodansSon** [comment]
image

File: internal/services/cdn/cdn_frontdoor_rule_resource.go [hunk 1]
```diff
@@ -246,14 +246,14 @@ func resourceCdnFrontDoorRule() *pluginsdk.Resource {
...
-										Required:     true,
+										Optional:     true,
 										ValidateFunc: validate.FrontDoorOriginGroupID,
 									},
 
+									// Removed Default value for issue #18889, default value is applied in the ExpandCdnFrontDoorRouteConfigurationOverrideAction func
 									"forwarding_protocol": {
 										Type:     pluginsdk.TypeString,
 										Optional: true,
-										Default:  string(cdn.ForwardingProtocolMatchRequest),
```
[the remark this answers is not in the document]
Comment (WodansSon) [reply internal/services/cdn/cdn_frontdoor_rule_resource.go:256]: This cannot be `Computed` because that would cause a perpetual diff since you would not actually be able to clear the value, which is required to make this to work correctly.

**Comment by WodansSon** [comment]
@stephybun, I am sorry I had to cancel your build on the TC server because I resolved the documentation conflict with main. However, before KT merged the other documentation PR I kicked off a new TC build and I will attach the results to this PR comment thread once it completes. Feel free to kick off another one if you'd like. 🙂

**Comment by WodansSon** [comment]
image

File: internal/services/cdn/cdn_frontdoor_rule_resource.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (WodansSon) [reply internal/services/cdn/cdn_frontdoor_rule_resource.go:256]: Due to another [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/18889#issuecomment-1290253767) (mentioned in the comment thread of the original issue) I had to make every field for this `action` optional and fix it in the `expand`/`flatten` functions of the resource. This is all related to Portal magic, I have added the following to the documentation **NOTE** to the `route_configuration_override_action` block. I know this is not ideal, but I feel this is the best that we can do given the cards we have been delt.

| <b>NOTE:</b> | While `cache_duration`, `cache_behavior` and `query_string_caching_behavior` do have default values, if you do not define these properties in your configuration file you will receive a diff during plan. |
| -- | :-- |

File: internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go [hunk 2]
```diff
@@ -354,13 +410,17 @@ func FlattenCdnFrontDoorRouteConfigurationOverrideAction(input cdn.DeliveryRuleR
...
 		}
 
 		if override := params.OriginGroupOverride; override != nil {
 			forwardingProtocol = string(override.ForwardingProtocol)
 
-			if group := override.OriginGroup; group != nil && group.ID != nil {
-				originGroupId = *group.ID
+			// NOTE: Need to normalize this ID here because if you modified this in portal the resourceGroup comes back as resourcegroup.
+			// ignore the error here since it was set on the resource in Azure and we know it is valid.
+			if originGroup, err := parse.FrontDoorOriginGroupIDInsensitively(*override.OriginGroup.ID); err == nil {
```
Comment (tombuildsstuff) [inline internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go:422]: in the Expand function we should be parsing these case-sensitively:

```suggestion
			if originGroup, err := parse.FrontDoorOriginGroupID(*override.OriginGroup.ID); err == nil {
```

Comment (WodansSon) [reply internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go:422]: I added this code specifically because if I created the rule in the portal and attempted it import it it would fail because of the casing of the resource group element. Is there something I am missing here?

**Comment by WodansSon** [comment]
image

File: internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go [hunk 3]
```diff
@@ -207,49 +208,104 @@ func ExpandCdnFrontDoorUrlRewriteAction(input []interface{}) (*[]cdn.BasicDelive
...
-		cacheConfiguration := &cdn.CacheConfiguration{
-			QueryStringCachingBehavior: cdn.RuleQueryStringCachingBehavior(item["query_string_caching_behavior"].(string)),
-			QueryParameters:            expandStringSliceToCsvFormat(item["query_string_parameters"].([]interface{})),
-			IsCompressionEnabled:       compressionEnabled,
-			CacheBehavior:              cdn.RuleCacheBehavior(item["cache_behavior"].(string)),
-			CacheDuration:              utils.String(item["cache_duration"].(string)),
+		// set the default value for forwarding protocol to avoid a breaking change...
+		if protocol == "" {
+			protocol = string(cdn.ForwardingProtocolMatchRequest)
 		}
```
Comment (tombuildsstuff) [inline internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go:230]: this'll want to be changed in v4.0, so could we feature-flag this?

File: internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go [hunk 4]
```diff
@@ -207,49 +208,104 @@ func ExpandCdnFrontDoorUrlRewriteAction(input []interface{}) (*[]cdn.BasicDelive
...
+
+			if cacheDuration := item["cache_duration"].(string); cacheDuration != "" {
+				return nil, fmt.Errorf("the 'route_configuration_override_action' block is not valid, if the 'cache_behavior' is set to 'Disabled' you cannot define the 'cache_duration', got %q", cacheDuration)
 			}
 		} else {
-			if queryStringCachingBehavior == cdn.RuleQueryStringCachingBehaviorUseQueryString || queryStringCachingBehavior == cdn.RuleQueryStringCachingBehaviorIgnoreQueryString {
-				return nil, fmt.Errorf("the 'route_configuration_override_action' block is not valid, 'query_string_parameters' must not be set if the'query_string_caching_behavior' is set to 'UseQueryStrings' or 'IgnoreQueryStrings'")
+			// since 'cache_duration', 'query_string_caching_behavior' and 'cache_behavior' are optional create a default values
+			// for those values if not set.
+			cacheDuration := "1.12:00:00"
```
Comment (tombuildsstuff) [inline internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go:262]: is there some context for this default value, presumably this is coming from the API's default value/the portal or something?

File: internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go (hunk 2 above)
Comment (tombuildsstuff) [reply internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go:422]: apologies that's my bad for missing this was in the Flatten and not the Expand - we should raise this error if this fails to pass, but this is otherwise fine 👍

File: website/docs/r/cdn_frontdoor_rule.html.markdown [hunk 5]
```diff
@@ -197,7 +197,9 @@ An `url_redirect_action` block supports the following:
 
 A `route_configuration_override_action` block supports the following:
 
-* `cache_duration` - (Required) When Cache behavior is set to `Override` or `SetIfMissing`, this field specifies the cache duration to use. The maximum duration is 366 days specified in the `d.HH:MM:SS` format(e.g. `365.23:59:59`). If the desired maximum cache duration is less than 1 day then the maximum cache duration should be specified in the `HH:MM:SS` format(e.g. `23:59:59`).
+->**NOTE:** While `cache_duration`, `cache_behavior` and `query_string_caching_behavior` do have default values, if you do not define these properties in your configuration file you will receive a diff during plan.
```
Comment (tombuildsstuff) [inline website/docs/r/cdn_frontdoor_rule.html.markdown:200]: this is the default behaviour for Terraform properties, perhaps what we should be saying is something along the lines of: "you can use [Terraform's `ignore_changes` functionality](XXX) to ignore these default values`?

**Review by tombuildsstuff — APPROVED** [review]
Left a few comments inline, but this otherwise LGTM 👍

File: internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go (hunk 4 above)
Comment (WodansSon) [reply internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go:262]: There is, Front Door will default the cache to somewhere between 1 to 3 days, I have no way of knowing what Front Door decided and since I had to offer a default value to match the portal experience and this field has to be optional now I picked a value in the middle of what the Front Door documentation says the cache range can be... it seemed to me to be the lesser of the two evils and also allows for parity in functionality between Terraform and the Portal, which does not currently exist in any other CLI solutions.

File: website/docs/r/cdn_frontdoor_rule.html.markdown (hunk 5 above)
Comment (WodansSon) [reply website/docs/r/cdn_frontdoor_rule.html.markdown:200]: Fixed.

File: internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go (hunk 3 above)
Comment (WodansSon) [reply internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go:230]: I personally believe that we should keep the default values in v4.0 as well since the service will return a 400 bad request error if the fields are not in the create/update call. I can feature-flag them if you would like, but I think that would lead to a bad user experience in v4.0 if we remove them.

**Review by katbyte — APPROVED** [review]
LGTM 🍄

**Comment by WodansSon** [comment]
image
