### PR TITLE
`azurerm_windows_web_app`/`azurerm_windows_web_app_slot` - fix perpetual diff around incorrect default for `always_on` and ignore default values for `logs.0.application_logs`

### LINKED ISSUE #16326: Terraform always tries to remove default "site_config.virtual_application" on "azurerm_windows_web_app_slot".
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app_slot

### Terraform Configuration Files

```hcl
resource "azurerm_windows_web_app" "app" {
  name                = "app"
  location            = var.location
  resource_group_name = var.rg
  service_plan_id     = azurerm_service_plan.asp.id
  
  site_config {
    always_on           = true
    minimum_tls_version = "1.2"
    ftps_state          = "FtpsOnly"
    http2_enabled       = true
    use_32_bit_worker   = false

    application_stack {
      current_stack  = "dotnet"
      dotnet_version = "v6.0"
    }
  }
}

resource "azurerm_windows_web_app_slot" "app_slot" {
  name           = "staging"
  app_service_id = azurerm_windows_web_app.app.id

  site_config {
    always_on           = false
    minimum_tls_version = "1.2"
    ftps_state          = "FtpsOnly"
    http2_enabled       = true
    use_32_bit_worker   = false

    application_stack {
      current_stack  = "dotnet"
      dotnet_version = "v6.0"
    }
}
```

### Debug Output/Panic Output

```shell
# azurerm_windows_web_app_slot.app_slot has been changed
  ~ resource "azurerm_windows_web_app_slot" "app_slot" {
        id                                = "app_id"
        name                              = "staging"

        # (16 unchanged attributes hidden)




      ~ site_config {
            # (23 unchanged attributes hidden)



          - virtual_application {
              - physical_path = "site\\wwwroot"
              - preload       = false
              - virtual_path  = "/"
            }
            # (2 unchanged blocks hidden)
        }

        # (4 unchanged blocks hidden)
    }
```

### Expected Behaviour

Since we have not configured `site_config.virtual_application` we would expect it to not appear at the plan / apply step as a modification that has to be done, since we are just using the default mapping 
 and since it is optional in the docs we would expect it to not interfere with the default mapping and thus not always be detected as a change. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app_slot#virtual_application.

### Actual Behaviour

That mapping is the default mapping for an Azure App Serivce.
When running terraform plan / apply with no configuration changes, terraform tries always tries to remove this default mapping.
"terraform apply" passes, but it won't remove that mapping since it's the only one as default.

This leads to it always appearing as a change in the terraform plan / apply step which is inconvenient as it clutters up and makes it harder to read other changes since we have this one appearing all the time.

We would like to know if this is expected and we should configure the default mapping explicitly through terraform or is there another issue.

### Steps to Reproduce

run terraform plan / apply on an already existing config and terraform will always try to remove the "default" virtual application on the `azurerm_windows_web_app_slot`

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by mbfrahry**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR fixes an issue where a perpetual diff occurred when `always_on` was false. Azure changed the default value of `virtual_application.0.preload_enabled` to `false` whereas we assumed it was true regardless of `always_on`.

This PR also addresses an issue where we were not setting `logs.0.application_logs.0.file_system_level` was `Off`. This was added to prevent a perpetual diff when the default values for `logs.0.application_logs` were returned by Azure but not set into Terraform which resulted in a perpetual diff. We now only set `logs.0.application_logs` when it's not the default values and use a DiffSuppressFunc to ignore the default values on subsequent plans.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_windows_web_app`/`azurerm_windows_web_app_slot` - fix perpetual diff around incorrect default for `always_on` and ignore default values for `logs.0.application_logs` [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #16326

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by mbfrahry** [comment]
Failing tests were transient 
image

File: internal/services/appservice/windows_web_app_resource_test.go [hunk 1]
```diff
@@ -4198,3 +4213,33 @@ resource "azurerm_windows_web_app" "test" {
...
+%s
+
+resource "azurerm_windows_web_app" "test" {
+  name                = "acctestWA-%d"
+  location            = azurerm_resource_group.test.location
+  resource_group_name = azurerm_resource_group.test.name
+  service_plan_id     = azurerm_service_plan.test.id
+
+  site_config {
+    always_on           = true
```
Comment (sreallymatt) [inline internal/services/appservice/windows_web_app_resource_test.go:4232]: I believe this should be `false`?

```suggestion
    always_on           = false
```

**Review by sreallymatt — COMMENTED** [review]
@mbfrahry I left one minor comment inline

File: internal/services/appservice/windows_web_app_resource_test.go (hunk 1 above)
Comment (mbfrahry) [reply internal/services/appservice/windows_web_app_resource_test.go]: Taken care of. ty ty

**Review by sreallymatt — APPROVED** [review]
LGTM!
