### PR TITLE
`azurerm_static_site_custom_domain` - set `validation_token` in create instead of read

### LINKED ISSUE #14750: azurerm_static_site_custom_domain.validation_token dissapears after successfull validation yielding entire TF setup stuck on failed validation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0
```

### Affected Resource(s)

* `azurerm_static_site_custom_domain`
* `azurerm_dns_txt_record` - as a result

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.90.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "minimum_working_example_name" {
  description = "Resources name to be used with appropriate resource type prefixes"
  type        = string
  default     = "terraform-mwe"
}

variable "domain_name" {
  description = "The domain you will map to (like mywebsite.com)"
  type        = string
}

resource "azurerm_resource_group" "resource_group" {
  name     = "rg-${var.minimum_working_example_name}"
  location = "westeurope"
}

resource "azurerm_static_site" "website" {
  name                = "app-${var.minimum_working_example_name}"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = azurerm_resource_group.resource_group.location
  sku_size            = "Free"
  sku_tier            = "Free"
}

resource "azurerm_dns_zone" "dns" {
  name                = var.domain_name
  resource_group_name = azurerm_resource_group.resource_group.name
}

resource "azurerm_static_site_custom_domain" "txt-root" {
  static_site_id  = azurerm_static_site.website.id
  domain_name     = azurerm_dns_zone.dns.name
  validation_type = "dns-txt-token"
}

resource "azurerm_dns_txt_record" "txt-root" {
  name                = "@"
  zone_name           = azurerm_dns_zone.dns.name
  resource_group_name = azurerm_resource_group.resource_group.name
  ttl                 = 3600
  record {
    value = azurerm_static_site_custom_domain.txt-root.validation_token
  }
}
```

### Debug Output
[Debug output Github Gist link](https://gist.github.com/piotr-lasota/67f6f9639d808de3d55500101c04df30)

### Panic Output

Not applicable

### Expected Behaviour
I can use `plan` and `apply` **after** successful TXT validation by `azurerm_static_site_custom_domain`

### Actual Behaviour

As long as the TXT validation is still pending (on Azure Portal), everything works perfectly.

As soon as the validation is done:
```
$: terraform plan / terraform apply
azurerm_resource_group.resource_group: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe]
azurerm_static_site.website: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Web/staticSites/app-terraform-mwe]
azurerm_dns_zone.dns: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Network/dnszones/<redacted_domain>]
azurerm_static_site_custom_domain.txt-root: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Web/staticSites/app-terraform-mwe/customDomains/<redacted_domain>]
azurerm_dns_txt_record.txt-root: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Network/dnszones/<redacted_domain>/TXT/@]
╷
│ Error: expected length of record.0.value to be in the range (1 - 1024), got 
│ 
│   with azurerm_dns_txt_record.txt-root,
│   on main.tf line 38, in resource "azurerm_dns_txt_record" "txt-root":
│   38: resource "azurerm_dns_txt_record" "txt-root" {
│ 
╵

```

### Steps to Reproduce

1. `terraform apply` the provided configuration file
2. Wait for TXT validation to finalize (not awaited by TF as [per explicit warning in the docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/static_site_custom_domain)) via Azure Portal
   1. Go to Azure Portal
   2. Go to Static Web Apps
   3. Go to Custom Domains
   4. Wait for your TXT "Validating" spinner to get replaced by green checkbox + "Ready" (this can take up to 12h)
3. Try doing `terraform plan` or `terraform apply` (even without changing anything)

If you do a `terraform plan -refresh-only` then it is indicated that the `azurerm_static_site_custom_domain` no longer contains the `validation_token`.

```
$: terraform plan -refresh-only
azurerm_resource_group.resource_group: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe]
azurerm_static_site.website: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Web/staticSites/app-terraform-mwe]
azurerm_dns_zone.dns: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Network/dnszones/<redacted_domain>]
azurerm_static_site_custom_domain.txt-root: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Web/staticSites/app-terraform-mwe/customDomains/<redacted_domain>]
azurerm_dns_txt_record.txt-root: Refreshing state... [id=/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Network/dnszones/<redacted_domain>/TXT/@]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_dns_txt_record.txt-root has changed
  ~ resource "azurerm_dns_txt_record" "txt-root" {
        id                  = "/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Network/dnszones/<redacted_domain>/TXT/@"
        name                = "@"
      + tags                = {}
        # (4 unchanged attributes hidden)

        record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

  # azurerm_dns_zone.dns has changed
  ~ resource "azurerm_dns_zone" "dns" {
        id                        = "/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Network/dnszones/<redacted_domain>"
        name                      = "<redacted_domain>"
      ~ number_of_record_sets     = 2 -> 3
      + tags                      = {}
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # azurerm_resource_group.resource_group has changed
  ~ resource "azurerm_resource_group" "resource_group" {
        id       = "/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe"
        name     = "rg-terraform-mwe"
      + tags     = {}
        # (1 unchanged attribute hidden)
    }

  # azurerm_static_site.website has changed
  ~ resource "azurerm_static_site" "website" {
        id                  = "/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Web/staticSites/app-terraform-mwe"
        name                = "app-terraform-mwe"
      + tags                = {}
        # (6 unchanged attributes hidden)
    }

  # azurerm_static_site_custom_domain.txt-root has changed
  ~ resource "azurerm_static_site_custom_domain" "txt-root" {
        id               = "/subscriptions/<redacted_subscription_id>/resourceGroups/rg-terraform-mwe/providers/Microsoft.Web/staticSites/app-terraform-mwe/customDomains/<redacted_domain>"
      - validation_token = (sensitive value)
        # (3 unchanged attributes hidden)
    }

```

Proceeding with the refresh via `terraform apply -refresh-only` yields no improvement on the issue

### Important Factoids

None that I am aware of

### References
Searching for similiar issue yielded no results so I assume this one is first.

### PR DESCRIPTION
**Pull request by stephybun**
Closes #14750
Supersedes #22637

### CODE REVIEW

File: internal/services/web/static_site_custom_domain_resource.go [hunk 1]
```diff
@@ -161,6 +162,15 @@ func resourceStaticSiteCustomDomainCreateOrUpdate(d *pluginsdk.ResourceData, met
...
+	// we set `validation_token` into state here since it's removed from the API once it's been validated
+	// setting it in the read would overwrite the value with an empty string and cause a diff, since this
+	// is not a user specifiable field we don't need to be concerned with it at import time either
+	resp, err := client.GetStaticSiteCustomDomain(ctx, staticSiteId.ResourceGroup, id.StaticSiteName, id.CustomDomainName)
+	if err != nil {
+		return fmt.Errorf("retrieving %s: %+v", id, err)
+	}
+	d.Set("validation_token", pointer.From(resp.ValidationToken))
+
 	d.SetId(id.ID())
```
Comment (tombuildsstuff) [inline internal/services/web/static_site_custom_domain_resource.go:174]: does this need to be after the `SetId`?

**Review by tombuildsstuff — APPROVED** [review]
One question but otherwise 👍
