### PR TITLE
Crash Fix: `azurerm_marketplace_agreement`

### LINKED ISSUE #12891: azurerm_marketplace_agreement in conjunction with azurerm_linux_virtual_machine causes AzureRM to crash
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform Version 1.0.4
AzureRM Version 2.71.0

### Affected Resource(s)

azurerm_marketplace_agreement
azurerm_linux_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_marketplace_agreement" "barracuda" {
  publisher = "barracudanetworks"
  offer     = "waf"
  plan      = "hourly"
}
```
Using a marketplace image storage_image_reference in azurerm_linux_virtual_machine

### Panic Output
Error: Plugin did not respond
│ 
│   with azurerm_marketplace_agreement.app,
│   on TOSAgreement.tf line 1, in resource "azurerm_marketplace_agreement" "app":
│    1: resource "azurerm_marketplace_agreement" "app" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.

Stack trace from the terraform-provider-azurerm_v2.71.0_x5 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48e31ee]
goroutine 168 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute.resourceMarketplaceAgreementCreateUpdate(0xc001437780, 0x57e1000, 0xc000a48e00, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute/marketplace_agreement_resource.go:99 +0x12ce
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0008fbdc0, 0x6787328, 0xc001771300, 0xc001437780, 0x57e1000, 0xc000a48e00, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008fbdc0, 0x6787328, 0xc001771300, 0xc000160310, 0xc001a70e80, 0x57e1000, 0xc000a48e00, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000317d10, 0x6787328, 0xc001771300, 0xc001441b80, 0xc001771300, 0x5cc9180, 0xc000a45800)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001b3d7a0, 0x67873d0, 0xc001771300, 0xc000993f10, 0xc001b3d7a0, 0xc000a458c0, 0xc001cadba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5cc9180, 0xc001b3d7a0, 0x67873d0, 0xc000a458c0, 0xc00174f1a0, 0x0, 0x67873d0, 0xc000a458c0, 0xc000c90000, 0x1dc)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002388c0, 0x67d3ab8, 0xc00025a780, 0xc001686d80, 0xc000676ae0, 0x9d7cfa0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002388c0, 0x67d3ab8, 0xc00025a780, 0xc001686d80, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000137cd0, 0xc0002388c0, 0x67d3ab8, 0xc00025a780, 0xc001686d80)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd
Error: The terraform-provider-azurerm_v2.71.0_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None

### References

* #0000

### PR DESCRIPTION
**Pull request by mbfrahry**
Fixes #12891 with help from @catriona-m.

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

File: internal/services/compute/marketplace_agreement_resource.go [hunk 1]
```diff
@@ -69,18 +69,17 @@ func resourceMarketplaceAgreement() *pluginsdk.Resource {
...
+	subscriptionId := meta.(*clients.Client).Account.SubscriptionId
 	defer cancel()
 
-	offer := d.Get("offer").(string)
-	plan := d.Get("plan").(string)
-	publisher := d.Get("publisher").(string)
+	id := parse.NewPlanID(subscriptionId, d.Get("publisher").(string), d.Get("offer").(string), d.Get("plan").(string))
 
-	log.Printf("[DEBUG] Retrieving the Marketplace Terms for Publisher %q / Offer %q / Plan %q", publisher, offer, plan)
+	log.Printf("[DEBUG] retreiving %s", id)
```
Comment (stephybun) [inline internal/services/compute/marketplace_agreement_resource.go:77]:
```suggestion
	log.Printf("[DEBUG] retrieving %s", id)
```
