### PR TITLE
`azurerm_network_watcher_flow_log` destroy fails

### LINKED ISSUE #6913: Destroy azurerm_network_watcher_flow_log fails if traffic_analytics is not enabled
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.24
+ provider.azurerm v2.5.0

### Affected Resource(s)

* `azurerm_network_watcher_flow_log`

### Terraform Configuration Files

resource "azurerm_network_watcher_flow_log" "flow-log-main" {
  count                     = length(var.region)
  
  network_watcher_name      = azurerm_network_watcher.my-nw[count.index].name
  resource_group_name       = data.azurerm_resource_group.my-rg.name
  network_security_group_id = element(matchkeys(azurerm_network_security_group.my-nsg.*.id, azurerm_network_security_group.my-nsg.*.location, var.region), count.index)
  storage_account_id        = azurerm_storage_account.nsg-storage[count.index].id
  enabled                   = true
  version                   = 2

  retention_policy {
    enabled = true
    days    = 30

  }
}

### Debug Output

Error: Error disabling Flow Log Configuration for target "/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/test-rg/providers/Microsoft.Network/networkSecurityGroups/my-main-nsg" (Network Watcher "NetworkWatcher_eastasia" / Resource Group "test-rg"): network.WatchersClient#SetFlowLogConfiguration: Invalid input: autorest/validation: validation failed: parameter=parameters.FlowAnalyticsConfiguration.NetworkWatcherFlowAnalyticsConfiguration constraint=Null value=(*network.TrafficAnalyticsConfigurationProperties)(nil) details: value cannot be null; required parameter

### Expected Behavior

All NSG resources should be destroyed, including the NSG Flog Log configurations, even if Traffic Analytics is in a disabled state as configured by the Terraform code.

### Actual Behavior

When destroying deployed TF resources, TF is trying to disable NSG Flow logs and expecting “Traffic Analytics” section in enabled mode.  If "Traffic Analytics" is disabled, the destroy errors out and will not destroy the NSG resources.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Important Factoids

When the following code to enable Traffic Analytics for the NSG Flow Logs is included, the destroy command works without issue.

traffic_analytics {
    enabled               = true
    workspace_id          = element(azurerm_log_analytics_workspace.my-workspace.*.workspace_id, count.index)
    workspace_region      = element(azurerm_log_analytics_workspace.my-workspace.*.location, count.index)
    workspace_resource_id = element(azurerm_log_analytics_workspace.my-workspace.*.id, count.index)
    //  interval_in_minutes   = 60
  }
}

### PR DESCRIPTION
**Pull request by yupwei68**
Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/6913

=== RUN   TestAccAzureRMNetworkWatcherFlowLog_basic
--- PASS: TestAccAzureRMNetworkWatcherFlowLog_basic (160.70s)
=== RUN   TestAccAzureRMNetworkWatcherFlowLog_disabled
--- PASS: TestAccAzureRMNetworkWatcherFlowLog_disabled (143.00s)
=== RUN   TestAccAzureRMNetworkWatcherFlowLog_reenabled
--- PASS: TestAccAzureRMNetworkWatcherFlowLog_reenabled (207.17s)
=== RUN   TestAccAzureRMNetworkWatcherFlowLog_retentionPolicy
--- PASS: TestAccAzureRMNetworkWatcherFlowLog_retentionPolicy (201.46s)
=== RUN   TestAccAzureRMNetworkWatcherFlowLog_updateStorageAccount
--- PASS: TestAccAzureRMNetworkWatcherFlowLog_updateStorageAccount (228.93s)
=== RUN   TestAccAzureRMNetworkWatcherFlowLog_trafficAnalytics
--- PASS: TestAccAzureRMNetworkWatcherFlowLog_trafficAnalytics (359.23s)
=== RUN   TestAccAzureRMNetworkWatcherFlowLog_version
--- PASS: TestAccAzureRMNetworkWatcherFlowLog_version (198.51s)
PASS

### CODE REVIEW

File: azurerm/internal/services/network/tests/network_watcher_flow_log_resource_test.go [hunk 1]
```diff
@@ -12,7 +12,7 @@ import (
 	nw "github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network"
 )
 
-func testAccAzureRMNetworkWatcherFlowLog_basic(t *testing.T) {
+func TestAccAzureRMNetworkWatcherFlowLog_basic(t *testing.T) {
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/tests/network_watcher_flow_log_resource_test.go:15]: these are intentionally a combined test since you can only provision one Network Watcher at a time - could we revert the changes in this file?

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hi @yupwei68 

Thanks for this PR - taking a look through this is looking good, if we can revert the changes to the test function then this otherwise LGTM 👍 

Thanks!

File: azurerm/internal/services/network/tests/network_watcher_flow_log_resource_test.go (hunk 1 above)
Comment (yupwei68) [reply azurerm/internal/services/network/tests/network_watcher_flow_log_resource_test.go:15]: I found that the test suite is a little bit too long. Changing the test cases into public permit us to directly test the specific case or test only `network_watcher_flow_log_resource_test.go` cases. We could just set `parallel=1` to limit the provision number in testing. Would you still like to revert them as origin?

Comment (katbyte) [reply azurerm/internal/services/network/tests/network_watcher_flow_log_resource_test.go:15]: @yupwei68 - please revert this and use the shared test runner, and will cause CI/CD to fail. this will also prevent users from running into this issue not knowing that they cannot be run in parallel - if you personally want to just run that test you can comment the others out while working on it

**Comment by yupwei68** [comment]
@tombuildsstuff @katbyte Thanks for your comments. Please continue reviewing.

**Review by katbyte — APPROVED** [review]
Thanks @yupwei68 - LGTM 👍
