### PR TITLE
`azurerm_logic_app_action_http` - omit `queries` when not specified

### LINKED ISSUE #28429: azurerm_logic_app_action_http implicitly setting the queries parameter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.10.2

### AzureRM Provider Version

4.14.0

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_action_http

### Terraform Configuration Files

```hcl
resource "azurerm_logic_app_action_http" "some_name" {
  name         = "action_1"
  logic_app_id = azurerm_logic_app_workflow.workflow.id
  method       = "POST"
  uri          = "https://prod-23.southafricanorth.logic.azure.com:443/workflows/<secret>/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=<secret>"
  headers = {
    Content-Type = "application/json"
  }
  body = jsonencode({
    rule     = "logAnalyticsWorkspaceQuotaExceeded"
    tenantId = data.azurerm_subscription.current.tenant_id
  })
}
```

### Debug Output/Panic Output

```shell
N/a
```

### Expected Behaviour

The action should be created without the `queries` atttribute. 

### Actual Behaviour

The action is created with the `queries` attribute specified as empty object. This results in the in-uri query parameters being ignored and the the workflow failing to trigger with the remote api complaining about missing query parameters. If the action is modified from the Azure portal, removing the `queries` attribute, the action works perfectly.

The behavior when invoking the action with the `queries` attribute present: 
image

How it deploys:
image

How it should deploy to work properly:
image

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ziyeqf**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

empty map and `nil` have different definitions on the service side, omit it when it's not specified on configuration.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
❯ tftest logic TestAccLogicAppActionHttp_
=== RUN   TestAccLogicAppActionHttp_basic
=== PAUSE TestAccLogicAppActionHttp_basic
=== RUN   TestAccLogicAppActionHttp_complete
=== PAUSE TestAccLogicAppActionHttp_complete
=== RUN   TestAccLogicAppActionHttp_requiresImport
=== PAUSE TestAccLogicAppActionHttp_requiresImport
=== RUN   TestAccLogicAppActionHttp_headers
=== PAUSE TestAccLogicAppActionHttp_headers
=== RUN   TestAccLogicAppActionHttp_queries
=== PAUSE TestAccLogicAppActionHttp_queries
=== RUN   TestAccLogicAppActionHttp_dynamicFunction
=== PAUSE TestAccLogicAppActionHttp_dynamicFunction
=== RUN   TestAccLogicAppActionHttp_bodyDiff
=== PAUSE TestAccLogicAppActionHttp_bodyDiff
=== RUN   TestAccLogicAppActionHttp_disappears
=== PAUSE TestAccLogicAppActionHttp_disappears
=== RUN   TestAccLogicAppActionHttp_runAfter
=== PAUSE TestAccLogicAppActionHttp_runAfter
=== CONT  TestAccLogicAppActionHttp_basic
=== CONT  TestAccLogicAppActionHttp_dynamicFunction
=== CONT  TestAccLogicAppActionHttp_headers
=== CONT  TestAccLogicAppActionHttp_disappears
=== CONT  TestAccLogicAppActionHttp_queries
=== CONT  TestAccLogicAppActionHttp_bodyDiff
=== CONT  TestAccLogicAppActionHttp_runAfter
=== CONT  TestAccLogicAppActionHttp_complete
--- PASS: TestAccLogicAppActionHttp_headers (113.97s)
=== CONT  TestAccLogicAppActionHttp_requiresImport
--- PASS: TestAccLogicAppActionHttp_queries (114.24s)
--- PASS: TestAccLogicAppActionHttp_disappears (116.67s)
--- PASS: TestAccLogicAppActionHttp_basic (132.71s)
--- PASS: TestAccLogicAppActionHttp_dynamicFunction (149.04s)
--- PASS: TestAccLogicAppActionHttp_complete (159.73s)
--- PASS: TestAccLogicAppActionHttp_requiresImport (74.80s)
--- PASS: TestAccLogicAppActionHttp_bodyDiff (216.38s)
--- PASS: TestAccLogicAppActionHttp_runAfter (222.35s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/logic 222.463s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_logic_app_action_http` - omit `queries` when not specified [GH-28447]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #28429

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/logic/logic_app_action_http_resource.go [hunk 1]
```diff
@@ -303,6 +303,12 @@ func expandLogicAppActionHttpHeaders(headersRaw map[string]interface{}) (*map[st
 }
 
 func expandLogicAppActionHttpQueries(queriesRaw map[string]interface{}) (*map[string]string, error) {
+	// per the issue https://github.com/hashicorp/terraform-provider-azurerm/issues/28429
+	// empty map and nil are different on the service side.
+	if len(queriesRaw) == 0 {
+		return nil, nil
+	}
+
```
Comment (stephybun) [inline internal/services/logic/logic_app_action_http_resource.go:311]: @ziyeqf could you extend the following test case to add a second step where `queries` is removed and validate that this works for that case?
https://github.com/hashicorp/terraform-provider-azurerm/blob/f6886d7b22e8f805e561b6fc36214432194719a8/internal/services/logic/logic_app_action_http_resource_test.go#L82-L95

**Comment by ziyeqf** [comment]
```
❯ tftest logic TestAccLogicAppActionHttp_queries
=== RUN   TestAccLogicAppActionHttp_queries
=== PAUSE TestAccLogicAppActionHttp_queries
=== CONT  TestAccLogicAppActionHttp_queries
--- PASS: TestAccLogicAppActionHttp_queries (242.09s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/logic 242.172s
```

**Review by stephybun — APPROVED** [review]
Thanks @ziyeqf LGTM 👍
