### PR TITLE
`azurerm_application_insights_api_key` - parse API Key ID insensitively

### LINKED ISSUE #25522: v3.98.0: azurerm_application_insights_api_key fails with error due to casing in `resourcegroup`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

azurerm_application_insights_api_key

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights_api_key" "a" {
  name                    = "appik-${local.resource_infix}-a"
  application_insights_id = var.datasources.application_insights.id
  read_permissions        = ["aggregate", "api", "draft", "extendqueries", "search"]
  write_permissions       = ["annotations"]
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349": parsing segment "staticResourceGroups": parsing the ApiKey ID: the segment at position 2 didn't match

Expected a ApiKey ID that matched:

> /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Insights/components/componentValue/apiKeys/keyIdValue

However this value was provided:

> /subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349

The parsed Resource ID was missing a value for the segment at position 2
(which should be the literal value "resourceGroups").



  with module.chatbot.azurerm_application_insights_api_key.chatbot,
  on ../../../../../modules/gap-chatbot/main.tf line 31, in resource "azurerm_application_insights_api_key" "chatbot":
  31: resource "azurerm_application_insights_api_key" "chatbot" {

##[error]Terraform command 'plan' failed with exit code '1'.:  parsing "/subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349": parsing segment "staticResourceGroups": parsing the ApiKey ID: the segment at position 2 didn't match
##[error]
Error: parsing "/subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349": parsing segment "staticResourceGroups": parsing the ApiKey ID: the segment at position 2 didn't match

Expected a ApiKey ID that matched:

> /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Insights/components/componentValue/apiKeys/keyIdValue

However this value was provided:

> /subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349

The parsed Resource ID was missing a value for the segment at position 2
(which should be the literal value "resourceGroups").
```

### Expected Behaviour

resource is created

### Actual Behaviour

error occurs (see debug output)

### Steps to Reproduce

`terraform plan`

The issue occurs after updating the provider to v3.98.0 and running a plan.

The issue did not occur with provider version 3.97.1

I think it is probably an error in the Azure REST API,  which returns the value `resourcegroup` in lower casing. The validation expect its with an upper `g`(`resourceGroup`)

### Important Factoids

_No response_

### References

Maybe it is related to this change: https://github.com/hashicorp/terraform-provider-azurerm/pull/25376

### PR DESCRIPTION
**Pull request by stephybun**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

The API returns the resource ID segments in lower case, so we need to parse the ID insensitively in the read function.

## Change Log

* `azurerm_application_insights_api_key` - parse API Key resource ID insensitively [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25522

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/applicationinsights/application_insights_api_key_resource.go [hunk 1]
```diff
@@ -160,7 +160,7 @@ func resourceApplicationInsightsAPIKeyRead(d *pluginsdk.ResourceData, meta inter
 	ctx, cancel := timeouts.ForRead(meta.(*clients.Client).StopContext, d)
 	defer cancel()
 
-	id, err := apikeys.ParseApiKeyID(d.Id())
+	id, err := apikeys.ParseApiKeyIDInsensitively(d.Id())
```
Comment (tombuildsstuff) [inline internal/services/applicationinsights/application_insights_api_key_resource.go:163]: This means we'll have Resources using the incorrect Resource IDs in the state - can we revert this and instead add a state migration to fix the Resource ID?

File: internal/services/applicationinsights/application_insights_api_key_resource.go [hunk 2]
```diff
@@ -203,7 +203,7 @@ func resourceApplicationInsightsAPIKeyDelete(d *pluginsdk.ResourceData, meta int
 	ctx, cancel := timeouts.ForDelete(meta.(*clients.Client).StopContext, d)
 	defer cancel()
 
-	id, err := apikeys.ParseApiKeyID(d.Id())
+	id, err := apikeys.ParseApiKeyIDInsensitively(d.Id())
```
Comment (tombuildsstuff) [inline internal/services/applicationinsights/application_insights_api_key_resource.go:206]: (same here)

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
Rather than parsing these insensitively we should use a State Migration to update the ID if required - can we update that?

File: internal/services/applicationinsights/migration/api_key_v1_to_v2.go [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+		// new:
+		// 	/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/component1/apiKeys/key1
+		oldIdRaw := rawState["id"].(string)
+		oldId, err := apikeys.ParseApiKeyIDInsensitively(oldIdRaw)
+		if err != nil {
+			return rawState, err
+		}
+
+		id := apikeys.NewApiKeyID(oldId.SubscriptionId, oldId.ResourceGroupName, oldId.ComponentName, oldId.KeyId)
+		newId := id.ID()
```
Comment (tombuildsstuff) [inline internal/services/applicationinsights/migration/api_key_v1_to_v2.go:35]: FWIW this can become:

```suggestion
		newId := oldId.ID()
```

Since this'll update the Static Segments to be the expected casing

**Review by tombuildsstuff — APPROVED** [review]
We can reuse the ID that's been parsed insensitively, but otherwise LGTM 👍
