### PR TITLE
`azurerm_mssql_managed_instance` fix `identity` bug and updating `subnet_id`

### LINKED ISSUE #19802: Support for both SystemAssigned and UserAssigned managed identities in azurerm_mssql_managed_instance
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The azurerm_mssql_managed_instance [(azurerm_mssql_managed_instance)](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_managed_instance#identity) identity.type  accepts either SystemAssigned OR  UserAssigned values but NOT both at the same time.
I would expect it to accept both managed identity types in a form of identity.type = SystemAssigned, UserAssigned so that both of them are created simultaneously for a particular instance of Azure SQL Server.
I want to be able to create a SQL Server instance with the following managed identities:

0..1 System Assigned Managed Identity
0..n User Assigned Managed Identities

This is the same as [Support for both SystemAssigned and UserAssigned managed identities in azurerm_mssql_server](https://github.com/hashicorp/terraform-provider-azurerm/issues/17199), but for SQL MI

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance

### Potential Terraform Configuration

```hcl
identity {
  type = "SystemAssigned,UserAssigned"
  identity_ids = ["id1", "id2"]
}

primary_user_assigned_identity_id = "id1"
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/17199

### LINKED ISSUE #21214: azurerm_mssql_managed_instance - Unable to configure [System assigned service principal] option via terraform resource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When provisioning a mssql_managed_instance the identity block has no provision for enabling the system assigned service principal only the System assigned managed identity is configured when declaring the below Identity Block.

`  
identity {
    type = "SystemAssigned"
  }`

image

A system assigned service principal enables Managed Instance users to authenticate using Kerberos protocol. Once enabled, all necessary permissions can be granted via Azure role-based-access-control. The lifecycle of this service principal is tied to the lifecycle of this resource. [Learn more about Windows Authentication for Azure AD Users](https://go.microsoft.com/fwlink/?linkid=2185215).

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance

### Potential Terraform Configuration

```hcl
` 
Managedidentity {
    type = "SystemAssigned"
  }

ServicePrincipal{
    type = "SystemAssigned"
  }
`
```

### References

https://github.com/MicrosoftDocs/sql-docs/blob/live/azure-sql/managed-instance/winauth-azuread-kerberos-managed-instance.md

### LINKED ISSUE #28320: `azurerm_mssql_managed_instance` subnet ID is nil when updating resource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.10.2

### AzureRM Provider Version

3.108.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.108.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_mssql_managed_instance" "example" {
  name                = "managedsqlinstance"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  license_type       = "BasePrice"
  sku_name           = "GP_Gen5"
  storage_size_in_gb = 32
  subnet_id          = azurerm_subnet.example.id
  vcores             = 4

  administrator_login          = "mradministrator"
  administrator_login_password = "foobar"

  depends_on = [
    azurerm_subnet_network_security_group_association.example,
    azurerm_subnet_route_table_association.example,
  ]
}

resource "azurerm_resource_group" "example" {
  name     = "wyatt-test"
  location = "eastus"
}

resource "azurerm_network_security_group" "example" {
  name                = "wyatt-test"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}


resource "azurerm_network_security_rule" "allow_management_inbound" {
  name                        = "allow_management_inbound"
  priority                    = 106
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["9000", "9003", "1438", "1440", "1452"]
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.example.name
  network_security_group_name = azurerm_network_security_group.example.name
}

resource "azurerm_network_security_rule" "allow_misubnet_inbound" {
  name                        = "allow_misubnet_inbound"
  priority                    = 200
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "*"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "10.0.0.0/24"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.example.name
  network_security_group_name = azurerm_network_security_group.example.name
}

resource "azurerm_network_security_rule" "allow_health_probe_inbound" {
  name                        = "allow_health_probe_inbound"
  priority                    = 300
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "*"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "AzureLoadBalancer"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.example.name
  network_security_group_name = azurerm_network_security_group.example.name
}

resource "azurerm_network_security_rule" "allow_tds_inbound" {
  name                        = "allow_tds_inbound"
  priority                    = 1000
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "1433"
  source_address_prefix       = "VirtualNetwork"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.example.name
  network_security_group_name = azurerm_network_security_group.example.name
}

resource "azurerm_network_security_rule" "deny_all_inbound" {
  name                        = "deny_all_inbound"
  priority                    = 4096
  direction                   = "Inbound"
  access                      = "Deny"
  protocol                    = "*"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.example.name
  network_security_group_name = azurerm_network_security_group.example.name
}

resource "azurerm_network_security_rule" "allow_management_outbound" {
  name                        = "allow_management_outbound"
  priority                    = 106
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["80", "443", "12000"]
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.example.name
  network_security_group_name = azurerm_network_security_group.example.name
}

resource "azurerm_network_security_rule" "allow_misubnet_outbound" {
  name                        = "allow_misubnet_outbound"
  priority                    = 200
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "*"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "10.0.0.0/24"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.example.name
  network_security_group_name = azurerm_network_security_group.example.name
}

resource "azurerm_network_security_rule" "deny_all_outbound" {
  name                        = "deny_all_outbound"
  priority                    = 4096
  direction                   = "Outbound"
  access                      = "Deny"
  protocol                    = "*"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.example.name
  network_security_group_name = azurerm_network_security_group.example.name
}

resource "azurerm_virtual_network" "example" {
  name                = "vnet-mi"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
}

resource "azurerm_subnet" "example" {
  name                 = "subnet-mi"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.0.0/24"]

  delegation {
    name = "managedinstancedelegation"

    service_delegation {
      name    = "Microsoft.Sql/managedInstances"
      actions = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action", "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"]
    }
  }
}

# output "test" {
#   value = {
#     vnet = azurerm_virtual_network.example
#     subnet = azurerm_subnet.example
#   }
# }

resource "azurerm_subnet_network_security_group_association" "example" {
  subnet_id                 = azurerm_subnet.example.id
  network_security_group_id = azurerm_network_security_group.example.id
}

resource "azurerm_route_table" "example" {
  name                          = "routetable-mi"
  location                      = azurerm_resource_group.example.location
  resource_group_name           = azurerm_resource_group.example.name
  disable_bgp_route_propagation = false
  depends_on = [
    azurerm_subnet.example,
  ]
}

resource "azurerm_subnet_route_table_association" "example" {
  subnet_id      = azurerm_subnet.example.id
  route_table_id = azurerm_route_table.example.id
}
```

### Debug Output/Panic Output

```shell
│ Error: updating Managed Instance: (Name "managedsqlinstance" / Resource Group "wyatt-test"): sql.ManagedInstancesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidSubnetResourceId" Message="Subnet resource ID '' is invalid. Please provide a correct resource Id for the target subnet."
```

### Expected Behaviour

Apply complete!

### Actual Behaviour

❯ tfp
azurerm_resource_group.example: Refreshing state...
[...]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_mssql_managed_instance.example will be updated in-place
  ~ resource "azurerm_mssql_managed_instance" "example" {
      ~ administrator_login_password   = (sensitive value)
        id                             = "/subscriptions/XXXXXXXXXXXXX/resourceGroups/wyatt-test/providers/Microsoft.Sql/managedInstances/managedsqlinstance"
        name                           = "managedsqlinstance"
        tags                           = {}
        # (19 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Saved the plan to: /tmp/tfplan.zip

To perform exactly these actions, run the following command to apply:
    terraform apply "/tmp/tfplan.zip"
❯ tfa
azurerm_mssql_managed_instance.example: Modifying... [id=/subscriptions/XXXXXXXXXXX/resourceGroups/wyatt-test/providers/Microsoft.Sql/managedInstances/managedsqlinstance]
╷
│ Error: updating Managed Instance: (Name "managedsqlinstance" / Resource Group "wyatt-test"): sql.ManagedInstancesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidSubnetResourceId" Message="Subnet resource ID '' is invalid. Please provide a correct resource Id for the target subnet."
│ 
│   with azurerm_mssql_managed_instance.example,
│   on main.tf line 14, in resource "azurerm_mssql_managed_instance" "example":
│   14: resource "azurerm_mssql_managed_instance" "example" {
│ 
│ updating Managed Instance: (Name "managedsqlinstance" / Resource Group "wyatt-test"): sql.ManagedInstancesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidSubnetResourceId" Message="Subnet resource ID '' is invalid. Please provide a correct
│ resource Id for the target subnet."
╵

### Steps to Reproduce

[change an attribute] then plan and apply

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by wyattfry**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Fixes a bug that introduced a discrepancy between Azure's API behavior and the provider's behavior, namely, Azure allows MSSQL managed instances to have either a System Assigned or User Assigned identity, or both. The provider only allowed for one or the other.

Also, it seems that `subnet_id` may have been immutable but is now mutable, and thus must be included in the Update command. This PR adds `subnet_id` to the command.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_mssql_managed_instance` - fix `identity` and `subnet_id` bugs [GH-28319]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #28320
Fixes #21214
Fixes #19802 
Fixes https://hashicorp.atlassian.net/browse/IPL-6520

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go [hunk 1]
```diff
@@ -181,7 +180,7 @@ func (r MsSqlManagedInstanceResource) Arguments() map[string]*pluginsdk.Schema {
 			ValidateFunc: validate.ManagedInstanceID,
 		},
 
-		"identity": commonschema.SystemOrUserAssignedIdentityOptional(),
+		"identity": commonschema.SystemAssignedUserAssignedIdentityOptional(),
```
Comment (wyattfry) [inline internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go:183]: This the crux of the identity bug fix, `SystemOrUserAssignedIdentityOptional` is XOR, exclusive or. `SystemAssignedUserAssignedIdentityOption` is true OR, i.e. one, the other, or both.

**Comment by wyattfry** [comment]
1 failing acceptance test, due to timeout, rerunning that one test
image
```
        API Response:
        ----[start]----
        {"name":"31930286-4dff-48ff-a098-15853e0712d0","status":"Failed","startTime":"2024-12-20T17:23:44.937Z","error":{"code":"ConflictingServerOperation","message":"Server
        'acctestsqlserver241220165729791029' is busy with another operation. Please
        try your operation later."}}
        -----[end]-----
--- FAIL: TestAccMsSqlManagedInstance_identity (4482.45s)
```

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go [hunk 2]
```diff
@@ -418,6 +417,9 @@ func (r MsSqlManagedInstanceResource) Update() sdk.ResourceFunc {
 					RequestedBackupStorageRedundancy: pointer.To(storageAccTypeToBackupStorageRedundancy(state.StorageAccountType)),
 					VCores:                           pointer.To(state.VCores),
 					ZoneRedundant:                    pointer.To(state.ZoneRedundantEnabled),
+					AdministratorLogin:               pointer.To(state.AdministratorLogin),
+					AdministratorLoginPassword:       pointer.To(state.AdministratorLoginPassword),
+					SubnetId:                         pointer.To(state.SubnetId),
```
Comment (wyattfry) [inline internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go:422]: because subnet_id has since become mutable (idk about the admin creds), it must now be included in resource updates.

**Comment by wyattfry** [comment]
> 1 failing acceptance test, due to timeout, rerunning that one test image
> 
> ```
>         API Response:
>         ----[start]----
>         {"name":"31930286-4dff-48ff-a098-15853e0712d0","status":"Failed","startTime":"2024-12-20T17:23:44.937Z","error":{"code":"ConflictingServerOperation","message":"Server
>         'acctestsqlserver241220165729791029' is busy with another operation. Please
>         try your operation later."}}
>         -----[end]-----
> --- FAIL: TestAccMsSqlManagedInstance_identity (4482.45s)
> ```

Test succeeded on the first retry
image

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go [hunk 3]
```diff
@@ -140,7 +140,6 @@ func (r MsSqlManagedInstanceResource) Arguments() map[string]*pluginsdk.Schema {
 		"subnet_id": {
 			Type:         schema.TypeString,
 			Required:     true,
-			ForceNew:     true,
```
[the remark this answers is not in the document]
Comment (catriona-m) [reply internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go:143]: could we update the docs to reflect this too?

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go (hunk 1 above)
Comment (catriona-m) [reply internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go:183]: the docs may need updating for this too

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource_test.go [hunk 4]
```diff
@@ -1686,3 +1782,75 @@ resource "azurerm_mssql_managed_instance" "test" {
...
+       deleted until this can be properly investigated
+      */
+      prevent_deletion_if_contains_resources = false
+    }
+  }
+}
+
+
+resource "azurerm_subnet" "test2" {
+  name                 = "subnet2-%[2]d"
```
Comment (catriona-m) [inline internal/services/mssqlmanagedinstance/mssql_managed_instance_resource_test.go:1804]: could we prefix this resource name with `acctest`?

```suggestion
  name                 = "acctestsubnet2-%[2]d"
```

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks @wyattfry - I left a couple of minor comments inline but otherwise this is looking pretty good 😄

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (wyattfry) [reply internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go:143]: certainly

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go (hunk 1 above)
Comment (wyattfry) [reply internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go:183]: roger

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource_test.go (hunk 4 above)
Comment (wyattfry) [reply internal/services/mssqlmanagedinstance/mssql_managed_instance_resource_test.go]: certainly

**Review by catriona-m — APPROVED** [review]
Thanks @wyattfry LGTM ✨
