### PR TITLE
`azurerm_storage_account` - Ensure `cross_tenant_replication_enabled` has a default value when users upgrade from v2 provider

### LINKED ISSUE #17302: `allowCrossTenantReplication` is not updated on existing `azurerm_storage_account`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "aks_storage" {
  name                             = var.name
  resource_group_name              = var.resource_group_name
  location                         = var.location
  account_tier                     = "Premium"
  account_kind                     = "FileStorage"
  account_replication_type         = "LRS"
  min_tls_version                  = "TLS1_2"
  allow_nested_items_to_be_public  = false
  shared_access_key_enabled        = true
  **cross_tenant_replication_enabled = false**
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

 `allowCrossTenantReplication` is set to false

### Actual Behaviour

 `allowCrossTenantReplication` is not set (true by default)

### Steps to Reproduce

_No response_

### Important Factoids

In the state file it is set to `null`:

```hcl
"cross_tenant_replication_enabled": null
```

### References

_No response_

### PR DESCRIPTION
**Pull request by magodo**
This is mainly to allow users who manage `azurerm_storage_account` created in v2 provider to be able to continue manage it using v3 provider seamlessly.

The detail can be found at: https://github.com/hashicorp/terraform-provider-azurerm/issues/17302#issuecomment-1535905682

Fix #17302

### CODE REVIEW

File: internal/services/storage/storage_account_resource.go [hunk 1]
```diff
@@ -1503,7 +1503,11 @@ func resourceStorageAccountUpdate(d *pluginsdk.ResourceData, meta interface{}) e
 		opts.AccountPropertiesUpdateParameters.DefaultToOAuthAuthentication = &defaultToOAuthAuthentication
 	}
 
-	if d.HasChange("cross_tenant_replication_enabled") {
+	// During the update from v2 to v3 of the provider, users are able to set this newly introduced property to be `false` (was absent in v2 provider).
+	// The storage service differentiate this property being `false` or absent, while the d.HasChange regards both (`false` and `null`) are the same.
+	// This makes setting the property to be `false` ends up being absent at the remote end.
+	// Hence, we need to explicitly check for the null case here to make it update the property to `false` if user has set so (instead of skipping the if branch below).
+	if d.HasChange("cross_tenant_replication_enabled") || d.GetRawState().GetAttr("cross_tenant_replication_enabled").IsNull() {
```
Comment (tombuildsstuff) [inline internal/services/storage/storage_account_resource.go:1510]: Rather than doing this, it'd be better to add a state migration to ensure that this value always has a default value if it's not explicitly set?

FWIW we're intentionally not using `d.GetRawState()` directly, in favour of a wrapper in `pluginsdk.IsExplicitlyNullInConfig` - so that we can ensure this is behaviourally consistent for the Framework migration (for the Framework shim, we'll be exposing an interface similar [to this](https://github.com/hashicorp/terraform-provider-azurerm/blob/05b4df660ea519e0fd4e264e25ba20a2df2088f5/internal/sdk/resource_data.go#L3-L39) [which'll probably get an `IsExplicitlyNull` method and serving a Plugin SDK or Framework implementation depending on which we're serving under - so we're intentionally not exposing `GetRawState` directly to not need to transform these objects)

Comment (magodo) [reply internal/services/storage/storage_account_resource.go:1510]: @tombuildsstuff Thank you for the hint! In my case, it was `d.GetRawState()`, shall I create a similar warpper like `pluginsdk.IsNullInState`?

I've been skimmed on the implementation of `pluginsdk.IsExplicitlyNullInConfig`, which seems odd in case the field is not defined in the config it returns `true`, which makes a non-exist field (in terms of schema) also returns `true` in this case. Instead, shall we do something like:

```go
func IsExplicitlyNullInConfig(d *ResourceData, configFieldName string) bool {
	var isNull bool

	v, ok := d.GetRawConfig().AsValueMap()[configFieldName]

       if !ok {
         return false // As this is not defined in the schema
       }

	if v.IsNull() {
		isNull = true
	}

	return isNull
}
```

This then aligns better to the fw as the methods in fw only apply to properties defined in the schema.

Comment (tombuildsstuff) [reply internal/services/storage/storage_account_resource.go:1510]: TBH if we add a state migration we remove the need for the call to `d.GetRawState()` entirely, since it'll then have a default value assigned - which it sounds like was missing from the 3.0 upgrade - so could we update this to use a state migration instead?

---

For the method above, that change makes sense to me, it's only used in a handful of places anyway if memory serves.

FWIW @mbfrahry is currently working on schema/model validation for Typed Data Sources/Resources which'll allow catching bugs where a field is provided to Get/Set but doesn't exist at unit test time, rather than acctest time - but that doesn't help for untyped resources (although we'll be migrating towards Typed Resources as time allows).

Comment (magodo) [reply internal/services/storage/storage_account_resource.go]: @tombuildsstuff You are right, a state migration suffices here. I've made a new commit, please take another look.

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @magodo, thanks for getting that state migration written but it needs some tweaking. We want to keep state migrations in their own files so `V0toV1` would have it's own file and `V1toV2` would be in it's own file. On top of that, each file would have a snapshot of the schema (with only the Type and Required/Optional/Computed tags) at the time of the upgrade.

I'm not sure why storage account isn't doing that but we can start doing it now by putting this into a file called `account_resource_v3_to_v4.go) with the current schema.

You can read more information [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/tf/pluginsdk/state_upgrades.go#L15) about what the schema looks like.

**Comment by magodo** [comment]
@mbfrahry Thank you for the review! After another look at this change, as it aims to solve the issue that only happens during v2 to v3 provder upgrade, which won't trigger the schema upgrade from v3 to v4 as v3 is introduced since v3. So the right place to add this change is in v2 to v3 migration, where v2 is the schema version used in v2 provider version, and v3 is used until the latest version.

The `cross_tenant_replication_enabled` is introduced since v3.5.0, btw, which by default is `true` if request doesn't explicitly specified it, per https://github.com/hashicorp/terraform-provider-azurerm/issues/17302#issuecomment-1535716062.

**Review by mbfrahry — CHANGES_REQUESTED** [review]
I see what you are saying @magodo but someone upgrading from v2 to v3 of the provider won't hit this migration until the release this migration goes out in. 

With that said, it won't matter for anyone where this migration goes but for our own best practices, we should make it a separate migration.

**Comment by magodo** [comment]
@mbfrahry Right, I've now switch back to creating the new schema version and created a separate file to hold the v3 to v4 migration. Please take another look! Thank you!

**Review by mbfrahry — APPROVED** [review]
LGTM!

**Comment by mbfrahry** [comment]
Thanks for making those changes @magodo
