### PR TITLE
linux_virtual_machine_resource: Support for license_type None.

### LINKED ISSUE #28785: azurerm_linux_virtual_machine: license_type "None" currently not supported
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.4

### AzureRM Provider Version

4.7.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "instance" {
  name                         = "testvm01"

  [...]

  license_type                 = "None"
}
```

### Debug Output/Panic Output

```shell
Error: expected license_type to be one of ["RHEL_BYOS" "RHEL_BASE" "RHEL_EUS" "RHEL_SAPAPPS" "RHEL_SAPHA" "RHEL_BASESAPAPPS" "RHEL_BASESAPHA" "SLES_BYOS" "SLES_SAP" "SLES_HPC" "UBUNTU_PRO"], got None
```

### Expected Behaviour

Setting `license_type` to `None` should be possible. This is the official way to change back from e. g. `RHEL_BYOS` to the default setting.

Additionally it should be considered, that there should be no diff between `None` and empty setting and vice-versa (same as already implemented in `azurerm_windows_virtual_machine`.

### Actual Behaviour

Setting `license_type` to `None` is not possible and causes this error message:
`Error: expected license_type to be one of ["RHEL_BYOS" "RHEL_BASE" "RHEL_EUS" "RHEL_SAPAPPS" "RHEL_SAPHA" "RHEL_BASESAPAPPS" "RHEL_BASESAPHA" "SLES_BYOS" "SLES_SAP" "SLES_HPC" "UBUNTU_PRO"], got None`

Even setting this manually via Azure portal and then removing the setting from Terraform does not work as it leads in an infinite diff:
```hcl
  ~ resource "azurerm_linux_virtual_machine" "instance" {
        id                                                     = "xxxxxx"
      - license_type                                           = "None" -> null
        name                                                   = "testvm01"
```

### Steps to Reproduce

1. Set `license_type` to `RHEL_BYOS` (or something else)
2. `terraform apply`
3. Set `license_type` to `None` 
4. `terraform apply`

### Important Factoids

_No response_

### References

https://learn.microsoft.com/en-us/azure/virtual-machines/linux/azure-hybrid-benefit-linux?tabs=ahbRhelPayg%2CahbNewPortal%2CahbExistingPortal%2Clicenseazcli%2CrhelAzcliByosConv%2Crhelazclipaygconv%2Crhelpaygconversion%2Crhelcompliance#convert-byos-to-payg

### PR DESCRIPTION
**Pull request by NilsBusche**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

According to microsoft documentation it should be possible to set `license_type` to `None` for linux VMs.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

We work as a service provider so we have only very limited and specific access to Azure resources, which prevents running the acceptance tests as they would create resources we do not have the necessary access rights for.

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_linux_virtual_machine` - support for setting `license_type` to `None` [GH-28785]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #28785 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by ms-zhenhua — CHANGES_REQUESTED** [review]
Hi @NilsBusche,

Thank you for the PR. 
Since the provider no longer exposes `None` to users, could you please follow [this doc ](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/schema-design-considerations.md#the-none-value-or-similar)to update your PR?

File: internal/services/compute/linux_virtual_machine_resource.go [hunk 1]
```diff
@@ -559,7 +559,7 @@ func resourceLinuxVirtualMachineCreate(d *pluginsdk.ResourceData, meta interface
 		}
 	}
 
-	if v, ok := d.GetOk("license_type"); ok {
+	if v, ok := d.GetOk("license_type"); ok && v.(string) != "" {
```
Comment (ms-zhenhua) [inline internal/services/compute/linux_virtual_machine_resource.go:562]: no need to change this code as `license_type` is an enum type and the value won't be empty
```suggestion
	if v, ok := d.GetOk("license_type"); ok {
```

File: internal/services/compute/linux_virtual_machine_resource.go [hunk 2]
```diff
@@ -1123,9 +1123,11 @@ func resourceLinuxVirtualMachineUpdate(d *pluginsdk.ResourceData, meta interface
 	if d.HasChange("license_type") {
 		shouldUpdate = true
 
-		if v, ok := d.GetOk("license_type"); ok {
-			update.Properties.LicenseType = pointer.To(v.(string))
+		licenseType := "None"
+		if v, ok := d.GetOk("license_type"); ok && v.(string) != "" {
+			licenseType = v.(string)
 		}
```
Comment (ms-zhenhua) [inline internal/services/compute/linux_virtual_machine_resource.go:1129]: No need to change the `if` block as the value of `license_type` won't be empty
```suggestion
		if v, ok := d.GetOk("license_type"); ok {
			update.Properties.LicenseType = pointer.To(v.(string))
		}
```

**Review by ms-zhenhua — CHANGES_REQUESTED** [review]

**Review by ms-zhenhua — APPROVED** [review]
@NilsBusche,  Thanks for your updates. LGTM~

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks for adding this @NilsBusche. In order to fully support the `None` option, we would also need to add it as an option in the validation for `license_type` and add this to the docs also. Once that is added, we can take another look at this. Thanks!

**Comment by catriona-m** [comment]
Thanks @NilsBusche - I think this should be fine, but can we add a test to make sure this will work as expected?

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks for adding the test @NilsBusche. I think it would also be good to test the update in the test but adding additional steps to update to a different license_type and then back to the default config again. Thanks!

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks for fixing this up @NilsBusche - I left a couple of minor comments on the tests but once those are addressed this should be good. Thanks!

**Review by catriona-m — APPROVED** [review]
Thanks for fixing up the tests @NilsBusche - LGTM!
