### PR TITLE
[BUG:] `azurerm_linux_virtual_machine`/`azurerm_windows_virtual_machine` - `vm_agent_platform_updates_enabled` field is now `read-only` due to API breaking change

### LINKED ISSUE #27484: `azurerm_linux_virtual_machine`not setting `vm_agent_platform_updates_enabled` correctly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.6

### AzureRM Provider Version

4.3.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "management" {
  name                              = "dev-management-vm"
  resource_group_name               = var.resource_group.name
  location                          = var.resource_group.location
  size                              = var.vm_sku
  admin_username                    = "admin"
  disable_password_authentication   = true
  patch_assessment_mode             = "AutomaticByPlatform"
  patch_mode                        = "AutomaticByPlatform"
  provision_vm_agent                = true
  allow_extension_operations        = true
  vm_agent_platform_updates_enabled = true
  encryption_at_host_enabled        = true
  network_interface_ids = [
    azurerm_network_interface.management.id,
  ]

  admin_ssh_key {
    username   = "pacman"
    public_key = var.public_key_openssh
  }

  identity {
    type = "SystemAssigned"
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = var.vm_disk_size
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }
}
```

### Debug Output/Panic Output

```shell
from terraform plan:

resource "azurerm_linux_virtual_machine" "management" {
        id                                                     = "/subscriptions/1234/resourceGroups/dev-rg/providers/Microsoft.Compute/virtualMachines/dev-management-vm"
        name                                                   = "dev-management-vm"
      ~ vm_agent_platform_updates_enabled                      = false -> true
}

from Azure Api:
GET https://management.azure.com/subscriptions/1234/resourceGroups/dev-rg/providers/Microsoft.Compute/virtualMachines/dev-management-vm?api-version=2023-03-01


"provisionVMAgent": true,
  "patchSettings": {
     "patchMode": "AutomaticByPlatform",
     "automaticByPlatformSettings": {
        "bypassPlatformSafetyChecksOnUserSchedule": false
     },
     "assessmentMode": "AutomaticByPlatform"
  },
"enableVMAgentPlatformUpdates": true
```

### Expected Behaviour

`vm_agent_platform_updates_enabled` should be `true` as it is already set true on the resource

### Actual Behaviour

`vm_agent_platform_updates_enabled` is seen by Terraform as `false` but it is set true on the resource

### Steps to Reproduce

terraform plan

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by WodansSon**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR addresses a breaking change to the VM API, see `Azure Rest API Specs` Issue [#31207](https://github.com/Azure/azure-rest-api-specs/issues/31307) and GitHub Issue [#27484](https://github.com/hashicorp/terraform-provider-azurerm/issues/27484#issuecomment-2442886963), thank you to @ms-zhenhua for the context around this issue.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [X] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

Massive improvement to test pass rate:

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_linux_virtual_machine` - `vm_agent_platform_updates_enabled` field is now read-only due to API breaking change [GH-00000]
* `azurerm_windows_virtual_machine` - `vm_agent_platform_updates_enabled` field is now read-only due to API breaking change [GH-00000]

This is a (please select all that apply):

- [X] Bug Fix
- [ ] New Feature (e.g., adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27484

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/compute/windows_virtual_machine_resource.go [hunk 1]
```diff
@@ -433,8 +428,22 @@ func resourceWindowsVirtualMachine() *pluginsdk.Resource {
...
 		},
 	}
+
+	if !features.FivePointOh() {
+		resource.Schema["vm_agent_platform_updates_enabled"] = &pluginsdk.Schema{
+			Type:     pluginsdk.TypeBool,
+			Optional: true,
+			Computed: true,
+		}
+	}
```
Comment (jackofallops) [inline internal/services/compute/windows_virtual_machine_resource.go:444]: Can we add a deprecation message here to help users that bump into this during a plan/apply understand the problem?
```suggestion
	if !features.FivePointOh() {
		resource.Schema["vm_agent_platform_updates_enabled"] = &pluginsdk.Schema{
			Type:       pluginsdk.TypeBool,
			Optional:   true,
			Computed:   true,
			Deprecated: "this property has been deprecated due to a breaking change in the API/Service making it read-only",
		}
	}
```

File: internal/services/compute/linux_virtual_machine_resource.go [hunk 2]
```diff
@@ -417,8 +412,22 @@ func resourceLinuxVirtualMachine() *pluginsdk.Resource {
...
 		},
 	}
+
+	if !features.FivePointOh() {
+		resource.Schema["vm_agent_platform_updates_enabled"] = &pluginsdk.Schema{
+			Type:     pluginsdk.TypeBool,
+			Optional: true,
+			Computed: true,
+		}
+	}
```
Comment (jackofallops) [inline internal/services/compute/linux_virtual_machine_resource.go:428]: Can we add a deprecation message here to help users that bump into this during a plan/apply understand the problem?
```suggestion
	if !features.FivePointOh() {
		resource.Schema["vm_agent_platform_updates_enabled"] = &pluginsdk.Schema{
			Type:       pluginsdk.TypeBool,
			Optional:   true,
			Computed:   true,
			Deprecated: "this property has been deprecated due to a breaking change in the API/Service making it read-only",
		}
	}
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Thanks @WodansSon - Couple of minor changes to help users that bump into the problem during a terraform operation and may not have seen the change notes / updated docs.

File: internal/services/compute/windows_virtual_machine_resource.go (hunk 1 above)
Comment (WodansSon) [reply internal/services/compute/windows_virtual_machine_resource.go:444]: Fixed.

File: internal/services/compute/linux_virtual_machine_resource.go (hunk 2 above)
Comment (WodansSon) [reply internal/services/compute/linux_virtual_machine_resource.go:428]: Fixed.

**Review by jackofallops — APPROVED** [review]
Thanks @WodansSon - This LGTM now.
