### PR TITLE
[Bug:] `azurerm_orchestrated_virtual_machine_scale_set` - fix `nil` pointer dereferences and unsafe type assertions

### LINKED ISSUE #29748: Crash when using empty os_profile block in azurerm_orchestrated_virtual_machine_scale_set resource
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.12.1

### AzureRM Provider Version

4.30.0

### Affected Resource(s)/Data Source(s)

azurerm_orchestrated_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
resource "azurerm_orchestrated_virtual_machine_scale_set" "example" {
  name                = "ad-test"
  location            = "eastus"
  resource_group_name = "ad-aks-test"

  platform_fault_domain_count = 1
  zones                       = ["1"]

  # Adding the empty os_profile block causes a crash
  os_profile {
  }
}
```

### Debug Output/Panic Output

```shell
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_orchestrated_virtual_machine_scale_set.example: Creating...
╷
│ Warning: Argument is deprecated
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on terraform.tf line 9, in provider "azurerm":
│    9:       graceful_shutdown              = false
│
│ 'graceful_shutdown' has been deprecated and will be removed from v5.0 of the AzureRM provider.
╵
╷
│ Warning: Attribute Deprecated
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on terraform.tf line 9, in provider "azurerm":
│    9:       graceful_shutdown              = false
│
│ 'graceful_shutdown' has been deprecated and will be removed from v5.0 of the AzureRM provider.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_orchestrated_virtual_machine_scale_set.example,
│   on main.tf line 339, in resource "azurerm_orchestrated_virtual_machine_scale_set" "example":
│  339: resource "azurerm_orchestrated_virtual_machine_scale_set" "example" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v4.30.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 109 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/compute.resourceOrchestratedVirtualMachineScaleSetCreate(0x11b86820, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go:521 +0x440d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1092d880, {0x801e4ec, 0x11b84420}, 0x11b86820, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:826 +0x164
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1092d880, {0x801e4ec, 0x11b84420}, 0x10b857a0, 0x11b86730, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:969 +0xad0
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 109 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/compute.resourceOrchestratedVirtualMachineScaleSetCreate(0x11b86820, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go:521 +0x440d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1092d880, {0x801e4ec, 0x11b84420}, 0x11b86820, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:826 +0x164
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1092d880, {0x801e4ec, 0x11b84420}, 0x10b857a0, 0x11b86730, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:969 +0xad0

goroutine 109 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/compute.resourceOrchestratedVirtualMachineScaleSetCreate(0x11b86820, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go:521 +0x440d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1092d880, {0x801e4ec, 0x11b84420}, 0x11b86820, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:826 +0x164
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1092d880, {0x801e4ec, 0x11b84420}, 0x10b857a0, 0x11b86730, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:969 +0xad0
        github.com/hashicorp/terraform-provider-azurerm/internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go:521 +0x440d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1092d880, {0x801e4ec, 0x11b84420}, 0x11b86820, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:826 +0x164
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1092d880, {0x801e4ec, 0x11b84420}, 0x10b857a0, 0x11b86730, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:969 +0xad0
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:826 +0x164
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1092d880, {0x801e4ec, 0x11b84420}, 0x10b857a0, 0x11b86730, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:969 +0xad0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1092d880, {0x801e4ec, 0x11b84420}, 0x10b857a0, 0x11b86730, {0x6baace0, 0x1141a008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:969 +0xad0
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:969 +0xad0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1042d890, {0x801e4ec, 0x11b843f0}, 0x100db3b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/grpc_provider.go:1188 +0xea3
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x10a21810, {0x801e4ec, 0x11b84318}, 0x100db3b0)
        github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x10a21ae0, {0x801e4ec, 0x11b84000}, 0x11b82140)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/tf5server/server.go:866 +0x418
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x76a2fa0, 0x10a21ae0}, {0x801e4ec, 0x11b84000}, 0x11b82100, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x98
google.golang.org/grpc.(*Server).processUnaryRPC(0x10df2508, {0x801e4ec, 0x111df068}, 0x112f4ae0, 0x1107b770, 0xcec32cc, 0x0)
        google.golang.org/grpc@v1.69.4/server.go:1392 +0xfe9
google.golang.org/grpc.(*Server).handleStream(0x10df2508, {0x80204f4, 0x11482128}, 0x112f4ae0)
        google.golang.org/grpc@v1.69.4/server.go:1802 +0xe24
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.69.4/server.go:1030 +0x8a
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 15
        google.golang.org/grpc@v1.69.4/server.go:1041 +0x12e

Error: The terraform-provider-azurerm_v4.30.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Terraform should apply the configuration without crashing. If os_profile requires required fields, it should return a validation error, not crash.

### Actual Behaviour

Terraform crashes during apply when an empty os_profile block is provided. No descriptive error or validation is raised.

### Steps to Reproduce

Run terraform init

Run terraform plan

Run terraform apply

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by WodansSon**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

* Fix crashing bug where an empty `os_profile` block in the `azurerm_orchestrated_virtual_machine_scale_set` resource causes a panic
* Fix additional resource code where `nil` pointer dereferences and unsafe type assertions could also cause panics

### **Go Error Message Standards Compliance:**
* **Lowercase**: All error messages now start with lowercase letters (unless they begin with proper nouns like "VMSS")
* **No punctuation**: Removed periods and unnecessary punctuation from error messages
* **Error wrapping**: Used `%w` verb for proper error wrapping instead of `%+v` or `%v`
* **Error clarity**: Update error messages to be more end user friendly and actionable

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_orchestrated_virtual_machine_scale_set` - Fix crashing bug where an empty `os_profile` block causes a runtime panic [GH-00000]

This is a (please select all that apply):

- [X] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29748

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go [hunk 1]
```diff
@@ -340,23 +340,23 @@ func resourceOrchestratedVirtualMachineScaleSet() *pluginsdk.Resource {
 
 				if hasSkuProfile {
 					if !hasSkuName || skuName != SkuNameMix {
-						return fmt.Errorf("`sku_profile` can only be set when `sku_name` is set to `Mix`")
+						return fmt.Errorf("'sku_profile' can only be configured when 'sku_name' is set to 'Mix'")
```
Comment (sreallymatt) [inline internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go]: Nit: can we change all single quotes around property names back to backticks? Ideally for consistency we stick to one or the other, and based on a quick search in the provider backticks are used around 7x more often vs single quotes within `fmt.Errorf`/`errors.New` calls.

```suggestion
						return fmt.Errorf("`sku_profile` can only be configured when `sku_name` is set to `Mix`")
```

File: internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go [hunk 2]
```diff
@@ -340,23 +340,23 @@ func resourceOrchestratedVirtualMachineScaleSet() *pluginsdk.Resource {
...
+						return fmt.Errorf("'sku_profile' must be configured when 'sku_name' is set to 'Mix'")
 					}
 				}
 
 				upgradeMode := virtualmachinescalesets.UpgradeMode(diff.Get("upgrade_mode").(string))
 				rollingUpgradePolicyRaw := diff.Get("rolling_upgrade_policy").([]interface{})
 
 				if upgradeMode == virtualmachinescalesets.UpgradeModeManual && len(rollingUpgradePolicyRaw) > 0 {
-					return fmt.Errorf("a `rolling_upgrade_policy` block cannot be specified when `upgrade_mode` is set to `%s`", string(upgradeMode))
+					return fmt.Errorf("'rolling_upgrade_policy' cannot be specified when 'upgrade_mode' is set to %q", string(upgradeMode))
```
Comment (sreallymatt) [inline internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go]: Similarly, here when we use `%q` instead of `` `%s` ``, the resulting error message will have a mix of single and double quotes.

```suggestion
					return fmt.Errorf("`rolling_upgrade_policy` cannot be specified when `upgrade_mode` is set to `%s`", string(upgradeMode))
```

File: internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go [hunk 3]
```diff
@@ -489,7 +489,7 @@ func resourceOrchestratedVirtualMachineScaleSetCreate(d *pluginsdk.ResourceData,
 
 	// Virtual Machine Scale Set with Flexible Orchestration Mode and 'Rolling' upgradeMode must have Health Extension Present
 	if upgradeMode == virtualmachinescalesets.UpgradeModeRolling && !hasHealthExtension {
-		return fmt.Errorf("a health extension must be specified when `upgrade_mode` is set to `Rolling`")
+		return fmt.Errorf("a health extension is required when 'upgrade_mode' is set to %q", string(upgradeMode))
```
Comment (sreallymatt) [inline internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go]: `TestAccOrchestratedVirtualMachineScaleSet_otherUpgradePolicyErrorValidation` will need updating as well since it checks for the previous error message and is now failing

File: internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go [hunk 4]
```diff
@@ -340,23 +340,23 @@ func resourceOrchestratedVirtualMachineScaleSet() *pluginsdk.Resource {
...
 				rollingUpgradePolicyRaw := diff.Get("rolling_upgrade_policy").([]interface{})
 
 				if upgradeMode == virtualmachinescalesets.UpgradeModeManual && len(rollingUpgradePolicyRaw) > 0 {
-					return fmt.Errorf("a `rolling_upgrade_policy` block cannot be specified when `upgrade_mode` is set to `%s`", string(upgradeMode))
+					return fmt.Errorf("'rolling_upgrade_policy' cannot be specified when 'upgrade_mode' is set to %q", string(upgradeMode))
 				}
 
 				if upgradeMode == virtualmachinescalesets.UpgradeModeRolling && len(rollingUpgradePolicyRaw) == 0 {
-					return fmt.Errorf("a `rolling_upgrade_policy` block must be specified when `upgrade_mode` is set to `%s`", string(upgradeMode))
+					return fmt.Errorf("'rolling_upgrade_policy' is required when 'upgrade_mode' is set to %q", string(upgradeMode))
```
Comment (sreallymatt) [inline internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go]: `TestAccOrchestratedVirtualMachineScaleSet_otherUpgradePolicyErrorValidation` will need updating as well since it checks for the previous error message and is now failing

**Review by sreallymatt — CHANGES_REQUESTED** [review]

File: internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go (hunk 1 above)
Comment (WodansSon) [reply internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go]: Fixed.

File: internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go (hunk 2 above)
Comment (WodansSon) [reply internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go]: Fixed.

File: internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go (hunk 3 above)
Comment (WodansSon) [reply internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go]: Fixed.

File: internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go (hunk 4 above)
Comment (WodansSon) [reply internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go]: Fixed.
