### PR TITLE
`azurerm_data_factory_pipeline` - migrate to `hashicorp/go-azure-sdk`

### LINKED ISSUE #24998: azurerm_data_factory_pipeline  - json: cannot unmarshal object into Go struct field WebActivityTypeProperties.headers of type string
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.2

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_pipeline

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory_pipeline" "oeeana_refresh_powerbi" {
  name            = "<some_name>"
  data_factory_id = var.data_factory_id
  folder          = "<some_folder>"
  parameters = {
    TenantId         = var.aad_tenant_id
    PBIWorkspaceName = "<some_workspace>"
    PBIDatasetName   = "<some_dataset>"

  }
  variables = {
    PBIWorkspaceID = ""
    PBIDatasetID   = ""
    RefreshStatus  = ""
    Keyvault_Env   = "some_key_vault"
  }
  activities_json = templatefile("${path.module}/templates/oeeana-refresh-powerbi.json.tmpl",
    {
      tenant_id          = var.aad_tenant_id
      pbi_workspace_name = "<some_workspace>"
      pbi_dataset_name   = "<some_dataset>"
  })
}

From init:
- Installing hashicorp/azurerm v3.93.0...
- Installed hashicorp/azurerm v3.93.0 (signed by HashiCorp)
```

### Debug Output/Panic Output

```shell
reading the state of Data Factory Pipeline "<name>": datafactory.PipelinesClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal object into Go struct field WebActivityTypeProperties.headers of type string' JSON = '{
```

### Expected Behaviour

_No response_

### Actual Behaviour

_No response_

### Steps to Reproduce

terraform plan

### Important Factoids

_No response_

### References

Marked as fixed, but happens to us even with 3.93.0
https://github.com/hashicorp/terraform-provider-azurerm/issues/24758

We downgraded to 3.89.0 now to temporarily overcome the issue

### PR DESCRIPTION
**Pull request by stephybun**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

- Moved the expand/flatten function for variables and parameters into the pipeline resource since that is the only place they're used
- Added a complete test with all resource properties specified and multiple activity types in the `activities_json`
- Update the update test to update all updateable properties as well as update back to the basic config
- Removed the custom serialize and deserialize functions for the `activities_json` which were replaced by the Unmarshaler for discriminated types in the `go-azure-sdk`
- Removed the `azuresdkhacks` folder and contents since this has been replaced by `go-azure-sdk`

**Note:** I opted to not also split the Create and Update methods here, since this is already quite a big change to the resource

## Testing 

image
image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `dependencies`: `azurerm_data_factory_pipelines` update to use `hashicorp/go-azure-sdk` [GH-00000]
* `azurerm_data_factory_pipelines` - fix issue where a web activity with a header in `activities_json` could not be unmarshaled [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #24998

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/datafactory/data_factory_pipeline_resource.go [hunk 1]
```diff
@@ -279,14 +289,78 @@ func resourceDataFactoryPipelineDelete(d *pluginsdk.ResourceData, meta interface
...
+		return output
+	}
+	for k, v := range *input {
+		// we only support string parameters at this time
+		if v.Type != pipelines.ParameterTypeString {
+			log.Printf("[DEBUG] Skipping parameter %q since it's not a string", k)
+			continue
+		}
+
+		output[k] = (*v.DefaultValue).(string)
```
Comment (catriona-m) [inline internal/services/datafactory/data_factory_pipeline_resource.go:330]: could `pointer.From` be used here?

**Review by catriona-m — APPROVED** [review]
LGTM!

File: internal/services/datafactory/data_factory_pipeline_resource.go (hunk 1 above)
Comment (stephybun) [reply internal/services/datafactory/data_factory_pipeline_resource.go]: It can! Thanks for the spot

**Review by jackofallops — APPROVED** [review]
Thanks @stephybun - LGTM 🦉
