### PR TITLE
`azurerm_automation_software_update_configuration` - fix  issue about `monthly_occurrence` is not allowed to be set to `-1`

### LINKED ISSUE #25550: azurerm_automation_software_update_configuration monthly_occurrence not allowing "-1"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
data "azurerm_automation_account" "Windows_Automation_Account" {
  name                = "Windows-Automation-Account"
  resource_group_name = "Windows-Automation-Account-RG"
}

resource "azurerm_automation_software_update_configuration" "ScheduleWindows" {
  name                  = "Windows-Automation"
  automation_account_id = azurerm_automation_account.Windows_Automation_Account.id
  target {
    azure_query {
      tag_filter = "All"
      tags {
        tag    = "UpdateGroup"
        values = "Cluster01"
      }
    }
  }
  schedule {
    is_enabled = true
    frequency  = "Month"
    time_zone  = "Etc/UTC"
    interval   = 1
    start_time = "10:00"
    monthly_occurrence {
      day        = "Thursday"
      occurrence = "-1"
    }
  }

  windows {
    classifications_included = ["Critical", "Security"]
    reboot                   = "Always"
  }
  duration = "PT3H"
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: expected schedule.0.monthly_occurrence.0.occurrence to be in the range (1 - 5), got -1
│
│   with module.automationAccount.azurerm_automation_software_update_configuration.ScheduleWindows["Windows-Automation"],
│   on main.tf line 149, in resource "azurerm_automation_software_update_configuration" "ScheduleWindows":
│  149:       occurrence = "-1"
│
╵
```

### Expected Behaviour

According to https://registry.terraform.io/providers/hashicorp/azurerm/3.95.0/docs/resources/automation_software_update_configuration, the values for "occurrence" are expected to be 1-5 or -1.  1 meaning the first occurrence of the day and -1 meaning the last occurrence.  When using occurrence = "-1" it is expected that the occurrence be set to "Last"

### Actual Behaviour

Planning failed. Terraform encountered an error while generating this plan.

Error: expected schedule.0.monthly_occurrence.0.occurrence to be in the range (1 - 5), got -1

### Steps to Reproduce

terraform plan

### Important Factoids

_No response_

### References

https://registry.terraform.io/providers/hashicorp/azurerm/3.95.0/docs/resources/automation_software_update_configuration

### PR DESCRIPTION
**Pull request by sinbai**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

After testing, it was found that the possible values of  `monthly_occurrence` should be `1`, `2`,`3`,`4`,`-1` ，corresponds to "First", "Second", "Third", "Fourth" and "Last" in the Azure Portal respectively. Details are as follows.
image

Submit this PR to replace the non-existent value `5` with `-1` to fix #25550.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

PASS: TestAccSoftwareUpdateConfiguration_occurrence (186.12s)

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25550

### CODE REVIEW

File: internal/services/automation/automation_software_update_configuration_resource.go [hunk 1]
```diff
@@ -628,7 +628,7 @@ func (m SoftwareUpdateConfigurationResource) Arguments() map[string]*pluginsdk.S
 								"occurrence": {
 									Type:         pluginsdk.TypeInt,
 									Required:     true,
-									ValidateFunc: validation.IntBetween(1, 5),
+									ValidateFunc: validation.IntInSlice([]int{1, 2, 3, 4, -1}),
```
Comment (katbyte) [inline internal/services/automation/automation_software_update_configuration_resource.go:631]: what currently happens if a user tries to set 5? does the API reject or acept it?

**Review by katbyte — CHANGES_REQUESTED** [review]

File: internal/services/automation/automation_software_update_configuration_resource.go (hunk 1 above)
Comment (sinbai) [reply internal/services/automation/automation_software_update_configuration_resource.go:631]: API accepts `5`, but it will be displayed as empty on the Portal. If `-1` is set, it will be displayed as `Last` on the Portal.

Comment (katbyte) [inline internal/services/automation/automation_software_update_configuration_resource.go:631]:
```suggestion
									ValidateFunc: validation.IntInSlice([]int{1, 2, 3, 4, -1}), // -1 is last week and 5 is invalid
```

**Review by katbyte — APPROVED** [review]
LGTM 🛋️
