### PR TITLE
`azurerm_mssql_managed_instance` - Add possible value `SQL_AustraliaEast_MI_2`  for `maintenance_configuration_name` property

### LINKED ISSUE #20883: maintenance_configuration_name Valid values incomplete
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_managed_instance" "example" {
  name                = "managedsqlinstance"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  license_type       = "BasePrice"
  sku_name           = "GP_Gen5"
  storage_size_in_gb = 32
  subnet_id          = azurerm_subnet.example.id
  vcores             = 4

  maintenance_configuration_name = "SQL_AustraliaEast_MI_2"

  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"

}
```

### Debug Output/Panic Output

```shell
Error: expected maintenance_configuration_name to be one of [SQL_Default SQL_EastUS_MI_1 SQL_EastUS2_MI_1 SQL_WestUS2_MI_1 SQL_SoutheastAsia_MI_1 SQL_AustraliaEast_MI_1 SQL_NorthEurope_MI_1 SQL_SouthCentralUS_MI_1 SQL_UKSouth_MI_1 SQL_WestEurope_MI_1 SQL_EastUS_MI_2 SQL_EastUS2_MI_2 SQL_WestUS2_MI_2 SQL_SoutheastAsia_MI_2 SQL_NorthEurope_MI_2 SQL_SouthCentralUS_MI_2 SQL_UKSouth_MI_2 SQL_WestEurope_MI_2 SQL_AustraliaSoutheast_MI_1 SQL_BrazilSouth_MI_1 SQL_CanadaCentral_MI_1 SQL_CanadaEast_MI_1 SQL_CentralUS_MI_1 SQL_EastAsia_MI_1 SQL_FranceCentral_MI_1 SQL_GermanyWestCentral_MI_1 SQL_CentralIndia_MI_1 SQL_JapanEast_MI_1 SQL_JapanWest_MI_1 SQL_NorthCentralUS_MI_1 SQL_UKWest_MI_1 SQL_WestUS_MI_1 SQL_AustraliaSoutheast_MI_2 SQL_BrazilSouth_MI_2 SQL_CanadaCentral_MI_2 SQL_CanadaEast_MI_2 SQL_CentralUS_MI_2 SQL_EastAsia_MI_2 SQL_FranceCentral_MI_2 SQL_GermanyWestCentral_MI_2 SQL_CentralIndia_MI_2 SQL_JapanEast_MI_2 SQL_JapanWest_MI_2 SQL_NorthCentralUS_MI_2 SQL_UKWest_MI_2 SQL_WestUS_MI_2 SQL_KoreaCentral_MI_1 SQL_KoreaCentral_MI_2 SQL_WestCentralUS_MI_1 SQL_WestCentralUS_MI_2 SQL_UAENorth_MI_1 SQL_SwitzerlandWest_MI_1 SQL_SwitzerlandNorth_MI_1 SQL_UAENorth_MI_2 SQL_SwitzerlandWest_MI_2 SQL_SwitzerlandNorth_MI_2 SQL_FranceSouth_MI_1 SQL_FranceSouth_MI_2 SQL_SouthAfricaNorth_MI_1 SQL_KoreaSouth_MI_1 SQL_UAECentral_MI_1 SQL_SouthAfricaNorth_MI_2 SQL_KoreaSouth_MI_2 SQL_UAECentral_MI_2 SQL_SouthIndia_MI_1 SQL_SouthIndia_MI_2 SQL_AustraliaCentral_MI_1 SQL_AustraliaCentral2_MI_1 SQL_AustraliaCentral_MI_2 SQL_AustraliaCentral2_MI_2 SQL_WestIndia_MI_1 SQL_WestIndia_MI_2 SQL_SouthAfricaWest_MI_1 SQL_SouthAfricaWest_MI_2 SQL_GermanyNorth_MI_1 SQL_GermanyNorth_MI_2 SQL_NorwayEast_MI_1 SQL_BrazilSoutheast_MI_1 SQL_NorwayWest_MI_1 SQL_WestUS3_MI_1 SQL_NorwayEast_MI_2 SQL_BrazilSoutheast_MI_2 SQL_NorwayWest_MI_2 SQL_WestUS3_MI_2], got SQL_AustraliaEast_MI_2
```

### Expected Behaviour

Accepted SQL_AustraliaEast_MI_2

### Actual Behaviour

Error

### Steps to Reproduce

terraform validate

### Important Factoids

_No response_

### References
If you check the Config options there is a SQL_AustraliaEast_MI_2 listed.

`$location = "australiaeast"
$configurations = Get-AzMaintenancePublicConfiguration
$configurations | ?{ $_.Location -eq $location -and $_.MaintenanceScope -eq "SQLManagedInstance"}`

Cant seem to upload a screenshot?

### PR DESCRIPTION
**Pull request by sinbai**
After checking the [Public Maintenance Configurations - List](https://learn.microsoft.com/en-us/rest/api/maintenance/public-maintenance-configurations/list?tabs=HTTP#code-try-0), the  `SQL_AustraliaEast_MI_2` is supported for location `australiaeast`. Submit this PR to fix #20883 .

### CODE REVIEW

File: internal/services/mssql/mssql_managed_instance_resource.go [hunk 1]
```diff
@@ -165,7 +165,7 @@ func (r MsSqlManagedInstanceResource) Arguments() map[string]*pluginsdk.Schema {
 			Type:     schema.TypeString,
 			Optional: true,
 			Default:  "SQL_Default",
-			ValidateFunc: validation.StringInSlice([]string{"SQL_Default", "SQL_EastUS_MI_1", "SQL_EastUS2_MI_1", "SQL_WestUS2_MI_1", "SQL_SoutheastAsia_MI_1", "SQL_AustraliaEast_MI_1", "SQL_NorthEurope_MI_1", "SQL_SouthCentralUS_MI_1",
+			ValidateFunc: validation.StringInSlice([]string{"SQL_Default", "SQL_EastUS_MI_1", "SQL_EastUS2_MI_1", "SQL_WestUS2_MI_1", "SQL_SoutheastAsia_MI_1", "SQL_AustraliaEast_MI_1", "SQL_AustraliaEast_MI_2", "SQL_NorthEurope_MI_1", "SQL_SouthCentralUS_MI_1",
```
Comment (tombuildsstuff) [inline internal/services/mssql/mssql_managed_instance_resource.go:168]: perhaps we should use a regex for this instead, since besides `SQL_Default` the other values are in the format `SQL_{Location}_MI_{Integer}`?

Comment (sinbai) [reply internal/services/mssql/mssql_managed_instance_resource.go]: Thanks for your feedback. The code has been updated. Could you please take another look?

File: website/docs/r/mssql_managed_instance.html.markdown [hunk 2]
```diff
@@ -233,7 +233,7 @@ The following arguments are supported:
...
...2`, `SQL_EastAsia_MI_2`, `SQL_FranceCentral_MI_2`, `SQL_GermanyWestCentral_MI_2`, `SQL_CentralIndia_MI_2`, `SQL_JapanEast_MI_2`, `SQL_JapanWest_MI_2`, `SQL_NorthCentralUS_MI_2`, `SQL_UKWest_MI_2`, `SQL_WestUS_MI_2`, `SQL_KoreaCentral_MI_1`, `SQL_KoreaCentral_MI_2`, `SQL_WestCentralUS_MI_1`, `SQL_WestCentralUS_MI_2`, `SQL_UAENorth_MI_1`, `SQL_SwitzerlandWest_MI_1`, `SQL_SwitzerlandNorth_MI_1`, `SQL_UAENorth_MI_2`, `SQL_SwitzerlandWest_MI_2`, `SQL_SwitzerlandNorth_MI_2`, `SQL_FranceSouth_MI_1`, `SQL_FranceSouth_MI_2`, `SQL_SouthAfricaNorth_MI_1`, `SQL_KoreaSouth_MI_1`, `SQL_UAECentral_MI_1`, `SQL_SouthAfricaNorth_MI_2`, `SQL_KoreaSouth_MI_2`, `SQL_UAECentral_MI_2`, `SQL_SouthIndia_MI_1`, `SQL_SouthIndia_MI_2`, `SQL_AustraliaCentral_MI_1`, `SQL_AustraliaCentral2_MI_1`, `SQL_AustraliaCentral_MI_2`, `SQL_AustraliaCentral2_MI_2`, `SQL_WestIndia_MI_1`, `SQL_WestIndia_MI_2`, `SQL_SouthAfricaWest_MI_1`, `SQL_SouthAfricaWest_MI_2`, `SQL_GermanyNorth_MI_1`, `SQL_GermanyNorth_MI_2`, `SQL_NorwayEast_MI_1`, `SQL_BrazilSoutheast_MI_1`, `SQL_NorwayWest_MI_1`, `SQL_WestUS3_MI_1`, `SQL_NorwayEast_MI_2`, `SQL_BrazilSoutheast_MI_2`, `SQL_NorwayWest_MI_2`, `SQL_WestUS3_MI_2`. Defaults to `SQL_Default`.
```
Comment (tombuildsstuff) [inline website/docs/r/mssql_managed_instance.html.markdown:236]: we can reduce this to:

```suggestion
* `maintenance_configuration_name` - (Optional) The name of the Public Maintenance Configuration window to apply to the SQL Managed Instance. Valid values include `SQL_Default` or an Azure Location in the format `SQL_{Location}_MI_{Size}`(for example `SQL_EastUS_MI_1`). Defaults to `SQL_Default`.
```

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hi @sinbai 

Thanks for pushing those changes, I've left a couple of comments inline - but in short we can reduce this to using a regex for the format of the string, rather than for the specific values - which should enable supporting this in Environments other than Azure Public too, would you mind taking a look?

Thanks!

File: website/docs/r/mssql_managed_instance.html.markdown (hunk 2 above)
Comment (sinbai) [reply website/docs/r/mssql_managed_instance.html.markdown]: Thanks for your feedback. The code has been updated. Could you please take another look?

File: internal/services/mssql/mssql_managed_instance_resource.go [hunk 3]
```diff
@@ -165,17 +166,10 @@ func (r MsSqlManagedInstanceResource) Arguments() map[string]*pluginsdk.Schema {
...
-				"SQL_AustraliaCentral2_MI_2", "SQL_WestIndia_MI_1", "SQL_WestIndia_MI_2", "SQL_SouthAfricaWest_MI_1", "SQL_SouthAfricaWest_MI_2", "SQL_GermanyNorth_MI_1", "SQL_GermanyNorth_MI_2", "SQL_NorwayEast_MI_1",
-				"SQL_BrazilSoutheast_MI_1", "SQL_NorwayWest_MI_1", "SQL_WestUS3_MI_1", "SQL_NorwayEast_MI_2", "SQL_BrazilSoutheast_MI_2", "SQL_NorwayWest_MI_2", "SQL_WestUS3_MI_2"}, false),
+			ValidateFunc: validation.StringMatch(
+				regexp.MustCompile(`^SQL_Default$|^SQL_(EastUS|EastUS2|WestUS2|SoutheastAsia|AustraliaEast|NorthEurope|SouthCentralUS|UKSouth|WestEurope|AustraliaSoutheast|BrazilSouth|CanadaCentral|CanadaEast|CentralUS|EastAsia|FranceCentral|GermanyWestCentral|CentralIndia|JapanEast|JapanWest|NorthCentralUS|UKWest|WestUS|KoreaCentral|WestCentralUS|UAENorth|SwitzerlandWest|SwitzerlandNorth|FranceSouth|SouthAfricaNorth|KoreaSouth|UAECentral|SouthIndia|AustraliaCentral|AustraliaCentral2|WestIndia|SouthAfricaWest|GermanyNorth|NorwayEast|NorwayWest|BrazilSoutheast|WestUS3)_MI_[1,2]$`),
+				`This is not a valid maintenance configuration name.`,
+			),
```
[the remark this answers is not in the document]
Comment (sinbai) [reply internal/services/mssql/mssql_managed_instance_resource.go]: Thanks for your feedback. The code has been updated. Could you please take another look?

**Comment by UppyAU** [comment]
How does it look now @tombuildsstuff ? 👀

File: internal/services/mssql/mssql_managed_instance_resource.go [hunk 4]
```diff
@@ -165,17 +166,12 @@ func (r MsSqlManagedInstanceResource) Arguments() map[string]*pluginsdk.Schema {
...
-				"SQL_SwitzerlandNorth_MI_2", "SQL_FranceSouth_MI_1", "SQL_FranceSouth_MI_2", "SQL_SouthAfricaNorth_MI_1", "SQL_KoreaSouth_MI_1", "SQL_UAECentral_MI_1", "SQL_SouthAfricaNorth_MI_2",
-				"SQL_KoreaSouth_MI_2", "SQL_UAECentral_MI_2", "SQL_SouthIndia_MI_1", "SQL_SouthIndia_MI_2", "SQL_AustraliaCentral_MI_1", "SQL_AustraliaCentral2_MI_1", "SQL_AustraliaCentral_MI_2",
-				"SQL_AustraliaCentral2_MI_2", "SQL_WestIndia_MI_1", "SQL_WestIndia_MI_2", "SQL_SouthAfricaWest_MI_1", "SQL_SouthAfricaWest_MI_2", "SQL_GermanyNorth_MI_1", "SQL_GermanyNorth_MI_2", "SQL_NorwayEast_MI_1",
-				"SQL_BrazilSoutheast_MI_1", "SQL_NorwayWest_MI_1", "SQL_WestUS3_MI_1", "SQL_NorwayEast_MI_2", "SQL_BrazilSoutheast_MI_2", "SQL_NorwayWest_MI_2", "SQL_WestUS3_MI_2"}, false),
+			ValidateFunc: validation.Any(
+				validation.StringInSlice([]string{
+					"SQL_Default",
+				}, false),
+				validation.StringMatch(regexp.MustCompile(`^SQL_([A-Za-z0-9])+_MI_(\\d)+$`), "expected a name in the format `SQL_{Location}_MI_{Number}` or `SQL_Default`"),
```
Comment (manicminer) [inline internal/services/mssql/mssql_managed_instance_resource.go:173]: We can remove the unneeded parantheses here, and also no need to escape the backslash in a raw string (which broke the regex), see https://go.dev/play/p/Xi1lVfXoc2u

```suggestion
				validation.StringMatch(regexp.MustCompile(`^SQL_[A-Za-z0-9]+_MI_\d+$`), "expected a name in the format `SQL_{Location}_MI_{Number}` or `SQL_Default`"),
```

alternatively use a regular string:

```suggestion
				validation.StringMatch(regexp.MustCompile("^SQL_[A-Za-z0-9]+_MI_\\d+$"), "expected a name in the format `SQL_{Location}_MI_{Number}` or `SQL_Default`"),
```

**Review by manicminer — CHANGES_REQUESTED** [review]
@sinbai Thanks for the changes, unfortunately the regex doesn't match any of the values, I've suggested a fix below.

File: internal/services/mssql/mssql_managed_instance_resource.go (hunk 4 above)
Comment (sinbai) [reply internal/services/mssql/mssql_managed_instance_resource.go]: @manicminer thanks for your feedback. The code has been updated. Could you please take another look?

**Review by katbyte — APPROVED** [review]
LGTM 💾
