### PR TITLE
Fix dependency parse of `azurerm_kusto_cluster.id`

### LINKED ISSUE #20868: Case change in kusto_cluster ID causing resource recreation/updates
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.15.5

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_kusto_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "my-kusto-cluster-rg"
  location = "West Europe"
}

resource "azurerm_kusto_cluster" "example" {
  name                = "kustocluster"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku {
    name     = "Standard_D13_v2"
    capacity = 2
  }

  tags = {
    Environment = "Production"
  }
}
```

### Debug Output/Panic Output

```shell
<none>
```

### Expected Behaviour

upgrading from 3.20.0 we should see no state changes if there was no configuration change

### Actual Behaviour

all resources that reference the azurerm_kusto_cluster.<name>.id are updated with the ID changing a single character from `Clusters` to `clusters`, for example:

```
"/subscriptions/sub-id/resourceGroups/exmaple-rg/providers/Microsoft.Kusto/Clusters/example" -> "/subscriptions/sub-id/resourceGroups/example-rg/providers/Microsoft.Kusto/clusters/example"
```

This causes resources like the `azurerm_monitor_diagnostic_setting` to be replaced due to the `target_resource_id` changing, and other resources like the `azurerm_kusto_eventhub_data_connection` to be updated with a new `identity_id`. this is an update in place however should not be necessary and I do not believe that the new ID is valid.

### Steps to Reproduce

1. create/import kusto cluster in azurerm provider version 3.20.0 or earlier, will use capital `C` `Clusters` along with some related resources such as diagnostics and/or eventhub connections.
2. Upgrade provider to 3.46.0
3. Run `terraform plan`
4. See that resources are edited/updated due to case change in ID

### Important Factoids

_No response_

### References

This PR https://github.com/hashicorp/terraform-provider-azurerm/pull/19525 did the changes but does not note why/how/what changes and/or how to mitigate.

Theoretically state manipulation to edit the stored IDs in the state would be a workaround but that seems unwise as Azure uses the capital `C` `Clusters` in all their IDs of Kusto Clusters using the UI/API.

### PR DESCRIPTION
**Pull request by myc2h6o**
Fix #20868
The segment `Clusters` in id of `azurerm_kusto_cluster` has been changed to `clusters` in #19525. For other resources which has kusto cluster as part of its dependency created in older provider version, the segment is already set to `Clusters` at service side. This could cause a diff when provider is updated, where `azurerm_kusto_cluster.id` is auto migrated to `clusters` in the state updater, while it's still `Clusters` at service side. Fixing the diff by normalize the ID returned by service.

### CODE REVIEW

File: internal/services/monitor/monitor_diagnostic_setting_resource.go [hunk 1]
```diff
@@ -462,6 +463,8 @@ func resourceMonitorDiagnosticSettingRead(d *pluginsdk.ResourceData, meta interf
 		return err
 	}
 
+	id.ResourceUri = normalizeMonitorDiagnosticSettingTargetResourceId(id.ResourceUri)
```
Comment (katbyte) [inline internal/services/monitor/monitor_diagnostic_setting_resource.go:466]: i'm not sure why this is a function as its only used in a single place? can we inline it?

**Review by katbyte — CHANGES_REQUESTED** [review]

File: internal/services/monitor/monitor_diagnostic_setting_resource.go (hunk 1 above)
Comment (myc2h6o) [reply internal/services/monitor/monitor_diagnostic_setting_resource.go]: done.

File: internal/services/monitor/monitor_diagnostic_setting_resource.go [hunk 2]
```diff
@@ -462,6 +463,12 @@ func resourceMonitorDiagnosticSettingRead(d *pluginsdk.ResourceData, meta interf
 		return err
 	}
 
+	if strings.Contains(strings.ToLower(id.ResourceUri), "microsoft.kusto/clusters/") {
+		if v, err := kustoParse.ClusterIDInsensitively(id.ResourceUri); err == nil {
+			id.ResourceUri = v.ID()
+		}
+	}
```
Comment (stephybun) [inline internal/services/monitor/monitor_diagnostic_setting_resource.go:470]: This can probably be simplified to 
```suggestion
	if v, err := kustoParse.ClusterIDInsensitively(id.ResourceUri); err == nil {
		id.ResourceUri = v.ID()
	}
```

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this @myc2h6o, one minor comment but otherwise this is looking good.

File: internal/services/monitor/monitor_diagnostic_setting_resource.go (hunk 2 above)
Comment (myc2h6o) [reply internal/services/monitor/monitor_diagnostic_setting_resource.go]: done.

**Review by stephybun — APPROVED** [review]
Thanks @myc2h6o LGTM 💯

**Comment by esener303** [comment]
I faced same issue but related to different service like azurerm_synapse_managed_private_endpoint and on server side there its Microsoft.Kusto/Clusters which was created by old provider version, after upgrade to 3.51.0 same issue persist and can not find any solution and workarounds so far.

``` 
 # module.plantlink_standalone_adx_cluster.azurerm_synapse_managed_private_endpoint.synapse_adx_endpoint must be replaced
-/+ resource "azurerm_synapse_managed_private_endpoint" "synapse_adx_endpoint" {
      ~ id                   = "/subscriptions/xxx-xxx-xxx-xxx/resourceGroups/rg-emea_we_hcpdev-plantlink_workspace_001/providers/Microsoft.Synapse/workspaces/plsynw-emea-we-hcpdev-plantlinksw-dev-001/managedVirtualNetworks/default/managedPrivateEndpoints/kustoplantlinkdev" -> (known after apply)
        name                 = "kustoplantlinkdev"
      ~ target_resource_id   = "/subscriptions/xxx-xxx-xxx-xxx/resourceGroups/rg-emea_we_hcpdev-plantlink_dev_001/providers/Microsoft.Kusto/Clusters/kustoplantlinkdev" -> "/subscriptions/xxx-xxx-xxx-xxx/resourceGroups/rg-emea_we_hcpdev-plantlink_dev_001/providers/Microsoft.Kusto/clusters/kustoplantlinkdev"
```
