### PR TITLE
`azurerm_logic_app_standard` - fix setting `public_network_access` for conflicting API properties

### LINKED ISSUE #27398: azurerm_logic_app_standard does not have an argument for Microsoft.Web/sites/publicNetworkAccess
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.108

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_standard

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "azure-functions-test-rg"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "functionsapptestsa"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "example" {
  name                = "azure-functions-test-service-plan"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  kind                = "elastic"


  sku {
    tier = "WorkflowStandard"
    size = "WS1"
  }
}

resource "azurerm_logic_app_standard" "example" {
  name                       = "test-azure-functions"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key

  app_settings = {
    "FUNCTIONS_WORKER_RUNTIME"     = "node"
    "WEBSITE_NODE_DEFAULT_VERSION" = "~18"
  }
}
```

### Debug Output/Panic Output

```shell
na
```

### Expected Behaviour

Using Terraform, I expect to be able to configure both Microsoft parameters described below.  Especially since policy or best practice scanners may check both parameters.  

Microsoft has 2 parameters regarding "publicNetworkAccess" for Logic App Standard:
1. "Microsoft.Web/sites/config" (properties.siteConfig.publicNetworkAccess)
2. "Microsoft.Web/sites" (properties.publicNetworkAccess)

Using Powershell: you can see the 2 parameters.
(get-azresource -id "/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.Web/sites/xxxxxx").properties.siteConfig.publicNetworkAccess
(get-azresource -id "/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.Web/sites/xxxxxx").properties.publicNetworkAccess

AND

Examination of the JSON exported template from a LogicApp in Azure Portal will also show these 2 parameters.  
1. Microsoft.Web/sites/config "publicNetworkAccess"
2. Microsoft.Web/sites "publicNetworkAccess"

UNFORTUNATELY, 
I could not find a way to see 'both' parameters with Azure CLI
This AZ CLI command only shows #1, properties.siteConfig.publicNetworkAccess, it does not give us #2, properties.publicNetworkAccess.
Get-AzWebApp -ResourceGroupName "xxxxxx" -Name "xxxxxx"  
 
ALSO,
Looking in Azure Portal > Logic app > settings > Networking > Inbound traffic configuration | Public network access
This configuration setting seems to be related only to #2, "Microsoft.Web/sites" (properties.publicNetworkAccess).  NOT #1.  
because when I changed the value here in portal, the deployment JSON shows:
        "value": "Microsoft.Web/sites/write",
        "localizedValue": "Update website"

### Actual Behaviour

azurerm_logic_app_standard currently only has 1 argument, and it is for "Microsoft.Web/sites/config" exposed inside the site_config block.    It does not have an argument for "Microsoft.Web/sites/"

### Steps to Reproduce

terraform apply

### Important Factoids

na

### References

na

### PR DESCRIPTION
**Pull request by jackofallops**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Fixes a bug in setting `publicNetworkAccess` due to this being set in two places currently which can conflict with each other and cause inconsistent behaviour.

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_logic_app_standard` - fix setting `public_network_access` for conflicting API properties

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Closes #27398

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/logic/logic_app_standard_resource.go [hunk 1]
```diff
@@ -341,9 +341,10 @@ func resourceLogicAppStandardCreate(d *pluginsdk.ResourceData, meta interface{})
 	}
 
 	publicNetworkAccess := d.Get("public_network_access").(string)
-	if !features.FivePointOhBeta() && publicNetworkAccess == "" {
+	if !features.FivePointOhBeta() {
 		// if a user is still using `site_config.public_network_access_enabled` we should be setting `public_network_access` for them
-		publicNetworkAccess = helpers.PublicNetworkAccessEnabled
+		publicNetworkAccess = reconcilePNA(d)
+		// publicNetworkAccess = helpers.PublicNetworkAccessEnabled
```
Comment (stephybun) [inline internal/services/logic/logic_app_standard_resource.go:347]:
```suggestion
```

**Review by stephybun — APPROVED** [review]
Thanks @jackofallops LGTM 🐗

**Comment by jackofallops** [comment]
Tests look good:

image
