### PR TITLE
`azurerm_application_gateway`: Support for `components` in `rewrite_rule_set.rewrite_rule.url`

### LINKED ISSUE #11563: [App Gateway] URL Rewrites don't support undefined values
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

>= 2.54.0

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
  rewrite_rule_set {
    name = "test-rewrite-ruleset"

    rewrite_rule {
      name          = "test-rewrite-rule"
      rule_sequence = 1

      condition {
        variable = "var_uri_path"
        pattern  = ".*article/(.*)/(.*)"
      }

      url {
      }
    }
  }
```

This configuration, which should cause an error, does not because the `url.path` and `url.query_string` values become `""` (empty strings) instead of `nil`. Empty strings are valid values but should not be the value when nothing is declared. As such, this causes a mis-configuration of the re-write as the path and query strings are removed rather than retained.

### Expected Behaviour

Undefined properties should not be passed to the underlying API as empty strings

### Actual Behaviour

Undefined properties are passed to the underlying API as empty strings

### Steps to Reproduce

1. `terraform apply`

### References

* #10950

cc-ing previously involved participants: @jackofallops, @katbyte, @ido-tr

### LINKED ISSUE #13894: Azure Application Gateway - Url can't be set without causing Query String to be empty
When writing a rewrite rule where the intent is to only update the path without rewriting the query string, Terraform will set an empty string on the query string.  This is a significant problem, as it causes query strings to be lost when using rewrite rules.  I'm using the latest version 2.82.0.

rewrite_rule_set {
        name                       = "rwruleset"
        rewrite_rule {

                name                   = "rwrule1"
                rule_sequence          = 1

             
                condition {
                   
                    variable           = "var_uri_path"
                    pattern            = "/checkout/(.+)"
                 
                }
                url {
                    path               = "/{var_uri_path_1}" 
                    # query_string         The query string should not be set by Terraform as empty string. 
                   
                }
        } 
    }

This was originally discovered here: https://github.com/hashicorp/terraform-provider-azurerm/pull/10950 . You can notice that this snippet of code will incorrectly assume that both Path and Query String needs to be rewritten. 

```
rewrite_rule_set {
    name = "test-rewrite-ruleset"

    rewrite_rule {
      name          = "test-rewrite-rule"
      rule_sequence = 1

      condition {
        variable = "var_uri_path"
        pattern  = ".*article/(.*)/(.*)"
      }

      url {
        path         = "/article.aspx"
      }
    }
  }
```

image

Having inspected the state file, I think I see the problem. When no value is provided the state file shows that there is a value of `""` (an empty string), which probably means the `query_string` is essentially being replaced by the rewrite rule.

I'm not entirely sure why this is the case, but I'll do some investigation as to why empty strings are going through when no value is provided.

_Originally posted by @dhensby in https://github.com/hashicorp/terraform-provider-azurerm/issues/10950#issuecomment-822334088_

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #13894
Fixes #11563

Introduction of a `rewrite_rule_set.rewrite_rule.url.components` property to limit rewrite to URL Path or URL Query String only

## Acceptance Tests
```bash
❯ go install && make acctests SERVICE='network' TESTARGS='-run=TestAccApplicationGateway_rewriteRuleSets_rewriteUrl'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/network -run=TestAccApplicationGateway_rewriteRuleSets_rewriteUrl -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccApplicationGateway_rewriteRuleSets_rewriteUrl
=== PAUSE TestAccApplicationGateway_rewriteRuleSets_rewriteUrl
=== CONT  TestAccApplicationGateway_rewriteRuleSets_rewriteUrl
--- PASS: TestAccApplicationGateway_rewriteRuleSets_rewriteUrl (712.80s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network     714.417
```

### CODE REVIEW

File: internal/services/network/application_gateway_resource.go [hunk 1]
```diff
@@ -1019,6 +1019,18 @@ func resourceApplicationGateway() *pluginsdk.Resource {
...
+
+												"components": {
+													Type:     pluginsdk.TypeString,
+													Optional: true,
+													Computed: true,
+													ValidateFunc: validation.StringInSlice([]string{
+														"path_only",
+														"query_string_only",
+														"",
+													}, true),
```
Comment (tombuildsstuff) [inline internal/services/network/application_gateway_resource.go:1031]: since we're explicitly comparing the values this needs to be case-sensitive, and there's no need for this to be computed?

```suggestion
													ValidateFunc: validation.StringInSlice([]string{
														"path_only",
														"query_string_only",
													}, false),
```

File: internal/services/network/application_gateway_resource.go [hunk 2]
```diff
@@ -3223,10 +3239,16 @@ func flattenApplicationGatewayRewriteRuleSets(input *[]network.ApplicationGatewa
...
 							}
 
 							if config.ModifiedQueryString != nil {
 								urlConfig["query_string"] = *config.ModifiedQueryString
+								urlConfig["components"] = "query_string_only"
+							}
+
+							if config.ModifiedQueryString != nil && config.ModifiedPath != nil {
+								urlConfig["components"] = ""
 							}
```
Comment (tombuildsstuff) [inline internal/services/network/application_gateway_resource.go:3252]: presumably `components` should be defaulted to `""` and then overridden if either Path or QueryString isn't present?

**Review by tombuildsstuff — APPROVED** [review]
hey @aristosvo 

Thanks for this PR - apologies for the delayed re-review here.

I've taken a look through and left a couple of comments inline - namely since these values are being used as a case-sensitive comparison they need to be case-sensitive - also we can remove `""` as a value by making this non-computed. Since this PR's not up to date with `main` at this point in time I hope you don't mind but I've pushed a commit to both fix that and rebase this so that we can get this merged 👍 

Thanks!

**Comment by mbfrahry** [comment]
Looks like the changes made caused a test to fail

```
TestAccApplicationGateway_rewriteRuleSets_rewriteUrl
testcase.go:110: Step 1/2 error: Check failed: Check 4/7 error: azurerm_application_gateway.test: Attribute 'rewrite_rule_set.0.rewrite_rule.0.url.0.components' expected "", got "path_only"
```

**Comment by benj-ch** [comment]
When this PR will be released ?
3 weeks that the feature is ready...

**Comment by benj-ch** [comment]
> This functionality has been released in [v3.4.0 of the Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.4.0/CHANGELOG.md). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
> 
> For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) following the template. Thank you!

I'm surprised that the feature isn't in the v3.4.0 of Terraform Provider as stated...
Do you have any release information?

**Review by mbfrahry — APPROVED** [review]
LGTM
