### PR TITLE
`azurerm_automation_schedule` - import `time/tzdata` to embed timezone information

### LINKED ISSUE #20690: "unknown time zone <timezone>" on azurerm_automation_schedule
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

2.3.0

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_schedule

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    resource_group_name  = "MyResourceGroup"
    storage_account_name = "terraform12345"
    container_name       = "tstate"
    key                  = "terraform.tfstate"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.64.0, != 2.86.0"

    }
  }
}

# Configure the Microsoft Azure Provider
provider "azurerm" {
  skip_provider_registration = true
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}
resource "azurerm_resource_group" "rg" {
  name     = "MyResourceGroup"
  location = "northeurope"
}

resource "azurerm_automation_account" "automation_account" {
  name                = "autom-dev"
  location            = "westeurope"
  resource_group_name = "MyResourceGroup"
  sku_name            = "Basic"
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_automation_schedule" "restart_app_service_during_the_night_schedule" {
  name                    = "RestartAppServiceDuringTheNightSchedule"
  resource_group_name     = "MyResourceGroup"
  automation_account_name = azurerm_automation_account.automation_account.name
  frequency               = "Week"
  interval                = 1
  timezone                = "Europe/Rome"
  start_time              = "2023-01-26T03:00:00+01:00"
  description             = "Schedule for restart of App Service during the night"
  week_days               = ["Monday", "Thursday"]
}
```

### Debug Output/Panic Output

```shell
│ Error: unknown time zone Europe/Rome
│
│   with module.automation.azurerm_automation_schedule.restart_app_service_during_the_night_schedule[0],
│   on ..\modules\automation\restartAppServiceDuringTheNight.tf line 25, in resource "azurerm_automation_schedule" "restart_app_service_during_the_night_schedule":
│   25: resource "azurerm_automation_schedule" "restart_app_service_during_the_night_schedule" {
```

### Expected Behaviour

The resource "azurerm_automation_schedule" should be created.

### Actual Behaviour

I receive the error specified before. I tried also to remove the "timezone" property, since there is a default value (UTC). I receive the same error with reference to UTC timezone.

### Steps to Reproduce

1. Create a resource group named "MyResourceGroup"
2. Create a Storage Account named "terraform12345"
3. Create a blob container named "tstate"
4. Create a configuration file like the one specified above.
5. terraform init
6. terraform apply

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by wuxu92**
whilst some platform/system does not provide full timezone information in the tzdata database, `time.LoadLocation()` will raise an error. this PR will cause the binary file size increase about <10kb by embeding the zip data of timezone into the built binary file.

reference https://github.com/golang/go/issues/38017 

resolves #20690.

### CODE REVIEW

File: internal/services/automation/automation_schedule_resource.go [hunk 1]
```diff
@@ -7,6 +7,9 @@ import (
 	"strings"
 	"time"
 
+	// import time/tzdata to embed timezone information in the program
+	_ "time/tzdata"
```
Comment (tombuildsstuff) [inline internal/services/automation/automation_schedule_resource.go:11]: could we link to the github issue this is fixing so we don't unintentionally remove this?

Comment (wuxu92) [reply internal/services/automation/automation_schedule_resource.go]: thanks for you suggestion, comment added. 🎉

**Review by katbyte — APPROVED** [review]
LGTM 🕙
