### PR TITLE
`azurerm_app_service_certificate` - introduce argument `app_service_plan_id` for usage with ASE

### LINKED ISSUE #11771: app_service_certificate not deploying properly and app_service_certificate_binding 404 error
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.46.0

### Affected Resource(s)

* `azurerm_app_service_certificate`
* `azurerm_app_service_certificate_binding`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_certificate" "app_cert" {
  name                                            = data.azurerm_key_vault_certificate.key_vault_certificate.name
  resource_group_name                 = var.resource_group_name
  location                                        = var.location
  hosting_environment_profile_id  = var.ase_id
  key_vault_secret_id                      = data.azurerm_key_vault_certificate.key_vault_certificate.id
}

resource "azurerm_app_service_certificate_binding" "cert_binding" {
  hostname_binding_id     = azurerm_app_service_custom_hostname_binding.hostname_binding.id
  certificate_id                   = azurerm_app_service_certificate.app_cert.id
  ssl_state                          = "SniEnabled"
}
```

### Debug Output

Error: Error creating/updating Custom Hostname Binding "testdomain.net" (App Service "TESTAPPSERVICE" / Resource Group "TESTRSG"): web.AppsClient#CreateOrUpdateHostNameBinding: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Certificate 82D...ADC was not found." Details=[{"Message":"Certificate 82D...ADC was not found."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","ExtendedCode":"04031","Message":"Certificate 82D...ADC was not found.","MessageTemplate":"Certificate {0} was not found.","Parameters":["82D...ADC"]}}]

### Expected Behaviour

Certificate should have been deployed to app_service and binding should have been successful

### Actual Behaviour

Certificate deploys, but `app_service_certificate_binding` is unable to see it.  Certificate also does not show up in the app_service.

### Steps to Reproduce

1. Deploy a valid app_service with ASE
2. Have a valid certificate and custom domain
2. `terraform apply`

### Important Factoids

If certificate is manually imported to the app_service and the thumbprint copied to terraform, the binding is successful.

### References

* #0000

### PR DESCRIPTION
**Pull request by haraldatbmw**
This PR introduces the argument app_service_plan_id to the resource azurerm_app_service_certificate and changes the attribute hosting_environment_profile_id to be computed.

The Azure SDK attribute hostingEnvironmentProfile is read-only and was never part of the REST API call for create or update a app_service_certificate.
**Azure SDK for go:** https://github.com/Azure/azure-sdk-for-go/blob/main/services/web/mgmt/2020-06-01/web/models.go#L7124
**Azure REST API:** https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-06-01/Certificates.json#L395

The new argument app_service_plan_id maps to the Azure SDK attribute serverFarmId which is required if an app-service-environment is in place.
**Azure REST API:** https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-06-01/Certificates.json#L430

fixes #11771

### CODE REVIEW

**Comment by haraldatbmw** [comment]
@jackofallops Please proceed your review here.

File: internal/services/web/app_service_certificate_resource.go [hunk 1]
```diff
@@ -166,10 +173,8 @@ func resourceAppServiceCertificateCreateUpdate(d *pluginsdk.ResourceData, meta i
 		Tags:     tags.Expand(t),
 	}
 
-	if len(hostingEnvironmentProfileId) > 0 {
-		certificate.CertificateProperties.HostingEnvironmentProfile = &web.HostingEnvironmentProfile{
-			ID: &hostingEnvironmentProfileId,
-		}
+	if appServicePlanId != "" {
+		certificate.CertificateProperties.ServerFarmID = &appServicePlanId
```
Comment (favoretti) [inline internal/services/web/app_service_certificate_resource.go:177]: Should we still be setting `hosting_environment_profile_id` together with the new option until 3.0?

Comment (haraldatbmw) [reply internal/services/web/app_service_certificate_resource.go:177]: I think this is still a valid computed attribute. Its filled with the app-service-environment ID. See REST API: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-06-01/Certificates.json#L395

**Comment by favoretti** [comment]
@haraldatbmw LGTM, still one of the maintainers needs to approve/have a look.

**Comment by adamyager** [comment]
@favoretti  are you able to approve this? Would be great to have this in the upcoming milestone. This has been broke for some time.

**Comment by favoretti** [comment]
@adamyager I'm sorry - I can't. But I see that @katbyte added it to the next release milestone.

**Comment by adamyager** [comment]
> @adamyager I'm sorry - I can't. But I see that @katbyte added it to the next release milestone.

I do see that. I appreciate it all!

**Comment by jackofallops** [comment]
Tests are looking good

**Review by jackofallops — APPROVED** [review]
Thanks @haraldatbmw - apologies for the delay in approval, this LGTM 👍
