### PR TITLE
`d/azurerm_shared_image_version`: Add semver sorting option

### LINKED ISSUE #13175: Data source azurerm_shared_image_version is not returning the actual latest version
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
 
- Terraform version: 1.0.5
- Azure provider version: 2.74.0

### Affected Resource(s)

* `data.azurerm_shared_image_version1st

### Terraform Configuration Files

```hcl
data "azurerm_shared_image_version" "latest" {
  name = "latest"
  gallery_name = azurerm_shared_image.example.gallery_name
  image_name = azurerm_shared_image.example.name
  resource_group_name = azurerm_shared_image.example.resource_group_name
}
```

### Debug Output
Since we have more than 20 images, the API return images in batches and a token to get the latest. However, the provider only find the latest in the first batch. This has been fixed in data source `azurerm_shared_image_versions` 

### Expected Behaviour
Return image of the latest

### Actual Behaviour
Return latest image in the first batch

### Steps to Reproduce

1. `terraform apply`

### References

* #8296
* #10374

### PR DESCRIPTION
**Pull request by favoretti**
TODO:
- [x] Add a set of unit tests for sorting function

Fixes #13175

### CODE REVIEW

File: internal/services/compute/helpers.go [hunk 1]
```diff
@@ -33,3 +37,25 @@ func flattenSubResourcesToIDs(input *[]compute.SubResource) []interface{} {
...
+			if err := recover(); err != nil {
+				log.Println("panic occurred:", err)
+				errors = append(errors, err.(error))
+			}
+		}()
+		verA, err := version.NewVersion(*values[i].Name)
+		verA = version.Must(verA, err)
+		verB, err := version.NewVersion(*values[j].Name)
+		verB = version.Must(verB, err)
+		return verA.LessThan(verB)
```
Comment (tombuildsstuff) [inline internal/services/compute/helpers.go:54]: we should remove the recover function here since we can default this:

```suggestion
		if values[i].Name == nil || values[j].Name == nil {
			return false, nil
		}

		verA, err := version.NewVersion(*values[i].Name)
		if err != nil {
			return false, nil
		}
		verA = version.Must(verA, err)
		
		verB, err := version.NewVersion(*values[j].Name)
		if err != nil {
			return false, nil
		}
		verB = version.Must(verB, err)
		return verA.LessThan(verB)
```

**Review by tombuildsstuff — COMMENTED** [review]
hey @favoretti 

Thanks for this PR - I've taken a look through and left a comment inline about the panic/recover - but if we can fix that up then this otherwise looks good to me 👍 

Thanks!

**Comment by katbyte** [comment]
we have a test failure: 
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccDataSourceSharedImageVersion_basic
=== PAUSE TestAccDataSourceSharedImageVersion_basic
=== CONT  TestAccDataSourceSharedImageVersion_basic

------- Stderr: -------
panic: Invalid address to set: []string{"sort_version_by_semver"}

goroutine 3741 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc003892e80, {0x60768a9, 0x16}, {0x55c0720, 0xae70b80})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:230 +0x2a5
github.com/hashicorp/terraform-provider-azurerm/internal/services/compute.dataSourceSharedImageVersionRead(0x68, {0x57402e0, 0xc003693500})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/compute/shared_image_version_data_source.go:124 +0x36d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x603e80b, {0x687bf78, 0xc002290800}, 0xc0039d80c0, {0x57402e0, 0xc003693500})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc001456380, {0x687bf78, 0xc002290800}, 0xc003892d80, {0x57402e0, 0xc003693500})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:569 +0xf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc002e10a20, {0x687bf78, 0xc002290800}, 0xc0018c96c0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:1133 +0x3a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000783800, {0x687c020, 0xc0032f9410}, 0xc00050c910)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:478 +0x37b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x5c99240, 0xc000783800}, {0x687c020, 0xc0032f9410}, 0xc0049aa540, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000337dc0, {0x68cbfa8, 0xc000600180}, 0xc003deaea0, 0xc00415daa0, 0xaee36b0, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000337dc0, {0x68cbfa8, 0xc000600180}, 0xc003deaea0, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:938 +0x294
```

**Comment by favoretti** [comment]
@katbyte oh, I see, I typoed apparently. Fixed, re-running tests.

**Comment by favoretti** [comment]
image

**Review by katbyte — APPROVED** [review]
Thanks @favoretti - LGTM 🚀
