### PR TITLE
`azurerm_service_plan` - fix CustomizeDiff

### LINKED ISSUE #30149: Not able to set zone_balancing_enabled to true, with sku_name EP1 even though it should work
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.11.3

### AzureRM Provider Version

4.36

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "service_plan" {
  name                = module.naming.app_service_plan.name
  resource_group_name = var.resource_group_name
  location            = local.location

  sku_name                     = "EP1"
  os_type                      = "Linux"
  zone_balancing_enabled       = true
  worker_count                 = 3
  per_site_scaling_enabled     = false
  maximum_elastic_worker_count = null

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
Error from CI/CD pipeline when running terraform plan 
Error: `zone_balancing_enabled` cannot be set to `true` when sku tier is not Premium
```

### Expected Behaviour

Expected is that setting zone_balancing_enabled to true is allowed when sku_name is equal to either EP1, EP2 or EP3 as these are premium azure versions

### Actual Behaviour

Error: `zone_balancing_enabled` cannot be set to `true` when sku tier is not Premium

Have tested with both EP1 and EP2, same issue

**Also noticed that this error started occuring during a scheduled run on 11/07/2025**

### Steps to Reproduce

1. Terraform init
2. Terraform plan using the terraform configuration showcased above
3. Error occurs

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by sreallymatt**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

- Fixes the CustomizeDiff that prevented SKUs other than Premium (P*) from specifying `zone_balancing_enabled` as true. 
- Clean up code

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

Failed test was due to an intermittent error that occurs with this test, reran:

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #30149 

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/appservice/helpers/service_plan.go [hunk 1]
```diff
@@ -8,26 +8,25 @@ import (
...
+	ServicePlanTypePremium         = "premium"
+	ServicePlanTypeWorkflow        = "workflow"
 )
 
 var appServicePlanSkus = []string{
 	"B1", "B2", "B3", // basic
 	"S1", "S2", "S3", // standard
-	"P1v2", "P2v2", "P3v2", // Premium V2
-	"P0v3", "P1v3", "P2v3", "P3v3", // Premium V3
-	"P1mv3", "P2mv3", "P3mv3", "P4mv3", "P5mv3", // Premium V3 memory optimized
```
Comment (sreallymatt) [inline internal/services/appservice/helpers/service_plan.go:30]: Note for whoever reviews this PR, these weren't removed as valid options, just removed from this slice since they're duplicated in the premium sku slice

**Review by mbfrahry — APPROVED** [review]
LGTM
