### PR TITLE
`azurerm_application_gate_way` - fix `url_path_map` constraint

### LINKED ISSUE #18064: default_backend in url_path_map in application_gateway is declared optional but throws error if you omit it
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

2.96.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "application_gateway" "agw"{
  ...
  url_path_map{
    # No default_backend_address_pool-name and default_backend_http_settings_name are provided
    ...
  }
  ...
}
```

### Debug Output/Panic Output

```shell
│ Error: creating/updating Application Gateway: (Name "agw" / Resource Group "rg"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayUrlPathMapMustSpecifyDefaultBackendHttpSettings" Message="UrlPathMap /subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/rg/providers/Microsoft.Network/applicationGateways/agw/urlPathMaps/urlpathmap must specify DefaultBackendHttpSettings." Details=[]
```

### Expected Behaviour

AGW is created with specified path_rules and without default_backend.

### Actual Behaviour

Error-message is shown and nothing is agw isn't created

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ziyeqf**
fixes #18064

Test
---
```
TF_ACC=1 go test -v ./internal/services/network -run=TestAccApplicationGateway_routingRedirect_pathBasedWithRedirection -timeout=600m
=== RUN   TestAccApplicationGateway_routingRedirect_pathBasedWithRedirection
=== PAUSE TestAccApplicationGateway_routingRedirect_pathBasedWithRedirection
=== CONT  TestAccApplicationGateway_routingRedirect_pathBasedWithRedirection
--- PASS: TestAccApplicationGateway_routingRedirect_pathBasedWithRedirection (1505.70s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       1505.717s
```

### CODE REVIEW

File: internal/services/network/application_gateway_resource_test.go [hunk 1]
```diff
@@ -5803,6 +5913,11 @@ provider "azurerm" {
 resource "azurerm_resource_group" "test" {
   name     = "acctestRG-%d"
   location = "%s"
+
+  tags = {
+    "SkipASMAzSecPack" = "true",
+    "SkipNRMSNSG"      = "true"
+  }
```
Comment (katbyte) [inline internal/services/network/application_gateway_resource_test.go:5920]: we shouldn't be committing these?

**Review by katbyte — APPROVED** [review]
other then one comment this LGTM 🏁

File: internal/services/network/application_gateway_resource_test.go (hunk 1 above)
Comment (ziyeqf) [reply internal/services/network/application_gateway_resource_test.go]: It should only work on our internal subscription, so I think it's better to remove these.
