### PR TITLE
`azurerm_function_app` - fix regressions in function app storage

### LINKED ISSUE #13536: New file share added to function when using azurerm 2.77.0 or greater
### Terraform (and AzureRM Provider) Version
Terraform version 1.0.7
Azurerm version 2.77.0

### Affected Resource(s)

azurerm_function_app

* `azurerm_XXXXX`

### Terraform Configuration Files

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "= 2.77.0"
    }
  }
}

provider azurerm {
    features {}
}

### Resource Groups
resource azurerm_resource_group rg {
  name     = "azurerm-issue-rg"
  location = "centralus"
}

### Service plans
resource azurerm_app_service_plan asp {
    name                = "ep1-asp-01"
    location            = azurerm_resource_group.rg.location
    resource_group_name = azurerm_resource_group.rg.name
    kind                = "elastic"

    sku {
      tier     = "ElasticPremium"
      size     = "EP1"
      capacity = 1
    }
}

resource azurerm_storage_account storage_account {
  name                     = "azurermfuncapp"
  location                 = azurerm_resource_group.rg.location
  resource_group_name      = azurerm_resource_group.rg.name
  account_tier             = "Standard"
  account_replication_type = "LRS"
  tags = {
    "type" = "function"
  }
}

resource azurerm_function_app app {
  name                       = "azurerm-func-app-9282021"
  location                   = azurerm_resource_group.rg.location
  resource_group_name        = azurerm_resource_group.rg.name
  app_service_plan_id        = azurerm_app_service_plan.asp.id
  storage_account_name       = azurerm_storage_account.storage_account.name
  storage_account_access_key = azurerm_storage_account.storage_account.primary_access_key
  version                    = "~3"

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output

The above configuration, along with version 2.77.00 will add the following two file shares to the Azure Function Storage.
azurerm-func-app-92820215d13
azurerm-func-app-9282021ff36

I would have expected to see only one file share with the name (which is what azurerm 2.76.00 produces)
azurerm-func-app-9282021-content

I believe that this issue may have been introduced with the change for https://github.com/hashicorp/terraform-provider-azurerm/pull/13349

### LINKED ISSUE #13566: azurerm_function_app throws error when upgrading from 2.76.0 to 2.77.0
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `Terraform v1.0.7`
* `azurerm v2.77.0`

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.0.7"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.77.0"
    }
  }
}
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "fun-rg" {
  name     = "fun-rg"
  location = "westeurope"
}

resource "azurerm_storage_account" "store0127u" {
  name                     = "store0127u"
  resource_group_name      = azurerm_resource_group.fun-rg.name
  location                 = azurerm_resource_group.fun-rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  network_rules {
    default_action = "Deny"
  }
}

resource "azurerm_app_service_plan" "fun-plan" {
  name                = "fun-plan"
  resource_group_name = azurerm_resource_group.fun-rg.name
  location            = azurerm_resource_group.fun-rg.location
  kind                = "elastic"
  reserved            = true

  sku {
    tier = "ElasticPremium"
    size = "EP1"
  }
}

resource "azurerm_function_app" "fun-function-app" {
  name                       = "fun-function-app"
  resource_group_name        = azurerm_resource_group.fun-rg.name
  location                   = azurerm_resource_group.fun-rg.location
  app_service_plan_id        = azurerm_app_service_plan.fun-plan.id
  storage_account_name       = azurerm_storage_account.store0127u.name
  storage_account_access_key = azurerm_storage_account.store0127u.primary_access_key
  os_type                    = "linux"
}
```

### Debug Output

While looking at the logs I found the following relevant difference between the 2.77.0 run and the 2.76.0 run.
```
2.77.0
"appSettings": [
                {
                    "name": "AzureWebJobsStorage",
                    "value": "DefaultEndpointsProtocol=https;AccountName=store0127u;AccountKey=<key>;EndpointSuffix=core.windows.net"
                },
                {
                    "name": "FUNCTIONS_EXTENSION_VERSION",
                    "value": "~1"
                },
                {
                    "name": "AzureWebJobsDashboard",
                    "value": "DefaultEndpointsProtocol=https;AccountName=store0127u;AccountKey=<key>;EndpointSuffix=core.windows.net"
                },
                {
                    "name": "WEBSITE_CONTENTSHARE",
                    "value": "fun-function-app7431"
                },
                {
                    "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
                    "value": "DefaultEndpointsProtocol=https;AccountName=store0127u;AccountKey=<key>;EndpointSuffix=core.windows.net"
                }
            ]
```
```
2.76.0
"appSettings": [
                {
                    "name": "AzureWebJobsStorage",
                    "value": "DefaultEndpointsProtocol=https;AccountName=store0127u;AccountKey=<key>;EndpointSuffix=core.windows.net"
                },
                {
                    "name": "FUNCTIONS_EXTENSION_VERSION",
                    "value": "~1"
                },
                {
                    "name": "AzureWebJobsDashboard",
                    "value": "DefaultEndpointsProtocol=https;AccountName=store0127u;AccountKey=<key>;EndpointSuffix=core.windows.net"
                }
            ]
```

### Expected Behaviour

Configuration is applied without error.

### Actual Behaviour

Terraform throws the following error:

Error: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Creation of storage file share failed with: 'The remote server returned an error: (403) Forbidden.'. Please check if the storage account is accessible." Details=[{"Message":"Creation of storage file share failed with: 'The remote server returned an error: (403) Forbidden.'. Please check if the storage account is accessible."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"99022","Message":"Creation of storage file share failed with: 'The remote server returned an error: (403) Forbidden.'. Please check if the storage account is accessible.","MessageTemplate":"Creation of storage file share failed with: '{0}'. Please check if the storage account is accessible.","Parameters":["The remote server returned an error: (403) Forbidden."]}}]

### Steps to Reproduce

1. `terraform apply` --> error
2. change `azurerm` to version `2.76.0`
3. `terraform init -upgrade`
4. `terraform apply` --> no error

### Important Factoids

It seems that `2.77.0` automatically sets `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`, while `2.76.0` does not do it. According to this [comment](https://github.com/Azure/Azure-Functions/issues/1361#issuecomment-571700656) not setting `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` allows to deploy a Premium Plan when the network access to the storage account is restricted.

I think this new behaviour was introduced with #13349.

To conclude, is my error a bug or expected behavior? If it is expected behavior, any ideas how to make my config work in `2.77.0`? I tried to set  `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` explicitly to empty strings, but the log shows that they get overwritten.

### PR DESCRIPTION
**Pull request by jackofallops**
fixes #13536 
fixes #13566

### CODE REVIEW

File: internal/services/web/function_app.go [hunk 1]
```diff
@@ -356,7 +350,7 @@ func getBasicFunctionAppAppSettings(d *pluginsdk.ResourceData, appServiceTier, e
 	// On consumption and premium plans include WEBSITE_CONTENT components, unless it's a Linux consumption plan
 	// (see https://github.com/Azure/azure-functions-python-worker/issues/598)
 	if !(strings.EqualFold(appServiceTier, "dynamic") && strings.EqualFold(d.Get("os_type").(string), "linux")) &&
-		(strings.EqualFold(appServiceTier, "dynamic") || strings.HasPrefix(strings.ToLower(appServiceTier), "elastic")) {
```
Comment (mbfrahry) [inline internal/services/web/function_app.go:359]: Just looking to confirm that we don't need to check for `elastic` anymore? Is there any chance someone has that still?

**Review by mbfrahry — APPROVED** [review]
LGTM! Just looking for a confirmation on one piece that is being removed

File: internal/services/web/function_app.go (hunk 1 above)
Comment (shibayan) [reply internal/services/web/function_app.go:359]: As far as I know, Azure Files is only required for Consumption (Windows) and Elastic Premium (Windows / Linux). I think it is correct to leave this conditional expression as `elastic`. See also https://github.com/hashicorp/terraform-provider-azurerm/pull/13218#issuecomment-913755737

Comment (jackofallops) [reply internal/services/web/function_app.go:359]: Hi both, from the [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentshare):
> Only used when deploying to a Premium plan or to a Consumption plan running on Windows. Not supported for Consumptions plans running Linux.

I initially misinterpreted this as ElasticPremium also, however, this is actually App Service Premium Plans. For context see #13566.

Comment (shibayan) [reply internal/services/web/function_app.go:359]: This is very confusing, but the Premium V2 / V3 of the App Service Plan and the Azure Functions Premium Plan are completely different services. The Premium Plan in this document refers to the latter.

If the File Share setting is added to the App Service Plan (Premium V2 / V3), the current working application may be lost. This is a very dangerous change and the application I manage is also affected.

Comment (jackofallops) [reply internal/services/web/function_app.go:359]: > This is very confusing,

You are not wrong there. 🙃 

The resource has always previously sent the content details for premium SKU's, and elasticpremium plans [see here](https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.76.0/internal/services/web/function_app.go#L334)

The change in 2.77 was intended to align the resource behaviour with the docs, but appears to have created the issue in 13218 where these settings were being sent where they had previously not been. Are you reporting that the Premium plans did _not_ get these settings as intended?


The other change in this PR addresses the change of setting for the share directory, which is a bug in the 2.77 implementation which attempted to maintain any existing value configured. (see 13536) If the property already exists in the Function App AppSettings, then it will be used and not added/created. Additionally this is intended to address a related bug whereby the provider created the share with a `-content` suffix that prevented proper operation of slots. This will also mean that if the share property is set for a Premium Plan, it will be honoured/maintained and not overwritten.

Comment (shibayan) [reply internal/services/web/function_app.go:359]: As for #13566, it is different from this issue.

Azure Functions has an option to operate without File Share, so I think it's more appropriate to add a property (e.g. `disabled_builtin_file_share` or etc) to not auto-set `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`.

https://docs.microsoft.com/en-us/azure/azure-functions/storage-considerations#create-an-app-without-azure-files

Comment (jackofallops) [reply internal/services/web/function_app.go:359]: Thanks for your insight @shibayan - I'm taking this back to the drawing board to work it back through...

Comment (jackofallops) [reply internal/services/web/function_app.go:359]: I've updated to correct the behaviour for PremiumV2/V3 (i.e. not send) and added the reuse of an existing value if defined (in case users do have it defined).  I believe this is going to be sufficient for this stage, as presently this resource is not usable since 2.77 because of the share recreation bug. I'm reticent to introduce another property at this stage that will further affect behaviour of the resource. Upon re-reading, I believe 13566 to be a symptom of the share recreation bug, so should be resolved by this PR in any case.

fwiw - I'm in the process of completely rewriting this resource for the beta / v3.0, so I've made notes for addressing this properly there. I'll also be speaking to the Service Team on this as soon as possible.

Comment (shibayan) [reply internal/services/web/function_app.go:359]: Thank you for the quick response. I've checked the changed code and I'm sure it works ideally with Provider v2.x.

**Review by mbfrahry — APPROVED** [review]

**Comment by jackofallops** [comment]
Tests looking OK, (2 transient / unrelated failures)
image
