### PR TITLE
azurerm_machine_learning_compute_cluster change subnet_resource_id constraint: Respect Managed Vnet when creating compute clusters fixes #25901 

### LINKED ISSUE #25901: azurerm_machine_learning_compute_cluster  subnet_resource_id should be optional, even though node_public_ip_enabled is false
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.2

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

azurerm_machine_learning_compute_cluster

### Terraform Configuration Files

```hcl
esource "azurerm_machine_learning_compute_cluster" "default_compute_cluster" {
  name                          = var.default_compute_cluster_name
  location                      = var.location
  vm_priority                   = "Dedicated"
  vm_size                       = var.default_compute_cluster_vm_size
  machine_learning_workspace_id = azurerm_machine_learning_workspace.mlw.id

  node_public_ip_enabled    = false
  ssh_public_access_enabled = false

  scale_settings {
    min_node_count                       = 0
    max_node_count                       = 4
    scale_down_nodes_after_idle_duration = "PT3600S" # 3600 seconds
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
Error: `subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false`
```

### Expected Behaviour

Since we are in a private networking scenario with a Managed VNET I don't have to provide the subnetid in the Azure MLW UI. 

I have created a compute cluster manually in my scenario via Azure UI and it says subnetid NULL and       "enableNodePublicIp": false
```

`  "id": ".../subscriptions/xxx/d-cpu-ds11",
  "name": "d-cpu-ds11",
  "type": "Microsoft.MachineLearningServices/workspaces/computes",
  "location": "westeurope",
  "tags": {},
  "identity": {
    "type": "SystemAssigned",
    "principalId": "xx-acf2-4c56-9e8b-xx",
    "tenantId": "xx-6509-4014-9859-xx"
  },
  "properties": {
    "createdOn": "2024-04-08T13:38:57.6595494+00:00",
    "modifiedOn": "2024-04-08T13:47:46.1190125+00:00",
    "disableLocalAuth": true,
    "description": null,
    "resourceId": null,
    "computeType": "AmlCompute",
    "computeLocation": "westeurope",
    "provisioningState": "Succeeded",
    "provisioningErrors": null,
    "provisioningWarnings": {},
    "isAttachedCompute": false,
    "properties": {
      "vmSize": "Standard_DS11_v2",
      "vmPriority": "Dedicated",
      "scaleSettings": {
        "maxNodeCount": 1,
        "minNodeCount": 0,
        "nodeIdleTimeBeforeScaleDown": "PT2M"
      },
      "subnet": null,
      "currentNodeCount": 0,
      "targetNodeCount": 0,
      "nodeStateCounts": {
        "preparingNodeCount": 0,
        "runningNodeCount": 0,
        "idleNodeCount": 0,
        "unusableNodeCount": 0,
        "leavingNodeCount": 0,
        "preemptedNodeCount": 0
      },
      "allocationState": "Steady",
      "allocationStateTransitionTime": "2024-04-22T09:39:29.695+00:00",
      "errors": null,
      "remoteLoginPortPublicAccess": "Disabled",
      "osType": "Linux",
      "virtualMachineImage": null,
      "isolatedNetwork": false,
      "enableNodePublicIp": false,
      "enableBatchPrivateLink": false,
      "propertyBag": {}
    }
  }
}

```

### Actual Behaviour

Error: `subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false`

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by hmrc87**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

When a Managed Vnet Setup as described in [the Microsoft documentation](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/machine-learning/how-to-managed-network.md ) is used a compute cluster can have NO public IP and we don't need to provide a subnet_resource_id since this is managed by Microsoft.

I have tested this setup by creating a compute cluster via cli/sdk and also querying an existing compute cluster. I both cases the subnet_ressource_id can be / was empty/null.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Change Log

* `azurerm_machine_learning_compute_cluster` - subnet_ressource_id is not mandatory when node_public_ip_enabled if in a managed vnet sceenario [GH-25901]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25901

### CODE REVIEW

File: internal/services/machinelearning/machine_learning_compute_cluster_resource.go [hunk 1]
```diff
@@ -171,21 +170,41 @@ func resourceComputeClusterCreate(d *pluginsdk.ResourceData, meta interface{}) e
...
 		}
 	}
-	if !response.WasNotFound(existing.HttpResponse) {
-		return tf.ImportAsExistsError("azurerm_machine_learning_compute_cluster", id.ID())
-	}
 
-	if !d.Get("node_public_ip_enabled").(bool) && d.Get("subnet_resource_id").(string) == "" {
-		return fmt.Errorf("`subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false`")
+	if !d.Get("node_public_ip_enabled").(bool) && d.Get("subnet_resource_id").(string) == "" && *workspaceModel.Properties.ManagedNetwork.Status.Status != workspaces.ManagedNetworkStatusActive {
+		return fmt.Errorf("`subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false` if the workspace is not in a managed network")
```
Comment (stephybun) [inline internal/services/machinelearning/machine_learning_compute_cluster_resource.go:207]:
```suggestion
		return fmt.Errorf("`subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false` or the workspace is not in a managed network")
```

File: internal/services/machinelearning/machine_learning_compute_cluster_resource.go [hunk 2]
```diff
@@ -171,21 +170,41 @@ func resourceComputeClusterCreate(d *pluginsdk.ResourceData, meta interface{}) e
...
 			return fmt.Errorf("checking for presence of existing %s: %+v", id, err)
 		}
 	}
-	if !response.WasNotFound(existing.HttpResponse) {
-		return tf.ImportAsExistsError("azurerm_machine_learning_compute_cluster", id.ID())
-	}
 
-	if !d.Get("node_public_ip_enabled").(bool) && d.Get("subnet_resource_id").(string) == "" {
-		return fmt.Errorf("`subnet_resource_id` must be set if `node_public_ip_enabled` is set to `false`")
+	if !d.Get("node_public_ip_enabled").(bool) && d.Get("subnet_resource_id").(string) == "" && *workspaceModel.Properties.ManagedNetwork.Status.Status != workspaces.ManagedNetworkStatusActive {
```
Comment (stephybun) [inline internal/services/machinelearning/machine_learning_compute_cluster_resource.go:206]: There's a potential crash here, we should nil check `Properties`, `ManagedNetwork` and `Status` before comparing the value.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @hmrc87. Although part of the code was just moved from what already existed I left a couple of suggestions on the error messages which would be good to update so that they're more consistent with the rest of the provider. We also need to add some more nil checks. Once that's been fixed up we can run the tests and see if this is ready to go!

File: internal/services/machinelearning/machine_learning_compute_cluster_resource.go (hunk 2 above)
Comment (hmrc87) [reply internal/services/machinelearning/machine_learning_compute_cluster_resource.go]: added additional checks to prevent this from happening.

File: internal/services/machinelearning/machine_learning_compute_cluster_resource.go [hunk 3]
```diff
@@ -171,21 +170,60 @@ func resourceComputeClusterCreate(d *pluginsdk.ResourceData, meta interface{}) e
...
+	}
+
 	existing, err := client.ComputeGet(ctx, id)
 	if err != nil {
 		if !response.WasNotFound(existing.HttpResponse) {
 			return fmt.Errorf("checking for presence of existing %s: %+v", id, err)
 		}
 	}
-	if !response.WasNotFound(existing.HttpResponse) {
-		return tf.ImportAsExistsError("azurerm_machine_learning_compute_cluster", id.ID())
```
Comment (stephybun) [inline internal/services/machinelearning/machine_learning_compute_cluster_resource.go:184]: Looks like this might have been removed accidentally? We need to add this back in or the `requiresImport` test fails.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @hmrc87, I overlooked the removal of the import required error message. Could you add that back in? Should fix the test failure that I'm seeing.

**Comment by hmrc87** [comment]
@stephybun  I will fix all the linter and tests errors asap

**Review by stephybun — APPROVED** [review]
Fantastic, thanks @hmrc87 LGTM 👍
