### PR TITLE
`azurerm_mssql_server` - fix panic due to unknown value

### LINKED ISSUE #28948: The terraform-provider-azurerm_v4.21.1_x5.exe plugin crashed
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.11.0

### AzureRM Provider Version

4.21.1

### Affected Resource(s)/Data Source(s)

azurerm_mssql_server

### Terraform Configuration Files

```hcl
https://github.com/golfalot/terraform-bug-report-01
```

### Debug Output/Panic Output

```shell
(base) PS D:\source\repos-vscode\Infrastructure-nonprod\nonprod-transacting> terraform init -upgrade
Initializing the backend...
Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "~> 4.19"...
- Finding latest version of hashicorp/random...
- Finding latest version of hashicorp/null...
- Installing hashicorp/azurerm v4.21.1...
- Installed hashicorp/azurerm v4.21.1 (signed by HashiCorp)
- Using previously-installed hashicorp/random v3.7.1
- Using previously-installed hashicorp/null v3.2.3
Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
(base) PS D:\source\repos-vscode\Infrastructure-nonprod\nonprod-transacting> terraform plan
data.azurerm_subscription.current: Reading...

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform planned the following actions, but then encountered a problem:

  # azurerm_resource_group.rg_sql will be created
  + resource "azurerm_resource_group" "rg_sql" {
      + id       = (known after apply)
      + location = "uksouth"
      + name     = "rg-sql-transacting-nonprod-uksouth"
    }

  # random_password.sql_admin_password will be created
  + resource "random_password" "sql_admin_password" {
      + bcrypt_hash      = (sensitive value)
      + id               = (known after apply)
      + length           = 16
      + lower            = true
      + min_lower        = 0
      + min_numeric      = 0
      + min_special      = 0
      + min_upper        = 0
      + number           = true
      + numeric          = true
      + override_special = "_%@"
      + result           = (sensitive value)
      + special          = true
      + upper            = true
    }

  # random_string.sql_username_suffix will be created
  + resource "random_string" "sql_username_suffix" {
      + id          = (known after apply)
      + length      = 8
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + numeric     = true
      + result      = (known after apply)
      + special     = false
      + upper       = false
    }

Plan: 3 to add, 0 to change, 0 to destroy.
╷
│ Error: Plugin did not respond
│
│   with data.azurerm_subscription.current,
│   on providers.tf line 20, in data "azurerm_subscription" "current":
│   20: data "azurerm_subscription" "current" {}
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_mssql_server.sql,
│   on sql_server.tf line 6, in resource "azurerm_mssql_server" "sql":
│    6: resource "azurerm_mssql_server" "sql" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v4.21.1_x5.exe plugin:

panic: value is unknown

goroutine 77 [running]:
github.com/hashicorp/go-cty/cty.Value.AsString({{{0x8b3ee68?, 0xc00000a821?}}, {0x72a24a0?, 0xdcb9be0?}})
        github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:1179 +0xf8
github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql.msSqlAdministratorLoginPassword({0x0?, 0x0?}, 0xc003088e00, {0x0?, 0x0?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql/mssql_server_resource.go:766 +0x9b
github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql.resourceMsSqlServer.CustomizeDiffShim.func8({0x8b3a168?, 0xc00308edb0?}, 0x0?, {0x729cb00?, 0xc00200a908?})
        github.com/hashicorp/terraform-provider-azurerm/internal/tf/pluginsdk/shim.go:18 +0x2c
github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql.resourceMsSqlServer.CustomDiffWithAll.func9({0x8b3a168, 0xc00308edb0}, 0xc003088e00, {0x729cb00, 0xc00200a908})
        github.com/hashicorp/terraform-provider-azurerm/internal/tf/pluginsdk/customize_diff.go:30 +0xab
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc00150b290, {0x8b3a168, 0xc00308edb0}, 0xc001710f70, 0xc00180a410, 0xc001219020, {0x729cb00, 0xc00200a908}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.0/helper/schema/schema.go:710 +0x4b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x8b3dc78?, {0x8b3a168?, 0xc00308edb0?}, 0xc001710f70, 0xc00308ede0?, {0x729cb00?, 0xc00200a908?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.0/helper/schema/resource.go:1022 +0xdb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc000c08108, {0x8b3a168?, 0xc00308ecc0?}, 0xc00180a230)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.0/helper/schema/grpc_provider.go:890 +0xbce
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).PlanResourceChange(0xc0002a0000, {0x8b3a168?, 0xc00308e9f0?}, 0xc00180a230)
        github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_PlanResourceChange.go:73 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc001a641e0, {0x8b3a168?, 0xc00308e180?}, 0xc00309c080)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/tf5server/server.go:826 +0x3f0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x808cc80, 0xc001a641e0}, {0x8b3a168, 0xc00308e180}, 0xc00309c000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:593 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007ea200, {0x8b3a168, 0xc00308e120}, 0xc002d800c0, 0xc001ed3530, 0xdc22a80, 0x0)
        google.golang.org/grpc@v1.69.4/server.go:1392 +0xfd2
google.golang.org/grpc.(*Server).handleStream(0xc0007ea200, {0x8b3de70, 0xc001c96b60}, 0xc002d800c0)
        google.golang.org/grpc@v1.69.4/server.go:1802 +0xbaa
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.69.4/server.go:1030 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 47
        google.golang.org/grpc@v1.69.4/server.go:1041 +0x125

Error: The terraform-provider-azurerm_v4.21.1_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

no crash

### Actual Behaviour

Error: The terraform-provider-azurerm_v4.21.1_x5.exe plugin crashed!

### Steps to Reproduce

1. clone repo
2. set valid subscription id and name in variables.tf
3. terraform init -upgrade
4. terraform plan

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by sreallymatt**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

- Removed `AsString()` function call on a value that may be unknown causing a panic
- Added a validateFunc that replaces the empty string check in the CustomizeDiff for `administrator_login`
- Modified tests to force an unknown value during planning phase
- Add required ExternalProviders config and replace duplicated TF config with a template func

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

WO tests:
```
--- PASS: TestAccMsSqlServer_writeOnlyAdminLoginPassword (1022.58s)
--- PASS: TestAccMsSqlServer_updateToWriteOnlyPassword (1255.39s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql 1257.253s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_mssql_server` - prevent panic by removing function call on a value that may be unknown [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #28948

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by mbfrahry — APPROVED** [review]
LGTM!

File: internal/services/mssql/mssql_server_resource.go [hunk 1]
```diff
@@ -84,6 +84,7 @@ func resourceMsSqlServer() *pluginsdk.Resource {
 				Computed:     true,
 				ForceNew:     true,
 				AtLeastOneOf: []string{"administrator_login", "azuread_administrator.0.azuread_authentication_only"},
+				ValidateFunc: validation.StringIsNotWhiteSpace,
```
Comment (stephybun) [inline internal/services/mssql/mssql_server_resource.go:87]: Is there a particular reason you've gone with `StringIsNotWhiteSpace` over `StringIsNotEmpty`

Comment (sreallymatt) [reply internal/services/mssql/mssql_server_resource.go:87]: It seems like the more "complete" validation check for non-empty values, I can change it to `StringIsNotEmpty` if that's what we prefer, WDYT?

Comment (stephybun) [reply internal/services/mssql/mssql_server_resource.go:87]: put it in the notes 👍 🗒️

**Review by stephybun — APPROVED** [review]
Thanks @sreallymatt LGTM 🦀
