### PR TITLE
`azurerm_linux_web_app_slot` - fix ignored `worker_count` argument in `site_config` block

### LINKED ISSUE #24678: `azurerm_linux_web_app_slot` ignores `worker_count` parameter in site_config block
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.1

### AzureRM Provider Version

3.89.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app_slot

### Terraform Configuration Files

```hcl
resource "random_integer" "ri" {
  min = 10000
  max = 99999
}

# Create the resource group
resource "azurerm_resource_group" "rg" {
  name     = "myResourceGroup-${random_integer.ri.result}"
  location = "westeurope"
}

# Create the Linux App Service Plan
resource "azurerm_service_plan" "appserviceplan" {
  name                     = "webapp-asp-${random_integer.ri.result}"
  location                 = azurerm_resource_group.rg.location
  resource_group_name      = azurerm_resource_group.rg.name
  os_type                  = "Linux"
  sku_name                 = "P1v3"
  per_site_scaling_enabled = true
  worker_count             = 2
}

# Create the web app, pass in the App Service Plan ID
resource "azurerm_linux_web_app" "webapp" {
  name                = "webapp-${random_integer.ri.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  service_plan_id     = azurerm_service_plan.appserviceplan.id
  https_only          = true
  site_config {
    minimum_tls_version = "1.2"
    worker_count        = 2
  }
}

resource "azurerm_linux_web_app_slot" "webapp_slot" {
  name           = "webapp-staging-${random_integer.ri.result}"
  app_service_id = azurerm_linux_web_app.webapp.id
  site_config {
    minimum_tls_version = "1.2"
    worker_count        = 2
  }
}
```

### Debug Output/Panic Output

PUT request to Azure for the slot:

```shell
PUT /subscriptions/SUBSCRIPTION/resourceGroups/myResourceGroup-42718/providers/Microsoft.Web/sites/webapp-42718/slots/webapp-staging-42718?api-version=2022-09-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.21.3 (arm64-linux) go-autorest/v14.2.1 tombuildsstuff/kermit/v0.20230703.1101016 web/2022-09-01 HashiCorp Terraform/1.7.1 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/3.89.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 876
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: CORRELATION_ID
Accept-Encoding: gzip

{"identity":{"type":"None"},"location":"West Europe","properties":{"clientAffinityEnabled":false,"clientCertEnabled":false,"clientCertMode":"Required","enabled":true,"httpsOnly":false,"publicNetworkAccess":"Enabled","serverFarmId":"/subscriptions/SUBSCRIPTION/resourceGroups/myResourceGroup-42718/providers/Microsoft.Web/serverFarms/webapp-asp-42718","siteConfig":{"acrUseManagedIdentityCreds":false,"alwaysOn":true,"autoHealEnabled":false,"ftpsState":"Disabled","http20Enabled":false,"loadBalancing":"LeastRequests","localMySqlEnabled":false,"managedPipelineMode":"Integrated","minTlsVersion":"1.2","publicNetworkAccess":"Enabled","remoteDebuggingEnabled":false,"scmIpSecurityRestrictionsUseMain":false,"scmMinTlsVersion":"1.2","use32BitWorkerProcess":true,"vnetRouteAllEnabled":false,"webSocketsEnabled":false},"vnetRouteAllEnabled":false},"tags":{}}: timestamp="2024-01-29T11:26:13.124+0100"
```
Payload: 

```json
{
  "identity": {
    "type": "None"
  },
  "location": "West Europe",
  "properties": {
    "clientAffinityEnabled": false,
    "clientCertEnabled": false,
    "clientCertMode": "Required",
    "enabled": true,
    "httpsOnly": false,
    "publicNetworkAccess": "Enabled",
    "serverFarmId": "/subscriptions/SUBSCRIPTION/resourceGroups/myResourceGroup-42718/providers/Microsoft.Web/serverFarms/webapp-asp-42718",
    "siteConfig": {
      "acrUseManagedIdentityCreds": false,
      "alwaysOn": true,
      "autoHealEnabled": false,
      "ftpsState": "Disabled",
      "http20Enabled": false,
      "loadBalancing": "LeastRequests",
      "localMySqlEnabled": false,
      "managedPipelineMode": "Integrated",
      "minTlsVersion": "1.2",
      "publicNetworkAccess": "Enabled",
      "remoteDebuggingEnabled": false,
      "scmIpSecurityRestrictionsUseMain": false,
      "scmMinTlsVersion": "1.2",
      "use32BitWorkerProcess": true,
      "vnetRouteAllEnabled": false,
      "webSocketsEnabled": false
    },
    "vnetRouteAllEnabled": false
  },
  "tags": {}
}
```

### Expected Behaviour

The resulting `azurerm_linux_web_app_slot` in Azure should have a `worker_count` of 2.

### Actual Behaviour

The resulting `azurerm_linux_web_app_slot` in Azure has a default `worker_count` of 1:

```shell 
$ az webapp deployment slot list --resource-group myResourceGroup-42718 --name webapp-42718  | jq '.[] | select(.name=="webapp-staging-42718") | .siteConfig.numberOfWorkers'

1
```

When running `terraform plan` directly after the `apply` it will always show differences:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_linux_web_app_slot.webapp_slot will be updated in-place
  ~ resource "azurerm_linux_web_app_slot" "webapp_slot" {
        id                                             = "/subscriptions/SUBSCRIPTION/resourceGroups/myResourceGroup-42718/providers/Microsoft.Web/sites/webapp-42718/slots/webapp-staging-42718"
        name                                           = "webapp-staging-42718"
        tags                                           = {}
        # (20 unchanged attributes hidden)

      ~ site_config {
          ~ worker_count                            = 1 -> 2
            # (20 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`
3.  The plan will output changes in the `worker_count`

### Important Factoids

Notice the `NumberOfWorkers` parameter is missing from the `siteConfig` block in the debug output. I think the missing parameter is the cause of this issue. I've created PR #24515 which solves the issue in my testing. 

### References
Documentation:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app_slot#worker_count

Related PR:
#24515

### PR DESCRIPTION
**Pull request by dkanbier**
Currently the [`worker_count`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app_slot#worker_count) argument in the `site_config` block on `azurerm_linux_web_app_slot` seems to get ignored when the resource is created:

```
resource "azurerm_linux_web_app_slot" "example" {
  name           = "example-slot"
  app_service_id = azurerm_linux_web_app.example.id

  site_config {
    worker_count = 2
  }
}
```
Running `terraform apply` on this code will show no issues and finish successfully. The resulting slot will have a `worker_count` of `1` however, which you can check via the JSON View of the slot in the Azure Portal.

Re-running a `terraform plan` directly after the `terraform apply` will show differences:

```
      ~ site_config {
          ~ worker_count                            = 1 -> 2
```

While debugging I discovered the `NumberOfWorkers` argument is simply missing from the AzureRM API call to Azure when the `azurerm_linux_web_app_slot` resource gets created. 

I think this is because it is never added to the expanded arguments. 

The goal of this PR is to remedy this, by adding the `NumberOfWorkers` to the expanded arguments. This causes the resulting slot to have the correct number of workers.

Unit tests:

```
=== RUN   TestAccLinuxWebAppSlot_complete
=== PAUSE TestAccLinuxWebAppSlot_complete
=== RUN   TestAccLinuxWebAppSlot_completeUpdate
=== PAUSE TestAccLinuxWebAppSlot_completeUpdate
=== CONT  TestAccLinuxWebAppSlot_complete
=== CONT  TestAccLinuxWebAppSlot_completeUpdate
--- PASS: TestAccLinuxWebAppSlot_complete (152.51s)
--- PASS: TestAccLinuxWebAppSlot_completeUpdate (221.91s)
PASS
```
fixes #24678

### CODE REVIEW

**Comment by dkanbier** [comment]
Fixes #24678

**Comment by sven5** [comment]
When will this one be merged?

File: internal/services/appservice/helpers/web_app_slot_schema.go [hunk 1]
```diff
@@ -666,6 +666,10 @@ func (s *SiteConfigLinuxWebAppSlot) ExpandForCreate(appSettings map[string]strin
 		expanded.RemoteDebuggingVersion = pointer.To(s.RemoteDebuggingVersion)
 	}
 
+	if s.WorkerCount != 0 {
+		expanded.NumberOfWorkers = pointer.To(int32(s.WorkerCount))
```
Comment (jackofallops) [inline internal/services/appservice/helpers/web_app_slot_schema.go:670]: Due to a recent API update, this is now an `int64` so would need to be:
```suggestion
		expanded.NumberOfWorkers = pointer.To(s.WorkerCount)
```

File: internal/services/appservice/helpers/web_app_slot_schema.go [hunk 2]
```diff
@@ -815,6 +819,10 @@ func (s *SiteConfigLinuxWebAppSlot) ExpandForUpdate(metadata sdk.ResourceMetaDat
 		expanded.HealthCheckPath = pointer.To(s.HealthCheckPath)
 	}
 
+	if metadata.ResourceData.HasChange("site_config.0.worker_count") {
+		expanded.NumberOfWorkers = pointer.To(int32(s.WorkerCount))
```
Comment (jackofallops) [inline internal/services/appservice/helpers/web_app_slot_schema.go:823]: Similarly here:
```suggestion
		expanded.NumberOfWorkers = pointer.To(s.WorkerCount)
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @dkanbier - Thanks for this PR, and for the catch on the missing property. Due to a recent change in the SDK, this property is now an `int64` type, so no longer requires casting. If you can update, we can get the tests run and hopefully get this merged when they pass.

Thanks!

File: internal/services/appservice/helpers/web_app_slot_schema.go (hunk 1 above)
Comment (dkanbier) [reply internal/services/appservice/helpers/web_app_slot_schema.go]: @jackofallops  thank you for your reply. I've updated the PR with your suggestions.

File: internal/services/appservice/helpers/web_app_slot_schema.go (hunk 2 above)
Comment (dkanbier) [reply internal/services/appservice/helpers/web_app_slot_schema.go]: @jackofallops  thank you for your reply. I've updated the PR with your suggestions.

**Comment by dkanbier** [comment]
> Hi @dkanbier - Thanks for this PR, and for the catch on the missing property. Due to a recent change in the SDK, this property is now an `int64` type, so no longer requires casting. If you can update, we can get the tests run and hopefully get this merged when they pass.
> 
> Thanks!

Hi @jackofallops , I've applied your suggested changes and tried rebuilding the module but it fails:

```
internal/services/appservice/helpers/web_app_slot_schema.go:670:30: cannot use pointer.To(s.WorkerCount) (value of type *int) as *int32 value in assignment
internal/services/appservice/helpers/web_app_slot_schema.go:823:30: cannot use pointer.To(s.WorkerCount) (value of type *int) as *int32 value in assignment
```

I think we would have to change the type of `NumberOfWorkers`.

If we do that I think we also need to update a lot more code to remove the int32 casting which is currently used on `WorkerCount` throughout the code. 

Please let me know if you want to pursue this or not so I can make changes accordingly. If we do the PR will become quite a bit bigger in my mind.

**Comment by jackofallops** [comment]
> > Hi @dkanbier - Thanks for this PR, and for the catch on the missing property. Due to a recent change in the SDK, this property is now an `int64` type, so no longer requires casting. If you can update, we can get the tests run and hopefully get this merged when they pass.
> > Thanks!
> 
> Hi @jackofallops , I've applied your suggested changes and tried rebuilding the module but it fails:
> 
> ```
> internal/services/appservice/helpers/web_app_slot_schema.go:670:30: cannot use pointer.To(s.WorkerCount) (value of type *int) as *int32 value in assignment
> internal/services/appservice/helpers/web_app_slot_schema.go:823:30: cannot use pointer.To(s.WorkerCount) (value of type *int) as *int32 value in assignment
> ```
> 
> I think we would have to change the type of `NumberOfWorkers`.
> 
> If we do that I think we also need to update a lot more code to remove the int32 casting which is currently used on `WorkerCount` throughout the code.
> 
> Please let me know if you want to pursue this or not so I can make changes accordingly. If we do the PR will become quite a bit bigger in my mind.

Hi @dkanbier - To pick up the change in main to build successfully you'd need to update your fork's `main` branch and rebase your PR branch on top of that. (you should then end up with: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/helpers/web_app_slot_schema.go#L46) in your local.)  It's not absolutely necessary for the PR however, since the merge branch appears to be handling it just fine.  Now you've made the change, I can run workflows and the testing on our CI server for this.

**Comment by dkanbier** [comment]
> > > Hi @dkanbier - Thanks for this PR, and for the catch on the missing property. Due to a recent change in the SDK, this property is now an `int64` type, so no longer requires casting. If you can update, we can get the tests run and hopefully get this merged when they pass.
> > > Thanks!
> > 
> > 
> > Hi @jackofallops , I've applied your suggested changes and tried rebuilding the module but it fails:
> > ```
> > internal/services/appservice/helpers/web_app_slot_schema.go:670:30: cannot use pointer.To(s.WorkerCount) (value of type *int) as *int32 value in assignment
> > internal/services/appservice/helpers/web_app_slot_schema.go:823:30: cannot use pointer.To(s.WorkerCount) (value of type *int) as *int32 value in assignment
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think we would have to change the type of `NumberOfWorkers`.
> > If we do that I think we also need to update a lot more code to remove the int32 casting which is currently used on `WorkerCount` throughout the code.
> > Please let me know if you want to pursue this or not so I can make changes accordingly. If we do the PR will become quite a bit bigger in my mind.
> 
> Hi @dkanbier - To pick up the change in main to build successfully you'd need to update your fork's `main` branch and rebase your PR branch on top of that. (you should then end up with: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/helpers/web_app_slot_schema.go#L46) in your local.) It's not absolutely necessary for the PR however, since the merge branch appears to be handling it just fine. Now you've made the change, I can run workflows and the testing on our CI server for this.

@jackofallops Ah yes you are right, I did the rebase but forgot I was on my fork. Sorry!

**Comment by dkanbier** [comment]
Hi @jackofallops , any news on the tests maybe?

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for this @dkanbier
