### PR TITLE
#24910: Use ParseFirewallPolicyIDInsensitively for parsing API response

### LINKED ISSUE #24910: Error: The terraform-provider-azurerm_v3.86.0_x5 plugin crashed! panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x65771cd]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

azurerm_firewall

### Terraform Configuration Files

```hcl
uncommented the firewall config to destroy it.

/*
resource "azurerm_firewall" "this" {
  name                = var.firewall_name
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  sku_name            = "AZFW_VNet"
  sku_tier            = "Premium"
  firewall_policy_id  = azurerm_firewall_policy.this.id 

  ip_configuration {
    name                 = "firewallipconfig"
    subnet_id            = azurerm_subnet.firewall.id
    public_ip_address_id = azurerm_public_ip.firewall.id
  }
}
*/
```

### Debug Output/Panic Output

```shell
module.prod_hub.azurerm_firewall.this: Destroying...

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.92.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5cbf90d]

goroutine 68 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/firewall.resourceFirewallDelete(0xc003d3c600, {0x7a33fa0?, 0xc001c4cd80?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/firewall/firewall_resource.go:541 +0x50d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0x9233420?, {0x9233420?, 0xc0040871a0?}, 0xd?, {0x7a33fa0?, 0xc001c4cd80?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:817 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000c19180, {0x9233420, 0xc0040871a0}, 0xc0024bbee0, 0xc003d3c580, {0x7a33fa0, 0xc001c4cd80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:878 +0x605
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000b34888, {0x9233420?, 0xc0040870b0?}, 0xc0018d7400)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0012920a0, {0x9233420?, 0xc0040868a0?}, 0xc0021242a0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x85fff80?, 0xc0012920a0}, {0x9233420, 0xc0040868a0}, 0xc002124230, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002321e0, {0x925a200, 0xc001438000}, 0xc0043f2b40, 0xc0013fa2a0, 0xec0be98, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002321e0, {0x925a200, 0xc001438000}, 0xc0043f2b40, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 13
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145

	
Error: The terraform-provider-azurerm_v3.92.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Firewall should be destroyed.

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by harshavmb**
Use `ParseFirewallPolicyIDInsensitively` for parsing API response rather `ParseFirewallPolicyID` as per below comment mentioned [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/vendor/github.com/hashicorp/go-azure-sdk/resource-manager/network/2023-06-01/firewallpolicies/id_firewallpolicy.go#L47-L48). 

```
// ParseFirewallPolicyIDInsensitively parses 'input' case-insensitively into a FirewallPolicyId
// note: this method should only be used for API response data and not user input
```

Reads are from API response, so `ParseFirewallPolicyIDInsensitively` needs to be used. 

Fixes #24910.

### CODE REVIEW

File: internal/services/firewall/firewall_resource.go [hunk 1]
```diff
@@ -537,7 +537,7 @@ func resourceFirewallDelete(d *pluginsdk.ResourceData, meta interface{}) error {
 		}
 
 		if read.Model.Properties != nil && read.Model.Properties.FirewallPolicy != nil && read.Model.Properties.FirewallPolicy.Id != nil {
-			id, _ := firewallpolicies.ParseFirewallPolicyID(*read.Model.Properties.FirewallPolicy.Id)
+			id, _ := firewallpolicies.ParseFirewallPolicyIDInsensitively(*read.Model.Properties.FirewallPolicy.Id)
```
Comment (tombuildsstuff) [inline internal/services/firewall/firewall_resource.go:540]: could we also return this error if it's returned, which would have caught the original crash here:

```suggestion
			id, err := firewallpolicies.ParseFirewallPolicyIDInsensitively(*read.Model.Properties.FirewallPolicy.Id)
			if err != nil {
				return err
			}
```

**Comment by harshavmb** [comment]
Hi @tombuildsstuff ,

Made the change! Over to you for the re-review.

**Review by katbyte — APPROVED** [review]
