### PR TITLE
`azurerm_kubernetes_cluster` - Support for `outbound_type = "*NATGateway"` and `nat_gateway_profile`

### LINKED ISSUE #14138: Support for new AKS outbound settings: managedNATGateway and userAssignedNATGateway
Support for new AKS outbound settings: managedNATGateway and userAssignedNATGateway

https://docs.microsoft.com/en-us/azure/aks/nat-gateway

Looks like validation is broken for those types. kubernetes_cluster_resource.go line 496.
There're missing 
```
string(containerservice.OutboundTypeManagedNATGateway),
string(containerservice.OutboundTypeUserAssignedNATGateway),
```

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #14138

### Acceptance Tests
- [x] `outboundType = "managedNATGateway"`
```bash
TF_ACC=1 go test -v ./internal/services/containers -run=TestAccKubernetesCluster_managedNatGateway -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccKubernetesCluster_managedNatGateway
=== PAUSE TestAccKubernetesCluster_managedNatGateway
=== CONT  TestAccKubernetesCluster_managedNatGateway
--- PASS: TestAccKubernetesCluster_managedNatGateway (589.09s)
PASS
ok   github.com/hashicorp/terraform-provider-azurerm/internal/services/containers     590.831s
```
- [x] `outboundType = "managedNATGateway"` with `nat_gateway_profile` settings
```bash
TF_ACC=1 go test -v ./internal/services/containers -run=TestAccKubernetesCluster_natGatewayProfile -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccKubernetesCluster_natGatewayProfile
=== PAUSE TestAccKubernetesCluster_natGatewayProfile
=== CONT  TestAccKubernetesCluster_natGatewayProfile
--- PASS: TestAccKubernetesCluster_natGatewayProfile (748.23s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/service
```
- [x] `outboundType = "userAssignedNATGateway"`
```bash
TF_ACC=1 go test -v ./internal/services/containers -run=TestAccKubernetesCluster_userAssignedNatGateway -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccKubernetesCluster_userAssignedNatGateway
=== PAUSE TestAccKubernetesCluster_userAssignedNatGateway
=== CONT  TestAccKubernetesCluster_userAssignedNatGateway
--- PASS: TestAccKubernetesCluster_userAssignedNatGateway (647.71s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/containers     649.450s
```

### CODE REVIEW

File: internal/services/containers/kubernetes_cluster_resource.go [hunk 1]
```diff
@@ -557,6 +559,38 @@ func resourceKubernetesCluster() *pluginsdk.Resource {
 								},
 							},
 						},
+
+						"nat_gateway_profile": {
```
Comment (katbyte) [inline internal/services/containers/kubernetes_cluster_resource.go:563]: i think we can remove profile from this property name?
```suggestion
						"nat_gateway": {
```

Comment (aristosvo) [reply internal/services/containers/kubernetes_cluster_resource.go:563]: Hi @katbyte! The naming is in this case based on the API property and consistent with existing property `load_balancer_profile`. I don't mind removing it though, just not sure.

**Comment by MasterKolka** [comment]
Hello. Will it be possible to review this before next release? Thanks. It will help me a lot.

File: internal/services/containers/kubernetes_cluster_resource.go (hunk 1 above)
Comment (katbyte) [reply internal/services/containers/kubernetes_cluster_resource.go:563]: ahh yea given that profile is used for a bunch here this is fine even thou i don't like it 😬 to popular of resource to really rename everything here to clean it up and make it simplier/better 

fwiw we try to be more clear/simplier with property names over following the exact API names as they can often be... quite verbrose and strangely worded

**Review by katbyte — APPROVED** [review]
LGTM @aristosvo ! 🚀
