### PR TITLE
`azurerm_storage_management_policy` - Add existance check

### LINKED ISSUE #18583: azurerm_storage_management_policy overwrites the rules
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_management_policy

### Terraform Configuration Files

```hcl
data "azurerm_storage_account" "example"{
    name = "csgxxxxxxxxxxxxxxxx"
    resource_group_name = "cloud-shell-xxxxxx"
}


resource "azurerm_storage_management_policy" "default" {
  storage_account_id = data.azurerm_storage_account.example.id

  rule {
    name    = "default"
    enabled = true
    filters {
      prefix_match = [""]
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than    = 999
        tier_to_archive_after_days_since_modification_greater_than = 999
        delete_after_days_since_modification_greater_than          = 0
      }
      
    }
  }
}


resource "azurerm_storage_management_policy" "default1" {
  storage_account_id = data.azurerm_storage_account.example.id

  rule {
    name    = "retention"
    enabled = true
    filters {
      prefix_match = ["container/blob1"]
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than    = 30
        # tier_to_archive_after_days_since_modification_greater_than = 90
        # delete_after_days_since_modification_greater_than          = 0
      }
      
    }
  }
}
```

### Debug Output/Panic Output

```shell
[0m[1mdata.azurerm_storage_account.example: Reading...[0m[0m
[0m[1mdata.azurerm_storage_account.example: Read complete after 0s [id=/subscriptions/xxxxx188-21a7-xxxx-8d0c-zzxxxxx/resourceGroups/cloud-shell-xxxxxxx/providers/Microsoft.Storage/storageAccounts/csgxxxxxxxxx][0m
[0m[1mazurerm_storage_management_policy.default: Refreshing state... [id=/subscriptions/xxxxx188-21a7-xxxx-8d0c-zzxxxxx/resourceGroups/cloud-shell-xxxxxxx/providers/Microsoft.Storage/storageAccounts/csgxxxxxxxxx/managementPolicies/default][0m
[0m[1mazurerm_storage_management_policy.default1: Refreshing state... [id=/subscriptions/xxxxx188-21a7-xxxx-8d0c-zzxxxxx/resourceGroups/cloud-shell-xxxxxxx/providers/Microsoft.Storage/storageAccounts/csgxxxxxxxxx/managementPolicies/default][0m

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  [33m~[0m update in-place
[0m
Terraform will perform the following actions:

[1m  # azurerm_storage_management_policy.default[0m will be updated in-place[0m[0m
[0m  [33m~[0m[0m resource "azurerm_storage_management_policy" "default" {
        [1m[0mid[0m[0m                 = "/subscriptions/xxxxx188-21a7-xxxx-8d0c-zzxxxxx/resourceGroups/cloud-shell-xxxxxxx/providers/Microsoft.Storage/storageAccounts/csgxxxxxxxxx/managementPolicies/default"
        [90m# (1 unchanged attribute hidden)[0m[0m

      [33m~[0m [0mrule {
          [33m~[0m [0m[1m[0mname[0m[0m    = "retention" [33m->[0m [0m"default"
            [90m# (1 unchanged attribute hidden)[0m[0m

          [33m~[0m [0mactions {
              [33m~[0m [0mbase_blob {
                  [33m~[0m [0m[1m[0mdelete_after_days_since_modification_greater_than[0m[0m              = -1 [33m->[0m [0m0
                  [33m~[0m [0m[1m[0mtier_to_archive_after_days_since_modification_greater_than[0m[0m     = -1 [33m->[0m [0m9999
                  [33m~[0m [0m[1m[0mtier_to_cool_after_days_since_modification_greater_than[0m[0m        = 30 [33m->[0m [0m9999
                    [90m# (3 unchanged attributes hidden)[0m[0m
                }
            }

          [33m~[0m [0mfilters {
              [33m~[0m [0m[1m[0mprefix_match[0m[0m = [
                  [32m+[0m [0m"",
                  [31m-[0m [0m"container/blob1",
                ]
                [90m# (1 unchanged attribute hidden)[0m[0m
            }
        }
    }

[0m[1mPlan:[0m 0 to add, 1 to change, 0 to destroy.
[0m[0m[1mazurerm_storage_management_policy.default: Modifying... [id=/subscriptions/xxxxx188-21a7-xxxx-8d0c-zzxxxxx/resourceGroups/cloud-shell-xxxxxxx/providers/Microsoft.Storage/storageAccounts/csgxxxxxxxxx/managementPolicies/default][0m[0m
[0m[1mazurerm_storage_management_policy.default: Modifications complete after 0s [id=/subscriptions/xxxxx188-21a7-xxxx-8d0c-zzxxxxx/resourceGroups/cloud-shell-xxxxxxx/providers/Microsoft.Storage/storageAccounts/csgxxxxxxxxx/managementPolicies/default][0m
[0m[1m[32m
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
[0m

```

### Expected Behaviour

Should create two policy rules , as they can be created from the portal 

### Actual Behaviour

terraform plan shows to create only one rule and doesn't shows the removal of the rule which the apply performs 

deletes one  rule and creates only one of the two rules for lifecycle management 

### Steps to Reproduce

terraform plan 

terraform apply 

### Important Factoids

_No response_

### References

Is this because of the constraint : 

https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview#:~:text=If%20you%20define%20more%20than%20one%20action%20on%20the%20same%20blob%2C%20lifecycle%20management%20applies%20the%20least%20expensive%20action%20to%20the%20blob.

### PR DESCRIPTION
**Pull request by magodo**
The concern is whether the lock here is necessary, as if that is the case, then I believe almost all of the existing resources should add that. But at least, it is needed for the use case in #18583.

Fix #18583 

## Test

```shell
💤  TF_ACC=1 go test -v -timeout=20h -run='TestAccStorageManagementPolicy_requiersImport' ./internal/services/storage
=== RUN   TestAccStorageManagementPolicy_requiersImport
=== PAUSE TestAccStorageManagementPolicy_requiersImport
=== CONT  TestAccStorageManagementPolicy_requiersImport
--- PASS: TestAccStorageManagementPolicy_requiersImport (152.71s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       152.721s
```

### CODE REVIEW

File: internal/services/storage/storage_management_policy_resource.go [hunk 1]
```diff
@@ -285,7 +287,21 @@ func resourceStorageManagementPolicyCreateOrUpdate(d *pluginsdk.ResourceData, me
 	// The name of the Storage Account Management Policy. It should always be 'default' (from https://docs.microsoft.com/en-us/rest/api/storagerp/managementpolicies/createorupdate)
 	mgmtPolicyId := parse.NewStorageAccountManagementPolicyID(rid.SubscriptionId, rid.ResourceGroupName, rid.StorageAccountName, "default")
 
-	// TODO: support Requires Import
+	if d.IsNewResource() {
+		// This lock is to protect the existence checking when two storage mgmt policies are being created at the same time.
+		locks.ByID(mgmtPolicyId.ID())
```
Comment (mbfrahry) [inline internal/services/storage/storage_management_policy_resource.go:292]: I'm not sure we should go this route quite yet. We should do a separate PR with it's own test to confirm that this will fix that issue.

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @magodo, this change looks good minus what you called out with the locks. We should do a separate PR for that so we can get this in quicker

File: internal/services/storage/storage_management_policy_resource.go (hunk 1 above)
Comment (magodo) [reply internal/services/storage/storage_management_policy_resource.go]: Yeah, I've removed the locks.

File: internal/services/storage/storage_management_policy_resource_test.go [hunk 2]
```diff
@@ -46,6 +46,21 @@ func TestAccStorageManagementPolicy_basic(t *testing.T) {
 	})
 }
 
+func TestAccStorageManagementPolicy_requiersImport(t *testing.T) {
```
Comment (stephybun) [inline internal/services/storage/storage_management_policy_resource_test.go:49]:
```suggestion
func TestAccStorageManagementPolicy_requiresImport(t *testing.T) {
```

**Review by stephybun — CHANGES_REQUESTED** [review]

**Review by stephybun — APPROVED** [review]
Thanks @magodo LGTM 👍
