### PR TITLE
`azurerm_cosmosdb_mongo_collection`: ignore throughput if Cosmos DB provisioned in 'serverless' capacity mode

### LINKED ISSUE #9697: Error reading Throughput on Cosmos Mongo Collection for Serverless CosmosDb
AzureRm provider supports creation of Serverless CosmosDb with Mongo API but fails refreshing state for azurerm_cosmosdb_mongo_collection. Azure does not support Throughput parameter for Serverless CosmosDb with MongoAPI. 

### Terraform (and AzureRM Provider) Version
Terraform v0.13.5
provider registry.terraform.io/hashicorp/azurerm v2.39.0

### Affected Resource(s)

* azurerm_cosmosdb_mongo_collection
* azurerm_cosmosdb_account (kind=MongoDb, capabilities=EnableMongo+EnableServerless

### Terraform Configuration Files

provider "azurerm" {
  environment     = "public"
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "testgroup"
  location = "eastus"
}

resource "azurerm_cosmosdb_account" "cosmodaccount" {
  name                = "todelete-test-cosmosdb-random"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  capabilities {
    name = "EnableMongo"
  }
  capabilities {
    name = "EnableServerless"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 10
    max_staleness_prefix    = 200
  }

  geo_location {
    location          = azurerm_resource_group.rg.location
    failover_priority = 0
  }
}

resource "azurerm_cosmosdb_mongo_database" "cosmosdb" {
  name                = "testname"
  resource_group_name = azurerm_cosmosdb_account.cosmodaccount.resource_group_name
  account_name        = azurerm_cosmosdb_account.cosmodaccount.name
}

resource "azurerm_cosmosdb_mongo_collection" "proposals" {
  name                = "testcollection"
  resource_group_name = azurerm_cosmosdb_account.cosmodaccount.resource_group_name
  account_name        = azurerm_cosmosdb_account.cosmodaccount.name
  database_name       = azurerm_cosmosdb_mongo_database.cosmosdb.name

  default_ttl_seconds = "0"
  shard_key           = "shardKey"

  index {
    keys   = ["_id"]
    unique = true
  }
}
```

### Debug Output

Error: Error reading Throughput on Cosmos Mongo Collection "testname" (Account: "todelete-test-cosmosdb", Database: "testname"): documentdb.MongoDBResourcesClient#GetMongoDBCollectionThroughput: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Message: {\"code\":\"BadRequest\",\"message\":\"Reading or replacing offers is not supported for serverless accounts.\\, Microsoft.Azure.Documents.Common/2.11.0\"}, Request URI: /offers, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.11.0"


### Expected Behaviour

MongoCollection for serverless CosmosDb (in preview) does not support throughtput for databases/collections. Azure does not return throughput parameter at refreshing the state (and ignores it during creation). azurerm_cosmosdb_mongo_collection fails during refresh. 

### Actual Behaviour

"terraform refresh" produces error:
Error: Error reading Throughput on Cosmos Mongo Collection "testname" (Account: "todelete-test-cosmosdb", Database: "testname"): documentdb.MongoDBResourcesClient#GetMongoDBCollectionThroughput: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Message: {\"code\":\"BadRequest\",\"message\":\"Reading or replacing offers is not supported for serverless accounts.\\, Microsoft.Azure.Documents.Common/2.11.0\"}, Request URI: /offers, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.11.0"

### Steps to Reproduce

1. `terraform apply --auto-approve`
2. terraform refresh

### PR DESCRIPTION
**Pull request by wiebeck**
This should fix #9697. I stumbled upon the same "Error reading Throughput on Cosmos Mongo Collection" when I provisioned a "serverless" Cosmos DB in Mongo mode.

There was already some code in other places (obviously missing from `cosmosdb_mongo_collection_resource.go`) that handles throughput if and only if...

1. ...the database account contains _any_ `Capabilities`
2. ...these `Capabilities` _do not contain_ `EnableServerless`

However I think that throughput should _also_ be handled if there are _no_ `Capabilities` since "Provisioned throughput" is the default, so I fixed that as well.

I moved the code into a central function `isServerlessCapacityMode` (DRY!) which I put into file `cosmosdb_account_resource.go`. Not sure if this is the right place though.

Feedback very welcome!

### CODE REVIEW

File: azurerm/internal/services/cosmos/cosmosdb_account_resource.go [hunk 1]
```diff
@@ -1009,6 +1009,17 @@ func findZoneRedundant(locations *[]documentdb.Location, id string) bool {
 	return false
 }
 
+func isServerlessCapacityMode(accResp documentdb.DatabaseAccountGetResults) bool {
+	if props := accResp.DatabaseAccountGetProperties; props != nil && props.Capabilities != nil {
+		for _, v := range *props.Capabilities {
+			if *v.Name == "EnableServerless" {
```
Comment (mbfrahry) [inline azurerm/internal/services/cosmos/cosmosdb_account_resource.go:1015]: We should confirm that `v` isn't nil before pointing to it

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @wiebeck, thanks for taking the time to write this PR! I just have a minor comment for an extra anil check and a request to add `serverless` tests to each of the resources you've touched. I believe a couple already have tests for serverless so we just have to make sure the others have them too

**Review by mbfrahry — APPROVED** [review]
LGTM!
