### PR TITLE
azurerm_storage_management_policy: handle unexpected deletion of the referenced storage account

### LINKED ISSUE #12933: Terraform plan fails if the Storage Account referenced in azurerm_storage_management_policy was deleted outside of Terraform
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform version: v1.0.0
- AzureRM Provider version: v2.71.0

### Affected Resource(s)

* `azurerm_storage_management_policy`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resource-group"
  location = "centralus"
}

resource "azurerm_storage_account" "example" {
  name                      = "jneafknzeae" # Random name for demo purposes
  resource_group_name       = azurerm_resource_group.example.name
  location                  = azurerm_resource_group.example.location
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  access_tier               = "Hot"
  account_replication_type  = "LRS"
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"
  allow_blob_public_access  = false
}

resource "azurerm_storage_management_policy" "example" {
  storage_account_id = azurerm_storage_account.example.id

  rule {
    name    = "Example-Rule"
    enabled = true
    filters {
      blob_types = ["blockBlob"]
    }
    actions {
      base_blob {
        delete_after_days_since_modification_greater_than = 30
      }
    }
  }
}
```

### Expected Behaviour

A drift is properly detected and the Storage Account / policy are recreated.

### Actual Behaviour

Terraform plan fails with:

```
│ Error: storage.ManagementPoliciesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Storage/storageAccounts/jneafknzeae' under resource group 'example-resource-group' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
│ 
│   with azurerm_storage_management_policy.example,
│   on main.tf line 23, in resource "azurerm_storage_management_policy" "example":
│   23: resource "azurerm_storage_management_policy" "example" {
```

Since plan fails, we are unable to recreate the Storage Account.

### Steps to Reproduce

1. `terraform apply` the above configuration
2. Go into the Azure portal and manually delete the Storage Account (or use the CLI, etc.)
3. `terraform plan` the above configuration

### References

* Similar to https://github.com/hashicorp/terraform-provider-azurerm/issues/11680

### PR DESCRIPTION
**Pull request by magodo**
Fix #12933

### CODE REVIEW

File: internal/services/storage/storage_management_policy_resource.go [hunk 1]
```diff
@@ -300,8 +308,11 @@ func resourceStorageManagementPolicyDelete(d *pluginsdk.ResourceData, meta inter
 		return err
 	}
 
-	if _, err = client.Delete(ctx, rid.ResourceGroup, rid.StorageAccountName); err != nil {
-		return err
+	if resp, err := client.Delete(ctx, rid.ResourceGroup, rid.StorageAccountName); err != nil {
+		if response.WasNotFound(resp.Response) {
+			return nil
+		}
```
Comment (tombuildsstuff) [inline internal/services/storage/storage_management_policy_resource.go:314]: this would indicate a bug which wasn't caught elsewhere:

```suggestion
```

File: internal/services/storage/storage_management_policy_resource.go [hunk 2]
```diff
@@ -300,8 +308,11 @@ func resourceStorageManagementPolicyDelete(d *pluginsdk.ResourceData, meta inter
...
+		return fmt.Errorf("waiting for deletion of %s: %+v", rid, err)
```
Comment (tombuildsstuff) [inline internal/services/storage/storage_management_policy_resource.go:315]: technically this is:

```suggestion
		return fmt.Errorf("deleting %s: %+v", rid, err)
```

**Review by tombuildsstuff — APPROVED** [review]
A couple of comments but this otherwise LGTM - thanks for this @magodo
