### PR TITLE
`azurerm_postgresql_flexible_server_virtual_endpoint` - is no longer removed from state when a fail-over occurs

### LINKED ISSUE #27796: [BUG] AzureRM - Azure Postgres Flexible Server - Virtual Endpoint Attempts to re-create after Failover
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.13

### AzureRM Provider Version

4.7.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_virtual_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server_virtual_endpoint" "testendpoint" {
  name              = "testendpoint1"
  source_server_id  = data.azurerm_postgresql_flexible_server.centralpg.id
  replica_server_id = data.azurerm_postgresql_flexible_server.eastpgreplica.id
  type              = "ReadWrite"

  depends_on = [
    data.azurerm_postgresql_flexible_server.centralpg,
    data.azurerm_postgresql_flexible_server.eastpgreplica
  ]
  
}
```

### Debug Output/Panic Output

```shell
Whitespace change before failover shows 0 changes.

After manually promoting the replica server to the primary server in the azure UI, this happens on whitespace change:

Terraform will perform the following actions:

  # azurerm_postgresql_flexible_server_virtual_endpoint.testendpoint will be created
  + resource "azurerm_postgresql_flexible_server_virtual_endpoint" "testendpoint" {
      + id                = (known after apply)
      + name              = "testendpoint1"
      + replica_server_id = "/subscriptions/XX/resourceGroups/eastus2-cloudpipelines-dev-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/eastus2-replica-test-demo-dev-fpg"
      + source_server_id  = "/subscriptions/XX/resourceGroups/centralus-development-dev-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/centralus-test-demo-dev-fpg"
      + type              = "ReadWrite"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Expected Behaviour

It should see there is already an endpoint assigned to both resources that is functional.

### Actual Behaviour

_No response_

### Steps to Reproduce

Whitespace change

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by mbfrahry**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR fixes #27796 where the resource is removed from state when a fail-over occurs. Instead of removing from state, we'll check to see if the resource exists under the replica server id. If it does, we hide the fact that a fail-over occurred. We've had to update the id of the resource to account for that and we've had to prevent the ability of the `replica_server_id` from being changed if a fail-over occurred due to the myriad of edge cases we'd need to account for.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_postgresql_flexible_server_virtual_endpoint` - is no longer removed from state when a fail-over occurs[GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27796

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by mbfrahry** [comment]
image

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go [hunk 1]
```diff
@@ -221,7 +291,7 @@ func (r PostgresqlFlexibleServerVirtualEndpointResource) Delete() sdk.ResourceFu
 
 func (r PostgresqlFlexibleServerVirtualEndpointResource) Update() sdk.ResourceFunc {
 	return sdk.ResourceFunc{
-		Timeout: 5 * time.Minute,
+		Timeout: 10 * time.Minute,
```
Comment (sreallymatt) [inline internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go:294]: This will have to be updated in the doc as well, looks like all timeouts except `read` are wrong

File: website/docs/r/postgresql_flexible_server_virtual_endpoint.html.markdown [hunk 2]
```diff
@@ -69,6 +69,8 @@ The following arguments are supported:
 
 * `replica_server_id` - (Required) The Resource ID of the *Replica* Postgres Flexible Server this should be associated with
 
+~> **Note:** If a fail-over has occurred, you will be unable to update `replica_server_id`. You can remove the resource from state and reimport it back in with `source_server_id` and `replica_server_id` flipped and then update `replica_server_id`.
```
Comment (sreallymatt) [inline website/docs/r/postgresql_flexible_server_virtual_endpoint.html.markdown:72]: Nit: there's 2 different forms of `failover` (`fail-over`) in the docs/resource error msg in update func, change for consistency? 

```suggestion
~> **Note:** If a failover has occurred, you will be unable to update `replica_server_id`. You can remove the resource from state and reimport it back in with `source_server_id` and `replica_server_id` flipped and then update `replica_server_id`.
```

**Review by sreallymatt — CHANGES_REQUESTED** [review]
I've left 2 minor comments inline, other than that I think this looks good

File: website/docs/r/postgresql_flexible_server_virtual_endpoint.html.markdown (hunk 2 above)
Comment (mbfrahry) [reply website/docs/r/postgresql_flexible_server_virtual_endpoint.html.markdown:72]: I fixed it in the error message!

**Review by sreallymatt — APPROVED** [review]
LGTM!
