### PR TITLE
[fix] Correctly set`replica_server_id` on `azurerm_postgresql_flexible_server_virtual_endpoint` for`azurerm_postgresql_flexible_server`s that exist in separate resource groups

### LINKED ISSUE #27453: `postgresql_flexible_server_virtual_endpoint_resource` incorrectly sets Replica Server ID
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.0

### AzureRM Provider Version

4.3.0

### Affected Resource(s)/Data Source(s)

postgresql_flexible_server_virtual_endpoint_resource

### Terraform Configuration Files

```hcl
resource "random_pet" "name_prefix" {
  length = 1
}

###### EAST RG ######

resource "azurerm_resource_group" "east" {
  name     = "${random_pet.name_prefix.id}-east"
  location = "eastus"
}

resource "azurerm_virtual_network" "east" {
  name                = "${random_pet.name_prefix.id}-east-vn"
  location            = azurerm_resource_group.east.location
  resource_group_name = azurerm_resource_group.east.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_network_security_group" "east" {
  name                = "${random_pet.name_prefix.id}-east-nsg"
  location            = azurerm_resource_group.east.location
  resource_group_name = azurerm_resource_group.east.name

  security_rule {
    name                       = "allow_all"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_subnet" "east" {
  name                 = "${random_pet.name_prefix.id}-east-sn"
  resource_group_name  = azurerm_resource_group.east.name
  virtual_network_name = azurerm_virtual_network.east.name
  address_prefixes     = ["10.0.1.0/24"]
  service_endpoints    = ["Microsoft.Storage"]

  delegation {
    name = "fs"
    service_delegation {
      name = "Microsoft.DBforPostgreSQL/flexibleServers"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_subnet_network_security_group_association" "east" {
  subnet_id                 = azurerm_subnet.east.id
  network_security_group_id = azurerm_network_security_group.east.id
}

resource "azurerm_private_dns_zone" "east" {
  name                = "${random_pet.name_prefix.id}-pdz.postgres.database.azure.com"
  resource_group_name = azurerm_resource_group.east.name

  depends_on = [azurerm_subnet_network_security_group_association.east]
}

resource "azurerm_virtual_network_peering" "east" {
  name                         = "east-to-west"
  resource_group_name          = azurerm_resource_group.east.name
  virtual_network_name         = azurerm_virtual_network.east.name
  remote_virtual_network_id    = azurerm_virtual_network.west.id
  allow_virtual_network_access = true
  allow_forwarded_traffic      = true
}

resource "azurerm_private_dns_zone_virtual_network_link" "east" {
  name                  = "${random_pet.name_prefix.id}-east-pdzvnetlink.com"
  private_dns_zone_name = azurerm_private_dns_zone.east.name
  virtual_network_id    = azurerm_virtual_network.east.id
  resource_group_name   = azurerm_resource_group.east.name

  depends_on = [azurerm_virtual_network_peering.east]
}

resource "random_password" "pass" {
  length = 20
}

resource "azurerm_postgresql_flexible_server" "east" {
  name                          = "${random_pet.name_prefix.id}-east-pg"
  resource_group_name           = azurerm_resource_group.east.name
  location                      = azurerm_resource_group.east.location
  version                       = "13"
  public_network_access_enabled = false
  administrator_login           = "adminTerraform"
  administrator_password        = random_password.pass.result
  sku_name                      = "GP_Standard_D2s_v3"

  delegated_subnet_id = azurerm_subnet.east.id
  private_dns_zone_id = azurerm_private_dns_zone.east.id

  depends_on = [azurerm_private_dns_zone_virtual_network_link.east]

  lifecycle {
    ignore_changes = [zone]
  }

  timeouts {
    create = "120m"
  }
}

resource "azurerm_postgresql_flexible_server_virtual_endpoint" "example" {
  name              = "${random_pet.name_prefix.id}-endpoint"
  source_server_id  = azurerm_postgresql_flexible_server.east.id
  replica_server_id = azurerm_postgresql_flexible_server.west.id
  type              = "ReadWrite"
}

###### WEST RG ######

resource "azurerm_resource_group" "west" {
  name     = "${random_pet.name_prefix.id}-west"
  location = "westus"
}

resource "azurerm_virtual_network" "west" {
  name                = "${random_pet.name_prefix.id}-west-vn"
  location            = azurerm_resource_group.west.location
  resource_group_name = azurerm_resource_group.west.name
  address_space       = ["11.0.0.0/16"]
}

resource "azurerm_network_security_group" "west" {
  name                = "${random_pet.name_prefix.id}-west-nsg"
  location            = azurerm_resource_group.west.location
  resource_group_name = azurerm_resource_group.west.name

  security_rule {
    name                       = "allow_all"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_subnet" "west" {
  name                 = "${random_pet.name_prefix.id}-west-sn"
  resource_group_name  = azurerm_resource_group.west.name
  virtual_network_name = azurerm_virtual_network.west.name
  address_prefixes     = ["11.0.1.0/24"]
  service_endpoints    = ["Microsoft.Storage"]

  delegation {
    name = "fs"
    service_delegation {
      name = "Microsoft.DBforPostgreSQL/flexibleServers"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_subnet_network_security_group_association" "west" {
  subnet_id                 = azurerm_subnet.west.id
  network_security_group_id = azurerm_network_security_group.west.id
}

resource "azurerm_private_dns_zone" "west" {
  name                = "${random_pet.name_prefix.id}-pdz.postgres.database.azure.com"
  resource_group_name = azurerm_resource_group.west.name

  depends_on = [azurerm_subnet_network_security_group_association.west]
}

resource "azurerm_virtual_network_peering" "west" {
  name                         = "west-to-east"
  resource_group_name          = azurerm_resource_group.west.name
  virtual_network_name         = azurerm_virtual_network.west.name
  remote_virtual_network_id    = azurerm_virtual_network.east.id
  allow_virtual_network_access = true
  allow_forwarded_traffic      = true
}

resource "azurerm_private_dns_zone_virtual_network_link" "west" {
  name                  = "${random_pet.name_prefix.id}-west-pdzvnetlink.com"
  private_dns_zone_name = azurerm_private_dns_zone.west.name
  virtual_network_id    = azurerm_virtual_network.west.id
  resource_group_name   = azurerm_resource_group.west.name

  depends_on = [azurerm_virtual_network_peering.west]
}

resource "azurerm_postgresql_flexible_server" "west" {
  name                          = "${random_pet.name_prefix.id}-west-pg"
  resource_group_name           = azurerm_resource_group.west.name
  location                      = azurerm_resource_group.west.location
  create_mode                   = "Replica"
  source_server_id              = azurerm_postgresql_flexible_server.east.id
  version                       = azurerm_postgresql_flexible_server.east.version
  public_network_access_enabled = azurerm_postgresql_flexible_server.east.public_network_access_enabled
  sku_name                      = azurerm_postgresql_flexible_server.east.sku_name

  delegated_subnet_id = azurerm_subnet.west.id
  private_dns_zone_id = azurerm_private_dns_zone.west.id

  depends_on = [azurerm_private_dns_zone_virtual_network_link.west]

  lifecycle {
    ignore_changes = [zone]
  }

  timeouts {
    create = "120m"
  }
}
```

### Debug Output/Panic Output

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_postgresql_flexible_server_virtual_endpoint.example will be updated in-place
  ~ resource "azurerm_postgresql_flexible_server_virtual_endpoint" "example" {
        id                = "/subscriptions/8ffedf3e-82d2-49f5-9603-8b318198e483/resourceGroups/cardinal-east/providers/Microsoft.DBforPostgreSQL/flexibleServers/cardinal-east-pg/virtualEndpoints/cardinal-endpoint"
        name              = "cardinal-endpoint"
      ~ replica_server_id = "/subscriptions/8ffedf3e-82d2-49f5-9603-8b318198e483/resourceGroups/cardinal-east/providers/Microsoft.DBforPostgreSQL/flexibleServers/cardinal-west-pg" -> "/subscriptions/8ffedf3e-82d2-49f5-9603-8b318198e483/resourceGroups/cardinal-west/providers/Microsoft.DBforPostgreSQL/flexibleServers/cardinal-west-pg"
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

No changes should be detected after initial creation

### Actual Behaviour

Resources deploy correctly, however the Replica Server ID changes on the endpoint on second run due to the way it is derived from the Source Server within the provider. 

The Virtual Endpoint presumes the replica server is in the same RG as the source server, which is not always the case.

### Steps to Reproduce

Deploy resources, then immediately deploy them again.

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-azurerm/blob/22b75edb3669a1d0fb48d0108fde66a49c73eed8/internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go#L162-L164

### LINKED ISSUE #27749: `azurerm_postgresql_flexible_server_virtual_endpoint` delete now errors with 404
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.3.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_virtual_endpoint

### Terraform Configuration Files

```hcl
# Initial

resource "azurerm_postgresql_flexible_server_virtual_endpoint" "database" {
  name              = "test1"
  source_server_id  = azurerm_postgresql_flexible_server.database.id
  replica_server_id = azurerm_postgresql_flexible_server.replica[0].id
  type              = "ReadWrite"
}

# Updated

resource "azurerm_postgresql_flexible_server_virtual_endpoint" "database" {
  name              = "test2"
  source_server_id  = azurerm_postgresql_flexible_server.database.id
  replica_server_id = azurerm_postgresql_flexible_server.replica[0].id
  type              = "ReadWrite"
}
```

### Debug Output/Panic Output

```shell
azurerm_postgresql_flexible_server_virtual_endpoint.database[0]: Destroying... [id=/subscriptions/xxx/resourceGroups/rg-xxx/providers/Microsoft.DBforPostgreSQL/flexibleServers/server-xxx/virtualEndpoints/vep-xxx]
╷
│ Error: retrieving Virtual Endpoint (Subscription: "xxx"
│ Resource Group Name: "rg-xxx"
│ Flexible Server Name: "server-xxx"
│ Virtual Endpoint Name: "vep-xxx"): unexpected status 404 (404 Not Found) with error: ResourceNotFound: The specified resource 'https://orcasbreadth.uksouth.control.database.windows.net:8343/modules/ArmPostgreSQL/subscriptions/xxx/resourceGroups/rg-xxx/providers/Microsoft.DBforPostgreSQL/flexibleServers/server-xxx/virtualEndpoints/vep-xxx?api-version=2023-06-01-preview' was not found.
│ 
│ retrieving Virtual Endpoint (Subscription:
│ "xxx"
│ Resource Group Name: "rg-xxx"
│ Flexible Server Name: "server-xxx"
│ Virtual Endpoint Name: "vep-xxx"): unexpected status 404
│ (404 Not Found) with error: ResourceNotFound: The specified resource
│ 'https://orcasbreadth.uksouth.control.database.windows.net:8343/modules/ArmPostgreSQL/subscriptions/xxx/resourceGroups/rg-xxx/providers/Microsoft.DBforPostgreSQL/flexibleServers/server-xxx/virtualEndpoints/vep-xxx?api-version=2023-06-01-preview'
│ was not found.
╵
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
│ Error: retrieving Virtual Endpoint (Subscription: "xxx"
│ Resource Group Name: "rg-xxx"
│ Flexible Server Name: "server-xxx"
│ Virtual Endpoint Name: "vep-xxx"): unexpected status 404 (404 Not Found) with error: ResourceNotFound: The specified resource 'https://orcasbreadth.uksouth.control.database.windows.net:8343/modules/ArmPostgreSQL/subscriptions/xxx/resourceGroups/rg-xxx/providers/Microsoft.DBforPostgreSQL/flexibleServers/server-xxx/virtualEndpoints/vep-xxx?api-version=2023-06-01-preview' was not found.
│ 
│ retrieving Virtual Endpoint (Subscription:
│ "xxx"
│ Resource Group Name: "rg-xxx"
│ Flexible Server Name: "server-xxx"
│ Virtual Endpoint Name: "vep-xxx"): unexpected status 404
│ (404 Not Found) with error: ResourceNotFound: The specified resource
│ 'https://orcasbreadth.uksouth.control.database.windows.net:8343/modules/ArmPostgreSQL/subscriptions/xxx/resourceGroups/rg-xxx/providers/Microsoft.DBforPostgreSQL/flexibleServers/server-xxx/virtualEndpoints/vep-xxx?api-version=2023-06-01-preview'
│ was not found.
╵
```

### Expected Behaviour

The destroy should have been reported as a success as the resource has gone, as indicated by the poller with a status 404

### Actual Behaviour

There is a workaround from a previous version of the API that returned 200 even after a delete which is no longer valid

### Steps to Reproduce

1. Create a virtual endpoint on a postgresql flexible server and it's replica
2. Rename the endpoint to trigger a destroy and create

### Important Factoids

_No response_

### References

A workaround created here is no longer valid https://github.com/hashicorp/terraform-provider-azurerm/pull/26708/files#diff-8d42a6764909f9ead04ec26199d82b54484e8d04ecb765bc79406656db7dfd67R23

### PR DESCRIPTION
**Pull request by bruceharrison1984**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This corrects a bug that occurs when the replica server doesn't exist in the same resource group as the source server. Previously, the endpoint would be flagged for changes on the second run. This corrects that issue.

Additionally, if the primary server was stopped it would also try to recreate the virtual endpoint. This also corrects that issue.

Anyone previously affected by this will see non-destructive changes on the first deploy, but the issue should correct it self there after.

This PR also removes the custom poller that was previously necessary. It appears Azure has changed the API so it is no longer necessary.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_postgresql_flexible_server_virtual_endpoint` - fix bug that affected replicas deployed in different resource groups from the source server [GH-27453]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27453
Fixes #27749

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go [hunk 1]
```diff
@@ -159,9 +160,19 @@ func (r PostgresqlFlexibleServerVirtualEndpointResource) Read() sdk.ResourceFunc
...
+
+					sourceServerId := servers.NewFlexibleServerID(id.SubscriptionId, id.ResourceGroupName, sourceServerName).ID()
+
+					replicaServer, err := lookupFlexibleServerByName(ctx, flexibleServerClient, id, replicaServerName, sourceServerId)
+					if err != nil {
+						return err
+					}
+
+					state.SourceServerId = sourceServerId
+					state.ReplicaServerId = *replicaServer.Id
```
Comment (jackofallops) [inline internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go:175]: Since this is direct from the lookup API, we can't be sure it will be correctly cased for the expected state (since we validate the input), can we normalise it using `servers.ParseFlexibleServerID()` before setting the value into `state.ReplicaServerId`?

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @bruceharrison1984 - Thanks for this PR, it looks mostly good, but there are a few minor changes to take a look at below if you could?
Thanks

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go [hunk 2]
```diff
@@ -231,17 +242,23 @@ func (r PostgresqlFlexibleServerVirtualEndpointResource) Update() sdk.ResourceFu
...
 
-// exposed so we can access from tests
-func DeletePostgresFlexibileServerVirtualEndpoint(ctx context.Context, client *virtualendpoints.VirtualEndpointsClient, id *virtualendpoints.VirtualEndpointId) error {
-	deletePoller := custompollers.NewPostgresFlexibleServerVirtualEndpointDeletePoller(client, *id)
-	poller := pollers.NewPoller(deletePoller, 5*time.Second, pollers.DefaultNumberOfDroppedConnectionsToAllow)
-
-	if _, err := client.Delete(ctx, *id); err != nil {
-		return fmt.Errorf("deleting %s: %+v", *id, err)
+// The flexible endpoint API does not store the location/rg information on replicas it only stores the name.
+// This lookup is safe because replicas for a given source server are *not* allowed to have identical names
```
[the remark this answers is not in the document]
Comment (bruceharrison1984) [reply internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go:246]: The names may not be unique per subscription, however they will be unique per source server. Since we check that the name matches, as well as filter those results based on the source server ID we should be protected from selecting an incorrect replica. Even if the names matched, replicas must have unique names per source servers.

https://github.com/hashicorp/terraform-provider-azurerm/pull/27509/files/94e28c5de14955a188f90192c06828946f9a6fcc#diff-6fceca959b7c5669ebd391456b3a69c7ff858802d5dc5e70a91c6237cd173ff0R258

I was worried about this as well, but I believe it is setup in a safe manner.

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go (hunk 1 above)
Comment (bruceharrison1984) [reply internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go]: I've updated the code to reflect your suggestion

**Review by leonrob — COMMENTED** [review]
From a hashi customer... THANK YOU FOR THIS @bruceharrison1984

**Comment by leonrob** [comment]
Hi can this be released this week?

**Comment by leonrob** [comment]
will this be released soon?

**Review by stephybun — APPROVED** [review]
Thanks for this @bruceharrison1984. Hope you don't mind I pushed some minor simplifications and additional nil checks to your code.

Tests are passing, LGTM 🚀 
image

**Comment by leonrob** [comment]
Thank you @stephybun  - is it possible to have someone merge? Bruce no longer works at Hashi. THANK YOU for finishing this

**Comment by bruceharrison1984** [comment]
@stephybun I've got no complaints with someone improving the codebase, and showing me a better way.

Thanks!
