### PR TITLE
`azurerm_monitor_aad_diagnostic_setting` - remove validation on `log.category`

### LINKED ISSUE #15416: `azurerm_monitor_aad_diagnostic_setting` missing support for `NetworkAccessTrafficLogs` log category
<!---
Please note the following potential times when an issue might be in Terraform core:

* [Configuration Language](https://www.terraform.io/docs/configuration/index.html) or resource ordering issues
* [State](https://www.terraform.io/docs/state/index.html) and [State Backend](https://www.terraform.io/docs/backends/index.html) issues
* [Provisioner](https://www.terraform.io/docs/provisioners/index.html) issues
* [Registry](https://registry.terraform.io/) issues
* Spans resources across multiple providers

If you are running into one of these scenarios, we recommend opening an issue in the [Terraform core repository](https://github.com/hashicorp/terraform/) instead.
--->

<!--- Please keep this note for the community --->

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

<!--- Thank you for keeping this note for the community --->

### Terraform (and AzureRM Provider) Version

<!--- Please run `terraform -v` to show the Terraform core version and provider version(s). If you are not running the latest version of Terraform or the provider, please upgrade because your issue may have already been fixed. [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions). --->

_latest_

```
$ terraform -v
Terraform v1.1.5
+ provider registry.terraform.io/hashicorp/azurerm v2.96.0
```


### Affected Resource(s)

<!--- Please list the affected resources and data sources. --->

* `azurerm_monitor_aad_diagnostic_setting`

### Terraform Configuration Files

<!--- Information about code formatting: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code --->

```hcl
resource "azurerm_monitor_aad_diagnostic_setting" "aad_diagnostic_setting" {
  name = "aad-diagnostic-setting"
  storage_account_id = "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Storage/storageAccounts/<redacted>"

  log {
    category = "SignInLogs"
    enabled  = true
    retention_policy {}
  }
  log {
    category = "AuditLogs"
    enabled  = true
    retention_policy {}
  }
  log {
    category = "NonInteractiveUserSignInLogs"
    enabled  = true
    retention_policy {}
  }
  log {
    category = "ServicePrincipalSignInLogs"
    enabled  = true
    retention_policy {}
  }
  log {
    category = "ManagedIdentitySignInLogs"                                                                                                                                                                                                                                                                                                                                   enabled  = true
    retention_policy {}
  }
  log {
    category = "ProvisioningLogs"
    enabled  = true
    retention_policy {}
  }
  log {
    category = "ADFSSignInLogs"
    enabled  = true
    retention_policy {}
  }
  log {
    category = "RiskyUsers"
    enabled  = true
    retention_policy {}
  }
  log {
    category = "UserRiskEvents"
    enabled  = true
    retention_policy {}
  }
  # You can't put the following block, otherwise the error below happens
  log {
    category = "NetworkAccessTrafficLogs"
    enabled = false
    retention_policy {}
  }
}
```



### Debug Output

N/A not useful

### Panic Output

N/A not useful

### Expected Behaviour

Deploy should happen without error.

### Actual Behaviour

If you put the last block I specified the following occurs.

_Error: expected log.3.category to be one of [AuditLogs SignInLogs ADFSSignInLogs ManagedIdentitySignInLogs NonInteractiveUserSignInLogs ProvisioningLogs ServicePrincipalSignInLogs RiskyUsers UserRiskEvents], got NetworkAccessTrafficLogs_

If you instead leave that last block out you get a forever re-applying loop that looks like this.

```
        log {                                                                                                                                                                                                                                                                                                                                                                        category = "ManagedIdentitySignInLogs"
            enabled  = true

            retention_policy {
                days    = 0
                enabled = false
            }
        }
      - log {
          - category = "NetworkAccessTrafficLogs" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
        log {
            category = "NonInteractiveUserSignInLogs"
            enabled  = true

            retention_policy {
                days    = 0
                enabled = false                                                                                                                                                                                                                                                                                                                                                      
     }
        }
        log {
            category = "ProvisioningLogs"
            enabled  = true

            retention_policy {
                days    = 0
                enabled = false
            }
        }
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

N/A

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
--->

* https://github.com/MicrosoftDocs/azure-docs/issues/87926
   * This particular diagnostic setting is not documented publically or in preview anywhere I could find. I wrote up a different issue with Microsoft docs to document this.

### Suggested Fix
Add the category item `NetworkAccessTrafficLogs` to https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/monitor/monitor_aad_diagnostic_setting_resource.go#L104

I doesn't look like this will require a dependency update. One question I don't know the answer to is if this particular category item is universal across all Azure Active Directory Tenants at this point.

### PR DESCRIPTION
**Pull request by stephybun**
Closes  #15416

### CODE REVIEW

File: internal/services/monitor/monitor_aad_diagnostic_setting_resource.go [hunk 1]
```diff
@@ -92,17 +92,6 @@ func resourceMonitorAADDiagnosticSetting() *pluginsdk.Resource {
 						"category": {
 							Type:     pluginsdk.TypeString,
 							Required: true,
-							ValidateFunc: validation.StringInSlice([]string{
```
Comment (tombuildsstuff) [inline internal/services/monitor/monitor_aad_diagnostic_setting_resource.go:95]: are these values covered in the docs?

**Review by tombuildsstuff — APPROVED** [review]
One thought about the docs but this otherwise LGTM 👍

File: internal/services/monitor/monitor_aad_diagnostic_setting_resource.go (hunk 1 above)
Comment (stephybun) [reply internal/services/monitor/monitor_aad_diagnostic_setting_resource.go:95]: Good point.
