### PR TITLE
`azurerm_automation_software_update_configuration` - Refactor and add correct API constraints.

### LINKED ISSUE #21970: azurerm_automation_software_update_configuration | monthly_occurance issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.58.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_automation_software_update_configuration" "current" {
  name                  = "schedule-test"
  automation_account_id = azurerm_automation_account.current.id
  operating_system      = "Linux"
  virtual_machine_ids   = ["<redacted>"]
  duration              = "PT2H"

  schedule {
    is_enabled = true
    frequency  = "Month"
    interval   = 1
    time_zone  = "Etc/UTC"
    start_time = "2023-06-30T18:00:00-00:00"

    monthly_occurrence {
      day        = "Tuesday"
      occurrence = 5
    }
  }

  linux {
    classification_included = "Critical"
    reboot                  = "IfRequired"
  }
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # azurerm_automation_software_update_configuration.current will be updated in-place
  ~ resource "azurerm_automation_software_update_configuration" "current" {
        id                       = "<redacted>"
        name                     = "schedule-test"
        # (7 unchanged attributes hidden)

      ~ schedule {
            # (14 unchanged attributes hidden)

          - monthly_occurrence {
              - day        = "Tuesday" -> null
              - occurrence = 5 -> null
            }
          - monthly_occurrence {
              - day        = "Tuesday" -> null
              - occurrence = 5 -> null
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
azurerm_automation_software_update_configuration.current: Modifying... [id=<redacted>]
azurerm_automation_software_update_configuration.current: Modifications complete after 1s [id=<redacted>]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
```


### Expected Behaviour

1. The `azurerm_automation_software_update_configuration` resource should show no changes on plans and applies when there were no modifications to it. 

2. Terraform state should not have duplicate `monthly_occurrence` blocks when the Terraform configuration, Azure portal, and Azure CLI all show only one `monthly_occurrence` block.

### Actual Behaviour

Terraform sees multiple `monthly_occurrence` blocks with the same configuration even though only one is passed in. It then wants to remove the ones that are not reflected in the configuration files. Viewing the resource in the portal or CLI reflects that there is only one `monthly_occurrence` configured on the resource, yet the state file reflects there are multiple.

### Steps to Reproduce

1. `terraform apply` with only one `monthly_occurrence` block configured in the `azurerm_automation_software_update_configuration` resource.
2. `terraform plan` or `terraform apply` again and you will observe the behavior

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jackofallops**
Adds schema validation and restrictions based on API limits / requirements:
* `operating_system` has been deprecated and is now controlled by the presence of either a `linux` or `windows` block.
* One of `linux` or `windows` block must now be present. This is a requirement of the API, so is a non-breaking `Optional` to `Required` change.
* `monthly_occurrence` - blocks limited to `1` due to:
```
Failure responding to request: StatusCode=400 -- Original Error:
        autorest/azure: Service returned an error. Status=400 Code="BadRequest"
        Message="{\"Message\":\"The request is
        invalid.\",\"ModelState\":{\"softwareUpdateConfiguration.properties.scheduleInfo.advancedSchedule.monthlyOccurrences\":[\"More
        than one Monthly Occurrence is not supported\"]}}"
```
* `duration` now defaults to `PT2H` as per the service.
* `schedule` block is now limited to `1`, to match the API limit.
* `schedule` block is now `Required` to match the API specification. The API  rejects requests that do not specify this block, with at least a `frequency` value.
* `frequency` is now a `Required` property of the `schedule` block. This is to match the minimum requirements of the API.
* `pre_task` blocks are now limited to `1` to match the API
* `post_task` blocks are now limited to `1` to match the API

closes #21970

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM aside from one comment ☁️

File: internal/services/automation/automation_software_update_configuration_resource_test.go [hunk 1]
```diff
@@ -451,7 +623,7 @@ provider "azurerm" {
 
 resource "azurerm_resource_group" "test" {
   name     = "acctestRG-auto-%[1]d"
-  location = "West US"
```
Comment (wuxu92) [inline internal/services/automation/automation_software_update_configuration_resource_test.go:454]: Use a random location will cause test failure, because the [required log analytics workspace](https://aka.ms/Automation-Region-Mapping) location is not the same as the automation account's location in `EastUS` and  `EastUS2`.

image

Error as below;
```
Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Error - chosen Azure Automation does not have a Log Analytics workspace linked for operation to succeed. To know which regions are supported for linking, see our documentation at: https://aka.ms/Automation-Region-Mapping
```
