### PR TITLE
`mssql_virtual_machine` - Deprecated `encryption_enabled` and validate `storage_account_access_key`

### LINKED ISSUE #12811: azurerm_mssql_virtual_machine auto_backup encryption_password failing
### Terraform (and Provider) Versions
Terraform Version: v1.0.3
azurerm v2.70.0
random v3.1.0

### Affected resources
`azurerm_mssql_virtual_machine
`
### Terraform configuration files
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "test-rg"
  location = "West Europe"
}

resource "azurerm_network_interface" "nic" {
  name                = "nic-vmtest"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = "<subnetID>"
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_windows_virtual_machine" "vm" {
  name                = "testvm"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  size                = "Standard_D2as_v4"
  admin_username      = "adminuser"
  admin_password      = "P@$$w0rd1234!"
  network_interface_ids = [
    azurerm_network_interface.nic.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "MicrosoftSQLServer"
    offer     = "sql2016sp2-ws2019"
    sku       = "standard"
    version   = "latest"
  }
}

resource "azurerm_managed_disk" "datadisk" {
    count                = 2
    name                 = "DataDisk_${count.index +1}"
    location             = azurerm_resource_group.rg.location
    resource_group_name  = azurerm_resource_group.rg.name
    storage_account_type = "Standard_LRS"
    create_option        = "Empty"
    disk_size_gb         = 128
}

resource "azurerm_virtual_machine_data_disk_attachment" "datadisk01" {
    count              = 2
    managed_disk_id    = element(azurerm_managed_disk.datadisk.*.id, count.index)
    virtual_machine_id = element(azurerm_windows_virtual_machine.vm.*.id, count.index)
    lun                = "1${count.index}"
    caching            = "ReadWrite"
}

resource "random_password" "encryptionpassword" {
    length = 12
    special = true
}

resource "azurerm_mssql_virtual_machine" "db_vm" {
  virtual_machine_id               = azurerm_windows_virtual_machine.vm.id
  sql_license_type                 = "PAYG"
  auto_patching {
    day_of_week                            = "Saturday"
    maintenance_window_duration_in_minutes = 60
    maintenance_window_starting_hour       = 6
  }
  auto_backup {
    encryption_enabled              = true
    encryption_password             = random_password.encryptionpassword.result
    retention_period_in_days        = 14
    system_databases_backup_enabled = true
    storage_blob_endpoint           = "https://test.blob.core.windows.net/automaticbackup"
    storage_account_access_key      = "<accessKey>"
    manual_schedule {
      full_backup_frequency           = "Daily"
      full_backup_start_hour          = 4
      full_backup_window_in_hours     = 4
      log_backup_frequency_in_minutes = 60
    }
  }
}
```
### Expected behaviour
Encryption password is created and used as the encryption_password in auto_backup

### Actual behaviour
 ```
terraform plan
Error: auto_backup: `encryption_password` is required when `encryption_enabled` is true
 with azurerm_mssql_virtual_machine.db_vm,
  on main.tf line 69, in resource "azurerm_mssql_virtual_machine" "db_vm":
  69: resource "azurerm_mssql_virtual_machine" "db_vm" {
```
### Steps to Reproduce

1. terraform plan

### PR DESCRIPTION
**Pull request by cgraf-spiria**
## Community Note
* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

- Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/12811 by :
  - removing the pre-checks on `encryption_enabled` and `encryption_password` which caused the issue
  - deprecating `encryption_enabled` attribute
  - enable/disable encryption if `encryption_password` is defined or not

- Add a validation for `storage_account_access_key` to ensure it is a base64 string. Without the validation, when the users gives an invalid value, the Azure API gives an unclear base64 error which makes it hard to find the correct issue.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

Not a new resource. But I ran existing unit tests and used the compiled provider to test it works.

For state migrations please test the changes locally and provide details here, such as the versions involved in testing the migration path. For further details on testing state migration changes please see our guide on [state migrations](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-state-migrations.md#testing) in the contributor documentation. -->

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `mssql_virtual_machine` - Deprecated `encryption_enabled`. Encryption is enabled when encryption_password is set; otherwise disabled.
* `mssql_virtual_machine` - Validate `storage_account_access_key` is a base64 string.

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #12811

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/mssql/mssql_virtual_machine_resource_test.go [hunk 1]
```diff
@@ -589,7 +589,6 @@ resource "azurerm_mssql_virtual_machine" "test" {
   sql_license_type   = "PAYG"
 
   auto_backup {
```
Comment (sreallymatt) [inline internal/services/mssql/mssql_virtual_machine_resource_test.go:591]: Could we add another test for testing the legacy functionality with `encryption_enabled` set?

**Review by sreallymatt — COMMENTED** [review]
Thanks for submitting this PR @cgraf-spiria, for deprecations we follow a specific format that allows us to clean up deprecated properties in the code easily after a major release. I have left some comments inline if you wouldn't mind taking a look!

File: internal/services/mssql/mssql_virtual_machine_resource.go [hunk 2]
```diff
@@ -940,13 +939,17 @@ func flattenSqlVirtualMachineAutoBackup(autoBackup *sqlvirtualmachines.AutoBacku
...
 	// from existing config as a best effort.
-	encryptionPassword := d.Get("auto_backup.0.encryption_password").(string)
 	storageKey := d.Get("auto_backup.0.storage_account_access_key").(string)
 	blobEndpoint := d.Get("auto_backup.0.storage_blob_endpoint").(string)
+	encryptionPassword := ""
+
+	// When encryption is enabled, assign password from existing config; otherwise empty
+	if autoBackup.EnableEncryption != nil && *autoBackup.EnableEncryption {
+		encryptionPassword = d.Get("auto_backup.0.encryption_password").(string)
+	}
```
[the remark this answers is not in the document]
Comment (cgraf-spiria) [reply internal/services/mssql/mssql_virtual_machine_resource.go:946]: My reasoning is Terraform needs to look at the value of `EnableEncryption` which comes from Azure. 
This way, if encryption is disabled outside of TF, we do not copy over the password and hence correctly show the state difference.

File: internal/services/mssql/mssql_virtual_machine_resource_test.go (hunk 1 above)
Comment (cgraf-spiria) [reply internal/services/mssql/mssql_virtual_machine_resource_test.go:609]: Would that be good: https://github.com/hashicorp/terraform-provider-azurerm/pull/28223/commits/70b3835c0470e4883bafcc8d0db0a3258de6560b ?
I'm not well versed in Terraform tests and don't have a subscription available where I can run the integration tests.

File: internal/services/mssql/mssql_virtual_machine_resource.go [hunk 3]
```diff
@@ -77,9 +78,10 @@ func resourceMsSqlVirtualMachine() *pluginsdk.Resource {
 				Elem: &pluginsdk.Resource{
 					Schema: map[string]*pluginsdk.Schema{
 						"encryption_enabled": {
-							Type:     pluginsdk.TypeBool,
-							Optional: true,
-							Default:  false,
+							Type:       pluginsdk.TypeBool,
+							Optional:   true,
+							Default:    false,
+							Deprecated: "This argument is no longer used. Encryption is enabled when encryption_password is set; otherwise disabled.",
```
[the remark this answers is not in the document]
Comment (cgraf-spiria) [reply internal/services/mssql/mssql_virtual_machine_resource.go]: Done. And thanks for the feedback/review !

File: internal/services/mssql/mssql_virtual_machine_resource.go [hunk 4]
```diff
@@ -28,10 +28,12 @@ import (
 	"github.com/hashicorp/terraform-provider-azurerm/internal/tf/validation"
 	"github.com/hashicorp/terraform-provider-azurerm/internal/timeouts"
 	"github.com/hashicorp/terraform-provider-azurerm/utils"
+
```
Comment (sreallymatt) [inline internal/services/mssql/mssql_virtual_machine_resource.go:31]: Could you remove this extra space and run `go fmt` on this file to reorder imports alphabetically?

File: internal/services/mssql/mssql_virtual_machine_resource.go [hunk 5]
```diff
@@ -469,6 +465,17 @@ func resourceMsSqlVirtualMachine() *pluginsdk.Resource {
 			"tags": commonschema.Tags(),
 		},
 	}
+
+	if !features.FivePointOh() {
+		resource.Schema["auto_backup"].Elem.(*pluginsdk.Resource).Schema["encryption_enabled"] = &pluginsdk.Schema{
+			Type:       pluginsdk.TypeBool,
+			Optional:   true,
+			Default:    false,
+			Deprecated: "This argument is no longer used. Encryption is enabled when encryption_password is set; otherwise disabled.",
```
Comment (sreallymatt) [inline internal/services/mssql/mssql_virtual_machine_resource.go:474]: I missed this previously, but `Default: false` causes an inaccurate diff if you remove `encryption_enabled` from your config after you've created the virtual machine with encryption enabled. (it will say `encryption_enabled: true -> false` even though the request sent to Azure will have encryption enabled)

With deprecation messages we tend to be very specific as well. 2 minor suggestions on the schema here:

```suggestion
		resource.Schema["auto_backup"].Elem.(*pluginsdk.Resource).Schema["encryption_enabled"] = &pluginsdk.Schema{
			Type:       pluginsdk.TypeBool,
			Optional:   true,
			Computed:   true,
			Deprecated: "`encryption_enabled` has been deprecated and will be removed in v5.0 of the AzureRM Provider. Encryption is enabled when `encryption_password` is set; otherwise disabled.",
```

File: internal/services/mssql/mssql_virtual_machine_resource.go [hunk 6]
```diff
@@ -940,13 +936,17 @@ func flattenSqlVirtualMachineAutoBackup(autoBackup *sqlvirtualmachines.AutoBacku
...
 	// Password, StorageAccessKey, StorageAccountURL are not returned, so we try to copy them
 	// from existing config as a best effort.
-	encryptionPassword := d.Get("auto_backup.0.encryption_password").(string)
 	storageKey := d.Get("auto_backup.0.storage_account_access_key").(string)
 	blobEndpoint := d.Get("auto_backup.0.storage_blob_endpoint").(string)
+	encryptionPassword := ""
 
-	return []interface{}{
+	// Copy password from config only if encryption is enabled in Azure
+	if autoBackup.EnableEncryption != nil && *autoBackup.EnableEncryption {
```
Comment (sreallymatt) [inline internal/services/mssql/mssql_virtual_machine_resource.go:944]:
```suggestion
	if pointer.From(autoBackup.EnableEncryption) {
```

File: internal/services/mssql/mssql_virtual_machine_resource_test.go [hunk 7]
```diff
@@ -16,6 +16,8 @@ import (
 	"github.com/hashicorp/terraform-provider-azurerm/internal/clients"
 	"github.com/hashicorp/terraform-provider-azurerm/internal/tf/pluginsdk"
 	"github.com/hashicorp/terraform-provider-azurerm/utils"
+
```
Comment (sreallymatt) [inline internal/services/mssql/mssql_virtual_machine_resource_test.go:19]: Could you remove this extra space and run `go fmt` on this file to reorder imports alphabetically?

File: internal/services/mssql/mssql_virtual_machine_resource_test.go [hunk 8]
```diff
@@ -104,7 +106,23 @@ func TestAccMsSqlVirtualMachine_autoBackup(t *testing.T) {
...
+					check.That(data.ResourceName).ExistsInAzure(r),
+				),
+			},
+			data.ImportStep("auto_backup.0.encryption_password",
+				"auto_backup.0.storage_account_access_key",
+				"auto_backup.0.storage_blob_endpoint"),
+		)
+	}
+
+	data.ResourceTest(t, r, testSteps)
```
Comment (sreallymatt) [inline internal/services/mssql/mssql_virtual_machine_resource_test.go:125]: Instead of having it conditionally included here, it would be great if it's an entirely separate test (e.g. `TestAccMsSqlVirtualMachine_autoBackupDeprecated`) This is so that when we run our tests it's clear that this is specifically related to a deprecated property.

To make sure the test is skipped once 5.0 is released, you can add the following to the top of the test:

```golang
if features.FivePointOh() {
    t.Skip("This test is not valid in 5.0")
}
```

[Here is an example](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-breaking-changes.md?plain=1#L102-L122) in our breaking changes guide, while this example is for a deprecated resource the idea is the same

**Review by sreallymatt — COMMENTED** [review]
Thanks for making those changes @cgraf-spiria, I left a few minor suggestions, once those are in this looks good to me!

File: internal/services/mssql/mssql_virtual_machine_resource_test.go (hunk 1 above)
Comment (sreallymatt) [reply internal/services/mssql/mssql_virtual_machine_resource_test.go:609]: Provided some additional info inline for this test, as for running the tests that's no problem, we'll run them on our end before merging the PR!

File: internal/services/mssql/mssql_virtual_machine_resource_test.go (hunk 8 above)
Comment (cgraf-spiria) [reply internal/services/mssql/mssql_virtual_machine_resource_test.go]: ✅ I added a new test function `TestAccMsSqlVirtualMachine_autoBackup_AndDeprecatedEncryptionEnabled`

File: internal/services/mssql/mssql_virtual_machine_resource.go (hunk 5 above)
Comment (cgraf-spiria) [reply internal/services/mssql/mssql_virtual_machine_resource.go]: Applied the change. Good catch

**Comment by sreallymatt** [comment]
image


We've got one test failure, I had a peek at what's happening and the issue lies in the `resourceMsSqlVirtualMachineAutoBackupSettingsRefreshFunc`, specifically the default case on [line 817](https://github.com/hashicorp/terraform-provider-azurerm/pull/28223/files#diff-4889f0b8d44bfeafd004e2654956c1d012c8789db0ff88bb272d65c09513b1dcR817-R821)

Could you add the following to that switch case, and resolve the 5.0-upgrade-guide merge conflict? (or if you prefer, I can push the changes to your fork!)

```go
default:
	// To be removed in 5.0:
	// When `encryption_enabled` is not set in config, but `encryption_password` is, `v != val` will always be `true`.
	// This causes an infinite loop until the resource creation times out. To avoid this, continue to the next iteration of the loop if
	// `prop` is `encryption_enabled`.
	if !features.FivePointOh() && prop == "encryption_enabled" {
		continue
	}

	if v != val {
		return resp, "Pending", nil
	}
```

**Comment by cgraf-spiria** [comment]
I added the fix & resolved the conflict. Thanks again for helping me get this PR working, much appreciated. :)

**Review by sreallymatt — APPROVED** [review]
Thanks @cgraf-spiria, tests passed, LGTM 🚀
