### PR TITLE
`azurerm_windows_web_app` - fix change detection for `tomcat_version`

### LINKED ISSUE #28471: azurerm_windows_web_app - Tomcat version returned is different 10.0 -> 10.0.2
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.x

### AzureRM Provider Version

4.5.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "4.5.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = "REDACTED"
}

resource "azurerm_resource_group" "example" {
  name     = "examplerg-REDACTED"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "examplesp-REDACTED"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku_name            = "P1v2"
  os_type             = "Windows"
}

resource "azurerm_windows_web_app" "example" {
  name                = "examplewa-REDACTED"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {
    application_stack {
      current_stack = "java"
      java_version = "11"
      tomcat_version = "10.0"
    }
  }
}
```
```


### Debug Output/Panic Output

```shell
10.0 -> 10.0.2

The payload sent to Azure as part of the relevant PUT request has a value that is "" for javaContainerVersion, which represents the desired Tomcat version. 

this can be done post initial provisioning via portal.
```

### Expected Behaviour

_No response_

### Actual Behaviour

As of AzureRM 4.5.0, it is not possible to update an azurerm_windows_web_app 's site_config.application_stack.tomcat_version after provisioning. 
A reproduction HCL configuration follows.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by wyattfry**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This fixes the bug that prevented the `azurerm_windows_web_app` property `site_config.application_stack.tomcat_version` from updating.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] ~I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.~ **N/A**
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

[Test Running...](https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_APPSERVICE/328491?)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_windows_web_app` - fix change detection for `tomcat_version` [GH-28842]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #28471 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/appservice/windows_web_app_resource_test.go [hunk 1]
```diff
@@ -1035,6 +1057,28 @@ func TestAccWindowsWebApp_withJava110414Tomcat10020(t *testing.T) {
 	})
 }
 
+func TestAccWindowsWebApp_withJava110414TomcatUpdate(t *testing.T) {
```
Comment (sreallymatt) [inline internal/services/appservice/windows_web_app_resource_test.go:1060]: Same comment as the one on `TestAccWindowsWebApp_withJava1702EmbeddedUpdate`

Comment (wyattfry) [reply internal/services/appservice/windows_web_app_resource_test.go]: Combined

File: internal/services/appservice/windows_web_app_resource_test.go [hunk 2]
```diff
@@ -1005,6 +1005,28 @@ func TestAccWindowsWebApp_withJava1702Embedded(t *testing.T) {
 	})
 }
 
+func TestAccWindowsWebApp_withJava1702EmbeddedUpdate(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (wyattfry) [reply internal/services/appservice/windows_web_app_resource_test.go]: Combined

**Review by sreallymatt — APPROVED** [review]
Thanks @wyattfry, LGTM! 🔥
