### PR TITLE
`azurerm_container_registry_token_password` - Eliminate callilng `listCredentials`

### LINKED ISSUE #21440: Cannot perform credential operations for ACR
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.52.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry_token_password

### Terraform Configuration Files

```hcl
data "azurerm_container_registry" "acr" {
  name                = local.acr_name
  resource_group_name = data.azurerm_resource_group.acr_rg.name
}

data "azurerm_container_registry_scope_map" "scope_map" {
  name                    = "_repositories_pull"
  container_registry_name = data.azurerm_container_registry.acr.name
  resource_group_name     = data.azurerm_resource_group.acr_rg.name
}


resource "azurerm_container_registry_token" "helm_registry_token" {
  name                    = "akspulluser"
  container_registry_name = data.azurerm_container_registry.acr.name
  resource_group_name     = data.azurerm_resource_group.acr_rg.name
  scope_map_id            = data.azurerm_container_registry_scope_map.scope_map.id
}

resource "azurerm_container_registry_token_password" "helm_registry_token_password" {
  container_registry_token_id = azurerm_container_registry_token.helm_registry_token.id
  password1 {

  }
}
```

### Debug Output/Panic Output

```shell
unexpected status 400 with error: UnAuthorizedForCredentialOperations: Cannot perform credential operations for /subscriptions/REDACTED/resourceGroups/rg/providers/Microsoft.ContainerRegistry/registries/REDACTED as admin user is disabled. Kindly enable admin user as per docs: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account
```

### Expected Behaviour

I should be able to do this operation. I already using this in another project with following difference
- working with resource ACR not DATA resource
- I'm creating the ACR in the other project when creating the password works
- In the working project I store the pass to KV, here I am referencing it from kubernetes provider's helm_release resource, but I expect that I am not yet so far

### Actual Behaviour

I'am getting "Cannot perform credential operations  <> │ as admin user is disabled. Kindly enable admin user as per docs"

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #21497: regression 0.52.0: ACR token passwords returned by provider are actually the admin user passwords
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.52.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry_token_password

### Terraform Configuration Files

```hcl
locals {
  sub_id = "00000000-0000-0000-0000-000000000000" # Have your own subscription id here
  rg_name = "MY_RSG"
  acr_name = "alextestacr"
}

terraform {
  required_version = ">=1.0.0"
  backend "local" {
    path = "./terraform.tfstate"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.52.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = local.sub_id
}

resource "azurerm_container_registry" "acr" {
  name                          = local.acr_name
  resource_group_name           = local.rg_name
  location                      = "eastus"
  sku                           = "Premium"
  public_network_access_enabled = true
  zone_redundancy_enabled       = false
  admin_enabled                 = true # Now needed so we can create token secrets. Cf https://github.com/hashicorp/terraform-provider-azurerm/issues/21440
}

resource "azurerm_container_registry_token" "pull_token" {
  name                    = "alex-test-token"
  container_registry_name = local.acr_name
  resource_group_name     = local.rg_name
  scope_map_id            = "/subscriptions/${local.sub_id}/resourceGroups/${local.rg_name}/providers/Microsoft.ContainerRegistry/registries/${local.acr_name}/scopeMaps/_repositories_admin"
  depends_on              = [azurerm_container_registry.acr]
}

resource "azurerm_container_registry_token_password" "pull_token_secret" {
  container_registry_token_id = azurerm_container_registry_token.pull_token.id
  password1 {}
  password2 {}
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/afeblot/b51490758f351eedbcc60630d7618bfe
```

### Expected Behaviour

Password values returned by the resource are the actual password values of the token and can be used to login to the ACR.

### Actual Behaviour

Password values returned by the resource are in fact the admin user passwords, and can obviously not be used as token passwords to login to the ACR.

Token secret password1 found in terraform state has the value of the admin user first password.
Token secret password2 found in terraform state has the value of the admin user second password.

This is a regression of provider version 0.52.0.
Using version 0.51.0 with the same terraform configuration, i.e. even keeping the admin user enabled, returns a correct ACR token secret value.

Issue related with https://github.com/hashicorp/terraform-provider-azurerm/issues/21440

### Steps to Reproduce

terraform apply -auto-approve

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by magodo**
Fix #21440, fix #21497

## Test

Testing by comment out the `admin_enabled = true` (which is also added in #21315, not sure about the reason) in the `azurerm_container_registry` and check whether the `listCredentials` is called in the mitmproxy:

```shell
$ TF_ACC=1 go test -v -timeout=20h ./internal/services/containers -run=TestAccContainerRegistryTokenPassword_basic
=== RUN   TestAccContainerRegistryTokenPassword_basic
=== PAUSE TestAccContainerRegistryTokenPassword_basic
=== CONT  TestAccContainerRegistryTokenPassword_basic
--- PASS: TestAccContainerRegistryTokenPassword_basic (260.69s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/containers    260.700s
```

While, if I keep the `admin_enabled = true` and try to create a ACR, it wil fail with:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```

But I checked that the TC test cases are all working well, not sure what's going wrong, but probably related to the `go-azure-sdk` request header.

### CODE REVIEW

File: internal/services/containers/container_registry_token_password_resource.go [hunk 1]
```diff
@@ -453,14 +454,23 @@ PasswordGenLoop:
 			return nil, fmt.Errorf("generating password credential %s: %v", string(*password.Name), err)
 		}
 
-		res, err := clients.ContainerRegistryClient_v2021_08_01_preview.Registries.ListCredentials(ctx, registryId)
+		result, err := clients.ContainerRegistryClient_v2021_08_01_preview.Registries.GenerateCredentials(ctx, registryId, param)
```
Comment (tombuildsstuff) [inline internal/services/containers/container_registry_token_password_resource.go:457]: this would cycle the credentials however?

Comment (magodo) [reply internal/services/containers/container_registry_token_password_resource.go:454]: Wow... Forgot to delete the line above.. Thank you for catching this!

**Review by katbyte — APPROVED** [review]
LGTM 🔑
