### PR TITLE
`azurerm_kubernetes_cluster` - nil check `APIServerAccessProfile`

### LINKED ISSUE #16967: Error: The terraform-provider-azurerm_v3.7.0_x5 plugin crashed! when update azurerm_kubernetes_cluster
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "main" {
  ...

  lifecycle {
    ignore_changes = [
      private_cluster_public_fqdn_enabled,
      run_command_enabled,
    ]
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/nigelis/ef737a98ec2b3a7cf956435b2d5ee0a2
```

### Expected Behaviour

The Kubernetes cluster is updated successfully.

### Actual Behaviour

Crash.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by stephybun**
Fixes #16967

### CODE REVIEW

File: internal/services/containers/kubernetes_cluster_resource.go [hunk 1]
```diff
@@ -1369,7 +1369,13 @@ func resourceKubernetesClusterUpdate(d *pluginsdk.ResourceData, meta interface{}
...
 	if d.HasChange("run_command_enabled") {
 		updateCluster = true
-		existing.ManagedClusterProperties.APIServerAccessProfile.DisableRunCommand = utils.Bool(!d.Get("run_command_enabled").(bool))
+		if existing.ManagedClusterProperties.APIServerAccessProfile != nil {
+			existing.ManagedClusterProperties.APIServerAccessProfile.DisableRunCommand = utils.Bool(!d.Get("run_command_enabled").(bool))
+		} else {
+			existing.ManagedClusterProperties.APIServerAccessProfile = &containerservice.ManagedClusterAPIServerAccessProfile{
+				DisableRunCommand: utils.Bool(!d.Get("run_command_enabled").(bool)),
+			}
+		}
```
Comment (tombuildsstuff) [inline internal/services/containers/kubernetes_cluster_resource.go:1378]: fwiw most of the other resources tend to do this - which means we only have a single assignment to this property:

```suggestion
		if existing.ManagedClusterProperties.APIServerAccessProfile == nil {
			existing.ManagedClusterProperties.APIServerAccessProfile = &containerservice.ManagedClusterAPIServerAccessProfile{
			}
		}
		existing.ManagedClusterProperties.APIServerAccessProfile.DisableRunCommand = utils.Bool(!d.Get("run_command_enabled").(bool))
```

**Review by tombuildsstuff — APPROVED** [review]
one minor suggestion for consistency but this otherwise LGTM 👍
