### PR TITLE
azurerm_postgresql_flexible_server: fix storage_tier calculation

### LINKED ISSUE #25938: [Postgres] Changing storage_mb from 524288 to 1048576 fails with storage_tier error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.15.5

### AzureRM Provider Version

3.103.1

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
# terraform.tfstate
{
  "mode": "managed",
  "type": "azurerm_postgresql_flexible_server",
  "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
  "instances": [
    {
      "sku_name": "GP_Standard_D2s_v3",
      "storage_mb": 524288,
      "storage_tier": "P20"
    }
  ]
}

# postgres.tf.json
{
  "resource": {
    "azurerm_postgresql_flexible_server": {
      "postgres_server": {
        "sku_name": "GP_Standard_D2s_v3",
        "storage_mb": 1048576,
        "version": "14"
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
[ERROR] provider.terraform-provider-azurerm_v3.103.1_x5: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto diagnostic_detail= tf_resource_type=azurerm_postgresql_flexible_server tf_rpc=PlanResourceChange diagnostic_severity=ERROR diagnostic_summary="1 error occurred:
        * invalid 'storage_tier' "P20" for defined 'storage_mb' size '1048576', expected one of ["P30", "P40" or "P50"]
```

### Expected Behaviour

The `storage_tier` is not explicitly mentioned in `postgres.tf.json`. The provider picks the default `storage_tier` (i.e `P30` as per the documentation [here](https://registry.terraform.io/providers/hashicorp/azurerm/3.96.0/docs/resources/postgresql_flexible_server#storage_tier-defaults-based-on-storage_mb)) for the storage_mb of `1048576`.

### Actual Behaviour

Changing `storage_mb` from `524288` to `1048576` fails due to invalid `storage_tier` "P20". 

### Steps to Reproduce

1. Setup a new Azure PostgreSQL Flexible Server with  `storage_mb` as `524288`. 
2. Change the  storage_mb to `1048576`. 

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by HappyTobi**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description
The PR fix an issue with `azurerm_postgresql_flexible_server`.
The issue can be reproduces when deploying an instance without a `storage_tier` property.
The redeployment of the same instance will fail when updating the `storage_mb` without setting the `storage_tier`.

The fix will handle the "autoupdate" of the `storage_tier` property when the value is not updated manually. (like the azure portal).

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

 
## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

For state migrations please test the changes locally and provide details here, such as the versions involved in testing the migration path. For further details on testing state migration changes please see our guide on [state migrations](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-state-migrations.md#testing) in the contributor documentation. -->

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25938

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 1]
```diff
@@ -382,7 +382,6 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
 			}
 
 			newMb = newStorageMbRaw.(int)
-			newTier = newTierRaw.(string)
```
Comment (neil-yechenwei) [inline internal/services/postgres/postgresql_flexible_server_resource.go:385]: I assume that the root cause is TF always returns the value in the previous apply when `storage_tier` isn't set in the tf config once `Computed: true` is added in the schema. So we may need to use `IsExplicitlyNullInConfig` to check if it's set in the tf config. Below is the potential fix.

```
// storage_tier is added `Computed: true` so that TF always returns the value in the previous apply when `storage_tier` isn't set in the tf config. So we need to use `IsExplicitlyNullInConfig` to check if it's set in the tf config
			if v := diff.GetRawConfig().AsValueMap()["storage_tier"]; v.IsNull() {
				newTierRaw = ""
			}
```

File: internal/services/postgres/validate/flexible_server_storage_tier.go [hunk 2]
```diff
@@ -88,3 +91,15 @@ func InitializeFlexibleServerStorageTierDefaults() map[int]StorageTiers {
 
 	return storageTiersMappings
 }
+
+// CompareAzureManagedDiskPerformancef returns an bool comparing two AzureManagedDiskPerformanceTiers.
+// The result will be false if disk == compareDisk, false if disk < compareDisk, and true if disk > compareDisk.
+func CompareAzureManagedDiskPerformance(disk, compareDisk servers.AzureManagedDiskPerformanceTiers) bool {
```
Comment (neil-yechenwei) [inline internal/services/postgres/validate/flexible_server_storage_tier.go:97]: I assume that we don't need it anymore if using "IsExplicitlyNullInConfig" to fix the issue.

File: internal/services/postgres/validate/flexible_server_storage_tier_test.go [hunk 3]
```diff
@@ -0,0 +1,30 @@
+// Copyright (c) HashiCorp, Inc.
```
Comment (neil-yechenwei) [inline internal/services/postgres/validate/flexible_server_storage_tier_test.go:1]: I assume that we don't need it anymore if using "IsExplicitlyNullInConfig" to fix the issue.

File: internal/services/postgres/postgresql_flexible_server_resource.go (hunk 1 above)
Comment (neil-yechenwei) [inline internal/services/postgres/postgresql_flexible_server_resource.go:385]: I assume that the root cause is TF always gets the value in the previous apply when `storage_tier` isn't set in the tf config once `Computed: true` is added in the schema. So we may need to use `IsExplicitlyNullInConfig` to check if it's set in the tf config . Below is the sample for the fix.

```
oldTierRaw, newTierRaw := diff.GetChange("storage_tier")

// storage_tier is added `Computed: true` so that TF always gets the value in the previous apply when `storage_tier` isn't set in the tf config. So we need to use `IsExplicitlyNullInConfig` to check if it's set in the tf config
			if v := diff.GetRawConfig().AsValueMap()["storage_tier"]; v.IsNull() {
				newTierRaw = ""
			}
```

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 4]
```diff
@@ -382,7 +382,6 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
...
```
Comment (neil-yechenwei) [inline internal/services/postgres/postgresql_flexible_server_resource.go:385]: I assume that expandArmServerStorage also needs to be update since d.GetOk("storage_tier") would always gets the value in the previous apply when it isn't set in the tf config. It's unexpected. Below is the sample for the fix.

```
// storage_tier is added `Computed: true` so that TF always returns the value in the previous apply when `storage_tier` isn't set in the tf config. So we need to use `IsExplicitlyNullInConfig` to check if it's set in the tf config
	if !pluginsdk.IsExplicitlyNullInConfig(d, "storage_tier") {
		if v, ok := d.GetOk("storage_tier"); ok {
			storage.Tier = pointer.To(servers.AzureManagedDiskPerformanceTiers(v.(string)))
		}
	}
```

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 5]
```diff
@@ -382,7 +382,6 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
...
 
 			// storage_mb can only be scaled up...
```
Comment (neil-yechenwei) [inline internal/services/postgres/postgresql_flexible_server_resource.go:386]: I assume that resourcePostgresqlFlexibleServerUpdate also needs to be updated since currently the update func wouldn't set the default value for storage_mb and storage_tier when they aren't set in the tf config. Below is the sample for the fix.

```
storage := expandArmServerStorage(d)
		var storageMb int

		if storage.StorageSizeGB == nil || *storage.StorageSizeGB == 0 {
			// set the default value for storage_mb...
			storageMb = 32768
			storage.StorageSizeGB = pointer.FromInt64(int64(32))
			log.Printf("[DEBUG]: Default 'storage_mb' Set -> %d\n", storageMb)
		} else {
			storageMb = int(*storage.StorageSizeGB) * 1024
		}

		if storage.Tier == nil || *storage.Tier == "" {
			// determine the correct default storage_tier based
			// on the defined storage_mb...
			storageTierMappings := validate.InitializeFlexibleServerStorageTierDefaults()
			storageTiers := storageTierMappings[storageMb]
			storage.Tier = pointer.To(storageTiers.DefaultTier)
			log.Printf("[DEBUG]: Default 'storage_tier' Set -> %q\n", storageTiers.DefaultTier)
		}

		storageUpdateParameters := servers.ServerForUpdate{
			Properties: &servers.ServerPropertiesForUpdate{
				Storage: storage,
			},
		}
```

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 6]
```diff
@@ -382,7 +382,6 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
...
 			if newMb < oldStorageMbRaw.(int) {
```
Comment (neil-yechenwei) [inline internal/services/postgres/postgresql_flexible_server_resource.go:387]: Suggest add test case for this issue. Below is the sample for the test case.

```
func TestAccPostgresqlFlexibleServer_updateOnlyWithStorageMb(t *testing.T) {
	data := acceptance.BuildTestData(t, "azurerm_postgresql_flexible_server", "test")
	r := PostgresqlFlexibleServerResource{}

	data.ResourceTest(t, r, []acceptance.TestStep{
		{
			Config: r.invalidStorageTierScaling(data, "P4", "32768"),
			Check: acceptance.ComposeTestCheckFunc(
				check.That(data.ResourceName).ExistsInAzure(r),
			),
		},
		data.ImportStep("administrator_password", "create_mode"),
		{
			Config: r.updateOnlyWithStorageMb(data, "65536"),
			Check: acceptance.ComposeTestCheckFunc(
				check.That(data.ResourceName).ExistsInAzure(r),
			),
		},
		data.ImportStep("administrator_password", "create_mode"),
	})
}

func (r PostgresqlFlexibleServerResource) updateOnlyWithStorageMb(data acceptance.TestData, storageMb string) string {
	return fmt.Sprintf(`
%s
resource "azurerm_postgresql_flexible_server" "test" {
  name                   = "acctest-fs-%d"
  resource_group_name    = azurerm_resource_group.test.name
  location               = azurerm_resource_group.test.location
  administrator_login    = "adminTerraform"
  administrator_password = "QAZwsx123"
  storage_mb             = %s
  version                = "12"
  sku_name               = "GP_Standard_D2s_v3"
  zone                   = "2"
}
`, r.template(data), data.RandomInteger, storageMb)
}
```

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 7]
```diff
@@ -382,7 +382,6 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
 			}
```
Comment (neil-yechenwei) [inline internal/services/postgres/postgresql_flexible_server_resource.go:382]: Suggest run all related test cases to ensure this fix wouldn't introduce the regression issue.

File: internal/services/postgres/validate/flexible_server_storage_tier.go [hunk 8]
```diff
@@ -4,6 +4,9 @@
 package validate
```
Comment (neil-yechenwei) [inline internal/services/postgres/validate/flexible_server_storage_tier.go:4]: I assume that we don't need it anymore if using "IsExplicitlyNullInConfig" to fix the issue.

File: internal/services/postgres/validate/flexible_server_storage_tier_test.go [hunk 9]
```diff
@@ -0,0 +1,30 @@
...
+// SPDX-License-Identifier: MPL-2.0
+
+package validate
```
Comment (neil-yechenwei) [inline internal/services/postgres/validate/flexible_server_storage_tier_test.go:4]: I assume that we don't need it anymore if using "IsExplicitlyNullInConfig" to fix the issue.

**Comment by neil-yechenwei** [comment]
Thanks for this PR - I've taken a look through and left some comments inline. If they can be addressed, we can take another look. 👍

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 10]
```diff
@@ -400,8 +399,16 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
 			// storage_mb size...
 			storageTiers := storageTierMappings[newMb]
 
+			newTier = ""
```
Comment (neil-yechenwei) [inline internal/services/postgres/postgresql_flexible_server_resource.go:402]: I assume that we don't need it anymore if using "IsExplicitlyNullInConfig" to fix the issue.

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 11]
```diff
@@ -400,8 +399,16 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
...
+
+			// set new tier only when tier is changed or when value is faster than default
+			if oldTierRaw.(string) != newTierRaw.(string) || validate.CompareAzureManagedDiskPerformance(servers.AzureManagedDiskPerformanceTiers(newTierRaw.(string)), storageTiers.DefaultTier) {
+				newTier = newTierRaw.(string)
+			}
+
 			if newTier == "" {
 				newTier = string(storageTiers.DefaultTier)
+				diff.SetNew("storage_tier", newTier)
```
Comment (neil-yechenwei) [inline internal/services/postgres/postgresql_flexible_server_resource.go:411]: I assume that we don't need it anymore if using "IsExplicitlyNullInConfig" to fix the issue.

**Comment by neil-yechenwei** [comment]
Thanks for this PR - I've taken a look through and left some comments inline, but if we can fix those up then we should be able to take another look through here. Maybe this [draft PR](https://github.com/hashicorp/terraform-provider-azurerm/compare/main...neil-yechenwei:fixstoragetier?expand=1) would be helpful.

Thanks!

File: internal/services/postgres/postgresql_flexible_server_resource.go (hunk 11 above)
Comment (HappyTobi) [reply internal/services/postgres/postgresql_flexible_server_resource.go:411]: Hi @neil-yechenwei, I added it, to make it visible while running the "plan" / "deploy" action.

For sure technically it's not required.
So should I remove it?

Comment (neil-yechenwei) [reply internal/services/postgres/postgresql_flexible_server_resource.go:411]: Seems your fix also can resolve this issue.

Comment (neil-yechenwei) [reply internal/services/postgres/postgresql_flexible_server_resource.go:411]: Seems expandArmServerStorage func also need to be updated accordingly, right?

Comment (HappyTobi) [reply internal/services/postgres/postgresql_flexible_server_resource.go:411]: Yes

**Comment by HappyTobi** [comment]
Test runs fine:
TF_ACC=1 go test -v ./internal/services/postgres -run=TestAccPostgresqlFlexibleServer_updateOnlyWithStorageMb -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccPostgresqlFlexibleServer_updateOnlyWithStorageMb
=== PAUSE TestAccPostgresqlFlexibleServer_updateOnlyWithStorageMb
=== CONT  TestAccPostgresqlFlexibleServer_updateOnlyWithStorageMb
--- PASS: TestAccPostgresqlFlexibleServer_updateOnlyWithStorageMb (683.51s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres      683.547s

**Comment by WodansSon** [comment]
@HappyTobi, thank you for opening this PR! Love to see the community contributions! Thank you so much for that! Looking at the linked issue and the PR, I think there maybe an easier way to fix this, but by all means please correct me if I am overlooking something. There is a hierarchy here, top level being `storage_mb`, that field trumps all, secondly is the `storage_tier`. In the update function the only thing we should have to do is get the new `storage_mb` field value and see if the current `storage_tier` is in the returned valid values for the defined `storage_mb` from the already exposed `InitializeFlexibleServerStorageTierDefaults` function. We should then check to see if the `storage_tier` is actually in the configuration file or not, as Neil has stated above. If the `storage_tier` field is not in the configuration file we should just update that field value to be the `default` value that was returned from the `InitializeFlexibleServerStorageTierDefaults` function, if it is in the configuration file and the `storage_tier` is not in the list of of valid storage tiers from the `InitializeFlexibleServerStorageTierDefaults` function, we should then raise the error that it is not a supported `storage_tier` for the defined `storage_mb`? Does that make sense, am I overlooking something?

**Comment by WodansSon** [comment]
@HappyTobi, interesting side tangent... your test name got me thinking... `updateOnlyWithStorageMb` should the reverse be possible as well (e.g., `updateOnlyWithStorageTier`) ?

**Comment by HappyTobi** [comment]
> ate that field value to be the `default` value that was returned from the `InitializeFlexibleServerStorageTierDefaults` function, if it is in the configuration file and the `storage_tier` is not in the list of of valid storage tiers from the `InitializeFlexibleServerStorageTierDefaults` function, we should then raise the error that it is not a supported `storage_tier` for the defined `storage_mb`? Does that make sense

Yes that make sense and the implementation reflect that already.
The change I've done is that I always use the "default" 'storage_tier' for the configures `storage_mb` / size.

File: internal/services/postgres/postgresql_flexible_server_resource.go (hunk 7 above)
Comment (neil-yechenwei) [reply internal/services/postgres/postgresql_flexible_server_resource.go]: There is a regression issue on the existing test case.

------- Stdout: -------
=== RUN   TestAccPostgresqlFlexibleServer_geoRestore
=== PAUSE TestAccPostgresqlFlexibleServer_geoRestore
=== CONT  TestAccPostgresqlFlexibleServer_geoRestore
    testcase.go:113: Step 3/4 error: After applying this test step, the plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # azurerm_postgresql_flexible_server.geo_restore will be updated in-place
          ~ resource "azurerm_postgresql_flexible_server" "geo_restore" {
                id                                = "/subscriptions/*******/resourceGroups/acctestRG-postgresql-240514110942768666/providers/Microsoft.DBforPostgreSQL/flexibleServers/acctest-fs-restore-240514110942768666"
                name                              = "acctest-fs-restore-240514110942768666"
              + storage_tier                      = "P4"
                # (14 unchanged attributes hidden)
                # (1 unchanged block hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccPostgresqlFlexibleServer_geoRestore (2753.46s)
FAIL

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 12]
```diff
@@ -400,6 +400,13 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
 			// storage_mb size...
 			storageTiers := storageTierMappings[newMb]
 
+			// set default tier for storage when there is now configuration available
+			if v := diff.GetRawConfig().AsValueMap()["storage_tier"]; v.IsNull() {
+				newTier = string(storageTiers.DefaultTier)
+				// set the new value that the update function will pickup and deploy new new storage tier.
+				diff.SetNew("storage_tier", newTier)
+			}
```
Comment (WodansSon) [inline internal/services/postgres/postgresql_flexible_server_resource.go:408]: I think we can remove all of this code and handle everything in the `!isValid` check below:

```suggestion
```

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 13]
```diff
@@ -400,6 +400,13 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
...
+
```
Comment (WodansSon) [inline internal/services/postgres/postgresql_flexible_server_resource.go:409]: What do you think if we just replace the current `if !isValid {` code below with this instead:
```suggestion
			if !isValid {
				if strings.EqualFold(oldTierRaw.(string), newTier) {
					// The tier value did not change, so we need to determin if they are
					// using the default value for the tier, or they actually defined the
					// tier in the config or not... If they did not define
					// the tier in the config we need to assign a new valid default
					// tier for the newMb value. However, if the tier is in the config
					// this is a valid error and should be returned...
					if v := diff.GetRawConfig().AsValueMap()["storage_tier"]; v.IsNull() {
						diff.SetNew("storage_tier", string(storageTiers.DefaultTier))
						log.Printf("[DEBUG]: 'storage_tier' was not valid and was not in the config assigning new default 'storage_tier' %q -> %q\n", newTier, storageTiers.DefaultTier)
						return nil
					}
				}

				return fmt.Errorf("invalid 'storage_tier' %q for defined 'storage_mb' size '%d', expected one of [%s]", newTier, newMb, azure.QuotedStringSlice(*storageTiers.ValidTiers))
			}
```

File: internal/services/postgres/postgresql_flexible_server_resource_test.go [hunk 14]
```diff
@@ -524,6 +524,48 @@ func TestAccPostgresqlFlexibleServer_invalidStorageTierScalingStorageMbStorageTi
 	})
 }
 
+func TestAccPostgresqlFlexibleServer_updateOnlyWithStorageMb(t *testing.T) {
```
Comment (WodansSon) [inline internal/services/postgres/postgresql_flexible_server_resource_test.go:527]: I think this is a great start to the test coverage, yet I think there are many more scenarios around this especially if we are now setting defaults when storage mb changes. I would like to see tests for storage tier set above storage tier default value, then remove the storage tier from the configuration (e.g., storage mb set to `65536` with a storage tier of `P10` in the config file) then remove the storage tier `P10` in the config. It should then revert tier from `P10` -> `P6`, etc. Does that make sense?

**Review by WodansSon — CHANGES_REQUESTED** [review]

File: internal/services/postgres/postgresql_flexible_server_resource.go (hunk 13 above)
Comment (HappyTobi) [reply internal/services/postgres/postgresql_flexible_server_resource.go:409]: Will move the logic to the  `!isValid` block.
The result will be the same at the end.

**Review by WodansSon — APPROVED** [review]
@HappyTobi, thanks for pushing those changes, this LGTM now! 🚀
