### PR TITLE
`azurerm_container_registry_task` - Fix missing `authentication` when updating

### LINKED ISSUE #16959: azurerm_container_registry_task unable to update after a successful creation.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.7

### Affected Resource(s)/Data Source(s)

azurerm_container_registry_task

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry_task" "acr_task_build_push" {
  name                  = "${module.naming-conventions.prefix}-build-push-on-commit-pr-main-ecs"
  container_registry_id = azurerm_container_registry.acr.id
  platform {
    os = "Linux"
  }
  docker_step {
    dockerfile_path      = "ecs/ecs.Dockerfile"
    context_path         = "https://EnterpriseCloudSolutions@dev.azure.com/EnterpriseCloudSolutions/EcsAgents/_git/ecsAgents#main:container"
    context_access_token = var.ado_pat_ecs
    image_names          = ["enterprise-containerized-agents:latest"]
  }

  source_trigger {
    name           = "test_trigger"
    events         = ["commit", "pullrequest"]
    repository_url = "https://EnterpriseCloudSolutions@dev.azure.com/EnterpriseCloudSolutions/EcsAgents/_git/ecsAgents"
    source_type    = "VisualStudioTeamService"
    authentication {
      token      = var.ado_pat_ecs
      token_type = "PAT"
    }
    branch  = "main"
    enabled = true
  }

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_container_registry_task.acr_task_build_push_eads: Modifying... [id=/subscriptions/***/resourceGroups/use-ecs-foundation-rg-ops/providers/Microsoft.ContainerRegistry/registries/***/tasks/use-ecs-build-push-on-commit-pr-main-eads]
╷
│ Error: updating Container Registry Task: (Task Name "use-ecs-build-push-on-commit-pr-main-ecs" / Registry Name "***" / Resource Group "use-ecs-foundation-rg-ops"): containerregistry.TasksClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidInputValue" Message="Some of the properties of 'taskCreateParameters' are invalid.. InnerErrors: SourceProperties:Missing required property 'SourceControlAuthProperties'." Target="request" Details=[{"code":"MissingRequiredProperty","message":"Missing required property 'SourceControlAuthProperties'.","target":"SourceProperties"}]
│ 
│   with azurerm_container_registry_task.acr_task_build_push_ecs,
│   on main.tf line 197, in resource "azurerm_container_registry_task" "acr_task_build_push_ecs":
│  197: resource "azurerm_container_registry_task" "acr_task_build_push_ecs" {
│ 
│ updating Container Registry Task: (Task Name
│ "use-ecs-build-push-on-commit-pr-main-ecs" / Registry Name
│ "***" / Resource Group "use-ecs-foundation-rg-ops"):
│ containerregistry.TasksClient#Create: Failure sending request:
│ StatusCode=400 -- Original Error: Code="InvalidInputValue" Message="Some of
│ the properties of 'taskCreateParameters' are invalid.. InnerErrors:
│ SourceProperties:Missing required property 'SourceControlAuthProperties'."
│ Target="request"
│ Details=[{"code":"MissingRequiredProperty","message":"Missing required
│ property 'SourceControlAuthProperties'.","target":"SourceProperties"}]
```

### Expected Behaviour

azurerm_container_registry_task.acr_task_build_push_eads: completed

### Actual Behaviour

[logs.txt](https://github.com/hashicorp/terraform-provider-azurerm/files/8774287/logs.txt)

### Steps to Reproduce

The first apply will be successful.

Then I simply rerun my pipeline without any changes.

1. terraform init
2. terraform plan -out=tffile
3. terraform fmt
4. terraform apply 'tffile'
5. │ Error: updating Container Registry Task: (Task Name "use-ecs-build-push-on-commit-pr-main-ecs" / Registry Name "***" / Resource Group "use-ecs-foundation-rg-ops"): containerregistry.TasksClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidInputValue" Message="Some of the properties of 'taskCreateParameters' are invalid.. InnerErrors: SourceProperties:Missing required property 'SourceControlAuthProperties'." Target="request" Details=[{"code":"MissingRequiredProperty","message":"Missing required property 'SourceControlAuthProperties'.","target":"SourceProperties"}]

### Important Factoids

Running the agent in an azure container instance

### References

N/A

### PR DESCRIPTION
**Pull request by magodo**
Fix #16959

The `source_trigger.authentication` is not returned in the GET response. When there is an update to other attributes other than `source_trigger`, as we conditionally expand `source_trigger` (only when it `HasChanged`), the content of `source_trigger` was from the GET response, therefore missing the `source_trigger.authentication`. API then complains.

This PR adds a special patch to the `source_trigger.authentication` in this case, right after the conditional expansion.

## Test

```shell
❯ TF_ACC=1 go test -timeout=60m -v -run='TestAccContainerRegistryTask_dockerStepSourceTrigger' ./internal/services/containers
=== RUN   TestAccContainerRegistryTask_dockerStepSourceTrigger                                                                                                                              === PAUSE TestAccContainerRegistryTask_dockerStepSourceTrigger
=== CONT  TestAccContainerRegistryTask_dockerStepSourceTrigger
--- PASS: TestAccContainerRegistryTask_dockerStepSourceTrigger (236.26s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/containers    236.271s
```

### CODE REVIEW

File: internal/services/containers/container_registry_task_resource.go [hunk 1]
```diff
@@ -897,9 +897,18 @@ func (r ContainerRegistryTaskResource) Update() sdk.ResourceFunc {
...
 			}
+
 			if metadata.ResourceData.HasChange("base_image_trigger") || metadata.ResourceData.HasChange("source_trigger") || metadata.ResourceData.HasChange("timer_trigger") {
 				existing.TaskProperties.Trigger = expandRegistryTaskTrigger(model)
 			}
+
+			if existing.TaskProperties.Trigger != nil {
+				if !metadata.ResourceData.HasChange("source_triggers") {
+					// For update that is not affecting source_triggers, we need to patch the source_triggers to include the properties missing in the response of GET.
+					patchRegistryTaskTriggerSourceTrigger(existing.TaskProperties.Trigger.SourceTriggers, model)
```
Comment (tombuildsstuff) [inline internal/services/containers/container_registry_task_resource.go:908]: fwiw returning the value/assigning this makes this clearer to readers what's going on here:

```suggestion
					existing.TaskProperties.Trigger.SourceTriggers = patchRegistryTaskTriggerSourceTrigger(existing.TaskProperties.Trigger.SourceTriggers, model)
```

**Review by tombuildsstuff — APPROVED** [review]
One comment about readability but this otherwise LGTM 👍

**Comment by magodo** [comment]
@tombuildsstuff Thank you for the comment! I've refine it and please take another look!

File: internal/services/containers/container_registry_task_resource.go [hunk 2]
```diff
@@ -897,9 +897,18 @@ func (r ContainerRegistryTaskResource) Update() sdk.ResourceFunc {
...
 			}
+
 			if metadata.ResourceData.HasChange("base_image_trigger") || metadata.ResourceData.HasChange("source_trigger") || metadata.ResourceData.HasChange("timer_trigger") {
 				existing.TaskProperties.Trigger = expandRegistryTaskTrigger(model)
 			}
+
+			if existing.TaskProperties.Trigger != nil {
+				if !metadata.ResourceData.HasChange("source_triggers") {
+					// For update that is not affecting source_triggers, we need to patch the source_triggers to include the properties missing in the response of GET.
+					existing.TaskProperties.Trigger.SourceTriggers = patchRegistryTaskTriggerSourceTrigger(existing.TaskProperties.Trigger.SourceTriggers, model)
```
Comment (tombuildsstuff) [inline internal/services/containers/container_registry_task_resource.go:908]: fwiw you can remove all of the de-references (and the nil-check, since it's covered above) below if we do it here instead:

```suggestion
					existing.TaskProperties.Trigger.SourceTriggers = patchRegistryTaskTriggerSourceTrigger(*existing.TaskProperties.Trigger.SourceTriggers, model)
```

File: internal/services/containers/container_registry_task_resource.go [hunk 3]
```diff
@@ -1618,3 +1627,28 @@ func flattenRegistryTaskAgentProperties(input *legacyacr.AgentProperties) []Agen
...
+		}
+		if t.SourceRepository == nil {
+			result[i] = t
+			continue
+		}
+		t.SourceRepository.SourceControlAuthProperties = expandRegistryTaskAuthInfo(trigger.Auth[0])
+		result[i] = t
+	}
+	return &result
+}
```
Comment (tombuildsstuff) [inline internal/services/containers/container_registry_task_resource.go:1654]: meaning this can become:

```suggestion
func patchRegistryTaskTriggerSourceTrigger(triggers []legacyacr.SourceTrigger, model ContainerRegistryTaskModel) *[]legacyacr.SourceTrigger {
	if len(triggers) != len(model.SourceTrigger) {
		return triggers
	}

	result := make([]legacyacr.SourceTrigger, len(triggers))
	for i, trigger := range model.SourceTrigger {
		t := triggers[i]
		if len(trigger.Auth) == 0 {
			result[i] = t
			continue
		}
		if t.SourceRepository == nil {
			result[i] = t
			continue
		}
		t.SourceRepository.SourceControlAuthProperties = expandRegistryTaskAuthInfo(trigger.Auth[0])
		result[i] = t
	}
	return &result
}
```

File: internal/services/containers/container_registry_task_resource.go [hunk 4]
```diff
@@ -897,9 +897,18 @@ func (r ContainerRegistryTaskResource) Update() sdk.ResourceFunc {
 			if metadata.ResourceData.HasChange("docker_step") || metadata.ResourceData.HasChange("file_step") || metadata.ResourceData.HasChange("encoded_step") {
 				existing.TaskProperties.Step = expandRegistryTaskStep(model)
 			}
+
 			if metadata.ResourceData.HasChange("base_image_trigger") || metadata.ResourceData.HasChange("source_trigger") || metadata.ResourceData.HasChange("timer_trigger") {
 				existing.TaskProperties.Trigger = expandRegistryTaskTrigger(model)
 			}
+
+			if existing.TaskProperties.Trigger != nil {
+				if !metadata.ResourceData.HasChange("source_triggers") {
```
Comment (tombuildsstuff) [inline internal/services/containers/container_registry_task_resource.go:906]:
```suggestion
				if !metadata.ResourceData.HasChange("source_triggers") && existing.TaskProperties.Trigger.SourceTriggers != nil {
```

**Review by tombuildsstuff — APPROVED** [review]
If we de-reference this prior to passing this in, we remove doing that from within the method, which removes some of the complexity/potential bugs fwiw - but this otherwise LGTM 👍
