### PR TITLE
`azurerm_managed_application` - extend supported types for `parameters`/`parameter_values`/`output` and deprecate `parameters`

### LINKED ISSUE #13427: Unexpected parameter type when processing output from Azure Managed Application
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azuread v2.3.0
+ provider registry.terraform.io/hashicorp/azurerm v2.77.0

### Affected Resource(s)

* `azurerm_managed_application`

### Terraform Configuration Files

```hcl
resource "azurerm_managed_application" "vmx" {
  name                = "meraki-vmx"
  location            = azurerm_resource_group.vmx.location
  resource_group_name = azurerm_resource_group.vmx.name
  kind                = "MarketPlace"
  managed_resource_group_name = "meraki-vmx-managed"

  plan {
    name      = "cisco-meraki-vmx"
    product   = "cisco-meraki-vmx"
    publisher = "cisco"
    version   = "15.37.0"
  }

  parameters = {
    location                    = azurerm_resource_group.vmx.location
    vmName                      = "meraki-vmx"
    virtualMachineSize          = "Standard_F4s_v2"
    merakiAuthToken             = "authtoken"
    zone                        = 0
    virtualNetworkNewOrExisting = "existing"
    virtualNetworkName          = data.azurerm_virtual_network.vnet.name
    virtualNetworkResourceGroup = data.azurerm_virtual_network.vnet.resource_group_name
    virtualNetworkAddressPrefix = data.azurerm_virtual_network.vnet.address_space[0]
    subnetName                  = data.azurerm_subnet.subnet.name
    subnetAddressPrefix         = data.azurerm_subnet.subnet.address_prefix
  }

  depends_on = [azurerm_marketplace_agreement.vmx]
}

resource "azurerm_marketplace_agreement" "vmx" {
  publisher = "cisco"
  offer     = "cisco-meraki-vmx"
  plan      = "cisco-meraki-vmx"
}

resource "azurerm_resource_group" "vmx" {
  name     = "meraki-vmx"
  location = "Australia Southeast"
}
```

### Debug Output

Debug log from running `terraform import` on the resource.
https://gist.github.com/oWretch/2aacd66e306083a8cb02e5f8e50a3a22

### Expected Behaviour

The resource creation should have completed and filled in the state information correctly. Subsequent terraform runs should read the state information from the resource and compare with the state file successfully.

### Actual Behaviour

Terraform errors with  `Error: unexpected parameter type map[string]interface {}` when reading the state of the application. Full error message:

```
│ Error: unexpected parameter type map[string]interface {}
│
│   with azurerm_managed_application.vmx,
│   on vmx.tf line 2, in resource "azurerm_managed_application" "vmx":
│    2: resource "azurerm_managed_application" "vmx" {
```
This error occurs in multiple regions.

### Steps to Reproduce

This issue occurs on creation of resource (via `terraform apply`), on plan or application of a subsequent run after the provisioning is complete, or when importing the resource into the state file.

### LINKED ISSUE #20016: azurerm_managed_application - "unexpected parameter type []interface {}"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.39.0

### Affected Resource(s)/Data Source(s)

azurerm_managed_application

### Terraform Configuration Files

```hcl
https://www.dropbox.com/s/f3d3u97wownj1se/bug_azurerm_managed_application.zip?dl=0
```

### Debug Output/Panic Output

```shell
https://gist.github.com/mtarnoci/ba5565e144379af1fe54cb3f3eab6cba
```

### Expected Behaviour

_No response_

### Actual Behaviour

I've tried to deploy Cisco SDWAN NVA in Virtual Hub from Marketplace using azurerm_managed_application resource.
NVA is deployed successfully, I can see it via Azure Console, also via CLI, however resource creation in terraform ends with error:

Error: unexpected parameter type []interface {}

│

│   with azurerm_managed_application.test-app-[0],

Same Error I can see when tried to deploy this application via Azure Portal and then import it to the Terraform.
Terraform log is provided by Gist link above.

BTW, I've tried to use azapi provider to deploy the same managed application using this resource: https://learn.microsoft.com/en-us/azure/templates/microsoft.solutions/2019-07-01/applications?pivots=deployment-language-terraform.

With AZAPI provider it is deployed successfully without error, however we would like to use AzureRM provider.

### Steps to Reproduce

simple code provided by Dropbox link above 
terraform apply -var-file example_variables_values.tfvars

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #21267: azurerm_managed_application fails to read state after provisioning
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_managed_application

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

variable "ux4iot_application_definition_id" {
  type        = string
  description = "Application Definition ID of ux4iot"
}

variable "resource_group_name" {
  type        = string
  description = "Resource group to install Service Bus ux4iot and the IoT Hub into"
  default     = "my-rg"
}

variable "location" {
  type        = string
  description = "Azure location where to deploy ux4iot and the IoT Hub into"
  default     = "WestEurope"
}

resource "azurerm_iothub" "main" {
  location            = var.location
  name                = "my-iothub"
  resource_group_name = var.resource_group_name
  sku {
    capacity = 1
    name     = "S1"
  }
}

resource "azurerm_iothub_shared_access_policy" "ux4iot" {
  iothub_name         = azurerm_iothub.main.name
  name                = "ux4iot"
  resource_group_name = var.resource_group_name
  registry_read       = true
  service_connect     = true
}

data "azurerm_iothub_shared_access_policy" "iothubowner" {
  iothub_name         = azurerm_iothub.main.name
  name                = "iothubowner"
  resource_group_name = var.resource_group_name
}

resource "azurerm_managed_application" "ux4iot" {
  application_definition_id   = var.ux4iot_application_definition_id
  kind                        = "ServiceCatalog"
  location                    = var.location
  managed_resource_group_name = "ux4iot-resources"
  name                        = "ux4iot"
  resource_group_name         = var.resource_group_name
  parameters                  = {
    iotHubEventHubConnectionString = azurerm_iothub_shared_access_policy.ux4iot.primary_connection_string
    iotHubServiceConnectionString  = "Endpoint=${azurerm_iothub.main.event_hub_events_endpoint};SharedAccessKeyName=iothubowner;SharedAccessKey=${data.azurerm_iothub_shared_access_policy.iothubowner.primary_key};EntityPath=${azurerm_iothub.main.event_hub_events_path}"
    sku = "small"
  }

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
Terraform reports the following error after successful provisioning


╷
│ Error: missing key 'value' in parameters or output map map[]
│ 
│   with module.ux4iot[0].azurerm_managed_application.ux4iot,
│   on modules/ux4iot/main.tf line 35, in resource "azurerm_managed_application" "ux4iot":
│   35: resource "azurerm_managed_application" "ux4iot" {
│ 
╵
```

The output from the `Microsoft.Solutions/applications` looks fine:
```
{
    "id": "/subscriptions/3.../resourceGroups/s.../providers/Microsoft.Solutions/applications/s...",
    "name": "s...",
    "type": "Microsoft.Solutions/applications",
    "kind": "ServiceCatalog",
    "location": "westeurope",
    "plan": {
        "name": "standard",
        "promotionCode": "",
        "product": "ux4iot",
        "publisher": "deviceinsightgmbh-4961725",
        "version": "1.5.0"
    },
    "etag": "\"9000a30e-0000-0d00-0000-642b17bb0000\"",
    "tags": {
        "environment": "int"
    },
    "properties": {
        "managedResourceGroupId": "/subscriptions/3.../resourceGroups/s...",
        "applicationDefinitionId": "/subscriptions/a.../resourceGroups/ux4iot-shared/providers/Microsoft.Solutions/applicationDefinitions/ux4iot",
        "parameters": {
            "serverVersion": {
                "type": "String",
                "value": "3.5.0"
            },
            "traefikVersion": {
                "type": "String",
                "value": "1.0.0"
            },
            "redisVersion": {
                "type": "String",
                "value": "1.2.0"
            },
            "iotHubEventHubConnectionString": {
                "type": "SecureString"
            },
            "iotHubServiceConnectionString": {
                "type": "SecureString"
            },
            "primaryAdminSecret": {
                "type": "SecureString"
            },
            "secondaryAdminSecret": {
                "type": "SecureString"
            },
            "eventHubConsumerGroup": {
                "type": "String",
                "value": "$Default"
            },
            "throttlingInterval": {
                "type": "Int",
                "value": -1
            },
            "skipCustomResource": {
                "type": "Bool",
                "value": false
            },
            "skipKeyVaultContents": {
                "type": "Bool",
                "value": false
            },
            "dnsLabelOverride": {
                "type": "String",
                "value": ""
            },
            "connectionStateCacheTTL": {
                "type": "Int",
                "value": 60
            },
            "customTimestampKey": {
                "type": "String",
                "value": "_ts"
            },
            "customDeviceIdKey": {
                "type": "String",
                "value": "deviceId"
            },
            "connectionStateOnTelemetry": {
                "type": "Bool",
                "value": true
            },
            "logLevel": {
                "type": "String",
                "value": "info"
            },
            "location": {
                "type": "String",
                "value": "westeurope"
            },
            "sku": {
                "type": "String",
                "value": "small"
            }
        },
        "provisioningState": "Succeeded",
        "authorizations": [
            {
                "principalId": "e...",
                "roleDefinitionId": "8..."
            }
        ],
        "managementMode": "Managed",
        "artifacts": [
            {
                "name": "ViewDefinition",
                "type": "Custom",
                "uri": "https://management.azure.com/subscriptions/3.../resourceGroups/s.../providers/Microsoft.Solutions/applications/s.../applicationArtifacts/ViewDefinition?api-version=2017-12-01"
            }
        ],
        "createdBy": {
            "oid": "c...",
            "puid": "1...",
            "applicationId": "0..."
        },
        "updatedBy": {
            "oid": "c...",
            "puid": "1...",
            "applicationId": "0..."
        }
    }
}
```
```


### Expected Behaviour

_No response_

### Actual Behaviour

_No response_

### Steps to Reproduce

1. `terraform apply`
2. wait for the module to crash 

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by myc2h6o**
Fix #21267
Fix #13427
Fix #20016

- Code
  - Split flatten for parameters and outputs, as `outputs` does not support secureString but `parameters` does. And moved common logic into functions.
  - while parsing secureString, use the value from local config, as it's not returned from server due to security concern.
  - fixed a bug in `expandManagedApplicationParameters`, previously it always read the value from `parameters` after `parameter_values`, which will cause an issue when updating `parameter_values`, because on the second apply, even `parameter` is not set in config, it's still present in the state from the first apply.
  - add `ForceNew` to `plan`, plan cannot be changed according to error returned by service `Code="CannotUpdatePlan"`.
- Document
  - added note in `parameters`, it only supports string and secureString due to the limitation of tf schema, for other types, `parmeter_values` could be used as it is a pure JSON string
- Test cases
  - updated `azurerm_managed_application_definition` to use inline template as dependency instead of online template to ensure stability
  - remove the old updatetest, cause it's updating forceNew properties, which is a re-creation, updates of certain properties are put into their own tests
  - added tests to cover all supported types within `parameters` and `parameter_values`
- Examples
  - added examples to use `parameters` and `parameter_values`, to show how to set parameters of different types.

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this @myc2h6o - could you add a test to validate this?

**Comment by stephybun** [comment]
Any updates @myc2h6o

**Comment by myc2h6o** [comment]
@stephybun I found some more issue while updating this pr, and I'm working on the update in a separate branch https://github.com/hashicorp/terraform-provider-azurerm/compare/main...myc2h6o:terraform-provider-azurerm:managed_app_type_backup currently, I'll update it here once I resolved all the issues

**Comment by myc2h6o** [comment]
Hi @stephybun sorry for the delayed update, I finally get this to work. I've updated the code and acc tests, and put the updated PR details into the pr descriptions, please take a look.

**Comment by myc2h6o** [comment]
Updated test result
image

**Comment by katbyte** [comment]
#21571 should probably be merged first as it will be easier to fix conflicts in this PR then that one

**Comment by myc2h6o** [comment]
@katbyte sure, I'll wait for the sdk to be upgraded first

**Comment by myc2h6o** [comment]
I have resolved conflicts after the sdk upgrade, below is the updated test result:
image

File: internal/services/managedapplications/managed_application_resource.go [hunk 1]
```diff
@@ -354,37 +366,64 @@ func flattenManagedApplicationParametersOrOutputs(input *interface{}) (map[strin
...
-					// Azure NVA managed applications read call returns empty map[string]interface{} parameter 'tags'
-					// Do not return an error if the parameter is unsupported type, but is empty
-					if len(v.(map[string]interface{})) == 0 {
-						log.Printf("parameter '%s' is unexpected type %T, but we're ignoring it because of the empty value", k, t)
-					} else {
-						return nil, fmt.Errorf("unexpected parameter type %T", t)
+					// Secure values are not returned, thus settings it with local value
+					v = ""
+					if oldValueStruct, oldValueStructOK := localParameters[k]; oldValueStructOK {
+						if oldValue, oldValueOK := oldValueStruct.(map[string]interface{})["value"]; oldValueOK {
```
Comment (manicminer) [inline internal/services/managedapplications/managed_application_resource.go:377]: I think we'll need some type-checking here because `oldValueStruct` is an `interface{}` and no guarantee that it will be a map? If it isn't, this will panic

File: internal/services/managedapplications/managed_application_resource.go [hunk 2]
```diff
@@ -394,21 +433,51 @@ func flattenManagedApplicationParameterValuesValueToString(input *interface{}) (
 		for k, v := range attrs.(map[string]interface{}) {
 			if v != nil {
 				delete(attrs.(map[string]interface{})[k].(map[string]interface{}), "type")
+
+				// Secure values are not returned, thus settings it with local value
+				value := attrs.(map[string]interface{})[k].(map[string]interface{})
+				if _, ok := value["value"]; !ok {
+					value["value"] = ""
+					if localParam, localParamOK := localParameters[k]; localParamOK {
+						if localParamValue, localParamValueOK := localParam.(map[string]interface{})["value"]; localParamValueOK {
```
Comment (manicminer) [inline internal/services/managedapplications/managed_application_resource.go:442]: As above, we should add more type-checking here

**Review by manicminer — CHANGES_REQUESTED** [review]
Thanks for updating and adding the tests @myc2h6o. I think this mostly looks good, just a couple of potential crashes I spotted, and given the messiness of this double implementation I wonder if we should consider deprecating `parameters` with a view to removing it in v4.0? Although it's an attempt at a more native implementation, it currently has to coexist with `parameter_values` because it's only a subset - we can avoid a lot of unnecessary gymnastics here by removing it. WDYT?

File: internal/services/managedapplications/managed_application_resource.go (hunk 1 above)
Comment (myc2h6o) [reply internal/services/managedapplications/managed_application_resource.go:402]: `oldValueStruct` comes from expanded blocks from terraform sdk, not from api side so we shall be able to asure it is a map.

File: internal/services/managedapplications/managed_application_resource.go (hunk 2 above)
Comment (myc2h6o) [reply internal/services/managedapplications/managed_application_resource.go:467]: `localParameters` comes from expanded blocks from terraform sdk, not from api side so we shall be able to asure it is a map.

File: internal/services/managedapplications/managed_application_resource.go (hunk 1 above)
Comment (myc2h6o) [reply internal/services/managedapplications/managed_application_resource.go]: yes make sense, have added the type check

File: internal/services/managedapplications/managed_application_resource.go (hunk 2 above)
Comment (myc2h6o) [reply internal/services/managedapplications/managed_application_resource.go]: yes make sense, have added the type check

**Comment by myc2h6o** [comment]
@manicminer thanks for reviewing the change! I've updated the code to deprecate `parameters` in 4.0 and added the type check. Please take a look.

**Comment by myc2h6o** [comment]
an example issue causes the CI failing, being fixed in #22839.

**Comment by myc2h6o** [comment]
updated test result
image

**Comment by myc2h6o** [comment]
have rebased to main to resolve the example issue fixed by #22839

**Review by manicminer — APPROVED** [review]
Thanks for updating @myc2h6o, this LGTM 👍
