### PR TITLE
azurerm_private_dns_a_record_resource - currently validate the `name` property by allowing `@`s

### LINKED ISSUE #12406: Private DNS: no error while create A record with more than 20 records
### Terraform (and AzureRM Provider) Version

Terraform v1.0.1
- Installed hashicorp/azurerm v2.66.0 (signed by HashiCorp)

### Affected Resource(s)

* `azurerm_private_dns_a_record

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_a_record" "a" {
  name                = "@"
  resource_group_name = "rg-corp-dns"
  zone_name           = "corp.com"
  ttl                 = 300
  records             = ["10.0.180.17", ...more than 20... ]
}
```

### Debug Output

```
module.corp-com-dns-zone["corp.com"].azurerm_private_dns_a_record.a["@"]: Creating...
```

### Panic Output

```
│ Error: creating/updating A Record: (A Name "@" / Private Dns Zone Name "corp.com" / Resource Group "rg-corp-dns"): privatedns.RecordSetsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
│ 
│   with module.corp-com-dns-zone["corp.com"].azurerm_private_dns_a_record.a["@"],
│   on .terraform/modules/corp-com-dns-zone/main.tf line 21, in resource "azurerm_private_dns_a_record" "a":
│   21: resource "azurerm_private_dns_a_record" "a" {
```

### Expected Behaviour

Detailed error message

### Actual Behaviour

No error message

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by stephybun**
Fixes #12406

### CODE REVIEW

File: helpers/validate/strings.go [hunk 1]
```diff
@@ -43,5 +43,9 @@ func LowerCasedString(i interface{}, k string) ([]string, []error) {
 		return nil, []error{fmt.Errorf("%q cannot contain whitespace", k)}
 	}
 
+	if strings.ContainsAny(v, "@") {
```
Comment (tombuildsstuff) [inline helpers/validate/strings.go:46]: I initially went [through the Azure naming rules since _some_ services allow these iirc](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) thinking this was used more widely than it is - but since this functions only used for Private DNS, it'd probably be worth moving this into the Private DNS package at the same time, since that's the only usage at the moment:

Screenshot 2021-08-19 at 09 21 41

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
one thought about refactoring this but this otherwise LGTM 👍

File: helpers/validate/strings.go (hunk 1 above)
Comment (stephybun) [reply helpers/validate/strings.go]: Makes sense, thanks for the input, i've moved this validation to the Private DNS package.

**Review by katbyte — APPROVED** [review]
Thanks @stephybun - LGTM now 🏗️

**Comment by calloes** [comment]
Why is this changed ? apex dns records are valid in private dns zones. Our existing code now fails.

Internal DNS zone can have a valid root record represented by @

[31m
[1m[31mError: [0m[0m[1m"name" cannot contain @[0m

[0m  on .terraform/modules/private_dns/main.tf line 7, in resource "azurerm_private_dns_a_record" "zone_root_a_record":
   7:   name                = [4m"@"[0m
[0m
[0m[0m

**Comment by stephybun** [comment]
Hello @calloes, yep you are right. We've reverted the validation on name that's causing your code to fail and added validation on the number of allowed records in this PR #13093 which will be released in v2.74.0 on Thursday.
