### PR TITLE
`azurerm_container_app_environment`: add support for `identity`

### LINKED ISSUE #28468: azurerm_container_app_environment support of manage identity
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

we are using container apps environment, 
On the Container App Environment
1: Terraform does not have an option to set managed identity (Its in the portal)
2: Azure CLI does nothave an option to set managed ideneity (Its in the portal)
3: We set this manually in the portal and rerun terraform and it sets managed ideneity off (This is expected with how terraform works, however we cant set it through terraform)

What should we do?
Can you fix this issue?

### Terraform Version

4.14

### AzureRM Provider Version

3.117

### Affected Resource(s)/Data Source(s)

azurerm_3.117

### Terraform Configuration Files

```hcl
we are using container apps environment, 
On the Container App Environment
1: Terraform does not have an option to set managed identity (Its in the portal)
2: Azure CLI does nothave an option to set managed ideneity (Its in the portal)
3: We set this manually in the portal and rerun terraform and it sets managed ideneity off (This is expected with how terraform works, however we cant set it through terraform)

What should we do?
Can you fix this issue?
```

### Debug Output/Panic Output

```shell
we are using container apps environment, 
On the Container App Environment
1: Terraform does not have an option to set managed identity (Its in the portal)
2: Azure CLI does nothave an option to set managed ideneity (Its in the portal)
3: We set this manually in the portal and rerun terraform and it sets managed ideneity off (This is expected with how terraform works, however we cant set it through terraform)

What should we do?
Can you fix this issue?
```

### Expected Behaviour

_No response_

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jiaweitao001**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #28468 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@sreallymatt this looks ripe for merge - and would also unlock other PRs depending on identity support (certificates)

File: internal/services/containerapps/container_app_environment_resource.go [hunk 1]
```diff
@@ -304,6 +308,12 @@ func (r ContainerAppEnvironmentResource) Create() sdk.ResourceFunc {
 				managedEnvironment.Properties.VnetConfiguration.Internal = pointer.To(containerAppEnvironment.InternalLoadBalancerEnabled)
 			}
 
+			ident, err := identity.ExpandSystemAndUserAssignedMapFromModel(containerAppEnvironment.Identity)
+			if err != nil {
+				return fmt.Errorf("expanding identity: %+v", err)
+			}
+			managedEnvironment.Identity = pointer.To(identity.LegacySystemAndUserAssignedMap(*ident))
```
Comment (sreallymatt) [inline internal/services/containerapps/container_app_environment_resource.go]: We can use the helper function for legacy identity maps

```suggestion
			ident, err := identity.ExpandLegacySystemAndUserAssignedMapFromModel(containerAppEnvironment.Identity)
			if err != nil {
				return fmt.Errorf("expanding `identity`: %+v", err)
			}
			managedEnvironment.Identity = ident
```

File: internal/services/containerapps/container_app_environment_resource.go [hunk 2]
```diff
@@ -343,6 +353,13 @@ func (r ContainerAppEnvironmentResource) Read() sdk.ResourceFunc {
 				state.ResourceGroup = id.ResourceGroupName
 				state.Location = location.Normalize(model.Location)
 				state.Tags = tags.Flatten(model.Tags)
+				if model.Identity != nil {
+					ident, err := identity.FlattenSystemAndUserAssignedMapToModel(pointer.To(identity.SystemAndUserAssignedMap(*model.Identity)))
+					if err != nil {
+						return err
+					}
+					state.Identity = pointer.From(ident)
```
Comment (sreallymatt) [inline internal/services/containerapps/container_app_environment_resource.go]: Here we can use the legacy flatten func, could you also wrap the error with `` flattening `identity` ... ``?

```suggestion
					ident, err := identity.FlattenLegacySystemAndUserAssignedMapToModel(model.Identity)
					if err != nil {
						return fmt.Errorf("flattening `identity`: %+v", err)
					}
					state.Identity = ident
```

File: internal/services/containerapps/container_app_environment_resource.go [hunk 3]
```diff
@@ -436,6 +453,14 @@ func (r ContainerAppEnvironmentResource) Update() sdk.ResourceFunc {
 				existing.Model.Tags = tags.Expand(state.Tags)
 			}
 
+			if metadata.ResourceData.HasChange("identity") {
+				ident, err := identity.ExpandSystemAndUserAssignedMapFromModel(state.Identity)
+				if err != nil {
+					return err
+				}
+				existing.Model.Identity = pointer.To(identity.LegacySystemAndUserAssignedMap(*ident))
```
Comment (sreallymatt) [inline internal/services/containerapps/container_app_environment_resource.go]:
```suggestion
				ident, err := identity.ExpandLegacySystemAndUserAssignedMapFromModel(state.Identity)
				if err != nil {
					return fmt.Errorf("expanding `identity`: %+v", err)
				}
				existing.Model.Identity = ident
```

File: internal/services/containerapps/container_app_environment_resource_test.go [hunk 4]
```diff
@@ -35,6 +35,36 @@ func TestAccContainerAppEnvironment_basic(t *testing.T) {
...
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.withSystemIdentity(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+			),
+		},
+		data.ImportStep(),
+	})
+}
```
Comment (sreallymatt) [inline internal/services/containerapps/container_app_environment_resource_test.go]: Could you combine these tests and update it so we cover update paths from one to another (e.g. system to user, user to system+user) as well as removing the identity block entirely?

File: website/docs/r/container_app_environment.html.markdown [hunk 5]
```diff
@@ -61,6 +61,8 @@ The following arguments are supported:
 
 ~> **Note:** can only be set to `true` if `infrastructure_subnet_id` is specified. 
 
+* `identity` - (Optional) An `identity` block as detailed below.
```
Comment (sreallymatt) [inline website/docs/r/container_app_environment.html.markdown]: Nit: generally we use `as defined`

```suggestion
* `identity` - (Optional) An `identity` block as defined below.
```

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Thanks for opening this PR @jiaweitao001, I've left a few comments inline

File: internal/services/containerapps/container_app_environment_resource.go (hunk 1 above)
Comment (jiaweitao001) [reply internal/services/containerapps/container_app_environment_resource.go]: Will change.

File: internal/services/containerapps/container_app_environment_resource.go (hunk 2 above)
Comment (jiaweitao001) [reply internal/services/containerapps/container_app_environment_resource.go]: Will fix.

File: internal/services/containerapps/container_app_environment_resource.go (hunk 3 above)
Comment (jiaweitao001) [reply internal/services/containerapps/container_app_environment_resource.go]: Will fix.

File: internal/services/containerapps/container_app_environment_resource_test.go (hunk 4 above)
Comment (jiaweitao001) [reply internal/services/containerapps/container_app_environment_resource_test.go]: Will do.

File: website/docs/r/container_app_environment.html.markdown (hunk 5 above)
Comment (jiaweitao001) [reply website/docs/r/container_app_environment.html.markdown]: Will fix.

**Review by sreallymatt — APPROVED** [review]
Thanks @jiaweitao001 LGTM! ✅
