### PR TITLE
`azurerm_subnet` - Swap `service_endpoints` from TypeList to TypeSet

### LINKED ISSUE #10087: azurerm_subnet continually updates resource depending on the order of service_endpoints
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "subnets" {
  name                      = "my-subnet"
  virtual_network_name      = azurerm_virtual_network.my_vnet.name
  resource_group_name       = azurerm_resource_group.my_rg.name
  address_prefixes          = [...]
  service_endpoints         = [
    "Microsoft.AzureCosmosDB",
    "Microsoft.Storage"
  ]
}
```

### Expected Behaviour

When Terraform inspects an existing subnet with service endpoints and the service endpoints are not declared in the same order as described in the Terraform resource, the resource is not updated. Terraform should evaluate the list of service endpoints and ensure the list contains the desired values (in any order).

Service endpoint triggered updates should only occur when the list of service endpoints differs in contents (not by the ordering of contents).

### Actual Behaviour

When Terraform inspects an existing subnet with service endpoints and the service endpoints are all present, but declared in a different order, an update-in-place is triggered. The update finishes, but the service endpoints are not re-ordered by Azure because the ordering doesn't matter.

As a result, during the next plan/apply the subnet is updated again. This continues until:
1. the Terraform file lists the subnets in the exact order as reflected in the Azure resource definition OR
2. a service endpoint is added/removed which triggers an actual update to the Azure resource and re-orders the service endpoints during the update

### Steps to Reproduce

1. Create a virtual network, add a subnet
2. Add 2 service endpoints to the subnet via the Azure CLI or Azure portal: Microsoft.AzureCosmosDB, Microsoft.Storage
3. Create a Terraform resource referencing the subnet, with the service endpoint ordering reverse of the order created: Microsoft.Storage, Microsoft.AzureCosmosDB
4. Import the resource to start tracking it in terraform state
5. `terraform plan` will show the resource needs updated
6. `terraform apply` will attempt to change the resource
7. `terraform plan` again will show the resource needs updated
8. Re-order the service endpoints in the Terraform file
9. `terraform plan` no longer shows an update is needed

### LINKED ISSUE #15157: `azurerm_subnet` resource `service_endpoints` ordering issue
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.92.0
```

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

keybase://private/speeddymon%2Chashicorp/vnet_module.tf - main.tf for a network module based on the `azurerm_virtual_network` resource, and using the below module to create subnets inside the vnet.

keybase://private/speeddymon%2Chashicorp/subnet_module.tf - main.tf for a module based on the `azurerm_subnet` resource.

Below is the code which uses the above `vnet_module.tf` file
```hcl
variable "svc_endpoints" {
  default = ["Microsoft.AzureCosmosDB", "Microsoft.EventHub", "Microsoft.KeyVault", "Microsoft.ServiceBus", "Microsoft.Sql", "Microsoft.Storage"]
}

module "network" {
  source  = redacted
  version = redacted

  vnet_name          = var.vnet_name
  vnet_address_space = var.vnet_address_space

  environment = var.environment
  product     = var.product
  owner       = var.owner
  region      = var.region

  rg_name                = var.rg_name
  create_ddos_protection = var.create_ddos_protection != null ? var.create_ddos_protection : true
  ddos_plan_name         = var.create_ddos_protection == true || var.create_ddos_protection == null ? "redacted" : null
  ddos_plan_id           = var.existing_ddos_plan_id != null ? var.existing_ddos_plan_id : null

  private_dns_zones = {
    "privatelink.blob.core.windows.net"  = "private-blob-storage-dns-to-cluster-subnet",
    "privatelink.servicebus.windows.net" = "private-eventhub-dns-to-cluster-subnet",
    "privatelink.vaultcore.azure.net"    = "private-keyvault-dns-to-cluster-subnet"
  }

  subnets = [{
    name     = var.subnet_name
    new_bits = 1,
    parameters = {
      svc_endpoints             = var.svc_endpoints,
      private_endpoints_enabled = var.private_endpoints_enabled
    }
  }]
}
```

### Expected Behaviour

No change
### Actual Behaviour
```
  # module.network.module.subnets.azurerm_subnet.default["redacted"] will be updated in-place
  ~ resource "azurerm_subnet" "default" {
        id                                             = "redacted"
        name                                           = "redacted"
      ~ service_endpoints                              = [
          - "Microsoft.Sql",
          - "Microsoft.Storage",
            "Microsoft.AzureCosmosDB",
          + "Microsoft.EventHub",
            "Microsoft.KeyVault",
            "Microsoft.ServiceBus",
          - "Microsoft.EventHub",
          + "Microsoft.Sql",
          + "Microsoft.Storage",
        ]
        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce

1. Reorder the above service endpoints in the variable's default value to be NOT in alphabetical order.
2. Run `terraform plan -out tfplan && terraform apply tfplan` to create a new subnet with the service endpoint list NOT defined in alphabetical order as far as the state file is concerned.
3. Run `terraform plan -out tfplan` a second time, or run `terraform state list` followed by copying and pasting the resource name from the state file into a `terraform state show` command.
4. Observe that the list in the state file is not in alphabetical order, but terraform reports that it will update the resource and reorder the endpoints in the state file to alphabetical order.
5. Run `terraform apply tfplan` and then `terraform plan -out tfplan` a third time.
6. Observe that the same change will happen again in the next plan output.
7. Reorder the variable in the hcl example above to be in alphabetical order again.
8. Re-run `terraform plan -out tfplan` and observe that even after reordering the variable's value locally and reapplying the plan, the endpoints are still out of order in the state file.
9. Re-run `terraform apply tfplan` and let the change happen
10. Run `terraform plan -out tfplan` one last time and confirm that the changes will STILL happen, thus indicating that the state file has not been updated.

It seems like the state file is not being updated by the subsequent plan and apply operations. Fortunately no azure resources are being destroyed and recreated, but it would be nice if the provider would detect that the endpoints are reordered upstream during the plan stage and automatically apply the update to the state file during the apply stage.

### References

* #0000

### PR DESCRIPTION
**Pull request by xiaxyi**
Api add the service endpoints following the sequence in the request body, which means, it doesn't respect the sequence that's being defined in the config, thus modifying the property from List to Set.

Addressing the GH issue：
1.https://github.com/hashicorp/terraform-provider-azurerm/issues/15157
2.https://github.com/hashicorp/terraform-provider-azurerm/issues/10087

acc tests:
```
--- PASS: TestAccSubnet_serviceEndpoints (1177.25s)
```

Fixes #15157
Fixes #10087

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @xiaxyi - you'll need to fix the data source now - it should not be a set and just return the order the API does as a computed list?

```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccDataSourceSubnet_basic
=== PAUSE TestAccDataSourceSubnet_basic
=== CONT  TestAccDataSourceSubnet_basic

------- Stderr: -------
panic: service_endpoints: '': source data must be an array or slice, got struct

goroutine 511 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc003cbfd80, {0x61611bc, 0x11}, {0x5d93380, 0xc00224afe0})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:230 +0x2a5
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.dataSourceSubnetRead(0x68, {0x5828a60, 0xc000a4ea80})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/network/subnet_data_source.go:129 +0xa88
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x613d8be, {0x69453f8, 0xc002246ec0}, 0xc00124de00, {0x5828a60, 0xc000a4ea80})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0011c5260, {0x69453f8, 0xc002246ec0}, 0xc003cbfc80, {0x5828a60, 0xc000a4ea80})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:569 +0xf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00254a000, {0x69453f8, 0xc002246ec0}, 0xc00224aa40)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:1133 +0x3a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0015ea180, {0x69454a0, 0xc00124c660}, 0xc004250820)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:478 +0x37b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x5d93220, 0xc0015ea180}, {0x69454a0, 0xc00124c660}, 0xc002336480, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0039b6000, {0x6996820, 0xc0023ec480}, 0xc00223bb00, 0xc001fb49f0, 0xb04ef10, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc0039b6000, {0x6996820, 0xc0023ec480}, 0xc00223bb00, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:938 +0x294
```

File: internal/services/network/subnet_data_source.go [hunk 1]
```diff
@@ -58,11 +58,12 @@ func dataSourceSubnet() *pluginsdk.Resource {
 			},
 
 			"service_endpoints": {
-				Type:     pluginsdk.TypeList,
+				Type:     pluginsdk.TypeSet,
```
Comment (tombuildsstuff) [inline internal/services/network/subnet_data_source.go:61]: a Data Source cannot be a Set, so this should be a List

```suggestion
				Type:     pluginsdk.TypeList,
```

File: internal/services/network/subnet_data_source.go [hunk 2]
```diff
@@ -58,11 +58,12 @@ func dataSourceSubnet() *pluginsdk.Resource {
...
 				Computed: true,
 				Elem: &pluginsdk.Schema{
 					Type: pluginsdk.TypeString,
 				},
+				Set: pluginsdk.HashString,
```
Comment (tombuildsstuff) [inline internal/services/network/subnet_data_source.go:66]:
```suggestion
```

File: internal/services/network/subnet_data_source.go [hunk 3]
```diff
@@ -125,7 +126,8 @@ func dataSourceSubnetRead(d *pluginsdk.ResourceData, meta interface{}) error {
 		}
 		d.Set("route_table_id", routeTableId)
 
-		if err := d.Set("service_endpoints", flattenSubnetServiceEndpoints(props.ServiceEndpoints)); err != nil {
+		serviceEndpoints := flattenSubnetServiceEndpoints(props.ServiceEndpoints)
+		if err := d.Set("service_endpoints", pluginsdk.NewSet(pluginsdk.HashString, serviceEndpoints)); err != nil {
```
Comment (tombuildsstuff) [inline internal/services/network/subnet_data_source.go:130]:
```suggestion
		if err := d.Set("service_endpoints", serviceEndpoints); err != nil {
```

File: internal/services/network/subnet_resource.go [hunk 4]
```diff
@@ -78,9 +78,10 @@ func resourceSubnet() *pluginsdk.Resource {
 			},
 
 			"service_endpoints": {
```
Comment (tombuildsstuff) [inline internal/services/network/subnet_resource.go:80]: since this is a breaking schema change, we need to make this conditionally a 3.0 thing:

```suggestion
			"service_endpoints": func() *pluginsdk.Schema {
				if !features.ThreePointOhBeta() {
					return &pluginsdk.Schema{
						Type: pluginsdk.TypeList,
						Optional: true,
 						Elem:     &pluginsdk.Schema{
 							Type: pluginsdk.TypeString,
 						},
					}
				}
				
				return &pluginsdk.Schema{
					Type: pluginsdk.TypeSet,
					Optional: true,
 					Elem:     &pluginsdk.Schema{
 						Type: pluginsdk.TypeString,
 					},
 					Set:      pluginsdk.HashString,
				}
			}(),
```

File: internal/services/network/subnet_resource.go [hunk 5]
```diff
@@ -230,7 +231,7 @@ func resourceSubnetCreate(d *pluginsdk.ResourceData, meta interface{}) error {
 	properties.PrivateEndpointNetworkPolicies = network.VirtualNetworkPrivateEndpointNetworkPolicies(expandSubnetPrivateLinkNetworkPolicy(privateEndpointNetworkPolicies))
 	properties.PrivateLinkServiceNetworkPolicies = network.VirtualNetworkPrivateLinkServiceNetworkPolicies(expandSubnetPrivateLinkNetworkPolicy(privateLinkServiceNetworkPolicies))
 
-	serviceEndpointsRaw := d.Get("service_endpoints").([]interface{})
+	serviceEndpointsRaw := d.Get("service_endpoints").(*pluginsdk.Set).List()
 	properties.ServiceEndpoints = expandSubnetServiceEndpoints(serviceEndpointsRaw)
```
Comment (tombuildsstuff) [inline internal/services/network/subnet_resource.go:235]: this'll need to be conditionally switched in 2.x/3.0 mode:

```suggestion
	if features.ThreePointOhBeta() {
		serviceEndpointsRaw := d.Get("service_endpoints").(*pluginsdk.Set).List()
		properties.ServiceEndpoints = expandSubnetServiceEndpoints(serviceEndpointsRaw)
	} else {
		serviceEndpointsRaw := d.Get("service_endpoints").([]interface{})
		properties.ServiceEndpoints = expandSubnetServiceEndpoints(serviceEndpointsRaw)
	}
```

File: internal/services/network/subnet_resource.go [hunk 6]
```diff
@@ -349,7 +350,7 @@ func resourceSubnetUpdate(d *pluginsdk.ResourceData, meta interface{}) error {
 	}
 
 	if d.HasChange("service_endpoints") {
-		serviceEndpointsRaw := d.Get("service_endpoints").([]interface{})
+		serviceEndpointsRaw := d.Get("service_endpoints").(*pluginsdk.Set).List()
 		props.ServiceEndpoints = expandSubnetServiceEndpoints(serviceEndpointsRaw)
```
Comment (tombuildsstuff) [inline internal/services/network/subnet_resource.go:354]: same here:

```suggestion
		if features.ThreePointOhBeta() {
			serviceEndpointsRaw := d.Get("service_endpoints").(*pluginsdk.Set).List()
			props.ServiceEndpoints = expandSubnetServiceEndpoints(serviceEndpointsRaw)
		} else {
			serviceEndpointsRaw := d.Get("service_endpoints").([]interface{})
			props.ServiceEndpoints = expandSubnetServiceEndpoints(serviceEndpointsRaw)
		}
```

File: internal/services/network/subnet_resource.go [hunk 7]
```diff
@@ -444,7 +445,7 @@ func resourceSubnetRead(d *pluginsdk.ResourceData, meta interface{}) error {
 		d.Set("enforce_private_link_service_network_policies", flattenSubnetPrivateLinkNetworkPolicy(string(props.PrivateLinkServiceNetworkPolicies)))
 
 		serviceEndpoints := flattenSubnetServiceEndpoints(props.ServiceEndpoints)
-		if err := d.Set("service_endpoints", serviceEndpoints); err != nil {
+		if err := d.Set("service_endpoints", pluginsdk.NewSet(pluginsdk.HashString, serviceEndpoints)); err != nil {
```
Comment (tombuildsstuff) [inline internal/services/network/subnet_resource.go:448]: fwiw we shouldn't need to set this explicitly, since we're using the default hash code here?

```suggestion
		if err := d.Set("service_endpoints", serviceEndpoints); err != nil {
```

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hi @xiaxyi 

Thanks for pushing those changes - I've taken a look through and left some more comments inline, since this is a breaking change (for users interpolating this field into another resource) we'll need to make this change conditionally in 2.x/3.0 mode.

Thanks!

File: internal/services/network/subnet_resource.go (hunk 4 above)
Comment (xiaxyi) [reply internal/services/network/subnet_resource.go:80]: Thanks Tom for making the suggestions. What about users who are currently using 2.x, are we going to leave things unchanged? would it be better to figure out another way than to change the schema to workaround this issue, for example, doing a sort before sending the request?

**Comment by xiaxyi** [comment]
Thanks @tombuildsstuff , updated

**Review by mbfrahry — APPROVED** [review]
LGTM!
