### PR TITLE
`azurerm_api_management_api` - change `id` format so specific `revision`s can be managed by Terraform

### LINKED ISSUE #12720: API Management - Cannot add a revision to an existing API
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```console
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.69.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)
* `azurerm_api_management_api`

### Terraform Configuration Files
Based on an existing revision:
```hcl
resource "azurerm_api_management_api" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  display_name        = "example"
  path                = "example"
  revision            = "1"
  protocols           = [
    "https",
  ]
  service_url         = "https://example.org"

  import {
    content_format = "openapi+json"
    content_value  = file("${path.module}/example.json")
  }
}
```
, create a new one:
```hcl
resource "azurerm_api_management_api" "example_2" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  display_name        = "example"
  path                = "example"
  revision            = "2"
  protocols           = [
    "https",
  ]
  service_url         = "https://example.org"

  import {
    content_format = "openapi+json"
    content_value  = file("${path.module}/example.json")
  }
}
```

### Expected Behaviour
Revision `2` created alongside `1`

### Actual Behaviour
```console
Error: waiting on creating/updating API Management API "example" (Resource Group "example"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=400 -- Original Error: Code="ValidationError" Message="Can't change property Name for non-current revision "
```

### Steps to Reproduce
1. `terraform apply`

### Additional information
If you try to create both at once, ie with:
```hcl
resource "azurerm_api_management_api" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  display_name        = "example"
  path                = "example"
  revision            = "1"
  protocols           = [
    "https",
  ]
  service_url         = "https://example.org"

  import {
    content_format = "openapi+json"
    content_value  = file("${path.module}/example.json")
  }
}

resource "azurerm_api_management_api" "example_2" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  display_name        = "example"
  path                = "example"
  revision            = "2"
  protocols           = [
    "https",
  ]
  service_url         = "https://example.org"

  import {
    content_format = "openapi+json"
    content_value  = file("${path.module}/example.json")
  }
}
}
```
, it works!
Revisions `1` & `2` are created.

### LINKED ISSUE #18093: creating an APIM revision results in error message Can't change property ApiVersion for non-current revision
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

2.84, 3.17.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api" "apim-api-env-api" {
    name                = "APISample"
    resource_group_name = azurerm_api_management.apim-env-api.resource_group_name
    api_management_name = azurerm_api_management.apim-env-api.name
    display_name        = "APISample"
    description         = "APISample"
    path                = "APISample"
    protocols           = ["https"]
    revision            = "1"
 
    import {
     content_format = "openapi+json"
     content_value  = file("swaggerFiles/suppliers-1.json")
    }


}
  
  
resource "azurerm_api_management_api" "apim-api-env-api2" {
    name                = "APISample"
    resource_group_name = azurerm_api_management.apim-env-api.resource_group_name
    api_management_name = azurerm_api_management.apim-env-api.name
    display_name        = "APISample"
    description         = "APISample"
    path                = "APISample"
    protocols           = ["https"]
    revision            = "2"
 
    import {
     content_format = "openapi+json"
     content_value  = file("swaggerFiles/suppliers-1.json")
    }


       depends_on = [azurerm_api_management_api.apim-api-env-api]


  }
```

### Debug Output/Panic Output

```shell
│ Error: waiting on creating/updating API Management API "APISample" (Resource Group "rg-sample-api"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=400 -- Original Error: Code="ValidationError" Message="Can't change property Name for non-current revision "
│
│   with azurerm_api_management_api.apim-api-env-api2,
│   on apim-env-api.tf line 94, in resource "azurerm_api_management_api" "apim-api-env-api2":
│   94:   resource "azurerm_api_management_api" "apim-api-env-api2" {
│
```

### Expected Behaviour

APIM API revision to be created in Azure portal, as per previous behaviour

### Actual Behaviour

HTTP 400 returned with message:  Can't change property Name for non-current revision

### Steps to Reproduce

1. Set environment variables for tracing 

TF_LOG="TRACE"
TF_LOG_PROVIDER="TRACE"
TF_LOG_PATH="c:\tmp\terraform.txt"

2. Two instances of azurerm_api_management_api declared

- azurerm_api_management_api.apim-api-env-api for the original API
- azurerm_api_management_api.apim-api-env-api**2** for the revision =2 
- Same  file used for imported swagger file
- Run terraform apply --auto-approve
- original API succeeds
- Revision = 2 fails with message:  Can't change property Name for non-current revision
- For both azurerm_api_management_api resources, the same swagger file is used

5. AzureRM v 2.84 and v.3.17.0  returns error 400:   Can't change property Name for non-current revision

6. Next, copy  PUT payload from terraform log file and submit via  https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/apis/create-or-update?tabs=HTTP#code-try-0

- Original API succeeds
- Revision API succeeds as well

 

 

   

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by mbfrahry**
Supersedes #22380

This is taking the existing work that was done by @kevjallen and smoothing out some of the edge cases around the `azurerm_api_management_api` and `azurerm_api_management_api_release` resources. 

Unfortunately, this resource is broken around revisions without a good path forward to fix existing issues. To fix issues around `revision` will require manual work by importing the revision in with the new id format

### CODE REVIEW

File: internal/services/apimanagement/migration/api_v0_to_v1.go [hunk 1]
```diff
@@ -0,0 +1,279 @@
...
+			Optional: true,
+		},
+	}
+
+	return schema
+}
+
+func (ApiV0ToV1) UpgradeFunc() pluginsdk.StateUpgraderFunc {
+	return func(ctx context.Context, rawState map[string]interface{}, meta interface{}) (map[string]interface{}, error) {
+		apiId := fmt.Sprintf("%s;rev=%s", rawState["name"], rawState["revision"])
```
Comment (stephybun) [inline internal/services/apimanagement/migration/api_v0_to_v1.go:269]: I think these need to be cast
```suggestion
		apiId := fmt.Sprintf("%s;rev=%s", rawState["name"].(string), rawState["revision"].(string))
```

**Review by stephybun — DISMISSED** [review]
Thanks @mbfrahry, minor comment otherwise LGTM 🌭

**Comment by kevjallen** [comment]
Any updates on this one?

**Comment by celsocoutinho-tangany** [comment]
Are there any plans to merge this PR?

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Review by tombuildsstuff — APPROVED** [review]

**Comment by celsocoutinho-tangany** [comment]
Can someone provide a working configuration on how to create new revisions on existing APIM APIs? It is not working for me...

**Comment by Andrei-Predoiu** [comment]
Has anyone come across this bug?
https://github.com/hashicorp/terraform-provider-azurerm/issues/25239
