### PR TITLE
`r\site_recovery_replicated_vm`: Fix issue of `create` depending on `update` timeout

### LINKED ISSUE #13725: waiting for site recovery to replicate vm: timeout while waiting for state to become 'Protected' (last state: 'UnprotectedStatesBegin', timeout: 1h20m0s)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v2.34.0
+ provider registry.terraform.io/hashicorp/azurerm v2.78.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

azurerm_site_recovery_replicated_vm

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_replicated_vm" "vm_replication" {
  count                                     = "${var.VM_Replication_Count}"
  depends_on                                = [ "azurerm_site_recovery_protection_container_mapping.container-mapping" ]
  name                                      = "${format("repl-%s-%s%d-replication", lower(var.customerid), lower(var.applicationenv),count.index+1)}"
  resource_group_name                       = "${var.dr_resource_group_name}"
  recovery_vault_name                       = "${var.dr_recovery_service_vault}"
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.policy.id

  source_recovery_fabric_name               = "${var.source_fabric_name}"
  source_vm_id                              = "${element(var.Virtual_Machine_resourceid, count.index)}"
  source_recovery_protection_container_name = "${var.source_protection_container_name}"

  target_resource_group_id                  = data.azurerm_resource_group.secondary.id
  target_recovery_fabric_id                 = "${var.target_fabric_id}"
  target_recovery_protection_container_id   = "${var.target_protection_container_id}"
  target_network_id                         = "${var.target_vnet_id}"

  managed_disk {
    disk_id                    = "${element(var.VM_OSdisk_resourceID, count.index)}"
    staging_storage_account_id = "${data.azurerm_storage_account.recovery_storage_account.id}"
    target_resource_group_id   = "${data.azurerm_resource_group.secondary.id}"
    target_disk_type           = "Standard_LRS" 
    target_replica_disk_type   = "Standard_LRS"
  }

  managed_disk {
    disk_id                    = "${element(var.VM_datadisk_resourceID, count.index)}"
    staging_storage_account_id = "${data.azurerm_storage_account.recovery_storage_account.id}"
    target_resource_group_id   = "${data.azurerm_resource_group.secondary.id}"
    target_disk_type           = "Premium_LRS"
    target_replica_disk_type   = "Premium_LRS"
    target_disk_encryption_set_id = "${var.dr_disk_encryption_id}"
  }

  network_interface {
      source_network_interface_id = "${element(var.Virtual_Machine_nics, count.index)}"
      target_static_ip = "${element(var.Virtual_Machine_IPs, count.index)}"
  }

  timeouts {
    create = "3h"
  }
}
```

### Expected Behaviour

The resource should be created successfully as the create timeout is 3 hours.  It appears that in the provider, this 3 hour is not taken into consideration when monitoring for the protected status. 

### Actual Behaviour

The resource creation fails after 1 hour 31 minute with the following error message;

Error: waiting for site recovery to replicate vm: timeout while waiting for state to become 'Protected' (last state: 'UnprotectedStatesBegin', timeout: 1h20m0s)

module.replicate[0].azurerm_site_recovery_replicated_vm.vm_replication[4]: Still creating... [1h31m11s elapsed]
module.replicate[0].azurerm_site_recovery_replicated_vm.vm_replication[4]: Still creating... [1h31m21s elapsed]

  on ../../../../../../terraform/modules/replicate/replicate.tf line 88, in resource "azurerm_site_recovery_replicated_vm" "vm_replication":
  88: resource "azurerm_site_recovery_replicated_vm" "vm_replication" {

### Steps to Reproduce

We have 128 GB OS disk and 300 GB data disk when we create the VM.  The synchronization of the machine in some cases takes more time and hence it doesn't turn into protected state in 1 hour and 20 mins timeout period.  

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by myc2h6o**
Fix #13725
- `create` internally calls `update` due to API limitation, and there is a long-running job in `update` waiting for `VMProtectionState` to become `Protected` (Fully replicated) during the first creation. Thus `timeouts.create` and `timeouts.update` both need a longer value when VM is large, which could cause confusion when a user does the first creation with only `timeouts.create` set to a longer value.
- This change tries removing the `timeouts.update` limitation in the `create`

### CODE REVIEW

**Comment by katbyte** [comment]
@myc2h6o - we should never be removing or disabling timeouts. instead of doing this can you move the parts of update required into the create function? we probably shouldn't be calling update from create anyways

**Comment by myc2h6o** [comment]
Hi @katbyte I've moved the common update parts into the new function `resourceSiteRecoveryReplicatedItemUpdateInternal`, `create` and `update` first set their own timeout and then call this common function.

File: internal/services/recoveryservices/site_recovery_replicated_vm_resource.go [hunk 1]
```diff
@@ -304,17 +304,20 @@ func resourceSiteRecoveryReplicatedItemCreate(d *pluginsdk.ResourceData, meta in
...
 	// We are not allowed to configure the NIC on the initial setup, and the VM has to be replicated before
 	// we can reconfigure. Hence this call to update when we create.
-	return resourceSiteRecoveryReplicatedItemUpdate(d, meta)
+	return resourceSiteRecoveryReplicatedItemUpdateInternal(ctx, d, meta)
 }
 
 func resourceSiteRecoveryReplicatedItemUpdate(d *pluginsdk.ResourceData, meta interface{}) error {
+	ctx, cancel := timeouts.ForUpdate(meta.(*clients.Client).StopContext, d)
+	defer cancel()
+	return resourceSiteRecoveryReplicatedItemUpdateInternal(ctx, d, meta)
```
Comment (myc2h6o) [inline internal/services/recoveryservices/site_recovery_replicated_vm_resource.go:313]: code to set update timeout has been moved here

File: internal/services/recoveryservices/site_recovery_replicated_vm_resource.go [hunk 2]
```diff
@@ -304,17 +304,20 @@ func resourceSiteRecoveryReplicatedItemCreate(d *pluginsdk.ResourceData, meta in
 
 	// We are not allowed to configure the NIC on the initial setup, and the VM has to be replicated before
 	// we can reconfigure. Hence this call to update when we create.
-	return resourceSiteRecoveryReplicatedItemUpdate(d, meta)
+	return resourceSiteRecoveryReplicatedItemUpdateInternal(ctx, d, meta)
 }
 
 func resourceSiteRecoveryReplicatedItemUpdate(d *pluginsdk.ResourceData, meta interface{}) error {
+	ctx, cancel := timeouts.ForUpdate(meta.(*clients.Client).StopContext, d)
+	defer cancel()
```
Comment (myc2h6o) [inline internal/services/recoveryservices/site_recovery_replicated_vm_resource.go:312]: code to set update timeout has been moved here

**Review by katbyte — APPROVED** [review]
Thanks @myc2h6o - LGTM 🦀
