### PR TITLE
Data source: `azurerm_container_app_environment`: Support log analytics workspaces in different subscriptions for data source

### LINKED ISSUE #25514: azurerm_container_app_environment throws error when log analytics workspace located in different subscription
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Terraform Configuration Files

```hcl
data "azurerm_container_app_environment" "app_env" {
  name                = "my-aca-env"
  resource_group_name = "aca-rg"
}
```

### Debug Output/Panic Output

```shell
│ Error: retrieving Log Analytics Workspace: no matching workspace found
│ 
│   with data.azurerm_container_app_environment.app_env,
│   on data.tf line 44, in data "azurerm_container_app_environment" "app_env":
│   44: data "azurerm_container_app_environment" "app_env" {
│ 
│ retrieving Log Analytics Workspace: no matching workspace found
```

### Expected Behaviour

Data source should be propagated successfully without error.

### Actual Behaviour

`azurerm_container_app_environment` data source throws error when log analytics workspace assigned to Azure Container Apps environment (`Monitoring` -> `Logging options` -> `Logs Destination` -> `Azure Log Analytics`) is located in different subscription. The last working version of provider is 3.73.0, bug was introduced in https://github.com/hashicorp/terraform-provider-azurerm/pull/23298, 3.74.0 and newer versions are affected.

### Steps to Reproduce

1. Create Azure Container Apps environment with assigned log analytics workspace from different subscription than environment (same tenant)
2. Attach its name and resource group name to `azurerm_container_app_environment` data source 
3. `terraform plan`

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/23298

### PR DESCRIPTION
**Pull request by dylan8902**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

No longer throw an error for a valid Log Analytics Workspace `customerId` not in the same subscription as the container app environment. Return an empty name.

I can't think of any use case for throwing an error in this data source if an existing resource exists that is configured correctly. If the workspace name cannot be found in the CAE subscription then never mind, just leave it blank.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

I have not written a unit test for this scenario - it might be useful. Would need someone to suggest a way of mocking the client in the function though please. I note the function's other code branches have not yet got any tests as far as I could find.

I have tested the updated provider locally and it works successfully with a container app environment configured with a log analytics workspace from another subscription:

```sh
terraform state show data.azurerm_container_app_environment.test
# data.azurerm_container_app_environment.test:
data "azurerm_container_app_environment" "test" {
    custom_domain_verification_id    = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    default_domain                   = "test-a00a0aa0.uksouth.azurecontainerapps.io"
    docker_bridge_cidr               = null
    id                               = "/subscriptions/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/resourceGroups/test/providers/Microsoft.App/managedEnvironments/test"
    infrastructure_subnet_id         = "/subscriptions/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/resourceGroups/test/providers/Microsoft.Network/virtualNetworks/test/subnets/test"
    internal_load_balancer_enabled   = false
    location                         = "uksouth"
    log_analytics_workspace_name     = null
    name                             = "test"
    platform_reserved_cidr           = null
    platform_reserved_dns_ip_address = null
    resource_group_name              = "test"
    static_ip_address                = "xxx.xxx.xxx.xxx"
    tags                             = {}
}
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* Data source `azurerm_container_app_environment` - support log analytics workspaces in different subscriptions [GH-25514]

This is a (please select all that apply):

- [X] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25514

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/containerapps/container_app_environment_data_source.go [hunk 1]
```diff
@@ -72,7 +72,7 @@ func (r ContainerAppEnvironmentDataSource) Attributes() map[string]*pluginsdk.Sc
 		"log_analytics_workspace_name": {
 			Type:        pluginsdk.TypeString,
 			Computed:    true,
-			Description: "The name of the Log Analytics Workspace this Container Apps Managed Environment is linked to.",
+			Description: "The name of the Log Analytics Workspace this Container Apps Managed Environment is linked to. (Only available if workspace is in same subscription)",
```
Comment (catriona-m) [inline internal/services/containerapps/container_app_environment_data_source.go:75]: could we add this as a note in the docs instead?

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks for fixing this @dylan8902 - I left one minor comment about adding a Note in the docs, but otherwise this looks good. Thanks!
