### PR TITLE
`azurerm_postgresql_flexible_server` - add support for `17` in the `version` property

### LINKED ISSUE #29998: Unable to create postgresql 17 version for PostgreSQL flexible server
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

4.33.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "psql" {
  name                   = test
  resource_group_name    = test
  location               = westus
  version                = 17
  administrator_login    = psqladmin
  administrator_password = random_password.administrator_login_password.result
  .......
}
```

### Debug Output/Panic Output

```shell
Error: expected version to be one of ["15" "14" "11" "16" "13" "12"], got 17
│ 
│   with module.sharedinfra.module.psql_synopsys[0].azurerm_postgresql_flexible_server.psql,
│   on .terraform/modules/sharedinfra.psql_synopsys/main.tf line 20, in resource "azurerm_postgresql_flexible_server" "psql":
│   20:   version                = var.pg_version
│
```

### Expected Behaviour

It should create psql server with 17 version

### Actual Behaviour

Failing with error, expected version to be one of ["15" "14" "11" "16" "13" "12"], got 17

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by catriona-m**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
=== RUN   TestAccPostgresqlFlexibleServer_version17
=== PAUSE TestAccPostgresqlFlexibleServer_version17
=== CONT  TestAccPostgresqlFlexibleServer_version17
--- PASS: TestAccPostgresqlFlexibleServer_version17 (433.13s)
PASS
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29998

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 1]
```diff
@@ -171,10 +171,18 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
...
+				Optional: true,
+				Computed: true,
+				ValidateFunc: validation.StringInSlice([]string{
+					string(servers.ServerVersionOneFive),
+					string(servers.ServerVersionOneFour),
+					string(servers.ServerVersionOneOne),
+					string(servers.ServerVersionOneSix),
+					string(servers.ServerVersionOneThree),
+					string(servers.ServerVersionOneTwo),
+					"17", // version 17 is supported but not yet present as an enum in the SDK
```
Comment (sreallymatt) [inline internal/services/postgres/postgresql_flexible_server_resource.go:184]: Will need to be added to the docs

Comment (catriona-m) [reply internal/services/postgres/postgresql_flexible_server_resource.go:184]: oops! done now 👍
