### PR TITLE
`azurerm_network_security_{group|rule}` - Setting correct casing `protocol` to state

### LINKED ISSUE #16092: r/network_security_group - the `protocol` casing change is missing from the 3.0 upgrade guide doc
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2

### Affected Resource(s)

* `azurerm_network_security_group`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
In security_rule, my rules have protocol TCP:

protocol                                   = "TCP"

This reflects the situation in the Azure Backend, where the resource provider set the protocol to TCP in capital letters.

### Expected Behaviour

Microsoft set the protocol parameter of my network security rules to "TCP" (with capital letters).
It used to be ok until AzureRM 2.99.0 included

Since AzureARM 3.0.*, I get the following error message when running terraform plan:

terraform plan

Error: expected security_rule.1.protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP

### Actual Behaviour

AzureRM should have accepted TCP as a valid protocol since the Azure resource provider accepts 'TCP' in capital letters.

AzureRM used to work properly. Something has changed since 2.99.0

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by magodo**
Fix #16092

### CODE REVIEW

File: internal/services/network/network_security_group_resource.go [hunk 1]
```diff
@@ -447,7 +455,7 @@ func flattenNetworkSecurityRules(rules *[]network.SecurityRule) []map[string]int
 					sgRule["source_port_ranges"] = set.FromStringSlice(*props.SourcePortRanges)
 				}
 
-				sgRule["protocol"] = string(props.Protocol)
+				sgRule["protocol"] = string(protocolMap[strings.ToLower(string(props.Protocol))])
```
Comment (tombuildsstuff) [inline internal/services/network/network_security_group_resource.go:458]: just an FYI - there's a Pandora PR to normalize this by default we'll be rolling out in the future too: https://github.com/hashicorp/pandora/pull/758

**Review by tombuildsstuff — APPROVED** [review]
One FYI but this otherwise LGTM if the tests pass 👍

**Comment by stephybun** [comment]
Tests look good
