### PR TITLE
azurerm_linux_web_app  - support 8.3 for the php_version property

### LINKED ISSUE #26121: php_version missing 8.3
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

3.105.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "webapp" {
  name                = "webapp-php-83"
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = azurerm_service_plan.asp.location
  service_plan_id     = azurerm_service_plan.asp.id
  site_config {
    application_stack {
      php_version = "8.3"
    }
  }
}
```

### Debug Output/Panic Output

```shell
sorry, cannot, reveals sensitive information
```

### Expected Behaviour

Create azurerm_linux_web_app with PHP 8.3 runtime

PHP version 8.3 is valid for Azure App Service with PHP runtime:
PS> az webapp list-runtimes --os linux
...
  "PHP:8.3",
  "PHP:8.2",
  "PHP:8.1",
  "PHP:8.0",
...

### Actual Behaviour

Plan: 0 to add, 6 to change, 0 to destroy.
╷
│ Error: expected site_config.0.application_stack.0.php_version to be one of ["7.4" "8.0" "8.1" "8.2"], got 8.3
│
│   with azurerm_linux_web_app.webapp,
│   on app.tf line 34, in resource "azurerm_linux_web_app" "webapp":
│   34:       php_version = "8.3"
│
╵

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by Chambras**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Adding support for PHP 8.3 in Linux Web Apps and Linux WebApp Slot.
Updated documentation with new version support.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

Linux WebApp test log:

```bash
$ make acctests SERVICE='appservice' TESTARGS=' -run=TestAccLinuxWebApp_withPhp83' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/appservice -run=TestAccLinuxWebApp_withPhp83 -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccLinuxWebApp_withPhp83
=== PAUSE TestAccLinuxWebApp_withPhp83
=== CONT  TestAccLinuxWebApp_withPhp83
--- PASS: TestAccLinuxWebApp_withPhp83 (138.99s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    139.010s
```

Linuz WebApp Slot test log:

```bash
$ make acctests SERVICE='appservice' TESTARGS=' -run=TestAccLinuxWebAppSlot_withPhp83' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/appservice -run=TestAccLinuxWebAppSlot_withPhp83 -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccLinuxWebAppSlot_withPhp83
=== PAUSE TestAccLinuxWebAppSlot_withPhp83
=== CONT  TestAccLinuxWebAppSlot_withPhp83
--- PASS: TestAccLinuxWebAppSlot_withPhp83 (223.50s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    223.519s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_linux_web_app` - support for `PHP 8.3`
* `azurerm_linux_web_app_slot` - support for `PHP 8.3`

This is a (please select all that apply):

- [ ] Bug Fix
- [X] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #26121

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/appservice/linux_web_app_slot_resource_test.go [hunk 1]
```diff
@@ -2972,10 +2990,12 @@ resource "azurerm_service_plan" "test" {
...
-  name                = "acctestWA-%[1]d"
-  location            = azurerm_resource_group.test.location
-  resource_group_name = azurerm_resource_group.test.name
-  service_plan_id     = azurerm_service_plan.test.id
+  name                                           = "acctestWA-%[1]d"
+  location                                       = azurerm_resource_group.test.location
+  resource_group_name                            = azurerm_resource_group.test.name
+  service_plan_id                                = azurerm_service_plan.test.id
+  ftp_publish_basic_authentication_enabled       = false
+  webdeploy_publish_basic_authentication_enabled = false
```
Comment (stephybun) [inline internal/services/appservice/linux_web_app_slot_resource_test.go:2998]: Since this is a base template we shouldn't be setting any `Optional` properties in here
```suggestion
```

File: internal/services/appservice/linux_web_app_slot_resource_test.go [hunk 2]
```diff
@@ -2469,8 +2484,10 @@ provider "azurerm" {
 %s
 
 resource "azurerm_linux_web_app_slot" "test" {
-  name           = "acctestWAS-%d"
-  app_service_id = azurerm_linux_web_app.test.id
+  name                                           = "acctestWAS-%d"
+  app_service_id                                 = azurerm_linux_web_app.test.id
+  ftp_publish_basic_authentication_enabled       = false
+  webdeploy_publish_basic_authentication_enabled = false
```
Comment (stephybun) [inline internal/services/appservice/linux_web_app_slot_resource_test.go:2490]: Why are these being set in the php template?

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @Chambras. Overall this looks fine, just the additional settings in the test templates are problematic, we shouldn't be changing test configs and setting additional properties that are unrelated to the change at hand. Could you please provide some context here?

File: internal/services/appservice/linux_web_app_slot_resource_test.go (hunk 2 above)
Comment (Chambras) [reply internal/services/appservice/linux_web_app_slot_resource_test.go:2490]: I want to see how the tests come up. I think it was because those get set by default when you create it, and when I Was running the tests, it was failing because of these.

**Comment by Chambras** [comment]
Thanks for the feedback @stephybun removed the extra properties in the template and all checks passed :)

File: internal/services/appservice/linux_web_app_slot_resource_test.go (hunk 2 above)
Comment (stephybun) [reply internal/services/appservice/linux_web_app_slot_resource_test.go:2490]: The PHP tests are passing on our side without these properties, so these should also be removed 
```suggestion
```

**Review by stephybun — CHANGES_REQUESTED** [review]

File: internal/services/appservice/linux_web_app_slot_resource_test.go (hunk 2 above)
Comment (Chambras) [reply internal/services/appservice/linux_web_app_slot_resource_test.go]: Thanks @stephybun missed that one. Should be done now :)

**Review by katbyte — APPROVED** [review]
LGTM 🌩️
